PACKAGE REPORT IS
PROCEDURE TEST(NAME:STRING;DESC:STRING);
PROCEDURE FAILED(MSG:STRING);
PROCEDURE RESULT;
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN;
END REPORT;
PACKAGE BODY REPORT IS
PROCEDURE TEST(NAME:STRING;DESC:STRING)IS BEGIN NULL;END TEST;
PROCEDURE FAILED(MSG:STRING)IS BEGIN NULL;END FAILED;
PROCEDURE RESULT IS BEGIN NULL;END RESULT;
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER IS BEGIN RETURN X;END IDENT_INT;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN IS BEGIN RETURN X;END IDENT_BOOL;
END REPORT;
