WITH TEXT_IO;USE TEXT_IO;
PACKAGE REPORT IS
PROCEDURE TEST(NAME:STRING;DESC:STRING);
PROCEDURE FAILED(MSG:STRING);
PROCEDURE RESULT;
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN;
FUNCTION IDENT_CHAR(X:CHARACTER)RETURN CHARACTER;
FUNCTION IDENT_STR(X:STRING)RETURN STRING;
END REPORT;
PACKAGE BODY REPORT IS
F:INTEGER:=0;
PROCEDURE TEST(NAME:STRING;DESC:STRING)IS BEGIN PUT_LINE("TEST "&NAME&": "&DESC);F:=0;END TEST;
PROCEDURE FAILED(MSG:STRING)IS BEGIN PUT_LINE("FAILED: "&MSG);F:=1;END FAILED;
PROCEDURE RESULT IS BEGIN IF F=0 THEN PUT_LINE("PASS");ELSE PUT_LINE("FAIL");END IF;END RESULT;
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER IS BEGIN RETURN X;END IDENT_INT;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN IS BEGIN RETURN X;END IDENT_BOOL;
FUNCTION IDENT_CHAR(X:CHARACTER)RETURN CHARACTER IS BEGIN RETURN X;END IDENT_CHAR;
FUNCTION IDENT_STR(X:STRING)RETURN STRING IS BEGIN RETURN X;END IDENT_STR;
END REPORT;
