PACKAGE REPORT IS
PROCEDURE TEST(NAME:STRING;DESC:STRING);
PROCEDURE FAILED(MSG:STRING);
PROCEDURE RESULT;
PROCEDURE COMMENT(MSG:STRING);
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN;
FUNCTION IDENT_CHAR(X:CHARACTER)RETURN CHARACTER;
FUNCTION IDENT_STR(X:STRING)RETURN STRING;
FUNCTION EQUAL(X,Y:INTEGER)RETURN BOOLEAN;
LEGAL_FILE_NAME:CONSTANT STRING:="test_file.tmp";
LEGAL_FILE_NAME_2:CONSTANT STRING:="test_file_2.tmp";
PROCEDURE NOT_APPLICABLE(DESCR:STRING);
MAX_IN_LEN:CONSTANT INTEGER:=1000;
VARIABLE_ADDRESS:CONSTANT INTEGER:=0;
END REPORT;
