PACKAGE BODY SEQUENTIAL_IO IS
SUBTYPE COUNT IS INTEGER RANGE 0..INTEGER'LAST;
TYPE ELEMENT_ARRAY IS ARRAY(POSITIVE RANGE<>)OF ELEMENT_TYPE;
TYPE FILE_INFO IS RECORD
FD:INTEGER;
M:FILE_MODE;
POS:COUNT;
OPEN:BOOLEAN;
EOF:BOOLEAN;
END RECORD;
TYPE FILE_TABLE IS ARRAY(0..15)OF FILE_INFO;
TYPE BUFFER_ARRAY IS ARRAY(0..15)OF ELEMENT_ARRAY(1..1000);
FILES:FILE_TABLE;
BUFFERS:BUFFER_ARRAY;
BUFFER_SIZES:ARRAY(0..15)OF COUNT;
NEXT_FD:INTEGER:=3;
PROCEDURE CREATE(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE:=OUT_FILE;NAME:IN STRING:="";FORM:IN STRING:="")IS
BEGIN
IF NEXT_FD>15 THEN RAISE USE_ERROR;END IF;
FILES(NEXT_FD):=(NEXT_FD,MODE,0,TRUE,FALSE);
FILE:=FILE_TYPE(NEXT_FD);
NEXT_FD:=NEXT_FD+1;
END CREATE;
PROCEDURE OPEN(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE;NAME:IN STRING;FORM:IN STRING:="")IS
BEGIN
IF NEXT_FD>15 THEN RAISE USE_ERROR;END IF;
FILES(NEXT_FD):=(NEXT_FD,MODE,0,TRUE,FALSE);
FILE:=FILE_TYPE(NEXT_FD);
NEXT_FD:=NEXT_FD+1;
END OPEN;
PROCEDURE CLOSE(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).OPEN:=FALSE;END IF;
END CLOSE;
PROCEDURE DELETE(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN FILES(I).OPEN:=FALSE;END IF;
END DELETE;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE;MODE:IN FILE_MODE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
FILES(I).M:=MODE;
FILES(I).POS:=0;
FILES(I).EOF:=FALSE;
END IF;
END RESET;
PROCEDURE RESET(FILE:IN OUT FILE_TYPE)IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
FILES(I).POS:=0;
FILES(I).EOF:=FALSE;
END IF;
END RESET;
FUNCTION MODE(FILE:IN FILE_TYPE)RETURN FILE_MODE IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
RETURN FILES(I).M;
END IF;
RETURN IN_FILE;
END MODE;
FUNCTION NAME(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END NAME;
FUNCTION FORM(FILE:IN FILE_TYPE)RETURN STRING IS BEGIN RETURN "";END FORM;
FUNCTION IS_OPEN(FILE:IN FILE_TYPE)RETURN BOOLEAN IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN RETURN FILES(I).OPEN;END IF;
RETURN FALSE;
END IS_OPEN;
PROCEDURE READ(FILE:IN FILE_TYPE;ITEM:OUT ELEMENT_TYPE)IS
I:INTEGER:=INTEGER(FILE);
P:COUNT;
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
IF FILES(I).M=OUT_FILE THEN RAISE MODE_ERROR;END IF;
P:=FILES(I).POS;
IF P>BUFFER_SIZES(I) THEN FILES(I).EOF:=TRUE;RAISE END_ERROR;END IF;
ITEM:=BUFFERS(I)(POSITIVE(P));
FILES(I).POS:=FILES(I).POS+1;
END IF;
END READ;
PROCEDURE WRITE(FILE:IN FILE_TYPE;ITEM:IN ELEMENT_TYPE)IS
I:INTEGER:=INTEGER(FILE);
P:COUNT;
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
IF FILES(I).M=IN_FILE THEN RAISE MODE_ERROR;END IF;
P:=FILES(I).POS;
IF P<=1000 THEN
BUFFERS(I)(POSITIVE(P)):=ITEM;
IF P>BUFFER_SIZES(I) THEN BUFFER_SIZES(I):=P;END IF;
FILES(I).POS:=FILES(I).POS+1;
END IF;
END IF;
END WRITE;
FUNCTION END_OF_FILE(FILE:IN FILE_TYPE)RETURN BOOLEAN IS
I:INTEGER:=INTEGER(FILE);
BEGIN
IF I>=0 AND I<16 THEN
IF NOT FILES(I).OPEN THEN RAISE STATUS_ERROR;END IF;
RETURN FILES(I).EOF;
END IF;
RETURN TRUE;
END END_OF_FILE;
BEGIN
FOR I IN 0..15 LOOP
FILES(I):=(-1,IN_FILE,1,FALSE,TRUE);
BUFFER_SIZES(I):=0;
END LOOP;
FILES(0):=(0,IN_FILE,1,TRUE,FALSE);
FILES(1):=(1,OUT_FILE,1,TRUE,FALSE);
FILES(2):=(2,OUT_FILE,1,TRUE,FALSE);
END SEQUENTIAL_IO;
