PACKAGE SYSTEM IS
TYPE ADDRESS IS PRIVATE;
TYPE NAME IS(PRIORITY);
MIN_INT:CONSTANT:=-(2**31);MAX_INT:CONSTANT:=2**31-1;
MAX_DIGITS:CONSTANT:=15;MAX_MANTISSA:CONSTANT:=31;
FINE_DELTA:CONSTANT:=2.0**(-31);TICK:CONSTANT:=0.01;
STORAGE_UNIT:CONSTANT:=8;MEMORY_SIZE:CONSTANT:=2**31;
SYSTEM_NAME:CONSTANT NAME:=PRIORITY;
SUBTYPE PRIORITY IS INTEGER RANGE 0..7;
PROCEDURE RT_PUTC(C:INTEGER);
PRIVATE
TYPE ADDRESS IS NEW INTEGER;
END SYSTEM;
