-- A22006E.ADA

-- CHECK THAT A COMPILATION MAY BE FOLLOWED BY EXTRA LINES
-- (INCLUDING LINES TERMINATED BY FORMAT EFFECTORS OTHER
--  THAN HORIZONTAL TABULATION).

-- NOTE: THIS FILE ENDS WITH:
--       1) AN EMPTY LINE
--       2) A CARRIAGE RETURN CHARACTER       (ASCII 13. = 0D HEX)
--       3) A CARRIAGE RETURN CHARACTER       (ASCII 13. = 0D HEX)
--       4) A VERTICAL TABULATION CHARACTER   (ASCII 11. = 0B HEX)
--       5) A LINE FEED CHARACTER             (ASCII 10. = 0A HEX)
--       6) A LINE FEED CHARACTER             (ASCII 10. = 0A HEX)
--       7) A FORM FEED CHARACTER             (ASCII 12. = 0C HEX)

-- PWB  2/13/86

WITH REPORT;
USE  REPORT;

PROCEDURE A22006E IS
BEGIN
     TEST ("A22006E", "CHECK THAT A COMPILATION CAN BE FOLLOWED BY " &
                      "EXTRA LINES");
     RESULT;
END A22006E;




