-- A22006B.ADA

-- CHECK THAT HORIZONTAL TABULATION CAN BE USED WITHIN AND OUTSIDE OF
-- COMMENTS.

-- JBG 5/26/85

WITH REPORT; USE REPORT;
PROCEDURE A22006B IS
BEGIN
	TEST ("A22006B", "CHECK USE OF HT IN AND OUT OF COMMENTS");
     -- PRECEDING LINE CONTAINED A LEADING HT
     -- NEXT LINE CONTAINS A TAB INSIDE A COMMENT
     -- HERE IS HT =>	<= CHARACTER IN A COMMENT
     RESULT;	-- TAB PRECEDES THIS COMMENT
END A22006B;
