-- A22006F.ADA

-- CHECK THAT A COMPILATION CAN BE FOLLOWED BY SPACES AND
-- HORIZONTAL TABULATION CHARACTERS.

-- NOTE: THE LAST LINE OF THIS FILE ENDS WITH FOUR SPACE
--       CHARACTERS AND A HORIZONTAL TABULATION CHARACTER

-- PWB  2/13/86

WITH REPORT;
USE  REPORT;

PROCEDURE A22006F IS
BEGIN
     TEST ("A22006F", "CHECK THAT A COMPILATION CAN BE FOLLOWED " &
                      "BY SPACE AND HORIZONTAL TABULATION CHARACTERS");
     RESULT;
END A22006F;    	
