-- A27003A.ADA

-- CHECK THAT IN A STRING LITERAL, CONSECUTIVE HYPHENS
-- ARE PERMITTED WITHOUT INDICATING A COMMENT,
-- AND THAT IN A COMMENT, A SINGLE DOUBLE-QUOTE IS
-- PERMITTED WITHOUT INDICATING A STRING LITERAL.

-- PWB  03/04/86

WITH REPORT; USE REPORT;
PROCEDURE A27003A IS

     -- COMMENT :  "  IS PERMITTED HERE.

     STR1 : CONSTANT STRING := "AB--C";
     STR2 : STRING (1..10);

BEGIN

     TEST ("A27003A", "CONSECUTIVE HYPHENS PERMITTED IN " &
                      "STRING LITERAL, AND QUOTE PERMITTED " &
                      "IN COMMENT");

     STR2 := STR1 & "--ABC";
     -- COMMENT : " IS PERMITTED HERE.

     RESULT;

END A27003A;
