PRAGMA SYSTEM_NAME (BOOLEAN);
PRAGMA MEMORY_SIZE (CHARACTER);
PRAGMA STORAGE_UNIT (STRING);

-- A28002C.ADA

-- CHECK THAT A PREDEFINED OR AN UNRECOGNIZED PRAGMA MAY HAVE ARGUMENTS
-- INVOLVING DECLARED IDENTIFIERS THAT ARE USED INCORRECTLY.

-- TBN 2/24/86

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (INTEGER);

PROCEDURE A28002C IS

     SUBTYPE MY_INT IS INTEGER RANGE 1 .. 4;
     PRAGMA CONTROLLED (MY_INT);

     AAAAAAA : INTEGER := 0;
     ZZZZ : INTEGER := 1;
     PRAGMA INLINE (AAAAAAA);
     PRAGMA INTERFACE (ZZZZ, AAAAAAA);

     TYPE ARRAY1 IS ARRAY (1 .. 2) OF INTEGER;
     ARRAY_OBJ : ARRAY1;
     MAYBE : BOOLEAN := TRUE;
     PROCEDURE FUN (A : INTEGER) IS 
     BEGIN
          NULL;
     END;

     PRAGMA OPTIMIZE (AAAAAAA > ZZZZ);
     PRAGMA PACK (ARRAY1 (1,2));
     PRAGMA PRIORITY (MAYBE);
     PRAGMA SHARED (ARRAY_OBJ);

     PACKAGE P IS
     END P;

     PRAGMA SUPPRESS (RANGE_CHECK, P);
     PRAGMA PHIL_BRASHEAR (MAYBE);

BEGIN
     TEST ("A28002C", "CHECK THAT A PREDEFINED OR AN UNRECOGNIZED " &
                      "PRAGMA MAY HAVE ARGUMENTS INVOLVING DECLARED " &
                      "IDENTIFIERS THAT ARE USED INCORRECTLY.");

     PRAGMA LIST (FUN(ZZZZ));
     PRAGMA PAGE (AAAAAAA);
     PRAGMA ROSA_WILLIAMS (AAAAAAA);
     PRAGMA THOMAS_NORRIS (ZZZZ);
     RESULT;

END A28002C;
