-- A28006D1.TST

-- OBJECTIVE:
--     CHECK THAT THE PRESENCE OF A PRAGMA INCLUDE DOES NOT CAUSE AN
--     OTHERWISE LEGAL PROGRAM TO BECOME ILLEGAL.

-- THIS FILE IS THE PARAMETER OF THE PRAGMA INCLUDE IN THE TEST
-- A28006D0M.TST.  IF THE PRAGMA IS SUPPORTED, THIS PROCEDURE CAUSES
-- COMPILATION ERRORS IN THE TEST.

-- HISTORY:
--     BCB 08/10/88  CREATED ORIGINAL TEST.

PROCEDURE A28006D1 (A : INTEGER) IS
BEGIN
     FAILED ("AMBIGUITY NOT DETECTED");
END A28006D1;
