-- A28004A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENTITY WITH THE NAME OF A PREDEFINED PRAGMA CAN BE
--     DECLARED AND THAT THE ENTITY DOES NOT HIDE THE PRAGMA.

-- HISTORY:
--     TBN 07/11/86  CREATED ORIGINAL TEST.
--     BCB 10/21/87  CHANGED HEADER TO STANDARD FORMAT.  REMOVED THE
--                   CONSTANT 'PFIRST'.  REPLACED THE SUBPROGRAM NAME
--                   THAT IS AN ARGUMENT OF PRAGMA INTERFACE.

WITH REPORT, SYSTEM;
USE REPORT, SYSTEM;
PROCEDURE A28004A IS

     PRIORITY : INTEGER := 1;
     PRAGMA PRIORITY (SYSTEM.PRIORITY'FIRST);

     INTERFACE : INTEGER := 0;

     FUNCTION MEMORY_SIZE (X : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN IDENT_INT (1);
     END MEMORY_SIZE;

     PRAGMA INTERFACE (ZZZZZZ, TEST_VAR);

     PROCEDURE SYSTEM_NAME (NAME : STRING) IS
     BEGIN
          NULL;
     END SYSTEM_NAME;

BEGIN
     TEST ("A28004A", "CHECK THAT AN ENTITY WITH THE NAME OF A " &
                      "PREDEFINED PRAGMA CAN BE DECLARED AND THAT " &
                      "THE ENTITY DOES NOT HIDE THE PRAGMA");

     DECLARE     --(A)

          SUBTYPE STORAGE_UNIT IS INTEGER RANGE 1 .. 10;

          ELABORATE : INTEGER := 1;

          TYPE OPTIMIZE IS (TIME, SPACE);

          PRAGMA OPTIMIZE (TIME);

          CONTROLLED : CHARACTER := 'A';
          TYPE CELL;
          TYPE LINK IS ACCESS CELL;
          TYPE CELL IS
               RECORD
                    VALUE : INTEGER := 2;
               END RECORD;

          PRAGMA CONTROLLED (LINK);

          GLOBAL : INTEGER := 5;
          PACK : CHARACTER := 'P';

          PRAGMA PACK (CELL);

          SHARED : CELL;

          PRAGMA SHARED (GLOBAL);

          TYPE SUPPRESS IS ARRAY (1..10) OF CHARACTER;
          ARA : SUPPRESS;

          PRAGMA SUPPRESS (RANGE_CHECK, ARA);

          TYPE LIST IS (ON, OFF);
          PAGE : CHARACTER := 'A';

          FUNCTION INLINE (X : INTEGER) RETURN BOOLEAN IS
          BEGIN
               RETURN (IDENT_BOOL (TRUE));
          END INLINE;

          PRAGMA INLINE (INLINE);

     BEGIN     --(A)
          PRAGMA LIST (ON);
          PRAGMA PAGE;
          NULL;
     END;     --(A)

     RESULT;
END A28004A;
