-- A35101B.ADA

-- CHECK THAT ONE ENUMERATION LITERAL IS PERMITTED IN AN ENUMERATION
-- TYPE DEFINITION.

-- RJW 2/14/86

WITH REPORT; USE REPORT;

PROCEDURE A35101B IS

BEGIN

     TEST ("A35101B", "CHECK THAT ONE ENUMERATION LITERAL IS " &
                      "PERMITTED IN AN ENUMERATION TYPE " &
                      "DEFINITION" );
     DECLARE

          TYPE E1 IS (A);                         -- OK.
          TYPE E2 IS ('1');                       -- OK.

     BEGIN
          NULL;
     END;

     RESULT;

END A35101B;
