-- A35710A.ADA

-- OBJECTIVE:
--     CHECK THAT THE BASE TYPE IS DETERMINED PARTLY BY THE RANGE GIVEN
--     IN THE TYPE DECLARATION.

-- HISTORY:
--     RJW 3/06/86  CREATED ORIGINAL TEST.
--     RJW 7/22/88  RENAMED FOR C35710A.ADA. FORMATTED HEADER.

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;

PROCEDURE A35710A IS

BEGIN

     TEST ("A35710A", "CHECK THAT THE BASE TYPE IS DETERMINED " &
                      "PARTLY BY THE RANGE GIVEN IN THE TYPE " &
                      "DECLARATION");

     DECLARE
          TYPE REAL IS DIGITS MAX_DIGITS;
          TYPE F1 IS DIGITS 1 RANGE REAL'SAFE_SMALL .. REAL'SAFE_LARGE;
          TYPE F2 IS DIGITS 1 RANGE -1.0 .. 1.0;

     BEGIN
          COMMENT ("COMPARING ATTRIBUTES FOR TWO FLOATING POINT " &
                   "TYPES WITH DIGITS 1 BUT MAXIMALLY DIFFERENT " &
                   "RANGES");

          IF F1'BASE'DIGITS = F2'BASE'DIGITS THEN
               COMMENT ("'DIGITS' IS THE SAME");
          ELSE
               COMMENT ("'DIGITS' IS DIFFERENT");
          END IF;

          IF F1'BASE'MANTISSA = F2'BASE'MANTISSA THEN
               COMMENT ("'MANTISSA' IS THE SAME");
          ELSE
               COMMENT ("'MANTISSA' IS DIFFERENT");
          END IF;

          IF F1'BASE'EPSILON = F2'BASE'EPSILON THEN
               COMMENT ("'EPSILON' IS THE SAME");
          ELSE
               COMMENT ("'EPSILON' IS DIFFERENT");
          END IF;

          IF F1'BASE'EMAX = F2'BASE'EMAX THEN
               COMMENT ("'EMAX' IS THE SAME");
          ELSE
               COMMENT ("'EMAX' IS DIFFERENT");
          END IF;

          IF F1'BASE'SMALL = F2'BASE'SMALL THEN
               COMMENT ("'SMALL' IS THE SAME");
          ELSE
               COMMENT ("'SMALL' IS DIFFERENT");
          END IF;

          IF F1'BASE'LARGE = F2'BASE'LARGE THEN
               COMMENT ("'LARGE' IS THE SAME");
          ELSE
               COMMENT ("'LARGE' IS DIFFERENT");
          END IF;

          IF F1'BASE'SAFE_EMAX = F2'BASE'SAFE_EMAX THEN
               COMMENT ("'SAFE_EMAX' IS THE SAME");
          ELSE
               COMMENT ("'SAFE_EMAX' IS DIFFERENT");
          END IF;

          IF F1'BASE'SAFE_SMALL = F2'BASE'SAFE_SMALL THEN
               COMMENT ("'SAFE_SMALL' IS THE SAME");
          ELSE
               COMMENT ("'SAFE_SMALL' IS DIFFERENT");
          END IF;

          IF F1'BASE'SAFE_LARGE = F2'BASE'SAFE_LARGE THEN
               COMMENT ("'SAFE_LARGE' IS THE SAME");
          ELSE
               COMMENT ("'SAFE_LARGE' IS DIFFERENT");
          END IF;

          IF F1'MACHINE_ROUNDS = F2'MACHINE_ROUNDS THEN
               COMMENT ("'MACHINE_ROUNDS' IS THE SAME");
          ELSE
               COMMENT ("'MACHINE_ROUNDS' IS DIFFERENT");
          END IF;

          IF F1'MACHINE_OVERFLOWS = F2'MACHINE_OVERFLOWS THEN
               COMMENT ("'MACHINE_OVERFLOWS' IS THE SAME");
          ELSE
               COMMENT ("'MACHINE_OVERFLOWS' IS DIFFERENT");
          END IF;

          IF F1'MACHINE_RADIX = F2'MACHINE_RADIX THEN
               COMMENT ("'MACHINE_RADIX' IS THE SAME");
          ELSE
               COMMENT ("'MACHINE_RADIX' IS DIFFERENT");
          END IF;

          IF F1'MACHINE_MANTISSA = F2'MACHINE_MANTISSA THEN
               COMMENT ("'MACHINE_MANTISSA' IS THE SAME");
          ELSE
               COMMENT ("'MACHINE_MANTISSA' IS DIFFERENT");
          END IF;

          IF F1'MACHINE_EMAX = F2'MACHINE_EMAX THEN
               COMMENT ("'MACHINE_EMAX' IS THE SAME");
          ELSE
               COMMENT ("'MACHINE_EMAX' IS DIFFERENT");
          END IF;

          IF F1'MACHINE_EMIN = F2'MACHINE_EMIN THEN
               COMMENT ("'MACHINE_EMIN' IS THE SAME");
          ELSE
               COMMENT ("'MACHINE_EMIN' IS DIFFERENT");
          END IF;

          IF F1'SIZE = F2'SIZE THEN
               COMMENT ("'SIZE' IS THE SAME");
          ELSE
               COMMENT ("'SIZE' IS DIFFERENT");
          END IF;

     END;

     RESULT;

END A35710A;
