-- A35801A.ADA

-- CHECK THAT THE ATTRIBUTES DIGITS, MANTISSA, EMAX, AND SAFE_EMAX ARE
-- OF TYPE UNIVERSAL INTEGER AND THAT THE ATTRIBUTES SMALL, LARGE, 
-- EPSILON, SAFE_SMALL, AND SAFE_LARGE ARE OF TYPE UNIVERSAL REAL.

-- R.WILLIAMS 8/21/86

WITH REPORT; USE REPORT;
PROCEDURE A35801A IS

     BEGIN
          TEST ( "A35801A", "CHECK THAT THE ATTRIBUTES DIGITS, " &
                            "MANTISSA, EMAX, SAFE_EMAX, SMALL, " &
                            "LARGE, EPSILON, SAFE_SMALL, AND " &
                            "SAFE_LARGE YIELD THE CORRECT TYPES " );

     DECLARE
          
          I1 : CONSTANT := FLOAT'DIGITS;
          I2 : CONSTANT := FLOAT'MANTISSA;
          I3 : INTEGER  := I1 + I2;
     
          I4 : CONSTANT := FLOAT'EMAX;
          I5 : CONSTANT := FLOAT'SAFE_EMAX;
          I6 : INTEGER  := I4 + I5;
          
          F1 : CONSTANT := FLOAT'SMALL;
          F2 : CONSTANT := FLOAT'LARGE;

          SUBTYPE FLT1 IS FLOAT RANGE F1 .. F2;

          F3 : CONSTANT := FLOAT'EPSILON;
          F4 : FLOAT := FLOAT'EPSILON;

          F5 : CONSTANT := FLOAT'SAFE_SMALL;
          F6 : CONSTANT := FLOAT'SAFE_LARGE;

          SUBTYPE FLT2 IS FLOAT RANGE F5 .. F6;

     BEGIN
          NULL;
     END;
    
     RESULT;
END A35801A;
