-- A35801F.ADA

-- CHECK THAT THE ATTRIBUTES FIRST AND LAST RETURN VALUES HAVING THE
-- SAME BASE TYPE AS THE PREFIX WHEN THE PREFIX IS A FLOATING POINT
-- TYPE.

-- THIS CHECK IS PROVIDED THROUGH THE USE OF THIS TEST IN CONJUNCTION
-- WITH TEST B35801C.

-- R.WILLIAMS 8/21/86

WITH REPORT; USE REPORT;
PROCEDURE A35801F IS

     TYPE REAL IS DIGITS 3 RANGE -100.0 .. 100.0;
     SUBTYPE SURREAL IS REAL RANGE -50.0 .. 50.0;

     TYPE NFLT IS NEW FLOAT;
     SUBTYPE UNIT IS NFLT RANGE -1.0 .. 1.0;     

     SUBTYPE EMPTY IS FLOAT RANGE 1.0 .. -1.0;

     R1 : REAL := SURREAL'FIRST;       -- OK.
     R2 : REAL := SURREAL'LAST;        -- OK.

     N1 : NFLT := UNIT'FIRST;          -- OK.
     N2 : NFLT := UNIT'LAST;           -- OK.

     F1 : FLOAT := FLOAT'FIRST;        -- OK.
     F2 : FLOAT := FLOAT'LAST;         -- OK.

     E1 : FLOAT := EMPTY'FIRST;        -- OK.
     E2 : FLOAT := EMPTY'LAST;         -- OK.

BEGIN
     TEST ( "A35801F", "CHECK THAT THE ATTRIBUTES FIRST AND LAST " &
                       "RETURN VALUES HAVING THE SAME BASE TYPE AS " &
                       "THE PREFIX WHEN THE PREFIX IS A FLOATING " &
                       "POINT TYPE" );

     RESULT;
END A35801F;
