-- A35902C.ADA

-- OBJECTIVE:
--     CHECK THAT A FIXED POINT TYPE WITH ONLY ONE MODEL NUMBER IS
--     ALLOWED.

-- HISTORY:
--     RJW 02/26/86 CREATED ORIGINAL TEST.
--     DHH 10/15/87 CORRECTED RANGE ERRORS.

WITH REPORT; USE REPORT;

PROCEDURE A35902C IS

BEGIN

     TEST ("A35902C", "CHECK THAT A FIXED POINT TYPE WITH ONLY ONE " &
                      "MODEL NUMBER IS ALLOWED" );
     DECLARE
          TYPE F IS DELTA 1.0 RANGE -0.5 .. 0.5;   -- OK.
          F1 : F := 0.0;

     BEGIN
          NULL;
     END;

     RESULT;

END A35902C;
