-- A38199C1M.ADA

-- CHECK THAT AN INCOMPLETE TYPE CAN BE DECLARED IN A SEPARATELY
-- COMPILED PACKAGE SPECIFICATION AND ITS FULL DECLARATION CAN LATER BE
-- GIVEN IN A SEPARATELY COMPILED BODY.

-- JBG 6/6/85

-- A38199C0    THE PACKAGE SPECIFICATION
-- A38199C1M   THE MAIN PROGRAM.
-- A38199C2    THE PACKAGE BODY.

WITH REPORT; USE REPORT;
WITH A38199C0; USE A38199C0;
PROCEDURE A38199C1M IS
     V : L;
BEGIN

     TEST ("A38199C", "CHECK THAT INCOMPLETE TYPE CAN BE DECLARED IN " &
                      "PRIVATE PART WITHOUT FULL DECLARATION - " &
                      "LIBRARY PACKAGE");

     RESULT;
END A38199C1M;
