-- A38199A.ADA

-- CHECK THAT AN INCOMPLETE TYPE CAN BE DECLARED IN THE PRIVATE PART OF
-- A PACKAGE, WITH THE FULL DECLARATION OCCURRING LATER IN A PACKAGE
-- BODY.

-- JBG 6/6/85

WITH REPORT; USE REPORT;
PROCEDURE A38199A IS

     PACKAGE P IS
          TYPE L IS LIMITED PRIVATE;
     PRIVATE
          TYPE INC (D : INTEGER);
          TYPE L IS ACCESS INC;
     END P;

     PACKAGE BODY P IS
          TYPE INC (D : INTEGER) IS
               RECORD
                    C: INTEGER;
               END RECORD;
     END P;

BEGIN

     TEST ("A38199A", "CHECK THAT INCOMPLETE TYPE CAN BE DECLARED IN " &
                      "PRIVATE PART WITHOUT FULL DECLARATION");

     RESULT;
END A38199A;
