-- A38199C0.ADA

-- CHECK THAT AN INCOMPLETE TYPE CAN BE DECLARED IN THE PRIVATE PART OF
-- A LIBRARY PACKAGE, WITH THE FULL DECLARATION OCCURRING LATER IN A
-- PACKAGE BODY.

-- JBG 6/6/85

PACKAGE A38199C0 IS
     TYPE L IS LIMITED PRIVATE;
PRIVATE
     TYPE INC (D : INTEGER);
     TYPE L IS ACCESS INC;
END A38199C0;
