-- A39005C.ADA

-- OBJECTIVE:
--     CHECK THAT A LENGTH CLAUSE SPECIFYING 'STORAGE_SIZE
--     FOR AN ACCESS TYPE CAN BE GIVEN BETWEEN TWO TYPE
--     DECLARATIONS.

-- HISTORY:
--     TBN  08/18/86  CREATED ORIGINAL TEST.
--     BCB  12/28/87  MODIFIED HEADER.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT; USE REPORT;
WITH SYSTEM;
PROCEDURE A39005C IS

     TYPE CELL IS
          RECORD
               NAME : STRING (1 .. 5);
          END RECORD;

     TYPE LIST IS ACCESS CELL;

     FOR LIST'STORAGE_SIZE
          USE 10*(CELL'SIZE/SYSTEM.STORAGE_UNIT);

     TYPE LIST_ARRAY IS ARRAY (1 .. 5) OF LIST;

     POINT : LIST_ARRAY;

BEGIN
     TEST ("A39005C", "CHECK THAT A LENGTH CLAUSE SPECIFYING " &
                      "'STORAGE_SIZE FOR AN ACCESS TYPE " &
                      "CAN BE GIVEN BETWEEN TWO TYPE DECLARATIONS");
     RESULT;
END A39005C;
