-- A39005F.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION REPRESENTATION CLAUSE CAN BE GIVEN
--     BETWEEN TWO TYPE DECLARATIONS.

-- HISTORY:
--     TBN  08/19/86  CREATED ORIGINAL TEST.
--     BCB  12/28/87  MODIFIED HEADER.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT; USE REPORT;
PROCEDURE A39005F IS

     TYPE MIX_CODE IS (ADD, SUB, MUL, LDA, STA, STZ);

     FOR MIX_CODE USE (ADD => 1, SUB => 2, MUL => 3,
                      LDA => 8, STA => 24, STZ => 33);

     TYPE STATE IS (A, M, W, P);

     VAR1 : MIX_CODE := SUB;
     VAR2 : STATE := M;

BEGIN
     TEST ("A39005F", "CHECK THAT AN ENUMERATION REPRESENTATION " &
                      "CLAUSE CAN BE GIVEN BETWEEN TWO TYPE " &
                      "DECLARATIONS");
     RESULT;
END A39005F;
