-- A39005B.ADA

-- OBJECTIVE:
--     CHECK THAT A LENGTH CLAUSE WITH THE ATTRIBUTE 'SIZE CAN BE GIVEN
--     BETWEEN TWO TYPE DECLARATIONS.

-- HISTORY:
--     TBN  08/12/86  CREATED ORIGINAL TEST.
--     BCB  12/28/87  MODIFIED HEADER.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT; USE REPORT;
PROCEDURE A39005B IS

     TYPE COLOR IS (WHITE, RED, YELLOW, GREEN, BLUE, BROWN, BLACK);

     FOR COLOR'SIZE USE 8;

     TYPE NEW_COLOR IS (RED, WHITE, BLUE);

BEGIN
     TEST ("A39005B", "CHECK THAT A LENGTH CLAUSE WITH THE ATTRIBUTE " &
                      "'SIZE CAN BE GIVEN BETWEEN TWO TYPE " &
                      "DECLARATIONS");

     RESULT;
END A39005B;
