-- A39005E.ADA

-- OBJECTIVE:
--     CHECK THAT A LENGTH CLAUSE WITH THE ATTRIBUTE 'SMALL CAN BE GIVEN
--     BETWEEN TWO TYPE DECLARATIONS.

-- HISTORY:
--     TBN  08/19/86  CREATED ORIGINAL TEST.
--     BCB  12/28/87  MODIFIED HEADER.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT; USE REPORT;
WITH SYSTEM;
PROCEDURE A39005E IS

     TYPE DEGREE IS DELTA 0.125 RANGE -1.0 .. 1.0;

     FOR DEGREE'SMALL USE 1.0 / (2**8);

     TYPE MIX_CODE IS (ADD, SUB, MUL, LDA, STA, STZ);

     VAR1 : DEGREE := 0.1;

BEGIN
     TEST ("A39005E", "CHECK THAT A LENGTH CLAUSE WITH THE ATTRIBUTE " &
                      "'SMALL CAN BE GIVEN BETWEEN TWO TYPE " &
                      "DECLARATIONS");
     RESULT;
END A39005E;
