-- A63202A.ADA

-- CHECK THAT ILLEGAL INLINE PRAGMAS HAVE NO EFFECT ON THE PROGRAM UNIT.
-- WARNINGS SHOULD BE ISSUED FOR IGNORED INLINE PRAGMAS.

-- ILLEGAL CASES  INCLUDE :
--     (1) PRAGMA APPEARS IN A DECLARATIVE REGION BUT
--          (A) THE NAME IS NOT THE NAME OF A SUBPROGRAM OR GENERIC
--              SUBPROGRAM; 
--          (B) THE NAME IS THAT OF A SUBPROGRAM OR GENERIC PROGRAM NOT
--              DECLARED IN THE SAME DECLARATIVE REGION OR PACKAGE
--              SPECIFICATION;
--     (2) PRAGMA APPEARS FOLLOWING A LIBRARY UNIT BUT
--          (A) THE NAME IS NOT THE NAME OF THE LIBRARY UNIT;
--          (B) THE UNIT IS NOT A SUBPROGRAM OR GENERIC SUBPROGRAM;
--     (3) PRAGMA DOES NOT APPEAR IN A DECLARATIVE PART, PACKAGE SPEC,
--         OR FOLLOWING A LIBRARY UNIT.

-- BHS 7/17/84
-- JRK 6/7/85


PACKAGE A63202A1 IS
END A63202A1;

PRAGMA INLINE (A63202A1);               -- ILLEGAL: (2B).


PROCEDURE A63202A2 IS
BEGIN
     NULL;
END A63202A2;


WITH A63202A1, A63202A2;
WITH REPORT;

PROCEDURE A63202A IS

     USE REPORT;

BEGIN
     TEST ("A63202A", "CHECK THAT ILLEGAL INLINE PRAGMAS ARE IGNORED");

     DECLARE
          X : INTEGER;
          PRAGMA INLINE (X);            -- ILLEGAL: (1A).

          PROCEDURE P IS
          BEGIN NULL; END P;
     BEGIN
          PRAGMA INLINE (P);            -- ILLEGAL: (3).
          NULL;
          P;

          DECLARE
               PROCEDURE Q;
               PRAGMA INLINE (P);       -- ILLEGAL: (1B).
               PRAGMA INLINE (Q);       -- LEGAL.

               PROCEDURE R RENAMES P;
               PRAGMA INLINE (R);       -- LEGAL.

               PROCEDURE Q IS
               BEGIN NULL; END Q;
          BEGIN
               NULL;
          END;
     END;

     DECLARE
          GENERIC
               TYPE ITEM IS PRIVATE;
               WITH FUNCTION F (X, Y : ITEM) RETURN ITEM IS <>;
          PROCEDURE GP;

          PROCEDURE GP IS
          BEGIN  
               NULL;   
          END GP;

          PRAGMA INLINE (F);            -- ILLEGAL: (1A).
          PRAGMA INLINE (GP);           -- LEGAL.

          PROCEDURE NGP IS NEW GP (INTEGER, "+");
          PRAGMA INLINE (NGP);          -- LEGAL.
     BEGIN
          NULL;
     END;

     DECLARE
          PROCEDURE X IS 
          BEGIN NULL; END X;

          PACKAGE Y IS
               Z : INTEGER;
          END Y;

          PRAGMA INLINE (Y);            -- ILLEGAL: (1A).
          PRAGMA INLINE (X);            -- LEGAL.
     BEGIN
          NULL;
     END;

     RESULT;
END A63202A;

PRAGMA INLINE (A63202A2);               -- ILLEGAL: (2A).
