-- A73001I.ADA

-- CHECK THAT IF A SUBPROGRAM IS DECLARED BY A RENAMING DECLARATION OR
-- GENERIC INSTANTIATION IN A PACKAGE SPECIFICATION NO PACKAGE BODY IS
-- REQUIRED.

-- BHS 6/26/84

WITH REPORT;
PROCEDURE A73001I IS

     USE REPORT;

BEGIN

     TEST ("A73001I", "CHECK THAT NO PACKAGE BODY IS REQUIRED FOR " &
                      "SUBPROGRAM DECLARED BY RENAMING DECLARATION " &
                      "OR GENERIC INSTANTIATION IN A PACKAGE " &
                      "SPECIFICATION");

     DECLARE
          PACKAGE PACK1 IS
               FUNCTION ADDI (X,Y : INTEGER) RETURN INTEGER RENAMES "+";
          END PACK1;

     BEGIN
          NULL;
     END;


     DECLARE
          GENERIC
               TYPE ITEM IS RANGE <>;
          PROCEDURE P (X : IN OUT ITEM);

          PROCEDURE P (X : IN OUT ITEM) IS
          BEGIN
               NULL;
          END P;

          PACKAGE PACK2 IS
               PROCEDURE NADA IS NEW P (INTEGER);
          END PACK2;

     BEGIN
          NULL;
     END;

     RESULT;

END A73001I;
