-- A73001J.ADA

-- CHECK THAT IF A SUBPROGRAM IS DECLARED BY A RENAMING DECLARATION OR
-- GENERIC INSTANTIATION IN A GENERIC PACKAGE SPECIFICATION, NO PACKAGE
-- BODY IS REQUIRED.


-- BHS 6/27/84

WITH REPORT;
PROCEDURE A73001J IS

     USE REPORT;

BEGIN

     TEST ("A73001J", "CHECK THAT NO PACKAGE BODY IS REQUIRED FOR " &
                      "SUBPROGRAM DECLARED BY RENAMING DECLARATION " &
                      "OR GENERIC INSTANTIATION IN A GENERIC " &
                      "PACKAGE SPECIFICATION");

     DECLARE
          GENERIC
               TYPE ITEM IS RANGE <>;
          PACKAGE PACK1 IS
               FUNCTION ADDI (X,Y : ITEM) RETURN ITEM RENAMES "+";
          END PACK1;

     BEGIN
          NULL;
     END;


     DECLARE
          GENERIC
               TYPE ITEM IS RANGE <>;
          PROCEDURE P (X : IN OUT ITEM);

          PROCEDURE P (X : IN OUT ITEM) IS
          BEGIN
               NULL;
          END P;

          GENERIC
               TYPE OBJ IS RANGE <>;
          PACKAGE PACK2 IS
               PROCEDURE NADA IS NEW P (OBJ);
          END PACK2;

     BEGIN
          NULL;
     END;

     RESULT;

END A73001J;
