-- A91002M.ADA

-- CHECK THAT INAPPROPRIATE PRAGMAS ARE IGNORED IN TASK SPECIFICATIONS

-- JRK 9/16/81
-- JBG 4/19/83

WITH REPORT; USE REPORT;

PROCEDURE A91002M IS

     TASK TYPE T2M IS

          ENTRY E;

          PRAGMA CONTROLLED (A);     -- IGNORE: PROHIBITED IN TASK SPEC.
          PRAGMA INLINE (P);         -- IGNORE: PROHIBITED IN TASK SPEC.
          PRAGMA INTERFACE (FORTRAN, F);   -- IGNORE: PROHIBITED IN TASK
                                           --        SPEC.
          PRAGMA MEMORY_SIZE (1000); -- IGNORE: PROHIBITED IN TASK SPEC.
          PRAGMA OPTIMIZE (TIME);    -- IGNORE: PROHIBITED IN TASK SPEC.
          PRAGMA PACK (B);           -- IGNORE: PROHIBITED IN TASK SPEC.
          PRAGMA STORAGE_UNIT (8);   -- IGNORE: PROHIBITED IN TASK SPEC.

     END T2M;

     TASK BODY T2M IS
     BEGIN
          NULL;
     END;

BEGIN
     TEST ("A91002M", "CHECK THAT FORBIDDEN PRAGMAS ARE IGNORED IN " &
                      "TASK SPECIFICATIONS");
     RESULT;
END A91002M;
