-- A98001A.ADA

-- CHECK THAT NO EXCEPTION IS RAISED IF THE EXPRESSION IN A PRAGMA
-- PRIORITY IS STATIC AND THE VALUE OF THE EXPRESSION IS OUTSIDE THE
-- RANGE OF THE SUBTYPE PRIORITY, IF THE PRAGMA IS LOCATED IN THE MAIN
-- PROGRAM.

-- TBN  12/18/86

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;
PROCEDURE A98001A IS

     PRAGMA PRIORITY (PRIORITY'FIRST - 1);

     X : INTEGER;

BEGIN
     TEST ("A98001A", "CHECK THAT NO EXCEPTION IS RAISED IF THE " &
                      "EXPRESSION IN A PRAGMA PRIORITY IS STATIC AND " &
                      "THE VALUE OF THE EXPRESSION IS OUTSIDE THE " &
                      "RANGE OF THE SUBTYPE PRIORITY, IF THE PRAGMA " &
                      "IS LOCATED IN THE MAIN PROGRAM");
     X := IDENT_INT(3);
     X := IDENT_INT(X);

     RESULT;
END A98001A;
