-- A99007A.ADA

-- OBJECTIVE:
--     CHECK THAT TASK TYPES AND TASK OBJECTS ARE ALLOWED AS PREFIXES
--     FOR 'STORAGE_SIZE.

-- HISTORY:
--     DHH 03/28/88 CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE A99007A IS

     Y, Z : INTEGER;

     TASK TYPE TTYPE IS
          ENTRY START;
          ENTRY E1;
          ENTRY STOP;
     END TTYPE;

     T1 : TTYPE;

     TASK T2;

     A : INTEGER := T2'STORAGE_SIZE;

     GENERIC
          GT : IN OUT TTYPE;
     PACKAGE GP IS
          GX : INTEGER := GT'STORAGE_SIZE;
     END GP;

     TASK BODY TTYPE IS
          X : INTEGER;
     BEGIN
          ACCEPT START;
          ACCEPT E1 DO
               X := TTYPE'STORAGE_SIZE;
          END E1;
          ACCEPT STOP;
     END TTYPE;

     TASK BODY T2 IS
          B : INTEGER := T2'STORAGE_SIZE;
     BEGIN
          NULL;
     END;

     PACKAGE PKG IS NEW GP (T1);

BEGIN

     TEST("A99007A", "CHECK THAT TASK TYPES AND TASK OBJECTS ARE " &
                     "ALLOWED AS PREFIXES FOR 'STORAGE_SIZE");

     Y := T1'STORAGE_SIZE;
     Z := TTYPE'STORAGE_SIZE;
     T1.START;
     T1.E1;
     T1.STOP;

     RESULT;
END A99007A;
