-- A9B002B.ADA

-- OBJECTIVE:
--     CHECK THAT IF A "SHARED" PRAGMA GIVES A NAME DECLARED BY A
--     RENAMING DECLARATION, THE PRAGMA IS IGNORED.

-- HISTORY:
--     DHH 08/16/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE A9B002B IS

     TYPE Y IS ACCESS STRING;

     FIRST : Y := NEW STRING'("ABCD");

     SECOND : Y RENAMES FIRST;

     PRAGMA SHARED(SECOND);                        -- SHOULD BE IGNORED.

     TASK TYPE CHOICE IS
          ENTRY E1;
     END CHOICE;

     T : CHOICE;

     TASK BODY CHOICE IS
     BEGIN
          ACCEPT E1;
     END CHOICE;

BEGIN

     TEST("A9B002B", "CHECK THAT IF A ""SHARED"" PRAGMA GIVES A NAME " &
                     "DECLARED BY A RENAMING DECLARATION, THE " &
                     "PRAGMA IS IGNORED");

     T.E1;

     RESULT;

END A9B002B;
