-- A9B001A.ADA

-- OBJECTIVE:
--     CHECK THAT IF MORE THAN ONE NAME IS GIVEN IN A "SHARED" PRAGMA,
--     THE PRAGMA IS IGNORED.

-- HISTORY:
--     DHH 03/28/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE A9B001A IS

     X, Y : INTEGER := 10;

     PRAGMA SHARED(X, Y);

     TASK TYPE CHOICE IS
          ENTRY E1;
     END CHOICE;

     T : CHOICE;

     TASK BODY CHOICE IS
     BEGIN
          ACCEPT E1 DO
               X := X + IDENT_INT(Y);
          END E1;
     END CHOICE;

BEGIN

     TEST("A9B001A", "CHECK THAT IF MORE THAN ONE NAME IS GIVEN IN " &
                     "A ""SHARED"" PRAGMA, THE PRAGMA IS IGNORED");
     T.E1;

     RESULT;

END A9B001A;
