-- AA2012A.ADA

-- CHECK THAT A BODY STUB CAN SERVE AS AN IMPLICIT DECLARATION OF A 
-- SUBPROGRAM, I.E., A PRECEDING SUBPROGRAM DECLARATION IS NOT 
-- REQUIRED.

-- R.WILLIAMS 9/18/86

PROCEDURE AA2012A1 IS

     I : INTEGER;

     PROCEDURE AA2012A2 IS SEPARATE;

     FUNCTION AA2012A3 RETURN INTEGER IS SEPARATE;

BEGIN
     AA2012A2;
     I := AA2012A3;

END AA2012A1;

SEPARATE (AA2012A1)
PROCEDURE AA2012A2 IS
BEGIN
     NULL;
END;

SEPARATE (AA2012A1)
FUNCTION AA2012A3 RETURN INTEGER IS
BEGIN
     RETURN 5;
END;
     
WITH AA2012A1;
WITH REPORT; USE REPORT;
PROCEDURE AA2012A IS

BEGIN
     TEST ( "AA2012A", "CHECK THAT A BODY STUB CAN SERVE AS AN " &
                       "IMPLICIT DECLARATION OF A SUBPROGRAM, " &
                       "I.E., A PRECEDING SUBPROGRAM DECLARATION " &
                       "IS NOT REQUIRED" );

     AA2012A1;

     RESULT;
END AA2012A;
