-- AA5008X.ADA

-- CHECK THAT PRAGMA ELABORATE IS IGNORED IF ANY OF THE NAMES GIVEN IN 
-- THE PRAGMA DO NOT APPEAR IN A PRECEDING CONTEXT CLAUSE.

-- R.WILLIAMS 9/22/86

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT, AA5008X0);
PRAGMA ELABORATE (AA5008X1);
PROCEDURE AA5008X IS
BEGIN
     TEST ( "AA5008X", "CHECK THAT PRAGMA ELABORATE IS IGNORED IF " &
                       "ANY OF THE NAMES GIVEN IN THE PRAGMA DO " &
                       "NOT APPEAR IN A PRECEDING CONTEXT CLAUSE" );
                         
     RESULT;
END AA5008X;
