-- AB7006A.ADA

-- OBJECTIVE:
--     CHECK THAT IF THE FIRST ARGUMENT OF A SUPPRESS PRAGMA IS
--     STORAGE_CHECK, THEN THE SECOND ARGUMENT MUST BE A NAME DENOTING
--     AN ACCESS TYPE, A TASK UNIT, OR A SUBPROGRAM (ELSE THE PRAGMA IS
--     IGNORED).

-- HISTORY:
--     DHH 04/01/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE AB7006A IS

     SUBTYPE OBJ IS INTEGER;
     PRAGMA SUPPRESS(STORAGE_CHECK, OBJ);

     PACKAGE PACK IS
     END PACK;
     PRAGMA SUPPRESS(STORAGE_CHECK, PACK);


BEGIN
     TEST("AB7006A", "CHECK THAT IF THE FIRST ARGUMENT OF A " &
                     "SUPPRESS PRAGMA IS STORAGE_CHECK, THEN THE " &
                     "SECOND ARGUMENT MUST BE A NAME DENOTING AN " &
                     "ACCESS TYPE, A TASK UNIT, OR A SUBPROGRAM " &
                     "(ELSE THE PRAGMA IS IGNORED)");

     RESULT;
END AB7006A;
