-- AC1015B.ADA

-- OBJECTIVE:
--     CHECK THAT WITHIN A GENERIC SUBPROGRAM THE NAME OF THE GENERIC
--     SUBPROGRAM CAN BE USED AS AN ACTUAL PARAMETER IN AN
--     INSTANTIATION.

-- HISTORY:
--     BCB 03/28/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE AC1015B IS

     GENERIC
     PROCEDURE P;

     PROCEDURE P IS
          GENERIC
               WITH PROCEDURE F;
          PROCEDURE T;

          PROCEDURE T IS
          BEGIN
               NULL;
          END T;

          PROCEDURE S IS NEW T(F => P);

     BEGIN
          NULL;
     END P;

     GENERIC
     FUNCTION D RETURN BOOLEAN;

     FUNCTION D RETURN BOOLEAN IS
          GENERIC
               WITH FUNCTION L RETURN BOOLEAN;
          FUNCTION A RETURN BOOLEAN;

          FUNCTION A RETURN BOOLEAN IS
          BEGIN
               RETURN TRUE;
          END A;

          FUNCTION B IS NEW A(L => D);

     BEGIN
          RETURN TRUE;
     END D;

BEGIN
     TEST ("AC1015B", "CHECK THAT WITHIN A GENERIC SUBPROGRAM THE " &
                      "NAME OF THE GENERIC SUBPROGRAM CAN BE USED AS " &
                      "AN ACTUAL PARAMETER IN AN INSTANTIATION");

     RESULT;
END AC1015B;
