-- AC3207A.ADA

-- OBJECTIVE:
--     CHECK THAT AN INSTANTIATION IS LEGAL IF A FORMAL PARAMETER
--     HAVING A LIMITED PRIVATE TYPE WITHOUT DISCRIMINANTS IS USED TO
--     DECLARE AN OBJECT IN A BLOCK THAT CONTAINS A SELECTIVE WAIT
--     WITH A TERMINATE ALTERNATIVE, AND THE ACTUAL PARAMETER'S BASE
--     TYPE IS A TASK TYPE OR A TYPE WITH A SUBCOMPONENT OF A TASK TYPE.

-- HISTORY:
--     DHH 09/16/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE AC3207A IS

     GENERIC
          TYPE PRIV IS LIMITED PRIVATE;
     PACKAGE GEN_P IS
          TASK T1 IS
               ENTRY E;
          END T1;
     END GEN_P;

     TASK TYPE TASK_T IS
     END TASK_T;

     TYPE REC IS
          RECORD
               OBJ : TASK_T;
          END RECORD;

     PACKAGE BODY GEN_P IS
          TASK BODY T1 IS
          BEGIN
               DECLARE
                    OBJ : PRIV;
               BEGIN
                    SELECT
                         ACCEPT E;
                    OR
                         TERMINATE;
                    END SELECT;
               END;
          END T1;
     END GEN_P;

     TASK BODY TASK_T IS
     BEGIN
          NULL;
     END;

     PACKAGE P IS NEW GEN_P(TASK_T);
     PACKAGE NEW_P IS NEW GEN_P(REC);

BEGIN
     TEST ("AC3207A", "CHECK THAT AN INSTANTIATION IS LEGAL IF A " &
                      "FORMAL PARAMETER HAVING A LIMITED PRIVATE " &
                      "TYPE WITHOUT DISCRIMINANTS IS USED TO " &
                      "DECLARE AN OBJECT IN A BLOCK THAT CONTAINS " &
                      "A SELECTIVE WAIT WITH A TERMINATE " &
                      "ALTERNATIVE, AND THE ACTUAL PARAMETER'S BASE " &
                      "TYPE IS A TASK TYPE OR A TYPE WITH A " &
                      "SUBCOMPONENT OF A TASK TYPE");

     P.T1.E;

     NEW_P.T1.E;

     RESULT;
END AC3207A;
