-- AD1D01E.ADA

-- OBJECTIVE:
--     CHECK WHETHER THE PRAGMA PACK IS OBEYED FOR A RECORD TYPE
--     WITH A REPRESENTATION CLAUSE, AND IF THE SIZE IS AFFECTED,
--     CHECK WHETHER THE MINIMUM IS USED.

-- HISTORY:
--     JET 09/23/87  CREATED ORIGINAL TEST.
--     DHH 11/16/88  CHANGED FROM 'C' TEST TO 'A' TEST. CHANGED
--                   EXTENSION FROM 'DEP' TO 'ADA'.

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;

PROCEDURE AD1D01E IS

     UNITS_PER_INTEGER : CONSTANT :=
          (INTEGER'SIZE + SYSTEM.STORAGE_UNIT - 1) /
          SYSTEM.STORAGE_UNIT;

     TYPE E_TYPE IS (RED, BLUE, GREEN);
     SUBTYPE I_TYPE IS INTEGER RANGE 0 .. 127;

     TYPE TEST_REP IS
          RECORD
               B1 : BOOLEAN := TRUE;
               I : I_TYPE := 127;
               C : CHARACTER := 'S';
               B2 : BOOLEAN := FALSE;
               E : E_TYPE := BLUE;
          END RECORD;

     FOR TEST_REP USE
          RECORD
               C AT 0 RANGE 0 .. CHARACTER'SIZE - 1;
               I AT 1*UNITS_PER_INTEGER RANGE 0 .. I_TYPE'SIZE - 1;
               E AT 2*UNITS_PER_INTEGER RANGE 0 .. E_TYPE'SIZE - 1;
          END RECORD;

     TYPE REC_TYPE IS
          RECORD
               B1 : BOOLEAN   := TRUE;
               I  : I_TYPE    := 127;
               C  : CHARACTER := 'S';
               B2 : BOOLEAN   := FALSE;
               E  : E_TYPE    := BLUE;
          END RECORD;

     FOR REC_TYPE USE
          RECORD
               C AT 0 RANGE 0 .. CHARACTER'SIZE - 1;
               I AT 1*UNITS_PER_INTEGER RANGE 0 .. I_TYPE'SIZE - 1;
               E AT 2*UNITS_PER_INTEGER RANGE 0 .. E_TYPE'SIZE - 1;
          END RECORD;

     PRAGMA PACK (REC_TYPE);

     REC : REC_TYPE;
     MIN_SIZE : CONSTANT := CHARACTER'SIZE + I_TYPE'SIZE +
                            E_TYPE'SIZE + 2*BOOLEAN'SIZE;

BEGIN

     TEST("AD1D01E", "CHECK WHETHER THE PRAGMA PACK IS OBEYED " &
                     "FOR A RECORD TYPE WITH A REPRESENTATION " &
                     "CLAUSE, AND IF THE SIZE IS AFFECTED, " &
                     "CHECK WHETHER THE MINIMUM IS USED");

     IF TEST_REP'SIZE = REC_TYPE'SIZE THEN
          COMMENT ("THE PRAGMA PACK HAD NO EFFECT ON THE VALUE OF " &
                   "REC_TYPE'SIZE");
     END IF;

     IF REC_TYPE'SIZE = IDENT_INT (MIN_SIZE) THEN
          COMMENT ("THE MINIMUM SIZE OF" & INTEGER'IMAGE (MIN_SIZE) &
                   " WAS USED");
     ELSE
          COMMENT ("THE MINIMUM SIZE WAS NOT USED.  THE SIZE WAS" &
                   INTEGER'IMAGE (REC_TYPE'SIZE));
     END IF;

     RESULT;

END AD1D01E;
