-- AD7001D0M.ADA

-- OBJECTIVE:
--     CHECK THAT A DECLARATION IN PACKAGE SYSTEM IS ACCESSIBLE
--     IN A SUBUNIT IF A WITH CLAUSE NAMING SYSTEM IS PROVIDED
--     FOR THE MAIN UNIT CONTAINING THE SUBUNIT, ALTHOUGH IN A
--     SEPARATE FILE.

-- HISTORY:
--     JET 09/09/87  CREATED ORIGINAL TEST.
--     RJW 05/03/88  REVISED AND ENTERED TEST INTO ACVC.

-- THIS FILE CONTAINS THE MAIN PROCEDURE FOR TEST AD7001D.  FILE
--     AD7001D1.ADA CONTAINS THE PACKAGE BODY FOR THE SUBUNIT PACKAGE
--     SPEC AND IS ALSO REQUIRED FOR TEST EXECUTION.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7001D0M IS

     PACKAGE AD7001D_PACKAGE IS

          I : INTEGER;
          F : FLOAT;

     END AD7001D_PACKAGE;

     PACKAGE BODY AD7001D_PACKAGE IS SEPARATE;

BEGIN
     TEST ("AD7001D", "CHECK THAT A DECLARATION IN PACKAGE SYSTEM " &
                      "IS ACCESSIBLE IN A SUBUNIT IF A WITH CLAUSE " &
                      "NAMING SYSTEM IS PROVIDED FOR THE MAIN UNIT " &
                      "CONTAINING THE SUBUNIT, ALTHOUGH IN A " &
                      "SEPARATE FILE");
     RESULT;
END AD7001D0M;
