-- AD7001C1.ADA

-- OBJECTIVE:
--     CHECK THAT A DECLARATION IN PACKAGE SYSTEM IS ACCESSIBLE
--     IN A LIBRARY PACKAGE BODY IF A WITH CLAUSE NAMING SYSTEM
--     IS PROVIDED FOR THE PACKAGE SPECIFICATION, ALTHOUGH IN ANOTHER
--     FILE.

-- HISTORY:
--     JET 09/09/87  CREATED ORIGINAL TEST.
--     RJW 05/03/88  REVISED AND ENTERED IN ACVC.

-- THIS FILE CONTAINS THE PACKAGE BODY FOR PACKAGE AD7001C_PACKAGE.
--     FILE AD7001C0M.ADA CONTAINS THE PACKAGE SPEC AND MAIN PROCEDURE
--     FOR TEST AD7001C AND IS ALSO REQUIRED FOR TEST EXECUTION.

PACKAGE BODY AD7001C_PACKAGE IS

     CHECK_ADDRESS  : SYSTEM.ADDRESS;
     CHECK_NAME     : SYSTEM.NAME := SYSTEM.SYSTEM_NAME;
     CHECK_PRIORITY : SYSTEM.PRIORITY;
     MEM_SIZE       : CONSTANT := SYSTEM.MEMORY_SIZE;

     TYPE INTRANGE IS RANGE SYSTEM.MIN_INT..SYSTEM.MAX_INT;

BEGIN
     I := SYSTEM.STORAGE_UNIT;
     I := SYSTEM.MAX_DIGITS;
     I := SYSTEM.MAX_MANTISSA;
     F := SYSTEM.FINE_DELTA;
     F := SYSTEM.TICK;
END AD7001C_PACKAGE;
