-- AD7001C0M.ADA

-- OBJECTIVE:
--     CHECK THAT A DECLARATION IN PACKAGE SYSTEM IS ACCESSIBLE
--     IN A LIBRARY PACKAGE BODY IF A WITH CLAUSE NAMING SYSTEM
--     IS PROVIDED FOR THE PACKAGE SPECIFICATION, ALTHOUGH IN A
--     SEPARATE FILE.

-- HISTORY:
--     JET 09/09/87  CREATED ORIGINAL TEST.
--     RJW 05/03/88  REVISED AND ENTERED TEST INTO ACVC.

-- THIS FILE CONTAINS PACKAGE SPEC AD7001C_PACKAGE AND THE MAIN
--     PROCEDURE FOR TEST AD7001C.  FILE AD7001C1.ADA CONTAINS
--     THE PACKAGE BODY FOR THE PACKAGE SPEC AND IS ALSO REQUIRED
--     FOR TEST EXECUTION.

WITH SYSTEM;

PACKAGE AD7001C_PACKAGE IS

     I : INTEGER;
     F : FLOAT;

END AD7001C_PACKAGE;


WITH AD7001C_PACKAGE; USE AD7001C_PACKAGE;
WITH REPORT;  USE REPORT;

PROCEDURE AD7001C0M IS

BEGIN
     TEST ("AD7001C", "CHECK THAT A DECLARATION IN PACKAGE SYSTEM " &
                      "IS ACCESSIBLE IN A LIBRARY PACKAGE BODY IF " &
                      "A WITH CLAUSE NAMING SYSTEM IS PROVIDED FOR " &
                      "THE PACKAGE SPECIFICATION, ALTHOUGH IN A " &
                      "SEPARATE FILE");
     RESULT;
END AD7001C0M;
