-- AD7001B.ADA

-- OBJECTIVE:
--     CHECK THAT A DECLARATION IN PACKAGE SYSTEM IS ACCESSIBLE
--     IF A WITH CLAUSE NAMING SYSTEM IS PROVIDED FOR THE UNIT
--     CONTAINING THE REFERENCES.

-- HISTORY:
--     JET 09/08/87  CREATED ORIGINAL TEST.
--     VCL 03/30/88  CREATED NAMED NUMBERS WITH VALUES OF
--                   SYSTEM.MIN_INT AND SYSTEM.MAX_INT. DELETED
--                   ASSIGNMENTS OF MIN_INT AND MAX_INT TO INTEGER
--                   VARIABLES.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7001B IS

     CHECK_ADDRESS  : SYSTEM.ADDRESS;
     CHECK_NAME     : SYSTEM.NAME := SYSTEM.SYSTEM_NAME;
     CHECK_PRIORITY : SYSTEM.PRIORITY;
     I              : INTEGER;
     F              : FLOAT;
     SMALL          : CONSTANT := SYSTEM.MIN_INT;
     LARGE          : CONSTANT := SYSTEM.MAX_INT;
     MEM            : CONSTANT := SYSTEM.MEMORY_SIZE;

BEGIN

     TEST ("AD7001B", "CHECK THAT A DECLARATION IN PACKAGE " &
                      "SYSTEM IS ACCESSIBLE IF A WITH CLAUSE " &
                      "NAMING SYSTEM IS PROVIDED FOR THE UNIT " &
                      "CONTAINING THE REFERENCES");

     I := SYSTEM.STORAGE_UNIT;
     I := SYSTEM.MAX_DIGITS;
     I := SYSTEM.MAX_MANTISSA;
     F := SYSTEM.FINE_DELTA;
     F := SYSTEM.TICK;

     RESULT;

END AD7001B;
