-- AD7006A.ADA

-- OBJECTIVE:
--     CHECK THAT THE CONSTANT 'SYSTEM.MEMORY_SIZE' IS DECLARED AND
--     THAT IT IS A STATIC UNIVERSAL INTEGER.

-- HISTORY:
--     VCL  09/14/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE AD7006A IS
BEGIN
     TEST ("AD7006A", "THE CONSTANT 'SYSTEM.MEMORY_SIZE' IS " &
                      "DECLARED AND THAT IT IS A STATIC UNIVERSAL " &
                      "INTEGER");

     DECLARE
          MY_MSIZE : CONSTANT := SYSTEM.MEMORY_SIZE;

          I       : INTEGER RANGE -1 .. 1;
     BEGIN
          I := SYSTEM.MEMORY_SIZE - MY_MSIZE + 1;
      END;

     RESULT;
END AD7006A;
