-- AD7005A.ADA

-- OBJECTIVE:
--     CHECK THAT THE CONSTANT 'SYSTEM.STORAGE_UNIT' IS DECLARED AND
--     THAT IT IS A STATIC UNIVERSAL INTEGER.

-- HISTORY:
--     VCL  09/11/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE AD7005A IS
BEGIN
     TEST ("AD7005A", "THE CONSTANT 'SYSTEM.STORAGE_UNIT' IS " &
                      "DECLARED AND THAT IT IS A STATIC UNIVERSAL " &
                      "INTEGER");

     DECLARE
          MY_UNIT : CONSTANT := SYSTEM.STORAGE_UNIT;

          I       : INTEGER;
     BEGIN
          I := SYSTEM.STORAGE_UNIT + MY_UNIT;
      END;

     RESULT;
END AD7005A;
