-- AD7103C.ADA

-- OBJECTIVE:
--     CHECK THAT THE CONSTANT FINE_DELTA IS DECLARED WITHIN THE
--     PACKAGE SYSTEM, THAT ITS TYPE IS <UNIVERSAL_REAL>, AND THAT
--     ITS VALUE IS STATIC.

-- HISTORY:
--     BCB 09/10/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7103C IS

     U_DELTA : CONSTANT := SYSTEM.FINE_DELTA;

     TYPE S_DELTA IS DELTA SYSTEM.FINE_DELTA RANGE -1.0 .. 1.0;

BEGIN

     TEST ("AD7103C", "CHECK THAT THE CONSTANT FINE_DELTA IS " &
                      "DECLARED WITHIN THE PACKAGE SYSTEM, THAT ITS " &
                      "TYPE IS <UNIVERSAL_REAL>, AND THAT ITS " &
                      "VALUE IS STATIC");
     RESULT;

END AD7103C;
