-- AD7102A.ADA

-- OBJECTIVE:
--     CHECK THAT THE CONSTANT MAX_DIGITS IS DECLARED WITHIN THE
--     PACKAGE SYSTEM, THAT ITS TYPE IS <UNIVERSAL_INTEGER>, AND THAT
--     ITS VALUE IS STATIC.

-- HISTORY:
--     BCB 09/10/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7102A IS

     U_DIGITS : CONSTANT := SYSTEM.MAX_DIGITS;

     TYPE S_DIGITS IS RANGE 7 .. SYSTEM.MAX_DIGITS;

BEGIN

     TEST ("AD7102A", "CHECK THAT THE CONSTANT MAX_DIGITS IS " &
                      "DECLARED WITHIN THE PACKAGE SYSTEM, THAT ITS " &
                      "TYPE IS <UNIVERSAL_INTEGER>, AND THAT ITS " &
                      "VALUE IS STATIC");
     RESULT;

END AD7102A;
