-- AD7101A.ADA

-- OBJECTIVE:
--     CHECK THAT MIN_INT AND MAX_INT ARE DECLARED IN PACKAGE SYSTEM
--     AND THAT BOTH ARE STATIC AND HAVE TYPE <UNIVERSAL INTEGER>.

-- HISTORY:
--     JET 09/10/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7101A IS

U_MIN : CONSTANT := SYSTEM.MIN_INT;
U_MAX : CONSTANT := SYSTEM.MAX_INT;

TYPE S_MIN IS RANGE SYSTEM.MIN_INT .. 7;
TYPE S_MAX IS RANGE 7 .. SYSTEM.MAX_INT;

BEGIN

     TEST ("AD7101A", "CHECK THAT MIN_INT AND MAX_INT ARE DECLARED " &
                      "IN PACKAGE SYSTEM AND THAT BOTH ARE STATIC " &
                      "AND HAVE TYPE <UNIVERSAL INTEGER>");

     RESULT;

END AD7101A;
