-- AD7104A.ADA

-- OBJECTIVE:
--     CHECK THAT THE CONSTANT TICK IS DECLARED WITHIN THE PACKAGE
--     SYSTEM, THAT ITS TYPE IS <UNIVERSAL_REAL>, AND THAT ITS VALUE
--     IS STATIC.

-- HISTORY:
--     BCB 09/10/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7104A IS

     U_TICK: CONSTANT := SYSTEM.TICK;

     F : FLOAT := SYSTEM.TICK;

BEGIN

     TEST ("AD7104A", "CHECK THAT THE CONSTANT TICK IS DECLARED " &
                      "WITHIN THE PACKAGE SYSTEM, THAT ITS TYPE IS " &
                      "<UNIVERSAL_REAL>, AND THAT ITS VALUE IS STATIC");

     RESULT;

END AD7104A;
