-- AD7103A.ADA

-- OBJECTIVE:
--     CHECK THAT THE CONSTANT MAX_MANTISSA IS DECLARED WITHIN THE
--     PACKAGE SYSTEM, THAT ITS TYPE IS <UNIVERSAL_INTEGER>, AND THAT
--     ITS VALUE IS STATIC.

-- HISTORY:
--     BCB 09/10/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT;  USE REPORT;

PROCEDURE AD7103A IS

     U_MANTISSA : CONSTANT := SYSTEM.MAX_MANTISSA;

     TYPE S_MANTISSA IS RANGE 7 .. SYSTEM.MAX_MANTISSA;

BEGIN

     TEST ("AD7103A", "CHECK THAT THE CONSTANT MAX_MANTISSA IS " &
                      "DECLARED WITHIN THE PACKAGE SYSTEM, THAT ITS " &
                      "TYPE IS <UNIVERSAL_INTEGER>, AND THAT ITS " &
                      "VALUE IS STATIC");
     RESULT;

END AD7103A;
