-- AD7205B.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREFIX OF THE 'STORAGE_SIZE ATTRIBUTE CAN BE AN
--     ACCESS TYPE, A TASK TYPE, A TASK OBJECT, OR A SINGLE TASK.

-- HISTORY:
--     JET 09/22/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE AD7205B IS

     B : BOOLEAN;

     TYPE A IS ACCESS INTEGER;
     TASK TYPE T;
     T1 : T;
     TASK T2;

     TASK BODY T IS
     BEGIN
          NULL;
     END T;

     TASK BODY T2 IS
     BEGIN
          NULL;
     END T2;

BEGIN

     TEST ("AD7205B", "CHECK THAT THE PREFIX OF THE 'STORAGE_SIZE " &
                      "ATTRIBUTE CAN BE AN ACCESS TYPE, A TASK TYPE, " &
                      "A TASK OBJECT, OR A SINGLE TASK");

     B := A'STORAGE_SIZE = T'STORAGE_SIZE;   -- ACCESS AND TASK TYPES.
     B := T1'STORAGE_SIZE = T2'STORAGE_SIZE; -- TASK OBJECT & SINGLE
                                             --   TASK.

     RESULT;

END AD7205B;
