-- AD7206A.ADA

-- OBJECTIVE:
--     THE 'ADDRESS ATTRIBUTE IS DEFINED FOR OBJECTS HAVING ANY TYPE.

-- HISTORY:
--     DHH 09/02/88  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE AD7206A IS
     SUBTYPE MY_ADDRESS IS SYSTEM.ADDRESS;

-- SCALAR
     TYPE ENUM IS (RED, YELO, BLUE);
     A : ENUM;
     A1 : BOOLEAN := (A'ADDRESS IN MY_ADDRESS);
     A1A : CONSTANT ENUM := RED;
     A1B : BOOLEAN := (A1A'ADDRESS IN MY_ADDRESS);

     SUBTYPE INT IS INTEGER RANGE 1 .. 10;
     B : INT;
     B1 : BOOLEAN := (B'ADDRESS IN MY_ADDRESS);
     B1A : CONSTANT INT := 1;
     B1B : BOOLEAN := (B1A'ADDRESS IN MY_ADDRESS);

     TYPE FLOAT IS DIGITS 5;
     C : FLOAT;
     C1 : BOOLEAN := (C'ADDRESS IN MY_ADDRESS);
     C1A : CONSTANT FLOAT := 1.0;
     C1B : BOOLEAN := (C1A'ADDRESS IN MY_ADDRESS);

     TYPE FIXED IS DELTA 0.125 RANGE 1.0 .. 10.0;
     D : FIXED;
     D1 : BOOLEAN := (D'ADDRESS IN MY_ADDRESS);
     D1A : CONSTANT FIXED := 1.0;
     D1B : BOOLEAN := (D1A'ADDRESS IN MY_ADDRESS);

     SUBTYPE BOOL IS BOOLEAN;
     E : BOOL;
     E1 : BOOLEAN := (E'ADDRESS IN MY_ADDRESS);
     E1A : CONSTANT BOOL := TRUE;
     E1B : BOOLEAN := (E1A'ADDRESS IN MY_ADDRESS);

-- COMPOSITE
     TYPE REC IS
          RECORD
               X : INTEGER;
          END RECORD;
     F : REC;
     F1 : BOOLEAN := (F'ADDRESS IN MY_ADDRESS);
     F1A : CONSTANT REC := (X => 1);
     F1B : BOOLEAN := (F1A'ADDRESS IN MY_ADDRESS);

     TYPE ARR IS ARRAY(1 .. 3) OF BOOLEAN;
     G : ARR;
     G1 : BOOLEAN := (G'ADDRESS IN MY_ADDRESS);
     G1A : CONSTANT ARR := (TRUE, TRUE, TRUE);
     G1B : BOOLEAN := (G1A'ADDRESS IN MY_ADDRESS);

-- COMPOSITE COMPONENT
     F2 : BOOLEAN := (F.X'ADDRESS IN MY_ADDRESS);

-- COMPOSITE SLICE
     G2 : BOOLEAN := (G(1 .. 2)'ADDRESS IN MY_ADDRESS);

-- DISCRIMINANT
     TYPE REC1(DIS : INTEGER) IS
          RECORD
               X : INTEGER;
          END RECORD;
     I : REC1(2);
     I1 : BOOLEAN := (I'ADDRESS IN MY_ADDRESS);
     I1A : CONSTANT REC1(2) := (DIS => 2, X => 1);
     I1B : BOOLEAN := (I1A'ADDRESS IN MY_ADDRESS);

     TYPE ARR1 IS ARRAY(INTEGER RANGE <>) OF BOOLEAN;
     J : ARR1(1 .. 2);
     J1 : BOOLEAN := (J'ADDRESS IN MY_ADDRESS);
     J1A : CONSTANT ARR1(1 .. 2) := (TRUE, FALSE);
     J1B : BOOLEAN := (J1A'ADDRESS IN MY_ADDRESS);

     PACKAGE P IS
-- LIMITED
          TYPE LMTD IS LIMITED PRIVATE;

-- PRIVATE
          TYPE PRIV IS PRIVATE;
     PRIVATE
          TYPE LMTD IS NEW INTEGER;
          TYPE PRIV IS NEW INTEGER;
     END P;
     USE P;
     K : LMTD;
     K1 : BOOLEAN := (K'ADDRESS IN MY_ADDRESS);

     L : PRIV;
     L1 : BOOLEAN := (L'ADDRESS IN MY_ADDRESS);

-- ACCESS
     TYPE ACC_PRIV IS ACCESS PRIV;
     M : ACC_PRIV;
     M1 : BOOLEAN := (M'ADDRESS IN MY_ADDRESS);
     M1A : CONSTANT ACC_PRIV := NEW PRIV;
     M1B : BOOLEAN := (M1A'ADDRESS IN MY_ADDRESS);

-- GENERIC PARAMETERS AND OBJECTS
     GENERIC
          Q : INTEGER;
     PROCEDURE GEN_P(R : INTEGER);

-- TASK TYPE
     TASK TYPE TASK_T IS
     END TASK_T;
     O : TASK_T;
     O1 : BOOLEAN := (O'ADDRESS IN MY_ADDRESS);

-- TASK
     TASK N IS
     END N;

     TASK BODY N IS
         N1 : BOOLEAN := (N'ADDRESS IN MY_ADDRESS);
     BEGIN
          NULL;
     END;

     TASK BODY TASK_T IS
     BEGIN
          NULL;
     END;

     PROCEDURE PARAM(P : INTEGER) IS
          P1 : BOOLEAN;
     BEGIN
          P1 := (P'ADDRESS IN MY_ADDRESS);
     END;

     PROCEDURE GEN_P(R : INTEGER) IS
          Q1, R1 : BOOLEAN;
     BEGIN
          Q1 := Q'ADDRESS IN MY_ADDRESS;
          R1 := R'ADDRESS IN MY_ADDRESS;
     END GEN_P;

-- TASK ENTRY
     TASK ENT IS
          ENTRY ONE(T : INTEGER);
     END ENT;

     TASK BODY ENT IS
          T1 : BOOLEAN;
     BEGIN
          ACCEPT ONE(T : INTEGER) DO
               T1 := T'ADDRESS IN MY_ADDRESS;
          END ONE;
     END ENT;

BEGIN
     TEST ("AD7206A", "THE 'ADDRESS ATTRIBUTE IS DEFINED FOR OBJECTS " &
                      "HAVING ANY TYPE");
     PARAM(5);

-- LOOP PARAMETER
     FOR S IN 1 .. 1 LOOP
          A1 := S'ADDRESS IN MY_ADDRESS;
     END LOOP;

     ENT.ONE(5);

     RESULT;
END AD7206A;
