-- AD7201E.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREFIX OF THE 'ADDRESS ATTRIBUTE CAN DENOTE AN
--     ATTRIBUTE THAT IS A FUNCTION ('SUCC, 'PRED, 'POS, 'VAL,
--     'IMAGE, 'VALUE).

-- HISTORY:
--     DHH 10/25/88  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE AD7201E IS

     SUBTYPE MY_ADDRESS IS SYSTEM.ADDRESS;

BEGIN
     TEST ("AD7201E", "CHECK THAT THE PREFIX OF THE 'ADDRESS " &
                      "ATTRIBUTE CAN DENOTE AN " &
                      "ATTRIBUTE THAT IS A FUNCTION ('SUCC, 'PRED, " &
                      "'POS, 'VAL, 'IMAGE, 'VALUE)");
     DECLARE
          M1 : BOOLEAN := (BOOLEAN'PRED'ADDRESS IN MY_ADDRESS);
          N1 : BOOLEAN := (BOOLEAN'SUCC'ADDRESS IN MY_ADDRESS);
          O1 : BOOLEAN := INTEGER'VAL'ADDRESS IN MY_ADDRESS;
          P1 : BOOLEAN := INTEGER'IMAGE'ADDRESS IN MY_ADDRESS;
          Q1 : BOOLEAN := INTEGER'POS'ADDRESS IN MY_ADDRESS;
          R1 : BOOLEAN := INTEGER'VALUE'ADDRESS IN MY_ADDRESS;

     BEGIN
          NULL;
     END;

     RESULT;
END AD7201E;
