-- AE2101F.ADA

-- CHECK THAT DIRECT_IO CAN BE INSTANTIATED WITH
-- USER-DEFINED AND PREDEFINED TYPES, SPECIFICALLY, BOOLEAN, INTEGER,
-- CONSTRAINED STRING, ENUMERATED, CHARACTER, ACCESS, CONSTRAINED ARRAY,
-- RECORD WITHOUT DISCRIMINANTS, AND RECORD WITH DISCRIMINANTS IF THE
-- DISCRIMINANTS HAVE DEFAULTS (SEE AI-00037).

-- ABW  8/9/82
-- JRK 3/26/84
-- JBG 5/23/85

WITH REPORT;
USE REPORT;
WITH DIRECT_IO;

PROCEDURE AE2101F IS

BEGIN

     TEST( "AE2101F" , "CHECK THAT DIRECT_IO  " &
                       "CAN BE INSTANTIATED WITH PREDEFINED " &
                       "AND USER-DEFINED TYPES" );

     DECLARE

          TYPE BOOL IS NEW BOOLEAN;
          TYPE INT IS NEW INTEGER;
          TYPE STR IS NEW STRING (1..6);
          TYPE ENUM IS (ONE,TWO,THREE,FOUR,FIVE);
          TYPE CHAR IS NEW CHARACTER;
          TYPE ACC_INT IS ACCESS INTEGER;
          TYPE ARR_CN IS ARRAY (1..9) OF INTEGER;
          TYPE REC IS
               RECORD
                    COMP1 : INTEGER;
                    COMP2 : INTEGER;
               END RECORD;

          TYPE DEFREC (D : INTEGER := 0) IS
               RECORD
                    COMP1 : INTEGER := D;
                    CASE D IS
                         WHEN 1..INTEGER'LAST =>
                              COMP2 : INTEGER;
                         WHEN INTEGER'FIRST..0 =>
                              COMP3, COMP4 : INTEGER;
                    END CASE;
               END RECORD;

          PACKAGE DIR_BOOLEAN IS NEW DIRECT_IO (BOOLEAN);
          PACKAGE DIR_INTEGER IS NEW DIRECT_IO (INTEGER);
          PACKAGE DIR_BOOL    IS NEW DIRECT_IO (BOOL);
          PACKAGE DIR_INT     IS NEW DIRECT_IO (INT);
          PACKAGE DIR_STR     IS NEW DIRECT_IO (STR);
          PACKAGE DIR_ENUM    IS NEW DIRECT_IO (ENUM);
          PACKAGE DIR_CHAR    IS NEW DIRECT_IO (CHAR);
          PACKAGE DIR_ACC_INT IS NEW DIRECT_IO (ACC_INT);
          PACKAGE DIR_ARR_CN  IS NEW DIRECT_IO (ARR_CN);
          PACKAGE DIR_REC     IS NEW DIRECT_IO (REC);
          PACKAGE DIR_DEFREC  IS NEW DIRECT_IO (DEFREC);

     BEGIN
          NULL;
     END;

     RESULT;

END AE2101F;
