-- AE2101G.ADA

-- CHECK THAT DIRECT_IO CAN BE INSTANTIATED WITH FIXED AND FLOATING
-- POINT TYPES.

-- TBN 2/12/86

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE AE2101G IS

BEGIN

     TEST( "AE2101G" , "CHECK THAT DIRECT_IO CAN BE INSTANTIATED " &
                       "WITH FIXED AND FLOATING POINT TYPES" );

     DECLARE

          SUBTYPE FLT IS FLOAT;
          TYPE FIXED IS DELTA 0.5 RANGE 0.0..255.0;

          PACKAGE DIR_FLT IS NEW DIRECT_IO (FLT);
          PACKAGE DIR_FIXED IS NEW DIRECT_IO (FIXED);

     BEGIN
          NULL;
     END;

     RESULT;

END AE2101G;
