-- AE2101A.ADA

-- CHECK THAT SEQUENTIAL_IO CAN BE INSTANTIATED WITH
-- USER-DEFINED AND PREDEFINED TYPES, SPECIFICALLY, BOOLEAN, INTEGER,
-- CONSTRAINED STRING, ENUMERATED, CHARACTER, ACCESS, CONSTRAINED ARRAY,
-- RECORD WITHOUT DISCRIMINANTS, AND RECORD WITH DISCRIMINANTS IF THE
-- DISCRIMINANTS HAVE DEFAULTS (SEE AI-00037).

-- ABW  8/9/82
-- JRK 3/26/84
-- JBG 5/23/85

WITH REPORT;
USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE AE2101A IS

BEGIN

     TEST( "AE2101A" , "CHECK THAT SEQUENTIAL_IO  " &
                       "CAN BE INSTANTIATED WITH PREDEFINED " &
                       "AND USER-DEFINED TYPES" );

     DECLARE

          TYPE BOOL IS NEW BOOLEAN;
          TYPE INT IS NEW INTEGER;
          TYPE STR IS NEW STRING (1..6);
          TYPE ENUM IS (ONE,TWO,THREE,FOUR,FIVE);
          TYPE CHAR IS NEW CHARACTER;
          TYPE ACC_INT IS ACCESS INTEGER;
          TYPE ARR_CN IS ARRAY (1..9) OF INTEGER;
          TYPE REC IS
               RECORD
                    COMP1 : INTEGER;
                    COMP2 : INTEGER;
               END RECORD;

          TYPE DEFREC (D : INTEGER := 0) IS
               RECORD
                    COMP1 : INTEGER := D;
                    CASE D IS
                         WHEN 1..INTEGER'LAST =>
                              COMP2 : INTEGER;
                         WHEN INTEGER'FIRST..0 =>
                              COMP3, COMP4 : INTEGER;
                    END CASE;
               END RECORD;

          PACKAGE SEQ_BOOLEAN IS NEW SEQUENTIAL_IO (BOOLEAN);
          PACKAGE SEQ_INTEGER IS NEW SEQUENTIAL_IO (INTEGER);
          PACKAGE SEQ_BOOL    IS NEW SEQUENTIAL_IO (BOOL);
          PACKAGE SEQ_INT     IS NEW SEQUENTIAL_IO (INT);
          PACKAGE SEQ_STR     IS NEW SEQUENTIAL_IO (STR);
          PACKAGE SEQ_ENUM    IS NEW SEQUENTIAL_IO (ENUM);
          PACKAGE SEQ_CHAR    IS NEW SEQUENTIAL_IO (CHAR);
          PACKAGE SEQ_ACC_INT IS NEW SEQUENTIAL_IO (ACC_INT);
          PACKAGE SEQ_ARR_CN  IS NEW SEQUENTIAL_IO (ARR_CN);
          PACKAGE SEQ_REC     IS NEW SEQUENTIAL_IO (REC);
          PACKAGE SEQ_DEFREC  IS NEW SEQUENTIAL_IO (DEFREC);

     BEGIN
          NULL;
     END;

     RESULT;

END AE2101A;
