-- AE2101B.ADA

-- CHECK THAT SEQUENTIAL_IO CAN BE INSTANTIATED WITH FIXED AND
-- FLOATING POINT TYPES.

-- ABW  8/9/82
-- TBN 2/12/86     SPLIT TEST.  PUT DIRECT_IO INTO AE2101G-B.ADA.

WITH REPORT ; USE REPORT ;
WITH SEQUENTIAL_IO ;

PROCEDURE AE2101B IS

BEGIN

     TEST( "AE2101B" , "CHECK THAT SEQUENTIAL_IO CAN BE INSTANTIATED " &
                       "WITH FIXED AND FLOATING POINT TYPES" ) ;

     DECLARE

          SUBTYPE FLT IS FLOAT ;
          TYPE FIXED IS DELTA 0.5 RANGE 0.0..255.0 ;

          PACKAGE SEQ_FLT IS NEW SEQUENTIAL_IO (FLT) ;
          PACKAGE SEQ_FIXED IS NEW SEQUENTIAL_IO (FIXED) ;

     BEGIN
          NULL ;
     END ;

     RESULT ;

END AE2101B ;
