-- AE2101D.ADA

-- CHECK THAT SEQUENTIAL_IO CAN BE INSTANTIATED WITH A PRIVATE TYPE.

-- ABW  8/9/82
-- SPS 9/15/82
-- TBN 2/12/86     SPLIT TEST.  PUT DIRECT_IO INTO AE2101I-B.ADA.

WITH REPORT ; USE REPORT ;
WITH SEQUENTIAL_IO ;

PROCEDURE AE2101D IS

BEGIN

     TEST( "AE2101D" , "CHECK THAT SEQUENTIAL_IO CAN BE INSTANTIATED " &
                       "WITH A PRIVATE TYPE" ) ;

     DECLARE

          PACKAGE PKG IS
               TYPE PRIV IS PRIVATE ;
          PRIVATE
               TYPE PRIV IS NEW BOOLEAN ;
          END PKG ;

          USE PKG ;

          PACKAGE SEQ IS NEW SEQUENTIAL_IO (PRIV) ;

     BEGIN
          NULL ;
     END ;

     RESULT ;

END AE2101D ;
