-- AE2101I.ADA

-- CHECK THAT DIRECT_IO CAN BE INSTANTIATED WITH A PRIVATE TYPE.

-- TBN 2/12/86

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE AE2101I IS

BEGIN

     TEST( "AE2101I" , "CHECK THAT DIRECT_IO CAN BE INSTANTIATED " &
                       "WITH A PRIVATE TYPE" );

     DECLARE

          PACKAGE PKG IS
               TYPE PRIV IS PRIVATE;
          PRIVATE
               TYPE PRIV IS NEW BOOLEAN;
          END PKG;

          USE PKG;

          PACKAGE DIR IS NEW DIRECT_IO (PRIV);

     BEGIN
          NULL;
     END;

     RESULT;

END AE2101I;
