-- AE3002G.ADA

-- CHECK THAT FILE_MODE IS VISIBLE AND HAS LITERALS IN_FILE AND
-- OUT_FILE.  ASLO CHECK THAT TYPE_SET IS VISIBLE AND HAS LITERALS
-- LOWER_CASE AND UPPER_CASE.

-- TBN  10/3/86

WITH TEXT_IO; USE TEXT_IO;
WITH REPORT; USE REPORT;
PROCEDURE AE3002G IS

     TEMP_FILE : FILE_TYPE;
     MODE : FILE_MODE := IN_FILE;
     LETTERS : TYPE_SET := LOWER_CASE;

BEGIN
     TEST ("AE3002G", "CHECK THAT FILE_MODE AND TYPE_SET ARE VISIBLE " &
                      "AND CHECK THEIR LITERALS");

     MODE := OUT_FILE;
     LETTERS := UPPER_CASE;

     RESULT;
END AE3002G;
