-- AE3709A.ADA

-- CHECK THE NAMES OF THE FORMAL PARAMETERS.

-- JBG 3/30/83

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;

PROCEDURE AE3709A IS

     PACKAGE INT IS NEW INTEGER_IO(INTEGER);
     USE INT;
     FILE : FILE_TYPE;
     STR  : STRING(1..3);
     LAST : POSITIVE;
     ITEM : INTEGER;

BEGIN

     TEST ("AE3709A", "CHECK NAMES OF FORMAL PARAMETERS");

     IF EQUAL(2, 3) THEN
          GET (FILE => FILE, ITEM => ITEM, WIDTH => 0);
          GET (ITEM => ITEM, WIDTH => 0);
          PUT (FILE => FILE, ITEM => ITEM, WIDTH => 4, BASE => 4);
          PUT (ITEM => ITEM, WIDTH => 4, BASE => 4);
          GET (FROM => STR, ITEM => ITEM, LAST => LAST);
          PUT (TO   => STR, ITEM => ITEM, BASE => 4);
     END IF;

     RESULT;

END AE3709A;
