-- AE3702A.ADA

-- CHECK THAT INTEGER_IO CAN BE INSTANTIATED FOR USER DEFINED INTEGER
-- TYPES.

-- SPS 10/1/82

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;

PROCEDURE AE3702A IS
BEGIN

     TEST ("AE3702A", "CHECK THAT INTEGER_IO CAN BE INSTANTIATED FOR " &
                      "USER DEFINED TYPES");

     DECLARE
          TYPE I1 IS RANGE 6 .. 14;
          TYPE I2 IS NEW INTEGER;
          TYPE I3 IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
          SUBTYPE S1 IS INTEGER RANGE 6 .. 14;
          SUBTYPE S2 IS INTEGER;
          SUBTYPE S3 IS INTEGER RANGE 0 .. INTEGER'LAST;

          PACKAGE NIO1 IS NEW INTEGER_IO (I1);
          PACKAGE NIO2 IS NEW INTEGER_IO (I2);
          PACKAGE NIO3 IS NEW INTEGER_IO (I3);
          PACKAGE NIO4 IS NEW INTEGER_IO (S1);
          PACKAGE NIO5 IS NEW INTEGER_IO (S2);
          PACKAGE NIO6 IS NEW INTEGER_IO (S3);

     BEGIN
          NULL;
     END;

     RESULT;
END AE3702A;
