-- B22004A.ADA

-- CHECK THAT IDENTIFIERS (INCLUDING RESERVED WORDS), INTEGER LITERALS,
-- AND COMPOUND SYMBOLS CANNOT CONTAIN SPACES.

-- JRK 12/12/79
-- JWC 6/28/85   RENAMED TO -AB

PROCEDURE B22004A IS

        AB CD : INTEGER;                -- ERROR: AB CD
        I1 : INTEGER RAN GE 1..10;      -- ERROR: RAN GE
        I2 : INTEGER := 12 3;           -- ERROR: 12 3
        I3 : INTEGER := 16# A3#;        -- ERROR: 16# A3#
        I4 : INTEGER : = 3;             -- ERROR: : =

BEGIN
        NULL;
END B22004A;
