-- B22001H.ADA

-- CHECK THAT AN IDENTIFIER, RESERVED WORD, COMPOUND SYMBOL,
--  INTEGER LITERAL, CHARACTER LITERAL, STRING LITERAL, OR COMMENT 
--  CANNOT BE CONTINUED ACROSS A LINE BOUNDARY.

-- COMMENT CROSSES LINE BOUNDARY.

-- DCB 12/18/79
-- JRK 4/21/80
-- JRK 12/16/80
-- CPP 5/23/84

PROCEDURE B22001H IS

     TYPE INTE IS NEW INTEGER;
     I  : INTEGER;
     EX : INTEGER;
     I1 : INTEGER;
     B1 : BOOLEAN;
     C1 : CHARACTER;
     S1 : STRING (1..6);

     I2 : INTEGER;
     I3 : INTEGER;

BEGIN

     -- THIS COMMENT WILL BE ILLEGAL BECAUSE IT WILL CROSS A LINE
BOUNDARY.;            -- ERROR: PRECEDING COMMENT CROSSES LINE BOUNDARY.
     NULL;

END B22001H;
