-- B22005U.ADA

-- CHECK THAT CONTROL CHARACTERS, EXCLUDING FORMAT EFFECTORS, ARE 
-- ILLEGAL OUTSIDE OF CHARACTER LITERALS, STRING LITERALS, AND COMMENTS.
-- THIS TEST CHECKS NAK (CTRL U).

-- AH 8/7/86

PROCEDURE B22005U IS
     TYPE INT_TYPE IS RANGE 1..5;     -- ERROR: BAD CHAR BEFORE "TYPE".
     I1 : INT_TYPE; 
BEGIN
     I1 := 2;                        
     I1 := I1 + 3;
END B22005U;
