-- B22003B.ADA

-- OBJECTIVE:
--     CHECK THAT AT LEAST ONE SPACE MUST SEPARATE ADJACENT IDENTIFIERS
--     (INCLUDING RESERVED WORDS) AND/OR NUMBERS.  THIS TEST CONTAINS
--     CHECK FOR THE RESERVED WORD 'RANGE'.

-- HISTORY:
--     DWC 10/02/87  CREATED ORIGINAL TEST FROM SPLIT OF B22003A.ADA.

PROCEDURE B22003B IS

        I : INTEGERRANGE 1..10;         -- ERROR: INTEGERRANGE
        J : INTEGER RANGE1..10;         -- ERROR: RANGE1

BEGIN

     NULL;

END B22003B;
