-- B22005P.ADA

-- CHECK THAT CONTROL CHARACTERS, EXCLUDING FORMAT EFFECTORS, ARE 
-- ILLEGAL OUTSIDE OF CHARACTER LITERALS, STRING LITERALS, AND COMMENTS.
-- THIS TEST CHECKS DLE (CTRL P).

-- AH 8/7/86

PROCEDURE B22005P IS
     TYPE INT_TYPE IS RANGE 1..5;     
     I1 : INT_TYPE;                   -- ERROR: BAD CHAR AFTER ";".
BEGIN
     I1 := 2;                        
     I1 := I1 + 3;
END B22005P;
