-- B22005Q.ADA

-- CHECK THAT CONTROL CHARACTERS, EXCLUDING FORMAT EFFECTORS, ARE 
-- ILLEGAL OUTSIDE OF CHARACTER LITERALS, STRING LITERALS, AND COMMENTS.
-- THIS TEST CHECKS DC1 (CTRL Q).

-- AH 8/7/86

PROCEDURE B22005Q IS
     TYPE INT_TYPE IS RANGE 1..5;     
     I1 : INT_TYPE; 
BEGIN
     I1 :=  2;                        -- ERROR: BAD CHAR BEFORE "2".
     I1 := I1 + 3;
END B22005Q;
