-- B23004B.ADA

-- CHECK THAT ? $ @ ARE NOT ALLOWED IN IDENTIFIERS.

-- DCB 12/19/79
-- JRK 10/23/80
-- JWC 6/28/85   RENAMED TO -AB

PROCEDURE B23004B IS

     I1   : INTEGER;
     I?2  : INTEGER;   -- ERROR: ? IN MIDDLE
     I3   : INTEGER;
     I$4  : INTEGER;   -- ERROR: $ IN MIDDLE
     I5   : INTEGER;
     I@6  : INTEGER;   -- ERROR: @ IN MIDDLE
     I11  : INTEGER;
     ?I14 : INTEGER;   -- ERROR: ? LEADING
     I14A : INTEGER;
     $I12 : INTEGER;   -- ERROR: $ LEADING
     I12A : INTEGER;
     @I14 : INTEGER;   -- ERROR: @ LEADING
     I15  : INTEGER;
     I16? : INTEGER;   -- ERROR: ? TRAILING
     I17  : INTEGER;
     I18$ : INTEGER;   -- ERROR: $ TRAILING
     I19  : INTEGER;
     I20@ : INTEGER;   -- ERROR: @ TRAILING
     I21  : INTEGER;

BEGIN

     NULL;
     I?2  := 0;     -- ERROR: ? IN MIDDLE
     NULL;
     I$4  := 0;     -- ERROR: $ IN MIDDLE
     NULL;
     I@6  := 0;     -- ERROR: @ IN MIDDLE
     NULL;

END B23004B;
