-- B24001C.ADA

-- CHECK THAT UNDERSCORES ARE NOT PERMITTED TO:
--     A. BE CONSECUTIVE WITHIN A FIXED POINT LITERAL,
--     B. LEAD OR TRAIL IN A FIXED POINT LITERAL,
--     C. BE ADJACENT TO THE . E + - # CHARACTERS IN A FIXED
--        POINT LITERAL.

-- DCB 04/22/80
-- JRK 10/27/80
-- TBN 10/16/85     RENAMED FROM B24001C.ADA; ADDED TRAILING # CASES.

PROCEDURE B24001C IS

     TYPE FIXED IS DELTA 0.1 RANGE 0.0 .. 100.0;
     F1, F2 : FIXED;

BEGIN

     F1 := 1__2.3;      -- ERROR: CONSECUTIVE UNDERSCORES IN A
                        --        FIXED POINT LITERAL
     NULL;
     F1 := 1.2__3;      -- ERROR: CONSECUTIVE UNDERSCORES IN A
                        --        FIXED POINT LITERAL
     NULL;
     F1 := 1.2E0__1;    -- ERROR: CONSECUTIVE UNDERSCORES IN A
                        --        FIXED POINT LITERAL
     NULL;
     F1 := 16#1__2.A#;  -- ERROR: CONSECUTIVE UNDERSCORES IN A
                        --        FIXED POINT LITERAL
     NULL;
     F1 := _1.2;        -- ERROR: UNDERSCORE LEADS A FIXED POINT
                        --        LITERAL
     NULL;
     F1 := 1.2_;        -- ERROR: UNDERSCORE TRAILS A FIXED POINT
                        --        LITERAL
     NULL;
     F1 := 1.2E1_;      -- ERROR: UNDERSCORE TRAILS A FIXED POINT
                        --        LITERAL
     NULL;
     F1 := 12_.1;       -- ERROR: UNDERSCORE ADJACENT TO .
     NULL;
     F1 := 12._1;       -- ERROR: UNDERSCORE ADJACENT TO .
     NULL;
     F1 := 2.0_E1;      -- ERROR: UNDERSCORE ADJACENT TO E
     NULL;
     F2 := 2.0E_1;      -- ERROR: UNDERSCORE ADJACENT TO E
     NULL;
     F1 := 2.0E+_1;     -- ERROR: UNDERSCORE ADJACENT TO +
     NULL;
     F2 := 2.0E_+1;     -- ERROR: UNDERSCORE ADJACENT TO +
     NULL;
     F1 := 2.0E-_1;     -- ERROR: UNDERSCORE ADJACENT TO -
     NULL;
     F2 := 2.0E_-1;     -- ERROR: UNDERSCORE ADJACENT TO -
     NULL;
     F2 := 16_#2.A#;    -- ERROR: UNDERSCORE ADJACENT TO #
     NULL;
     F2 := 16#_2.A#;    -- ERROR: UNDERSCORE ADJACENT TO #
     NULL;
     F2 := 16#2.A_#;    -- ERROR: UNDERSCORE ADJACENT TO #
     NULL;
     F2 := 16#2.A#_;    -- ERROR: UNDERSCORE ADJACENT TO #
     NULL;

END B24001C;
