-- B24204D.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF AN INTEGER LITERAL
--     ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B24204A.ADA.

PROCEDURE B24204D IS

        I  : INTEGER;

BEGIN

        I := 3A;                -- ERROR: 3A
        I := 0A#2#;             -- ERROR: 0A#2#
        I := 2E1A;              -- ERROR: 2E1A

END B24204D;
