-- B24204F.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF A FIXED POINT
--     LITERAL ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE.
--     THIS TEST CHECKS LITERALS WITH BASES OTHER THAN 10.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B24204C.ADA.

PROCEDURE B24204F IS

        TYPE FIXED IS DELTA 0.1 RANGE 0.0 .. 100.0;

        F : FIXED;

BEGIN

        F := 7#7.6#;            -- ERROR: 7#7.6#
        F := 9#8.9#;            -- ERROR: 9#8.9#

END B24204F;
