-- B24204E.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF A FLOATING POINT
--     LITERAL ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE.
--     THIS TEST CHECKS THE CASE WHEN THE BASE IS NOT 10.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B24204B.ADA.

PROCEDURE B24204E IS

        F : FLOAT;

BEGIN

        F := 7#7.6#;            -- ERROR: 7#7.6#
        F := 9#8.9#;            -- ERROR: 9#8.9#

END B24204E;
