-- B24211B.ADA

-- OBJECTIVE:
--     CHECK THAT ILLEGAL FORMS INVOLVING A DIGIT FOLLOWED BY A COLON
--     ARE CORRECTLY ANALYZED USING A TWO CHARACTER LOOK-AHEAD.

-- HISTORY:
--     LDC 06/07/88 CREATED ORIGINAL TEST.

PROCEDURE B24211B IS

     LDC : INTEGER RANGE 0 .. 2:10::= 1;
     LLZ : INTEGER RANGE 0 .. 2:10:= 1;                -- ERROR:
     LLC : INTEGER RANGE 2#0# .. 2:10::= 1;

BEGIN
     NULL;
END B24211B;
