-- B28006E.ADA

--OBJECTIVE:
--     CHECK THAT AN UNRECOGNIZED PRAGMA IS REJECTED IF IT HAS
--     ARGUMENTS THAT ARE NOT NAMES OR EXPRESSIONS. THIS TEST CHECKS THE
--     CASE IN WHICH THE ARGUMENT IS AN EMPTY LIST. (THIS TEST IS A
--     VARIATION OF B28006A.)

--HISTORY:
--     DHH 01/19/88 CREATED ORIGINAL TEST.

PROCEDURE B28006E IS

BEGIN
     PRAGMA ADAM_AND_CARA_HAWKINS();                          -- ERROR:
     NULL;
END B28006E;
