-- B28001F.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED AS THE ONLY STATEMENT IN A 
-- SEQUENCE OF STATEMENTS IN AN IF STATEMENT.

-- TBN 5/28/86

PROCEDURE B28001F IS

     CHOICE : BOOLEAN := TRUE;

BEGIN
     IF CHOICE THEN
          PRAGMA LIST (ON);
     END IF;                                -- ERROR: MISSING STATEMENT.
END B28001F;
