-- B28001W.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- EXCEPTION HANDLER IN A SEQUENCE OF HANDLERS IN A BLOCK STATEMENT.

-- TBN  9/11/86

PROCEDURE B28001W IS

     A : INTEGER := 1;

BEGIN
     BEGIN
          A := A + 1;
     EXCEPTION
          PRAGMA ROSA_WILLIAMS;
     END;                                     -- ERROR: MISSING HANDLER.
END B28001W;
