-- B28001N.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED AS THE ONLY STATEMENT IN A
-- SEQUENCE OF STATEMENTS IN AN ACCEPT STATEMENT.

-- TBN  9/11/86

PROCEDURE B28001N IS

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS
     BEGIN
          ACCEPT E1 DO
               PRAGMA LIST (ON);
          END E1;                           -- ERROR: MISSING STATEMENT.
     END T1;

BEGIN
     NULL;
END B28001N;
