-- B28001M.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- STATEMENT IN A SEQUENCE OF STATEMENTS IN A TASK BODY.

-- TBN  9/11/86

PROCEDURE B28001M IS

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS
     BEGIN
          PRAGMA LEE_BROWN;
     END T1;                                -- ERROR: MISSING STATEMENT.

BEGIN
     NULL;
END B28001M;
