-- B28001T.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED AS THE ONLY SELECT ALTERNATIVE
-- IN A SEQUENCE OF ALTERNATIVES IN A SELECTIVE WAIT STATEMENT.

-- TBN  9/11/86
-- GMT  6/29/87 CHANGED "STATEMENT" TO "ALTERNATIVE" IN ERROR COMMENT.

PROCEDURE B28001T IS

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS
     BEGIN
          SELECT
               PRAGMA LIST (ON);
          END SELECT;                     -- ERROR: MISSING ALTERNATIVE.
     END T1;

BEGIN
     NULL;
END B28001T;
