-- B28001S.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY CASE
-- STATEMENT ALTERNATIVE IN A SEQUENCE OF ALTERNATIVES IN A CASE
-- STATEMENT.

-- TBN 6/3/86
-- GMT 6/29/87 CHANGED "STATEMENT" TO "ALTERNATIVE" IN ERROR COMMENT.

PROCEDURE B28001S IS

     CHOICE : BOOLEAN := TRUE;

BEGIN
     CASE CHOICE IS
          PRAGMA ROSA_WILLIAMS;
     END CASE;                       -- ERROR: MISSING ALTERNATIVE.
END B28001S;
