-- B28001P.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED AS THE ONLY STATEMENT IN A 
-- SEQUENCE OF STATEMENTS IN THE ELSE PART OF A CONDITIONAL ENTRY
-- CALL STATEMENT.

-- TBN 5/28/86

PROCEDURE B28001P IS

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS
     BEGIN
          NULL;
     END T1;

BEGIN
     SELECT
          T1.E1;
     ELSE
          PRAGMA LIST (ON);
     END SELECT;                            -- ERROR: MISSING STATEMENT.
END B28001P;
