-- B28001O.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- STATEMENT IN A SEQUENCE OF STATEMENTS IN THE ELSE PART OF A
-- SELECTIVE WAIT STATEMENT.

-- TBN 6/3/86

PROCEDURE B28001O IS

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS
     BEGIN
          SELECT
               ACCEPT E1;
          ELSE
               PRAGMA PHIL_BRASHEAR;
          END SELECT;                       -- ERROR: MISSING STATEMENT.

          NULL;
     END T1;

BEGIN
     NULL;
END B28001O;
