-- B28001K.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- STATEMENT IN A SEQUENCE OF STATEMENTS IN A FUNCTION BODY.

-- TBN  9/11/86

PROCEDURE B28001K IS

     FUNCTION P RETURN INTEGER IS
     BEGIN
          PRAGMA PHIL_BRASHEAR;
     END P;                                 -- ERROR: MISSING STATEMENT.

BEGIN
     NULL;
END B28001K;
