-- B28001G.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- STATEMENT IN A SEQUENCE OF STATEMENTS IN A CASE STATEMENT.

-- TBN  9/11/86

PROCEDURE B28001G IS

     CHOICE : BOOLEAN := TRUE;

BEGIN
     CASE CHOICE IS
          WHEN TRUE =>
               PRAGMA ROSA_WILLIAMS;
          WHEN OTHERS =>                    -- ERROR: MISSING STATEMENT.
               NULL;
     END CASE;
END B28001G;
