-- B28001C.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED IN AN ACTUAL
-- PARAMETER PART.

-- TBN  9/11/86

PROCEDURE B28001C IS

     FUNCTION P RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END P;

     PROCEDURE P (X : INTEGER) IS
     BEGIN
          NULL;
     END P;

BEGIN
     P (PRAGMA HEATHER_TILTON; 1);         -- ERROR: POSITION OF PRAGMA.
     P (2);
     NULL;
END B28001C;
