-- B28001Q.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- STATEMENT IN A SEQUENCE OF STATEMENTS IN AN EXCEPTION HANDLER.

-- TBN  9/11/86

PROCEDURE B28001Q IS

     A : INTEGER := 1;

BEGIN
     A := A + 1;
EXCEPTION
     WHEN OTHERS =>
          PRAGMA TERESA_BANKS;
END B28001Q;                                -- ERROR: MISSING STATEMENT.
