-- B28001I.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED AS THE ONLY
-- STATEMENT IN A SEQUENCE OF STATEMENTS IN A BLOCK STATEMENT.

-- TBN 6/3/86

PROCEDURE B28001I IS

BEGIN
     BEGIN
          PRAGMA ROSA_WILLIAMS;
     END;                                   -- ERROR: MISSING STATEMENT.
END B28001I;
