-- B28001R.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED AS THE ONLY COMPONENT
-- DECLARATION IN A SEQUENCE OF COMPONENT DECLARATIONS IN A RECORD
-- TYPE DEFINITION.

-- TBN  9/11/86
-- GMT  6/29/87   CHANGED "STATEMENT" TO "COMPONENT DECLARATION" IN
--                THE ERROR COMMENT.


PROCEDURE B28001R IS

     TYPE REC1 IS
          RECORD
               PRAGMA LIST (ON);
          END RECORD;           -- ERROR: MISSING COMPONENT DECLARATION.

BEGIN
     NULL;
END B28001R;
