-- B28001D.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED IN A DISCRIMINANT PART.

-- TBN 2/18/86

PROCEDURE B28001D IS

     TYPE R (PRAGMA LIST(ON); D : INTEGER) IS         -- ERROR: POSITION
          RECORD                                      -- OF PRAGMA.
               POS : INTEGER;
          END RECORD;

BEGIN
     NULL;
END B28001D;
