-- B28001B.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED IN A STATEMENT.

-- TBN 2/18/86

PROCEDURE B28001B IS

     B : INTEGER;

     FUNCTION P RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END P;

     PROCEDURE P IS
     BEGIN
          NULL;
     END P;

BEGIN
     B := PRAGMA LIST (ON);                -- ERROR: POSITION OF PRAGMA.
     P;
     NULL;
END B28001B;
