-- B28006A.ADA

--OBJECTIVE:
--     CHECK THAT AN UNRECOGNIZED PRAGMA IS REJECTED IF IT HAS
--     ARGUMENTS THAT ARE NOT NAMES OR EXPRESSIONS. THIS TEST CHECKS
--     THE CASE WHERE ONE OF THE ARGUMENTS IS INVALID.

--HISTORY:
--     DHH 01/19/88 CREATED ORIGINAL TEST.

PROCEDURE B28006A IS

     PRAGMA CONNIE_HAWKINS(5**2,=);                          -- ERROR:

BEGIN
     NULL;
END B28006A;
