-- B28001A.ADA

-- CHECK THAT AN UNRECOGNIZED PRAGMA IS NOT ALLOWED IN AN EXPRESSION.

-- TBN 2/18/86

PROCEDURE B28001A IS

     A : INTEGER := 1;

     FUNCTION P RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END P;

     PROCEDURE P IS
     BEGIN
          NULL;
     END P;

BEGIN
     A := 2 * PRAGMA THOMAS_NORRIS;        -- ERROR: POSITION OF PRAGMA.
     P;
     NULL;
END B28001A;
