-- B28006F1.TST

-- OBJECTIVE:
--     CHECK THAT THE PRESENCE OF A PRAGMA INCLUDE DOES NOT CAUSE AN
--     OTHERWISE ILLEGAL PROGRAM TO BECOME LEGAL.

-- THIS FILE IS THE PARAMETER OF THE PRAGMA INCLUDE IN THE TEST
-- B28006F0M.TST.  IF THE PRAGMA IS SUPPORTED, THIS PROCEDURE CAUSES
-- THE TEST TO COMPILE WITHOUT ERRORS, WHICH IS INCORRECT BEHAVIOR.

-- HISTORY:
--     BCB 08/10/88  CREATED ORIGINAL TEST.

PROCEDURE B28006F_PROC IS
BEGIN
     NULL;
END B28006F_PROC;
