-- B28001H.ADA

-- CHECK THAT PRAGMA LIST IS NOT ALLOWED AS THE ONLY STATEMENT IN A 
-- SEQUENCE OF STATEMENTS IN A LOOP STATEMENT.

-- TBN 5/28/86

PROCEDURE B28001H IS

     CHOICE : BOOLEAN := TRUE;

BEGIN
     FOR I IN 1 .. 10 LOOP
          PRAGMA LIST (ON);
     END LOOP;                              -- ERROR: MISSING STATEMENT.
END B28001H;
