-- B2A003D.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF AN INTEGER LITERAL
--     ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE WHEN COLONS
--     ARE USED INSTEAD OF SHARPS.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT TO B2A003A.ADA.

PROCEDURE B2A003D IS

        I  : INTEGER;

BEGIN

        I := 3A;                -- ERROR: 3A
        I := 0A:2:;             -- ERROR: 0A:2:
        I := 2E1A;              -- ERROR: 2E1A

END B2A003D;
