-- B2A003E.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF A FLOATING POINT
--     LITERAL ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE WHEN
--     COLONS ARE USED INSTEAD OF SHARPS.
--     THIS TEST CHECKS BASES OTHER THAN BASE 10.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B2A003B.ADA.

PROCEDURE B2A003E IS

        F : FLOAT;

BEGIN

        F := 7:7.6:;            -- ERROR: 7:7.6:
        F := 9:8.9:;            -- ERROR: 9:8.9:

END B2A003E;
