-- B2A003C.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF A FIXED POINT
--     LITERAL ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE WHEN
--     LITERAL USED INSTEAD OF SHARPS.
--     THIS TEST CHECKS FOR BASE 10 LITERALS.

-- HISTORY:
--     JRK 04/21/80
--     JRK 10/27/80
--     JBG 05/25/85
--     DWC 09/22/87  MOVED CHECKS INVOLVING BASES OTHER THAN BASE 10
--                   TO B2A003F.ADA.

PROCEDURE B2A003C IS

        TYPE FIXED IS DELTA 0.1 RANGE 0.0 .. 100.0;

        F : FIXED;

BEGIN

        F := 3A.5;              -- ERROR: 3A.5
        F := 3.0A1;             -- ERROR: 3.0A1
        F := 0.3E1A;            -- ERROR: 0.3E1A
        F := 0A:2.3:;           -- ERROR: 0A:2.3:

END B2A003C;
