-- B2A003B.ADA

-- OBJECTIVE:
--     CHECK THAT THE DIGITS AND EXTENDED_DIGITS OF A FLOATING POINT
--     LITERAL ARE WITHIN THE CORRECT RANGE FOR THE NUMBER'S BASE WHEN
--     COLONS ARE USED INSTEAD OF SHARPS.
--     THIS TEST CHECKS BASE 10 LITERALS.

-- HISTORY:
--     JRK 04/21/80
--     JRK 10/27/80
--     JBG 05/25/85
--     DWC 09/22/87  MOVED CHECKS INVOLVING BASES OTHER THAN 10
--                   TO B2A003E.ADA.

PROCEDURE B2A003B IS

        F : FLOAT;

BEGIN

        F := 3A.5;              -- ERROR: 3A.5
        F := 3.0A1;             -- ERROR: 3.0A1
        F := 0.3E1A;            -- ERROR: 0.3E1A
        F := 0A:2.3:;           -- ERROR: 0A:2.3:

END B2A003B;
