-- B32103A.ADA

-- CHECK THAT CONSTANT OBJECT DECLARATIONS MUST HAVE AN EXPLICIT
-- INITIALIZATION, EVEN WHEN DEFAULT VALUES EXIST FOR THE TYPE
-- OR FOR EACH COMPONENT.

-- DAT 3/17/81
-- SPS 2/4/83

PROCEDURE B32103A IS

     TYPE TA IS ACCESS INTEGER;
     TYPE AA IS ARRAY (BOOLEAN) OF TA;
     TYPE REC IS
          RECORD
               C : INTEGER := 1;
          END RECORD;

     CX : CONSTANT INTEGER;                  -- ERROR: UNINITIALIZED.
     CY : CONSTANT BOOLEAN;                  -- ERROR: UNINITIALIZED.
     CZ : CONSTANT CHARACTER;                -- ERROR: UNINITIALIZED.
     C1 : CONSTANT TA;                       -- ERROR: UNINITIALIZED.
     C2 : CONSTANT AA;                       -- ERROR: UNINITIALIZED.
     C3 : CONSTANT REC;                      -- ERROR: UNINITIALIZED.
     C4 : CONSTANT ARRAY (1..1) OF TA;       -- ERROR: UNINITIALIZED.

     PACKAGE P IS

          TYPE P IS PRIVATE;
          TYPE ENUM IS (A);
          TYPE TA IS ACCESS P;
          TYPE AA IS ARRAY (BOOLEAN) OF TA;
          TYPE REC IS
               RECORD
                    C : INTEGER := 1;
               END RECORD;

          C1 : CONSTANT TA;                  -- ERROR: UNINITIALIZED.
          C2 : CONSTANT AA;                  -- ERROR: UNINITIALIZED.
          C3 : CONSTANT REC;                 -- ERROR: UNINITIALIZED.
          C4 : CONSTANT ARRAY (1..1) OF TA;  -- ERROR: UNINITIALIZED.
          C5 : CONSTANT ENUM;                -- ERROR: UNINITIALIZED.

     PRIVATE
          TYPE P IS ARRAY (1..1) OF BOOLEAN;
     END P;

BEGIN
     NULL;
END B32103A;
