-- B33002A.ADA

-- CHECK THAT COMPILER ALLOWS LEGAL RECURSIVE TYPES
-- AND DISALLOWS ILLEGAL RECURSIVE TYPES.

-- GOM 11/29/84
-- JWC 05/13/85
-- JRK 06/07/85
-- TLB 10/30/87  RENAMED FROM B33006B.ADA.

PROCEDURE B33002A IS

     TYPE A;
     TYPE B IS ACCESS A;
     TYPE A IS ACCESS B;

     TYPE C;
     TYPE D IS NEW C;         -- ERROR: C INCOMPLETE.
     TYPE C IS NEW D;         -- OPTIONAL ERROR: D.

     TYPE E;
     TYPE F IS ACCESS E;
     TYPE E IS NEW F;

     TYPE G;
     TYPE G IS ACCESS G;      -- ERROR: G NOT VISIBLE.

     TYPE H;
     TYPE H IS NEW H;         -- ERROR: H NOT VISIBLE.

BEGIN
     NULL;
END B33002A;
