-- B33102B.ADA

-- CHECK THAT A TYPE DECLARATION, INCOMPLETE TYPE DECLARATION,
-- PRIVATE TYPE DECLARATION OR SUBTYPE DECLARATION CANNOT INTRODUCE
-- AN IDENTIFIER THAT WAS INTRODUCED PREVIOUSLY IN THE SAME
-- DECLARATIVE PART.

-- CASE B:  A PACKAGE SPECIFICATION AND ITS BODY.

-- JRK 4/1/81
-- JWC 10/2/85
-- JRK 11/15/85

PROCEDURE B33102B IS

     PACKAGE PKG2 IS

          A : INTEGER;
          B : CONSTANT INTEGER := 0;
          C : CONSTANT := 0;

          TYPE D IS RANGE 0..10;
          SUBTYPE E IS INTEGER RANGE 0..10;

          PROCEDURE F (X : INTEGER);
          FUNCTION G (X : INTEGER) RETURN INTEGER;

          PACKAGE H IS
               X : INTEGER;
          END H;

          I : EXCEPTION;
          J : INTEGER RENAMES A;

     END PKG2;

     PACKAGE BODY PKG2 IS

          TYPE A IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE B IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE C;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE D IS INTEGER;   -- ERROR: ID ALREADY DELCARED.
          TYPE E IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE F IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE G;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE H IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE I IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE J IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.

          PROCEDURE F (X : INTEGER) IS
          BEGIN
               NULL;
          END F;

          FUNCTION G (X : INTEGER) RETURN INTEGER IS
          BEGIN
               RETURN 0;
          END G;
     END PKG2;

BEGIN
     NULL;
END B33102B;
