-- B33102C.ADA

-- CHECK THAT A TYPE DECLARATION, INCOMPLETE TYPE DECLARATION,
-- PRIVATE TYPE DECLARATION OR SUBTYPE DECLARATION CANNOT INTRODUCE
-- AN IDENTIFIER THAT WAS INTRODUCED PREVIOUSLY IN THE SAME
-- DECLARATIVE PART.

-- CASE C:  A PACKAGE BODY.

-- JRK 4/1/81
-- JWC 10/2/85
-- JRK 11/15/85

PROCEDURE B33102C IS

     PACKAGE PKG3 IS
     END PKG3;

     PACKAGE BODY PKG3 IS

          A : INTEGER;
          B : CONSTANT INTEGER := 0;
          C : CONSTANT := 0;

          TYPE D IS RANGE 0..10;
          SUBTYPE E IS INTEGER RANGE 0..10;

          PROCEDURE F (X : INTEGER);
          FUNCTION G (X : INTEGER) RETURN INTEGER;

          PACKAGE H IS
               X : INTEGER;
          END H;

          I : EXCEPTION;
          J : INTEGER RENAMES A;

          TYPE A;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE B IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE C IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE D IS NEW INTEGER;  -- ERROR: ID ALREADY DELCARED.
          TYPE E;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE F IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE G IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE H IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE I;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE J IS INTEGER;   -- ERROR: ID ALREADY DECLARED.

          PROCEDURE F (X : INTEGER) IS
          BEGIN
               NULL;
          END F;

          FUNCTION G (X : INTEGER) RETURN INTEGER IS
          BEGIN
               RETURN 0;
          END G;
     END PKG3;

BEGIN
     NULL;
END B33102C;
