-- B33102D.ADA

-- CHECK THAT A TYPE DECLARATION, INCOMPLETE TYPE DECLARATION,
-- PRIVATE TYPE DECLARATION OR SUBTYPE DECLARATION CANNOT INTRODUCE
-- AN IDENTIFIER THAT WAS INTRODUCED PREVIOUSLY IN THE SAME
-- DECLARATIVE PART.

-- CASE D:  A BLOCK.

-- JRK 4/1/81
-- JWC 10/2/85
-- JRK 11/15/85

PROCEDURE B33102D IS

BEGIN

     DECLARE

          A : INTEGER;
          B : CONSTANT INTEGER := 0;
          C : CONSTANT := 0;

          TYPE D IS RANGE 0..10;
          SUBTYPE E IS INTEGER RANGE 0..10;

          PROCEDURE F (X : INTEGER);
          FUNCTION G (X : INTEGER) RETURN INTEGER;

          PACKAGE H IS
               X : INTEGER;
          END H;

          I : EXCEPTION;
          J : INTEGER RENAMES A;

          SUBTYPE A IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE B IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE C IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE D;                 -- ERROR: ID ALREADY DELCARED.
          SUBTYPE E IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE F IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE G IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE H;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE I IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE J IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.

          PROCEDURE F (X : INTEGER) IS
          BEGIN
               NULL;
          END F;

          FUNCTION G (X : INTEGER) RETURN INTEGER IS
          BEGIN
               RETURN 0;
          END G;

     BEGIN
          NULL;
     END;

END B33102D;
