-- B33102E.ADA

-- CHECK THAT A TYPE DECLARATION, INCOMPLETE TYPE DECLARATION,
-- PRIVATE TYPE DECLARATION OR SUBTYPE DECLARATION CANNOT INTRODUCE
-- AN IDENTIFIER THAT WAS INTRODUCED PREVIOUSLY IN THE SAME
-- DECLARATIVE PART.

-- CASE E:  A SUBPROGRAM BODY.

-- JRK 4/1/81
-- JWC 10/2/85  RENAMED FROM B33001A.ADA; ADDED FORMAL PARAMETER CASES.

PROCEDURE B33102E IS

     PROCEDURE P (K : IN INTEGER; L : IN OUT INTEGER;
                  M : OUT INTEGER) IS

          A : INTEGER;
          B : CONSTANT INTEGER := 0;
          C : CONSTANT := 0;

          TYPE D IS RANGE 0..10;
          SUBTYPE E IS INTEGER RANGE 0..10;

          PROCEDURE F (X : INTEGER);
          FUNCTION G (X : INTEGER) RETURN INTEGER;

          PACKAGE H IS
               X : INTEGER;
          END H;

          I : EXCEPTION;
          J : INTEGER RENAMES A;

          TYPE A IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE B;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE C IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE D IS PRIVATE;      -- ERROR: ID ALREADY DELCARED.
          TYPE E IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE F;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE G IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE H IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE I IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.
          TYPE J;                 -- ERROR: ID ALREADY DECLARED.
          SUBTYPE K IS INTEGER;   -- ERROR: ID ALREADY DECLARED.
          TYPE L IS PRIVATE;      -- ERROR: ID ALREADY DECLARED.
          TYPE M IS NEW INTEGER;  -- ERROR: ID ALREADY DECLARED.

          PROCEDURE F (X : INTEGER) IS
          BEGIN
               NULL;
          END F;

          FUNCTION G (X : INTEGER) RETURN INTEGER IS
          BEGIN
               RETURN 0;
          END G;

     BEGIN
          NULL;
     END P;

BEGIN
     NULL;
END B33102E;
