-- B33101A.ADA

-- CHECK THAT ENUMERATION, INTEGER, REAL, ARRAY, ACCESS, AND DERIVED
-- TYPE_DECLARATIONS CANNOT HAVE DISCRIMINANT PARTS.

-- JRK 4/1/81
-- JWC 10/4/85  RENAMED FROM B33002A.ADA;
--              ADDED TESTS FOR ACCESS AND DERIVED TYPES.

PROCEDURE B33101A IS

     SUBTYPE S IS INTEGER RANGE 0..10;

     TYPE E (D : S) IS (E1, E2);        -- ERROR: DISCRIMINANT_PART.
     TYPE I (D : S) IS RANGE 0..10;     -- ERROR: DISCRIMINANT_PART.
     TYPE R (D : S) IS DIGITS 3;        -- ERROR: DISCRIMINANT_PART.
     TYPE F (D : S) IS DELTA 1.0        -- ERROR: DISCRIMINANT_PART
                       RANGE 0.0 .. 3.0;
     TYPE A (D : S) IS ARRAY (S) OF S;  -- ERROR: DISCRIMINANT_PART.
     TYPE P (D : S) IS ACCESS S;        -- ERROR: DISCRIMINANT_PART.
     TYPE N (D : S) IS NEW INTEGER;     -- ERROR: DISCRIMINANT_PART.

BEGIN
     NULL;
END B33101A;
