-- B33202E.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN AN OBJECT DECLARATION,
-- A FLOATING POINT CONSTRAINT IS NOT ALLOWED IF THE TYPE MARK
-- DENOTES AN ENUMERATION, INTEGER, FIXED POINT, ARRAY,
-- RECORD, ACCESS, TASK OR PRIVATE TYPE.

-- JRK 4/2/81
-- VKG 1/6/83
-- JWC 10/9/85  RENAMED FROM B33003B-AB.ADA AND DIVIDED INTO FIVE
--              SEPARATE TESTS. EACH TYPE IS NOW TESTED IN AN OBJECT
--              DECLARATION. THE TESTS FOR TASK TYPE AND FIXED TYPE
--              WERE ADDED.

PROCEDURE B33202E IS

     TYPE FLT IS DIGITS 4;

     TYPE E IS (E1, E2);

     TYPE I IS RANGE 0 .. 100;

     TYPE FX IS DELTA 0.1 RANGE 0.0 .. 1.0;

     TYPE AR IS ARRAY (NATURAL RANGE <>) OF FLT;

     TYPE R IS
          RECORD
              I : FLT;
          END RECORD;

     TYPE AC IS ACCESS FLT;

     TASK TYPE TK IS
     END TK;

     PACKAGE PKG IS
          TYPE P IS PRIVATE;
     PRIVATE
          TYPE P IS NEW FLT;
     END PKG;
     USE PKG;

     T1 : E DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON ENUMERATION TYPE.
     T2 : I DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON INTEGER TYPE.
     T3 : FX DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON FIXED TYPE.
     T4 : AR DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON ARRAY TYPE.
     T5 : R DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON RECORD TYPE.
     T6 : AC DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON ACCESS TYPE.
     T7 : TK DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON TASK TYPE.
     T8 : P DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                         -- ON PRIVATE TYPE.

     TASK BODY TK IS
     BEGIN
          NULL;
     END TK;

BEGIN
     NULL;
END B33202E;
