-- B33201E.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN AN OBJECT DECLARATION,
-- A RANGE CONSTRAINT IS NOT PERMITTED FOR ARRAY, RECORD, ACCESS,
-- TASK, OR PRIVATE TYPES.

-- JRK 4/2/81
-- JWC 10/9/85  RENAMED FROM B33003A.ADA AND DIVIDED INTO FIVE SEPARATE
--              TESTS. EACH TYPE IS NOW TESTED IN AN OBJECT DECLARATION
--              AND THE TEST OF TASK TYPE WAS ADDED.

PROCEDURE B33201E IS

     TYPE ARR IS ARRAY (NATURAL RANGE <>) OF INTEGER;

     TYPE REC IS
          RECORD
               I : INTEGER;
          END RECORD;

     TYPE ACC IS ACCESS INTEGER;

     PACKAGE PKG IS
          TYPE PRIV IS PRIVATE;
     PRIVATE
          TYPE PRIV IS NEW INTEGER;
     END PKG;
     USE PKG;

     TASK TYPE TSK IS
     END TSK;

     A : ARR RANGE 0 .. 9;        -- ERROR: RANGE CONSTRAINT
                                  -- ON ARRAY TYPE.
     R : REC RANGE 0 .. 9;        -- ERROR: RANGE CONSTRAINT
                                  -- ON RECORD TYPE.
     C : ACC RANGE 0 .. 9;        -- ERROR: RANGE CONSTRAINT
                                  -- ON ACCESS TYPE.
     P : PRIV RANGE 0 .. 9;       -- ERROR: RANGE CONSTRAINT
                                  -- ON PRIVATE TYPE.
     T : TSK RANGE 0 .. 9;        -- ERROR: RANGE CONSTRAINT
                                  -- ON TASK TYPE.
     TASK BODY TSK IS
     BEGIN
          NULL;
     END TSK;

BEGIN
     NULL;
END B33201E;
