-- B33203C.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN A COMPONENT OF A RECORD OR
-- ARRAY TYPE DECLARATION, A FIXED POINT CONSTRAINT IS NOT ALLOWED
-- IF THE TYPE MARK DENOTES AN ENUMERATION, INTEGER, FLOATING POINT,
-- ARRAY, RECORD, ACCESS, TASK OR PRIVATE TYPE.  INCLUDE CONSTRAINED
-- ARRAY TYPE DEFINITION IN GENERIC FORMAL PARAMETER.

-- JRK 4/2/81
-- VKG 1/6/83
-- JWC 10/10/85  RENAMED FROM B33003C-AB.ADA AND DIVIDED INTO FIVE
--               SEPARATE TESTS. EACH TYPE IS NOW TESTED IN A COMPONENT
--               OF A RECORD AND OF AN ARRAY TYPE DECLARATION.
--               THE TESTS OF TASK TYPE AND FLOAT TYPE WERE ADDED.
-- PWB 02/20/86  CORRECTED ERROR -- LINE 45: "IN" => "IS".

PROCEDURE B33203C IS

     TYPE FX IS DELTA 1.0 RANGE 0.0 .. 5.0;

     TYPE E IS (E1, E2);

     TYPE I IS RANGE 0 .. 100;

     TYPE FL IS DIGITS 3;

     TYPE AR IS ARRAY (NATURAL RANGE <>) OF FX;

     TYPE R IS
          RECORD
              I : FX;
          END RECORD;

     TYPE AC IS ACCESS FX;

     TASK TYPE TK IS
     END TK;

     PACKAGE PKG IS
          TYPE P IS PRIVATE;
     PRIVATE
          TYPE P IS NEW FX;
     END PKG;
     USE PKG;

     SUBTYPE INT IS INTEGER RANGE 1 .. 2;

     TYPE REC IS
          RECORD
               T1 : E DELTA 1.0;      -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON ENUMERATION TYPE.
               T2 : I DELTA 1.0;      -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON INTEGER TYPE.
               T3 : FL DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON FLOATING POINT TYPE.
               T4 : AR DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON ARRAY TYPE.
               T5 : R DELTA 1.0;      -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON RECORD TYPE.
               T6 : AC DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON ACCESS TYPE.
               T7 : TK DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON TASK TYPE.
               T8 : P DELTA 1.0;      -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON PRIVATE TYPE.
          END RECORD;

     TYPE AT1 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF E DELTA 1.0;         -- ON ENUMERATION TYPE.
     TYPE AT2 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF I DELTA 1.0;         -- ON INTEGER TYPE.
     TYPE AT3 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF FL DELTA 1.0;        -- ON FLOATING POINT TYPE.
     TYPE AT4 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF AR DELTA 1.0;        -- ON ARRAY TYPE.
     TYPE AT5 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF R DELTA 1.0;         -- ON RECORD TYPE.
     TYPE AT6 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF AC DELTA 1.0;        -- ON ACCESS TYPE.
     TYPE AT7 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF TK DELTA 1.0;        -- ON TASK TYPE.
     TYPE AT8 IS ARRAY (1 .. 2)       -- ERROR: FIXED POINT CONSTRAINT
              OF P DELTA 1.0;         -- ON PRIVATE TYPE.

     GENERIC
          TYPE GT1 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF E DELTA 1.0;    -- ON ENUMERATION TYPE.
          TYPE GT2 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF I DELTA 1.0;    -- ON INTEGER TYPE.
          TYPE GT3 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF FL DELTA 1.0;   -- ON FLOATING POINT TYPE.
          TYPE GT4 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF AR DELTA 1.0;   -- ON ARRAY TYPE.
          TYPE GT5 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF R DELTA 1.0;    -- ON RECORD TYPE.
          TYPE GT6 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF AC DELTA 1.0;   -- ON ACCESS TYPE.
          TYPE GT7 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF TK DELTA 1.0;   -- ON TASK TYPE.
          TYPE AT8 IS ARRAY (INT)     -- ERROR: FIXED POINT CONSTRAINT
                   OF P DELTA 1.0;    -- ON PRIVATE TYPE.
     PACKAGE GENPCK IS
     END GENPCK;

     TASK BODY TK IS
     BEGIN
          NULL;
     END TK;

BEGIN
     NULL;
END B33203C;
