-- B33202B.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN AN ALLOCATOR,
-- A FLOATING POINT CONSTRAINT IS NOT ALLOWED IF THE TYPE MARK
-- DENOTES AN ENUMERATION, INTEGER, FIXED POINT, ARRAY, RECORD,
-- ACCESS, TASK OR PRIVATE TYPE.

-- JRK 4/2/81
-- VKG 1/6/83
-- JWC 10/9/85  RENAMED FROM B33003B-AB.ADA AND DIVIDED INTO FIVE
--              SEPARATE TESTS. EACH TYPE IS NOW TESTED IN AN
--              ALLOCATOR. THE TESTS OF TASK TYPE AND FIXED TYPE WERE
--              ADDED.

PROCEDURE B33202B IS

     TYPE FLT IS DIGITS 4;
     TYPE ACF IS ACCESS FLT;

     TYPE E IS (E1, E2);
     TYPE ACE IS ACCESS E;

     TYPE I IS RANGE 0 .. 100;
     TYPE ACI IS ACCESS I;

     TYPE FX IS DELTA 0.1 RANGE 0.0 .. 1.0;
     TYPE ACFX IS ACCESS FX;

     TYPE AR IS ARRAY (NATURAL RANGE <>) OF FLT;
     TYPE ACAR IS ACCESS AR;

     TYPE R IS
          RECORD
              I : FLT;
          END RECORD;
     TYPE ACR IS ACCESS R;

     TYPE AC IS ACCESS FLT;
     TYPE ACAC IS ACCESS AC;

     TASK TYPE TK IS
     END TK;
     TYPE ACTK IS ACCESS TK;

     PACKAGE PKG IS
          TYPE P IS PRIVATE;
     PRIVATE
          TYPE P IS NEW FLT;
     END PKG;
     USE PKG;
     TYPE ACP IS ACCESS P;

     T1 : ACE := NEW E DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ENUMERATION TYPE.
     T2 : ACI := NEW I DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON INTEGER TYPE.
     T3 : ACFX := NEW FX DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON FIXED TYPE.
     T4 : ACAR := NEW AR DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ARRAY TYPE.
     T5 : ACR := NEW R DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON RECORD TYPE.
     T6 : ACAC := NEW AC DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ACCESS TYPE.
     T7 : ACTK := NEW TK DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON TASK TYPE.
     T8 : ACP := NEW P DIGITS 1;    -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON PRIVATE TYPE.
     T9 : ACF := NEW FLT DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    --        IN ALLOCATOR.
     XT6 : ACAC := NEW AC;          -- OK.

     TASK BODY TK IS
     BEGIN
          NULL;
     END TK;

BEGIN
     NULL;
END B33202B;
