-- B33203E.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN AN OBJECT DECLARATION,
-- A FIXED POINT CONSTRAINT IS NOT ALLOWED
-- IF THE TYPE MARK DENOTES AN ENUMERATION, INTEGER, FLOATING POINT,
-- ARRAY, RECORD, ACCESS, TASK OR PRIVATE TYPE.

-- JRK 4/2/81
-- VKG 1/6/83
-- JWC 10/10/85  RENAMED FROM B33003C-AB.ADA AND DIVIDED INTO FIVE
--               SEPARATE TESTS.  EACH TYPE IS NOW TESTED IN AN OBJECT
--               DECLARATION.  THE TESTS OF TASK TYPE AND FLOAT TYPE
--               WERE ADDED.

PROCEDURE B33203E IS

     TYPE FX IS DELTA 1.0 RANGE 0.0 .. 5.0;

     TYPE E IS (E1, E2);

     TYPE I IS RANGE 0 .. 100;

     TYPE FL IS DIGITS 3;

     TYPE AR IS ARRAY (NATURAL RANGE <>) OF FX;

     TYPE R IS
          RECORD
              I : FX;
          END RECORD;

     TYPE AC IS ACCESS FX;

     TASK TYPE TK IS
     END TK;

     PACKAGE PKG IS
          TYPE P IS PRIVATE;
     PRIVATE
          TYPE P IS NEW FX;
     END PKG;
     USE PKG;

     T1 : E DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                         -- ON ENUMERATION TYPE.
     T2 : I DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                         -- ON INTEGER TYPE.
     T3 : FL DELTA 1.0;  -- ERROR: FIXED POINT CONSTRAINT
                         -- ON FLOATING POINT TYPE.
     T4 : AR DELTA 1.0;  -- ERROR: FIXED POINT CONSTRAINT
                         -- ON ARRAY TYPE.
     T5 : R DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                         -- ON RECORD TYPE.
     T6 : AC DELTA 1.0;  -- ERROR: FIXED POINT CONSTRAINT
                         -- ON ACCESS TYPE.
     T7 : TK DELTA 1.0;  -- ERROR: FIXED POINT CONSTRAINT
                         -- ON TASK TYPE.
     T8 : P DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                         -- ON PRIVATE TYPE.

     TASK BODY TK IS
     BEGIN
          NULL;
     END TK;

BEGIN
     NULL;
END B33203E;
