-- B33203B.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN AN ALLOCATOR,
-- A FIXED POINT CONSTRAINT IS NOT ALLOWED IF THE TYPE MARK DENOTES
-- AN ENUMERATION, INTEGER, FLOATING POINT, ARRAY, RECORD, ACCESS,
-- TASK OR PRIVATE TYPE.

-- JRK 4/2/81
-- VKG 1/6/83
-- JWC 10/9/85  RENAMED FROM B33003C-AB.ADA AND DIVIDED INTO FIVE
--              SEPARATE TESTS. EACH TYPE IS NOW TESTED IN AN ALLOCATOR.
--              THE TESTS OF TASK TYPE AND FLOAT TYPE WERE ADDED.

PROCEDURE B33203B IS

     TYPE FX IS DELTA 1.0 RANGE 0.0 .. 5.0;

     TYPE E IS (E1, E2);
     TYPE ACE IS ACCESS E;

     TYPE I IS RANGE 0 .. 100;
     TYPE ACI IS ACCESS I;

     TYPE FL IS DIGITS 3;
     TYPE ACFL IS ACCESS FL;

     TYPE AR IS ARRAY (NATURAL RANGE <>) OF FX;
     TYPE ACAR IS ACCESS AR;

     TYPE R IS
          RECORD
              I : FX;
          END RECORD;
     TYPE ACR IS ACCESS R;

     TYPE AC IS ACCESS FX;
     TYPE ACAC IS ACCESS AC;

     TASK TYPE TK IS
     END TK;
     TYPE ACTK IS ACCESS TK;

     PACKAGE PKG IS
          TYPE P IS PRIVATE;
     PRIVATE
          TYPE P IS NEW FX;
     END PKG;
     USE PKG;
     TYPE ACP IS ACCESS P;

     T1 : ACE := NEW E DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON ENUMERATION TYPE.
     T2 : ACI := NEW I DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON INTEGER TYPE.
     T3 : ACFL := NEW FL DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON FLOATING POINT TYPE.
     T4 : ACAR := NEW AR DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON ARRAY TYPE.
     T5 : ACR := NEW R DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON RECORD TYPE.
     T6 : ACAC := NEW AC DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON ACCESS TYPE.
     T7 : ACTK := NEW TK DELTA 1.0;   -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON TASK TYPE.
     T8 : ACP := NEW P DELTA 1.0;     -- ERROR: FIXED POINT CONSTRAINT
                                      -- ON PRIVATE TYPE.

     TASK BODY TK IS
     BEGIN
          NULL;
     END TK;

BEGIN
     NULL;
END B33203B;
