-- B33205A.ADA

-- OBJECTIVE:
--     CHECK THAT A DISCRIMINANT CONSTRAINT IS ILLEGAL IN A SUBTYPE
--     INDICATION IF THE TYPE MARK DENOTES:
--          A SCALAR
--          AN ARRAY
--          A CONSTRAINED RECORD
--          A CONSTRAINED ACCESS
--          A TASK
--          A CONSTRAINED PRIVATE TYPE
--          AN ACCESS TYPE DENOTING ANY OF THE ABOVE.

-- HISTORY:
--     DHH 01/21/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE B33205A IS

-- SCALAR
     SUBTYPE INT IS INTEGER RANGE 0 .. 10;
     TYPE INT_ACC IS ACCESS INT;
     SUBTYPE SHORT_INT IS INT(5);           -- ERROR: INTEGER.
     A : INT_ACC(5);               -- ERROR: ACCESS DESIGNATING INTEGER.

     TYPE COLOR IS (RED, BLUE, YELLOW);
     TYPE COLOR_ACC IS ACCESS COLOR;
     SUBTYPE SUB_COLOR IS COLOR(RED);       -- ERROR: ENUMERATION.
     B : COLOR_ACC(RED);          -- ERROR: ACCESS DESIGNATING ENUMER.

     TYPE FLOAT IS DIGITS 5;
     TYPE FLOAT_ACC IS ACCESS FLOAT;
     SUBTYPE SUB_FLOAT IS FLOAT(5.0);       -- ERROR: FLOATING POINT.
     BB : FLOAT_ACC(4.0);           -- ERROR: ACCESS DESIGNATING FLOAT.

-- ARRAY
     TYPE SHORT_ARRAY IS ARRAY(INTEGER RANGE <>) OF INTEGER;
     TYPE ARRAY_PTR IS ACCESS SHORT_ARRAY;
     SUBTYPE FAIL_ARRAY IS SHORT_ARRAY(5);    -- ERROR: ARRAY.
     C : ARRAY_PTR(5);              -- ERROR: ACCESS DESIGNATING ARRAY.

-- CONSTRAINED RECORD
     TYPE MATRIX IS ARRAY(INTEGER RANGE <>) OF INTEGER;
     TYPE SQUARE (X : INTEGER) IS
          RECORD
               MAT : MATRIX(1 .. X);
          END RECORD;
     SUBTYPE NEW_SQUARE IS SQUARE(5);
     TYPE NEW_SQUARE_PTR IS ACCESS NEW_SQUARE;
     SUBTYPE FAIL_SQUARE IS NEW_SQUARE(5);  -- ERROR: CONSTRAINED REC.
     SUBTYPE FAIL_PTR IS NEW_SQUARE_PTR(5);
                                          -- ERROR: ACCESS DESIGNATING
                                          -- CONSTRAINED RECORD.

-- TASK
     TASK TYPE T IS
          ENTRY READ(S : INTEGER);
     END T;
     TYPE T_PTR IS ACCESS T;
     SUBTYPE TT IS T(5);                    -- ERROR: TASK TYPE.
     SUBTYPE TT_PTR IS T_PTR(5);     -- ERROR: ACCESS DESIGNATING TASK.

-- CONSTRAINED PRIVATE TYPE
     PACKAGE PACK IS
          TYPE P(X : INTEGER) IS PRIVATE;
          TYPE P_PTR IS ACCESS P;
          SUBTYPE PP IS P(5);
          TYPE AC_PTR IS ACCESS PP(5);      -- ERROR: ACCESS DESIGNATING
                                            --      CONSTRAINED PRIVATE.
          SUBTYPE PP_PTR IS P_PTR(5);
          SUBTYPE PPP IS PP(5);             -- ERROR: CONSTRAINED
                                            --        PRIVATE TYPE.
          SUBTYPE PPP_PTR IS PP_PTR(5);     -- ERROR: ACCESS DESIGNATING
                                            --      CONSTRAINED ACCESS
                                            --       SUBTYPE.

     PRIVATE
          TYPE P(X : INTEGER) IS
               RECORD
                    MAT : MATRIX(1 .. X);
               END RECORD;
     END PACK;
     USE PACK;

-- CONSTRAINED ACCESS
     TYPE CON_ACC IS ACCESS SQUARE(5);
     SUBTYPE SUB_ACC IS CON_ACC(2);        -- ERROR: CONSTRAINED ACCESS.
     TYPE CON_ACC_PTR IS ACCESS CON_ACC;
     AC : CON_ACC_PTR(5);                  -- ERROR: ACCESS DESIGNATING
                                           -- CONSTRAINED ACCESS.
     TASK BODY T IS
          Q : INTEGER;
     BEGIN
          ACCEPT READ(S : INTEGER) DO
               Q := S;
          END READ;
     END T;

BEGIN
     NULL;
END B33205A;
