-- B33202A.ADA

-- CHECK THAT IN A SUBTYPE INDICATION IN AN ACCESS TYPE DEFINITION,
-- A FLOATING POINT CONSTRAINT IS NOT ALLOWED IF THE TYPE MARK
-- DENOTES AN ENUMERATION, INTEGER, FIXED POINT, ARRAY, RECORD,
-- ACCESS, TASK OR PRIVATE TYPE. INCLUDE ACCESS TYPE DEFINITIONS
-- IN GENERIC FORMAL PARAMETERS.

-- JRK 4/2/81
-- VKG 1/6/83
-- JWC 10/9/85  RENAMED FROM B33003B-AB.ADA AND DIVIDED INTO FIVE
--              SEPARATE TESTS. EACH TYPE IS NOW TESTED IN AN ACCESS
--              TYPE DEFINITION. THE TESTS FOR TASK TYPE AND FIXED TYPE
--              WERE ADDED.

PROCEDURE B33202A IS

     TYPE FLT IS DIGITS 4;

     TYPE E IS (E1, E2);

     TYPE I IS RANGE 0 .. 100;

     TYPE FX IS DELTA 0.1 RANGE 0.0 .. 1.0;

     TYPE AR IS ARRAY (NATURAL RANGE <>) OF FLT;

     TYPE R IS
          RECORD
              I : FLT;
          END RECORD;

     TYPE AC IS ACCESS FLT;

     TASK TYPE TK IS
     END TK;

     PACKAGE PKG IS
          TYPE P IS PRIVATE;
     PRIVATE
          TYPE P IS NEW FLT;
     END PKG;
     USE PKG;

     TYPE T1 IS ACCESS E DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ENUMERATION TYPE.
     TYPE T2 IS ACCESS I DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON INTEGER TYPE.
     TYPE T3 IS ACCESS FX DIGITS 1; -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON FIXED TYPE.
     TYPE T4 IS ACCESS AR DIGITS 1; -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ARRAY TYPE.
     TYPE T5 IS ACCESS R DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON RECORD TYPE.
     TYPE T6 IS ACCESS AC DIGITS 1; -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ACCESS TYPE.
     TYPE T7 IS ACCESS TK DIGITS 1; -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON TASK TYPE.
     TYPE T8 IS ACCESS P DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON PRIVATE TYPE.

     GENERIC
          TYPE GT1 IS
               ACCESS E DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ENUMERATION TYPE.
          TYPE GT2 IS
               ACCESS I DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON INTEGER TYPE.
          TYPE GT3 IS
               ACCESS FX DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON FIXED TYPE.
          TYPE GT4 IS
               ACCESS AR DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ARRAY TYPE.
          TYPE GT5 IS
               ACCESS R DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON RECORD TYPE.
          TYPE GT6 IS
               ACCESS AC DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON ACCESS TYPE.
          TYPE GT7 IS
               ACCESS TK DIGITS 1;  -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON TASK TYPE.
          TYPE GT8 IS
               ACCESS P DIGITS 1;   -- ERROR: FLOATING POINT CONSTRAINT
                                    -- ON PRIVATE TYPE.
     PACKAGE GENPCK IS
     END GENPCK;

     TASK BODY TK IS
     BEGIN
          NULL;
     END TK;

BEGIN
     NULL;
END B33202A;
