-- B33301A.ADA

-- OBJECTIVE:
--     CHECK THAT T'BASE CANNOT BE USED AS A TYPE_MARK IN A
--     SUBTYPE_INDICATION (I.E., IN A DISCRETE_RANGE,
--     GENERIC_ACTUAL_PARAMETER, RELATION),
--     QUALIFIED_EXPRESSION, OR TYPE_CONVERSION.

-- HISTORY:
--     JRK 04/01/81
--     JWC 10/11/85  RENAMED FROM B33004A.ADA.
--                   ADDED TESTS FOR GENERIC FORMAL PARAMETERS AND
--                   GENERIC ACTUAL PARAMETERS WHERE THE FORMAL
--                   PARAMETER IS A PRIVATE TYPE AND AN ARRAY TYPE.
--     DWC 09/22/87  MOVED OTHER CHECKS TO B33301B.ADA.

PROCEDURE B33301A IS

     SUBTYPE T IS INTEGER RANGE 0..10;

     TYPE AR IS ARRAY (T) OF INTEGER;

     SUBTYPE ST IS STRING (1 .. 3);

     I : INTEGER := 0;
     B : BOOLEAN;

     TYPE A IS ACCESS INTEGER;
     AI : A;

     TYPE T5 IS ARRAY (T'BASE) OF T;                -- ERROR: 'BASE.

     GENERIC
          TYPE I IS RANGE <>;
     PACKAGE PKG IS
          J : I;
     END PKG;

     PACKAGE PGK1 IS NEW PKG (T'BASE);              -- ERROR: 'BASE.

     TYPE T8 IS ARRAY (T'BASE RANGE <>) OF T;       -- ERROR: 'BASE.

     GENERIC
          TYPE GTYPE1 IS PRIVATE;
          TYPE GTYPE2 IS ARRAY (T) OF GTYPE1;
     PACKAGE GENPACK2 IS
          X : GTYPE2;
     END GENPACK2;

     PACKAGE INST1 IS NEW GENPACK2 (T'BASE, AR);    -- ERROR: 'BASE.

     GENERIC
          TYPE GT IS ARRAY (POSITIVE RANGE <>) OF CHARACTER;
     PACKAGE GENPACK3 IS
     END GENPACK3;

     PACKAGE INST2 IS NEW GENPACK3 (ST'BASE);       -- ERROR: 'BASE.

BEGIN

     FOR I IN T'BASE LOOP                           -- ERROR: 'BASE.
          NULL;
     END LOOP;

     B := I IN T'BASE;                              -- ERROR: 'BASE.
     I := T'BASE'(3);                               -- ERROR: 'BASE.
     I := T'BASE(4);                                -- ERROR: 'BASE.

END B33301A;
