-- B35103B.ADA

-- CHECK THAT DUPLICATE ENUMERATION LITERALS ARE NOT ALLOWED.
-- LOWER CASE LETTERS ARE USED.

-- JBG 11/18/85

PROCEDURE B35103B IS

     TYPE E1 IS (AB, B, C, ab);    -- ERROR: DUPLICATE LITERAL.
     TYPE E2 IS (A, 'b', C, 'b');  -- ERROR: DUPLICATE LITERAL.

     TYPE E3 IS (A, 'B', C, 'b');  -- OK.

BEGIN
     NULL;
END B35103B;
