-- B35103A.ADA

-- CHECK THAT DUPLICATE ENUMERATION LITERALS ARE NOT ALLOWED.

-- JBG 11/18/85

PROCEDURE B35103A IS

     TYPE E1 IS (AB, B, C, AB);    -- ERROR: DUPLICATE LITERAL.
     TYPE E2 IS (A, 'B', C, 'B');  -- ERROR: DUPLICATE LITERAL.

BEGIN
     NULL;
END B35103A;
