-- B35401A.ADA

-- CHECK THAT THE BOUNDS IN AN INTEGER TYPE DEFINITION MUST BE STATIC.

-- RJW 2/20/86

PROCEDURE B35401A IS

     I1 : INTEGER := 1;
     I2 : INTEGER := 2000;

     ICON : CONSTANT INTEGER := I1;
 
     FUNCTION F (I : INTEGER) RETURN INTEGER;

     TYPE PAGE_NUM1 IS RANGE I1 .. 2000;        -- ERROR: NOT STATIC.
     TYPE PAGE_NUM2 IS RANGE 1 .. I2;           -- ERROR: NOT STATIC.
     TYPE OK IS ARRAY(1..5) OF INTEGER;
     TYPE LINE_SIZE IS RANGE OK'FIRST .. 10;    -- ERROR: NOT STATIC.
     TYPE LENGTH_SIZE IS RANGE 1 .. OK'LENGTH;  -- ERROR: NOT STATIC.
     TYPE SMALL_INT1 IS RANGE ICON .. 10;       -- ERROR: NOT STATIC.
     TYPE SMALL_INT2 IS RANGE 1 .. ICON;        -- ERROR: NOT STATIC.
     TYPE BUFFER_SIZE IS RANGE F(2) .. 10;      -- ERROR: NOT STATIC.
     TYPE HIS_INT IS RANGE 1 .. F(5);           -- ERROR: NOT STATIC.

     FUNCTION F (I : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN I;
     END F;
BEGIN
     NULL;
END B35401A;
