-- B35401B.ADA

-- CHECK THAT THE BOUNDS IN A RANGE ATTRIBUTE TYPE DEFINITION
-- MUST BE STATIC.

-- HLT 08/06/86

PROCEDURE B35401B IS

     TYPE OK IS ARRAY(1 .. 5) OF INTEGER;                              
     TYPE LINE_SIZE IS RANGE OK'RANGE;           -- ERROR: NOT STATIC.

BEGIN
     NULL;
END B35401B;
