-- B35709A.ADA

-- DISTINCTION OF REAL TYPES: THREE SUBTESTS
-- (A) TWO TEXTUALLY IDENTICAL TYPES ARE DISTINCT
-- (B) TWO TYPES DERIVED FROM FLOAT ARE DISTINCT
-- (C) SUBTYPES OF DISTINCT TYPES ARE DISTINCT

-- BAW 5 SEPT 80

PROCEDURE B35709A IS
     TYPE D1 IS DIGITS 5;
     TYPE D2 IS DIGITS 5;
     XD1: D1 := 1.0;
     XD2: D2 := XD1;       -- ERROR: WRONG TYPES (A)

     TYPE D3 IS NEW FLOAT;
     TYPE D4 IS NEW FLOAT;
     XD3: D3 := 1.0;
     XD4: D4 := XD3;       -- ERROR: WRONG TYPES (B)

     SUBTYPE D5 IS D1 RANGE 0.0 .. 2.0;
     SUBTYPE D6 IS D2 RANGE 0.0 .. 2.0;
     XD5: D5 := 1.0;
     XD6: D6 := XD5;       -- ERROR: WRONG TYPES (C)
BEGIN
     NULL;
END B35709A;
