-- B35801C.ADA

-- CHECK THAT THE ATTRIBUTES FIRST AND LAST RETURN VALUES HAVING THE
-- SAME BASE TYPE AS THE PREFIX WHEN THE PREFIX IS A FLOATING POINT
-- TYPE.

-- THIS CHECK IS PROVIDED THROUGH THE USE OF THIS TEST IN CONJUNCTION
-- WITH TEST A35801F.

-- R.WILLIAMS 8/21/86

PROCEDURE B35801C IS

     TYPE REAL IS DIGITS 3 RANGE -100.0 .. 100.0;

     TYPE NFLT IS NEW FLOAT;

     SUBTYPE EMPTY IS FLOAT RANGE 1.0 .. -1.0;

     R1 : CONSTANT := REAL'FIRST;      -- ERROR: NOT UNIVERSAL REAL.
     R2 : CONSTANT := REAL'LAST;       -- ERROR: NOT UNIVERSAL REAL.

     R3 : REAL := REAL'FIRST;          -- OK.
     R4 : REAL := REAL'LAST;           -- OK.

     N1 : CONSTANT := NFLT'FIRST;      -- ERROR: NOT UNIVERSAL REAL.
     N2 : CONSTANT := NFLT'LAST;       -- ERROR: NOT UNIVERSAL REAL.

     N3 : NFLT := NFLT'FIRST;          -- OK.
     N4 : NFLT := NFLT'LAST;           -- OK.

     F1 : CONSTANT := FLOAT'FIRST;     -- ERROR: NOT UNIVERSAL REAL.
     F2 : CONSTANT := FLOAT'LAST;      -- ERROR: NOT UNIVERSAL REAL.

     F3 : FLOAT := FLOAT'FIRST;        -- OK.
     F4 : FLOAT := FLOAT'LAST;         -- OK.

     E1 : CONSTANT := EMPTY'FIRST;     -- ERROR: NOT UNIVERSAL REAL.
     E2 : CONSTANT := EMPTY'LAST;      -- ERROR: NOT UNIVERSAL REAL.

     E3 : FLOAT := EMPTY'FIRST;        -- OK.
     E4 : FLOAT := EMPTY'LAST;         -- OK.

BEGIN
     NULL;
END B35801C;
