-- B36171C.ADA

-- CHECK THAT EMPTY INDEX-CONSTRAINTS ARE NOT ALLOWED.

-- DAT 2/9/81
-- ABW 7/21/82

PROCEDURE B36171C IS

     TYPE D1 IS ARRAY (INTEGER RANGE <>)
          OF BOOLEAN RANGE TRUE .. FALSE;

     TYPE T IS NEW D1 ();                    -- ERROR: ().

BEGIN
     NULL;

END B36171C;
