-- B36171F.ADA

-- CHECK THAT BOXES MAY NOT APPEAR IN AN INDEX-CONSTRAINT.

-- DAT 2/9/81
-- ABW 7/21/82

PROCEDURE B36171F IS

     TYPE T IS NEW STRING
          (NATURAL RANGE <>);            -- ERROR: <>.

BEGIN
     NULL;

END B36171F;
