-- B36171G.ADA

-- OBJECTIVE:
--     CHECK THAT BOXES MAY NOT APPEAR IN AN INDEX-CONSTRAINT.

-- HISTORY:
--     DAT 02/09/81  CREATED ORIGINAL TEST.
--     ABW 07/21/82
--     BCB 08/01/88  MODIFIED HEADER FORMAT AND REMOVED THE "TOO MANY
--                   INDICES" ERROR BY DELETING THE COMMA FROM THE
--                   INDEX CONSTRAINT.

PROCEDURE B36171G IS

     SUBTYPE INT_1 IS INTEGER RANGE 1 .. 1;
     TYPE U IS ARRAY (INT_1 RANGE <>) OF INT_1;

     SUBTYPE UU IS U (INT_1 RANGE <>);           -- ERROR: <>.

BEGIN
     NULL;

END B36171G;
