-- B36103A.ADA

-- CHECK THAT UPPER AND LOWER BOUNDS OF A DISCRETE RANGE MUST HAVE THE
-- SAME TYPE AS THE TYPE MARK, WHERE BOTH BOUNDS ARE OF THE SAME TYPE.

-- DAT 2/3/81

PROCEDURE B36103A IS

     SUBTYPE B1 IS BOOLEAN RANGE TRUE .. TRUE;
     BT : B1 := TRUE;

     TYPE D_BOOL IS NEW BOOLEAN;
     SUBTYPE DB1 IS D_BOOL RANGE TRUE .. TRUE;
     DBT : DB1 := TRUE;

     TYPE AA IS ARRAY (B1 RANGE
          D_BOOL'(TRUE) .. D_BOOL'(TRUE))  -- ERROR: D_BOOL NOT B1.
          OF BOOLEAN;

     TYPE BA IS ARRAY (BOOLEAN RANGE
          D_BOOL'(FALSE) .. D_BOOL'(TRUE)) -- ERROR: D_BOOL NOT BOOLEAN.
          OF BOOLEAN;

     TYPE AB IS ARRAY (D_BOOL RANGE
          BOOLEAN'(FALSE)..BOOLEAN'(TRUE)) -- ERROR: BOOLEAN NOT D_BOOL.
          OF BOOLEAN;

BEGIN

     FOR I IN BOOLEAN RANGE DBT .. DBT LOOP -- ERROR: DBT NOT BOOLEAN.
          NULL;
     END LOOP;

     FOR I IN B1 RANGE DBT .. DBT LOOP     -- ERROR: DBT NOT TYPE B1.
          NULL;
     END LOOP;

     FOR I IN D_BOOL RANGE BT .. BT LOOP   -- ERROR: BT NOT D_BOOL.
          NULL;
     END LOOP;

     FOR I IN DB1 RANGE BT .. BT LOOP      -- ERROR: BT NOT DB1.
          NULL;
     END LOOP;

END B36103A;
