-- B36171B.ADA

-- CHECK THAT AN UNCONSTRAINED ARRAY TYPE_MARK IS NOT ALLOWED AS THE
-- COMPONENT TYPE IN AN ARRAY_TYPE_DEFINITION USED IN A
-- GENERIC_TYPE_DEFINITION.

-- DAT 2/11/81
-- SPS 12/10/82

PROCEDURE B36171B IS

     TYPE I_1 IS NEW INTEGER RANGE 1 .. 1;
     TYPE U_I IS ARRAY (I_1 RANGE <> ) OF I_1;
     TYPE E_1 IS (ENUM_VALUE);
     TYPE U_E IS ARRAY (E_1 RANGE <> ) OF E_1;

     GENERIC
          TYPE C IS PRIVATE;
          TYPE EA_1 IS ARRAY (E_1 RANGE <> )
               OF C;                         -- OK.
          TYPE EA_2 IS ARRAY (E_1 RANGE <> )
               OF U_E;                       -- ERROR: UNCONSTRAINED.
          TYPE EA_3 IS ARRAY (I_1 RANGE <> )
               OF U_I;                       -- ERROR: UNCONSTRAINED.
          TYPE EA_4 IS ARRAY (E_1) OF C ;    -- OK.
          TYPE EA_5 IS ARRAY (E_1) OF U_E;   -- ERROR: UNCONSTRAINED.
          TYPE EA_6 IS ARRAY (I_1) OF U_I;   -- ERROR: UNCONSTRAINED.

     PROCEDURE G1;

     PROCEDURE G1 IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B36171B;
