-- B36216A.ADA

-- OBJECTIVE:
--     CHECK THAT 'RANGE IS NOT ALLOWED WHEN THE PREFIX IS AN
--     ENUMERATION TYPE OR AN INTEGER TYPE.

-- HISTORY:
--     DHH 02/01/88 CREATED ORIGINAL TEST.

PROCEDURE B36216A IS

     TYPE COLOR IS (RED,BLUE,GREEN,YELLOW,PURPLE);
     SUBTYPE I IS INTEGER RANGE -6 .. 6;
     SUBTYPE P IS INTEGER RANGE 1 .. 6;
     SUBTYPE N IS INTEGER RANGE -6 .. 0;
     TYPE ENUM IS (GEORGE, HAROLD, SAM, DAN, MARK, EDDIE, JIM);
     TYPE CHAR IS ('A', 'B', 'C');
     SUBTYPE X IS INTEGER RANGE P'RANGE;                      -- ERROR:
     SUBTYPE Y IS INTEGER RANGE 1 .. 6;

     TYPE Q IS ARRAY(INTEGER RANGE I'RANGE) OF BOOLEAN;       -- ERROR:
     TYPE R IS ARRAY(INTEGER RANGE -6 .. 6) OF BOOLEAN;

     TYPE S IS ARRAY(CHAR RANGE CHAR'RANGE) OF BOOLEAN;       -- ERROR:
     TYPE T IS ARRAY(CHAR RANGE 'A' .. 'C') OF BOOLEAN;

     TYPE A IS ARRAY(COLOR RANGE COLOR'RANGE) OF BOOLEAN;     -- ERROR:
     TYPE B IS ARRAY(COLOR RANGE RED .. PURPLE) OF BOOLEAN;

     TYPE U IS ARRAY(INTEGER RANGE N'RANGE) OF BOOLEAN;       -- ERROR:
     TYPE V IS ARRAY(INTEGER RANGE -6 .. -1) OF BOOLEAN;

     TYPE C IS ARRAY(ENUM RANGE ENUM'RANGE) OF BOOLEAN;       -- ERROR:
     TYPE D IS ARRAY(ENUM RANGE GEORGE .. JIM) OF BOOLEAN;

     AI : I;
     TYPE VAR(W : I) IS
          RECORD
               CASE W IS
                    WHEN N'RANGE =>                           -- ERROR:
                         NULL;
                    WHEN OTHERS =>
                         NULL;
               END CASE;
           END RECORD;

BEGIN
     FOR I IN Y'RANGE LOOP                                    -- ERROR:
          NULL;
     END LOOP;

END B36216A;
