-- B36307A.ADA

-- CHECK THAT DECLARATION OF A MULTIDIMENSIONAL ARRAY OF CHARACTER TYPE
-- DOES NOT IMPLICITLY DECLARE A STRING LITERAL FORMATION OPERATION.

-- L.BROWN   08/18/86

PROCEDURE B36307A IS

     -- CHECK THAT NO STRING LITERAL FORMATION OPERATION IS DECLARED
     -- FOR A MULTIDIMENSIONAL ARRAY TYPE.

     TYPE ARR_TYPE IS ARRAY( 1 .. 2, 1 .. 4) OF CHARACTER;

     AR1 : ARR_TYPE := "ABCDEFGH";               -- ERROR: STRING LIT.
     AR2 : ARR_TYPE;
     AR3 : ARR_TYPE;

     GENERIC
          AR4 : ARR_TYPE;
     PROCEDURE PROC;
     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;

     PROCEDURE PROC1 IS NEW PROC("ADSGFDJA");    -- ERROR: STRING LIT.

     FUNCTION FUN (ARR : ARR_TYPE) RETURN ARR_TYPE IS
          BEGIN
               RETURN ARR;
          END FUN;

BEGIN

     AR2 := "MNOPQRSG";                          -- ERROR: STRING LIT.
     AR3 := FUN("AGDEKGFB");                     -- ERROR: STRING LIT.

     IF AR1 = "ABCDEFGH"  THEN                   -- ERROR: STRING LIT.
          AR1 := ("ADFS","DJFI");
     END IF;

END B36307A;
