-- B37004C.ADA

--  CHECK THAT VACUOUS COMPONENT_LISTS ARE FORBIDDEN IN 
--  RECORD TYPE DEFINITIONS.

-- VKG 2/2/83
-- CPP 6/5/84

PROCEDURE B37004C IS

     SUBTYPE S1 IS INTEGER RANGE 1 .. 1;
     TYPE R1 IS RECORD END RECORD;               -- ERROR: 

BEGIN
     NULL;
END B37004C;
