-- B37004E.ADA

-- CHECK THAT VACUOUS TYPE DECLARATIONS ARE FORBIDDEN.

-- DAT 5/18/81
-- ABW 6/10/82

PROCEDURE B37004E IS

     SUBTYPE S1 IS INTEGER RANGE 1 .. 1;

     TYPE R1 (D : S1) IS RECORD
          CASE D IS
               WHEN 1 => NULL;
          END CASE;
     END RECORD;                              -- OK.

     TYPE R2 (D : S1) IS RECORD
          CASE D IS WHEN 1 => END CASE;       -- ERROR: MISSING NULL.
     END RECORD;

BEGIN
     NULL;

END B37004E;
