-- B37004D.ADA

-- CHECK THAT ABSENCE OF RECORD COMPONENTS FORBIDDEN.

-- DAT 5/18/81
-- ABW 6/9/82

PROCEDURE B37004D IS

     SUBTYPE S1 IS INTEGER RANGE 1 .. 1;

     TYPE REC (D : S1) IS RECORD
     END RECORD;                        -- ERROR: MISSING NULL.

BEGIN
     NULL;

END B37004D;
