-- B37202B.ADA

-- CHECK THAT A DISCRIMINANT CONSTRAINT CANNOT BE SPECIFIED FOR A
-- TASK TYPE.

-- ASL 6/19/81
-- JWC 6/28/85   RENAMED TO -AB

PROCEDURE B37202B IS

     TASK TYPE TSK;

     TASK BODY TSK IS
     BEGIN
          NULL;
     END;

BEGIN

     DECLARE
          T : TSK(5);                         -- ERROR: CONSTRAINT.
     BEGIN
          NULL;
     END;

END B37202B;
