-- B37203A.ADA

-- CHECK THAT A DISCRIMINANT CONSTRAINT IS NOT OMITTED WHERE IT IS
-- REQUIRED, I.E., CHECK  THAT A DISCRIMINANT CONSTRAINT CANNOT BE
-- OMITTED FROM A SUBTYPE INDICATION FOR A TYPE_MARK HAVING
-- DISCRIMINANTS WITH NO DEFAULT VALUES WHEN THE SUBTYPE IS USED
-- IN AN OBJECT DECLARATION FOR A VARIABLE, AN ARRAY_TYPE_DEFINITION OR
-- A RECORD COMPONENT_DECLARATON.

-- ASL 7/2/81
-- RJW 1/16/86 - RENAMED FROM B37203A.ADA.  ADDED INITIAL VALUES.

PROCEDURE B37203A IS

     TYPE REC(DISC : INTEGER) IS
          RECORD
               NULL;
          END RECORD;

     OBJ1 : REC := (DISC => 5);               -- ERROR: UNCONSTRAINED.
     OBJ2 : REC;                              -- ERROR: UNCONSTRAINED.

     TYPE ARR IS ARRAY(1..10) OF REC;         -- ERROR: UNCONSTRAINED.

     ARROBJ : ARRAY(1..10) OF REC :=          -- ERROR: UNCONSTRAINED.
          (1 .. 10 => (DISC => 5));

     TYPE REC2 IS
          RECORD
               COMP : REC := (DISC => 5);     -- ERROR: UNCONSTRAINED.
               COMP2 : REC;                   -- ERROR: UNCONSTRAINED.
          END RECORD;

     PACKAGE PACK IS
          TYPE PRI IS PRIVATE;
          TYPE LIM IS LIMITED PRIVATE;
     PRIVATE
          TYPE PRI IS NEW REC;                -- ERROR: UNCONSTRAINED.
          TYPE LIM IS NEW REC;                -- ERROR: UNCONSTRAINED.
     END PACK;

BEGIN
     NULL;
END B37203A;
