-- B37212A.ADA

-- CHECK THAT A DISCRIMINANT CONSTRAINT IS NOT ALLOWED FOR AN INCOMPLETE
-- TYPE DECLARED IN A PRIVATE PART (IN AN ACCESS TYPE DEFINITION) IF
-- THE FULL TYPE DECLARATION IS GIVEN IN A PACKAGE BODY.

-- THIS TEST REFLECTS AI-00007.

-- JBG 10/17/86

PROCEDURE B37212A IS

     PACKAGE P1 IS
          X : INTEGER;
     PRIVATE
          TYPE INC (D : INTEGER);
          TYPE ACC_INC IS ACCESS INC(2);   -- OPTIONAL ERROR.
          TYPE U IS ACCESS INC;            -- OK.
     END P1;                               -- ERROR: INC IS CONSTRAINED.

     PACKAGE BODY P1 IS
          TYPE INC (D : INTEGER) IS
               RECORD NULL; END RECORD;
     END P1;

     PACKAGE P2 IS
          TYPE T1 IS PRIVATE;
          TYPE T2 IS LIMITED PRIVATE;
          TYPE T3 IS PRIVATE;
     PRIVATE
          TYPE INC1 (D : INTEGER);
          TYPE INC2 (D : POSITIVE);
          TYPE T1 IS ACCESS INC1(1);       -- OPTIONAL ERROR.
          TYPE T2 IS ACCESS INC2(-1);      -- OPTIONAL ERROR.
          TYPE T3 IS ACCESS INC1;          -- OK.
     END P2;                  -- ERROR: INC1 AND INC2 CONSTRAINED.

     PACKAGE BODY P2 IS
          TYPE INC1 (D : INTEGER) IS
               RECORD NULL; END RECORD;
          TYPE INC2 (D : POSITIVE) IS
               RECORD NULL; END RECORD;
     END P2;
BEGIN
     NULL;
END B37212A;
