-- B37212B0.ADA

-- OBJECTIVE:
--     FOR SEPARATELY COMPILED UNITS, CHECK THAT A DISCRIMINANT
--     CONSTRAINT IS NOT ALLOWED FOR AN INCOMPLETE TYPE DECLARED
--     IN A PRIVATE PART IF THE FULL TYPE DECLARATION IS GIVEN
--     IN A PACKAGE BODY.

--     THIS TEST REFLECTS AI-00007.

-- HISTORY:
--     JBG 10/21/86
--     JLH 09/25/87  REFORMATTED HEADER.

PACKAGE B37212B0 IS
     TYPE T1 IS PRIVATE;
     TYPE T2 IS LIMITED PRIVATE;
     TYPE T3 IS PRIVATE;
PRIVATE
     TYPE INC1 (D : INTEGER);
     TYPE INC2 (D : POSITIVE);
     TYPE T1 IS ACCESS INC1(-1);       -- ERROR: CONSTRAINT.
     TYPE T2 IS ACCESS INC2(1);        -- ERROR: CONSTRAINT.
     TYPE T3 IS ACCESS INC1;           -- OK.
END B37212B0;
