-- B37201B.ADA

-- OBJECTIVE:
--     CHECK THAT THE FORM OF A DISCRIMINANT CONSTRAINT MUST BE
--     CORRECT, NAMELY, CHECK THAT:

--     TOO FEW DISCRIMINANT VALUES CANNOT BE GIVEN.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B37201A.ADA.

PROCEDURE B37201B IS

     TYPE CONSTR2(D2,D3 : INTEGER) IS
          RECORD
               NULL;
          END RECORD;

     T11 : CONSTR2();                         -- ERROR: TOO FEW VALUES.

BEGIN
     NULL;
END B37201B;
