-- B37310B.ADA
 
-- CHECK THAT IF A DISCRIMINANT HAS A DYNAMIC SUBTYPE, AN OTHERS
-- CHOICE MUST NOT BE OMITTED IF ONE OR MORE VALUES IN THE BASE
-- TYPE'S RANGE ARE MISSING.
 
-- ASL 7/10/81
-- SPS 12/7/82 
-- SPS 2/17/83

PROCEDURE B37310B IS

     ACHAR : CHARACTER := 'A';
     ECHAR : CHARACTER := 'E';
     JCHAR : CHARACTER := 'J';
     MCHAR : CHARACTER := 'M';
     SUBTYPE STATCHAR IS CHARACTER RANGE 'I'..'N';
     SUBTYPE DYNCHAR IS CHARACTER RANGE ACHAR..ECHAR;
     SUBTYPE SSC IS STATCHAR RANGE JCHAR..MCHAR; 
     SUBTYPE SDYN IS DYNCHAR RANGE 'B' .. 'D';
     TYPE LETTER IS NEW CHARACTER RANGE 'A'..'Z';
     SUBTYPE DYNLETTER IS LETTER RANGE LETTER(ECHAR)..LETTER(JCHAR);
 
     TYPE REC1(DISC : SSC) IS
          RECORD
               CASE DISC IS
                    WHEN ' '..ASCII.DEL => NULL;
               END CASE; END RECORD;          -- ERROR: MISSING CHOICES.
 
     TYPE REC2(DISC : DYNCHAR) IS
          RECORD
               CASE DISC IS
                    WHEN ASCII.NUL..ASCII.TILDE => NULL;
               END CASE; END RECORD;          -- ERROR: MISSING CHOICE.
 
     TYPE REC3(DISC: DYNCHAR) IS
          RECORD
               CASE DISC IS
                    WHEN ' '..CHARACTER'LAST => NULL;
               END CASE; END RECORD;          -- ERROR: MISSING CHOICES.
 
     TYPE REC4(DISC : DYNLETTER) IS
          RECORD
               CASE DISC IS
                    WHEN LETTER'VAL(0)..'W'   => NULL;
                    WHEN 'Y'..LETTER'VAL(127) => NULL;
               END CASE; END RECORD;          -- ERROR: MISSING CHOICE.

     TYPE REC5(DISC : SDYN) IS
          RECORD
               CASE DISC IS
                    WHEN 'B' => NULL;
                    WHEN 'C' => NULL;
                    WHEN 'D' => NULL;
               END CASE;                      -- ERROR: MISSING CHOICES.
          END RECORD;

BEGIN
     NULL;
END B37310B;
