-- B37301A.ADA
 
-- CHECK THAT A VARIANT PART OF A RECORD MUST USE PROPER RESERVED
-- WORDS AND SYMBOLS WHERE NECESSARY, I.E.:
 
-- THE RESERVED WORD "IS" IS REQUIRED.
 
-- ASL 7/1/81
 
PROCEDURE B37301A IS
 
     TYPE DAY IS (SUN,MON,TUE,WED,THU,FRI,SAT);
 
     TYPE VREC0(DISC : DAY) IS
          RECORD
               COMP : INTEGER;
               CASE DISC                      -- ERROR: MISSING "IS".
                    WHEN OTHERS => NULL;
               END CASE;
          END RECORD;
 
         
BEGIN
     NULL;
END B37301A;
