-- B38001A.ADA
 
-- CHECK THAT MULTIPLE SUBTYPE_INDICATIONS ARE NOT ALLOWED
--  IN ACCESS_TYPE_DEFINITIONS.
 
-- DAT 3/6/81
-- JWC 4/1/85
 
PROCEDURE B38001A IS
 
     TYPE A1 IS ACCESS INTEGER;              -- OK.
     TYPE A2 IS ACCESS A1;                   -- OK.
     TYPE A3 IS ACCESS (INTEGER, BOOLEAN);   -- ERROR: ().
 
BEGIN
     NULL;
END B38001A;
