-- B38001C.ADA
 
-- CHECK THAT ARRAY_TYPE_DEFINITIONS MAY NOT REPLACE SUBTYPE_INDICATION
--  IN ACCESS_TYPE_DEFINITIONS.
 
-- DAT 3/6/81
-- JWC 4/1/85
 
PROCEDURE B38001C IS
 
     TYPE A1 IS ACCESS INTEGER;              -- OK.
     TYPE A2 IS ACCESS A1;                   -- OK.
     TYPE A3 IS ACCESS ARRAY (1..2) OF A1;   -- ERROR: ARRAY.
     TYPE A4 IS ARRAY (1..2) OF A2;          -- OK.
 
BEGIN
     NULL;
END B38001C;
