-- B38008A.ADA

-- CHECK THAT ACCESS TYPES USED IN A SUBTYPE_INDICATION
-- CANNOT BE CONSTRAINED WITH A RANGE CONSTRAINT
-- OR ACCURACY CONSTRAINT.
-- CHECK THAT ACCESS TYPES WHICH ARE ALREADY CONSTRAINED
-- CANNOT BE FURTHER CONSTRAINED IN A SUBTYPE_INDICATION.

-- DAT 3/19/81
-- VKG 01/05/83
-- PWB 02/20/86  DELETED CODE WHICH TESTED ANOTHER OBJECTIVE.

PROCEDURE B38008A IS

     TYPE A1 IS ACCESS INTEGER RANGE 1 .. 2; -- OK.
     TYPE A2 IS ACCESS INTEGER;              -- OK.
     TYPE A3 IS NEW A2 RANGE 1 .. 2;         -- ERROR: RANGE CONSTRAINT.
     TYPE A4 IS ACCESS FLOAT DIGITS 1;       -- OK.
     TYPE A5 IS NEW A4 DIGITS 1;             -- ERROR: ACC. CONSTRAINT.
     SUBTYPE A6 IS A2 RANGE 1 .. 2;          -- ERROR: RANGE CONST.
     SUBTYPE A7 IS A4 DIGITS 1;              -- ERROR: ACC. CONSTRAINT.

     TYPE AS IS ACCESS STRING;               -- OK.
     SUBTYPE CAS IS AS (1 .. 5);             -- OK.
     SUBTYPE CAS2 IS CAS (1 .. 5);           -- ERROR: TWICE CONSTR.

     TYPE AAS IS ACCESS AS (1 .. 4);         -- OK.
     TYPE AAS2 IS ACCESS AS;                 -- OK.
     SUBTYPE AASA IS AAS (1 .. 4);           -- ERROR: TWICE CONSTR.
     SUBTYPE AASB IS AAS2 (1 .. 4);          -- ERROR: CONSTR. ACCESS.

BEGIN
     NULL;
END B38008A;
