-- B38001B.ADA
 
-- CHECK THAT ACCESS_TYPE_DEFINITIONS MAY NOT REPLACE SUBTYPE_INDICATION
-- IN ACCESS_TYPE_DEFINITIONS.
 
-- DAT 3/6/81
-- JWC 4/1/85
 
PROCEDURE B38001B IS
 
     TYPE A1 IS ACCESS INTEGER;              -- OK.
     TYPE A2 IS ACCESS A1;                   -- OK.
     TYPE A3 IS ACCESS ACCESS A2;            -- ERROR: 2ND ACCESS.
 
BEGIN
     NULL;
END B38001B;
