-- B38001D.ADA
 
-- CHECK THAT RECORD_DEFINITIONS MAY NOT REPLACE SUBTYPE_INDICATION
--  IN ACCESS_TYPE_DEFINITIONS.
 
-- DAT 3/6/81
-- JWC 4/1/85
 
PROCEDURE B38001D IS
 
     TYPE A1 IS ACCESS INTEGER;                   -- OK.
     TYPE A9 IS ACCESS RECORD NULL; END RECORD;   -- ERROR: RECORD.
 
BEGIN
     NULL;
END B38001D;
