-- B38003A.ADA
 
-- CHECK THAT IF AN INDEX OR DISCRIMINANT CONSTRAINT IS PROVIDED IN
-- A SUBTYPE DEFINITION OR DIRECTLY IN AN ACCESS TYPE DEFINITION,
-- THE ACCESS TYPE NAME CANNOT SUBSEQUENTLY BE USED WITH AN INDEX 
-- OR DISCRIMINANT CONSTRAINT, EVEN IF THE SAME CONSTRAINT VALUES 
-- ARE USED.

-- CASES:
--     A) OBJECT DECLARATION
--     B) ARRAY COMPONENT DECLARATION
--     C) RECORD COMPONENT DECLARATION
--     D) ACCESS TYPE DECLARATION
--     E) DERIVED TYPE DEFINITION
--     F) PARAMETER DECLARATION
--     G) RETURN TYPE IN FUNCTION DECLARATION

--        1) WHEN INDEX CONSTRAINT IS PROVIDED IN ACCESS TYPE DEF'NN.
--        2) WHEN DISCRIMINANT CONSTRAINT IS PROVIDED IN ACCESS TYPE
--           DEFINITION.
--        3) WHEN SUBTYPE INDICATION IS ALREADY CONSTRAINED.
 
-- ASL 6/22/81
-- SPS 12/10/82
-- AH  8/25/86  ADDED CASE WITH CONSTRAINED SUBTYPE.

PROCEDURE B38003A IS

     TYPE ARR IS ARRAY(INTEGER RANGE <>) OF INTEGER;
     TYPE ARR_NAME IS ACCESS ARR(1..5);               -- 1.
     SUBTYPE SUB_ARR IS ARR(1..5);                    -- 3.
     TYPE ARR_NAME3 IS ACCESS SUB_ARR;                -- 3.
 
     TYPE REC(DISC : INTEGER) IS
          RECORD
               NULL;
          END RECORD;
 
     TYPE REC_NAME IS ACCESS REC(5);                  -- 2.
 
     OBJ1 : ARR_NAME(1..5);                        -- ERROR: A1.
     OBJ2 : REC_NAME(5);                           -- ERROR: A2.
     OBJ3 : ARR_NAME3(1..5);                       -- ERROR: A3.
 

     TYPE ARR2 IS ARRAY(1..10) OF ARR_NAME(1..5);  -- ERROR: B1.
     TYPE ARR3 IS ARRAY(1..10) OF REC_NAME(5);     -- ERROR: B2.
     TYPE ARR4 IS ARRAY(1..10) OF ARR_NAME3(1..5); -- ERROR: B3.
  
     TYPE REC2 IS
          RECORD
               COMP1 : ARR_NAME(1..5);             -- ERROR: C1.
               COMP2 : REC_NAME(5);                -- ERROR: C2.
               COMP3 : ARR_NAME3(1..5);            -- ERROR: C3.
          END RECORD;
 
     TYPE AA_NAME IS ACCESS ARR_NAME(1..5);        -- ERROR: D1.
     TYPE AR_NAME IS ACCESS REC_NAME(5);           -- ERROR: D2.
     TYPE AS_NAME IS ACCESS ARR_NAME3(1..5);       -- ERROR: D3.
 
     TYPE DER1 IS NEW ARR_NAME(1..5);              -- ERROR: E1.
     TYPE DER2 IS NEW REC_NAME(5);                 -- ERROR: E2.
     TYPE DER3 IS NEW ARR_NAME3(1..5);             -- ERROR: E3.
 
     PROCEDURE PROC1 (PARM1 : IN OUT ARR_NAME(1..5);      -- ERROR: F1.
                      PARM2 : IN OUT REC_NAME(5);         -- ERROR: F2.
                      PARM3 : IN OUT ARR_NAME3(1..5)) IS  -- ERROR: F3.
     BEGIN
          PARM1 := NEW ARR(1..5);
          PARM2 := NEW REC(5);
          PARM3 := NEW SUB_ARR;
     END PROC1;

     FUNCTION FUNC1 RETURN ARR_NAME(1..5) IS       -- ERROR: G1.
          F1 : ARR_NAME;
     BEGIN
          F1 := NEW ARR(1..5);
          RETURN F1;
     END FUNC1;

     FUNCTION FUNC2 RETURN REC_NAME(5) IS          -- ERROR: G2.
          F2 : REC_NAME;
     BEGIN
          F2 := NEW REC(5);
          RETURN F2;
     END FUNC2;

     FUNCTION FUNC3 RETURN ARR_NAME3(1..5) IS      -- ERROR: G3.
          F3 : ARR_NAME3;
     BEGIN
          F3 := NEW SUB_ARR;
          RETURN F3;
     END FUNC3;

 BEGIN
     NULL;
END B38003A;
