-- B38101D.ADA

-- CHECK THAT THE FULL TYPE DECLARATION OF AN INCOMPLETE 
-- TYPE CANNOT BE A PRIVATE TYPE DECLARATION.

-- AH  8/27/86

PROCEDURE B38101D IS
     PACKAGE PACK1 IS
          TYPE T1;
          TYPE T2 IS PRIVATE;
          TYPE T1 IS PRIVATE;              -- ERROR: T1.
     PRIVATE
          TYPE T2 IS NEW INTEGER;
     END PACK1;

     PACKAGE BODY PACK1 IS
     END PACK1;

BEGIN
     NULL;
END B38101D;
