-- B38103C0.ADA

-- JRK 2/16/84

PACKAGE B38103C0 IS

     SUBTYPE I IS INTEGER RANGE 0..2;
     SUBTYPE I1 IS I;

     V1, V2, V : I := 0;

     PACKAGE P1 IS
          SUBTYPE I2 IS I1;
          W1, W2 : I := 0;
     END P1;
     USE P1;

     WW1 : I RENAMES P1.W1;
     VV1 : I RENAMES V1;

     PACKAGE P3 IS
          SUBTYPE T IS I;
     END P3;
     USE P3;

     FUNCTION F1 (L, R : INTEGER) RETURN INTEGER RENAMES STANDARD."+";

     TYPE RD (D : I := 0) IS
          RECORD NULL; END RECORD;

     TYPE R IS
          RECORD NULL; END RECORD;

END B38103C0;
