-- B38101B.ADA
 
-- CHECK THAT IF AN INCOMPLETE TYPE DECLARATION APPEARS IN THE
-- DECLARATIVE PART OF A TASK BODY, THE CORRESPONDING COMPLETE
-- DECLARATION MUST APPEAR IN THE SAME DECLARATION PART, EXCLUDING
-- ANY NESTED DECLARATIVE PARTS OR PACKAGE SPECIFICATIONS.
 
-- ASL 7/17/81
-- SPS 10/26/82

PROCEDURE B38101B IS
 
     TASK TSK;
 
     TASK BODY TSK IS
          TYPE T;
          TYPE U;
          PACKAGE PACK IS
               TYPE T IS (X);
          END PACK;
          PROCEDURE PROC IS                   -- ERROR: T,U INCOMPLETE.
               TYPE U IS (X);
          BEGIN
               NULL;
          END PROC;
     BEGIN
          NULL;
     END TSK;
 
BEGIN
     NULL;
END B38101B;
