-- B38105A.ADA

-- CHECK THAT AN INCOMPLETE TYPE CANNOT BE USED PRIOR TO ITS FULL
-- DECLARATION IN AN OBJECT DECLARATION, COMPONENT DECLARATION, OR
-- PARAMETER DECLARATION, SUBTYPE DECLARATION, OR AS THE COMPONENT TYPE
-- IN AN ARRAY DECLARATION.

-- CHECK THAT AN INCOMPLETE TYPE CANNOT BE USED IN AN ACCESS TYPE
-- DEFINITION WITH A RANGE CONSTRAINT, ACCURACY CONSTRAINT, OR INDEX
-- CONSTRAINT.

-- CHECK THAT AN ACCESS TYPE WHOSE DESIGNATED TYPE IS AN INCOMPLETE TYPE
-- CANNOT BE USED WITH INDEX CONSTRAINTS PRIOR TO THE FULL DECLARATION
-- OF THE TYPE.

-- JBG 4/27/83

PROCEDURE B38105A IS

     TYPE INC;
     TYPE INC1;
     TYPE INC2;
     TYPE INC3;
     TYPE INC4;
     V : INC;                           -- ERROR: INCOMPLETE TYPE.

     TYPE ARR IS ARRAY (1..2) OF INC;   -- ERROR: INCOMPLETE TYPE.

     TYPE REC IS
          RECORD
               A : INC;                      -- ERROR: INCOMPLETE TYPE.
          END RECORD;

     PROCEDURE P (X : INC);                  -- ERROR: INCOMPLETE TYPE.

     GENERIC
          X : INC;                           -- ERROR: INCOMPLETE TYPE.
     PACKAGE P1 IS END P1;

     SUBTYPE SINC IS INC;                    -- ERROR: INCOMPLETE TYPE.

     TYPE ACC1 IS ACCESS INC1 RANGE 4..6;    -- ERROR: INCOMPLETE TYPE.

     TYPE ACC2 IS ACCESS 
          INC2 DIGITS 1 RANGE 0.0 .. 0.0;    -- ERROR: INCOMPLETE TYPE.

     TYPE ACC3 IS ACCESS
          INC3 DELTA 1.0 RANGE -1.0 .. 1.0;  -- ERROR: INCOMPLETE TYPE.

     TYPE ACC4 IS ACCESS INC4(1..2);         -- ERROR: INCOMPLETE TYPE.

     TYPE A_INC IS ACCESS INC4;              -- OK.

     SUBTYPE SA_INC IS A_INC(1..2);          -- ERROR: INCOMPLETE TYPE.

     TYPE INC IS NEW INTEGER;
     TYPE INC1 IS NEW INTEGER;
     TYPE INC2 IS NEW FLOAT;
     TYPE INC3 IS DELTA 1.0 RANGE -1.0 .. 1.0;
     TYPE INC4 IS ARRAY (INTEGER RANGE <>) OF INTEGER;

     TYPE ACC5 IS ACCESS INC1 RANGE 4..6;
     TYPE ACC6 IS ACCESS INC2 DIGITS 1 RANGE 0.0 .. 0.0;
     TYPE ACC7 IS ACCESS INC3 DELTA 1.0 RANGE -1.0 .. 1.0;
     TYPE ACC8 IS ACCESS INC4(1..2);

     PROCEDURE P (X : INC) IS                
     BEGIN
          NULL;
     END P;

BEGIN
          NULL;
END B38105A;
