-- B39004G.ADA

-- OBJECTIVE:
--      CHECK THAT A SIZE SPECIFICATION IS NOT ALLOWED IN A DECLARATIVE
--      PART AFTER A FUNCTION BODY.

-- HISTORY:
--      RJW 07/16/86  CREATED ORIGINAL TEST.
--      BCB 09/23/87  REMOVED UNNECESSARY REPRESENTATION CLAUSES.

PROCEDURE B39004G IS

     TYPE SHORT IS DELTA 2.0 ** (-1) RANGE -100.0 .. 100.0;

     FUNCTION F RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END F;

     FOR SHORT'SIZE USE 15;             -- ERROR: SIZE SPEC AFTER
                                        --        FUNCTION BODY.
BEGIN
     NULL;
END B39004G;
