-- B39004D.ADA

-- CHECK THAT A RENAMING DECLARATION IS NOT ALLOWED IN A DECLARATIVE
-- PART AFTER A PROCEDURE BODY STUB.

-- RJW 2/27/86 

PROCEDURE B39004D IS
     
     PACKAGE AA IS END AA;

     I1 : INTEGER;
     I2 : INTEGER RENAMES I1;           -- OK.

     PROCEDURE B39004D_P;

     PROCEDURE Q RENAMES B39004D_P;     -- OK.

     PROCEDURE B39004D_P IS SEPARATE;
          
     PACKAGE BB RENAMES AA;             -- ERROR: RENAMING DECL AFTER
                                        --        PROCEDURE BODY STUB.

BEGIN
     NULL;          
END B39004D;                                
