-- B39004L.ADA

-- OBJECTIVE:
--      CHECK THAT A RECORD REPRESENTATION CLAUSE IS NOT ALLOWED IN A
--      DECLARATIVE PART AFTER A TASK BODY STUB.

-- HISTORY:
--      RJW 07/16/86  CREATED ORIGINAL TEST.
--      BCB 09/23/87  REMOVED UNNECESSARY REPRESENTATION CLAUSES.

PROCEDURE B39004L IS

     TYPE FIX IS DELTA 0.25 RANGE -1.0 .. 1.0;

     TYPE COMPLEX IS
          RECORD
               RE : FIX;
               IM : FIX;
          END RECORD;

     TASK B39004L1 IS END B39004L1;

     TASK BODY B39004L1 IS SEPARATE;

     FOR COMPLEX USE                              -- ERROR: RECORD REP
          RECORD AT MOD 16;                       -- CLAUSE AFTER TASK
               RE AT 0 RANGE 0 .. 15;             -- BODY STUB.
               IM AT 2 RANGE 0 .. 15;
          END RECORD;

BEGIN
     NULL;
END B39004L;
