-- B39004H.ADA

-- CHECK THAT A COLLECTION SIZE SPECIFICATION IS NOT ALLOWED IN A 
-- DECLARATIVE PART AFTER A PACKAGE BODY.

-- RJW 7/16/86 

WITH SYSTEM;
PROCEDURE B39004H IS
     
     TYPE CELL IS NEW INTEGER;
     TYPE LINK IS ACCESS CELL;

     TYPE PERSON IS 
          RECORD
               NULL;
          END RECORD;

     TYPE PERSON_NAME IS ACCESS PERSON;

     TYPE MATRIX IS ARRAY (INTEGER RANGE <>, INTEGER RANGE <>) 
          OF FLOAT;
     TYPE FRAME IS ACCESS MATRIX;

     FOR LINK'STORAGE_SIZE USE                   -- MAY BE REJECTED.
          500 * (CELL'SIZE / SYSTEM.STORAGE_UNIT);

     PACKAGE PKG IS END PKG;

     FOR PERSON_NAME'STORAGE_SIZE USE 1000;      -- MAY BE REJECTED.

     PACKAGE BODY PKG IS END PKG;
          
     FOR FRAME'STORAGE_SIZE USE 600;             -- ERROR: COLLECTION 
                                                 -- SIZE AFTER PACKAGE
                                                 -- BODY.
BEGIN
     NULL;          
END B39004H;                                
