-- B39004F.ADA

-- CHECK THAT A SUBTYPE DECLARATION IS NOT ALLOWED IN A DECLARATIVE
-- PART AFTER A TASK BODY STUB.

-- RJW 2/27/86 

PROCEDURE B39004F IS
     
     SUBTYPE ST1 IS INTEGER;            -- OK.

     TASK B39004F_T IS END B39004F_T;

     SUBTYPE ST2 IS BOOLEAN;            -- OK.

     TASK BODY B39004F_T IS SEPARATE;
          
     SUBTYPE ST3 IS CHARACTER;          -- ERROR: SUBTYPE DECL AFTER
                                        --        TASK BODY STUB.
BEGIN
     NULL;          
END B39004F;                                
