-- B39004J.ADA

-- OBJECTIVE:
--      CHECK THAT A 'SMALL SPECIFICATION FOR A FIXED POINT TYPE IS NOT
--      ALLOWED IN A DECLARATIVE PART AFTER A PROCEDURE BODY STUB.

-- HISTORY:
--      RJW 07/16/86  CREATED ORIGINAL TEST.
--      BCB 09/23/87  REMOVED UNNECESSARY REPRESENTATION CLAUSES.

PROCEDURE B39004J IS

     TYPE VOLT IS DELTA 0.125 RANGE 0.0 .. 255.0;

     PROCEDURE B39004J1 IS SEPARATE;

     FOR VOLT'SMALL USE 2.0 ** (-4);           -- ERROR: 'SMALL SPEC
                                               -- AFTER PROCEDURE
                                               -- BODY STUB.
BEGIN
     NULL;
END B39004J;
