-- B41101C.ADA

-- CHECK THAT THE BASE TYPE OF THE SUBSCRIPT OF AN INDEXED
--   COMPONENT MUST BE THE SAME AS THE BASE TYPE OF THE INDEX
--   OF THE ARRAY TYPE.

-- WKB 8/12/81
-- JBG 8/21/83

PROCEDURE B41101C IS

     SUBTYPE S IS INTEGER RANGE 5..50;
     TYPE S1 IS NEW S;
     TYPE S2 IS ARRAY (S1 RANGE 5..10) OF INTEGER;
     X : S1 := 6;
     Y : S2 := (5..10 => 1);

     TYPE T IS ARRAY (INTEGER RANGE 0..20) OF INTEGER;
     A : T := (0..20 => 2);
     I : INTEGER;
     J : INTEGER := 6;

     TYPE U IS (E1,E2,E3,E4);
     U1 : ARRAY (U) OF INTEGER;

BEGIN

     I := A(X);               -- ERROR: DIFFERENT INDEX BASE TYPES.
     NULL;
     I := A(E2);              -- ERROR: DIFFERENT INDEX BASE TYPES.
     NULL;
     I := A(FALSE);           -- ERROR: DIFFERENT INDEX BASE TYPES.
     NULL;
     I := A(ASCII.CR);        -- ERROR: DIFFERENT INDEX BASE TYPES.
     NULL;
     I := Y(J);               -- ERROR: DIFFERENT INDEX BASE TYPES.
     NULL;
     I := U1(3);              -- ERROR: DIFFERENT INDEX BASE TYPES.

END B41101C;
