-- B41202D.ADA

-- CHECK THAT THE NAME PART OF A SLICE MAY NOT BE AN IDENTIFIER WHOSE
--   DESIGNATED OBJECT IS AN ACCESS VALUE DESIGNATING AN ARRAY.

-- WKB 8/5/81
-- SPS 2/4/83
-- JBG 2/6/83

PROCEDURE B41202D IS

     TYPE A IS ARRAY (NATURAL RANGE <> ) OF INTEGER;
     TYPE AA IS ACCESS A;
     TYPE AAA IS ACCESS AA;

     I : A (1..3);
     AC : AAA;

BEGIN

     AC := NEW AA'(NEW A'(2,4,6,8,10));
     I := AC(1..3);                    -- ERROR: DOUBLE DEREFERENCING
                                       --        VIA SLICING.

END B41202D;
