-- B41202C.ADA

-- CHECK THAT THE NAME PART OF A SLICE MAY NOT BE AN ALLOCATOR.

-- WKB 8/5/81
-- SPS 2/4/83
-- JBG 2/6/83

PROCEDURE B41202C IS

     TYPE A IS ARRAY (NATURAL RANGE <> ) OF INTEGER;
     TYPE AA IS ACCESS A;
     TYPE AAA IS ACCESS AA;

     I : A (1..3);
     AC : AAA;

BEGIN

     I := NEW A'(2,4,6,8,10) (1..3);   -- ERROR: SLICED ALLOCATOR.
     NULL;

END B41202C;
