-- B41327B.ADA

-- CHECK THAT IMPLICITLY DECLARED EQUALITY AND INEQUALITY OPERATORS
-- MAY NOT BE SELECTED FROM OUTSIDE A PACKAGE USING AN EXPANDED NAME,
-- FOR A LIMITED PRIVATE TYPE.

-- TBN  7/18/86

PROCEDURE B41327B IS

     PACKAGE P IS
          TYPE KEY IS LIMITED PRIVATE;
          TYPE CHAR IS LIMITED PRIVATE;
          FUNCTION INIT_KEY (X : NATURAL) RETURN KEY;
          FUNCTION INIT_CHAR (X : CHARACTER) RETURN CHAR;
     PRIVATE
          TYPE KEY IS NEW NATURAL;
          TYPE CHAR IS NEW CHARACTER;
     END P;

     BOOLEAN_1 : BOOLEAN := TRUE;

     PACKAGE BODY P IS

          FUNCTION INIT_KEY (X : NATURAL) RETURN KEY IS
          BEGIN
               RETURN (KEY (X));
          END INIT_KEY;

          FUNCTION INIT_CHAR (X : CHARACTER) RETURN CHAR IS
          BEGIN
               RETURN (CHAR (X));
          END INIT_CHAR;

     BEGIN
          NULL;
     END P;

BEGIN

     BOOLEAN_1 := P."=" (P.INIT_KEY (1), P.INIT_KEY (2));      -- ERROR:
     NULL;
     BOOLEAN_1 := P."/=" (P.INIT_CHAR ('A'),
                          P.INIT_CHAR ('B'));                  -- ERROR:

END B41327B;
