-- B41302B.ADA

-- CHECK THAT L.R IS ILLEGAL IF L IS AN ALLOCATOR.

-- WKB 8/13/81
-- RJK 8/30/83

PROCEDURE B41302B IS

     TYPE R IS
          RECORD
               B : BOOLEAN;
               I : INTEGER;
          END RECORD;

     TYPE AR IS ACCESS R;

     X : INTEGER;

BEGIN

     X := NEW R'(B=>FALSE, I=>1) . I;   -- ERROR: SELECTED ALLOCATOR.

END B41302B;
