-- B41302A.ADA

-- CHECK THAT L.R IS ILLEGAL IF L IS AN AGGREGATE.

-- WKB 8/13/81
-- RJK 8/30/83

PROCEDURE B41302A IS

     TYPE R IS
          RECORD
               B : BOOLEAN;
               I : INTEGER;
          END RECORD;

     X : INTEGER;

BEGIN

     X := (B=>FALSE, I=>1) . I;         -- ERROR: SELECTED AGGREGATE.

END B41302A;
