-- B42004A.ADA

-- CHECK THAT THE CHARACTER LITERALS IN A STRING LITERAL MUST BE
-- DIRECTLY VISIBLE.

-- SPS 2/23/84

PROCEDURE B42004A IS

     PACKAGE PACK IS
          TYPE CODE IS ('A', 'B', 'C', 'D', 'E');
          TYPE CODE_ARR IS ARRAY (POSITIVE RANGE <>) OF CODE;
     END PACK;

     ST : PACK.CODE_ARR (1 .. 3) := "ABC";   -- ERROR: LITERALS NOT
                                             -- VISIBLE. 
     USE PACK;

     STR : CODE_ARR (1.. 3) := "ABC";        -- OK.

BEGIN
     NULL;
END B42004A;
