-- B43001F.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'RANGE(N).

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001F IS

     N : CONSTANT := 2;

     B : INTEGER := 3;

     TYPE A IS ARRAY(1..3,1..3) OF INTEGER;

BEGIN

     IF B IN (1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5)'RANGE(N) -- ERROR:
          THEN NULL;
     END IF;

END B43001F;
