-- B43001D.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'SIZE.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001D IS

     TYPE REC(D : INTEGER) IS RECORD
          A : INTEGER;
     END RECORD;

     B : REC(3);

BEGIN

     B.A := (D => 3, A => 10)'SIZE;                    -- ERROR:

END B43001D;
