-- B43002F.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN TWO COMPONENT
--     ASSOCIATIONS WITH THE CHOICE OTHERS.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002F IS

     TYPE REC (D : BOOLEAN) IS RECORD
          COMP1 : INTEGER;
          COMP2 : INTEGER;
          COMP3 : INTEGER;
          COMP4 : INTEGER;
     END RECORD;

     A : REC(TRUE);

BEGIN

     A := (D => TRUE, COMP1 => 2, OTHERS => 3, OTHERS => 4); -- ERROR:

END B43002F;
