-- B43002A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     IS EMPTY PARENTHESES.

-- HISTORY:
--     BCB 01/22/88  CREATED ORIGINAL TEST.

PROCEDURE B43002A IS

     A : ARRAY(1..5) OF INTEGER;

BEGIN

     A := ();                                          -- ERROR:

END B43002A;
