-- B43002N.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     CONTAINS "OTHERS".

-- HISTORY:
--     BCB 05/26/88  CREATED ORIGINAL TEST.

PROCEDURE B43002N IS

     D : ARRAY(1..5) OF INTEGER;

BEGIN

     D := (OTHERS => );                                -- ERROR:

END B43002N;
