-- B43001L.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'LENGTH(N).

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001L IS

     N : CONSTANT := 2;

     TYPE A IS ARRAY(1..3,1..3) OF INTEGER;

BEGIN

     IF A'LENGTH(N) =
       (1 => (1,2,3),2 => (4,5,6),3 => (7,8,9))'LENGTH(N) THEN -- ERROR:
          NULL;
     END IF;

END B43001L;
