-- B43002C.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     USES NAMED NOTATION.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43002C IS

     TYPE REC (D : INTEGER := 0) IS RECORD
          COMP1 : INTEGER := 1;
          COMP2 : INTEGER := 2;
     END RECORD;

     B : REC;

BEGIN

     B := (D => , COMP1 => , COMP2 => );               -- ERROR:

END B43002C;
