-- B43002B.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     IS EMPTY PARENTHESES.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43002B IS

     TYPE REC IS RECORD
          NULL;
     END RECORD;

     A : REC;

BEGIN

     A := ();                                          -- ERROR:

END B43002B;
