-- B43002H.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN A CHOICE OTHERS
--     IN ANY BUT THE LAST COMPONENT ASSOCIATION.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002H IS

     TYPE REC IS RECORD
          COMP1 : INTEGER;
          COMP2 : INTEGER;
          COMP3 : INTEGER;
          COMP4 : INTEGER;
     END RECORD;

     A, B, C : REC;

BEGIN

     A := (COMP1 => 2, OTHERS => 3, COMP4 => 4);       -- ERROR:

     B := (OTHERS => 1, COMP4 => 5);                   -- ERROR:

     C := (COMP1 => 1, OTHERS => 5);                   -- OK.

END B43002H;
