-- B43001B.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX TO FORM
--     AN INDEXED COMPONENT.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001B IS

     TYPE ARR IS ARRAY(1..5) OF INTEGER;

     B : ARR;

BEGIN

     B(1) := (1,2,3,4,5)(1);                          -- ERROR:

END B43001B;
