-- B43001G.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'FIRST.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001G IS

     TYPE A IS ARRAY(1..5) OF INTEGER;

BEGIN

     IF A'FIRST = (1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5)'FIRST THEN
          NULL;                                        -- ERROR:
     END IF;

END B43001G;
