-- B43001A.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX TO FORM
--     A SELECTED COMPONENT.

-- HISTORY:
--     BCB 01/22/88  CREATED ORIGINAL TEST.

PROCEDURE B43001A IS

     TYPE REC(D : INTEGER) IS RECORD
          A : INTEGER;
     END RECORD;

     B : REC(3);

BEGIN

     B.A := (D => 3, A => 10).A;                       -- ERROR:

END B43001A;
