-- B43002I.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN A CHOICE OTHERS
--     NOT APPEARING ALONE IN ITS COMPONENT ASSOCIATION.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002I IS

     TYPE ARR IS ARRAY(1..5) OF INTEGER;

     A : ARR;

BEGIN

     A := ARR'(1 | OTHERS => 3);                       -- ERROR:

END B43002I;
