-- B43002M.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     CONTAINS ONLY COMMAS.

-- HISTORY:
--     BCB 05/26/88  CREATED ORIGINAL TEST.

PROCEDURE B43002M IS

     C : ARRAY(1..5) OF BOOLEAN;

BEGIN

     C := ( , , , , );                                 -- ERROR:

END B43002M;
