-- B43001E.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'RANGE.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001E IS

     TYPE A IS ARRAY(1..5) OF INTEGER;

     B : INTEGER := 3;

BEGIN

     IF B IN (1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5)'RANGE   -- ERROR:
          THEN NULL;
     END IF;

END B43001E;
