-- B43001J.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'LAST(N).

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001J IS

     N : CONSTANT := 2;

     TYPE A IS ARRAY(1..3,1..3) OF INTEGER;

BEGIN

     IF A'LAST(N) =
        (1 => (1,2,3), 2|3 => (4,5,6))'LAST(N) THEN    -- ERROR:
          NULL;
     END IF;

END B43001J;
