-- B43005F.ADA

-- OBJECTIVE:
--     CHECK THAT THE USE OF MIXED POSITIONAL AND NAMED COMPONENT
--     ASSOCIATIONS IS NOT USED IN RESOLVING THE TYPE OF AN AGGREGATE.

-- HISTORY:
--     BCB 07/14/88

PROCEDURE B43005F IS

     TYPE ARR IS ARRAY(1..4) OF INTEGER;

     TYPE REC (D : INTEGER := 0) IS RECORD
          COMP1 : INTEGER;
          COMP2 : INTEGER;
          COMP3 : BOOLEAN;
     END RECORD;

     PROCEDURE P (X : ARR) IS
     BEGIN
          NULL;
     END P;

     PROCEDURE P (X : REC) IS
     BEGIN
          NULL;
     END P;

BEGIN

     P ((0,1,COMP2 => 2, COMP3 => TRUE));                   -- ERROR:

END B43005F;
