-- B43001K.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE CANNOT BE USED AS A PREFIX OF THE
--     ATTRIBUTE 'LENGTH.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43001K IS

     TYPE A IS ARRAY(1..5) OF INTEGER;

BEGIN

     IF A'LENGTH = (1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5)'LENGTH THEN
          NULL;                                        -- ERROR:
     END IF;

END B43001K;
