-- B43002G.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN A CHOICE OTHERS
--     IN ANY BUT THE LAST COMPONENT ASSOCIATION.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002G IS

     TYPE ARR IS ARRAY(1..5) OF INTEGER;

     A, B, C : ARR;

BEGIN

     A := ARR'(1 => 1, 2 => 2, OTHERS => 3, 5 => 5);  -- ERROR:

     B := ARR'(OTHERS => 5, 5 => 3);                  -- ERROR:

     C := ARR'(1 => 2, OTHERS => 3);                  -- OK.

END B43002G;
