-- B43002O.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     CONTAINS ONLY COMMAS.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B43002O IS

     TYPE REC (D : INTEGER := 0) IS RECORD
          COMP1 : INTEGER := 1;
          COMP2 : INTEGER := 2;
     END RECORD;

     C : REC;

BEGIN

     C := ( , , );                                     -- ERROR:

END B43002O;
