-- B43002K.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN A POSITIONAL
--     ASSOCIATION FOLLOWING A NAMED ASSOCIATION.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002K IS

     TYPE REC IS RECORD
          COMP1 : INTEGER;
          COMP2 : INTEGER;
          COMP3 : INTEGER;
          COMP4 : INTEGER;
     END RECORD;

     A : REC;

BEGIN

     A := (COMP1 => 1, COMP2 => 2, COMP3 => 3, 4);     -- ERROR:

END B43002K;
