-- B43002E.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN TWO COMPONENT
--     ASSOCIATIONS WITH THE CHOICE OTHERS.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002E IS

     TYPE ARR IS ARRAY(1..5) OF INTEGER;

     A : ARR;

BEGIN

     A := ARR'(1 => 1, 2 => 2, OTHERS => 3, OTHERS => 4);  -- ERROR:

END B43002E;
