-- B43002J.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD AGGREGATE CANNOT CONTAIN A CHOICE OTHERS
--     NOT APPEARING ALONE IN ITS COMPONENT ASSOCIATION.

-- HISTORY:
--     BCB 07/08/88  CREATED ORIGINAL TEST.

PROCEDURE B43002J IS

     TYPE REC IS RECORD
          COMP1 : INTEGER;
          COMP2 : INTEGER;
          COMP3 : INTEGER;
          COMP4 : INTEGER;
     END RECORD;

     A : REC;

BEGIN

     A := (COMP1 | OTHERS => 3);                       -- ERROR:

END B43002J;
