-- B43002L.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE CANNOT CONTAIN AN EMPTY LIST
--     OF COMPONENT ASSOCIATIONS.  CHECK THE CASE IN WHICH THE LIST
--     USES NAMED NOTATION.

-- HISTORY:
--     BCB 05/26/88  CREATED ORIGINAL TEST.

PROCEDURE B43002L IS

     B : ARRAY(1..5) OF FLOAT;

BEGIN

     B := (1 => , 2 => , 3 => , 4 => , 5 => );         -- ERROR:

END B43002L;
