-- B43105C.ADA

-- OBJECTIVE:
--     CHECK THAT IN A RECORD AGGREGATE, THE RESOLUTION OF E IN
--     (X | Y => E) DOES NOT USE THE FACT THAT X AND Y MUST HAVE
--     THE SAME TYPE.

-- HISTORY:
--     DHH 06/16/88 CREATED ORIGINAL TEST.

PROCEDURE B43105C IS

     TYPE COLOR IS (RED, YELLOW, BLUE);

     TYPE LIGHT IS (RED, GREEN, YELLOW);

     TYPE REC1(X : COLOR) IS
          RECORD
               Y : LIGHT;
          END RECORD;

     TYPE REC2 IS
          RECORD
               X : COLOR;
               Y : COLOR;
          END RECORD;

     PROCEDURE PROC_VR(X : REC1) IS
     BEGIN
          NULL;
     END PROC_VR;

     PROCEDURE PROC_VR(X : REC2) IS
     BEGIN
          NULL;
     END PROC_VR;

BEGIN

     PROC_VR((X | Y => RED));                      -- ERROR: AMBIGUOUS.

END B43105C;
