-- B43209B.ADA

-- OBJECTIVE:
--     CHECK THAT A STRING LITERAL USED IN A MULTIDIMENSIONAL ARRAY
--     AGGREGATE IN PLACE OF THE FINAL ONE-DIMENSIONAL AGGREGATE MUST
--     NOT BE ENCLOSED IN PARENTHESES.

-- HISTORY:
--     DHH 06/17/88 CREATED ORIGINAL TEST.

PROCEDURE B43209B IS

     TYPE AS IS ARRAY(1 .. 2) OF STRING(2 .. 3);
     TYPE A2 IS ARRAY(1 .. 2, POSITIVE RANGE 2 .. 3) OF CHARACTER;

     X : AS := (1 .. 2 => ("EF"));   -- LEGAL. STRING TO STRING.

     Y : A2 := (1 .. 2 => ("EF"));                      -- ERROR:
                                     -- STRING INTO TWO CHARACTER ARRAY.

     Z : A2 := (1 .. 2 => "EF");     -- LEGAL.
BEGIN
     NULL;
END B43209B;
