-- B43221B.ADA

-- OBJECTIVE:
--     CHECK THAT THE LENGTH OF AN ARRAY AGGREGATE IS NOT USED IN
--     OVERLOAD RESOLUTION.

-- HISTORY:
--     DHH 06/17/88 CREATED ORIGINAL TEST.

PROCEDURE B43221B IS

     TYPE BOOLEN IS ARRAY(1 .. 2) OF BOOLEAN;

     TYPE BOOLAN IS ARRAY(1 .. 4) OF BOOLEAN;

     PROCEDURE PROC_VR(X : BOOLEN) IS
     BEGIN
          NULL;
     END PROC_VR;

     PROCEDURE PROC_VR(X : BOOLAN) IS
     BEGIN
          NULL;
     END PROC_VR;

BEGIN
     PROC_VR((TRUE, FALSE));                       -- ERROR: AMBIGUOUS.

     PROC_VR((TRUE, TRUE, TRUE, FALSE));           -- ERROR: AMBIGUOUS.

     PROC_VR((1 => TRUE, 2 => FALSE));             -- ERROR: AMBIGUOUS.

     PROC_VR((1 .. 4 => TRUE));                    -- ERROR: AMBIGUOUS.

END B43221B;
