-- B43221A.ADA

-- OBJECTIVE:
--     CHECK THAT THE COMPLETENESS OF AN ARRAY AGGREGATE IS NOT USED IN
--     OVERLOAD RESOLUTION.

-- HISTORY:
--     DHH 06/17/88 CREATED ORIGINAL TEST.

PROCEDURE B43221A IS

     TYPE ARRY IS ARRAY(1 .. 4) OF INTEGER;

     TYPE REC(X, Y : INTEGER) IS
          RECORD
               NULL;
          END RECORD;

     PROCEDURE PROC_VR(X : REC) IS
     BEGIN
          NULL;
     END PROC_VR;

     PROCEDURE PROC_VR(X : ARRY) IS
     BEGIN
          NULL;
     END PROC_VR;

BEGIN
     PROC_VR((3, 6));                              -- ERROR: AMBIGUOUS.

END B43221A;
