-- B44001B.ADA

-- OBJECTIVE:
--     CHECK THE DETECTION OF SYNTAX ERRORS IN EXPRESSIONS.

--     THIS TEST CHECKS THAT A PROCEDURE CALL CANNOT BE A PRIMARY.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B44001A.ADA.

PROCEDURE  B44001B  IS

     A , B , C , D , E : BOOLEAN:= TRUE;
     I , J , K         : INTEGER := 0;

     PROCEDURE  PROC1( X : INTEGER := 17 )  IS
     BEGIN
          NULL;
     END PROC1;

     PROCEDURE  PROC2  IS
     BEGIN
          NULL;
     END PROC2;

BEGIN

     -- A <PROCEDURE_CALL> CANNOT BE A <PRIMARY>.

     I  :=  J ** PROC1(K);    -- ERROR: (E)
     NULL;
     I  :=  J ** PROC1   ;    -- ERROR: (E)
     NULL;
     I  :=  J ** PROC2   ;    -- ERROR: (E)
     NULL;

END  B44001B;
