-- B44004E.ADA

-- CHECK THAT "OBJECT IN REC_TYPE(DISCRIMINANT_CONSTRAINT)" IS ILLEGAL.

-- PWB  03/04/86

PROCEDURE B44004E IS

     TYPE REC (DISC : INTEGER) IS RECORD
          NULL;
     END RECORD;
     TYPE REC_PTR IS ACCESS REC;

     RVAR : REC(4);
     RP   : REC_PTR;

BEGIN

     IF RVAR IN REC(4) THEN              -- ERROR: DISCRIMINANT CONSTR.
          RP := NEW REC(1);
          IF RP.ALL NOT IN REC(1) THEN   -- ERROR: DISCRIMINANT CONSTR.
               NULL;
          END IF;
     ELSIF RVAR NOT IN REC(1) THEN       -- ERROR: DISCRIMINANT CONSTR.
          RP := NULL;
          IF RP.ALL IN REC(0) THEN       -- ERROR: DISCRIMINANT CONSTR.
               NULL;
          END IF;
     END IF;

END B44004E;
