-- B44004D.ADA

-- CHECK THAT "OBJECT IN TYPE_MARK (LO .. HI)" IS ILLEGAL.

-- PWB  03/04/86

PROCEDURE B44004D IS

     TYPE ARRAY_OVER_INT IS ARRAY (INTEGER RANGE <>) OF BOOLEAN;
     TYPE ARRAY_OVER_CHAR IS ARRAY (CHARACTER RANGE <>) OF INTEGER;
     CON_ARRAY_INT : ARRAY_OVER_INT(1..2) := (OTHERS => FALSE);
     CON_ARRAY_CH : ARRAY_OVER_CHAR('A'..'Z') := (OTHERS => 0);

     BOOL : BOOLEAN := (CON_ARRAY_INT IN 
                        ARRAY_OVER_INT(1..2));   -- ERROR: INDEX CONSTR.

BEGIN

     IF CON_ARRAY_INT NOT IN 
        ARRAY_OVER_INT(1..2) THEN                -- ERROR: INDEX CONSTR.
          BOOL := (CON_ARRAY_CH IN 
                   ARRAY_OVER_CHAR('A'..'Z'));   -- ERROR: INDEX CONSTR.
     ELSIF CON_ARRAY_CH NOT IN 
           ARRAY_OVER_CHAR('A'..'Z') THEN        -- ERROR: INDEX CONSTR.
          NULL;
     END IF;

END B44004D;
