-- B44002C.ADA


-- CHECK THAT NAMES OF EXCEPTIONS ARE NOT PERMITTED AS PRIMARIES.


-- RM   19 SEPTEMBER 1980


PROCEDURE  B44002C  IS

     EXC1 : EXCEPTION ;
     A    : INTEGER ;

BEGIN

     A := EXC1 ;   -- ERROR: NAMES OF EXCEPTIONS ARE NOT PERMITTED AS
                   --    PRIMARIES

END  B44002C ;
