-- B44004A.ADA

-- CHECK THAT "OBJECT IN TYPE_MARK RANGE LOW .. HIGH" IS ILLEGAL.

-- PWB  03/04/86

PROCEDURE B44004A IS

     TYPE ENUM IS (EA, EB, EC);
     SUBTYPE SMALL IS INTEGER RANGE 0 .. 10;
     TYPE FLOATING IS DIGITS 5;
     TYPE FIXED IS DELTA 0.1 RANGE 1.0..100.0;

     EVAR : ENUM := EA;
     IVAR : INTEGER := 0;
     CVAR : CHARACTER := 'A';
     BVAR : BOOLEAN := FALSE;
     FIVAR : FIXED := 1.0;
     FLVAR : FLOATING := 0.0;

BEGIN

     BVAR := ( EVAR IN ENUM RANGE EA .. EC );        -- ERROR: RANGE.

     IF IVAR IN SMALL RANGE 1..5 THEN                -- ERROR: RANGE.
          NULL;
     ELSIF IVAR NOT IN INTEGER RANGE 0..10 THEN      -- ERROR: RANGE.
          NULL;
     ELSIF CVAR IN CHARACTER RANGE 'A' .. 'Z' THEN   -- ERROR: RANGE.
          NULL;
     ELSIF BVAR NOT IN 
                BOOLEAN RANGE TRUE .. FALSE THEN     -- ERROR: RANGE.
          NULL;
     END IF;

     IF FIVAR IN FIXED RANGE 2.0 .. 3.0 THEN         -- ERROR: RANGE.
          NULL;
     ELSIF FIVAR NOT IN FIXED RANGE 2.0 .. 3.0 THEN  -- ERROR: RANGE.
          NULL;
     ELSIF FLVAR IN FLOATING RANGE 1.0 .. 2.0 THEN   -- ERROR: RANGE.
          NULL;
     ELSE 
          BVAR := (FLVAR NOT IN 
                   FLOATING RANGE 1.0 .. 2.0);       -- ERROR: RANGE.
     END IF;

END B44004A;
