-- B44004C.ADA

-- CHECK THAT "OBJECT IN TYPE_MARK DELTA D" IS ILLEGAL.

-- PWB  03/04/86

PROCEDURE B44004C IS

     TYPE FINE IS DELTA 0.01 RANGE -10.0 .. 10.0;
     SUBTYPE COARSE IS FINE DELTA 0.1;
     NUM  : FINE := 0.01;
     BOOL : BOOLEAN := (NUM IN COARSE DELTA 1.0);       -- ERROR: DELTA.

BEGIN

     IF NUM IN FINE DELTA 0.1 THEN                      -- ERROR: DELTA.
          NULL;
     ELSIF NUM NOT IN COARSE DELTA 0.2 THEN             -- ERROR: DELTA.
          NULL;
     ELSIF NUM NOT IN FINE DELTA 0.05 THEN              -- ERROR: DELTA.
          BOOL := NUM NOT IN FINE DELTA 0.05;           -- ERROR: DELTA.
     END IF;

END B44004C;
