-- B45209D.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS CHARACTER.

-- JWC 8/20/85

PROCEDURE B45209D IS

     TYPE CHAR1 IS ('A', 'B', 'C');
     C : CHARACTER := 'A';
     B : BOOLEAN;

BEGIN

     B := C IN CHARACTER;           -- OK.

     B := C IN CHAR1;               -- ERROR: DIFFERENT TYPES.

     B := C NOT IN CHARACTER;       -- OK.

     B := C NOT IN CHAR1;           -- ERROR: DIFFERENT TYPES.

END B45209D;
