-- B45208N.ADA 

-- CHECK THAT THE ORDERING OPERATORS ARE NOT PREDEFINED FOR LIMITED
--     TYPES, MULTIDIMENSIONAL ARRAY TYPES, RECORD TYPES, ACCESS
--     TYPES, AND FOR TYPES DERIVED FROM THESE.

 
-- PART 3: LIMITED TYPES INVOLVING TASKING BUT NOT INVOLVING
--     TYPE DERIVATION.
    
 
-- CASES COVERED (ALL TYPES COVERED HERE INVOLVE TASK TYPES WHOSE
--     TASK NATURE IS DISCLOSED UP FRONT, AS DISTINGUISHED FROM
--     LIMITED PRIVATE TYPES WHICH TURN OUT TO BE REALIZED AS
--     (OR IN TERMS OF) TASKS)
--                             ( ">>" MARKS CASES COVERED IN THIS FILE.)

--    * TASK TYPE
-->>  * ARRAY WHOSE COMPONENTS ARE OF A TASK TYPE
--          (ONE-DIMENSIONAL ARRAYS ONLY; SUCCESSFUL HANDLING
--          OF MULTIDIMENSIONAL ARRAYS IS IMPLIED BY THAT OF
--          MULTIDIMENSIONAL ARRAYS OF DISCRETE TYPES.)
--   ** ACCESS TO A TASK-TYPE OBJECT
--          (NOT DONE; SEE BELOW.)
--   ** RECORD WITH A COMPONENT WHICH IS OF A TASK TYPE
--          (NOT DONE; SEE BELOW.)
--   ** ARRAY OF LIMITED-TYPE RECORDS (AS ABOVE)
--          (NOT DONE; SEE BELOW.)
--   ** RECORDS OF LIMITED-TYPE ARRAYS  (AS ABOVE)
--          (NOT DONE;  SUCCESSFUL HANDLING OF THESE (AND OF MORE
--          HIGHLY COMPOSITE) LIMITED TYPES IS IMPLIED BY THE SUCCESSFUL
--          HANDLING OF
--             * ACCESS TO DISCRETE-TYPE OBJECTS;
--             * ONE-DIMENSIONAL ARRAYS;
--             * MULTIDIMENSIONAL ARRAYS OF DISCRETE-TYPE COMPONENTS;
--             * RECORDS CONTAINING DISCRETE-TYPE COMPONENTS. 
--          )

 
-- RM  2/25/82


PROCEDURE  B45208N  IS

BEGIN

     -------------------------------------------------------------------
     ---------  ARRAY WHOSE COMPONENTS ARE OF A TASK TYPE  -------------
     
     DECLARE

          B      : BOOLEAN := TRUE ;

          TASK TYPE  TT  IS
               ENTRY  E1 ;
          END  TT ;

          TYPE  ARR  IS ARRAY ( 1..3 ) OF  TT ;

          X , Y  :  ARR ;

          TASK BODY  TT  IS
          BEGIN
               ACCEPT  E1  DO
                    NULL;
               END  E1 ;
          END  TT ;


     BEGIN

          IF  X > Y                     -- ERROR: ORDERING NOT AVAILABLE
          THEN
               NULL ;
          END IF;

          B := ( X >= Y ) ;             -- ERROR: ORDERING NOT AVAILABLE

     END ;


     -------------------------------------------------------------------


END B45208N ;
