-- B45209J.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS ACCESS.

-- JWC 8/20/85

PROCEDURE B45209J IS

     TYPE ACC1 IS ACCESS INTEGER;
     TYPE ACC2 IS ACCESS INTEGER;
     A : ACC1;
     B : BOOLEAN;

BEGIN

    B := A IN ACC1;          -- OK.

    B := A IN ACC2;          -- ERROR: DIFFERENT TYPES.

    B := A NOT IN ACC1;      -- OK.

    B := A NOT IN ACC2;      -- ERROR: DIFFERENT TYPES.

END B45209J;
