-- B45209K.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS PRIVATE.

-- JWC 8/20/85

PROCEDURE B45209K IS

     PACKAGE PKG IS
          TYPE PRIV1 IS PRIVATE;
          TYPE PRIV2 IS PRIVATE;
          C1 : CONSTANT PRIV1;
     PRIVATE
          TYPE PRIV1 IS RANGE 1 .. 10;
          TYPE PRIV2 IS RANGE 1 .. 10;
          C1 : CONSTANT PRIV1 := 1;
     END PKG;

     P : PKG.PRIV1 := PKG.C1;
     B : BOOLEAN;

BEGIN

     B := P IN PKG.PRIV1;          -- OK.

     B := P IN PKG.PRIV2;          -- ERROR: DIFFERENT TYPES.

     B := P NOT IN PKG.PRIV1;      -- OK.

     B := P NOT IN PKG.PRIV2;      -- ERROR: DIFFERENT TYPES.

END B45209K;
