-- B45209H.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS ARRAY.

-- JWC 8/20/85

PROCEDURE B45209H IS

     TYPE ARR1 IS ARRAY (1 .. 10) OF INTEGER;
     TYPE ARR2 IS ARRAY (1 .. 10) OF INTEGER;
     A : ARR1 := (OTHERS => 0);
     B : BOOLEAN;

BEGIN

     B := A IN ARR1;          -- OK.

     B := A IN ARR2;          -- ERROR: DIFFERENT TYPES.

     B := A NOT IN ARR1;      -- OK.

     B := A NOT IN ARR2;      -- ERROR: DIFFERENT TYPES.

END B45209H;
