-- B45209I.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS RECORD.

-- JWC 8/20/85

PROCEDURE B45209I IS

     TYPE REC1 IS
          RECORD
               NULL;
          END RECORD;

     TYPE REC2 IS
          RECORD
               NULL;
          END RECORD;

     R : REC1;
     B : BOOLEAN;

BEGIN

    B := R IN REC1;          -- OK.

    B := R IN REC2;          -- ERROR: DIFFERENT TYPES.

    B := R NOT IN REC1;      -- OK.

    B := R NOT IN REC2;      -- ERROR: DIFFERENT TYPES.

END B45209I;
