-- B45203A.ADA


-- CHECK THAT VARIABLES OF TWO ENUMERATION TYPES HAVING
--    IDENTICAL SETS OF VALUES APPEARING IN THE SAME ORDER  CANNOT BE
--    COMPARED WITH AN EQUALITY OR ORDERING OPERATOR.


-- RM   22 OCTOBER 1980
-- JWC 7/8/85   RENAMED TO -AB


PROCEDURE  B45203A  IS

     TYPE  T  IS  ( A , B , C , D ) ;
     TYPE  U  IS  ( A , B , C , D ) ;

     X : T := T'(A) ;
     Y : U := U'(A) ;

BEGIN

     IF  X /= Y      -- ERROR: ARGUMENTS TO '/=' HAVE DIFFERENT TYPES
     THEN  NULL ;
     END IF;

     IF  X =  Y      -- ERROR: ARGUMENTS TO '= ' HAVE DIFFERENT TYPES
     THEN  NULL ;
     END IF;

     IF  X <  Y      -- ERROR: ARGUMENTS TO '< ' HAVE DIFFERENT TYPES
     THEN  NULL ;
     END IF;

     IF  X <= Y      -- ERROR: ARGUMENTS TO '<=' HAVE DIFFERENT TYPES
     THEN  NULL ;
     END IF;

     IF  X >  Y      -- ERROR: ARGUMENTS TO '> ' HAVE DIFFERENT TYPES
     THEN  NULL ;
     END IF;

     IF  X >= Y      -- ERROR: ARGUMENTS TO '>=' HAVE DIFFERENT TYPES
     THEN  NULL ;
     END IF;

END  B45203A ;
