-- B45209E.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS BOOLEAN.

-- JWC 8/20/85

PROCEDURE B45209E IS

     TYPE DER_BOOLEAN IS NEW BOOLEAN;
     B1, B2 : BOOLEAN := TRUE;

BEGIN

     B1 := B2 IN BOOLEAN;               -- OK.

     B1 := B2 IN DER_BOOLEAN;           -- ERROR: DIFFERENT TYPES.

     B1 := B2 NOT IN BOOLEAN;           -- OK.

     B1 := B2 NOT IN DER_BOOLEAN;       -- ERROR: DIFFERENT TYPES.

END B45209E;
