-- B45209F.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS FIXED.

-- JWC 8/20/85

PROCEDURE B45209F IS

     TYPE FIXED1 IS DELTA 1.0 RANGE 0.0 .. 10.0;
     TYPE FIXED2 IS DELTA 1.0 RANGE 0.0 .. 10.0;
     F : FIXED1 := 5.0;
     B : BOOLEAN;

BEGIN

     B := F IN FIXED1;         -- OK.

     B := F IN FIXED2;         -- ERROR: DIFFERENT TYPES.

     B := F NOT IN FIXED1;     -- OK.

     B := F NOT IN FIXED2;     -- ERROR: DIFFERENT TYPES.

END B45209F;
