-- B45209G.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS FLOAT.

-- JWC 8/20/85

PROCEDURE B45209G IS

     TYPE FLOAT1 IS DIGITS 4;
     TYPE FLOAT2 IS DIGITS 4;
     F : FLOAT1 := 1.0;
     B : BOOLEAN;

BEGIN

     B := F IN FLOAT1;          -- OK.

     B := F IN FLOAT2;          -- ERROR: DIFFERENT TYPES.

     B := F NOT IN FLOAT1;      -- OK.

     B := F NOT IN FLOAT2;      -- ERROR: DIFFERENT TYPES.

END B45209G;
