-- B45209C.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS ENUMERATION.

-- JWC 8/20/85

PROCEDURE B45209C IS

     TYPE ENUM1 IS (A, B, C);
     TYPE ENUM2 IS (A, B, C);
     E : ENUM1 := A;
     B1 : BOOLEAN;

BEGIN

     B1 := E IN ENUM1;          -- OK.

     B1 := E IN ENUM2;          -- ERROR: DIFFERENT TYPES.

     B1 := E NOT IN ENUM1;      -- OK.

     B1 := E NOT IN ENUM2;      -- ERROR: DIFFERENT TYPES.

END B45209C;
