-- B45209B.ADA

-- CHECK THAT MEMBERSHIP OPERATIONS ARE NOT DEFINED FOR OPERANDS OF
-- DIFFERENT TYPES.  THIS TEST CHECKS TYPE CLASS INTEGER.

-- JWC 8/20/85

PROCEDURE B45209B IS

     TYPE INT1 IS RANGE 1 .. 10;
     I : INT1 := 2;
     B : BOOLEAN;

BEGIN

     B := I IN INT1;          -- OK.

     B := I IN INTEGER;       -- ERROR: DIFFERENT TYPES.

     B := I NOT IN INT1;      -- OK.

     B := I NOT IN INTEGER;   -- ERROR: DIFFERENT TYPES.

END B45209B;
