-- B45533A.ADA

-- CHECK THAT 'MOD' AND 'REM' ARE NOT PREDEFINED FOR OPERANDS HAVING 
-- FIXED POINT TYPES.

-- RJW 2/10/86

PROCEDURE B45533A IS

     TYPE T IS DELTA 1.0 RANGE -1.0 .. 1.0;

     F1, F2 : T := 1.0;
BEGIN
     F1 := F1 MOD F2;          -- ERROR: INVALID TYPES FOR 'MOD'.
     F1 := F1 REM F2;          -- ERROR: INVALID TYPES FOR 'REM'.
END B45533A;
