-- B45522A.ADA

-- CHECK THAT
-- (A) DIFFERENT FLOATING POINT TYPES CANNOT BE MULTIPLIED
--     TOGETHER.
-- (B) MOD AND REM CANNOT BE USED WITH FLOATING POINT OPERANDS.

-- BAW 17 SEPT 80

PROCEDURE B45522A IS

     TYPE F IS DIGITS 5;
     TYPE G IS DIGITS 5;
     F1: F := 1.0;
     G1: G := 1.0;
BEGIN
     F1 := F1 * G1;      -- ERROR: WRONG TYPES (A)
     F1 := F1 / G1;      -- ERROR: WRONG TYPES (A)
     G1 := G1 MOD 1.0;   -- ERROR: WRONG TYPES (B)
     G1 := G1 REM 1.0;   -- ERROR: WRONG TYPES (B)
END B45522A;
