-- B45615A.ADA

-- CHECK THAT THE EXPONENT FOR INTEGER EXPONENTIATION CANNOT HAVE A TYPE
-- DERIVED FROM INTEGER OR ANY OTHER USER-DEFINED TYPE.

-- JBG 6/1/85

WITH SYSTEM;
PROCEDURE B45615A IS

     TYPE DER_INT IS NEW INTEGER;
     TYPE NEW_INT IS RANGE INTEGER'FIRST .. INTEGER'LAST;
     TYPE SHT_INT IS RANGE 1..10;
     TYPE LNG_INT IS RANGE -SYSTEM.MAX_INT .. SYSTEM.MAX_INT;

     V_INTEGER : INTEGER := 1;
     V_DER_INT : DER_INT := 1;
     V_NEW_INT : NEW_INT := 1;
     V_SHT_INT : SHT_INT := 1;
     V_LNG_INT : LNG_INT := 1;

BEGIN

     V_INTEGER := V_INTEGER ** V_INTEGER;    -- OK.
     V_DER_INT := V_DER_INT ** V_DER_INT;    -- ERROR: EXP NOT INTEGER.
     V_NEW_INT := V_NEW_INT ** V_NEW_INT;    -- ERROR: EXP NOT INTEGER.
     V_SHT_INT := V_SHT_INT ** V_SHT_INT;    -- ERROR: EXP NOT INTEGER.
     V_LNG_INT := V_LNG_INT ** V_LNG_INT;    -- ERROR: EXP NOT INTEGER.

END B45615A;
