-- B45625A.ADA

-- CHECK THAT THE EXPONENT FOR INTEGER EXPONENTIATION CANNOT HAVE A TYPE
-- DERIVED FROM INTEGER OR ANY OTHER USER-DEFINED TYPE.

-- CHECK WHEN THE BASE HAS A FLOATING POINT TYPE.

-- JBG 6/1/85

WITH SYSTEM;
PROCEDURE B45625A IS

     TYPE DER_INT IS NEW INTEGER;
     TYPE NEW_INT IS RANGE INTEGER'FIRST .. INTEGER'LAST;
     TYPE SHT_INT IS RANGE 1..10;
     TYPE LNG_INT IS RANGE -SYSTEM.MAX_INT .. SYSTEM.MAX_INT;

     VAR_FLOAT : FLOAT := 1.0;
     V_INTEGER : INTEGER := 1;
     V_DER_INT : DER_INT := 1;
     V_NEW_INT : NEW_INT := 1;
     V_SHT_INT : SHT_INT := 1;
     V_LNG_INT : LNG_INT := 1;

BEGIN

     VAR_FLOAT := VAR_FLOAT ** V_INTEGER;    -- OK.
     VAR_FLOAT := VAR_FLOAT ** V_DER_INT;    -- ERROR: EXP NOT INTEGER.
     VAR_FLOAT := VAR_FLOAT ** V_NEW_INT;    -- ERROR: EXP NOT INTEGER.
     VAR_FLOAT := VAR_FLOAT ** V_SHT_INT;    -- ERROR: EXP NOT INTEGER.
     VAR_FLOAT := VAR_FLOAT ** V_LNG_INT;    -- ERROR: EXP NOT INTEGER.

END B45625A;
