-- B46005A.ADA

-- OBJECTIVE:
--     CHECK THAT IF THE TARGET TYPE OF A CONVERSION IS AN ENUMERATION
--     TYPE, A RECORD TYPE, AN ACCESS TYPE, OR A PRIVATE TYPE, THE
--     OPERAND TYPE CANNOT BE A DIFFERENT ENUMERATION TYPE, RECORD
--     TYPE, ACCESS TYPE, OR PRIVATE TYPE UNRELATED BY DERIVATION.

-- HISTORY:
--     JET 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B46005A IS
     TYPE ENUM1 IS (WE, LOVE, WRITING, TESTS);
     TYPE ENUM2 IS (JOHN, LYNN, BRIAN, VINCE);
     TYPE ENUMD IS NEW ENUM1 RANGE LOVE..TESTS;

     TYPE REC1 IS RECORD
          F : INTEGER;
     END RECORD;

     TYPE REC2 IS RECORD
          F : INTEGER;
     END RECORD;

     TYPE RECD IS NEW REC1;

     TYPE ACC1 IS ACCESS INTEGER;
     TYPE ACC2 IS ACCESS INTEGER;
     TYPE ACCD IS NEW ACC1;

     PACKAGE P IS
          TYPE PRIV1 IS PRIVATE;
          TYPE PRIV2 IS PRIVATE;
          ZERO : CONSTANT PRIV1;
          ONE : CONSTANT PRIV2;
     PRIVATE
          TYPE PRIV1 IS RANGE -100 .. 100;
          TYPE PRIV2 IS RANGE -100 .. 100;
          ZERO : CONSTANT PRIV1 := 0;
          ONE : CONSTANT PRIV2 := 1;
     END P;

     TYPE PRIVD IS NEW P.PRIV1;

     E1 : ENUM1 := WE;
     R1 : REC1 := (F => 0);
     A1 : ACC1 := NEW INTEGER'(0);
     P1 : P.PRIV1 := P.ZERO;
     E2 : ENUM2 := JOHN;
     R2 : REC2 := (F => 1);
     A2 : ACC2 := NEW INTEGER'(1);
     P2 : P.PRIV2 := P.ONE;
     ED : ENUMD := LOVE;
     RD : RECD := (F => 2);
     AD : ACCD := NEW INTEGER'(2);
     PD : PRIVD;

BEGIN
     E1 := ENUM1(ED);                    -- OK.
     E1 := ENUM1(E2);                    -- ERROR: ILLEGAL CONVERSION.
     R1 := REC1(RD);                     -- OK.
     R1 := REC1(R2);                     -- ERROR: ILLEGAL CONVERSION.
     AD := ACCD(A1);                     -- OK.
     AD := ACCD(A2);                     -- ERROR: ILLEGAL CONVERSION.
     PD := PRIVD(P1);                    -- OK.
     PD := PRIVD(P2);                    -- ERROR: ILLEGAL CONVERSION.
END B46005A;
