-- B46004B.ADA

-- WHEN THE TARGET TYPE OF A TYPE CONVERSION IS AN ARRAY TYPE, CHECK 
-- THAT THE OPERAND TYPE CANNOT HAVE FEWER OR MORE DIMENSIONS THAN
-- THE TARGET TYPE.

-- R.WILLIAMS 9/19/86

PROCEDURE B46004B IS

     TYPE ARR1 IS ARRAY (1 .. 2) OF INTEGER;
     A1 : ARR1 := (1 => 1, 2 => 2);

     TYPE NARR1 IS ARRAY (2 .. 1) OF INTEGER;
     NA1 : NARR1;

     TYPE ARR2 IS ARRAY (1 .. 1,  1 .. 2) OF INTEGER;
     A2 : ARR2 := (1 => (1 => 1, 2 => 2));

     TYPE NARR2 IS ARRAY (1 .. 1, 2 .. 1) OF INTEGER;
     NA2 : NARR2;

BEGIN
     A1 := ARR1 (A2);              -- ERROR: DIMENSIONALITY OF OPERAND.
     
     A2 := ARR2 (A1);              -- ERROR: DIMENSIONALITY OF OPERAND.

     A1 := ARR1 (NA2);             -- ERROR: DIMENSIONALITY OF OPERAND.

     A2 := ARR2 (NA1);             -- ERROR: DIMENSIONALITY OF OPERAND.

     NA2 := NARR2 (NA1);           -- ERROR: DIMENSIONALITY OF OPERAND.

     NA1 := NARR1 (NA2);           -- ERROR: DIMENSIONALITY OF OPERAND.
END B46004B;
