-- B46003A.ADA

-- OBJECTIVE:
--     CHECK THAT IF THE TARGET TYPE OF A CONVERSION IS A NUMERIC TYPE,
--     THE OPERAND TYPE CANNOT BE AN ENUMERATION TYPE, AN ARRAY TYPE OR
--     RECORD TYPE WITH NUMERIC COMPONENTS, AN ACCESS TYPE, OR A
--     PRIVATE TYPE WHOSE FULL DECLARATION DECLARES A NUMERIC TYPE.

-- HISTORY:
--     JET 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE B46003A IS
     TYPE NUM1 IS NEW INTEGER RANGE -100 .. 100;
     TYPE NUM2 IS DELTA 2#0.01# RANGE -16#80.0# .. 16#80.0#;
     SUBTYPE NUM3 IS FLOAT RANGE -100.0 .. 100.0;

     TYPE ENUM IS (WE, LOVE, WRITING, TESTS);

     TYPE ARR IS ARRAY (1..10) OF NUM1;

     TYPE REC IS RECORD
          F : NUM2;
     END RECORD;

     TYPE ACC IS ACCESS NUM3;

     PACKAGE P IS
          TYPE PRIV IS PRIVATE;
          ZERO : CONSTANT PRIV;
     PRIVATE
          TYPE PRIV IS NEW FLOAT;
          ZERO : CONSTANT PRIV := 0.0;
     END P;

     N1 : NUM1;
     N2 : NUM2;
     N3 : NUM3;
     N4 : INTEGER;
     N5 : FLOAT;

     EN : ENUM := WE;
     AR : ARR := (OTHERS => 0);
     RC : REC := (F => 0.0);
     AX : ACC := NEW NUM3'(0.0);
     PV : P.PRIV := P.ZERO;

BEGIN
     N1 := NUM1(AR);                      -- ERROR: ILLEGAL CONVERSION.
     N2 := NUM2(RC);                      -- ERROR: ILLEGAL CONVERSION.
     N3 := NUM3(AX);                      -- ERROR: ILLEGAL CONVERSION.
     N4 := INTEGER(LOVE);                 -- ERROR: ILLEGAL CONVERSION.
     N4 := INTEGER(EN);                   -- ERROR: ILLEGAL CONVERSION.
     N5 := FLOAT(P.ZERO);                 -- ERROR: ILLEGAL CONVERSION.
     N5 := FLOAT(PV);                     -- ERROR: ILLEGAL CONVERSION.
END B46003A;
