-- B48002F.ADA

-- CHECK THAT ILLEGAL FORMS OF ALLOCATORS ARE FORBIDDEN. IN PARTICULAR,
-- FOR ALLOCATORS OF THE FORM "NEW T X", WHERE X IS AN INDEX CONSTRAINT,
-- CHECK THAT T CANNOT BE A CONSTRAINED ACCESS SUBTYPE WHOSE DESIGNATED
-- TYPE IS AN ARRAY TYPE.

-- EG  07/27/84

PROCEDURE B48002F IS

     TYPE UA IS ARRAY(INTEGER RANGE <>) OF INTEGER;

     TYPE A_UA IS ACCESS UA;
     TYPE AA_UA IS ACCESS A_UA;

     SUBTYPE CA_UA IS A_UA(1 .. 5);

     V_AA_UA : AA_UA;

BEGIN

     V_AA_UA := NEW A_UA(1 .. 5);  -- OK.
     V_AA_UA := NEW CA_UA(1 .. 3); -- ERROR:

END B48002F;
