-- B48003D.ADA

-- CHECK THAT ILLEGAL FORMS OF ALLOCATORS ARE FORBIDDEN. IN PARTICULAR,
-- FOR ALLOCATORS OF THE FORM "NEW T'(X)", CHECK THAT IF T IS AN
-- UNCONSTRAINED ARRAY TYPE, (X) CANNOT BE AN AGGREGATE WITH AN OTHERS
-- CHOICE.

-- EG  08/03/84

PROCEDURE B48003D IS

     TYPE UA IS ARRAY(INTEGER RANGE <>) OF INTEGER;

     TYPE A_UA IS ACCESS UA;

     UA1 : A_UA := NEW UA'(1, 2, OTHERS => 3);    -- ERROR:
     UA2 : CONSTANT A_UA := NEW UA'(OTHERS => 1); -- ERROR:
     UA3 : A_UA;

BEGIN

     UA3 := NEW UA'(1, OTHERS => 2);              -- ERROR:

END B48003D;
