-- B48002C.ADA

-- CHECK THAT ILLEGAL FORMS OF ALLOCATORS ARE FORBIDDEN. IN PARTICULAR,
-- FOR ALLOCATORS OF THE FORM "NEW T X", WHERE X IS A DISCRIMINANT
-- CONSTRAINT OR A VALUE OF TYPE T ENCLOSED IN PARENTHESES, CHECK THAT
-- T CANNOT BE A CONSTRAINED ACCESS SUBTYPE WHOSE DESIGNATED TYPE HAS
-- DISCRIMINANTS.

-- EG  07/26/84

PROCEDURE B48002C IS

     TYPE GENDER IS (M, F, UNKNOWN);
     SUBTYPE GENDER_TYPE IS GENDER RANGE M .. F;
     TYPE PERSON(GNDR : GENDER_TYPE := F) IS
          RECORD
               AGE : INTEGER RANGE 0 .. 100 := 0;
          END RECORD;
     TYPE PEOPLE IS ACCESS PERSON;
     SUBTYPE PEOPLE_M IS PEOPLE(M);

     TYPE A_MP IS ACCESS PEOPLE_M;

     V_A_MP : A_MP;

BEGIN

     V_A_MP := NEW PEOPLE_M(M);    -- ERROR: ALREADY CONSTRAINED.

END B48002C;
