-- B49002A.ADA

-- CHECK THAT NO EXPRESSION HAVING A SCALAR GENERIC FORMAL TYPE (OR TYPE
-- DERIVED INDIRECTLY FROM A GENERIC FORMAL TYPE) IS CONSIDERED STATIC.

-- L.BROWN  08/20/86

PROCEDURE B49002A IS

     GENERIC
          TYPE T IS RANGE <> ;
     PACKAGE PACK IS
          TYPE ARR IS ARRAY(T RANGE 0 .. 1) OF BOOLEAN;
          X : ARR := (0 => FALSE, T'(1) => TRUE);              -- ERROR:
     END PACK;

     GENERIC
          TYPE T IS RANGE <> ;
     FUNCTION FUN RETURN INTEGER ;
     FUNCTION FUN RETURN INTEGER IS
          TYPE S IS NEW T ;
          TYPE ARR IS ARRAY(S RANGE 0 .. 1) OF INTEGER;
          X : ARR := (S'(0) => 4, 1 => 5);                     -- ERROR:
          XR : INTEGER RANGE 1 .. 10 := 5;
     BEGIN
          RETURN XR;
     END FUN;

     GENERIC
          TYPE T IS RANGE <> ;
     PROCEDURE PROC ;
     PROCEDURE PROC IS
          TYPE SNEW IS NEW T ;
          TYPE SNEW2 IS NEW SNEW ;
          TYPE ARR IS ARRAY(SNEW2 RANGE 0 .. 1) OF INTEGER;
          X : ARR := (0 => 2, SNEW2'(1) => 3);                 -- ERROR:
     BEGIN
          NULL;
     END PROC;

     PACKAGE PACK1 IS NEW PACK(INTEGER);
     FUNCTION FUN2 IS NEW FUN(INTEGER);
     PROCEDURE PROC2 IS NEW PROC(INTEGER);

BEGIN
     NULL;
END B49002A;
