-- B49006B.ADA

-- CHECK THAT EXPLICIT CONVERSIONS ARE NOT ALLOWED IN REPRESENTATION
-- CLAUSES.

-- JBG 11/3/85

PROCEDURE B49006B IS

     TYPE INT1 IS RANGE 0 ..1;
     FOR INT1'SIZE USE INTEGER(INTEGER'SIZE);     -- ERROR: NOT STATIC.

     TYPE FIX1 IS DELTA 1.0 RANGE -3.0 .. 3.0;
     FOR FIX1'SMALL USE FLOAT(1.0);               -- ERROR: NOT STATIC.

     TYPE ENUM IS (A, B);
     FOR ENUM USE (A => INTEGER(0), B => INTEGER(1));  -- ERROR: NOT
                                                       --        STATIC.

BEGIN
     NULL;
END B49006B;
