-- B49006A.ADA

-- OBJECTIVE:
--     CHECK THAT EXPLICIT CONVERSIONS ARE NOT ALLOWED IN STATIC
--     EXPRESSIONS.

-- HISTORY:
--     JBG 11/03/85 CREATED ORIGINAL TEST.
--     PWB 02/20/86 MADE SYNTAX CORRECTIONS:
--               (SUBSTITUTE ';' FOR ':' TWICE, ADD 'END CASE').
--               ENSURED THAT EXPRESSIONS HAVE <UNIVERSAL_INTEGER>
--               VALUES WHEN REQUIRED BY CONTEXT.
--     DHH 10/19/87 SHORTENED LINES CONTAINING MORE THAN 72 CHARACTERS.

PROCEDURE B49006A IS

     CONS_INT : CONSTANT := 2**INTEGER(1.5);      -- ERROR: NOT STATIC.

     TYPE INT_TYPE IS RANGE INTEGER(1.5) .. 3;    -- ERROR: NOT STATIC.
     TYPE INT_TYPE2 IS RANGE -3 .. INTEGER(3);    -- ERROR: NOT STATIC.

     TYPE FLT1 IS DIGITS INTEGER(1);              -- ERROR: NOT STATIC.
     SUBTYPE FLT2 IS FLOAT DIGITS INTEGER(1);     -- ERROR: NOT STATIC.

     TYPE FLT3 IS DIGITS 1 RANGE FLOAT(1.5)..3.0; -- ERROR: NOT STATIC.
     TYPE FLT4 IS DIGITS 1 RANGE -3.0..FLOAT(1.5);-- ERROR: NOT STATIC.

     TYPE FIX1 IS DELTA FLOAT(1.0) RANGE 1.0..3.0;-- ERROR: NOT STATIC.
     TYPE FIX2 IS DELTA 1.0 RANGE -3.0 .. 3.0;
     SUBTYPE FIX3 IS FIX2 DELTA FLOAT(1.0);       -- ERROR: NOT STATIC.

     TYPE FIX4 IS DELTA 1.0 RANGE FLOAT(1.5)..3.0;-- ERROR: NOT STATIC.
     TYPE FIX5 IS DELTA 1.0 RANGE 1.5..FLOAT(3.0);-- ERROR: NOT STATIC.

     SUBTYPE STR IS STRING (1..5);
     C1 : INTEGER :=
          STR'FIRST(INTEGER'POS(INTEGER(1)));     -- ERROR: NOT STATIC.
     C2 : INTEGER :=
          STR'LAST(INTEGER'POS(INTEGER(1)));      -- ERROR: NOT STATIC.
     C3 : STRING
          (STR'RANGE(INTEGER'POS(INTEGER(1))));   -- ERROR: NOT STATIC.
     C4 : INTEGER :=
          STR'LENGTH(INTEGER'POS(INTEGER(1)));    -- ERROR: NOT STATIC.

     TYPE VARIANT1 (D : POSITIVE) IS
          RECORD
               CASE D IS
                    WHEN INTEGER(1) =>            -- ERROR: NOT STATIC.
                         C1 : INTEGER;
                    WHEN OTHERS =>
                         C2 : INTEGER;
               END CASE;
          END RECORD;

     TYPE VARIANT2 (D : POSITIVE) IS
          RECORD
               CASE D IS
                    WHEN 1 =>
                         C1 : INTEGER;
                    WHEN OTHERS =>
                         C2 : INTEGER;
               END CASE;
          END RECORD;

     X_VAR2 : VARIANT2(1) := (INTEGER(1), 3);     -- ERROR: NOT STATIC.

     OK : INTEGER := 1;

BEGIN

     CASE OK IS
          WHEN INTEGER(1) =>                      -- ERROR: NOT STATIC.
               NULL;
          WHEN OTHERS =>
               NULL;
     END CASE;

END B49006A;
