-- B4A010C.ADA

-- CHECK THAT STATIC UNIVERSAL REAL EXPRESSIONS ARE EVALUATED EXACTLY BY
-- CONSTRUCTING CASES WHERE EXACT EVALUATION IS NEEDED TO DETERMINE THE
-- LEGALITY OF A CONSTRUCT.

-- JBG 5/3/85
-- PWB 2/3/86  CORRECTED TEST ERROR
--             BY MOVING DECLARATION OF B BEFORE PROCEDURE BODY.

PROCEDURE B4A010C IS

     B : BOOLEAN := FALSE;

     PROCEDURE P (X : FLOAT := 3#0.1#);      -- 1/3

     PROCEDURE P (X : FLOAT :=
                    0.333333333333333333333333333333) IS    -- ERROR:
                                     -- LITERALS DO NOT HAVE SAME VALUE.
     BEGIN NULL; END P;

BEGIN
     CASE B IS
          WHEN (0.1 * 0.1 = 0.01) => NULL;
          WHEN TRUE => NULL;
     END CASE;                -- ERROR: TWO CHOICES HAVE SAME VALUE.
END B4A010C;
