-- B51003C.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE OF STATEMENTS MUST BE CODED
--     AS AN EXPLICIT NULL STATEMENT.  THIS TEST CHECKS AN EMPTY
--     PACKAGE BODY.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003A.

PROCEDURE B51003C IS

     PACKAGE P IS
          B : BOOLEAN;
     END P;

     PACKAGE BODY P IS
          B2 : BOOLEAN;
     BEGIN
     END P;   -- ERROR: EXPLICIT NULL MISSING IN PACKAGE BODY.

BEGIN
     NULL;
END B51003C;
