-- B51003G.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE OF STATEMENTS MUST BE CODED
--     AS AN EXPLICIT NULL STATEMENT.  THIS TEST CHECKS AN EMPTY
--     LOOP BODY.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003A.

PROCEDURE B51003G IS
     I : INTEGER := 1;
BEGIN

     WHILE I < 5 LOOP
     END LOOP;             -- ERROR: EXPLICIT NULL MISSING IN LOOP BODY.

END B51003G;
