-- B51003B.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE_OF_STATEMENTS IS NOT ALLOWED IN
--     A TASK BODY.

-- HISTORY:
--     TBN 02/05/86  CREATED ORIGINAL TEST.
--     JET 08/16/88  SPLIT SYNTAX ERRORS INTO INDIVIDUAL TESTS.
--                   THIS TEST WAS SPLIT INTO B51003B AND B51003H..J.

PROCEDURE B51003B IS

     TASK FRED;

     TASK BODY FRED IS

     BEGIN
     END FRED;                    -- ERROR: MISSING STATEMENT

BEGIN
     NULL;
END B51003B;
