-- B51003I.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE_OF_STATEMENTS IS NOT ALLOWED IN
--     A SELECT STATEMENT.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003B.

PROCEDURE B51003I IS

     TASK T1 IS
          ENTRY E2;
     END T1;

     TASK BODY T1 IS

     BEGIN
          SELECT
               ACCEPT E2;
          ELSE
          END SELECT;             -- ERROR: MISSING STATEMENT
     END T1;

BEGIN
     NULL;
END B51003I;
