-- B51003E.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE OF STATEMENTS MUST BE CODED
--     AS AN EXPLICIT NULL STATEMENT.  THIS TEST CHECKS AN EMPTY
--     CASE BODY.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003A.

PROCEDURE B51003E IS
     I : INTEGER := 2;
BEGIN
     CASE I IS
          WHEN 1..3 =>            -- ERROR: EXPLICIT NULL MISSING IN
                                  --    CASE BODY.
          WHEN OTHERS => NULL;
     END CASE;
END B51003E;
