-- B51003F.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE OF STATEMENTS MUST BE CODED
--     AS AN EXPLICIT NULL STATEMENT.  THIS TEST CHECKS AN EMPTY
--     BLOCK STATEMENT.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003A.

PROCEDURE B51003F IS
BEGIN
     DECLARE
          I : INTEGER;
     BEGIN
     END;                -- ERROR: EXPLICIT NULL MISSING IN EMPTY BLOCK.
END B51003F;
