-- B51003A.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE OF STATEMENTS MUST BE CODED
--     AS AN EXPLICIT NULL STATEMENT.  THIS TEST CHECKS AN EMPTY
--     SUBPROGRAM BODY.

-- HISTORY:
--     DCB 02/27/80  CREATED ORIGINAL TEST.
--     SPS 03/15/83
--     JET 08/16/88  SPLIT SYNTAX ERRORS INTO INDIVIDUAL TESTS.
--                   THIS TEST WAS SPLIT INTO B51003A AND B51003C..G.

PROCEDURE B51003A IS

     PROCEDURE NONULL IS
          C1, C2 : INTEGER;
     BEGIN
     END NONULL;   -- ERROR: EXPLICIT NULL MISSING IN SUBPROGRAM WITH
                   --   EMPTY BODY.

BEGIN
     NULL;
END B51003A;
