-- B51003D.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE OF STATEMENTS MUST BE CODED
--     AS AN EXPLICIT NULL STATEMENT.  THIS TEST CHECKS AN EMPTY
--     IF STATEMENT.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003A.

PROCEDURE B51003D IS
BEGIN
     IF TRUE THEN
     END IF;    -- ERROR: EXPLICIT NULL MISSING IN EMPTY SEQUENCE IN
                --    IF BODY.
END B51003D;
