-- B51003H.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE_OF_STATEMENTS IS NOT ALLOWED IN AN
--     ACCEPT STATEMENT.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003B.

PROCEDURE B51003H IS

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS

     BEGIN
          DECLARE
          BEGIN
               ACCEPT E1 DO
               END E1;            -- ERROR: MISSING STATEMENT
          END;
     END T1;

BEGIN
     NULL;
END B51003H;
