-- B51003J.ADA

-- OBJECTIVE:
--     CHECK THAT AN EMPTY SEQUENCE_OF_STATEMENTS IS NOT ALLOWED IN
--     AN EXCEPTION HANDLER.

-- HISTORY:
--     JET 08/16/88  CREATED ORIGINAL TEST FROM SPLIT OF B51003B.

PROCEDURE B51003J IS

BEGIN
     NULL;
EXCEPTION
     WHEN OTHERS =>               -- ERROR: MISSING STATEMENT
END B51003J;
