-- B52002G.ADA

-- CHECK THAT THE LEFT SIDE OF AN ASSIGNMENT STMT MUST BE A VARIABLE.

-- LHS CANNOT BE AN ATTRIBUTE.

-- JRK 10/30/80
-- RM  06/09/82  (REVISION FOR ADA-82)
-- RM  07/13/82  (SEPARATE "SYNTAX" FROM "SEMANTICS" (NON-CF SYNTAX))
-- SPS 03/21/83

PROCEDURE B52002G IS

     TYPE DRT (I : INTEGER := 0) IS
          RECORD
               B : BOOLEAN;
          END RECORD;

     DR : DRT;

BEGIN

     DR'SIZE := 1;      -- ERROR: ATTRIBUTE ON LEFT.

END B52002G ;
