-- B52002A.ADA

-- CHECK THAT THE LEFT SIDE OF AN ASSIGNMENT STMT MUST BE A VARIABLE.

-- "SEMANTICS" VIOLATIONS (CONTEXT-SENSITIVE RESTRICTIONS).

-- CHECK THAT THE LHS MAY NOT BE A FORM OF A CONSTANT.

-- DCB 1/31/80
-- JRK 10/30/80
-- RM  06/09/82  (REVISION FOR ADA-82)
-- RM  07/13/82  (SEPARATE "SYNTAX" FROM "SEMANTICS" (NON-CF SYNTAX))
-- SPS 03/21/83

PROCEDURE B52002A IS

     C1 : CONSTANT := 3;
     C2 : CONSTANT INTEGER := 4;
     CA : CONSTANT ARRAY (1..3) OF INTEGER := (1,2,3);

     TYPE DRT (I : INTEGER := 0) IS
          RECORD
               B : BOOLEAN;
          END RECORD;
     DR : DRT;

     EX : INTEGER ;

     TYPE T IS ACCESS INTEGER;

     FUNCTION F (I : INTEGER) RETURN T IS
     BEGIN
          I := 3;       -- ERROR: IN PARAMETER ON LEFT.
          RETURN NEW INTEGER'(5);
     END F;

BEGIN

     C1 := 6;           -- ERROR: CONSTANT ON LEFT.
     C2 := 7;           -- ERROR: CONSTANT ON LEFT.
     CA(2) := 9;        -- ERROR: CONSTANT COMPONENT ON LEFT.

     FOR I IN 1..10 LOOP
          I := I + 1;   -- ERROR: LOOP PARAMETER ON LEFT.
     END LOOP;

     DR.I := 4;         -- ERROR: DISCRIMINANT COMPONENT ON LEFT.

END B52002A;
