-- B52006A.ADA


-- CHECK THAT THE EQUALITY OPERATOR CANNOT BE USED AS AN ASSIGNMENT
--    SYMBOL.


-- RM 02/17/80
-- SPS 3/21/83
-- RJK 9/13/83


PROCEDURE  B52006A  IS

     I , J  :  INTEGER ;
     C      :  CONSTANT INTEGER := 12 ;

BEGIN

     I = J ;                       -- ERROR: '=' USED INSTEAD OF ':='

END B52006A ;
