-- B52004B.ADA

-- CHECK THAT TYPES OF TARGET VARIABLE AND EXPRESSION MUST MATCH
--    AT COMPILE TIME FOR FLOAT AND OTHER TYPES.

-- DCB 3/2/80
-- SPS 03/21/83

PROCEDURE B52004B IS

     TYPE FLT IS DIGITS 3 RANGE -3.0E4 .. 3.0E4;

     FL1 : FLT := 1.1;
     FL2 : FLOAT := 1.2;
     VL1 : ARRAY (1..10) OF FLT :=
               (1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0);

     I1 : INTEGER := 5;
     C1 : CHARACTER := 'A';
     V1 : ARRAY (1..10) OF INTEGER := (1,2,3,4,5,6,7,8,9,10);

BEGIN

     I1 := FL1;     -- ERROR: TYPES DON'T MATCH.
     FL1 := I1;     -- ERROR: TYPES DON'T MATCH.

     C1 := FL1;     -- ERROR: TYPES DON'T MATCH.
     FL1 := C1;     -- ERROR: TYPES DON'T MATCH.

     V1 := FL1;     -- ERROR: TYPES DON'T MATCH.
     FL1 := V1;     -- ERROR: TYPES DON'T MATCH.

     FL1 := FL2;    -- ERROR: TYPES DON'T MATCH.

     FL2 := I1;     -- ERROR: TYPES DON'T MATCH.

     VL1 := FL1;    -- ERROR: TYPES DON'T MATCH.
     FL1 := VL1;    -- ERROR: TYPES DON'T MATCH.

     VL1 := V1;     -- ERROR: TYPES DON'T MATCH.

END B52004B;
