-- B52002B.ADA

-- CHECK THAT THE LEFT SIDE OF AN ASSIGNMENT STMT MUST BE A VARIABLE.

-- CHECK THAT THE LHS MAY NOT BE AN ENUMERATION LITERIAL, BLOCK
--  IDENTIFIER, LOOP IDENTIFIER, STATEMENT LABEL, PACKAGE NAME,
--  TYPE NAME, SUBTYPE, OR PRAGMA IDENTIFIER.

-- JRK 10/30/80
-- SPS 03/21/83

PROCEDURE B52002B IS

     TYPE E IS (E1, E2);
     SUBTYPE ES IS E RANGE E1..E1;

     PACKAGE P IS
          I : INTEGER;
     END P;

BEGIN

     E1 := E2;            -- ERROR: ENUMERATION LITERAL ON LEFT.

     B52002B := B52002B;  -- ERROR: SUBPROGRAM IDENTIFIER ON LEFT.

  B: BEGIN
          B := B;         -- ERROR: BLOCK IDENTIFIER ON LEFT.
     END B;

  F: FOR I IN 1..10 LOOP
          F := F;         -- ERROR: LOOP IDENTIFIER ON LEFT.
     END LOOP F;

<<L>>
     L := L;              -- ERROR: STATEMENT LABEL ON LEFT.

     P := P;              -- ERROR: PACKAGE IDENTIFIER ON LEFT.

     LIST := LIST;        -- ERROR: PRAGMA IDENTIFER ON LEFT.

     E := E;              -- ERROR: TYPE IDENTIFIER ON LEFT.

     ES := ES;            -- ERROR: SUBTYPE IDENTIFIER ON LEFT.

END B52002B;
