-- B53001B.ADA

-- CHECK THAT THE ELSE OF AN ENCLOSING IF STATEMENT CANNOT BE USED TO
-- TERMINATE A NESTED IF STATEMENT.

-- DCB 3/6/80
-- JRK 7/7/80
-- ABW 6/11/82
-- SPS 3/3/83

PROCEDURE B53001B IS

     B1, B2 : BOOLEAN;
     I1, I2 : INTEGER;

BEGIN
     B1 := TRUE;
     B2 := FALSE;

     IF B1 THEN
          IF B2 THEN
               B1 := FALSE;
          ELSE B2 := TRUE;
     ELSE I2 := 0;             -- ERROR: "END IF;" MISSING.
     END IF;

END B53001B;
