-- B54A09A.ADA

-- OBJECTIVE:
--     CHECK THAT A CHOICE IN A CASE STATEMENT MAY NOT BE A COMPONENT
--     SIMPLE NAME.

-- HISTORY:
--     BCB 03/01/88  CREATED ORIGINAL TEST.

PROCEDURE B54A09A IS

     TYPE REC(D : INTEGER) IS RECORD
          I : INTEGER;
     END RECORD;

     A : REC(D => 5);

BEGIN
     CASE A.D IS
          WHEN I => NULL;             -- ERROR: COMPONENT SIMPLE NAME.
          WHEN OTHERS => NULL;
     END CASE;

END B54A09A;
