-- B54A01G.ADA

-- CHECK THAT A LABEL CANNOT BE AT THE END OF A CASE STATEMENT.

-- DAT 3/18/81
-- ABW 6/11/82

PROCEDURE B54A01G IS

     I : INTEGER := 4;

BEGIN

     <<LABEL>> CASE I IS
          WHEN OTHERS => NULL;
     END CASE LABEL;              -- ERROR: LABEL.

END B54A01G;
