-- B54A01F.ADA

-- CHECK THAT THE CASE EXPRESSION IS NOT REPEATED
-- AT THE END OF THE CASE STATEMENT.

-- DAT 3/18/81
-- ABW 6/11/82

PROCEDURE B54A01F IS

     I : INTEGER := 4;

BEGIN

     CASE I IS
          WHEN OTHERS => NULL;
     END CASE I;                  -- ERROR: I.

END B54A01F;
