-- B54A01A.ADA

-- CHECK THAT 'OF' IS FORBIDDEN IN A CASE STATEMENT.

-- DAT 3/18/81
-- ABW 6/11/82

PROCEDURE B54A01A IS

     I : INTEGER := 4;

BEGIN

     CASE I OF                          -- ERROR: OF.      
          WHEN OTHERS => NULL;
     END CASE;

END B54A01A;
