-- B54A60A.ADA

-- OBJECTIVE:
--     CHECK THAT A CASE EXPRESSION MAY NOT BE AN OVERLOADED ENUMERATION
--     LITERAL OR AN OVERLOADED FUNCTION CALL.

-- HISTORY:
--     BCB 02/29/88  CREATED ORIGINAL TEST.

PROCEDURE B54A60A IS

     TYPE INT IS NEW INTEGER;

     TYPE ENUM1 IS (RED, BLUE, GREEN, YELLOW);
     TYPE ENUM2 IS (ORANGE, PURPLE, BLACK, RED, BLUE);

     FUNCTION FUNC RETURN INTEGER IS
     BEGIN
          RETURN 0;
     END FUNC;

     FUNCTION FUNC RETURN INT IS
     BEGIN
          RETURN 0;
     END FUNC;

BEGIN

     CASE RED IS                                       -- ERROR:
          WHEN OTHERS => NULL;
     END CASE;

     CASE FUNC IS                                      -- ERROR:
          WHEN 0 => NULL;
          WHEN OTHERS => NULL;
     END CASE;

END B54A60A;
