-- B54A60B.ADA

-- OBJECTIVE:
--     CHECK THAT A CASE EXPRESSION MAY NOT BE AN OVERLOADED CHARACTER
--     LITERAL.

-- HISTORY:
--     BCB 07/14/88  CREATED ORIGINAL TEST.

PROCEDURE B54A60B IS

     TYPE ENUM IS ('A', 'B', 'C', 'D');

BEGIN

     CASE 'B' IS                 -- ERROR: OVERLOADED CHARACTER LITERAL.
          WHEN OTHERS => NULL;
     END CASE;

END B54A60B;
