-- B54A08A.ADA

-- CHECK THAT A CASE EXPRESSION CANNOT BE OF A GENERIC FORMAL TYPE.

-- SPS 5/5/82
-- SPS 12/10/82
-- SPS 01/05/83

WITH SYSTEM;
PROCEDURE B54A08A IS

     GENERIC
          TYPE T IS RANGE <>;
          V1 : IN T;
          V2 : IN OUT T;
     PROCEDURE PROC;

     PROCEDURE PROC IS
     BEGIN

          CASE V1 IS               -- ERROR: GENERIC TYPE.
               WHEN SYSTEM.MIN_INT .. SYSTEM.MAX_INT => NULL;
               WHEN OTHERS => NULL;
          END CASE;

          CASE V2 IS               -- ERROR: GENERIC TYPE.
               WHEN SYSTEM.MIN_INT .. SYSTEM.MAX_INT => NULL;
               WHEN OTHERS => NULL;
          END CASE;

     END;

BEGIN
     NULL;
END B54A08A;
