-- B54A01H.ADA

-- CHECK THAT A CASE STATEMENT LABEL CANNOT BE INDICATED WITH A ':'.

-- DAT 3/18/81
-- ABW 6/11/82

PROCEDURE B54A01H IS

     I : INTEGER := 4;

BEGIN

     L: CASE I IS                  -- ERROR: 'L:' PRECEDING 'CASE'.
          WHEN OTHERS => NULL;
     END CASE;

END B54A01H;
