-- B54A27B.ADA

-- CHECK THAT RELATIONAL OPERATORS ARE NOT
-- ALLOWED IN CASE CHOICES IF NOT PARENTHESIZED.

-- DAT 3/30/81
-- JRK 2/2/83 SPLIT FROM B54A27B.

PROCEDURE B54A27B IS

     T : CONSTANT BOOLEAN := TRUE;
     F : CONSTANT BOOLEAN := FALSE;

BEGIN

     CASE FALSE IS
          WHEN F < T => NULL;                -- ERROR: NO ()'S.
          WHEN OTHERS => NULL;
     END CASE;

END B54A27B;
