-- B54A01J.ADA

-- CHECK THAT A CASE STATEMENT CANNOT END WITH 'ENDCASE'.

-- DAT 3/18/81
-- ABW 6/11/82

PROCEDURE B54A01J IS

     I : INTEGER := 4;

BEGIN

     CASE I IS
          WHEN OTHERS => NULL;
     ENDCASE;                      -- ERROR: ENDCASE.

END B54A01J;
