-- B55A01K.ADA

-- CHECK ILLEGAL END LOOP SYNTAX.

-- CHECK WHEN THE WORD LOOP IS MISSING ON END LOOP STATEMENTS.

-- CHECK 'FOR' LOOPS.

-- DAT 1/21/81
-- ABW 6/17/82
-- SPS 3/1/83

PROCEDURE B55A01K IS

     I : INTEGER;

BEGIN

     FOR I IN 1 .. 10 LOOP
          NULL;
     END;                     -- ERROR: END LOOP REQUIRED.

END B55A01K;
