-- B55A01F.ADA

-- CHECK FOR ILLEGAL SYNTAX IN FOR STATEMENT.
-- CHECK THAT 'DO' MAY NOT BE SUBSTITUTED FOR 'LOOP'.

-- DAT 1/21/81
-- ABW 6/17/82

PROCEDURE B55A01F IS

     I : INTEGER;

BEGIN

     FOR I IN 1 .. 10 DO                -- ERROR: 'DO'.
          NULL;
     END LOOP;

END B55A01F;
