-- B55A01E.ADA

-- CHECK FOR ILLEGAL SYNTAX IN WHILE STATEMENT.
-- CHECK THAT A ';' MAY NOT BE SUBSTITUTED FOR 'LOOP'.

-- DAT 1/21/81
-- ABW 6/17/82

PROCEDURE B55A01E IS

     VBF : BOOLEAN := FALSE;

BEGIN

     WHILE VBF;                          -- ERROR: ';'.
          NULL;
     END LOOP;

END B55A01E;
