-- B55A01J.ADA

-- CHECK ILLEGAL SYNTAX IN END LOOP STATEMENT.

-- CHECK WHEN THE WORD LOOP IS MISSING ON AN END LOOP STATEMENT.

-- CHECK FOR LOOPS WITH LOOP IDENTIFIERS.

-- DAT 1/21/81
-- ABW 6/17/82
-- SPS 3/1/83

PROCEDURE B55A01J IS

     VBF : BOOLEAN := FALSE;

BEGIN

L20:
     WHILE VBF LOOP
          NULL;
     END L20;       -- ERROR: "END LOOP L20" REQUIRED.

END B55A01J;
