-- B55A01O.ADA

-- CHECK FOR ILLEGAL COUPLING OF 'FOR' AND 'WHILE' IN LOOP STATEMENTS.

-- DAT 1/21/81
-- ABW 6/17/82

PROCEDURE B55A01O IS

     VBF : BOOLEAN := FALSE;

     I : INTEGER;

BEGIN

     WHILE VBF FOR I IN 1 .. 10 LOOP    -- ERROR: ILLEGAL SYNTAX
          NULL;                         -- (WHILE ... FOR ...).
     END LOOP;

END B55A01O;
