-- B55A01N.ADA

-- CHECK FOR ILLEGAL COUPLING OF 'FOR' AND 'WHILE' IN LOOP STATEMENTS.

-- DAT 1/21/81
-- ABW 6/17/82

PROCEDURE B55A01N IS

     VBF : BOOLEAN := FALSE;

     I : INTEGER;

BEGIN

     FOR I IN 1 .. 10 WHILE VBF LOOP    -- ERROR: ILLEGAL SYNTAX
          NULL;                         -- (FOR ... WHILE ...).
     END LOOP;

END B55A01N;
