-- B55A01G.ADA

-- CHECK FOR ILLEGAL SYNTAX IN WHILE STATEMENT.
-- CHECK THAT 'DO' MAY NOT BE SUBSTITUTED FOR 'LOOP'.

-- DAT 1/21/81
-- ABW 6/17/82

PROCEDURE B55A01G IS

     VBF : BOOLEAN := FALSE;

BEGIN

     WHILE VBF DO                       -- ERROR: 'DO'.
          NULL;
     END LOOP;

END B55A01G;
