-- B55A01L.ADA

-- CHECK ILLEGAL END LOOP SYNTAX.

-- CHECK WHEN THE WORD LOOP IS MISSING ON END LOOP STATEMENTS.

-- CHECK 'WHILE' LOOPS.

-- DAT 1/21/81
-- ABW 6/17/82
-- SPS 3/1/83

PROCEDURE B55A01L IS

     VBF : BOOLEAN := FALSE;

BEGIN

     WHILE VBF LOOP
          NULL;
     END;                -- ERROR: END LOOP REQUIRED.

END B55A01L;
