-- B55A01D.ADA

-- CHECK FOR ILLEGAL SYNTAX IN FOR STATEMENT.
-- CHECK THAT A ';' MAY NOT BE SUBSTITUTED FOR 'LOOP'.

-- DAT 1/21/81
-- ABW 6/17/82

PROCEDURE B55A01D IS

     I : INTEGER;

BEGIN

     FOR I IN 1 .. 10;                -- ERROR: ';'.
          NULL;
     END LOOP;

END B55A01D;
