-- B55B01A.ADA

-- CHECK THAT A LOOP_PARAMETER CANNOT BE USED AS THE TARGET OF AN
--   ASSIGNMENT STATEMENT OR AS AN ACTUAL IN OUT OR OUT PARAMETER.

-- DAS 01/12/81
-- SPS 10/26/82

PROCEDURE B55B01A IS

     I1 : INTEGER := 0;

     PROCEDURE P ( P1 : OUT INTEGER; P2 : IN OUT INTEGER ) IS
     BEGIN
          NULL;
     END P;

BEGIN

     FOR I IN 1..10 LOOP
          I := I1;       -- ERROR: LOOP_PARAMETER USED AS THE TARGET 
                         --    OF AN ASSIGNMENT STATEMENT.
          P (I1, I);     -- ERROR: LOOP_PARAMETER USED AS AN IN OUT
                         --    PARAMETER.
          P (I, I1);     -- ERROR: LOOP_PARAMETER USED AS AN OUT
                         --    PARAMETER.
     END LOOP;

END B55B01A;
