-- B55B17A.ADA

-- OBJECTIVE:
--     CHECK THAT A LOOP PARAMETER CANNOT BE A SUBSCRIPTED VARIABLE.

-- HISTORY:
--     DHH 06/15/88 CREATED ORIGINAL TEST.

PROCEDURE B55B17A IS
     TYPE ARY IS ARRAY(1..5) OF INTEGER;
     A : ARY;

BEGIN
    FOR I IN 1 .. 5 LOOP
         FOR A(I) IN 1 .. 5 LOOP                           -- ERROR:
              NULL;
         END LOOP;
    END LOOP;
END B55B17A;
