-- B55B17B.ADA

-- OBJECTIVE:
--     CHECK THAT A LOOP PARAMETER CANNOT BE A RECORD COMPONENT.

-- HISTORY:
--     DHH 06/15/88 CREATED ORIGINAL TEST.

PROCEDURE B55B17B IS
     TYPE REC IS
          RECORD
               I : INTEGER;
               T : CHARACTER;
          END RECORD;
     A : REC;

BEGIN
    FOR A.I IN 1 .. 5 LOOP                             -- ERROR:
         NULL;
    END LOOP;
END B55B17B;
