-- B55B17C.ADA

-- OBJECTIVE:
--     CHECK THAT A LOOP PARAMETER CANNOT BE A SELECTED NAME IDENTIFYING
--     A VARIABLE IN THE SCOPE ENCLOSING THE LOOP.

-- HISTORY:
--     DHH 06/15/88 CREATED ORIGINAL TEST.

PROCEDURE B55B17C IS

     I,K : INTEGER;

BEGIN
    FOR B55B17C.I IN 1 .. 5 LOOP                             -- ERROR:
         NULL;
    END LOOP;
END B55B17C;
