-- B56001E.ADA

-- CHECK THAT IN A BLOCK STATEMENT, DECLARATIONS MUST COME BEFORE BEGIN.

-- SPS 3/4/83

PROCEDURE B56001E IS
BEGIN

     BEGIN Y: INTEGER; Y := 5; END;          -- ERROR: DCL AS STMT.

END B56001E;
