-- B56001D.ADA

-- CHECK THAT BEGIN CANNOT BE OMITTED FROM BLOCK STATEMENTS.

-- SPS 3/4/83

PROCEDURE B56001D IS
BEGIN

     DECLARE EXCEPTION                       -- ERROR: MISSING BEGIN.
          WHEN OTHERS => NULL;
     END;

END B56001D;
