-- B56001H.ADA

-- CHECK THAT END CANNOT BE OMITTED FROM BLOCK STATEMENTS.

-- SPS 3/4/83

PROCEDURE B56001H IS
BEGIN

 L3: DECLARE
     BEGIN
          DECLARE
          BEGIN
               NULL;
          EXCEPTION
               WHEN OTHERS => NULL;
     END L3;                            -- ERROR: MISSING END.

END B56001H;
