-- B56001C.ADA

-- CHECK THAT A BLOCK CANNOT HAVE MORE THAN ONE BLOCK ID.

-- SPS 3/4/83

PROCEDURE B56001C IS
BEGIN

     B4 : B5 : BEGIN                         -- ERROR: TWO IDS.
          NULL;
     END B5;

END B56001C;
