-- B56001F.ADA

-- CHECK THAT STATEMENTS MUST APPEAR AFTER THE BEGIN IN BLOCK
-- STATEMENTS.   

-- SPS 3/4/83

PROCEDURE B56001F IS
BEGIN

     DECLARE NULL;                      -- ERROR: STMT BEFORE BEGIN.
     BEGIN NULL; END;

END B56001F;
