-- B56001G.ADA

-- CHECK THAT THE EXCEPTION PART OF A BLOCK STATEMENT MUST CONTAIN AT
-- LEAST ONE EXCEPTION HANDLER.

-- SPS 3/4/83

PROCEDURE B56001G IS
BEGIN

     L7: BEGIN
          NULL;
     EXCEPTION
     END L7;                                 -- ERROR: EMPTY EXCEPTION.

END B56001G;
