-- B58002B.ADA

-- CHECK THAT A RETURN STATEMENT IN A FUNCTION MUST HAVE AN EXPRESSION
--   AND THAT A RETURN STMT IN A PROCEDURE MUST NOT HAVE AN EXPRESSION.

-- CHECKS GENERIC FUNCTIONS AND PROCEDURES.

-- SPS 3/7/83

PROCEDURE B58002B IS

     GENERIC
     FUNCTION FNC1 RETURN INTEGER;

     FUNCTION FNC1 RETURN INTEGER IS

          I1 : INTEGER;

          GENERIC
          PROCEDURE PRC1 (I1 : OUT INTEGER);

          PROCEDURE PRC1 (I1 : OUT INTEGER) IS
          BEGIN
               I1 := 5;
               RETURN (I1 + 4);  -- ERROR: EXPRESSION IN PROC RETURN.
          END PRC1;

     BEGIN
          RETURN;                -- ERROR: EXPRESSION MISSING IN GENERIC
                                 -- FUNCTION RETURN.
     END FNC1;

BEGIN
     NULL;
END B58002B;
