-- B58002A.ADA

-- CHECK THAT A RETURN STATEMENT IN A FUNCTION MUST HAVE AN EXPRESSION
--   AND THAT A RETURN STMT IN A PROCEDURE MUST NOT HAVE AN EXPRESSION.

-- DCB 2/11/80
-- JRK 11/3/80
-- SPS 11/3/82

PROCEDURE B58002A IS

     I2, I3 : INTEGER;

     FUNCTION FNC1 RETURN INTEGER IS

          I1 : INTEGER;

          PROCEDURE PRC1 (I1 : OUT INTEGER) IS
          BEGIN
               I1 := 5;
               RETURN (I1 + 4);  -- ERROR: EXPRESSION IN PROC RETURN.
          END PRC1;

     BEGIN
          I1 := 5;
          PRC1(I3);
          RETURN;                -- ERROR: MISSING EXPRESSION.
     END FNC1;

BEGIN
     I2 := FNC1;
END B58002A;
