-- B58002C.ADA

-- CHECK THAT A RENTURN STATEMENT IN AN ACCEPT STATEMENT MUST NOT
-- CONTAIN A RETURN EXPRESSION.

-- SPS 3/7/83
-- JBG 8/21/83

PROCEDURE B58002C IS

     TASK T IS
          ENTRY E1 (I : IN OUT INTEGER);
     END T;

     TASK BODY T IS
          I1 : INTEGER := 5;
     BEGIN
          ACCEPT E1 (I : IN OUT INTEGER) DO
               RETURN (I1);      -- ERROR: EXPRESSION IN ACCEPT RETURN.
          END E1;
     END T;

BEGIN
     NULL;
END B58002C;
