-- B58001A.ADA

-- CHECK THAT A RETURN STATEMENT CANNOT APPEAR OUTSIDE
--    THE BODY OF A SUBPROGRAM.

-- DCB 2/1/80
-- JRK 11/3/80
-- SPS 3/7/83

PROCEDURE B58001A IS

     PACKAGE P IS
          I : INTEGER;
     END P;

     PACKAGE BODY P IS
     BEGIN
          RETURN;   -- ERROR: RETURN STATEMENT USED OUTSIDE SUBPROGRAM
                    --        TO LEAVE A PACKAGE BODY.
     END P;

BEGIN

     DECLARE

          PACKAGE P IS
               I : INTEGER;
          END P;

          PACKAGE BODY P IS
          BEGIN
               RETURN;   -- ERROR: RETURN STATEMENT USED OUTSIDE 
                         --        SUBPROGRAM TO LEAVE A PACKAGE BODY.
          END P;

     BEGIN
          NULL;
     END;

END B58001A;
