-- B58003B.ADA

-- CHECK THAT THE TYPE OF A RETURN STATEMENT'S EXPRESSION MUST MATCH
--    THE RETURN TYPE SPECIFIED IN THE FUNCTION'S SPECIFICATION.

-- CHECKS GENERIC FUNCTIONS.

-- SPS 3/7/83

PROCEDURE B58003B IS

     SUBTYPE INT IS INTEGER RANGE 0..10;

     GENERIC
     FUNCTION FNC1 RETURN INTEGER;

     GENERIC
     FUNCTION FNC2 RETURN INT;

     FUNCTION FNC2 RETURN INT IS
          I2 : INTEGER RANGE 5..15 := 6;
     BEGIN
          RETURN I2;     -- LEGAL: TYPES MATCH, SUBTYPES OVERLAP.
     END FNC2;

     FUNCTION FNC1 RETURN INTEGER IS
     BEGIN
          RETURN 'Z';    -- ERROR: EXPRESSION TYPE DOES NOT MATCH.
     END FNC1;

BEGIN
     NULL;
END B58003B;
