-- B58003A.ADA

-- CHECK THAT THE TYPE OF A RETURN STATEMENT'S EXPRESSION MUST MATCH
--    THE RETURN TYPE SPECIFIED IN THE FUNCTION'S SPECIFICATION.

-- DCB 2/11/80
-- JRK 11/3/80
-- SPS 11/3/82
-- SPS 11/22/82

PROCEDURE B58003A IS

     SUBTYPE INT IS INTEGER RANGE 0..10;
     I1 : INTEGER;

     FUNCTION FNC2 RETURN INT IS
          I2 : INTEGER RANGE 5..15 := 6;
     BEGIN
          RETURN I2;     -- LEGAL: TYPES MATCH, SUBTYPES OVERLAP.
     END FNC2;

     FUNCTION FNC1 RETURN INTEGER IS
     BEGIN
          RETURN 'Z';    -- ERROR: EXPRESSION TYPE DOES NOT MATCH.
     END FNC1;

BEGIN
     I1 := FNC2;
     I1 := FNC1;
END B58003A;
