-- B61001O.ADA

-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A FLOATING POINT ACCURACY CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001O IS

     PROCEDURE P11 ( X : FLOAT DIGITS 6 ) IS        -- ERROR:  DIGITS
     BEGIN
          NULL;
     END P11;

BEGIN

     NULL;

END B61001O;
