-- B61003A.ADA

-- CHECK THAT A SUBPROGRAM DECLARATION AND A SUBPROGRAM BODY CAN BE
--   GIVEN SEPARATELY IN THE SAME DECLARATIVE PART, BUT THAT THE 
--   SUBPROGRAM DECLARATION MUST PRECEDE THE SUBPROGRAM BODY.

-- DAS  1/20/81
-- SPS 10/19/83

PROCEDURE B61003A IS

     PROCEDURE PROC1 (X : INTEGER) IS
     BEGIN
          NULL;
     END PROC1;

     PROCEDURE PROC2 (X : INTEGER) IS
     BEGIN
          PROC1 (3);
     END PROC2;

     PROCEDURE PROC1 (X : INTEGER);    -- ERROR: DECLARATION MUST 
                                       -- PRECEDE BODY.

BEGIN
     NULL;
END B61003A;
