-- B61001R.ADA

-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A DISCRIMINANT CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001R IS

     TYPE REC ( DISC : INTEGER ) IS
          RECORD NULL;  END RECORD;

     PROCEDURE P14 ( X : REC (DISC => 1) ) IS  -- ERROR: DISCRIMINANT
                                               -- CONSTRAINT
     BEGIN 
          NULL;
     END P14;

BEGIN

     NULL;

END B61001R;
