-- B61001P.ADA

-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A FIXED POINT ACCURACY CONSTRAINT.

-- BHS 6/29/84

PROCEDURE B61001P IS

     PROCEDURE P12 ( X : DURATION DELTA 0.01 ) IS    -- ERROR: DELTA
     BEGIN
          NULL;
     END P12;

BEGIN
     
     NULL;

END B61001P;
