-- B61001Q.ADA

-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT BE AN ARRAY INDEX CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001Q IS

     TYPE ARR IS ARRAY ( INTEGER RANGE <> ) OF INTEGER;

     PROCEDURE P13 ( X : ARR(1..10) ) IS    -- ERROR: ARRAY CONSTRAINT
     BEGIN
          NULL;
     END P13;

BEGIN

     NULL;

END B61001Q;
