-- B61001M.ADA

-- CHECK THAT AN ARRAY TYPE DEFINITION IS NOT ALLOWED IN A FORMAL
-- PARAMETER DECLARATION.

-- DAS  1/20/81

PROCEDURE B61001M IS

     PROCEDURE P9 (X: ARRAY(1..10) OF INTEGER) IS -- ERROR: FORMAL ARRAY
                                                  -- TYPE DEFINITION.
     BEGIN
          NULL;
     END P9;

BEGIN

     NULL;

END B61001M;
