-- B61001T.ADA

-- CHECK THAT THE RETURN TYPE OF A FUNCTION MUST BE DESIGNATED BY A TYPE
-- MARK; IT CANNOT HAVE A FLOATING POINT ACCURACY CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001T IS

     FUNCTION F5 (X : INTEGER) RETURN FLOAT DIGITS 6  IS   -- ERROR:
                                                           -- DIGITS

     BEGIN
          RETURN 5.0;
     END F5;

BEGIN

     NULL;

END B61001T;
