-- B61001V.ADA

-- CHECK THAT THE RETURN TYPE OF A FUNCTION MUST BE DESIGNATED BY A TYPE
-- MARK; IT CANNOT HAVE AN ARRAY INDEX CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001V IS

     TYPE ARR IS ARRAY ( INTEGER RANGE <> ) OF INTEGER;

     FUNCTION F7 (X : INTEGER) RETURN ARR(1..10) IS   -- ERROR: ARRAY 
                                                      -- CONSTRAINT
     BEGIN
          RETURN (1..10 => 7);
     END F7;

BEGIN

     NULL;

END B61001V;
