-- B61001E.ADA

-- CHECK THAT A CHARACTER LITERAL MAY NOT BE USED AS A FUNCTION NAME.

-- DAS  1/20/81
-- JBG 8/21/83

PROCEDURE B61001E IS

     FUNCTION '+' (X,Y : CHARACTER) RETURN INTEGER IS      -- ERROR: '
     BEGIN
          RETURN 3;
     END;

BEGIN

     NULL;

END B61001E;
