-- B61001W.ADA

-- CHECK THAT THE RETURN TYPE OF A FUNCTION MUST BE DESIGNATED BY A TYPE
-- MARK; IT CANNOT HAVE A DISCRIMINANT CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001W IS

     TYPE REC (DISC : INTEGER) IS
          RECORD NULL; END RECORD;


     FUNCTION F8 (X : INTEGER) RETURN REC(DISC => 8) IS   -- ERROR:
                                                     -- DISCRIMINANT
     BEGIN
          RETURN (DISC => 8);
     END F8;

BEGIN

     NULL;

END B61001W;
