-- B61001U.ADA

-- CHECK THAT THE RETURN TYPE OF A FUNCTION MUST BE DESIGNATED BY A TYPE
-- MARK; IT CANNOT HAVE A FIXED POINT ACCURACY CONSTRAINT.

-- BHS 6/29/84

PROCEDURE B61001U IS

     FUNCTION F6 (X : INTEGER) RETURN DURATION DELTA 0.01 IS   -- ERROR:
                                                               -- DELTA

     BEGIN
          RETURN 6.00;
     END F6;

BEGIN

     NULL;

END B61001U;
