-- B61001N.ADA

-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A RANGE CONSTRAINT.

-- BHS 6/28/84

PROCEDURE B61001N IS

     PROCEDURE P10 ( X : INTEGER RANGE 1..10 ) IS    -- ERROR: RANGE
     BEGIN
          NULL;
     END P10;
     
BEGIN          

     NULL;

END B61001N;
