-- B61005A.ADA

-- OBJECTIVE:
--     CHECK THAT DEFAULT EXPRESSIONS ARE FORBIDDEN FOR SUBPROGRAM
--     FORMAL PARAMETERS OF MODE "INOUT" OR "OUT".

-- HISTORY:
--     DHH 03/07/88 CREATED ORIGINAL TEST.

PROCEDURE B61005A IS

     PROCEDURE TEST_INOUT(I : IN OUT INTEGER := 12) IS     -- ERROR:
          BEGIN
               NULL;
          END;

     PROCEDURE TEST_OUT(I : OUT INTEGER := 12) IS          -- ERROR:
          BEGIN
               I := 12;
          END;
BEGIN
     NULL;
END B61005A;
