-- B62001C.ADA

-- CHECK THAT SUBPROGRAMS CAN NEITHER BE DECLARED NOR PASSED AS
-- SUBPROGRAM PARAMETERS.

-- DAS 1/23/81
-- JRK 3/16/81
-- JBG 8/21/83

PROCEDURE B62001C IS
     PROCEDURE P10 (P : PROCEDURE ) IS -- ERROR: FORMAL PROC PARAM.   
     BEGIN
          P10 (B62001C);           -- ERROR: ACTUAL PROC PARAMETER.
                                   -- IT IS SUFFICIENT TO DETECT ONLY
                                   -- ONE OF THESE ERRORS.
     END P10;

BEGIN
     NULL;
END B62001C;
