-- B62001B.ADA

-- CHECK THAT LABELS AND SUBPROGRAMS CAN NEITHER BE DECLARED NOR PASSED
--   AS SUBPROGRAM PARAMETERS.

-- DAS 1/23/81
-- JRK 3/16/81

PROCEDURE B62001B IS

     PROCEDURE P9 (L : LABEL) IS -- ERROR: FORMAL LABEL PARAMETER.
     BEGIN
     <<LBL>>
          NULL;
          P9 (LBL);           -- ERROR: ACTUAL LABEL PARAMETER.
     END P9;

BEGIN
     NULL;
END B62001B;
