-- B63006A.ADA

-- OBJECTIVE:
--     CHECK THAT IF A SUBPROGRAM BODY HAS AN EXCEPTION PART, THEN
--     AT LEAST ONE HANDLER MUST BE SPECIFIED.

-- HISTORY:
--     DHH 03/07/88 CREATED ORIGINAL TEST.

PROCEDURE B63006A IS
     I : INTEGER;
BEGIN
     I := 12;
EXCEPTION
     -- NO HANDLER                                        -- ERROR:
END B63006A;
