-- B63005C.ADA

-- CHECK THAT A RENAMING DECLARATION CANNOT BE USED TO PROVIDE A
-- SUBPROGRAM BODY FOR A SPECIFICATION GIVEN IN A PACKAGE OR IN A
-- DECLARATIVE PART.

-- BHS 7/16/84

PROCEDURE B63005C IS

     PROCEDURE PRO (X : INTEGER);
     FUNCTION FUN RETURN INTEGER;

     PROCEDURE P1 (X : INTEGER);
     FUNCTION F1 RETURN INTEGER;

     PROCEDURE OK1 (X : INTEGER) RENAMES PRO;       -- OK
     FUNCTION OK2 RETURN INTEGER RENAMES FUN;       -- OK

     PROCEDURE P1 (X : INTEGER) RENAMES PRO;        -- ERROR: RENAMES
     FUNCTION F1 RETURN INTEGER RENAMES FUN;        -- ERROR: RENAMES

     PROCEDURE PRO (X : INTEGER) IS
     BEGIN
          NULL;
     END PRO;

     FUNCTION FUN RETURN INTEGER IS
     BEGIN
          RETURN 4;
     END FUN;


     PACKAGE PACK1 IS
          PROCEDURE P2 (X : INTEGER);
     END PACK1;

     PACKAGE BODY PACK1 IS
          PROCEDURE P2 (X : INTEGER) RENAMES PRO;   -- ERROR: RENAMES
     END PACK1;


     PACKAGE PACK2 IS
          FUNCTION F2 RETURN INTEGER;
     END PACK2;

     PACKAGE BODY PACK2 IS
          FUNCTION F2 RETURN INTEGER RENAMES FUN;   -- ERROR: RENAMES
     END PACK2;


BEGIN
     NULL;
END B63005C;
