-- B63010A.ADA

-- CHECK THAT A SUBPROGRAM SPECIFICATION CANNOT FOLLOW ITS BODY IN A
-- DECLARATIVE PART.

-- BHS 7/06/84

PROCEDURE B63010A IS

     PROCEDURE P1 (X : INTEGER) IS
     BEGIN
          NULL;
     END P1;

     FUNCTION F2 RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END F2;

     PROCEDURE P1 (X : INTEGER);      -- ERROR: SPEC FOLLOWING BODY.
     FUNCTION F2 RETURN BOOLEAN;      -- ERROR: SPEC FOLLOWING BODY.

BEGIN

     NULL;

END B63010A;
