-- B63001A.ADA

-- CHECK THAT THE DESIGNATOR AT THE END OF A SUBPROGRAM BODY MUST BE THE
--   SAME AS THE DESIGNATOR USED IN THE SUBPROGRAM SPECIFICATION.

-- DAS  1/23/81

PROCEDURE B63001A IS

     PROCEDURE PROC1 IS
     BEGIN
          NULL;
     END PROC;           -- ERROR: DESIGNATOR DOES NOT MATCH.

     FUNCTION FUNC1 RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END PROC1;          -- ERROR: DESIGNATOR DOES NOT MATCH.

     FUNCTION "+" (X,Y : BOOLEAN) RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END PLUS;           -- ERROR: DESIGNATOR DOES NOT MATCH.

     PROCEDURE PROC2 IS
     BEGIN
          NULL;
     END B63001A.PROC2;  -- ERROR: SELECTED COMPONENT DESIGNATOR.

BEGIN

     NULL;

END B63001A;
