-- B63001B.ADA

-- CHECK THAT THE DESIGNATOR AT THE END OF A GENERIC SUBPROGRAM BODY
-- MUST BE THE SAME AS THE DESIGNATOR USED IN THE SUBPROGRAM
-- SPECIFICATION. 

-- DAS  1/23/81
-- BHS  7/06/84

PROCEDURE B63001B IS

     GENERIC
     PROCEDURE PROC1;

     PROCEDURE PROC1 IS
     BEGIN
          NULL;
     END PROC;           -- ERROR: DESIGNATOR DOES NOT MATCH.


     GENERIC
     FUNCTION FUNC1 RETURN INTEGER;

     FUNCTION FUNC1 RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END PROC1;          -- ERROR: DESIGNATOR DOES NOT MATCH.


     GENERIC
     PROCEDURE PROC2;

     PROCEDURE PROC2 IS
     BEGIN
          NULL;
     END B63001B.PROC2;  -- ERROR: SELECTED COMPONENT DESIGNATOR.


BEGIN

     NULL;

END B63001B;
