-- B64004A.ADA

-- FOR FUNCTIONS AND PROCEDURES HAVING AT LEAST ONE DEFAULT PARAMETER,
--   CHECK THAT:
--        (A) FOR A CALL USING ONLY POSITIONAL NOTATION, NO
--            PARAMETER CAN BE OMITTED UNLESS THE DEFAULT
--            PARAMETERS ARE AT THE END OF THE LIST.
--        (B) FOR A CALL USING NAMED NOTATION, CHECK THAT OMITTED
--            PARAMETERS MUST HAVE DEFAULT VALUES.

-- DAS  1/27/81


PROCEDURE B64004A IS

     I    : INTEGER;

     PROCEDURE P (X1: INTEGER; X2: INTEGER := 2; X3: INTEGER := 3) IS
     BEGIN
          NULL;
     END P;

     FUNCTION F (X1: INTEGER := 1; X2: INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END F;

BEGIN

     I := F(1);          -- ERROR: (A).
     NULL;
     P (X2=>2,X3=>3);    -- ERROR: (B).
     NULL;
     P (X2=>2);          -- ERROR: (B).
     NULL;
     P;                  -- ERROR: (B).
     NULL;
     I := F(X1=>1);      -- ERROR: (B).
     NULL;

END B64004A;
