-- B64001A.ADA

-- OBJECTIVE:
--     CHECK THE USE OF PARENTHESES IN SUBPROGRAM CALLS.  IN
--     PARTICULAR, CHECK THAT IT IS ILLEGAL TO OMIT ACTUAL PARAMETERS
--     IN SUBPROGRAM CALLS IN WHICH ACTUALS ARE REQUIRED.

-- HISTORY:
--     DAS 01/23/81
--     VKG 01/07/83
--     DWC 09/22/87  SPLIT TEST INTO B64001B.ADA.

PROCEDURE B64001A IS

     SUBTYPE INT IS INTEGER RANGE -10..10;

     I    : INT;

     FUNCTION FUNC1 RETURN INT IS
     BEGIN
          RETURN 1;
     END FUNC1;

     FUNCTION FUNC2 (X : INT := 3; Y : INT := -1) RETURN INT IS
     BEGIN
          RETURN 2;
     END FUNC2;

     FUNCTION FUNC3 (X : INT := 3; Y : INT) RETURN INT IS
     BEGIN
          RETURN 3;
     END FUNC3;

BEGIN

     I := FUNC3;    -- ERROR: AT LEAST ONE ACTUAL REQUIRED.
     NULL;
     I := FUNC1;    -- OK.
     NULL;
     I := FUNC2;    -- OK.

END B64001A;
