-- B64001B.ADA

-- OBJECTIVE:
--     CHECK THE USE OF PARENTHESES IN SUBPROGRAM CALLS.  IN
--     PARTICULAR, CHECK THAT EMPTY PARENTHESES ARE NOT PERMITTED
--     AS ACTUAL PARAMETERS.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT B64001A.ADA.

PROCEDURE B64001B IS

     SUBTYPE INT IS INTEGER RANGE -10..10;

     I    : INT;

     PROCEDURE PROC1 IS
     BEGIN
          NULL;
     END PROC1;

     PROCEDURE PROC2 (X : IN INT := 3; Y : IN INT := 5) IS
     BEGIN
          NULL;
     END PROC2;

     FUNCTION FUNC1 RETURN INT IS
     BEGIN
          RETURN 1;
     END FUNC1;

     FUNCTION FUNC2 (X : INT := 3; Y : INT := -1) RETURN INT IS
     BEGIN
          RETURN 2;
     END FUNC2;

BEGIN

     PROC1 ();      -- ERROR: () NOT PERMITTED.
     NULL;
     PROC2 ();      -- ERROR: () NOT PERMITTED.
     NULL;
     I := FUNC1();  -- ERROR: () NOT PERMITTED.
     NULL;
     I := FUNC2();  -- ERROR: () NOT PERMITTED.
     NULL;
     I := FUNC1;    -- OK.
     NULL;
     I := FUNC2;    -- OK.

END B64001B;
