-- B64006A.ADA

-- CHECK THAT CALLS OF THE FORM F(X | Y => 0) ARE NOT PERMITTED EVEN IF
--   X AND Y ARE BOTH INTEGER FORMAL PARAMETERS OF F.

-- DAS  1/28/81

PROCEDURE B64006A IS

     I : INTEGER;

     PROCEDURE P (X,Y : INTEGER) IS
     BEGIN
          NULL;
     END P;

     FUNCTION F (X,Y : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END F;

BEGIN

     P (X | Y => 0);          -- ERROR: | NOT PERMITTED.
     NULL;
     I := F(X | Y => 0);      -- ERROR: | NOT PERMITTED.
     NULL;

END B64006A;
