-- B64004F.ADA

-- FOR FUNCTIONS AND PROCEDURES HAVING AT LEAST ONE DEFAULT PARAMETER,
--   CHECK THAT:
--        (A) CALLS OF THE FORM F(A,,C) ARE FORBIDDEN, WHERE THE
--            SECOND FORMAL PARAMETER HAS A DEFAULT VALUE.
--        (B) FOR A CALL USING ONLY POSITIONAL NOTATION, NO
--            PARAMETER CAN BE OMITTED UNLESS THE DEFAULT
--            PARAMETERS ARE AT THE END OF THE LIST.
--        (C) FOR A CALL USING NAMED NOTATION, CHECK THAT OMITTED
--            PARAMETERS MUST HAVE DEFAULT VALUES.

-- DAS  1/27/81
-- EG  04/05/84

PROCEDURE B64004F IS

     I    : INTEGER;

     PROCEDURE P (X1: INTEGER; X2: INTEGER := 2; X3: INTEGER := 3) IS
     BEGIN
          NULL;
     END P;

     FUNCTION F (X1: INTEGER := 1; X2: INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END F;

BEGIN

     I := F(,2);         -- ERROR: (A).
     NULL;

END B64004F;
