-- B64110A.ADA

-- OBJECTIVE:
--     CHECK THAT TYPE MARKS APPEARING IN ACTUAL IN OUT OR OUT
--     PARAMETERS HAVING THE FORM OF TYPE CONVERSIONS MUST CONFORM TO
--     THE TYPE MARK GIVEN IN THE FORMAL PARAMETER'S DECLARATION.

-- HISTORY:
--     BCB 09/24/87  CREATED ORIGINAL TEST.

PROCEDURE B64110A IS

     SUBTYPE SUBINT1 IS INTEGER RANGE 1 .. 20;
     SUBTYPE SUBINT2 IS INTEGER RANGE 1 .. 10;
     SUBTYPE SUBINT3 IS SUBINT1;
     TYPE NEWINT IS NEW INTEGER RANGE 1 .. 20;

     I1 : INTEGER := 1;
     I2 : NEWINT := 2;

     PROCEDURE PROC1 (PINOUT : IN OUT SUBINT1) IS

     BEGIN
          NULL;
     END PROC1;

     PROCEDURE PROC2 (POUT : OUT SUBINT1) IS

     BEGIN
          POUT := 5;
     END PROC2;

     PROCEDURE PROC3 (PIN : IN SUBINT1) IS

     BEGIN
          NULL;
     END PROC3;

BEGIN

     PROC1 (INTEGER(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC2 (INTEGER(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC3 (INTEGER(I1));   -- OK.

     PROC1 (SUBINT2(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC2 (SUBINT2(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC3 (SUBINT2(I1));   -- OK.

     PROC1 (NEWINT(I1));    -- ERROR: MISMATCHED BASE TYPES.
     PROC2 (NEWINT(I1));    -- ERROR: MISMATCHED BASE TYPES.
     PROC3 (NEWINT(I1));    -- ERROR: MISMATCHED BASE TYPES.

     PROC1 (SUBINT3(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC2 (SUBINT3(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC3 (SUBINT3(I1));   -- OK.

     PROC1 (INTEGER(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC2 (INTEGER(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC3 (INTEGER(I2));   -- OK.

     PROC1 (SUBINT2(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC2 (SUBINT2(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC3 (SUBINT2(I2));   -- OK.

     PROC1 (SUBINT3(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC2 (SUBINT3(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     PROC3 (SUBINT3(I2));   -- OK.

     PROC1 (SUBINT1(I2));   -- OK.
     PROC2 (SUBINT1(I2));   -- OK.
     PROC3 (SUBINT1(I2));   -- OK.

     PROC1 (B64110A.SUBINT1(I2));   -- OK.
     PROC2 (B64110A.SUBINT1(I2));   -- OK.
     PROC3 (B64110A.SUBINT1(I2));   -- OK.

END B64110A;
