-- B65001A.ADA

-- CHECK THAT IN OUT AND OUT PARAMETERS CANNOT BE SPECIFIED FOR
-- FUNCTIONS.

-- DAS 2/2/81

PROCEDURE B65001A IS

     TYPE T IS NEW INTEGER RANGE 0 .. 100;

     FUNCTION F1 (I : IN T; J : IN OUT T) RETURN T IS  -- ERROR: IN OUT.
     BEGIN
          RETURN 1;
     END F1;

     FUNCTION F2 (J : OUT T) RETURN T IS               -- ERROR: OUT.
     BEGIN
          RETURN 2;
     END F2;

     FUNCTION "+" (I : IN OUT T; J : IN T) RETURN T IS -- ERROR: IN OUT.
     BEGIN
          RETURN 3;
     END "+";

     FUNCTION "-" (I : OUT T) RETURN T IS              -- ERROR: OUT.
     BEGIN
          RETURN 4;
     END "-";

BEGIN
     NULL;
END B65001A;
