-- B65002A.ADA

-- CHECK THAT A FUNCTION BODY MUST CONTAIN ONE OR MORE
-- RETURN STATEMENTS SPECIFYING A RETURN VALUE.

-- RJK 9/13/83

PROCEDURE B65002A IS

     X : INTEGER;

     FUNCTION NO_RETURN RETURN INTEGER IS
          RET_VAL : INTEGER;
     BEGIN

          IF TRUE THEN
               RET_VAL := 5;
          ELSE
               RET_VAL := 10;
          END IF;

     END NO_RETURN;           -- ERROR: NO RETURN STATEMENT
                              -- SPECIFYING A RETURN VALUE.

BEGIN

     X := NO_RETURN;

END B65002A;
