-- B65002B.ADA

-- CHECK THAT A FUNCTION BODY MUST CONTAIN ONE OR MORE
-- RETURN STATEMENTS SPECIFYING A RETURN VALUE.

-- THIS TEST CONTAINS A NESTED FUNCTION WITH A RETURN STATEMENT.

-- RJK 9/13/83
-- JBG 10/14/83

PROCEDURE B65002B IS

     X : INTEGER;

     FUNCTION NO_RETURN RETURN INTEGER IS

          RET_VAL : INTEGER;

          FUNCTION WITH_RETURN RETURN INTEGER IS
          BEGIN
               RETURN 5;
          END WITH_RETURN;

     BEGIN

          IF TRUE THEN
               RET_VAL := 5;
          ELSE
               RET_VAL := 10;
          END IF;

     END NO_RETURN;           -- ERROR: NO RETURN STATEMENT
                              -- SPECIFYING A RETURN VALUE.

BEGIN

     X := NO_RETURN;

END B65002B;
