-- B66001D.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION LITERAL AND A PARAMETERLESS FUNCTION
--     WITH THE SAME PROFILE CANNOT BE DECLARED IN THE SAME DECLARATIVE
--     REGION.

-- HISTORY:
--     BCB 09/24/87  CREATED ORIGINAL TEST.

PROCEDURE B66001D IS

BEGIN

     DECLARE

          TYPE ENUM IS (P);

          FUNCTION P RETURN ENUM IS   -- ERROR: DUPLICATE NAME P.
          BEGIN
               RETURN ENUM'VAL(1);
          END P;

     BEGIN
          NULL;
     END;

     NULL;

END B66001D;
