-- B67001J.ADA

-- OBJECTIVE:
--     CHECK THAT A PROCEDURE DECLARATION WITH THE OPERATOR SYMBOL
--     ":=" IS NOT ALLOWED AS GENERIC INSTANTIATION.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT B67001C.ADA.

PROCEDURE B67001J IS

     GENERIC
          TYPE ELEMENT IS (<>);
     PROCEDURE P (P1 : OUT ELEMENT; P2 : ELEMENT);
     PROCEDURE P (P1 : OUT ELEMENT; P2 : ELEMENT) IS
     BEGIN
          P1 := P2;
     END P;

BEGIN

     DECLARE   -- (A)

          PROCEDURE ":=" IS NEW P                 -- ERROR: :=.
               (ELEMENT => INTEGER);

     BEGIN     -- (A)
          NULL;
     END; -- (A)

END B67001J;
