-- B67001K.ADA

-- OBJECTIVE:
--     CHECK THAT CERTAIN FUNCTION DECLARATIONS WITH OPERATOR SYMBOLS
--     ARE NOT ALLOWED IN RENAMING DECLARATIONS.  IN PARTICULAR, THE
--     FOLLOWING SUBTEST IS PERFORMED:
--     (A)  CHECK THAT ":=" IS NOT PERMITTED AS OPERATOR SYMBOL.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B67001D.ADA.

PROCEDURE B67001K IS

     PACKAGE PKG IS
          TYPE LIM_PRIV IS LIMITED PRIVATE;
          FUNCTION "=" (P1, P2 : LIM_PRIV) RETURN BOOLEAN;
     PRIVATE
          TYPE LIM_PRIV IS NEW INTEGER;
     END PKG;
     USE PKG;

     PACKAGE BODY PKG IS
          FUNCTION "=" (P1, P2 : LIM_PRIV) RETURN BOOLEAN IS
          BEGIN
               RETURN TRUE;
          END "=";
     END PKG;

     PROCEDURE P (P1 : OUT INTEGER; P2 : INTEGER) IS
     BEGIN
          P1 := P2;
     END P;

BEGIN

     --------------------------------------------------

     DECLARE   -- (A)

          PROCEDURE ":=" (P1 : OUT INTEGER;          -- ERROR: :=.
               P2 : INTEGER) RENAMES P;


     BEGIN     -- (A)
          NULL;
     END; -- (A)

END B67001K;
