-- B71001H.ADA

-- CHECK THAT A PACKAGE BODY CANNOT APPEAR IN A GENERIC PACKAGE
-- SPECIFICATION. 

-- JBG 9/14/83

PROCEDURE B71001H IS

     GENERIC
     PACKAGE P5 IS
          PACKAGE P6 IS
               I : INTEGER;
          END P6;
          PACKAGE BODY P6 IS                 -- ERROR: PACKAGE BODY.
          END;
     END P5;

BEGIN
     NULL;
END B71001H;
