-- B71001W.ADA

-- CHECK THAT MULTIPLE GENERIC BODY STUBS CANNOT APPEAR IN A GENERIC
-- PACKAGE SPECIFICATION.

-- JBG 9/14/83

GENERIC
PACKAGE B71001W IS

     GENERIC
     PROCEDURE PR;                      -- OK.

     GENERIC
     PACKAGE PA IS
     END PA;

     PACKAGE BODY PA IS SEPARATE;       -- ERROR: STUB.

     PACKAGE PB IS END PB;

     PROCEDURE PR IS SEPARATE;          -- ERROR: STUB.

END B71001W;
