-- B71001P.ADA

-- CHECK THAT A SINGLE GENERIC BODY STUB CANNOT APPEAR IN A PACKAGE
-- SPECIFICATION.

-- DAT 4/3/81
-- JBG 9/14/83

PACKAGE B71001P IS

     GENERIC 
     FUNCTION F RETURN INTEGER;

     FUNCTION F RETURN INTEGER IS SEPARATE;     -- ERROR: STUB.

END B71001P;
