-- B71001N.ADA

-- CHECK THAT A GENERIC PACKAGE BODY CANNOT APPEAR IN A PACKAGE
-- SPECIFICATION. 

-- DAT 4/3/81
-- JBG 9/14/83

PROCEDURE B71001N IS

     PACKAGE P5 IS
          GENERIC
          PACKAGE P6 IS
               I : INTEGER;
          END P6;

          PACKAGE BODY P6 IS                 -- ERROR: PACKAGE BODY.
          END;
     END P5;

BEGIN
     NULL;
END B71001N;
