-- B71001J.ADA

-- CHECK THAT A SINGLE BODY STUB CANNOT APPEAR IN A GENERIC PACKAGE
-- SPECIFICATION.

-- JBG 9/14/83

GENERIC
PACKAGE B71001J IS

     PROCEDURE PR IS SEPARATE;          -- ERROR: STUB.

END B71001J;
