-- B71001V.ADA

-- CHECK THAT A SINGLE GENERIC BODY STUB CANNOT APPEAR IN A GENERIC
-- PACKAGE SPECIFICATION.

-- JBG 9/14/83

GENERIC
PACKAGE B71001V IS

     GENERIC
     FUNCTION FR RETURN INTEGER;

     FUNCTION FR RETURN INTEGER IS SEPARATE;      -- ERROR: STUB.

END B71001V;
