-- B71001C.ADA

-- CHECK THAT A SUBPROGRAM BODY CANNOT APPEAR IN A PACKAGE
-- SPECIFICATION.

-- DAT 4/3/81
-- JBG 9/14/83

PROCEDURE B71001C IS

     PACKAGE P7 IS
          FUNCTION FUNC RETURN INTEGER IS        -- ERROR: IS.
          BEGIN  RETURN 5;  END FUNC;
     END P7;

BEGIN
     NULL;
END B71001C;
