-- B71001I.ADA

-- CHECK THAT A SUBPROGRAM BODY CANNOT APPEAR IN A GENERIC PACKAGE
-- SPECIFICATION.

-- JBG 9/14/83

PROCEDURE B71001I IS

     GENERIC
     PACKAGE P7 IS
          FUNCTION FUNC RETURN INTEGER IS        -- ERROR: IS.
          BEGIN  RETURN 5;  END FUNC;
     END P7;

BEGIN
     NULL;
END B71001I;
