-- B71001L.ADA

-- CHECK THAT TASK BODIES CANNOT APPEAR IN A GENERIC PACKAGE
-- SPECIFICATION. 

-- DAT 4/3/81
-- JBG 9/14/83

PROCEDURE B71001L IS

     GENERIC
     PACKAGE P IS
          TASK T;
          TASK BODY T IS                     -- ERROR: BODY.
          BEGIN NULL; END T;
     END P;

BEGIN
     NULL;
END B71001L;
