-- B71001U.ADA

-- CHECK THAT A GENERIC SUBPROGRAM BODY CANNOT APPEAR IN A GENERIC
-- PACKAGE SPECIFICATION.

-- JBG 9/14/83

PROCEDURE B71001U IS

     GENERIC
     PACKAGE P7 IS
          GENERIC
          PROCEDURE PROC;

          PROCEDURE PROC IS                  -- ERROR: IS.
          BEGIN NULL; END PROC;
     END P7;

BEGIN
     NULL;
END B71001U;
