-- B71001Q.ADA

-- CHECK THAT MULTIPLE GENERIC BODY STUBS CANNOT APPEAR IN A PACKAGE
-- SPECIFICATION.

-- DAT 4/3/81
-- JBG 9/14/83

PACKAGE B71001Q IS

     GENERIC
     PROCEDURE PR;                      -- OK.

     GENERIC
     PACKAGE PA IS
     END PA;

     PACKAGE BODY PA IS SEPARATE;       -- ERROR: STUB.

     PACKAGE PB IS END PB;

     PROCEDURE PR IS SEPARATE;          -- ERROR: STUB.

END B71001Q;
