-- B71001O.ADA

-- CHECK THAT A GENERIC SUBPROGRAM BODY CANNOT APPEAR IN A PACKAGE
-- SPECIFICATION.

-- DAT 4/3/81
-- JBG 9/14/83

PROCEDURE B71001O IS

     PACKAGE P7 IS
          GENERIC PROCEDURE PROC;

          PROCEDURE PROC IS                  -- ERROR: IS.
          BEGIN NULL; END PROC;
     END P7;

BEGIN
     NULL;
END B71001O;
