-- B73001C.ADA

-- CHECK THAT IF AN INCOMPLETE TYPE IS DECLARED IN THE PRIVATE PART OF A
--   PACKAGE AND NO FULL DECLARATION IS PROVIDED IN THE SAME PRIVATE
--   PART, THEN A PACKAGE BODY IS REQUIRED.

-- JBG 9/19/83

PROCEDURE B73001C IS

     PACKAGE PACK1 IS
          TYPE T IS PRIVATE;
     PRIVATE
          TYPE INC;
          TYPE T IS ACCESS INC;
     END PACK1;

BEGIN               -- ERROR: BODY OF PACK1 MISSING.
     NULL;
END B73001C;
