-- B73006A.ADA


-- CHECK THAT A PACKAGE BODY CANNOT BE PROVIDED UNLESS ITS SPECIFICATION
--    HAS ALREADY BEEN GIVEN.


-- RM 05/07/81


PROCEDURE  B73006A  IS
BEGIN

     DECLARE

          PACKAGE BODY  PACK1  IS -- ERROR: BODY PRECEDES SPECIFICATION.
          END  PACK1 ;

          PACKAGE  PACK1  IS
               I : INTEGER ;
          END  PACK1 ;

     BEGIN
          NULL ;
     END ;


     DECLARE

          PACKAGE BODY  PACK1  IS -- ERROR: SPECIFICATION MISSING.
          BEGIN
               NULL ;
          END  PACK1 ;

     BEGIN
          NULL ;
     END ;


END B73006A;
