-- B74105A.ADA

-- CHECK THAT THE FULL TYPE DECLARATION OF A PRIVATE TYPE MAY NOT BE: 
   -- (1) AN UNCONSTRAINED TYPE WITH DISCRIMINANTS.
   -- (2) AN UNCONSTRAINED ARRAY TYPE.

-- DSJ 4/29/83
-- SPS 10/20/83

PROCEDURE B74105A IS

     PACKAGE PACK1 IS
          TYPE UNCONS4 IS PRIVATE;
          TYPE UNCONS5 IS PRIVATE;
          TYPE UNCONS6 IS PRIVATE;
          TYPE UNCONS7 IS PRIVATE;
          TYPE UNCONS8 IS PRIVATE;
     PRIVATE
          TYPE UNCONS1 (H : INTEGER) IS
               RECORD
                    NULL;
               END RECORD;
          TYPE UNCONS2 (D : INTEGER := 2) IS
               RECORD
                    NULL;
               END RECORD;
          TYPE UNCONS3 IS ARRAY
                    (INTEGER RANGE <>) OF INTEGER;
          TYPE UNCONS4 IS NEW UNCONS1;       -- ERROR: UNCONSTRAINED
          TYPE UNCONS5 IS NEW UNCONS2;       -- ERROR: UNCONSTRAINED
          TYPE UNCONS6 IS NEW UNCONS3;       -- ERROR: UNCONSTRAINED
          TYPE UNCONS7 IS ARRAY              -- ERROR: UNCONSTRAINED
                    (INTEGER RANGE <>) OF INTEGER;
          TYPE UNCONS8 (D:INTEGER:=2) IS     -- ERROR: UNCONSTRAINED
               RECORD
                    NULL;
               END RECORD;
     END PACK1;

     PACKAGE PACK2 IS
          TYPE UNCONS4 IS LIMITED PRIVATE;
          TYPE UNCONS5 IS LIMITED PRIVATE;
          TYPE UNCONS6 IS LIMITED PRIVATE;
          TYPE UNCONS7 IS LIMITED PRIVATE;
     PRIVATE
          TYPE UNCONS1 (H : INTEGER) IS
               RECORD
                    NULL;
               END RECORD;
          TYPE UNCONS2 (D : INTEGER := 2) IS
               RECORD
                    NULL;
               END RECORD;
          TYPE UNCONS3 IS ARRAY
                    (INTEGER RANGE <>) OF INTEGER;
          TYPE UNCONS4 IS NEW UNCONS1;       -- ERROR: UNCONSTRAINED
          TYPE UNCONS5 IS NEW UNCONS2;       -- ERROR: UNCONSTRAINED
          TYPE UNCONS6 IS NEW UNCONS3;       -- ERROR: UNCONSTRAINED
          TYPE UNCONS7 IS ARRAY              -- ERROR: UNCONSTRAINED
                    (INTEGER RANGE <>) OF INTEGER;
     END PACK2;


BEGIN

     NULL;

END B74105A;
