-- B74103B.ADA

-- CHECK THAT BEFORE THE FULL DECLARATION OF A PRIVATE TYPE,

     -- (1) THE NAME OF THE PRIVATE TYPE,
     -- (2) A NAME THAT DENOTES A SUBTYPE OF THE PRIVATE TYPE, AND
     -- (3) A NAME THAT DENOTES A COMPOSITE TYPE WITH A SUBCOMPONENT 
     --     OF THE PRIVATE TYPE (OR SUBTYPE)

-- MAY NOT BE USED IN A DEFAULT EXPRESSION FOR A SUBPROGRAM PARAMETER.

-- DSJ 4/27/83
-- BHS 6/14/84
-- JRK 8/3/84

PROCEDURE B74103B2 IS

     PACKAGE PACK1 IS

          TYPE P1 IS PRIVATE;
          TYPE LP2 IS LIMITED PRIVATE;

          CP1 : CONSTANT P1;
          CLP2 : CONSTANT LP2;

          SUBTYPE SP1 IS P1;
          SUBTYPE SLP2 IS LP2;

          TYPE ARR1_P1 IS ARRAY ( 1 .. 2 ) OF P1;
          TYPE ARR2_LP2 IS ARRAY ( 1 .. 2 ) OF LP2;
          TYPE ARR3_SP1 IS ARRAY ( 1 .. 2 ) OF SP1;
          TYPE ARR4_SLP2 IS ARRAY ( 1 .. 2 ) OF SLP2;
          TYPE ARR51 IS ARRAY ( 1 .. 2 ) OF ARR1_P1;
          TYPE ARR52 IS ARRAY ( 1 .. 2 ) OF ARR2_LP2;
          TYPE ARR53 IS ARRAY ( 1 .. 2 ) OF ARR3_SP1;
          TYPE ARR54 IS ARRAY ( 1 .. 2 ) OF ARR4_SLP2;

          TYPE REC1 IS
               RECORD
                    C1 : P1;
               END RECORD;

          TYPE REC2 IS
               RECORD
                    C2 : LP2;
               END RECORD;

          TYPE REC3 IS
               RECORD
                    C3 : SP1;
               END RECORD;

          TYPE REC4 IS
               RECORD
                    C4 : SLP2;
               END RECORD;

          TYPE REC51 IS
               RECORD
                    C5 : REC1;
               END RECORD;

          TYPE REC52 IS
               RECORD
                    C6 : REC2;
               END RECORD;

          TYPE REC53 IS
               RECORD
                    C7 : REC3;
               END RECORD;

          TYPE REC54 IS
               RECORD
                    C8 : REC4;
               END RECORD;

          SUBTYPE SS1 IS ARR1_P1;
          SUBTYPE SS2 IS ARR2_LP2;
          SUBTYPE SS3 IS ARR3_SP1;
          SUBTYPE SS4 IS ARR4_SLP2;
          SUBTYPE SS5 IS REC1;
          SUBTYPE SS6 IS REC2;
          SUBTYPE SS7 IS REC3;
          SUBTYPE SS8 IS REC4;

          ------------------------------------------------------------


          PROCEDURE G01 (X : INTEGER := P1'SIZE);    -- ERROR: USE OF 
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G02 (X : INTEGER := LP2'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G03 (X : P1 := SP1'(CP1));       -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G04 (X : INTEGER := SLP2'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G05 (X : INTEGER := ARR1_P1'SIZE);   -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G06 (X : INTEGER := ARR2_LP2'SIZE);  -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G07 (X : INTEGER := ARR3_SP1'SIZE);  -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G08 (X : INTEGER := ARR4_SLP2'SIZE);  -- ERROR: 
                   -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G09 (X : REC1 := REC1'( C1 => CP1 )); -- ERROR:
                  -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G10 (X : INTEGER := REC2'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G11 (X : INTEGER := REC3'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G12 (X : INTEGER := REC4'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G13 (X : INTEGER := SS1'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G14 (X : INTEGER := SS2'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G15 (X : INTEGER := SS3'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G16 (X : INTEGER := SS4'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G17 (X : SS5 := SS5'( C1 => CP1 ));  -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G18 (X : INTEGER := SS6'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G19 (X : SS7 := SS7'( C3 => SP1(CP1)));  -- ERROR:
                   -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G20 (X : INTEGER := SS8'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G21 (X : INTEGER := ARR51'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G22 (X : INTEGER := ARR52'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G23 (X : INTEGER := ARR53'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G24 (X : INTEGER := ARR54'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G25 (X : INTEGER := REC51'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G26 (X : INTEGER := REC52'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G27 (X : INTEGER := REC53'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE G28 (X : INTEGER := REC54'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.


     PRIVATE

          PROCEDURE GG01 (X : INTEGER := P1'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG02 (X : INTEGER := LP2'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG03 (X : P1 := SP1(CP1));       -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG04 (X : INTEGER := SLP2'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG05 (X : INTEGER := ARR1_P1'SIZE);  -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG06 (X : INTEGER := ARR2_LP2'SIZE); -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG07 (X : INTEGER := ARR3_SP1'SIZE); -- ERROR: USE
                      -- OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG08 (X : INTEGER := ARR4_SLP2'SIZE);  -- ERROR: 
                    -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG09 (X : INTEGER := REC1'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG10 (X : INTEGER := REC2'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG11 (X : REC3 := (C3 => SP1(CP1)));  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG12 (X : INTEGER := REC4'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG13 (X : INTEGER := SS1'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG14 (X : INTEGER := SS2'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG15 (X : INTEGER := SS3'SIZE);   -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG16 (X : INTEGER := SS4'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG17 (X : SS5 := SS5'( C1 => CP1 ));   -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG18 (X : INTEGER := SS6'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG19 (X : SS7 := SS7'(C3 => SP1(CP1))); -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG20 (X : INTEGER := SS8'SIZE);  -- ERROR: USE OF
                        -- TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG21 (X : INTEGER := ARR51'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG22 (X : INTEGER := ARR52'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG23 (X : INTEGER := ARR53'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG24 (X : INTEGER := ARR54'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG25 (X : INTEGER := REC51'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG26 (X : INTEGER := REC52'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG27 (X : INTEGER := REC53'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.
          PROCEDURE GG28 (X : INTEGER := REC54'SIZE);  -- ERROR:
                 -- USE OF TYPE NAME ILLEGAL BEFORE FULL DECLARATION.


          TYPE P1 IS NEW INTEGER;
          TYPE LP2 IS NEW INTEGER;
          
          CP1  : CONSTANT P1  := 3;
          CLP2 : CONSTANT LP2 := 4;

     END PACK1;

     PACKAGE BODY PACK1 IS        -- NEEDED TO PROVIDE PROCEDURE BODIES.

          PROCEDURE G01 (X : INTEGER := P1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G02 (X : INTEGER := LP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G03 (X : P1 := SP1'(CP1)) IS
               BEGIN NULL; END;
          PROCEDURE G04 (X : INTEGER := SLP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G05 (X : INTEGER := ARR1_P1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G06 (X : INTEGER := ARR2_LP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G07 (X : INTEGER := ARR3_SP1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G08 (X : INTEGER := ARR4_SLP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G09 (X : REC1 := REC1'( C1 => CP1 )) IS
               BEGIN NULL; END;
          PROCEDURE G10 (X : INTEGER := REC2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G11 (X : INTEGER := REC3'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G12 (X : INTEGER := REC4'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G13 (X : INTEGER := SS1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G14 (X : INTEGER := SS2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G15 (X : INTEGER := SS3'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G16 (X : INTEGER := SS4'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G17 (X : SS5 := SS5'( C1 => CP1 )) IS
               BEGIN NULL; END;
          PROCEDURE G18 (X : INTEGER := SS6'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G19 (X : SS7 := SS7'(C3 => SP1(CP1))) IS
               BEGIN NULL; END;
          PROCEDURE G20 (X : INTEGER := SS8'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G21 (X : INTEGER := ARR51'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G22 (X : INTEGER := ARR52'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G23 (X : INTEGER := ARR53'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G24 (X : INTEGER := ARR54'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G25 (X : INTEGER := REC51'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G26 (X : INTEGER := REC52'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G27 (X : INTEGER := REC53'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE G28 (X : INTEGER := REC54'SIZE) IS
               BEGIN NULL; END;


          PROCEDURE GG01 (X : INTEGER := P1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG02 (X : INTEGER := LP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG03 (X : P1 := SP1(CP1)) IS
               BEGIN NULL; END;
          PROCEDURE GG04 (X : INTEGER := SLP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG05 (X : INTEGER := ARR1_P1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG06 (X : INTEGER := ARR2_LP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG07 (X : INTEGER := ARR3_SP1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG08 (X : INTEGER := ARR4_SLP2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG09 (X : INTEGER := REC1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG10 (X : INTEGER := REC2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG11 (X : REC3 := (C3 => SP1(CP1))) IS
               BEGIN NULL; END;
          PROCEDURE GG12 (X : INTEGER := REC4'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG13 (X : INTEGER := SS1'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG14 (X : INTEGER := SS2'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG15 (X : INTEGER := SS3'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG16 (X : INTEGER := SS4'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG17 (X : SS5 := SS5'( C1 => CP1 )) IS
               BEGIN NULL; END;
          PROCEDURE GG18 (X : INTEGER := SS6'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG19 (X : SS7 := SS7'(C3 => SP1(CP1))) IS
               BEGIN NULL; END;
          PROCEDURE GG20 (X : INTEGER := SS8'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG21 (X : INTEGER := ARR51'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG22 (X : INTEGER := ARR52'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG23 (X : INTEGER := ARR53'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG24 (X : INTEGER := ARR54'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG25 (X : INTEGER := REC51'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG26 (X : INTEGER := REC52'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG27 (X : INTEGER := REC53'SIZE) IS
               BEGIN NULL; END;
          PROCEDURE GG28 (X : INTEGER := REC54'SIZE) IS
               BEGIN NULL; END;


     END PACK1;

BEGIN

     NULL;

END B74103B2;
