-- B74204A.ADA

-- OBJECTIVE:
--     CHECK THAT REDECLARATION OF EQUALITY IS ILLEGAL AFTER THE FULL
--     DECLARATION OF A LIMITED PRIVATE TYPE IF THE FULL DECLARATION
--     DOES NOT ITSELF DECLARE A LIMITED TYPE.

-- HISTORY:
--     BCB 03/24/88  CREATED ORIGINAL TEST.

PROCEDURE B74204A IS

     PACKAGE P IS
          TYPE LP IS LIMITED PRIVATE;
     PRIVATE
          TYPE LP IS NEW INTEGER;
          FUNCTION "=" (L, R : LP) RETURN BOOLEAN;  -- ERROR: LP IS NOT
                                                    -- LIMITED TYPE.
     END P;

     PACKAGE BODY P IS
          FUNCTION "=" (L, R : LP) RETURN BOOLEAN IS
          BEGIN
               RETURN TRUE;
          END "=";
     BEGIN
          NULL;
     END P;

BEGIN
     NULL;
END B74204A;
