-- B74202D.ADA

-- OBJECTIVE:
--     WHEN THE DESIGNATED TYPE OF AN ACCESS TYPE IS LIMITED
--     PRIVATE, OPERATIONS FOR THE ACCESS TYPE WHICH DEPEND ON
--     CHARACTERISTICS OF THE FULL DECLARATION ARE NOT ACCESSIBLE
--     FROM OUTSIDE THE PACKAGE.

-- HISTORY:
--     BCB 07/28/88  CREATED ORIGINAL TEST.

PROCEDURE B74202D IS

     PACKAGE P IS
          TYPE ARR IS LIMITED PRIVATE;
          TYPE REC (D : INTEGER) IS LIMITED PRIVATE;
          TYPE ACC_ARR IS ACCESS ARR;
          TYPE ACC_REC IS ACCESS REC;
     PRIVATE
          TYPE ARR IS ARRAY(1..3) OF INTEGER;

          TYPE REC (D : INTEGER) IS RECORD
               COMP1 : INTEGER;
               COMP2 : BOOLEAN;
          END RECORD;
     END P;

     USE P;

     TYPE Z IS ARRAY(1..2) OF INTEGER;

     AR, CR : ACC_ARR := NEW ARR;

     BR : ACC_REC := NEW REC(0);

     V : INTEGER;

     W : Z;

BEGIN

     V := AR(1);                          -- ERROR: INDEXING.

     W := AR(1..2);                       -- ERROR: SLICING.

     IF AR'FIRST /= 1 THEN                -- ERROR: 'FIRST ATTRIBUTE.
          NULL;
     END IF;

     IF AR'LAST /= 3 THEN                 -- ERROR: 'LAST ATTRIBUTE.
          NULL;
     END IF;

     IF AR'LENGTH /= 3 THEN               -- ERROR: 'LENGTH ATTRIBUTE.
          NULL;
     END IF;

     IF CR IN AR'RANGE THEN               -- ERROR: 'RANGE ATTRIBUTE.
          NULL;
     END IF;

     V := BR.COMP1;                       -- ERROR: COMPONENT SELECTION.

END B74202D;
