-- B74203B.ADA

-- OBJECTIVE:
--     CHECK THAT NO BASIC OPERATIONS THAT DEPEND ON THE FULL
--     DECLARATION OF THE TYPE ARE AVAILABLE FOR LIMITED AND NON-LIMITED
--     PRIVATE TYPES.  INCLUDE TYPES WITH DISCRIMINANTS AND PRIVATE
--     TYPES WITH LIMITED COMPONENTS.

-- HISTORY:
--     BCB 07/15/88  CREATED ORIGINAL TEST.

PROCEDURE B74203B IS

     PACKAGE PP IS
          TYPE INT IS LIMITED PRIVATE;
          TYPE PARENT IS PRIVATE;
     PRIVATE
          TYPE INT IS RANGE 1 .. 100;
          TYPE PARENT IS ARRAY(1..3) OF INTEGER;
     END PP;

     USE PP;

     PACKAGE P IS
          TYPE PR IS PRIVATE;
          TYPE ARR1 IS LIMITED PRIVATE;
          TYPE ARR2 IS PRIVATE;
          TYPE REC (D : INTEGER) IS PRIVATE;
          TYPE ACC IS PRIVATE;
          TYPE TSK IS LIMITED PRIVATE;
          TYPE FLT IS LIMITED PRIVATE;
          TYPE FIX IS LIMITED PRIVATE;
          TYPE CHILD IS NEW PARENT;

          TASK TYPE T IS
               ENTRY ONE;
          END T;

          CONS : CONSTANT PR;

          CONS2 : CONSTANT ARR2;

          CONS3 : CONSTANT REC;

          CONS4 : CONSTANT ACC;

          CONS5 : CONSTANT FLT;

          CONS6 : CONSTANT FIX;

          PROCEDURE CHECK (V : ARR2);

          PROCEDURE INIT_FLT (ONE : IN OUT FLT; TWO : FLT);

          PROCEDURE INIT_FIX (ONE : IN OUT FIX; TWO : FIX);
     PRIVATE
          TYPE PR IS NEW INTEGER;

          TYPE ARR1 IS ARRAY(1..5) OF INT;

          TYPE ARR2 IS ARRAY(1..5) OF BOOLEAN;

          TYPE REC (D : INTEGER) IS RECORD
               COMP1 : INTEGER;
               COMP2 : BOOLEAN;
          END RECORD;

          TYPE ACC IS ACCESS INTEGER;

          TYPE TSK IS NEW T;

          TYPE FLT IS DIGITS 5 RANGE -100.0 .. 100.0;

          TYPE FIX IS DELTA 2.0**(-1) RANGE -100.0 .. 100.0;

          CONS : CONSTANT PR := 10;

          CONS2 : CONSTANT ARR2 := (TRUE,TRUE,TRUE,TRUE,TRUE);

          CONS3 : CONSTANT REC := (0,1,FALSE);

          CONS4 : CONSTANT ACC := NEW INTEGER'(0);

          CONS5 : CONSTANT FLT := 1.0;

          CONS6 : CONSTANT FIX := 1.0;
     END P;

     USE P;

     X1, X2, X3 : PR := CONS;
     BOOL : BOOLEAN := FALSE;
     VAL : INTEGER := 0;
     FVAL : FLOAT := 0.0;
     INT_VAR : INT;
     ST : STRING(1..10) := "1234567890";

     Y1, Y2, Y3 : ARR2 := CONS2;

     Z1 : REC(0) := CONS3;

     W1, W2 : ACC := CONS4;

     V1 : TSK;

     M1 : FLT;

     N1 : FIX;

     O1 : ARR1;

     PACKAGE BODY PP IS
          VAL : INTEGER;
          PRIV_VAR, PRIV_VAR2, RES : CHILD;
     BEGIN

          IF PRIV_VAR(1) THEN               -- ERROR: INDEXING.
               NULL;
          END IF;

          IF PRIV_VAR(1..2) THEN            -- ERROR: SLICING.
               NULL;
          END IF;

          IF VAL IN PRIV_VAR'RANGE THEN     -- ERROR: 'RANGE ATTRIBUTE
               NULL;                        --        NOT DEFINED.
          END IF;

          VAL := PRIV_VAR'LENGTH;           -- ERROR: 'LENGTH ATTRIBUTE
                                            --        NOT DEFINED.

          RES := PRIV_VAR & PRIV_VAR2;      -- ERROR: CATENATION.

     END PP;

     PACKAGE BODY P IS
          TASK BODY T IS
          BEGIN
               ACCEPT ONE;
          END T;

          PROCEDURE CHECK (V : ARR2) IS
          BEGIN
               NULL;
          END CHECK;

          PROCEDURE INIT_FLT (ONE : IN OUT FLT; TWO : FLT) IS
          BEGIN
               ONE := TWO;
          END INIT_FLT;

          PROCEDURE INIT_FIX (ONE : IN OUT FIX; TWO : FIX) IS
          BEGIN
               ONE := TWO;
          END INIT_FIX;
     END P;

BEGIN

     X1 := 10;         -- ERROR: LITERALS NOT DEFINED.

     X3 := X1 + X2;    -- ERROR: ADDITION OPERATOR NOT DEFINED.

     X3 := X1 - X2;    -- ERROR: SUBTRACTION OPERATOR NOT DEFINED.

     X3 := X1 * X2;    -- ERROR: MULTIPLICATION OPERATOR NOT DEFINED.

     X3 := X1 / X2;    -- ERROR: DIVISION OPERATOR NOT DEFINED.

     X3 := X1 ** 2;    -- ERROR: EXPONENTIATION OPERATOR NOT DEFINED.

     BOOL := X1 < X2;  -- ERROR: LESS THAN OPERATOR NOT DEFINED.

     BOOL := X1 > X2;  -- ERROR: GREATER THAN OPERATOR NOT DEFINED.

     BOOL := X1 <= X2; -- ERROR: LESS THAN OR EQUAL TO OPERATOR
                       --        NOT DEFINED.

     BOOL := X1 >= X2; -- ERROR: GREATER THAN OR EQUAL TO OPERATOR
                       --        NOT DEFINED.

     X3 := X1 MOD X2;  -- ERROR: MOD OPERATOR NOT DEFINED.

     X3 := X1 REM X2;  -- ERROR: REM OPERATOR NOT DEFINED.

     X3 := ABS(X1);    -- ERROR: ABS OPERATOR NOT DEFINED.

     X3 := P.PR'BASE'FIRST; -- ERROR: 'BASE ATTRIBUTE NOT DEFINED.

     X3 := P.PR'FIRST; -- ERROR: 'FIRST ATTRIBUTE NOT DEFINED.

     X3 := P.PR'LAST;  -- ERROR: 'LAST ATTRIBUTE NOT DEFINED.

     VAL := P.PR'WIDTH; -- ERROR: 'WIDTH ATTRIBUTE NOT DEFINED.

     VAL := P.PR'POS(X3); -- ERROR: 'POS ATTRIBUTE NOT DEFINED.

     X3 := P.PR'VAL(VAL); -- ERROR: 'VAL ATTRIBUTE NOT DEFINED.

     X3 := P.PR'SUCC(X2); -- ERROR: 'SUCC ATTRIBUTE NOT DEFINED.

     X3 := P.PR'PRED(X2); -- ERROR: 'PRED ATTRIBUTE NOT DEFINED.

     ST := P.PR'IMAGE(X3); -- ERROR: 'IMAGE ATTRIBUTE NOT DEFINED.

     X3 := P.PR'VALUE(ST); -- ERROR: 'VALUE ATTRIBUTE NOT DEFINED.

     CHECK ((TRUE,FALSE,TRUE,FALSE,TRUE));  -- ERROR: AGGREGATES.

     IF O1(2) THEN         -- ERROR: INDEXED COMPONENTS.
          NULL;
     END IF;

     IF O1(2..4) THEN      -- ERROR: SLICING.
          NULL;
     END IF;

     IF INT_VAR IN O1'RANGE THEN -- ERROR: 'RANGE ATTRIBUTE NOT DEFINED.
          NULL;
     END IF;

     VAL := O1'LENGTH;     -- ERROR: 'LENGTH ATTRIBUTE NOT DEFINED.

     Y3 := Y1 & Y2;        -- ERROR: CATENATION.

     Y3 := NOT Y1;         -- ERROR: NOT OPERATOR NOT DEFINED.

     Y3 := Y1 AND Y2;      -- ERROR: AND OPERATOR NOT DEFINED.

     Y3 := Y1 OR Y2;       -- ERROR: OR OPERATOR NOT DEFINED.

     Y3 := Y1 XOR Y2;      -- ERROR: XOR OPERATOR NOT DEFINED.

     VAL := Z1.COMP1;      -- ERROR: SELECTION OF RECORD COMPONENTS.

     W1 := NEW INTEGER'(0); -- ERROR: ALLOCATORS NOT DEFINED.

     W1 := NULL;            -- ERROR: NULL LITERAL NOT DEFINED.

     VAL := W2.ALL;         -- ERROR: SELECTED COMPONENT NOT DEFINED.

     BOOL := V1'CALLABLE;   -- ERROR: 'CALLABLE ATTRIBUTE NOT DEFINED.

     BOOL := V1'TERMINATED; -- ERROR: 'TERMINATED ATTRIBUTE NOT DEFINED.

     V1.ONE;                -- ERROR: SELECTION OF AN ENTRY.

     INIT_FLT (M1, CONS5);

     IF FLT (1.0) IN FLT THEN  -- ERROR: IMPLICIT CONVERSION.
          NULL;
     END IF;

     VAL := FLT'DIGITS;     -- ERROR: 'DIGITS ATTRIBUTE NOT DEFINED.

     VAL := FLT'MANTISSA;   -- ERROR: 'MANTISSA ATTRIBUTE NOT DEFINED.

     FVAL := FLT'EPSILON;   -- ERROR: 'EPSILON ATTRIBUTE NOT DEFINED.

     VAL := FLT'EMAX;       -- ERROR: 'EMAX ATTRIBUTE NOT DEFINED.

     FVAL := FLT'SMALL;     -- ERROR: 'SMALL ATTRIBUTE NOT DEFINED.

     FVAL := FLT'LARGE;     -- ERROR: 'LARGE ATTRIBUTE NOT DEFINED.

     VAL := FLT'SAFE_EMAX;  -- ERROR: 'SAFE_EMAX ATTRIBUTE NOT DEFINED.

     FVAL := FLT'SAFE_SMALL; -- ERROR: 'SAFE_SMALL ATTRIBUTE
                             --        NOT DEFINED.

     FVAL := FLT'SAFE_LARGE; -- ERROR: 'SAFE_LARGE ATTRIBUTE
                             --        NOT DEFINED.

     BOOL := FLT'MACHINE_ROUNDS; -- ERROR: 'MACHINE_ROUNDS ATTRIBUTE
                                 --        NOT DEFINED.

     BOOL := FLT'MACHINE_OVERFLOWS; -- ERROR: 'MACHINE_OVERFLOWS
                                    --        ATTRIBUTE NOT DEFINED.

     VAL := FLT'MACHINE_RADIX;   -- ERROR: 'MACHINE_RADIX ATTRIBUTE
                                 --        NOT DEFINED.

     VAL := FLT'MACHINE_MANTISSA; -- ERROR: 'MACHINE_MANTISSA ATTRIBUTE
                                  --        NOT DEFINED.

     VAL := FLT'MACHINE_EMAX;     -- ERROR: 'MACHINE_EMAX ATTRIBUTE
                                  --        NOT DEFINED.

     VAL := FLT'MACHINE_EMIN;     -- ERROR: 'MACHINE_EMIN ATTRIBUTE
                                  --        NOT DEFINED.

     INIT_FIX (N1, CONS6);

     FVAL := FIX'DELTA;       -- ERROR: 'DELTA ATTRIBUTE NOT DEFINED.

     VAL := FIX'FORE;         -- ERROR: 'FORE ATTRIBUTE NOT DEFINED.

     VAL := FIX'AFT;          -- ERROR: 'AFT ATTRIBUTE NOT DEFINED.

END B74203B;
