-- B74307B.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN EXPLICIT CONSTRAINT IS GIVEN IN THE SUBTYPE
--     INDICATION OF THE FULL DECLARATION OF A DEFERRED CONSTANT, THEN
--     IT MUST BE APPROPRIATE FOR THE TYPE MARK.

-- HISTORY:
--     BCB 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B74307B IS

     PACKAGE P IS
          TYPE T (D : INTEGER) IS PRIVATE;
          TYPE T1 IS PRIVATE;
          C : CONSTANT T;
          C1 : CONSTANT T1;
     PRIVATE
          TYPE T (D : INTEGER) IS RECORD
               NULL;
          END RECORD;

          TYPE T1 IS NEW T(3);

          C : CONSTANT T (D => 3);                     -- ERROR:

          C1 : CONSTANT T1(D => 3) := (D => 3);        -- ERROR:
     END P;

BEGIN
     NULL;
END B74307B;
