-- B74303A.ADA

-- OBJECTIVE:
--     CHECK THAT THE TYPE MARKS OF A DEFERRED CONSTANT DECLARATION AND
--     ITS CORRESPONDING FULL DECLARATION MUST DENOTE THE SAME TYPE OR
--     SUBTYPE DECLARATION, NOT JUST THE SAME TYPE OR SUBTYPE.

-- HISTORY:
--     BCB 03/14/88  CREATED ORIGINAL TEST.

PROCEDURE B74303A IS

     PACKAGE P IS
          TYPE T IS PRIVATE;
          TYPE U IS PRIVATE;
          SUBTYPE ST IS T;
          CT : CONSTANT T;
          CSTS : CONSTANT ST;
          CST : CONSTANT ST;
          UT : CONSTANT U;
     PRIVATE
          TYPE T IS RANGE 1 .. 100;
          TYPE U IS NEW T;
          CSTS : CONSTANT ST := 50;    -- OK.
          CT : CONSTANT ST := 5;       -- ERROR: DIFFERENT DECLARATIONS.
          CST : CONSTANT T := 50;      -- ERROR: DIFFERENT DECLARATIONS.
          UT : CONSTANT T := 50;       -- ERROR: TYPES DIFFERENT.
     END P;

BEGIN
     NULL;
END B74303A;
