-- B74401R.ADA

-- CHECK THAT IN A GENERIC SUBPROGRAM DECLARATION, A PARAMETER OF MODE
-- OUT MAY NOT BE OF A LIMITED TYPE IF:
--   (A) THE SUBPROGRAM AND PARAMETER TYPE DECLARATIONS OCCUR IN A
--       NESTED PACKAGE, WHERE THE FULL DECLARATION OF THE TYPE DEPENDS 
--       ON A LIMITED TYPE DECLARED IN THE OUTER PACKAGE;
--   (B) THE PARAMETER TYPE IS A COMPOSITE LIMITED TYPE WHOSE FULL
--       DECLARATION OCCURS BEFORE THAT OF ITS LIMITED COMPONENT TYPE,
--       EVEN IF THE FULL COMPONENT DECLARATION DECLARES A NON-LIMITED
--       TYPE. 

-- BHS 7/09/84
-- JBG 5/1/85

PROCEDURE B74401R IS

-- CASE A

     PACKAGE PACK1 IS
          TYPE LP1 IS LIMITED PRIVATE;

          PACKAGE NEST IS
               TYPE NLP2 IS LIMITED PRIVATE;

               GENERIC
               PROCEDURE P1 (L : OUT NLP2); 
          PRIVATE
               TYPE NLP2 IS ARRAY (1..2) OF LP1;    -- ERROR: LP1 
                                                    -- STILL LIMITED.
          END NEST; 
     PRIVATE
          TYPE LP1 IS RANGE 1..10;
     END PACK1;

     PACKAGE BODY PACK1 IS
          PACKAGE BODY NEST IS
               PROCEDURE P1(L : OUT NLP2) IS         -- OK HERE.
               BEGIN  NULL;  END P1;
          END NEST;
     END PACK1;


-- CASE B1 : RECORD TYPE

     PACKAGE PACK2 IS
          TYPE LP3 IS LIMITED PRIVATE;
          TYPE LP4 IS LIMITED PRIVATE;
          TYPE LP5 IS LIMITED PRIVATE;

          GENERIC
          PROCEDURE P2 (L : OUT LP3; M : LP3);

          GENERIC
          PROCEDURE P3 (X : OUT LP5; M : LP5);
     PRIVATE
          TYPE LP3 IS
               RECORD
                    C1 : LP4;        -- ERROR: LP4 STILL LIMITED.
               END RECORD;
          TYPE LP4 IS RANGE 1..10;
          TYPE LP5 IS 
               RECORD
                    C2 : LP4;      -- OK; NOT LIMITED.
               END RECORD;
     END PACK2;

     PACKAGE BODY PACK2 IS
          PROCEDURE P2(L : OUT LP3; M : LP3) IS    -- OK HERE.
          BEGIN  NULL;  END P2;

          PROCEDURE P3 (X : OUT LP5; M : LP5) IS
          BEGIN  NULL;  END P3;
     END PACK2;

-- CASE B2: ARRAY TYPE

     PACKAGE PACK3 IS
          TYPE LP3 IS LIMITED PRIVATE;
          TYPE LP4 IS LIMITED PRIVATE;
          TYPE LP5 IS LIMITED PRIVATE;

          GENERIC
          PROCEDURE P2 (L : OUT LP3; M : LP3);

          GENERIC
          PROCEDURE P3 (X : OUT LP5; M : LP5);
     PRIVATE
          TYPE LP3 IS
               ARRAY (1..5) OF LP4;  -- ERROR: LP4 STILL LIMITED.
          TYPE LP4 IS RANGE 1..10;
          TYPE LP5 IS 
               ARRAY (1..5) OF LP4;  -- OK; NOT LIMITED.
     END PACK3;

     PACKAGE BODY PACK3 IS
          PROCEDURE P2(L : OUT LP3; M : LP3) IS    -- OK HERE.
          BEGIN  NULL;  END P2;

          PROCEDURE P3 (X : OUT LP5; M : LP5) IS
          BEGIN  NULL;  END P3;
     END PACK3;

BEGIN

     NULL;

END B74401R;
