-- B74401B.ADA

-- CHECK THAT IN A SUBPROGRAM DECLARATION, A PARAMETER OF MODE OUT MAY
-- NOT BE OF A LIMITED TYPE IF:

--   B) IT IS A LIMITED PRIVATE TYPE AND THE DECLARATION APPEARS IN THE
--      PRIVATE PART OR BODY OF THE PACKAGE DECLARING THE LIMITED
--      PRIVATE TYPE, OR OUTSIDE THE PACKAGE DECLARING THE TYPE;

-- JBG 9/23/83
-- BHS 7/10/84
-- JRK 12/4/84
-- JBG 5/1/85

PROCEDURE B74401B IS

     PACKAGE P IS
          TYPE LP IS LIMITED PRIVATE;
          TASK TYPE TSK;
          TYPE ARR_LP IS ARRAY(1..2) OF P.LP;
          TYPE REC_LP IS
               RECORD
                    LP : P.LP;
               END RECORD;
     PRIVATE
          TYPE LP IS NEW INTEGER;
     END P;

     PACKAGE BODY P IS
          TASK BODY TSK IS
          BEGIN
               NULL;
          END TSK;
     END P;

     PACKAGE CASE_B IS
          TYPE LP2 IS LIMITED PRIVATE;
          TYPE LP3 IS LIMITED PRIVATE;
     PRIVATE
          PROCEDURE P12 (X : OUT LP2);       -- ERROR: NOT VISIBLE PART.
          TYPE LP2 IS NEW INTEGER;
          TYPE LP3 IS NEW P.LP;
     END CASE_B;

     PACKAGE BODY CASE_B IS

          PROCEDURE P12 (X : OUT LP2) IS     -- ERR MSG OPTIONAL.
          BEGIN
               NULL;
          END P12;

          PROCEDURE P13 (X : OUT LP3) IS     -- ERROR: NOT VISIBLE PART.
          BEGIN
               NULL;
          END P13;

     END CASE_B;

BEGIN
     NULL;
END B74401B;
