-- B83024F0M.ADA

-- OBJECTIVE:
--     IF A DECLARATION IN THE DECLARATIVE REGION OF A GENERIC PACKAGE
--     HIDES AN OUTER DECLARATION OF A HOMOGRAPH, THEN CHECK THAT A USE
--     OF THE COMMON IDENTIFIER WHICH WOULD BE A LEGAL REFERENCE TO THE
--     OUTER DECLARATION MUST BE REJECTED IF IT IS ILLEGAL AS A
--     REFERENCE TO THE INNER, IF THE GENERIC PACKAGE BODY IS SEPARATELY
--     COMPILED, BUT NOT AS A SUBUNIT.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE TO IMPLEMENTATIONS WHICH SUPPORT SEPARATE
--     COMPILATION OF GENERIC SPECIFICATIONS AND BODIES.

-- SEPARATE FILES ARE:
--     B83024F0M.ADA - (THIS FILE) MAIN PROGRAM.
--     B83024F1.ADA -- PACKAGE BODIES.

-- HISTORY:
--     BCB 08/30/88  CREATED ORIGINAL TEST.

GENERIC
     TYPE T IS PRIVATE;
     X : T;
FUNCTION B83024F_GEN_FUN RETURN T;

FUNCTION B83024F_GEN_FUN RETURN T IS
BEGIN
     RETURN X;
END B83024F_GEN_FUN;

WITH B83024F_GEN_FUN;
PACKAGE B83024F_P1 IS
     INT : INTEGER := 1;
     FLO : FLOAT := 6.25;

     FUNCTION F IS NEW B83024F_GEN_FUN (INTEGER, INT);
     FUNCTION F IS NEW B83024F_GEN_FUN (FLOAT, FLO);

     GENERIC
     PACKAGE B83024F_PACK1 IS
          F : FLOAT := 6.25;
     END B83024F_PACK1;
END B83024F_P1;

PACKAGE B83024F_P2 IS
     A : INTEGER := 2;

     PROCEDURE P;

     GENERIC
          X : IN INTEGER := A;
          A : IN OUT FLOAT;
     PACKAGE B83024F_PACK2 IS
          TYPE P IS NEW INTEGER;
     END B83024F_PACK2;
END B83024F_P2;

PACKAGE B83024F_P3 IS
     A : FLOAT := 1.0;

     GENERIC
          X : IN OUT INTEGER;
     PACKAGE B83024F_PACK3 IS
          A : INTEGER := 3;
     END B83024F_PACK3;

     B : FLOAT := A;
END B83024F_P3;

PROCEDURE B83024F0M IS
BEGIN
     NULL;
END B83024F0M;
