-- B83029B.ADA

-- OBJECTIVE:
--     IF A LOOP PARAMETER HIDES AN OUTER DECLARATION OF A HOMOGRAPH,
--     THEN CHECK THAT A USE OF THE COMMON IDENTIFIER WHICH WOULD BE A
--     LEGAL REFERENCE TO THE OUTER DECLARATION MUST BE REJECTED IF IT
--     IS ILLEGAL AS A REFERENCE TO THE INNER.

-- HISTORY:
--     BCB 09/06/88  CREATED ORIGINAL TEST.

PROCEDURE B83029B IS

     GENERIC
          TYPE T IS PRIVATE;
          X : T;
     FUNCTION GEN_FUN RETURN T;

     FUNCTION GEN_FUN RETURN T IS
     BEGIN
          RETURN X;
     END GEN_FUN;

BEGIN

     ONE:
     DECLARE
          INT : INTEGER := 1;
          FLO : FLOAT := 6.25;

          Y : FLOAT;

          FUNCTION F IS NEW GEN_FUN (INTEGER, INT);

          FUNCTION F IS NEW GEN_FUN (FLOAT, FLO);

     BEGIN  -- ONE
          FOR F IN 0 .. 1 LOOP
               Y := F;                           -- ERROR:
          END LOOP;
     END ONE;

END B83029B;
