-- B83031D.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN IMPLICIT DECLARATION OF A PREDEFINED OPERATOR
--     IS HIDDEN BY A GENERIC INSTANTIATION, THEN A USE OF THE COMMON
--     IDENTIFIER OF HOMOGRAPHS MUST BE REJECTED IF IT WOULD BE LEGAL
--     FOR THE HIDDEN IMPLICIT DECLARATION BUT ILLEGAL FOR THE VISIBLE
--     EXPLICIT DECLARATION.

-- HISTORY:
--     BCB 09/19/88  CREATED ORIGINAL TEST.

PROCEDURE B83031D IS

BEGIN
     DECLARE             -- CHECK SUBPROGRAM DECLARATIONS OF OPERATORS
          PACKAGE P IS
               TYPE INT IS RANGE -20 .. 20;

               M : INT := 5;

               GENERIC
                    TYPE X IS RANGE <>;
               FUNCTION GEN_FUN (L, R : X) RETURN X;
          END P;
          USE P;

          PACKAGE BODY P IS
               FUNCTION GEN_FUN (L, R : X) RETURN X IS
               BEGIN
                    RETURN L / R;
               END GEN_FUN;

               FUNCTION "*" IS NEW GEN_FUN (INT);
          BEGIN
               M := "*" (LEFT => 2, RIGHT => 2);       -- ERROR:
          END P;
     BEGIN
          NULL;
     END;

END B83031D;
