-- B83003B2.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXPLICIT DECLARATION IN THE DECLARATIVE PART OF A
--     TASK'S BODY CANNOT HAVE THE SAME IDENTIFIER AS THAT OF A SINGLE
--     ENTRY OR AN ENTRY FAMILY.
--     THIS TEST CHECKS THE CASE WHERE THE TASK SPECIFICATION AND BODY
--     ARE IN SEPARATE COMPILATIONS (TASKS BODIES AS SUBUNITS).

-- SEPARATE FILES:
--     B83003B0M     CONTAINS THE DECLARATIONS OF THE TASKS AND THE
--                   TASK BODY STUBS.
--
--     B83003B1      CONTAINS SEPARATE TASK BODIES.
--
--     B83003B2      CONTAINS SEPARATE TASK BODIES.

-- HISTORY:
--     VCL  02/04/88  CREATED ORIGINAL TEST.

-- MULTIPLE TASKS ARE USED SO THAT ONLY ONE DECLARATION WHICH REQUIRES
-- A BODY (TASK AND GENERIC UNITS) IS GIVEN IN EACH TASK.

SEPARATE (B83003B0M)
TASK BODY TSK3 IS
     GENERIC                                       -- ERROR: HOMOGRAPH.
     FUNCTION E10 RETURN STRING;

-- BODY FOR THE ABOVE HOMOGRAPH.

     FUNCTION E10 RETURN STRING IS              -- OPTIONAL ERR MESSAGE:
     BEGIN                                      --  BODY OF AN INVALID
          RETURN "E10";                         --  GENERIC FUNCTION.
     END E10;
BEGIN
     NULL;
END TSK3;

SEPARATE (B83003B0M)
TASK BODY TSK4 IS
     GENERIC                                       -- ERROR: HOMOGRAPH.
     PROCEDURE E11;

     GENERIC                                       -- ERROR: HOMOGRAPH.
     PACKAGE E12 IS END E12;

     -- BODY FOR THE ABOVE HOMOGRAPH.

     PROCEDURE E11 IS                           -- OPTIONAL ERR MESSAGE:
     BEGIN                                      --  BODY OF AN INVALID
          NULL;                                 --  GENERIC PROCEDURE.
     END E11;
BEGIN
     NULL;
END TSK4;
