-- B83022H2.ADA

-- OBJECTIVE:
--     IF A DECLARATION IN THE DECLARATIVE REGION OF A SUBPROGRAM HIDES
--     AN OUTER DECLARATION OF A HOMOGRAPH, THEN CHECK THAT A USE OF THE
--     COMMON IDENTIFIER WHICH WOULD BE A LEGAL REFERENCE TO THE OUTER
--     DECLARATION MUST BE REJECTED IF IT IS ILLEGAL AS A REFERENCE TO
--     THE INNER, IF THE SUBPROGRAM BODY IS SEPARATELY COMPILED AS A
--     SUBUNIT.

-- HISTORY:
--     BCB 08/26/88  CREATED ORIGINAL TEST.

SEPARATE (B83022H1)
PROCEDURE INNER (X : INTEGER := F;          -- OPTIONAL ERROR MESSAGE:
                 F : FLOAT) IS
                 Y : INTEGER;
BEGIN
     Y := INTEGER(F);
     IF X /= Y THEN
          NULL;
     END IF;
END INNER;

SEPARATE (B83022H0M)
PROCEDURE INNER2 (X : INTEGER := F) IS
     F : FLOAT;
     Y : INTEGER;
BEGIN
     Y := F;                                -- ERROR:
     IF X /= Y THEN
          NULL;
     END IF;
END INNER2;
