-- B83004B0M.ADA

-- OBJECTIVE:
--     CHECK THAT HOMOGRAPHS ARE FORBIDDEN IN ANY OF THESE COMBINATIONS
--     OF PARTS OF A GENERIC PACKAGE, WHEN THE BODY IS SEPARATELY
--     COMPILED:
--          A) VISIBLE-BODY.
--          B) PRIVATE-BODY.
--          C) BODY-BODY.

-- SEPARATE FILES ARE:
--     B83004B0M   MAIN PROCEDURE AND PACKAGE SPECIFICATIONS.
--     B83004B1    PACKAGE BODIES.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE TO IMPLEMENTATIONS THAT SUPPORT
--     SEPARATE COMPILATION OF GENERIC SPECIFICATIONS AND BODIES.

-- HISTORY:
--     TBN 07/25/88  CREATED ORIGINAL TEST.

-- CASE A:
GENERIC
PACKAGE B83004B_PACK1 IS
     VAR1 : INTEGER := 1;
     CON1 : CONSTANT STRING := "HELLO";
     EXC1 : EXCEPTION;

     TYPE INT IS NEW INTEGER;
     SUBTYPE INT_SUBTYPE IS INTEGER RANGE 1..10;

     PACKAGE P IS
          X : INTEGER := 0;
     END P;

     TASK T;

     GENERIC
     FUNCTION FUN RETURN INTEGER;

     PROCEDURE PROC1 (X : IN INTEGER; Y : OUT BOOLEAN);
END B83004B_PACK1;


-- CASE B:
GENERIC
PACKAGE B83004B_PACK2 IS
     TYPE INT2 IS PRIVATE;
PRIVATE
     VAR2 : INTEGER := 2;
     CON2 : CONSTANT STRING := "HELLO";
     EXC2 : EXCEPTION;

     TYPE INT2 IS NEW INTEGER;
     SUBTYPE INT_SUBTYPE2 IS INTEGER RANGE 2..20;

     PACKAGE P2 IS
          X : INTEGER := 0;
     END P2;

     TASK T2;

     GENERIC
     FUNCTION FUN2 RETURN INTEGER;

     PROCEDURE PROC2 (X : IN INTEGER; Y : OUT BOOLEAN);
END B83004B_PACK2;


-- CASE C:
GENERIC
     TYPE FUNNY_TYPE IS PRIVATE;
PACKAGE B83004B_PACK3 IS
     NEW_VAR : BOOLEAN;
     TYPE ARR1 IS ARRAY (1..50) OF CHARACTER;
     TYPE ARR2 IS ARRAY (1..25) OF ARR1;
     TYPE ARR3 IS ARRAY (1..20) OF ARR2;
     TYPE ARR4 IS ARRAY (1..15) OF ARR3;
     TYPE ARR5 IS ARRAY (1..10) OF ARR4;
     TYPE ARR6 IS ARRAY (1.. 5) OF ARR5;
     ARRAY_OBJECT : ARR6;

     FUNCTION FUNNY (A : FUNNY_TYPE) RETURN FUNNY_TYPE;

END B83004B_PACK3;

PROCEDURE B83004B0M IS
BEGIN
     NULL;
END B83004B0M;
