-- B83025D.ADA

-- OBJECTIVE:
--     IF A DECLARATION IN THE DECLARATIVE REGION OF A GENERIC
--     SUBPROGRAM HIDES AN OUTER DECLARATION OF A HOMOGRAPH, THEN CHECK
--     THAT A USE OF THE COMMON IDENTIFIER WHICH WOULD BE A LEGAL
--     REFERENCE TO THE OUTER DECLARATION MUST BE REJECTED IF IT IS
--     ILLEGAL AS A REFERENCE TO THE INNER, IF THE GENERIC SUBPROGRAM
--     BODY IS COMPILED AS A SUBUNIT IN THE SAME COMPILATION.

-- HISTORY:
--     BCB 08/31/88  CREATED ORIGINAL TEST.

PROCEDURE B83025D IS

     GENERIC
          TYPE T IS PRIVATE;
          X : T;
     FUNCTION GEN_FUN RETURN T;

     INT : INTEGER := 1;
     FLO : FLOAT := 6.25;

     A : FLOAT := 2.0;
     B : FLOAT := A;

     FUNCTION F IS NEW GEN_FUN (INTEGER, INT);

     GENERIC
     PROCEDURE INNER1 (X : INTEGER := F;
                       F : FLOAT);

     FUNCTION F IS NEW GEN_FUN (FLOAT, FLO);

     PROCEDURE INNER1 (X : INTEGER := F;               -- ERROR:
                       F : FLOAT) IS SEPARATE;

     GENERIC
     PROCEDURE INNER2 (X : INTEGER := F);

     PROCEDURE INNER2 (X : INTEGER := F) IS SEPARATE;

     GENERIC
          A : INTEGER := 3;
     FUNCTION INNER3 (X : INTEGER) RETURN INTEGER;

     FUNCTION INNER3 (X : INTEGER) RETURN INTEGER IS SEPARATE;

     FUNCTION GEN_FUN RETURN T IS
     BEGIN
          RETURN X;
     END GEN_FUN;

BEGIN
     NULL;
END B83025D;

SEPARATE (B83025D)
PROCEDURE INNER1 (X : INTEGER := F;         -- OPTIONAL ERROR MESSAGE:
                  F : FLOAT) IS
     Y : INTEGER;
BEGIN
     Y := INTEGER(F);
     IF X /= Y THEN
          NULL;
     END IF;
END INNER1;

SEPARATE (B83025D)
PROCEDURE INNER2 (X : INTEGER := F) IS
     F : FLOAT;
     Y : INTEGER;
BEGIN
     Y := F;                                          -- ERROR:
     IF X /= Y THEN
          NULL;
     END IF;
END INNER2;

SEPARATE (B83025D)
FUNCTION INNER3 (X : INTEGER) RETURN INTEGER IS
     C : FLOAT := A;                                  -- ERROR:
BEGIN
     RETURN 0;
END INNER3;
