-- B83012C.ADA

-- OBJECTIVE:
--     CHECK THAT WITHIN A SUBPROGRAM INSTANTIATION NO DECLARATION OF
--     THE DESIGNATOR OF THE DECLARED SUBPROGRAM IS VISIBLE, EITHER
--     DIRECTLY OR BY SELECTION.  THIS TEST CHECKS THE CASE IN WHICH
--     SUBPROGRAM NAMES ARE IDENTIFIERS.

-- HISTORY:
--     JET 07/26/88  CREATED ORIGINAL TEST.

PROCEDURE B83012C IS

     PACKAGE PACK IS
          TYPE PROC1 IS RANGE -100..100;
          PROC2 : INTEGER := 0;
          TYPE FUNK7 IS NEW INTEGER;
     END PACK;

     USE PACK;

     TYPE REC IS RECORD
          PROC3 : INTEGER;
          PROC4 : INTEGER;
     END RECORD;

     R : REC := (0,0);

     FUNCTION FUNK (PROC5 : INTEGER) RETURN INTEGER;

     SUBTYPE PROC9 IS INTEGER;

     GENERIC
          TYPE T IS RANGE <>;
     PROCEDURE GENA;

     GENERIC
          I : INTEGER;
     PROCEDURE GENB;

     GENERIC
          R : REC;
     PROCEDURE GENC;

     GENERIC
          PROC6 : INTEGER;
     PROCEDURE GEND;

     GENERIC
          TYPE T IS RANGE <>;
     FUNCTION GENE RETURN T;

     PACKAGE PROC8 IS
          TYPE T IS RANGE -100 .. 100;
     END PROC8;

     PROCEDURE GENA IS BEGIN NULL; END;
     PROCEDURE GENB IS BEGIN NULL; END;
     PROCEDURE GENC IS BEGIN NULL; END;
     PROCEDURE GEND IS BEGIN NULL; END;
     FUNCTION GENE RETURN T IS BEGIN RETURN 0; END;

     FUNCTION FUNK(PROC5 : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN PROC5;
     END FUNK;

     PROCEDURE PROC1 IS NEW GENA(PROC1);
                                           -- ERROR: PROC1 UNDENOTABLE.
     PROCEDURE PROC2 IS NEW GENB(PACK.PROC2);
                                           -- ERROR: PROC2 UNDENOTABLE.
     PROCEDURE PROC3 IS NEW GENB(R.PROC3);
                                           -- ERROR: PROC3 UNDENOTABLE.
     PROCEDURE PROC4 IS NEW GENC((1, PROC4 => 1));
                                           -- ERROR: PROC4 UNDENOTABLE.
     PROCEDURE PROC5 IS NEW GENB(FUNK(PROC5 => 0));
                                           -- ERROR: PROC5 UNDENOTABLE.
     PROCEDURE PROC6 IS NEW GEND(PROC6 => 1);
                                           -- ERROR: PROC6 UNDENOTABLE.
     FUNCTION FUNK7 IS NEW GENE(PACK.FUNK7);
                                           -- ERROR: FUNK7 UNDENOTABLE.
     PACKAGE BODY PROC8 IS
          PROCEDURE PROC8 IS NEW GENA(PROC8.T);
                                           -- ERROR: PROC8 UNDENOTABLE.
          PROCEDURE PROC9 IS NEW GENA(PROC9);
                                           -- ERROR: PROC9 UNDENOTABLE.
     END PROC8;

BEGIN
     NULL;
END B83012C;
