-- B83031F.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN IMPLICIT DECLARATION OF A PREDEFINED OPERATOR IS
--     HIDDEN BY A GENERIC FORMAL SUBPROGRAM DECLARATION, THEN A USE OF
--     THE COMMON IDENTIFIER OF HOMOGRAPHS MUST BE REJECTED IF IT WOULD
--     BE LEGAL FOR THE HIDDEN IMPLICIT DECLARATION BUT ILLEGAL FOR THE
--     VISIBLE EXPLICIT DECLARATION.

-- HISTORY:
--     BCB 09/19/88  CREATED ORIGINAL TEST.

PROCEDURE B83031F IS

BEGIN
     DECLARE
          TYPE INT IS RANGE -20 .. 20;

          N : INT := 5;

          GENERIC
               WITH FUNCTION "*" (L, R : INT) RETURN INT;
          PACKAGE P IS
          END P;

          PACKAGE BODY P IS
          BEGIN
               N := "*" (LEFT => 2, RIGHT => 2);       -- ERROR:
          END P;
     BEGIN
          NULL;
     END;

END B83031F;
