-- B83022H0M.ADA

-- OBJECTIVE:
--     IF A DECLARATION IN THE DECLARATIVE REGION OF A SUBPROGRAM HIDES
--     AN OUTER DECLARATION OF A HOMOGRAPH, THEN CHECK THAT A USE OF THE
--     COMMON IDENTIFIER WHICH WOULD BE A LEGAL REFERENCE TO THE OUTER
--     DECLARATION MUST BE REJECTED IF IT IS ILLEGAL AS A REFERENCE TO
--     THE INNER, IF THE SUBPROGRAM BODY IS SEPARATELY COMPILED AS A
--     SUBUNIT.

-- SEPARATE FILES ARE:
--     B83022H0M.ADA - (THIS FILE) MAIN PROGRAM.
--     B83022H1.ADA -- SUBPROGRAM SPECIFICATION.
--     B83022H2.ADA -- SUBPROGRAM BODIES.

-- HISTORY:
--     BCB 08/26/88  CREATED ORIGINAL TEST.

PROCEDURE B83022H0M IS

     GENERIC
          TYPE T IS PRIVATE;
          X : T;
     FUNCTION GEN_FUN RETURN T;

     INT : INTEGER := 1;
     FLO : FLOAT := 6.25;

     FUNCTION GEN_FUN RETURN T IS
     BEGIN
          RETURN X;
     END GEN_FUN;

     FUNCTION F IS NEW GEN_FUN (INTEGER, INT);

     FUNCTION F IS NEW GEN_FUN (FLOAT, FLO);

     PROCEDURE INNER2 (X : INTEGER := F) IS SEPARATE;

BEGIN
     NULL;
END B83022H0M;
