-- B83024F1.ADA

-- OBJECTIVE:
--     IF A DECLARATION IN THE DECLARATIVE REGION OF A GENERIC PACKAGE
--     HIDES AN OUTER DECLARATION OF A HOMOGRAPH, THEN CHECK THAT A USE
--     OF THE COMMON IDENTIFIER WHICH WOULD BE A LEGAL REFERENCE TO THE
--     OUTER DECLARATION MUST BE REJECTED IF IT IS ILLEGAL AS A
--     REFERENCE TO THE INNER, IF THE GENERIC PACKAGE BODY IS SEPARATELY
--     COMPILED, BUT NOT AS A SUBUNIT.

-- HISTORY:
--     BCB 08/30/88  CREATED ORIGINAL TEST.

PACKAGE BODY B83024F_P1 IS
     PACKAGE BODY B83024F_PACK1 IS
          X : INTEGER := F;                                 -- ERROR:
     BEGIN
          NULL;
     END B83024F_PACK1;
END B83024F_P1;

PACKAGE BODY B83024F_P2 IS
     PROCEDURE P IS
     BEGIN
          NULL;
     END P;

     PACKAGE BODY B83024F_PACK2 IS
          C : INTEGER := A;                                 -- ERROR:
     BEGIN
          P;                                                -- ERROR:
     END B83024F_PACK2;
END B83024F_P2;

PACKAGE BODY B83024F_P3 IS
     PACKAGE BODY B83024F_PACK3 IS
          C : FLOAT := A;                                   -- ERROR:
     BEGIN
          NULL;
     END B83024F_PACK3;
END B83024F_P3;
