-- B83032B.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN IMPLICIT DECLARATION OF A PREDEFINED OPERATOR IS
--     HIDDEN BY A DERIVED SUBPROGRAM HOMOGRAPH, THEN A USE OF THE
--     COMMON IDENTIFIER OF THE HOMOGRAPHS MUST BE REJECTED IF IT WOULD
--     BE A LEGAL REFERENCE TO THE IMPLICIT DECLARATION BUT ILLEGAL FOR
--     THE DERIVED SUBPROGRAM.

-- HISTORY:
--     BCB 09/19/88  CREATED ORIGINAL TEST.

PROCEDURE B83032B IS

BEGIN
     DECLARE             -- CHECK PREDEFINED OPERATOR.
          PACKAGE P IS
               TYPE INT IS RANGE -20 .. 20;

               FUNCTION "ABS" (X : INT) RETURN INT;
          END P;
          USE P;

          TYPE NINT IS NEW INT;

          I2 : NINT := -5;

          PACKAGE BODY P IS
               I1 : NINT := 5;

               FUNCTION "ABS" (X : INT) RETURN INT IS
               BEGIN
                    RETURN INT (- (ABS (INTEGER (X))));
               END "ABS";
          BEGIN
               I1 := "ABS" (RIGHT => -10);             -- ERROR:
          END P;
     BEGIN
          I2 := "ABS" (RIGHT => 10);                   -- ERROR:
     END;

END B83032B;
