-- B83006B.ADA

-- OBJECTIVE:
--     CHECK THAT THE DISCRIMINANTS IN A GENERIC FORMAL TYPE DECLARATION
--     CANNOT HAVE THE SAME IDENTIFIER.

-- HISTORY:
--     TBN 07/28/88  CREATED ORIGINAL TEST.

PROCEDURE B83006B IS

     TYPE ENUM IS (ONE, TWO, THREE);

     TYPE SHORT IS NEW INTEGER RANGE 1..10;

     GENERIC
          TYPE REC1 (X : INTEGER) IS PRIVATE;
          TYPE REC2 (A : INTEGER; A : INTEGER) IS PRIVATE;     -- ERROR:
          TYPE REC3 (B : INTEGER; B : BOOLEAN) IS PRIVATE;     -- ERROR:
          TYPE REC4 (C : INTEGER; C : CHARACTER) IS PRIVATE;   -- ERROR:
          TYPE REC5 (D : INTEGER; D : ENUM) IS PRIVATE;        -- ERROR:
          TYPE REC7 (F : INTEGER; F : SHORT) IS PRIVATE;       -- ERROR:
     PACKAGE PACK1 IS
          A : REC1(3);
     END PACK1;

     GENERIC
          TYPE REC1 (X : CHARACTER) IS PRIVATE;
          TYPE REC2 (A : CHARACTER; A : CHARACTER) IS PRIVATE; -- ERROR:
          TYPE REC3 (B : BOOLEAN; B : BOOLEAN) IS PRIVATE;     -- ERROR:
          TYPE REC4 (C : ENUM; A : INTEGER; C : CHARACTER) IS  -- ERROR:
                PRIVATE;
          TYPE REC5 (D : ENUM; D : ENUM) IS PRIVATE;           -- ERROR:
          TYPE REC7 (F : SHORT; F : SHORT) IS PRIVATE;         -- ERROR:
     PROCEDURE PROC1;

     GENERIC
          TYPE REC1 (X : BOOLEAN) IS LIMITED PRIVATE;
          TYPE REC2 (A, B : INTEGER; A : CHARACTER) IS         -- ERROR:
               LIMITED PRIVATE;
          TYPE REC3 (B : BOOLEAN; A : INTEGER; B : ENUM) IS    -- ERROR:
               LIMITED PRIVATE;
          TYPE REC5 (D : ENUM; C : INTEGER; D : CHARACTER) IS  -- ERROR:
               PRIVATE;
          TYPE REC6 (E : BOOLEAN; D : INTEGER; E : SHORT) IS   -- ERROR:
               PRIVATE;
          TYPE REC7 (F : SHORT; E : CHARACTER; F : SHORT) IS   -- ERROR:
               LIMITED PRIVATE;
     FUNCTION FUNC1 RETURN INTEGER;


     PROCEDURE PROC1 IS
     BEGIN
          NULL;
     END PROC1;

     FUNCTION FUNC1 RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END FUNC1;

BEGIN
     NULL;
END B83006B;
