-- B83A01B.ADA


-- CHECK THAT A STATEMENT LABEL INSIDE AN EXCEPTION HANDLER CANNOT BE
--     THE SAME AS A STATEMENT LABEL OUTSIDE IT.


-- RM 02/05/80


PROCEDURE  B83A01B  IS

BEGIN

     << LAB_OUTSIDE_INHANDLER >>              NULL ;

     BEGIN

          << LAB_INBLOCK_INHANDLER >>         NULL ;

          FOR  I  IN  INTEGER  LOOP
               << LAB_INBLOCKLOOP_INHANDLER>> NULL ;
          END LOOP;

     END ;

     FOR  I  IN  INTEGER  LOOP
          << LAB_INLOOP_INHANDLER >>          NULL ;
     END LOOP;

EXCEPTION

     WHEN  CONSTRAINT_ERROR  =>
          << LAB_INHANDLER_INHANDLER >>       NULL ;
          << LAB_OUTSIDE_INHANDLER >>         NULL ;  -- ERROR: DUPLIC.
     WHEN  NUMERIC_ERROR     =>
          << LAB_INBLOCK_INHANDLER >>         NULL ;  -- ERROR: DUPLIC.
     WHEN  PROGRAM_ERROR     =>
          << LAB_INBLOCKLOOP_INHANDLER>>      NULL ;  -- ERROR: DUPLIC.
     WHEN  STORAGE_ERROR     =>
          << LAB_INLOOP_INHANDLER >>          NULL ;  -- ERROR: DUPLIC.
     WHEN  TASKING_ERROR     =>
          << LAB_INHANDLER_INHANDLER >>       NULL ;  -- ERROR: DUPLIC.

END B83A01B ;
