-- B83A01A.ADA


-- CHECK THAT A STATEMENT LABEL INSIDE A LOOP OR BLOCK BODY CANNOT BE 
--    THE SAME AS A STATEMENT LABEL OUTSIDE THESE CONSTRUCTS WHEN ALL 
--    LABELS ARE INSIDE THE SAME SUBPROGRAM.

-- RM 02/05/80


PROCEDURE  B83A01A  IS

BEGIN

     << LAB_OUTSIDE_INBLOCK >>                NULL ;
     << LAB_OUTSIDE_INLOOP >>                 NULL ;
     << LAB_OUTSIDE_INBLOCKLOOP >>            NULL ;

     BEGIN

          << LAB_OUTSIDE_INBLOCK >>           NULL ;  -- ERROR: DUPLIC.
          << LAB_INBLOCK_INLOOP >>            NULL ;
          << LAB_INBLOCK_INBLOCKLOOP >>       NULL ;

          FOR  I  IN  INTEGER  LOOP
               << LAB_OUTSIDE_INBLOCKLOOP >>  NULL ;  -- ERROR: DUPLIC.
               << LAB_INBLOCK_INBLOCKLOOP >>  NULL ;  -- ERROR: DUPLIC.
               << LAB_INLOOP_INBLOCKLOOP >>   NULL ;
          END LOOP;

     END ;

     FOR  I  IN  INTEGER  LOOP
          << LAB_OUTSIDE_INLOOP >>            NULL ;  -- ERROR: DUPLIC.
          << LAB_INBLOCK_INLOOP >>            NULL ;  -- ERROR: DUPLIC.
          << LAB_INLOOP_INBLOCKLOOP >>        NULL ;  -- ERROR: DUPLIC.
     END LOOP;


END B83A01A ;
