-- B83B01A.ADA


-- CHECK THAT THE VALUE OF A LOOP PARAMETER CAN NOT BE ACCESSED
--    FROM OUTSIDE THE BODY OF THE LOOP.


--    RM  4/20/80
--    ABW 6/17/82


PROCEDURE  B83B01A  IS

     I : INTEGER ;

BEGIN

     FOR  LOOP_PAR  IN  1 .. 10  LOOP
          NULL;
     END LOOP;

     I := LOOP_PAR ; -- ERROR: 'LOOP_PAR' UNKNOWN OUTSIDE THE LOOP

END B83B01A ;
