-- B83E01A.ADA

-- OBJECTIVE:
--     CHECK THAT NON-GENERIC SUBPROGRAM SPECIFICATIONS CANNOT DECLARE
--     DUPLICATE FORMAL PARAMETERS. INCLUDE DECLARATIONS WITH LATER
--     BODIES, BODIES WITHOUT EARLIER DECLARATIONS, STUBS, AND RENAMING
--     DECLARATIONS.

-- HISTORY:
--     DHH 09/08/88  CREATED ORIGINAL TEST.

PROCEDURE B83E01A IS

     FUNCTION F(PARAM1 : BOOLEAN;
                PARAM1 : INTEGER) RETURN BOOLEAN;   -- ERROR: DUPLICATE.

     PROCEDURE P(PARAM1 : IN BOOLEAN;
                 PARAM1 : OUT INTEGER);             -- ERROR: DUPLICATE.

     PROCEDURE P1(PARAM1 : BOOLEAN;
                  PARAM2 : INTEGER);

     PROCEDURE NEW_P(PARAM1 : BOOLEAN;
                     PARAM1 : INTEGER) RENAMES P1;  -- ERROR: DUPLICATE.

     FUNCTION MULT(X : POSITIVE; Y : INTEGER) RETURN INTEGER;
     FUNCTION "*"(X : POSITIVE;
                  X : INTEGER)                      -- ERROR: DUPLICATE.
                               RETURN INTEGER RENAMES MULT;

     PROCEDURE P2(PARAM1 : IN BOOLEAN;
                  PARAM1 : OUT INTEGER)             -- ERROR: DUPLICATE.
                                   IS SEPARATE;

     FUNCTION F2(PARAM1 : BOOLEAN;
                 PARAM1 : BOOLEAN)                  -- ERROR: DUPLICATE.
                                   RETURN BOOLEAN IS SEPARATE;

     FUNCTION F(PARAM1 : BOOLEAN;
                PARAM1 : INTEGER) RETURN BOOLEAN IS -- ERROR: DUPLICATE.
     BEGIN
          RETURN TRUE;
     END F;

     PROCEDURE P(PARAM1 : IN BOOLEAN;
                 PARAM1 : OUT INTEGER) IS           -- ERROR: DUPLICATE.
     BEGIN
          NULL;
     END P;

     PROCEDURE P1(PARAM1 : BOOLEAN;
                  PARAM2 : INTEGER) IS
     BEGIN
          NULL;
     END P1;

     PROCEDURE A(PARAM1 : BOOLEAN;
                 PARAM1 : INTEGER;                  -- ERROR: DUPLICATE.
                 PARAM2 : CHARACTER;
                 PARAM1 : STRING;                   -- ERROR: DUPLICATE.
                 PARAM3 : POSITIVE;
                 PARAM1 : NATURAL;                  -- ERROR: DUPLICATE.
                 PARAM1 : BOOLEAN)IS                -- ERROR: DUPLICATE.
     BEGIN
          NULL;
     END A;

     FUNCTION B(PARAM1 : BOOLEAN;
                PARAM1 : STRING) RETURN BOOLEAN IS  -- ERROR: DUPLICATE.
     BEGIN
          RETURN TRUE;
     END;

     FUNCTION MULT(X : POSITIVE; Y : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN X * Y;
     END;

BEGIN
     NULL;
END B83E01A;
