-- B83E01E0M.ADA

-- OBJECTIVE:
--     CHECK THAT A FORMAL PARAMETER OF A SUBPROGRAM SUBUNIT, IN A
--     SEPARATE FILE FROM THE SPECIFICATION CANNOT  BE IDENTICAL TO
--     ANY OTHER IDENTIFIERS DECLARED IN THE SUBUNIT.

-- SEPARATE FILES:
--     B83E01E0M CONTAINS THE PROCEDURE WHICH HOLDS THE SPECIFICATIONS
--               FOR THE SUBUNITS. THIS FILE SHOULD COMPILE WITHOUT
--               ERRORS.
--     B83E01E1  CONTAINS THE SUBUNIT BODIES.

-- HISTORY:
--     DHH 09/15/88  CREATED ORIGINAL TEST.

PROCEDURE B83E01E0M IS

     PROCEDURE B83E01E_PROC1(PARAM1, PARAM2, PARAM3, PARAM4, PARAM5,
                             PARAM6, PARAM7 : INTEGER) IS SEPARATE;

     PROCEDURE B83E01E_PROC2(PARAM1, PARAM2, PARAM3, PARAM4 :
                             IN OUT INTEGER) IS SEPARATE;

     FUNCTION B83E01E_PROC3(PARAM1, PARAM2, PARAM3, PARAM4, PARAM5,
                            PARAM6 :INTEGER) RETURN BOOLEAN IS SEPARATE;
BEGIN
     NULL;
END B83E01E0M;
