-- B83E01F0M.ADA

-- OBJECTIVE:
--     CHECK THAT A FORMAL PARAMETER OF A GENERIC SUBPROGRAM SUBUNIT,
--     IN A SEPARATE FILE, CANNOT  BE IDENTICAL TO ANY OTHER IDENTIFIERS
--     DECLARED IN THE SUBUNIT.

-- SEPARATE FILES:
--     B83E01F0M CONTAINS THE PROCEDURE WHICH HOLDS THE SPECIFICATIONS
--               FOR THE SUBUNITS. THIS FILE SHOULD COMPILE WITHOUT
--               ERRORS.
--     B83E01F1  CONTAINS THE SUBUNIT BODIES.

-- HISTORY:
--     DHH 09/15/88  CREATED ORIGINAL TEST.

PROCEDURE B83E01F0M IS

     GENERIC
     PROCEDURE B83E01F_GEN_PROC1(PARAM1, PARAM2, PARAM3, PARAM4,
                                 PARAM5, PARAM6, PARAM7 : INTEGER);

     GENERIC
     PROCEDURE B83E01F_GEN_PROC2(PARAM1, PARAM2, PARAM3,
                                 PARAM4 : IN OUT INTEGER);

     GENERIC
     FUNCTION B83E01F_GEN_PROC3(PARAM1, PARAM2 : INTEGER)
                                                        RETURN BOOLEAN;

     GENERIC
          TYPE PARAM1 IS (<>);
          TYPE PARAM2 IS (<>);
          TYPE PARAM3 IS (<>);
          TYPE PARAM4 IS (<>);
          TYPE PARAM5 IS (<>);
          TYPE PARAM6 IS (<>);
          TYPE PARAM7 IS (<>);
     PROCEDURE B83E01F_GEN_PROC4;

     GENERIC
          TYPE PARAM1 IS (<>);
          TYPE PARAM2 IS (<>);
          TYPE PARAM3 IS (<>);
          TYPE PARAM4 IS (<>);
     PROCEDURE B83E01F_GEN_PROC5;

     GENERIC
          TYPE PARAM1 IS (<>);
          TYPE PARAM2 IS (<>);
     FUNCTION B83E01F_GEN_PROC6 RETURN BOOLEAN;

     PROCEDURE B83E01F_GEN_PROC1(PARAM1, PARAM2, PARAM3, PARAM4,
                                 PARAM5, PARAM6, PARAM7 : INTEGER)
                                                            IS SEPARATE;

     PROCEDURE B83E01F_GEN_PROC2(PARAM1, PARAM2, PARAM3,
                                 PARAM4 :IN OUT INTEGER) IS SEPARATE;

     FUNCTION B83E01F_GEN_PROC3(PARAM1, PARAM2 : INTEGER) RETURN BOOLEAN
                                                           IS SEPARATE;

     PROCEDURE B83E01F_GEN_PROC4 IS SEPARATE;

     PROCEDURE B83E01F_GEN_PROC5 IS SEPARATE;

     FUNCTION B83E01F_GEN_PROC6 RETURN BOOLEAN IS SEPARATE;

BEGIN
     NULL;
END B83E01F0M;
