-- B84007A.ADA

-- OBJECTIVE:
--     CHECK THAT THE NAMES MADE VISIBLE BY A USE CLAUSE ARE NOT MADE
--     VISIBLE UNTIL AFTER THE END OF THE USE CLAUSE.

-- HISTORY:
--     JET 03/10/88 CREATED ORIGINAL TEST.

PROCEDURE B84007A IS

     PACKAGE PACK1 IS
          PACKAGE PACK2 IS
               TYPE A IS RANGE 0..100;
          END PACK2;
     END PACK1;

     USE PACK2;                    -- ERROR: PACK2 NOT VISIBLE.

     X : INTEGER;

     USE PACK1, PACK2;             -- ERROR: PACK2 STILL NOT VISIBLE.

BEGIN
     NULL;
END B84007A;
