-- B84005B.ADA

-- OBJECTIVE:
--     CHECK THAT TWO POTENTIALLY VISIBLE HOMOGRAPHS OF A SUBPROGRAM
--     IDENTIFIER CAN BE MADE DIRECTLY VISIBLE BY A USE CLAUSE, AND THAT
--     UNLESS DIFFERENT FORMAL PARAMETER NAMES ARE USED THE SUBPROGRAMS
--     ARE AMBIGUOUS.

-- HISTORY:
--     JET 07/21/88  CREATED ORIGINAL TEST.

PROCEDURE B84005B IS

     PACKAGE PACK1 IS
          FUNCTION FUNK(X : INTEGER) RETURN INTEGER;
          PROCEDURE PROK(X : INTEGER; Y : OUT INTEGER);
     END PACK1;

     PACKAGE PACK2 IS
          FUNCTION FUNK(X : INTEGER) RETURN INTEGER;
          PROCEDURE PROK(X : INTEGER; Y : OUT INTEGER);
     END PACK2;

     USE PACK1, PACK2;
     I, J : INTEGER := 0;

     PACKAGE BODY PACK1 IS
          FUNCTION FUNK(X : INTEGER) RETURN INTEGER IS
          BEGIN
               RETURN 1;
          END FUNK;

          PROCEDURE PROK(X : INTEGER; Y : OUT INTEGER) IS
          BEGIN
               Y := 1;
          END PROK;
     END PACK1;

     PACKAGE BODY PACK2 IS
          FUNCTION FUNK(X : INTEGER) RETURN INTEGER IS
          BEGIN
               RETURN 2;
          END FUNK;

          PROCEDURE PROK(X : INTEGER; Y : OUT INTEGER) IS
          BEGIN
               Y := 2;
          END PROK;
     END PACK2;

BEGIN

     I := FUNK(J);                         -- ERROR: FUNK IS AMBIGUOUS.

     I := FUNK(X => J);                    -- ERROR: FUNK IS AMBIGUOUS.

     PROK(I, J);                           -- ERROR: PROK IS AMBIGUOUS.

     PROK(X => I, Y => J);                 -- ERROR: PROK IS AMBIGUOUS.

END B84005B;
