-- B84008B.ADA

-- OBJECTIVE:
--     CHECK THAT THE NAMES MADE VISIBLE BY A USE CLAUSE IN THE VISIBLE
--     PART OF A PACKAGE ARE NOT MADE VISIBLE OUTSIDE THE PACKAGE EVEN
--     IF A USE CLAUSE IS GIVEN FOR THE PACKAGE IN WHICH THE ORIGINAL
--     USE CLAUSE IS GIVEN.

-- HISTORY:
--     JET 07/21/88  CREATED ORIGINAL TEST.

PROCEDURE B84008B IS

     PACKAGE PACK1 IS
          TYPE A IS RANGE 0..100;
          PROCEDURE PROC;
          I : INTEGER;
     END PACK1;

     PACKAGE PACK2 IS
          USE PACK1;
          VAR1 : A;
     END PACK2;

     USE PACK2;

     VAR2 : A;                         -- ERROR: A NOT VISIBLE.

     PACKAGE BODY PACK1 IS
          PROCEDURE PROC IS
          BEGIN
               NULL;
          END PROC;
     END PACK1;

BEGIN
     PROC;                             -- ERROR: PROC NOT VISIBLE.
     I := 10;                          -- ERROR: I NOT VISIBLE.
END B84008B;
