-- B85001F.ADA

-- OBJECTIVE:
--     CHECK THAT AN OBJECT RENAMING DECLARATION CANNOT RENAME AN
--     ENUMERATION LITERAL, BLOCK NAME, LOOP NAME, LABEL, TYPE, SUBTYPE,
--     EXCEPTION, SUBPROGRAM, PACKAGE, GENERIC UNIT, ENTRY, ENTRY
--     FAMILY, OR AN ATTRIBUTE WHICH IS A FUNCTION.

-- HISTORY:
--     JET 07/22/88  CREATED ORIGINAL TEST.

PROCEDURE B85001F IS

     TYPE ENUM IS (SEMPER, FIDELIS);
     SUBTYPE ST IS INTEGER;

     PROCEDURE PROC;

     GENERIC
     PROCEDURE GPROC;

     PACKAGE PACK IS
          TYPE T IS RANGE 0 .. 10;
     END PACK;

     TASK TSK IS
          ENTRY E;
          ENTRY F(ENUM);
     END TSK;

     A : ENUM RENAMES FIDELIS;                -- ERROR: ENUM LITERAL.
     B : INTEGER RENAMES ENUM;                -- ERROR: TYPE NAME.
     C : INTEGER RENAMES ST;                  -- ERROR: SUBTYPE.
     D : INTEGER RENAMES PROGRAM_ERROR;       -- ERROR: EXCEPTION.
     E : INTEGER RENAMES PROC;                -- ERROR: SUBPROGRAM.
     F : INTEGER RENAMES PACK;                -- ERROR: PACKAGE.
     G : INTEGER RENAMES GPROC;               -- ERROR: GENERIC UNIT.
     H : INTEGER RENAMES TSK.E;               -- ERROR: ENTRY.
     I : INTEGER RENAMES TSK.F;               -- ERROR: ENTRY FAMILY.
     J : INTEGER RENAMES INTEGER'PRED;        -- ERROR: ATTRIBUTE.

     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;

     PROCEDURE GPROC IS
     BEGIN
          NULL;
     END GPROC;

     TASK BODY TSK IS
     BEGIN
          ACCEPT E DO
               NULL;
          END E;
          ACCEPT F(SEMPER) DO
               NULL;
          END F;
          ACCEPT F(FIDELIS) DO
               NULL;
          END F;
     END TSK;

BEGIN
<<LABEL_NAME>>
     NULL;
LOOP_NAME:
     LOOP
BLOCK_NAME:
          DECLARE
               K: INTEGER RENAMES BLOCK_NAME; -- ERROR: BLOCK NAME.
               L : INTEGER RENAMES LOOP_NAME;  -- ERROR: LOOP NAME.
               M : INTEGER RENAMES LABEL_NAME; -- ERROR: LABEL NAME.
          BEGIN
               NULL;
          END BLOCK_NAME;
     END LOOP LOOP_NAME;
END B85001F;
