-- B85001E.ADA

-- OBJECTIVE:
--     CHECK THAT AN OBJECT RENAMING DECLARATION CANNOT RENAME AN
--     AGGREGATE.

-- HISTORY:
--     JET 07/21/88  CREATED ORIGINAL TEST.

PROCEDURE B85001E IS
     TYPE REC IS RECORD
          I : INTEGER;
          B : BOOLEAN;
     END RECORD;

     A : REC := (0, FALSE);
     B : REC RENAMES A;                      -- OK.
     T : REC RENAMES (0, FALSE);             -- ERROR: RENAMES LITERAL.
BEGIN
     NULL;
END B85001E;
