-- B85001J.ADA

-- OBJECTIVE:
--     CHECK THAT THE TYPE MARK IN AN OBJECT RENAMING DECLARATION CANNOT
--     BE REPLACED BY A SUBTYPE INDICATION WITH AN ACCURACY CONSTRAINT.

-- HISTORY:
--     JET 07/25/88 CREATED ORIGINAL TEST.

PROCEDURE B85001J IS

     TYPE FIX IS DELTA 2#0.01# RANGE -100.0 .. 100.0;

     X0 : FIX;

     X : FIX DELTA 2#0.01# RENAMES X0;  -- ERROR: ACCURACY CONSTRAINT.

BEGIN
     NULL;
END B85001J;
