-- B85001I.ADA

-- OBJECTIVE:
--     CHECK THAT THE TYPE MARK IN AN OBJECT RENAMING DECLARATION CANNOT
--     BE REPLACED BY A SUBTYPE INDICATION WITH A RANGE CONSTRAINT.

-- HISTORY:
--     JET 07/25/88 CREATED ORIGINAL TEST.

PROCEDURE B85001I IS

     I0 : INTEGER RANGE 0..9;

     I : INTEGER RANGE 0..9 RENAMES I0;      -- ERROR: RANGE CONSTRAINT.

BEGIN
     NULL;
END B85001I;
