-- B85008G.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXCEPTION RENAMING DECLARATION CANNOT RENAME AN
--     ENUMERATION LITERAL, BLOCK NAME, LOOP NAME, LABEL, TYPE, SUBTYPE,
--     SUBPROGRAM, PACKAGE, GENERIC UNIT, ENTRY, ENTRY FAMILY, OR AN
--     ATTRIBUTE WHICH IS A FUNCTION.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B85008G IS

     TYPE ENUM IS (SEMPER, FIDELIS);
     SUBTYPE ST IS INTEGER;

     PROCEDURE PROC;

     GENERIC
     PROCEDURE GPROC;

     PACKAGE PACK IS
          TYPE T IS RANGE 0 .. 10;
     END PACK;

     TASK TSK IS
          ENTRY E;
          ENTRY F(ENUM);
     END TSK;

     A : EXCEPTION RENAMES FIDELIS;           -- ERROR: ENUM LITERAL.
     B : EXCEPTION RENAMES ENUM;              -- ERROR: TYPE NAME.
     C : EXCEPTION RENAMES ST;                -- ERROR: SUBTYPE.
     D : EXCEPTION RENAMES PROC;              -- ERROR: SUBPROGRAM.
     E : EXCEPTION RENAMES PACK;              -- ERROR: PACKAGE.
     F : EXCEPTION RENAMES GPROC;             -- ERROR: GENERIC UNIT.
     G : EXCEPTION RENAMES TSK.E;             -- ERROR: ENTRY.
     H : EXCEPTION RENAMES TSK.F;             -- ERROR: ENTRY FAMILY.
     I : EXCEPTION RENAMES INTEGER'PRED;      -- ERROR: ATTRIBUTE.

     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;

     PROCEDURE GPROC IS
     BEGIN
          NULL;
     END GPROC;

     TASK BODY TSK IS
     BEGIN
          ACCEPT E DO
               NULL;
          END E;
          ACCEPT F(SEMPER) DO
               NULL;
          END F;
          ACCEPT F(FIDELIS) DO
               NULL;
          END F;
     END TSK;

BEGIN
<<LABEL_NAME>>
     NULL;
LOOP_NAME:
     LOOP
BLOCK_NAME:
          DECLARE
               J : EXCEPTION RENAMES BLOCK_NAME; -- ERROR: BLOCK NAME.
               K : EXCEPTION RENAMES LOOP_NAME;  -- ERROR: LOOP NAME.
               L : EXCEPTION RENAMES LABEL_NAME; -- ERROR: LABEL NAME.
          BEGIN
               NULL;
          END BLOCK_NAME;
     END LOOP LOOP_NAME;
END B85008G;
