-- B85008D.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXCEPTION RENAMING DECLARATION CANNOT RENAME THE
--     NULL LITERAL.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B85008D IS

     EXCEPTION1 : EXCEPTION;

     EXCEPTION2 : EXCEPTION RENAMES EXCEPTION1;  -- OK.

     EXCEPTION5 : EXCEPTION RENAMES NULL;        -- ERROR: LITERAL

BEGIN
     NULL;
END B85008D;
