-- B85010A.ADA

-- OBJECTIVE:
--     CHECK THAT A PACKAGE RENAMING DECLARATION CANNOT RENAME AN
--     INTEGER LITERAL;

-- HISTORY:
--     JET 03/24/88  CREATED ORIGINAL TEST.

PROCEDURE B85010A IS

     PACKAGE PACK1 IS
          TYPE COLORS IS (RED, BLUE, GREEN);
     END PACK1;

     PACKAGE PACK2 RENAMES PACK1;                   -- OK.

     PACKAGE PACK6 RENAMES 12_000;                  -- ERROR: LITERAL

BEGIN
     NULL;
END B85010A;
