-- B85001A.ADA

-- OBJECTIVE:
--     CHECK THAT AN OBJECT RENAMING DECLARATION CANNOT RENAME AN
--     INTEGER LITERAL.

-- HISTORY:
--     JET 03/10/88  CREATED ORIGINAL TEST.

PROCEDURE B85001A IS
     A : INTEGER := 3;
     B : INTEGER RENAMES A;               -- OK.
     T : INTEGER RENAMES 0;               -- ERROR: RENAMES LITERAL
BEGIN
     NULL;
END B85001A;
