-- B85001C.ADA

-- OBJECTIVE:
--     CHECK THAT AN OBJECT RENAMING DECLARATION CANNOT RENAME A
--     STRING LITERAL.

-- HISTORY:
--     JET 07/21/88  CREATED ORIGINAL TEST.

PROCEDURE B85001C IS
     A : CONSTANT STRING := "THIS IS ONLY A TEST";
     B : STRING RENAMES A;               -- OK.
     T : STRING RENAMES "OH NO";         -- ERROR: RENAMES LITERAL.
BEGIN
     NULL;
END B85001C;
