-- B85001D.ADA

-- OBJECTIVE:
--     CHECK THAT AN OBJECT RENAMING DECLARATION CANNOT RENAME THE
--     NULL LITERAL.

-- HISTORY:
--     JET 07/21/88  CREATED ORIGINAL TEST.

PROCEDURE B85001D IS
     TYPE ACC IS ACCESS INTEGER;
     A : ACC := NULL;
     B : ACC RENAMES A;                  -- OK.
     T : ACC RENAMES NULL;               -- ERROR: RENAMES LITERAL.
BEGIN
     NULL;
END B85001D;
