-- B85001B.ADA

-- OBJECTIVE:
--     CHECK THAT AN OBJECT RENAMING DECLARATION CANNOT RENAME A
--     REAL LITERAL.

-- HISTORY:
--     JET 07/21/88  CREATED ORIGINAL TEST.

PROCEDURE B85001B IS
     A : FLOAT := 3.0;
     B : FLOAT RENAMES A;               -- OK.
     T : FLOAT RENAMES 2#11.0#;         -- ERROR: RENAMES LITERAL.
BEGIN
     NULL;
END B85001B;
