-- B85001L.ADA

-- OBJECTIVE:
--     CHECK THAT THE TYPE MARK IN AN OBJECT RENAMING DECLARATION CANNOT
--     BE REPLACED BY A SUBTYPE INDICATION WITH A DISCRIMINANT
--     CONSTRAINT.

-- HISTORY:
--     JET 07/25/88 CREATED ORIGINAL TEST.

PROCEDURE B85001L IS

     TYPE REC (D : INTEGER) IS RECORD
          I : INTEGER;
          F : FLOAT;
     END RECORD;

     D0 : REC(1);

     D : REC2(1) RENAMES D0;          -- ERROR: DISCRIMINANT CONSTRAINT.

BEGIN
     NULL;
END B85001L;
