-- B85008H.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXCEPTION RENAMING DECLARATION CANNOT RENAME A
--     SUBCOMPONENT OF A FUNCTION VALUE OR AN ATTRIBUTE WHICH RETURNS
--     A VALUE.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B85008H IS

     TYPE REC0 IS RECORD
          J : INTEGER;
     END RECORD;

     TYPE REC IS RECORD
          I : REC0;
          B : BOOLEAN;
     END RECORD;

     FUNCTION FUNK RETURN REC;

     A : REC := ((J => 0), FALSE);
     T : EXCEPTION RENAMES FUNK.I.J;      -- ERROR: RENAMES SUBCOMPONENT
                                          -- OF FUNCTION VALUE.
     U : EXCEPTION RENAMES INTEGER'FIRST; -- ERROR: RENAMES ATTRIBUTE.

     FUNCTION FUNK RETURN REC IS
     BEGIN
          RETURN ((J => 1), TRUE);
     END FUNK;

BEGIN
     NULL;
END B85008H;
