-- B85001H.ADA

-- OBJECTIVE:
--     CHECK THAT THE BASE TYPE OF THE TYPE MARK IN AN OBJECT RENAMING
--     DECLARATION MUST BE THE SAME AS THE RENAMED OBJECT.

-- HISTORY:
--     JET 07/22/88 CREATED ORIGINAL TEST.

PROCEDURE B85001H IS

     TYPE NEWINT IS NEW INTEGER;

     F0 : FLOAT;
     N : NEWINT;

     A : INTEGER RENAMES F0;            -- ERROR: DIFFERENT BASE TYPE.
     B : INTEGER RENAMES N;             -- ERROR: DIFFERENT BASE TYPE.

BEGIN
     NULL;
END B85001H;
