-- B85008C.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXCEPTION RENAMING DECLARATION CANNOT RENAME A
--     STRING LITERAL.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B85008C IS

     EXCEPTION1 : EXCEPTION;

     EXCEPTION2 : EXCEPTION RENAMES EXCEPTION1;  -- OK.

     EXCEPTION5 : EXCEPTION RENAMES "LABOR ET SCIENTIA";
                                                 -- ERROR: LITERAL

BEGIN
     NULL;
END B85008C;
