-- B85008A.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXCEPTION RENAMING DECLARATION CANNOT RENAME AN
--     INTEGER LITERAL;

-- HISTORY:
--     JET 03/23/88  CREATED ORIGINAL TEST.

PROCEDURE B85008A IS

     EXCEPTION1 : EXCEPTION;

     EXCEPTION2 : EXCEPTION RENAMES EXCEPTION1;  -- OK.

     EXCEPTION5 : EXCEPTION RENAMES 16#A00#;     -- ERROR: LITERAL

BEGIN
     NULL;
END B85008A;
