-- B8500IK.ADA

-- OBJECTIVE:
--     CHECK THAT THE TYPE MARK IN AN OBJECT RENAMING DECLARATION CANNOT
--     BE REPLACED BY A SUBTYPE INDICATION WITH AN INDEX CONSTRAINT.

-- HISTORY:
--     JET 07/25/88 CREATED ORIGINAL TEST.

PROCEDURE B8500IK IS

     TYPE ARR IS ARRAY (INTEGER RANGE <>) OF INTEGER;

     A0 : ARR(1..10);

     A : ARR(1..10) RENAMES A0;              -- ERROR: INDEX CONSTRAINT.

BEGIN
     NULL;
END B8500IK;
