-- B85008F.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXCEPTION RENAMING DECLARATION CANNOT RENAME A
--     VARIABLE, CONSTANT, OR SUBCOMPONENT.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B85008F IS

     TYPE REC0 IS RECORD
          G : INTEGER;
     END RECORD;

     TYPE REC IS RECORD
          F : REC0;
     END RECORD;

     V : INTEGER;
     C1 : CONSTANT := 1;
     C2 : CONSTANT INTEGER := 2;
     R : REC;

     RV : EXCEPTION RENAMES V;               -- ERROR: VARIABLE.
     RC1 : EXCEPTION RENAMES C1;             -- ERROR: NAMED NUMBER.
     RC2 : EXCEPTION RENAMES C2;             -- ERROR: CONSTANT.
     RR : EXCEPTION RENAMES R.F.G;           -- ERROR: SUBCOMPONENT.

     PROCEDURE PROC (P : IN INTEGER) IS
          RP : EXCEPTION RENAMES P;          -- ERROR: FORMAL PARAMETER.
     BEGIN
          NULL;
     END PROC;

BEGIN
     FOR L IN 1..10 LOOP
          DECLARE
               RL : EXCEPTION RENAMES L;     -- ERROR: LOOP VARIABLE.
          BEGIN
               NULL;
          END;
     END LOOP;
END B85008F;
