-- B85013D.ADA

-- OBJECTIVE:
--     CHECK THAT A SUBPROGRAM OR ENTRY CAN BE RENAMED WITH:
--       A) DIFFERENT PARAMETER VALUE;
--       B) DIFFERENT DEFAULT VALUES;
--       C) DIFFERENT PARAMETERS HAVING DEFAULT VALUES;
--     AND THAT THE NEW NAMES/DEFAULTS ARE USED WHEN THE NEW NAME IS
--     USED IN A CALL.
--     CASE WHERE THE AGGREGATE CONTEXT IN A RENAMING DECLARATION COMES
--     FROM THE SUBTYPE INDICATIONS IN THE RENAMED SUBPROGRAM,
--     ESPECIALLY FOR A DEFAULT EXPRESSION.

-- HISTORY:
--     DWC 10/02/87  CREATED ORIGINAL TEST FROM SPLIT OF B85013C.ADA.

PROCEDURE B85013D (N : INTEGER) IS

     SUBTYPE S  IS STRING;                        -- UNCONSTRAINED.
     SUBTYPE S1 IS STRING(1 .. 2);                -- STATIC.
     SUBTYPE S2 IS STRING(1 .. N);                -- NON-STATIC.

     FUNCTION  C1 (L : S1 := (OTHERS => 'L');     -- ERROR: OTHERS NOT
                                                  -- ALLOWED.
                   R : S2 := (OTHERS => 'R'))     -- ERROR: OTHERS NOT
                                                  -- ALLOWED.
                         RETURN S RENAMES "&";

BEGIN

     NULL;

END B85013D;
