-- B85010B.ADA

-- OBJECTIVE:
--     CHECK THAT A PACKAGE RENAMING DECLARATION CANNOT RENAME A
--     REAL LITERAL.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

PROCEDURE B85010B IS

     PACKAGE PACK1 IS
          F : CONSTANT := 15.7;
     END PACK1;

     PACKAGE PACK2 RENAMES PACK1;                   -- OK.

     PACKAGE PACK6 RENAMES 15.7;                    -- ERROR: LITERAL.

BEGIN
     NULL;
END B85010B;
