-- B86001B.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY UNIT CANNOT HAVE THE NAME  'INTEGER'.

-- HISTORY:
--     RM   01/16/81  CREATED ORIGINAL TEST.
--     JRK  02/24/83
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BB.ADA.

PROCEDURE  INTEGER  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

BEGIN

     NULL ;

END INTEGER ;
