-- B86001N.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY UNIT CANNOT HAVE THE NAME  'BOOLEAN'.

-- HISTORY:
--     RM   01/16/81  CREATED ORIGINAL TEST.
--     JRK  02/24/83
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BA.ADA.

PROCEDURE  BOOLEAN  IS    -- ERROR: ILLEGAL NAME.

     A : INTEGER ;

BEGIN

     NULL ;

END BOOLEAN ;
