-- B86001M.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY UNIT CANNOT HAVE THE NAME  'TASKING_ERROR'.

-- HISTORY:
--     RM   01/16/81  CREATED ORIGINAL TEST.
--     JRK  02/24/83
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BM.ADA.

PROCEDURE  TASKING_ERROR  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

BEGIN

     NULL ;

END TASKING_ERROR ;
