-- B86001C.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY UNIT CANNOT HAVE THE NAME  'CHARACTER'.

-- HISTORY:
--     RM   01/16/81  CREATED ORIGINAL TEST.
--     JRK  02/24/83
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BC.ADA.

PROCEDURE  CHARACTER  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

BEGIN

     NULL ;

END CHARACTER ;
