-- B86001S.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY PACKAGE CANNOT HAVE THE NAME  'FALSE'.

-- HISTORY:
--     JRK  02/24/83  CREATED ORIGINAL TEST.
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BX.ADA.

PACKAGE  FALSE  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

END FALSE ;
