-- B86001A1M.ADA


-- MAIN PROGRAM REQUIRING A SEPARATELY COMPILED PROCEDURE (B86001A0 )


-- CHECK THAT THE NAME  STANDARD.M  IS ILLEGAL IF  M  DOES NOT APPEAR
--    IN A  WITH_CLAUSE  AND THE NAME OF THE LIBRARY UNIT BEING COM-
--    PILED IS NOT  M .


--                                    -- NOTE THE ABSENCE OF 'WITH...'
PROCEDURE  B86001A1M  IS

     B : INTEGER;

BEGIN

     STANDARD.B86001A0;  -- ERROR: ILLEGAL REFERENCE ( 'B86001A0'  IS
		      --    NOT THE NAME OF THIS VERY PROCEDURE AND
          	      --    IS NOT MENTIONED IN A  WITH_CLAUSE  AT
		      --    THE HEAD OF THIS PROCEDURE)

END B86001A1M;
