-- B86001R.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY PACKAGE CANNOT HAVE THE NAME  'TRUE'.

-- HISTORY:
--     JRK  02/24/83  CREATED ORIGINAL TEST.
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BW.ADA.

PACKAGE  TRUE  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

END TRUE ;
