-- B86001P.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY UNIT CANNOT HAVE THE NAME  'NATURAL'.

-- HISTORY:
--     RM  01/16/81  CREATED ORIGINAL TEST.
--     JRK 02/24/83
--     BCB 11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                   B86001BE.ADA.
--     JET 01/11/88  RENAMED FROM B86001E.ADA, REPLACING FORMER TEST.

PROCEDURE  NATURAL  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

BEGIN

     NULL ;

END NATURAL ;
