-- B86001H.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY UNIT CANNOT HAVE THE NAME  'DURATION'.

-- HISTORY:
--     RM   01/16/81  CREATED ORIGINAL TEST.
--     JRK  02/24/83
--     BCB  11/13/87  CHANGED HEADER TO STANDARD FORMAT.  RENAMED FROM
--                    B86001BH.ADA.

PROCEDURE  DURATION  IS    -- ERROR: ILLEGAL NAME.

     A : BOOLEAN ;

BEGIN

     NULL ;

END DURATION ;
