-- B91002C.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (C) ACCESS TYPE DECLARATIONS.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002C IS

     TASK TYPE T2C IS

          ENTRY E;

          TYPE A IS ACCESS INTEGER;  -- ERROR: PROHIBITED IN TASK SPEC.

     END T2C;

     TASK BODY T2C IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002C;
