-- B91002K.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (K) SINGLE TASK DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002K IS

     TASK TYPE T2K IS

          ENTRY E;

          TASK T2;                   -- ERROR: PROHIBITED IN TASK SPEC.

     END T2K;

     TASK BODY T2K IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002K;
