-- B91002B.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (B) NUMBER DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002B IS

     TASK TYPE T2B IS

          ENTRY E;

          N : CONSTANT := 1;         -- ERROR: PROHIBITED IN TASK SPEC.

     END T2B;

     TASK BODY T2B IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002B;
