-- B91003D.ADA

-- CHECK THAT A TASK SPECIFICATION CANNOT FOLLOW THE TASK BODY IN A
-- DECLARATIVE PART.

-- TBN 1/30/86

PROCEDURE B91003D IS

     TASK BODY FRED IS          -- ERROR: BODY PRECEDES SPEC.

     BEGIN
          NULL;
     END FRED;

     TASK FRED;

     TASK BODY T1 IS            -- ERROR: BODY PRECEDES SPEC.

     BEGIN
          ACCEPT E;             -- OPTIONAL ERROR: E UNDECLARED.
     END T1;

     TASK TYPE T1 IS
          ENTRY E;
     END T1;

BEGIN
     NULL;
END B91003D;
