-- B91002L.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (L) EXCEPTION DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002L IS

     TASK TYPE T2L IS

          ENTRY E;

          EX : EXCEPTION;            -- ERROR: PROHIBITED IN TASK SPEC.

     END T2L;

     TASK BODY T2L IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002L;
