-- B91001F.ADA

-- CHECK THAT THE IDENTIFIER AT THE END OF A TASK DECLARATION
-- OR BODY CANNOT BE DIFFERENT FROM THE IDENTIFIER SERVING AS
-- THE NAME OF THE TASK.

-- JRK 9/16/81
-- ABW 7/23/82

PROCEDURE B91001F IS

     TASK TYPE T1 IS
          ENTRY E;
     END TS1;                      -- ERROR: NON-MATCHING IDENTIFIER.

     TASK T2 IS
          ENTRY E;
     END TS2;                      -- ERROR: NON-MATCHING IDENTIFIER.

     TASK BODY T1 IS
     BEGIN
          NULL;
     END TB1;                      -- ERROR: NON-MATCHING IDENTIFIER.

     TASK BODY T2 IS
     BEGIN
          NULL;
     END T1;                       -- ERROR: NON-MATCHING IDENTIFIER.

BEGIN
     NULL;
END B91001F;
