-- B91001H.ADA

-- OBJECTIVE:
--     CHECK THAT TWO ENTRY DECLARATIONS CANNOT BE SEPARATED BY AN
--     ADDRESS CLAUSE THAT APPLIES TO THE FIRST ENTRY DECLARATION.  ALSO
--     CHECK THAT AN ADDRESS CLAUSE CANNOT PRECEDE AN ENTRY DECLARATION.

-- HISTORY:
--     TBN 01/28/86  CREATED ORIGINAL TEST.
--     BCB 10/21/87  CHANGED HEADER TO STANDARD FORMAT.  USED SPPRT13
--                   FUNCTION FOR ADDRESS VALUE.

WITH SYSTEM;
WITH SPPRT13;
PROCEDURE B91001H IS

     TASK T1 IS
          ENTRY E1;
          FOR E1 USE AT SPPRT13.ENTRY_ADDRESS;
          ENTRY E2;                               -- ERROR: DECL. AFTER
     END T1;                                      --        REP. CLAUSE


     TASK TYPE T2 IS
          FOR FRED USE AT SPPRT13.ENTRY_ADDRESS;  -- ERROR: FRED UNDECL.
          ENTRY FRED;
     END T2;

     TASK BODY T1 IS
     BEGIN
          NULL;
     END T1;

     TASK BODY T2 IS
     BEGIN
          NULL;
     END T2;

BEGIN
     NULL;
END B91001H;
