-- B91003E.ADA

-- OBJECTIVE:
--     CHECK THAT A (MATCHING) TASK BODY IS REQUIRED FOR EACH
--     TASK SPECIFICATION.  IN PARTICULAR, CHECK THAT THE CLOSING
--     IDENTIFIER OF THE TASK BODY MUST MATCH THE IDENTIFIER GIVEN
--     IN THE SPECIFICATIONS.

-- HISTORY:
--     DWC 09/22/87  CREATED ORIGINAL TEST FROM SPLIT OF B91003B.ADA.

PROCEDURE B91003E IS

     TASK T4;
     TASK T5;

     TASK BODY T4 IS
     BEGIN
          NULL;
     END T5;        -- ERROR: WRONG CLOSING IDENTIFIER.

     TASK BODY T5 IS
     BEGIN
          NULL;
     END T4;        -- ERROR: WRONG CLOSING IDENTIFIER.

BEGIN

     NULL;

END B91003E;
