-- B91003B.ADA

-- OBJECTIVE:
--     CHECK THAT A (MATCHING) TASK BODY IS REQUIRED FOR EACH
--     TASK SPECIFICATION.

-- HISTORY:
--     WEI 03/04/82
--     RJK 02/01/84  ADDED TO ACVC
--     JWC 06/28/85  FROM B910ABA-B.ADA
--     DWC 09/22/87  MOVED CHECK THAT THE CLOSING IDENTIFIER MUST
--                   MATCH THE IDENTIFIER GIVEN IN THE SPECIFICATION
--                   TO B91003E.ADA.

PROCEDURE B91003B IS

     TASK T1;
     TASK T2;
     TASK T3;

     TASK BODY T1 IS
     BEGIN
          NULL;
     END T1;        -- OK.

     TASK BODY T22 IS
     BEGIN
          NULL;
     END T22;       -- ERROR: BODY WITHOUT SPECIFICATION.

     TASK TYPE TT1;
     TASK TYPE TT2;
     TASK TYPE TT3;

     TASK BODY TT1 IS
     BEGIN
          NULL;
     END TT1;       -- OK.

     TASK BODY TT22 IS
     BEGIN
          NULL;
     END TT22;      -- ERROR: BODY WITHOUT SPEC.

-- ERROR: MISSING BODY FOR TASKS T2,T3.
-- ERROR: MISSING BODY FOR TASK TYPES TT2, TT3.

BEGIN
     NULL;
END B91003B;
