-- B91002G.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (G) PROCEDURE DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002G IS

     TASK TYPE T2G IS

          ENTRY E;

          PROCEDURE P;               -- ERROR: PROHIBITED IN TASK SPEC.

     END T2G;

     TASK BODY T2G IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002G;
