-- B91001A.ADA

-- CHECK THAT A PARAMETER LIST MAY NOT FOLLOW THE IDENTIFIER
-- IN A TASK SPECIFICATION.

-- JRK 9/16/81
-- ABW 6/18/82

PROCEDURE B91001A IS

     TASK TYPE T (I : INTEGER) IS     -- ERROR: PARAMETER LIST
                                      --        PROHIBITED.  
          ENTRY E;
     END T;

     TASK BODY T IS
     BEGIN
          NULL;
     END T;

BEGIN
     NULL;
END B91001A;
