-- B91002I.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (I) PACKAGE DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002I IS

     TASK TYPE T2I IS

          ENTRY E;

          PACKAGE PKG IS             -- ERROR: PROHIBITED IN TASK SPEC.
               I : INTEGER;
          END PKG;

     END T2I;

     TASK BODY T2I IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002I;
