-- B91002H.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (H) FUNCTION DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002H IS

     TASK TYPE T2H IS

          ENTRY E;

          FUNCTION F RETURN INTEGER; -- ERROR: PROHIBITED IN TASK SPEC.

     END T2H;

     TASK BODY T2H IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002H;
