-- B91002D.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (D) SUBTYPE DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002D IS

     TASK TYPE T2D IS

          ENTRY E;

          SUBTYPE S IS INTEGER;      -- ERROR: PROHIBITED IN TASK SPEC.

     END T2D;

     TASK BODY T2D IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002D;
