-- B91002E.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (E) ARRAY TYPE DECLARATION.

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002E IS

     TASK TYPE T2E IS

          ENTRY E;

          TYPE B IS ARRAY (1..4) OF BOOLEAN; -- ERROR: PROHIBITED IN
                                             --        TASK SPEC.

     END T2E;

     TASK BODY T2E IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002E;
