-- B91005A.ADA

-- CHECK THAT THE IDENTIFIER OF A SINGLE TASK NAMES A TASK OBJECT
-- NOT A TASK TYPE.
--
--
--

-- WEI  3/ 4/82
-- RJK  2/ 1/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM B910ACA-B.ADA

PROCEDURE B91005A IS

     I : INTEGER;

     TASK T IS
          ENTRY E;
     END T;

     THIS_TASK : T;    -- ERROR: T DENOTES A TASK OBJECT, NOT A TYPE.

     TASK BODY T IS
     BEGIN
          ACCEPT E;
     END T;

BEGIN
     T.E;                   -- OK.
     I := T'STORAGE_SIZE;   -- OK.
     I := T.E'COUNT;        -- ERROR: NOT INSIDE TASK.
     I := T'SIZE;           -- OK.
END B91005A;
