-- B91002A.ADA

-- CHECK THAT DECLARATIONS OTHER THAN ENTRY DECLARATIONS ARE NOT ALLOWED
-- IN TASK SPECIFICATIONS.

-- (A) VARIABLE DECLARATION

-- JRK 9/16/81
-- JBG 4/19/83

PROCEDURE B91002A IS

     TASK TYPE T2A IS

          ENTRY E;

          I : INTEGER;               -- ERROR: PROHIBITED IN TASK SPEC.

     END T2A;

     TASK BODY T2A IS
     BEGIN
          NULL;
     END;

BEGIN
     NULL;
END B91002A;
