-- B95061E.ADA
 
-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT BE AN ARRAY INDEX CONSTRAINT.
 
-- JWC 6/18/85
 
PROCEDURE B95061E IS
 
     TYPE ARR IS ARRAY ( INTEGER RANGE <> ) OF INTEGER;
 
     TASK T IS
 
          ENTRY E1 ( X : ARR(1..10) );     -- ERROR: INDEX CONSTRAINT.
 
     END T;
 
     TASK BODY T IS
     BEGIN
          NULL;
     END T;
 
BEGIN
     NULL;
END B95061E;
