-- B95006B.ADA

-- CHECK THAT A NON-IDENTIFIER FORM OF NAME MUST NOT FOLLOW THE "END"
--   OF AN ACCEPT_STATEMENT.

-- SELECTED COMPONENT FORM OF NAME FOR ENTRY.

-- JRK 10/29/81

PROCEDURE B95006B IS

     TASK T IS
          ENTRY E1 (I : INTEGER);
          ENTRY E2 (BOOLEAN) (I : INTEGER);
     END T;

     TASK BODY T IS
     BEGIN

          ACCEPT E1 (I : INTEGER) DO
               NULL;
          END T.E1;           -- ERROR: NOT AN IDENTIFIER.

     END T;

BEGIN
     NULL;
END B95006B;
