-- B95077A.ADA

-- CHECK THAT NO EXCEPTION HANDLER PART CAN BE PROVIDED IN AN ACCEPT
-- STATEMENT.

-- JWC 7/19/85

PROCEDURE B95077A IS

     TASK T IS
          ENTRY E1;
     END T;

     TASK BODY T IS
     BEGIN
          ACCEPT E1 DO
               NULL;
          EXCEPTION               -- ERROR: EXCEPTION HANDLER IN ACCEPT.
               WHEN OTHERS =>
                    NULL;
          END E1;
     END T;

BEGIN
     NULL;
END B95077A;
