-- B95063A.ADA

-- CHECK THAT DEFAULT EXPRESSIONS ARE FORBIDDEN FOR FORMAL PARAMETERS
-- OF MODE IN OUT OR OUT.

-- JWC 7/19/85

PROCEDURE B95063A IS

     TASK T IS

          ENTRY E1 ( X : IN OUT INTEGER := 1);   -- ERROR: IN OUT.

          ENTRY E2 ( X : OUT INTEGER := 1);      -- ERROR: OUT.

          ENTRY E3 ( X : IN INTEGER := 1);       -- OK: IN.

     END T;

     TASK BODY T IS
     BEGIN
          NULL;
     END T;

BEGIN
     NULL;
END B95063A;
