-- B95061F.ADA
 
-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A DISCRIMINANT CONSTRAINT.
 
-- JWC 6/18/85
 
PROCEDURE B95061F IS
 
     TYPE REC ( DISC : INTEGER ) IS
          RECORD NULL; END RECORD;
 
     TASK T IS
 
          ENTRY E1 ( X : REC (DISC => 1) );     -- ERROR: DISCRIMINANT
                                                -- CONSTRAINT.
     END T;
 
     TASK BODY T IS
     BEGIN
          NULL;
     END T;
 
BEGIN
     NULL;
END B95061F;
