-- B95030A.ADA

-- CHECK THAT AN ENTRY DECLARATION MAY OCCUR ONLY
-- IN A TASK SPECIFICATION.

-- WEI  3/ 4/82
-- RJK  2/ 1/84     ADDED TO ACVC
-- JBG 3/30/84
-- JWC 6/28/85   RENAMED FROM B950ABA-B.ADA

PROCEDURE B95030A IS

     TASK T1 IS
          ENTRY E1;      -- OK.
     END T1;

     TASK BODY T1 IS
          ENTRY E2;      -- ERROR: ENTRY DECLARED IN BODY.
     BEGIN
          ACCEPT E1;     -- OK.
     END T1;

BEGIN
     NULL;
END B95030A;
