-- B95091A.ADA

-- CHECK THAT TYPE MARKS APPEARING IN ACTUAL IN OUT OR OUT PARAMETERS
-- MUST CONFORM TO THE TYPE MARK GIVEN IN THE FORMAL PARAMETER'S
-- DECLARATION.
-- CHECK THAT CONFORMANCE IS NOT REQUIRED FOR IN PARAMETERS.

-- JWC 7/19/85
-- JRK 10/1/85

PROCEDURE B95091A IS

     SUBTYPE SUBINT1 IS INTEGER RANGE 1 .. 20;
     SUBTYPE SUBINT2 IS INTEGER RANGE 1 .. 10;
     SUBTYPE SUBINT3 IS SUBINT1;
     TYPE NEWINT IS NEW INTEGER;

     I1 : INTEGER := 1;
     I2 : NEWINT := 2;

     TASK T IS
          ENTRY ES1 ( X1 : IN OUT SUBINT1 );
          ENTRY ES2 ( X1 : OUT SUBINT1 );
          ENTRY ES3 ( X1 : IN SUBINT1 );
     END T;

     TASK BODY T IS
     BEGIN
          NULL;
     END T;

BEGIN

     T.ES1 (INTEGER(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES2 (INTEGER(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES3 (INTEGER(I1));   -- OK.

     T.ES1 (SUBINT2(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES2 (SUBINT2(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES3 (SUBINT2(I1));   -- OK.

     T.ES1 (NEWINT(I1));    -- ERROR: MISMATCHED BASE TYPES.
     T.ES2 (NEWINT(I1));    -- ERROR: MISMATCHED BASE TYPES.
     T.ES3 (NEWINT(I1));    -- ERROR: MISMATCHED BASE TYPES.

     T.ES1 (SUBINT3(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES2 (SUBINT3(I1));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES3 (SUBINT3(I1));   -- OK.

     T.ES1 (INTEGER(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES2 (INTEGER(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES3 (INTEGER(I2));   -- OK.

     T.ES1 (SUBINT2(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES2 (SUBINT2(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES3 (SUBINT2(I2));   -- OK.

     T.ES1 (SUBINT3(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES2 (SUBINT3(I2));   -- ERROR: NON-CONFORMING TYPE MARKS.
     T.ES3 (SUBINT3(I2));   -- OK.

     T.ES1 (SUBINT1(I2));   -- OK.
     T.ES2 (SUBINT1(I2));   -- OK.
     T.ES3 (SUBINT1(I2));   -- OK.

     T.ES1 (B95091A.SUBINT1(I2));   -- OK.
     T.ES2 (B95091A.SUBINT1(I2));   -- OK.
     T.ES3 (B95091A.SUBINT1(I2));   -- OK.

END B95091A;
