-- B95001B.ADA

-- CHECK THAT THE BASE TYPE OF AN INDEX IN AN ENTRY CALL OR AN ACCEPT 
-- STATEMENT MUST MATCH THAT GIVEN IN THE ENTRY FAMILY'S DECLARATION.

-- RM 1/15/82
-- R.WILLIAMS 9/15/86  -- ADDED ACCESS TO TASK TYPE TO CHECK INDEX OF
--                        ENTRY FAMILY. RENAMED FROM -AB. REVISED 
--                        COMMENTS TO CONFORM THOSE IN AIG.

PROCEDURE B95001B IS

     SUBTYPE S IS INTEGER RANGE 5 .. 50;
     TYPE S1 IS NEW S;
     X : S1 := 6;
     Y : S  := 6;
     TYPE U IS (EN1, EN2, EN3, EN4);
     TYPE NBOOL IS NEW BOOLEAN;
     NTRUE : NBOOL := TRUE;
     TYPE CHAR IS ('A', 'B', 'C');
     A : CHAR := 'A';

     TASK TK IS
	 ENTRY E1 (S1 RANGE 5 .. 10);
	 ENTRY E2 (INTEGER RANGE 0 .. 20) (I : IN INTEGER);
	 ENTRY E3 (U RANGE EN1 .. EN4);
     END;

     TASK TYPE TT IS
          ENTRY F1 (S1 RANGE 5 .. 10);
          ENTRY F2 (INTEGER RANGE 5 .. 10);
          ENTRY F3 (CHARACTER RANGE 'A' .. 'Z');
          ENTRY F4 (BOOLEAN);
          ENTRY F5 (U);
     END TT;

     TYPE TT_NAME IS ACCESS TT;
     TTN : TT_NAME;

     TASK BODY TK IS
     BEGIN
	  ACCEPT E1 (Y);        -- ERROR: DIFFERENT INDEX BASE TYPES.
	  NULL;
	  ACCEPT E1 (EN2);      -- ERROR: DIFFERENT INDEX BASE TYPES.
	  NULL;
	  ACCEPT E1 (FALSE);    -- ERROR: DIFFERENT INDEX BASE TYPES.
	  NULL;
	  ACCEPT E1 (ASCII.CR); -- ERROR: DIFFERENT INDEX BASE TYPES.
	  NULL;
	  ACCEPT E2 (X)         -- ERROR: DIFFERENT INDEX BASE TYPES.
	       (I : IN INTEGER);
	  NULL;
	  ACCEPT E3 (3);        -- ERROR: DIFFERENT INDEX BASE TYPES.
     END;

     TASK BODY TT IS
     BEGIN
          ACCEPT F1 (Y);        -- ERROR: DIFFERENT INDEX BASE TYPES.
          NULL;
          ACCEPT F2 (X);        -- ERROR: DIFFERENT INDEX BASE TYPES.
          NULL;
          ACCEPT F3 (A);        -- ERROR: DIFFERENT INDEX BASE TYPES.
          NULL;
          ACCEPT F4 (NTRUE);    -- ERROR: DIFFERENT INDEX BASE TYPES.
          NULL;
          ACCEPT F5 
               (U'POS (EN1));   -- ERROR: DIFFERENT INDEX BASE TYPES.
     END TT;

BEGIN

     TK.E1 (Y);                 -- ERROR: DIFFERENT INDEX BASE TYPES.
     TK.E1 (EN2);               -- ERROR: DIFFERENT INDEX BASE TYPES.
     TK.E1 (FALSE);             -- ERROR: DIFFERENT INDEX BASE TYPES.
     TK.E1 (ASCII.CR);          -- ERROR: DIFFERENT INDEX BASE TYPES.
     TK.E2 (X) (17);            -- ERROR: DIFFERENT INDEX BASE TYPES.
     TK.E3 (3);                 -- ERROR: DIFFERENT INDEX BASE TYPES.

     TTN := NEW TT;

     TTN.F1 (Y);                -- ERROR: DIFFERENT INDEX BASE TYPES.
     TTN.F2 (X);                -- ERROR: DIFFERENT INDEX BASE TYPES.
     TTN.F3 (A);                -- ERROR: DIFFERENT INDEX BASE TYPES.
     TTN.F4 (NTRUE);            -- ERROR: DIFFERENT INDEX BASE TYPES.
     TTN.F5 (U'POS (EN1));      -- ERROR: DIFFERENT INDEX BASE TYPES.

END B95001B;
