-- B95082A.ADA

-- FOR ENTRIES HAVING AT LEAST ONE DEFAULT PARAMETER,
-- CHECK THAT:
--        (A) CALLS OF THE FORM T.F(A,,C) ARE FORBIDDEN, WHERE THE
--            SECOND FORMAL PARAMETER HAS A DEFAULT VALUE.
--        (B) FOR A CALL USING ONLY POSITIONAL NOTATION, NO
--            PARAMETER CAN BE OMITTED UNLESS THE DEFAULT
--            PARAMETERS ARE AT THE END OF THE LIST.
--        (C) FOR A CALL USING NAMED NOTATION, OMITTED
--            PARAMETERS MUST HAVE DEFAULT VALUES.

-- JWC 7/17/85

PROCEDURE B95082A IS

     TASK T IS
          ENTRY E1 (X1: INTEGER := 1; X2: INTEGER);
          ENTRY E2 (X1: INTEGER; X2: INTEGER := 2; X3: INTEGER := 3);
     END T;

     TASK BODY T IS
     BEGIN
          NULL;
     END;

BEGIN

     T.E1 (1);              -- ERROR: (B).
     NULL;
     T.E2 (X2=>2, X3=>3);   -- ERROR: (C).
     NULL;
     T.E2 (X2=>2);          -- ERROR: (C).
     NULL;
     T.E2;                  -- ERROR: (C).
     NULL;
     T.E1 (X1=>1);          -- ERROR: (C).
     NULL;

END B95082A;
