-- B95061B.ADA
 
-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A RANGE CONSTRAINT.
 
-- JWC 6/18/85
 
PROCEDURE B95061B IS
 
     TASK T IS
 
          ENTRY E1 ( X : INTEGER RANGE 1..10 );     -- ERROR: RANGE.
 
     END T;
 
     TASK BODY T IS
     BEGIN
          NULL;
     END T;
 
BEGIN
     NULL;
END B95061B;
