-- B95006C.ADA

-- CHECK THAT A NON-IDENTIFIER FORM OF NAME MUST NOT FOLLOW THE "END"
--   OF AN ACCEPT_STATEMENT.

-- SELECTED COMPONENT FORM OF NAME FOR ENTRY FAMILY.

-- JRK 10/29/81

PROCEDURE B95006C IS

     TASK T IS
          ENTRY E1 (I : INTEGER);
          ENTRY E2 (BOOLEAN) (I : INTEGER);
     END T;

     TASK BODY T IS
     BEGIN

          ACCEPT E2 (TRUE) (I : INTEGER) DO
               NULL;
          END T.E2;           -- ERROR: NOT AN IDENTIFIER.

     END T;

BEGIN
     NULL;
END B95006C;
