-- B95061C.ADA
 
-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A FLOATING POINT ACCURRACY CONSTRAINT.
 
-- JWC 6/18/85
 
PROCEDURE B95061C IS
 
     TASK T IS
 
          ENTRY E1 ( X : FLOAT DIGITS 6 );     -- ERROR: DIGITS.
 
     END T;
 
     TASK BODY T IS
     BEGIN
          NULL;
     END T;
 
BEGIN
     NULL;
END B95061C;
