-- B95082F.ADA

-- FOR ENTRIES HAVING AT LEAST ONE DEFAULT PARAMETER,
-- CHECK THAT:
--        (A) CALLS OF THE FORM T.F(A,,C) ARE FORBIDDEN, WHERE THE
--            SECOND FORMAL PARAMETER HAS A DEFAULT VALUE.
--        (B) FOR A CALL USING ONLY POSITIONAL NOTATION, NO
--            PARAMETER CAN BE OMITTED UNLESS THE DEFAULT
--            PARAMETERS ARE AT THE END OF THE LIST.
--        (C) FOR A CALL USING NAMED NOTATION, OMITTED
--            PARAMETERS MUST HAVE DEFAULT VALUES.

-- JWC 7/17/85

PROCEDURE B95082F IS

     TASK T IS
          ENTRY E (X1: INTEGER := 1; X2: INTEGER);
     END T;

     TASK BODY T IS
     BEGIN
          NULL;
     END T;

BEGIN

     T.E (,2);         -- ERROR: (A).
     NULL;

END B95082F;
