-- B95094B.ADA

-- CHECK THAT A SUBPROGRAM CANNOT BE DECLARED IN A TASK BODY WITH THE
-- SAME IDENTIFIER AS THAT OF AN ENTRY FAMILY.

-- JWC 7/22/85

PROCEDURE B95094B IS

     TASK T IS
          ENTRY E (1 .. 10) (X : IN INTEGER);  -- OK: INITIAL DECL.
     END T;

     TASK BODY T IS

          PROCEDURE E IS                -- ERROR: ILLEGAL OVERLOAD.
          BEGIN
               NULL;
          END E;
     BEGIN
          NULL;
     END T;

BEGIN
     NULL;
END B95094B;
