-- B95061D.ADA
 
-- CHECK THAT THE TYPE OF A FORMAL PARAMETER MUST BE DESIGNATED BY A
-- TYPE MARK; IT CANNOT HAVE A FIXED POINT ACCURRACY CONSTRAINT.
 
-- JWC 6/18/85
 
PROCEDURE B95061D IS
 
     TASK T IS
 
          ENTRY E1 ( X : DURATION DELTA 0.01 );     -- ERROR: DELTA.
 
     END T;
 
     TASK BODY T IS
     BEGIN
          NULL;
     END T;
 
BEGIN
     NULL;
END B95061D;
