-- B95003A.ADA

-- CHECK THAT - WITHIN THE OWN TASK BODY - THE ENTRIES OF A TASK ARE
-- NAMED BY THE CORRESPONDING SIMPLE NAMES (NOT BY SELECTED
-- COMPONENTS).

-- WEI  3/ 4/82
-- RJK  2/ 1/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM B950AFA-B.ADA

PROCEDURE B95003A IS

     TASK T1 IS
          ENTRY ET1;
     END T1;

     TASK TYPE TT1 IS
          ENTRY ETT1;
     END TT1;

     OBJ : TT1;

     TASK BODY T1 IS
     BEGIN
          ACCEPT T1.ET1;      -- ERROR: USE SIMPLE NAME FOR OWN ENTRY.
     END T1;

     TASK BODY TT1 IS
     BEGIN
          ACCEPT TT1.ETT1;    -- ERROR: USE SIMPLE NAME FOR OWN ENTRY.
          ACCEPT OBJ.ETT1;    -- ERROR: USE SIMPLE_NAME.
     END TT1;

BEGIN
     NULL;
END B95003A;
