-- B97206A.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN ENTRY CALL IS RENAMED AS A PROCEDURE, THEN THE
--     PROCEDURE NAME CANNOT BE USED TO CALL THE ENTRY IN A CONDITIONAL
--     ENTRY CALL.

-- HISTORY:
--     DHH 03/22/88 CREATED ORIGINAL TEST.

PROCEDURE B97206A IS

     TASK TE IS
          ENTRY INTGR(X : INTEGER);
     END TE;

     PROCEDURE INTGER(X : INTEGER) RENAMES TE.INTGR;

     TASK BODY TE IS
          Y : INTEGER;
     BEGIN
          ACCEPT INTGR(X : INTEGER) DO
               Y := X;
          END INTGR;
     END TE;
BEGIN
     FOR I IN 1 .. INTEGER'LAST LOOP
          SELECT
               INTGER(6);               -- ERROR:
          ELSE
               NULL;
          END SELECT;
     END LOOP;

END B97206A;
