-- B97306A.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN ENTRY CALL IS RENAMED AS A PROCEDURE, THEN THE
--     PROCEDURE NAME CANNOT BE USED IN PLACE OF THE ENTRY NAME IN A
--     TIMED ENTRY CALL.

-- HISTORY:
--     DHH 03/22/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE B97306A IS

     TASK TE IS
          ENTRY INTGR(X : INTEGER);
     END TE;

     PROCEDURE INTEGR(X : INTEGER) RENAMES TE.INTGR;

     PROCEDURE DUMMY IS
     BEGIN
          NULL;
     END DUMMY;

     TASK BODY TE IS
          Y : INTEGER;
     BEGIN
          ACCEPT INTGR(X : INTEGER) DO
               Y := X;
          END INTGR;
     END TE;
BEGIN
     INTEGR(5);

     SELECT
          INTEGR(5);                                 -- ERROR:
     OR
          DELAY 5.0;
          DUMMY;
     END SELECT;

     RESULT;
END B97306A;
