-- BA1020B0.ADA

-- WKB 6/17/81


PACKAGE PAC2PROC IS
     PROCEDURE P (INVOKED : IN OUT BOOLEAN);
END PAC2PROC;


PACKAGE BODY PAC2PROC IS
     PROCEDURE P (INVOKED : IN OUT BOOLEAN) IS SEPARATE;
END PAC2PROC;
