-- BA1020C3.ADA

-- BODY FOR A LIBRARY PACKAGE ONCE DECLARED, BUT LATER REPLACED
-- IN LIBRARY.

-- THIS UNIT SHOULD BE REJECTED, SINCE THE PACKAGE DECLARATION
-- NO LONGER EXISTS.

-- BHS 7/26/84
-- PWB 2/19/86  CLARIFIED COMMENTS, ESPECIALLY REGARDING EXPECTED
--              COMPILER ACTION.

PACKAGE BODY BA1020C1 IS                 -- ERROR: NO LONGER IN LIBRARY.

     PROCEDURE P1 (X : INTEGER) IS
     BEGIN

          NULL;

     END P1;

END BA1020C1;
