-- BA1010A3.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED PROCEDURE
--     BODY MUST CONFORM TO THAT OF THE DECLARED SPECIFICATION.  THIS
--     FILE IS TO BE COMPILED AFTER BA1010A0M.ADA.

-- HISTORY:
--     JET 03/25/88  CREATED ORIGINAL TEST.

FUNCTION BA1010A1 RETURN INTEGER IS        -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     RETURN 0;
END BA1010A1;

PROCEDURE BA1010A2 (I : INTEGER) IS        -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A2;

PROCEDURE BA1010A3 IS                      -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A3;

PROCEDURE BA1010A4 IS                      -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A4;

PROCEDURE BA1010A5 (I,J: IN OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
     J := 0;
END BA1010A5;

FUNCTION BA1010A6 (I : INTEGER) RETURN POSITIVE IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     RETURN 1;
END BA1010A6;

PROCEDURE BA1010A8 (I : IN INTEGER := 2+3) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A8;
