-- BA1010D4.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED GENERIC
--     SUBPROGRAM BODY MUST CONFORM TO THAT OF THE DECLARED
--     SPECIFICATION.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS THAT SUPPORT
--     SEPARATE COMPILATION OF GENERIC SPECIFICATIONS AND BODIES.

-- HISTORY:
--     JET 07/29/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010D2 IS                      -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D2;

PROCEDURE BA1010D3 (I,J: IN OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
     J := 0;
END BA1010D3;

PROCEDURE BA1010D4 (I,J: OUT INTEGER) IS   -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
     J := 0;
END BA1010D4;

PROCEDURE BA1010D5 (I : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D5;

FUNCTION BA1010D6 (J : INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     RETURN 1;
END BA1010D6;

PROCEDURE BA1010D8 (J : IN INTEGER := 5) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D8;
