-- BA1020B6M.ADA

-- CHECK THAT IF A PACKAGE THAT HAS SUBUNITS IS RECOMPILED
--   AS A SUBPROGRAM, THE SUBUNITS ARE NO LONGER ACCESSIBLE.

-- SEPARATE FILES ARE:
--   BA1020B0  A LIBRARY PACKAGE   (PAC2PROC).
--   BA1020B1  A SUBUNIT PROCEDURE (P).
--   BA1020B2  A LIBRARY PROCEDURE (PAC2PROC).
--   BA1020B3  A LIBRARY PACKAGE   (PAC2FUN).
--   BA1020B4  A SUBUNIT FUNCTION  (F).
--   BA1020B5  A LIBRARY FUNCTION  (PAC2FUN).
--   BA1020B6M THE MAIN PROCEDURE.

-- WKB 6/17/81
-- SPS 11/9/82

WITH PAC2PROC, PAC2FUN;
PROCEDURE BA1020B6M IS

     INVOKED : BOOLEAN := FALSE;

BEGIN

     PAC2PROC.P (INVOKED);           -- ERROR: UNACCESSIBLE PROCEDURE.
     INVOKED := FALSE;

     IF PAC2FUN.F THEN               -- ERROR: UNACCESSIBLE FUNCTION.
          INVOKED := FALSE;
     END IF;

END BA1020B6M;
