-- BA1010A4.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED PROCEDURE
--     BODY MUST CONFORM TO THAT OF THE DECLARED SPECIFICATION.  THIS
--     FILE IS TO BE COMPILED AFTER BA1010A0M.ADA.

-- HISTORY:
--     JET 03/25/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010A2 IS                      -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A2;

PROCEDURE BA1010A3 (I,J: IN OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
     J := 0;
END BA1010A3;

PROCEDURE BA1010A4 (I,J: OUT INTEGER) IS   -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
     J := 0;
END BA1010A4;

PROCEDURE BA1010A5 (I : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A5;

FUNCTION BA1010A6 (J : INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     RETURN 1;
END BA1010A6;

PROCEDURE BA1010A8 (J : IN INTEGER := 5) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A8;
