-- BA1010D8.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED GENERIC
--     SUBPROGRAM BODY MUST CONFORM TO THAT OF THE DECLARED
--     SPECIFICATION.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS THAT SUPPORT
--     SEPARATE COMPILATION OF GENERIC SPECIFICATIONS AND BODIES.

-- HISTORY:
--     JET 07/29/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010D2 (I : IN INTEGER := 5) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D2;

PROCEDURE BA1010D5 (I : IN INTEGER; J : OUT POSITIVE) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 1;
END BA1010D5;
