-- BA1010A6.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED PROCEDURE
--     BODY MUST CONFORM TO THAT OF THE DECLARED SPECIFICATION.  THIS
--     FILE IS TO BE COMPILED AFTER BA1010A0M.ADA.

-- HISTORY:
--     JET 03/25/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010A2 (J : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A2;

PROCEDURE BA1010A3 (I : IN OUT POSITIVE) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 1;
END BA1010A3;

PROCEDURE BA1010A4 (I : OUT POSITIVE) IS   -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 1;
END BA1010A4;

PROCEDURE BA1010A5 (J : IN INTEGER; I : OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
END BA1010A5;
