-- BA1010A7.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED PROCEDURE
--     BODY MUST CONFORM TO THAT OF THE DECLARED SPECIFICATION.  THIS
--     FILE IS TO BE COMPILED AFTER BA1010A0M.ADA.

-- HISTORY:
--     JET 03/25/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010A2 (I : IN POSITIVE) IS    -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A2;

PROCEDURE BA1010A5 (J : OUT INTEGER; I : IN INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 0;
END BA1010A5;
