-- BA1020C5.ADA

-- BODY FOR PROCEDURE BA1020C2, DECLARED IN BA1020C2-B.ADA.

-- THIS UNIT SHOULD BE ACCEPTED, SINCE ITS DECLARATION REPLACED
-- THE DECLARATION OF GENERIC PACKAGE BA1020C2 IN THE LIBRARY.

-- BHS 7/26/84
-- PWB 2/19/86  CLARIFIED COMMENTS, ESPECIALLY REGARDING EXPECTED
--              COMPILER ACTION.

PROCEDURE BA1020C2 (Z : BOOLEAN) IS
     I : INTEGER;
BEGIN

     IF Z THEN I := 2;
     ELSE I := 3;
     END IF;

END BA1020C2;
