-- BA1010D5.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED GENERIC
--     SUBPROGRAM BODY MUST CONFORM TO THAT OF THE DECLARED
--     SPECIFICATION.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS THAT SUPPORT
--     SEPARATE COMPILATION OF GENERIC SPECIFICATIONS AND BODIES.

-- HISTORY:
--     JET 07/29/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010D2 (I,J: IN INTEGER) IS    -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D2;

PROCEDURE BA1010D3 (J : IN OUT INTEGER) IS -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 0;
END BA1010D3;

PROCEDURE BA1010D4 (J : OUT INTEGER) IS    -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 0;
END BA1010D4;

FUNCTION BA1010D5 (I : IN INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     RETURN 0;
END BA1010D5;

PROCEDURE BA1010D6 (I : INTEGER; BA1010D6 : OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     BA1010D6 := 5;
END BA1010D6;
