-- BA1020F2M.ADA

-- CHECK THAT COMPILATION OF A PACKAGE BODY IS ILLEGAL IF THERE IS A
-- GENERIC INSTANTIATION FOR A PACKAGE HAVING THE SAME IDENTIFIER.

-- JBG 5/28/85

PACKAGE BODY BA1020F1_PACK IS      -- ERROR: NO PACKAGE SPECIFICATION.
BEGIN
     NULL;
END;

PROCEDURE BA1020F2M IS
BEGIN
     NULL;
END BA1020F2M;
