-- BA1010A5.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED PROCEDURE
--     BODY MUST CONFORM TO THAT OF THE DECLARED SPECIFICATION.  THIS
--     FILE IS TO BE COMPILED AFTER BA1010A0M.ADA.

-- HISTORY:
--     JET 03/25/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010A2 (I,J: IN INTEGER) IS    -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010A2;

PROCEDURE BA1010A3 (J : IN OUT INTEGER) IS -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 0;
END BA1010A3;

PROCEDURE BA1010A4 (J : OUT INTEGER) IS    -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 0;
END BA1010A4;

FUNCTION BA1010A5 (I : IN INTEGER; J : OUT INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     J := 0;
     RETURN 0;
END BA1010A5;

PROCEDURE BA1010A6 (I : INTEGER; BA1010A6 : OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     BA1010A6 := 5;
END BA1010A6;
