-- BA1010D1.ADA

-- OBJECTIVE:
--     CHECK THAT THE SPECIFICATION OF A SEPARATELY COMPILED GENERIC
--     SUBPROGRAM BODY MUST CONFORM TO THAT OF THE DECLARED
--     SPECIFICATION.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS THAT SUPPORT
--     SEPARATE COMPILATION OF GENERIC SPECIFICATIONS AND BODIES.

-- HISTORY:
--     JET 07/29/88  CREATED ORIGINAL TEST.

PROCEDURE BA1010D1 (I : INTEGER := 5) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D1;

PROCEDURE BA1010D2 (I : IN OUT INTEGER) IS -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     I := 0;
END BA1010D2;

PROCEDURE BA1010D3 (I : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D3;

PROCEDURE BA1010D4 (I : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D4;

PROCEDURE BA1010D5 (I: IN INTEGER; J: IN INTEGER) IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D5;

FUNCTION BA1010D6 (I : IN INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     RETURN 1;
END BA1010D6;

PROCEDURE BA1010D7 (I : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D7;

PROCEDURE BA1010D8 (I : IN INTEGER) IS     -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA1010D8;
