-- BA1101A.ADA

-- CHECK THAT THE NAMES IN A WITH_CLAUSE CANNOT BE 
--   ASCII, TRUE, OR FALSE.

-- WKB 6/18/81
-- BHS 7/19/84


WITH ASCII;                   -- ERROR: PACKAGE DECLARED IN STANDARD.
WITH TRUE;                    -- ERROR: NOT LIBRARY UNIT.
WITH FALSE;                   -- ERROR: NOT LIBRARY UNIT.
PROCEDURE BA1101A1 IS
BEGIN
     NULL;
END BA1101A1;


WITH SYSTEM;
USE ASCII;                    -- ERROR: NO WITH_CLAUSE.
PROCEDURE BA1101A2 IS
BEGIN
     NULL;
END BA1101A2;
