-- BA1101G.ADA

-- CHECK THAT A USE_CLAUSE CANNOT MENTION A NAME MADE VISIBLE BY A
-- PRECEDING USE_CLAUSE IN THE SAME CONTEXT SPECIFICATION.

-- BHS 7/24/84

PACKAGE BA1101G_PKG IS

     PACKAGE P IS
          I : INTEGER;
     END P;

END BA1101G_PKG;


WITH BA1101G_PKG;
USE BA1101G_PKG;
USE P;                   -- ERROR: NOT NAMED IN PRECEDING WITH CLAUSE.
PROCEDURE BA1101G IS
BEGIN

     NULL;

END BA1101G;
