-- BA1101D.ADA

-- CHECK THAT "WITH STANDARD;" IS NOT PERMITTED IF 
--   THERE IS NO USER-DEFINED LIBRARY UNIT CALLED STANDARD.

-- WKB 6/19/81

WITH STANDARD;          -- ERROR: NO USER-DEFINED STANDARD LIBRARY UNIT.

PROCEDURE BA1101D IS

BEGIN

     NULL;

END BA1101D;
