-- BA1109A1.ADA

-- CHECK THAT A NAME DECLARED BY A RENAMING DECLARATION CANNOT BE USED 
-- IN A WITH CLAUSE OF A CONTEXT CLAUSE.

-- SEPARATE FILES ARE:
--     BA1109A0     PACKAGE SPEC WITH RENAMING DECLARATION FOR Q.
--     BA1109A2M    MAIN PROCEDURE TESTING USE CLAUSE.

-- TBN 2/10/86

WITH BA1109A0; USE BA1109A0;
WITH Q;                                                      -- ERROR: Q

PACKAGE BA1109A1 IS
END BA1109A1;
