-- BA1110A0.ADA

-- THIS PACKAGE IS USED BY BA1110A1M TO CHECK THE USE OF "USE 
-- <PACKAGE_NAME>" IN THE SUBUNIT WHEN <PACKAGE_NAME> ONLY APPEARS
-- IN A WITH CLAUSE OF ANCESTOR LIBRARY UNIT.

-- THIS UNIT SHOULD COMPILE CORRECTLY.

-- TBN 2/10/86

PACKAGE BA1110A0 IS

END BA1110A0;
