-- BA1110A1M.ADA

-- CHECK THAT A USE CLAUSE FOR A SUBUNIT CANNOT NAME A PACKAGE THAT IS
-- ONLY NAMED IN A WITH CLAUSE OF AN ANCESTOR UNIT.

-- THE FOLLOWING FILES DEPEND ON EACH OTHER:
--           BA1110A0  - A PACKAGE.
--           BA1110A1M - THE MAIN PROCEDURE.
--           BA1110A2  - A SEPARATE PACKAGE SUBUNIT.
--           BA1110A3  - A SEPARATE PROCEDURE SUBUNIT.
--           BA1110A4  - A SEPARATE FUNCTION SUBUNIT.
--           BA1110A5  - A SEPARATE TASK SUBUNIT.
-- THIS UNIT SHOULD COMPILE CORRECTLY.

-- TBN 2/10/86

WITH BA1110A0;
PROCEDURE BA1110A1M IS

     PACKAGE BA1110A2 IS
     END BA1110A2;

     PACKAGE BODY BA1110A2 IS SEPARATE;

     PROCEDURE BA1110A3 IS SEPARATE;

     FUNCTION BA1110A4 RETURN BOOLEAN IS SEPARATE;

     TASK BA1110A5;

     TASK BODY BA1110A5 IS SEPARATE;

-------------------------------------------

BEGIN          -- (MAIN)
     NULL;
END BA1110A1M;
