-- BA2001D.ADA

-- CHECK THAT A BODY_STUB CANNOT BE GIVEN FOR A SUBPROGRAM
--   NAMED WITH AN OPERATOR SYMBOL.

-- WKB 6/24/81

PROCEDURE BA2001D IS

     FUNCTION "*" (X, Y : INTEGER) RETURN INTEGER IS SEPARATE; -- ERROR:
                                        -- ILLEGAL NAME FOR BODY_STUB.

BEGIN
     NULL;
END BA2001D;
