-- BA2001B.ADA

-- CHECK THAT A PACKAGE OR TASK BODY_STUB CANNOT BE GIVEN UNLESS THERE 
--   HAS BEEN A PRECEDING SPECIFICATION FOR THE STUB.

-- WKB 6/24/81
-- JRK 6/24/81

PROCEDURE BA2001B IS

     PACKAGE BODY PKG IS SEPARATE; -- ERROR: NO PACKAGE SPECIFICATION.
     TASK BODY TSK IS SEPARATE;    -- ERROR: NO TASK SPECIFICATION.

BEGIN
     NULL;
END BA2001B;
