-- BA2011A2.ADA

-- OBJECTIVE:
--     CHECK THAT A BODY STUB MUST CONFORM TO A PRECEDING DECLARATION,
--     AND A PROPER BODY MUST CONFORM WITH ITS STUB.

-- HISTORY:
--     JET 07/07/88  CREATED ORIGINAL TEST.

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_1 (I : INTEGER) IS       -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_1;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_2 (I: IN OUT INTEGER) IS -- ERROR: DOESN'T MATCH STUB.
BEGIN
     I := 0;
END BA2011A_2;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_3 (I : IN INTEGER) IS    -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_3;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_4 (I : IN INTEGER) IS    -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_4;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_5 (I: IN INTEGER; J: IN INTEGER) IS
                                           -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_5;

SEPARATE (BA2011A1M)
FUNCTION BA2011A_6 (I : INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH STUB.
BEGIN
     RETURN 1;
END BA2011A_6;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_7 (I : IN INTEGER) IS    -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_7;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_8 (I : IN INTEGER) IS    -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_8;
