-- BA2011A9.ADA

-- OBJECTIVE:
--     CHECK THAT A BODY STUB MUST CONFORM TO A PRECEDING DECLARATION,
--     AND A PROPER BODY MUST CONFORM WITH ITS STUB.

-- HISTORY:
--     JET 07/07/88  CREATED ORIGINAL TEST.

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_2 (I: IN INTEGER := 5) IS
                                           -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_2;

SEPARATE (BA2011A1M)
FUNCTION BA2011A_5 (I : INTEGER; J : INTEGER) RETURN INTEGER IS
                                           -- ERROR: DOESN'T MATCH STUB.
BEGIN
     RETURN 0;
END BA2011A_5;
