-- BA2011A0.ADA

-- OBJECTIVE:
--     CHECK THAT A BODY STUB MUST CONFORM TO A PRECEDING DECLARATION,
--     AND A PROPER BODY MUST CONFORM WITH ITS STUB.

-- SEPARATE FILES ARE:
--     BA2011A0.ADA  - SPECIFICATIONS AND MISMATCHED STUBS FOR
--                     SUBPROGRAMS BA2011A_*.
--     BA2011A1M.ADA - SPECIFICATIONS AND MATCHING STUBS FOR
--                     SUBPROGRAMS BA2011A_*.  THIS FILE SHOULD COMPILE
--                     WITHOUT ERRORS.
--     BA2011A2.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_1-8.
--     BA2011A3.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_1-8.
--     BA2011A4.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_2-6,8.
--     BA2011A5.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_2-5,8.
--     BA2011A6.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_2-5.
--     BA2011A7.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_2-5.
--     BA2011A8.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_2,3,5.
--     BA2011A9.ADA  - PROPER BODIES FOR SUBPROGRAM STUBS BA2011A_2,5.

-- HISTORY:
--     JET 07/07/88  CREATED ORIGINAL TEST.

PROCEDURE BA2011A0 IS
     PROCEDURE BA2011A_1;
     PROCEDURE BA2011A_2 (I : IN INTEGER);
     PROCEDURE BA2011A_3 (I : IN OUT INTEGER);
     PROCEDURE BA2011A_4 (I : OUT INTEGER);
     PROCEDURE BA2011A_5 (I : INTEGER; J : INTEGER);
     FUNCTION BA2011A_6 RETURN INTEGER;
     PROCEDURE BA2011A_7 (I : INTEGER);
     PROCEDURE BA2011A_8 (I : IN INTEGER := 5);

     PROCEDURE BA2011A_1 (I : INTEGER) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_2 (I : INTEGER) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_3 (I : OUT INTEGER) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_4 (J : OUT INTEGER) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_5 (I, J : INTEGER) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_6 (I : OUT INTEGER) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_7 (I : FLOAT) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
     PROCEDURE BA2011A_8 (I : IN INTEGER := 2+3) IS SEPARATE;
                                        -- ERROR: DOESN'T MATCH SPEC.
BEGIN
     NULL;
END BA2011A0;
