-- BA2001A.ADA

-- CHECK THAT A BODY STUB CANNOT BE GIVEN IN A DECLARATIVE PART
--   PHYSICALLY ENCLOSED BY ANOTHER DECLARATIVE PART.

-- WKB 6/24/81

PROCEDURE BA2001A IS

     PROCEDURE P IS
          PROCEDURE Q IS SEPARATE; -- ERROR: BODY_STUB NOT IN OUTERMOST 
                                   --        DECLARATIVE PART.
     BEGIN
          NULL;
     END P;

     PACKAGE R IS
     END R;

     PACKAGE BODY R IS
          PROCEDURE S IS SEPARATE; -- ERROR: BODY_STUB NOT IN OUTERMOST
                                   --        DECLARATIVE PART.
     END R;

BEGIN
     DECLARE
          PROCEDURE T IS SEPARATE; -- ERROR: BODY_STUB NOT IN OUTERMOST
                                   --        DECLARATIVE PART.
     BEGIN
          NULL;
     END;

END BA2001A;
