-- BA2001G0M.ADA

-- CHECK THAT THE FULL PATH NAME OF THE PARENT OF A SUBUNIT CANNOT
--   BE WRITTEN FOLLOWING 'SEPARATE' AS STANDARD.NAME.

-- SEPARATE FILES ARE:
--   BA2001G0M THE MAIN PROCEDURE.
--   BA2001G1  A SUBUNIT PROCEDURE BODY.

-- WKB 6/24/81

PROCEDURE BA2001G0M IS

     PROCEDURE BA2001G1 IS SEPARATE;

BEGIN
     NULL;
END BA2001G0M;
