-- BA2001C.ADA

-- CHECK THAT TWO BODY STUBS IN THE SAME DECLARATIVE PART
--   CANNOT CONTAIN OVERLOADED SUBPROGRAM SPECIFICATIONS.

-- WKB 6/24/81

PROCEDURE BA2001C IS

     PROCEDURE P(I : INTEGER) IS SEPARATE;
     PROCEDURE P(I : BOOLEAN) IS SEPARATE;     -- ERROR: SUBUNIT NAME
                                               --        NOT DISTINCT.

     FUNCTION F RETURN INTEGER IS SEPARATE;
     FUNCTION F RETURN BOOLEAN IS SEPARATE;    -- ERROR: SUBUNIT NAME 
                                               --        NOT DISTINCT.

BEGIN
     NULL;
END BA2001C;
