-- BA2013B.ADA

-- CHECK THAT AN IDENTIFIER DECLARED IN A LIBRARY PACKAGE NAMED IN A
-- USE_CLAUSE IS NOT VISIBLE IN A SUBUNIT IF THE IDENTIFIER IS DECLARED
-- IN A PARENT UNIT AND IS DIRECTLY VISIBLE AT THE STUB.

-- BHS 8/07/84

PROCEDURE BA2013B IS

     VAR : INTEGER;
     F : FLOAT;
     PROCEDURE BA2013B_SUB IS SEPARATE;

BEGIN
     NULL;
END BA2013B;


PACKAGE BA2013B_PACK IS

     VAR : BOOLEAN := FALSE;
     FUNCTION F RETURN BOOLEAN;

END BA2013B_PACK;

PACKAGE BODY BA2013B_PACK IS

     FUNCTION F RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END F;

END BA2013B_PACK;

WITH BA2013B_PACK;
USE BA2013B_PACK;
SEPARATE (BA2013B)
PROCEDURE BA2013B_SUB IS
BEGIN
     
     IF NOT VAR THEN          -- ERROR: ONLY BA2013B.VAR VISIBLE.
          NULL;
     END IF;

     VAR := 5;                      -- OK.

     IF NOT BA2013B_PACK.VAR THEN   -- OK.
          NULL;
     END IF;

     IF F THEN                -- ERROR: ONLY BA2013B.F VISIBLE.
          NULL;
     END IF;

     F := 6.0;                      -- OK.

     IF BA2013B_PACK.F THEN         -- OK.
          NULL;
     END IF;

END BA2013B_SUB;
