-- BA2001E5.ADA

-- EG  11/18/85  ALLOW SUBUNIT DUPLICATION TO BE DETECTED WHEN SUBUNIT
--               IS COMPILED.

SEPARATE (BA2001E0M.BA2001E1)

PACKAGE BODY BA2001E5 IS      -- OPTIONAL ERROR: REPEATED SUBUNIT
                              --                 IDENTIFIER.

BEGIN

     NULL;

END BA2001E5;
