-- BA2011A5.ADA

-- OBJECTIVE:
--     CHECK THAT A BODY STUB MUST CONFORM TO A PRECEDING DECLARATION,
--     AND A PROPER BODY MUST CONFORM WITH ITS STUB.

-- HISTORY:
--     JET 07/07/88  CREATED ORIGINAL TEST.

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_2 IS                     -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_2;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_3 (I,J: IN OUT INTEGER) IS
                                           -- ERROR: DOESN'T MATCH STUB.
BEGIN
     I := 0;
     J := 0;
END BA2011A_3;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_4 (I,J: OUT INTEGER) IS  -- ERROR: DOESN'T MATCH STUB.
BEGIN
     I := 0;
     J := 0;
END BA2011A_4;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_5 (I : INTEGER) IS       -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_5;

SEPARATE (BA2011A1M)
PROCEDURE BA2011A_8 (J : IN INTEGER := 5) IS
                                           -- ERROR: DOESN'T MATCH STUB.
BEGIN
     NULL;
END BA2011A_8;
