-- BA3001E0M.ADA

-- CHECK THAT A SUBUNIT CANNOT BE COMPILED IF ITS
--   PARENT HAS NOT BEEN COMPILED.

-- SEPARATE FILES ARE:
--   BA3001E0M THE MAIN PROCEDURE.
--   BA3001E1  A SUBUNIT PROCEDURE BODY.
--   BA3001E2  A SUBUNIT FUNCTION BODY.
--   BA3001E3  A SUBUNIT PACKAGE BODY.

-- WKB 7/1/81
-- JRK 7/2/81

PROCEDURE BA3001E0M IS

     PROCEDURE UNCOMPILED1 IS SEPARATE;

     PACKAGE UNCOMPILED3 IS
     END UNCOMPILED3;

     PACKAGE BODY UNCOMPILED3 IS SEPARATE;

BEGIN

     NULL;

END BA3001E0M;
