-- BA3001D0M.ADA

-- CHECK THAT A SUBPROGRAM BODY CANNOT BE COMPILED IF ANY UNITS
--   MENTIONED IN ITS WITH_CLAUSES HAVE NOT BEEN COMPILED.

-- SEPARATE FILES ARE:
--   BA3001D0M THE MAIN PROCEDURE.
--   BA3001D1  A LIBRARY FUNCTION BODY.

-- WKB 7/1/81
-- JRK 3/26/84


WITH UNCOMPILED;                       -- ERROR: UNIT NOT COMPILED.

PROCEDURE BA3001D0M IS

BEGIN

     NULL;

END BA3001D0M;


FUNCTION BA3001D1 RETURN INTEGER;
