-- BB2003B.ADA

-- CHECK THAT OTHERS CAN ONLY APPEAR AT THE END OF AN
-- EXCEPTION-HANDLER.

-- DCB 05/07/80
-- JRK 11/17/80
-- ABW 06/10/82

PROCEDURE BB2003B IS

     I1 : INTEGER;

     PROCEDURE P IS
          IA : INTEGER;
     BEGIN
          IA := 1;
     EXCEPTION
          WHEN OTHERS =>            -- ERROR: 'OTHERS' NOT LAST.
               NULL;
          WHEN CONSTRAINT_ERROR =>
               NULL;
     END P;

BEGIN
     NULL;

END BB2003B;
