-- BB2003A.ADA

--  CHECK THAT OTHERS CAN ONLY APPEAR BY ITSELF IN AN
--  EXCEPTION-HANDLER.

-- DCB 05/07/80
-- JRK 11/17/80
-- ABW 06/09/82

PROCEDURE BB2003A IS

     E1, E2 : EXCEPTION;

     PROCEDURE P IS
          IA : INTEGER;
     BEGIN
          IA := 1;
     EXCEPTION
          WHEN E1 | OTHERS | E2 =>  -- ERROR: 'OTHERS' NOT ALONE.
               NULL;
     END P;

BEGIN
     NULL;

END BB2003A;
