-- BB2001A.ADA

-- CHECK THAT NAMES THAT ARE NOT EXCEPTIONS CANNOT BE THE
--    NAME OF A HANDLER.

-- DCB 05/07/80
-- JRK 11/17/80
-- SPS 3/23/83

PROCEDURE BB2001A IS

     I1 : INTEGER;
     E1 : EXCEPTION;

BEGIN

     I1 := 1;

EXCEPTION
     WHEN CONSTRAINT_ERROR =>
          NULL;
     WHEN E9 =>       -- ERROR: EXCEPTION NAME  E9  NOT DECLARED.
          NULL;
     WHEN NUMERIC_ERROR |
            E8 |      -- ERROR: EXCEPTION NAME  E8  NOT DECLARED.
            STORAGE_ERROR =>
          NULL;
     WHEN E1 =>
          NULL;
     WHEN I1 =>       -- ERROR: HANDLER NAME IS NOT AN EXCEPTION.
          NULL;
END BB2001A;
