-- BB3001A.ADA

-- CHECK THAT THE IDENTIFIER MENTIONED IN A RAISE STATEMENT
--    MUST BE AN EXCEPTION.

-- DCB 04/01/80
-- JRK 11/19/80
-- VKG 01/07/83
-- JBG 4/19/83

PROCEDURE BB3001A IS

     I9 : INTEGER := 9;
     C9 : CHARACTER := 'X';
     B9 : BOOLEAN := FALSE;
     E1 : EXCEPTION;

BEGIN
     I9 := 9;

     BEGIN
          RAISE I9;     -- ERROR: RAISING A NON-EXCEPTION.
     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

     BEGIN
          RAISE C9;     -- ERROR: RAISING A NON-EXCEPTION.
     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

     BEGIN
          RAISE E1;     -- LEGAL RAISE STATEMENT.
     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

     BEGIN
          RAISE B9;     -- ERROR: RAISING A NON-EXCEPTION.
     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

     BEGIN
          RAISE NUMERIC_ERROR; -- LEGAL RAISE STATEMENT.
     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

     BEGIN
          RAISE E;      -- ERROR: E NOT DECLARED.
     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

     DECLARE

          CONSTRAINT_ERROR,
          NUMERIC_ERROR,
          PROGRAM_ERROR,
          STORAGE_ERROR,
          TASKING_ERROR : INTEGER := 1;

     BEGIN
          -- THE FOLLOWING STATEMENTS ATTEMPT TO RAISE EXCEPTION NAMES
          -- WHICH HAVE BEEN REDECLARED AS INTEGER.

          RAISE CONSTRAINT_ERROR;  -- ERROR: RAISING A NON-EXCEPTION.
          NULL;
          RAISE NUMERIC_ERROR;     -- ERROR: RAISING A NON-EXCEPTION.
          NULL;
          RAISE PROGRAM_ERROR;      -- ERROR: RAISING A NON-EXCEPTION.
          NULL;
          RAISE STORAGE_ERROR;     -- ERROR: RAISING A NON-EXCEPTION.
          NULL;
          RAISE TASKING_ERROR;     -- ERROR: RAISING A NON-EXCEPTION.
          NULL;

     EXCEPTION
          WHEN OTHERS =>
               NULL;
     END;

END BB3001A;
