-- BC1008C.ADA

-- CHECK THAT GENERIC PARTS CANNOT OMIT A SEMICOLON AFTER A PARAMETER.

-- DAT 8/6/81

PROCEDURE BC1008C IS

     GENERIC P : INTEGER PACKAGE IP3 IS      -- ERROR: MISSING ";".
     END IP3;

BEGIN
     NULL;
END BC1008C;
