-- BC1008B.ADA

-- CHECK THAT GENERIC PARTS CANNOT USE COMMAS INSTEAD OF SEMICOLONS.

-- DAT 8/6/81

PROCEDURE BC1008B IS

     GENERIC P:INTEGER, Q:INTEGER; PACKAGE   -- ERROR: ",".
     P2 IS END P2;

BEGIN
     NULL;
END BC1008B;
