-- BC1016B.ADA

-- CHECK THAT A GENERIC UNIT IS EITHER A GENERIC SUBPROGRAM
-- (PROCEDURE OR FUNCTION) OR A GENERIC PACKAGE AND NOTHING
-- ELSE, E.G. IT MAY NOT BE A GENERIC TASK TYPE.

-- KEI 3/4/82
-- RJK 1/23/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM BC10ABB-B.ADA

PROCEDURE BC1016B IS

     GENERIC
          I : INTEGER;
     TASK TYPE T_T;                -- ERROR: TASK TYPE

     TASK BODY T_T IS
     BEGIN
          NULL;
     END T_T;

BEGIN
     NULL;
END BC1016B;
