-- BC1011A.ADA

-- CHECK THAT A GENERIC SUBPROGRAM (I.E. THE TEMPLATE) CANNOT BE
-- USED AS THE CALLED SUBPROGRAM IN A SUBPROGRAM CALL (I.E. AN
-- INSTANTIATION SHOULD BE USED).

-- ASL 8/7/81

PROCEDURE BC1011A IS
 
     A,B : INTEGER := 7;

     GENERIC
     PROCEDURE TEMPLATE(X,Y : IN OUT INTEGER);

     PROCEDURE TEMPLATE(X,Y : IN OUT INTEGER) IS
     BEGIN
          NULL;
     END TEMPLATE;

BEGIN
     DECLARE
         PROCEDURE INSTANCE IS NEW TEMPLATE;
     BEGIN
          INSTANCE(A,B);                       -- OK.
          TEMPLATE(A,B);                       -- ERROR: TEMPLATE.
     END;
END BC1011A;
