-- BC1014A.ADA

-- CHECK THAT THE IDENTIFIER OF A GENERIC SUBPROGRAM IS NOT
-- OVERLOADABLE.

-- KEI 3/4/82
-- RJK 1/24/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM BC10AFA-B.ADA

PROCEDURE BC1014A IS

     GENERIC
          T : INTEGER;
     PROCEDURE CHECK (X : STRING);

     GENERIC
     PROCEDURE CHECK (X : INTEGER);       -- ERROR: OVERLOADING

     P1 : INTEGER := 15;

     PROCEDURE CHECK (X : STRING) IS
     BEGIN
          NULL;
     END CHECK;

     PROCEDURE CHECK (X : INTEGER) IS
     BEGIN
          NULL;
     END CHECK;

BEGIN
     NULL;
END BC1014A;
