-- BC1008A.ADA

-- CHECK THAT GENERIC PARTS CANNOT BE ENCLOSED IN PARENTHESES.

-- DAT 8/6/81

PROCEDURE BC1008A IS

     GENERIC (P : INTEGER) PACKAGE P1        -- ERROR: ()'S
     IS END P1;

     GENERIC P : INTEGER; PACKAGE P3 IS      -- OK.
     END P3;

BEGIN
     NULL;
END BC1008A;
