-- BC1014B.ADA

-- CHECK THAT THE IDENTIFIER OF A GENERIC SUBPROGRAM
--   IS NOT OVERLOADABLE.

-- CASE B: DIFFERENT NUMBERS OF PARAMETERS.

-- PWB  1/24/86

PROCEDURE BC1014B IS

     GENERIC
          T : INTEGER;
     PROCEDURE CHECK (X : STRING);

     GENERIC
     PROCEDURE CHECK (X : STRING; Y : INTEGER);     -- ERROR: OVERLOAD.

     PROCEDURE CHECK (X : STRING) IS
     BEGIN
          NULL;
     END CHECK;

     PROCEDURE CHECK (X : STRING; Y : INTEGER) IS   -- OPTIONAL ERROR.
     BEGIN
          NULL;
     END CHECK;

BEGIN  -- BC1014B
     NULL;
END BC1014B;
