-- BC1005A.ADA
-- CHECK THAT THE IDENTIFIER OF A GENERIC UNIT CANNOT BE USED IN ITS
-- GENERIC FORMAL PART AS A:

-- CASES:
--     A) TYPEMARK.
--     B) PRIMARY IN AN EXPRESSION.
--     C) FUNCTION NAME IN FUNCTION CALL.
--     D) PREFIX OF INDEXED COMPONENT.
--     E) PREFIX OF A SLICE.
--     F) PREFIX OF A SELECTED COMPONENT.
--     G) PREFIX OF AN ATTRIBUTE.
--     H) DEFAULT NAME IN FORMAL SUBPROGRAM DECLARATION.
--     I) SELECTOR OF EXPANDED NAME WHOSE PREFIX DENOTES A UNIT 
--        ENCLOSING THE GENERIC DECLARATION.

-- FOR A GENERIC FUNCTION, CHECK THAT THE FUNCTION IS NOT CONSIDERED 
-- OVERLOADABLE WITHIN ITS GENERIC FORMAL PART.

-- AH  10/1/86

WITH REPORT; USE REPORT;
PROCEDURE BC1005A IS
     PACKAGE PKG IS
          TYPE TM IS RANGE 1..10;
          TYPE ARR1 IS ARRAY (1..5) OF INTEGER;
          TYPE ARR2 IS ARRAY (1..3) OF INTEGER;
          TYPE ATT_TYPE IS RANGE 1..5;
          SUBTYPE SUB_ATT_TYPE IS ATT_TYPE;

          TYPE REC_TYPE IS
               RECORD
                    REC_OBJ : INTEGER := IDENT_INT(2);
               END RECORD;

          PRIM : CONSTANT INTEGER := 5;
          ARR_OBJ1 : ARR1 := (1..5 => 1);
          ARR_OBJ2 : ARR2 := (1..3 => 2);
          REC : REC_TYPE;
          OBJ_10 : INTEGER := IDENT_INT(2);

          FUNCTION FUNC1 RETURN INTEGER;

          FUNCTION FUNC2 RETURN INTEGER;

          FUNCTION FUNC3 RETURN INTEGER;

          FUNCTION FUNC4 (X : FLOAT) RETURN INTEGER;
     END PKG;
     USE PKG;

     GENERIC
          WITH FUNCTION GEN_1 RETURN TM;             -- ERROR: A.
     PACKAGE TM IS END TM;

     GENERIC 
          GEN2_OBJ : INTEGER := PRIM + IDENT_INT(5); -- ERROR: B.
     PROCEDURE PRIM;

     GENERIC 
          GEN3_OBJ : INTEGER := FUNC1;               -- ERROR: C.
     PROCEDURE FUNC1;

     GENERIC
          GEN4_OBJ : INTEGER := FUNC2;               -- ERROR: C.
     PACKAGE FUNC2 IS END FUNC2;

     GENERIC
          GEN5_OBJ : INTEGER := ARR_OBJ1(3);         -- ERROR: D.
     PROCEDURE ARR_OBJ1;

     GENERIC
          GEN6_OBJ : ARR2 := ARR_OBJ2(3..5);         -- ERROR: E.
     PACKAGE ARR_OBJ2 IS END ARR_OBJ2;

     GENERIC
          GEN7_OBJ : INTEGER := REC.REC_OBJ;         -- ERROR: F.
     FUNCTION REC RETURN INTEGER;

     GENERIC
          GEN8_OBJ : SUB_ATT_TYPE := ATT_TYPE'LAST;  -- ERROR: G.
     PACKAGE ATT_TYPE IS END ATT_TYPE;

     GENERIC
          WITH FUNCTION GEN_FUNC RETURN INTEGER 
               IS FUNC3;                             -- ERROR: H.
     PROCEDURE FUNC3;

     PACKAGE EN IS
          P_OBJ : INTEGER := IDENT_INT(0);
          GENERIC
               GEN9_OBJ : INTEGER := EN.P_OBJ;       -- ERROR: I.
          PROCEDURE EN;
     END EN;

     PACKAGE BODY EN IS
          PROCEDURE EN IS
          BEGIN
               NULL;
          END EN;
     END EN;

     GENERIC
          GEN10_OBJ : INTEGER := FUNC4(1.0);     -- ERROR: FUNCTION NOT
                                                 --        OVERLOADABLE.
     FUNCTION FUNC4 (X : INTEGER) RETURN INTEGER;

     PROCEDURE PRIM IS
     BEGIN
          NULL;
     END PRIM;

     PROCEDURE FUNC1 IS
     BEGIN
          NULL;
     END FUNC1;

     PROCEDURE ARR_OBJ1 IS
     BEGIN
          NULL;
     END ARR_OBJ1;

     FUNCTION REC RETURN INTEGER IS
     BEGIN
          RETURN IDENT_INT(1);
     END REC;

     PROCEDURE FUNC3 IS
     BEGIN
          NULL;
     END FUNC3;

     FUNCTION FUNC4 (X : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN IDENT_INT(4);
     END FUNC4;

     PACKAGE BODY PKG IS
          FUNCTION FUNC1 RETURN INTEGER IS
          BEGIN
               RETURN IDENT_INT(2);
          END FUNC1;

          FUNCTION FUNC2 RETURN INTEGER IS
          BEGIN
               RETURN IDENT_INT(3);
          END FUNC2;

          FUNCTION FUNC3 RETURN INTEGER IS
          BEGIN
               RETURN IDENT_INT(1);
          END FUNC3;
 
          FUNCTION FUNC4 (X : FLOAT) RETURN INTEGER IS
          BEGIN
               RETURN IDENT_INT(4);
          END FUNC4;
     END PKG;

BEGIN
     NULL;
END BC1005A;
