-- BC1011C.ADA

-- CHECK THAT A GENERIC FUNCTION CAN NOT BE USED AS A
-- CALLED FUNCTION

-- KEI 3/4/82
-- RJK 1/23/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM BC10ACA-B.ADA

PROCEDURE BC1011C IS

     GENERIC
     FUNCTION F1 (F : BOOLEAN) RETURN BOOLEAN;

     FUNCTION F1 (F : BOOLEAN) RETURN BOOLEAN IS
     BEGIN
          RETURN FALSE;
     END F1;

BEGIN
     DECLARE
          P, B : BOOLEAN := TRUE;

          FUNCTION G1 IS NEW F1;
          FUNCTION G2 IS NEW F1;

     BEGIN
          B := NOT G1 (P) ;     -- OK.
          B := F1 (P);          -- ERROR: GENERIC
          B := G2 (B);          -- OK.
     END;
END BC1011C;
