-- BC1016A.ADA

-- CHECK THAT A GENERIC UNIT IS EITHER A GENERIC SUBPROGRAM
-- (PROCEDURE OR FUNCTION) OR A GENERIC PACKAGE AND NOTHING
-- ELSE, E.G. IT MAY NOT BE A GENERIC TASK

-- KEI 3/4/82
-- RJK 1/23/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM BC10ABA-B.ADA

PROCEDURE BC1016A IS

     GENERIC
          I : INTEGER := 1;
     PROCEDURE PROC;                    -- OK. PROCEDURE

     GENERIC
          P1 : INTEGER;
     FUNCTION F1 RETURN INTEGER;        -- OK. FUNCTION

     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;

     FUNCTION F1 RETURN INTEGER IS
     BEGIN
          RETURN 0;
     END F1;

     GENERIC
          I, J : INTEGER;
     PACKAGE P1 IS
     END P1;                       -- OK. PACKAGE

     GENERIC
          TYPE P_T IS RANGE <>;
     TASK S_T IS                   -- ERROR: SINGLE TASK
         ENTRY E0;
     END S_T;

     TASK BODY S_T IS
     BEGIN
         NULL;
     END S_T;

BEGIN
     NULL;
END BC1016A;
