-- BC1109B.ADA

-- CHECK THAT A GENERIC FORMAL OBJECT DECLARATION
--     MAY NOT SPECIFY AN ACCURACY CONSTRAINT.

-- PWB   1/24/86

PROCEDURE BC1109B IS

     TYPE FLOATING IS DIGITS 4 RANGE -1.0 .. 1.0;
     TYPE FIXED IS DELTA 0.01 RANGE -1.0 .. 1.0;

     GENERIC
          FL : IN OUT FLOATING DIGITS 2;   -- ERROR: CONSTRAINT.
          FI : FIXED DELTA 0.1;            -- ERROR: CONSTRAINT.
     PACKAGE PKG IS
     END PKG;

     GENERIC
          FL : FLOATING DIGITS 2;          -- ERROR: CONSTRAINT.
          FI : IN OUT FIXED DELTA 0.1;     -- ERROR: CONSTRAINT.
     FUNCTION CHECK ( X : INTEGER ) RETURN BOOLEAN;

     FUNCTION CHECK ( X : INTEGER ) RETURN BOOLEAN IS
     BEGIN
          RETURN FALSE;
     END CHECK;

BEGIN     -- BC1109B
     NULL;
END BC1109B;
