-- BC1109A.ADA

-- CHECK THAT A FORMAL GENERIC OBJECT DECLARATION
--     MAY NOT SPECIFY A RANGE CONSTRAINT.

-- PWB  1/24/86

PROCEDURE BC1109A IS

     TYPE FLOATING IS DIGITS   2 RANGE -1.0 .. 1.0;
     TYPE FIXED    IS DELTA 0.01 RANGE -1.0 .. 1.0;

     GENERIC
          I : INTEGER RANGE 0 .. 10;           -- ERROR: CONSTRAINT.
          B : IN OUT BOOLEAN
                      RANGE FALSE .. TRUE;     -- ERROR: CONSTRAINT.
          C : CHARACTER RANGE 'A' .. 'Z';      -- ERROR: CONSTRAINT.
          FL : IN OUT FLOATING
                       RANGE -1.0 .. 0.0;      -- ERROR: CONSTRAINT.
          FI : FIXED    RANGE -1.0 .. 0.0;     -- ERROR: CONSTRAINT.
     PACKAGE PKG IS
     END PKG;

     GENERIC
          I : IN OUT INTEGER RANGE 0 .. 10;    -- ERROR: CONSTRAINT.
          B : BOOLEAN RANGE FALSE .. TRUE;     -- ERROR: CONSTRAINT.
          C : IN OUT CHARACTER
                      RANGE 'A' .. 'Z';        -- ERROR: CONSTRAINT.
          FL : FLOATING RANGE -1.0 .. 0.0;     -- ERROR: CONSTRAINT.
          FI : IN OUT FIXED RANGE -1.0 .. 0.0; -- ERROR: CONSTRAINT.
     PROCEDURE CHECK ( X : INTEGER );

     PROCEDURE CHECK ( X : INTEGER ) IS
     BEGIN
          NULL;
     END CHECK;

BEGIN     -- BC1109A
     NULL;
END BC1109A;
