-- BC1109C.ADA

-- CHECK THAT A GENERIC FORMAL OBJECT DECLARATION
--  MAY NOT SPECIFY AN INDEX CONSTRAINT.

--  PWB  1/24/86

PROCEDURE BC1109C IS

     TYPE IARR IS ARRAY ( INTEGER RANGE <> ) OF BOOLEAN;
     TYPE BARR IS ARRAY ( BOOLEAN RANGE <> ) OF CHARACTER;
     TYPE CARR IS ARRAY ( CHARACTER RANGE <> ) OF INTEGER;

     GENERIC
          IA : IN OUT IARR ( 1..5 );         -- ERROR: INDEX CONSTRAINT.
          BA : BARR ( TRUE .. TRUE );        -- ERROR: INDEX CONSTRAINT.
          CA : IN OUT CARR ( 'A' .. 'Z' );   -- ERROR: INDEX CONSTRAINT.
          ST : STRING ( 1..4 );              -- ERROR: INDEX CONSTRAINT.
     PACKAGE PKG IS
     END PKG;

     GENERIC
          IA : IARR ( 1..5 );                -- ERROR: INDEX CONSTRAINT.
          BA : IN OUT BARR ( TRUE .. TRUE ); -- ERROR: INDEX CONSTRAINT.
          CA : CARR ( 'A' .. 'Z' );          -- ERROR: INDEX CONSTRAINT.
          ST : IN OUT STRING ( 1..4 );       -- ERROR: INDEX CONSTRAINT.
     PROCEDURE CHECK ( X : INTEGER );

     PROCEDURE CHECK ( X : INTEGER ) IS
     BEGIN
          NULL;
     END CHECK;

BEGIN    -- BC1109C
  NULL;
END BC1109C;
