-- BC1106A.ADA

-- CHECK THAT MODE IN IS ASSUMED WHEN NO MODE IS EXPLICITLY SPECIFIED
-- IN A GENERIC PARAMETER DECLARATION.

-- DAT 8/14/81

PROCEDURE BC1106A IS

BEGIN
     DECLARE
          GENERIC
               P : INTEGER;
          PACKAGE PKG IS END PKG;

          I : INTEGER;

          PACKAGE BODY PKG IS
          BEGIN
               P := 5;                       -- ERROR: P IS IN PARM.
          END PKG;
     BEGIN
          NULL;
     END;
END BC1106A;
