-- BC1109D.ADA

-- CHECK THAT A GENERIC FORMAL OBJECT DECLARATION
--     MAY NOT SPECIFY A DISCRIMINANT CONSTRAINT.

-- PWB  1/24/86

PROCEDURE BC1109D IS

     TYPE RECTYPE ( CONSTRAINT : INTEGER ) IS
          RECORD
               I : INTEGER;
          END RECORD;

     GENERIC
          R1 : IN OUT RECTYPE ( 7 );             -- ERROR: CONSTRAINT.
          R2 : RECTYPE ( CONSTRAINT => 5 );      -- ERROR: CONSTRAINT.
     PACKAGE PKG IS
     END PKG;

     GENERIC
          R1 : RECTYPE ( 7 );                    -- ERROR: CONSTRAINT.
          R2 : IN OUT RECTYPE (CONSTRAINT => 5); -- ERROR: CONSTRAINT.
     FUNCTION CHECK ( X : INTEGER ) RETURN BOOLEAN;

     FUNCTION CHECK ( X : INTEGER ) RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END CHECK;

BEGIN     -- BC1109D
     NULL;
END BC1109D;
