-- BC1202G.ADA

-- CHECK THAT IF THE DECLARATION OF GENERIC FORMAL TYPES INCLUDES
-- A DISCRIMINANT PART, THE GENERIC TYPE DEFINITION MUST NOT BE A RECORD
-- TYPE.

-- KEI 3/4/82
-- RJK 1/24/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM BC12ACA-B.ADA

PROCEDURE BC1202G IS

     TYPE N IS NEW INTEGER;

     GENERIC
          TYPE BUFFER (SIZE : INTEGER) IS PRIVATE;          -- OK.

          TYPE MATRIX (DIM : N) IS
               RECORD
                    VECTOR : ARRAY (INTEGER RANGE <>) OF FLOAT;
               END RECORD;                            -- ERROR:

     PACKAGE P1 IS
     END P1;

BEGIN
     NULL;
END BC1202G;
