-- BC1201K.ADA

-- CHECK THAT A RANGE OF FORM T RANGE L..R IS NOT ALLOWED 
-- AS AN INDEX RANGE IN A GENERIC FORMAL ARRAY TYPE DECLARATION.

-- PWB  2/11/86

PROCEDURE BC1201K IS

     TYPE ENUM IS (ONE, TWO, THREE);
     
     GENERIC
          TYPE BASE IS PRIVATE;
          TYPE ARRAY_1 IS 
               ARRAY (INTEGER RANGE 1 .. 10)      -- ERROR: INDEX RANGE.
                    OF BASE;
          TYPE ARRAY_2 IS 
               ARRAY (INTEGER RANGE 10 .. 1)      -- ERROR: INDEX RANGE.
                    OF BASE;
     PROCEDURE GEN_PROC (X : INTEGER);

     GENERIC
          TYPE BASE IS (<>);
          TYPE ARRAY_1 IS 
               ARRAY (BOOLEAN RANGE FALSE..TRUE)  -- ERROR: INDEX RANGE.
                    OF BASE;
          TYPE ARRAY_2 IS 
               ARRAY (ENUM RANGE ONE..THREE)      -- ERROR: INDEX RANGE.
                    OF BASE;
     FUNCTION GEN_FUNC (X : INTEGER) 
                       RETURN BOOLEAN;

     GENERIC
          TYPE BASE IS RANGE <>;
          LEFT  : INTEGER;
          RIGHT : INTEGER;
          TYPE ARRAY_1 IS 
               ARRAY (INTEGER RANGE LEFT..RIGHT)  -- ERROR : INDEX RANGE
               OF BASE;
     PACKAGE GEN_PACK IS
     END GEN_PACK;

     PROCEDURE GEN_PROC (X : INTEGER) IS
     BEGIN
          NULL;
     END GEN_PROC;

     FUNCTION GEN_FUNC (X : INTEGER) RETURN BOOLEAN IS
     BEGIN
          RETURN (X=5);
     END GEN_FUNC;

BEGIN    -- BC1201K
     NULL;
END BC1201K;
