-- BC1201D.ADA

-- CHECK THAT A NORMAL NUMERIC TYPE DECLARATION IS FORBIDDEN IN A
-- GENERIC PART.

-- ASL 8/7/81

PROCEDURE BC1201D IS

     TYPE I IS NEW INTEGER;

     GENERIC
          TYPE FIX IS DELTA 1.0 RANGE -1.0 .. 1.0;   -- ERROR: DELTA

     PACKAGE P IS
     END P;
BEGIN
     NULL;
END BC1201D;
