-- BC1201L.ADA

-- CHECK THAT A RANGE OF FORM T'RANGE IS NOT ALLOWED 
-- AS AN INDEX RANGE IN A GENERIC FORMAL ARRAY TYPE DECLARATION.

-- PWB  2/11/86

PROCEDURE BC1201L IS

     TYPE SMALL IS ARRAY (1..10) OF BOOLEAN;
     TYPE ENUM  IS (ONE, TWO, THREE);
     TYPE ENUM_ARRAY IS 
          ARRAY (ENUM RANGE <>) OF INTEGER;

     GENERIC
          TYPE BASE IS PRIVATE;
          LIST : ENUM_ARRAY;                      -- O.K.
          TYPE ARRAY_1 IS
               ARRAY (LIST'RANGE) OF BASE;        -- ERROR: 'RANGE.
     PROCEDURE GEN_PROC (X : INTEGER);

     GENERIC
          TYPE BASE IS (<>);
          TYPE ARRAY_1 IS
               ARRAY (BASE) OF INTEGER;           -- O.K.
          TYPE ARRAY_2 IS
               ARRAY (ARRAY_1'RANGE) OF BOOLEAN;  -- ERROR: 'RANGE.
     FUNCTION GEN_FUNC (X : INTEGER) 
          RETURN BOOLEAN;

     GENERIC
          TYPE BASE IS RANGE <>;
          TYPE ARRAY_1 IS 
               ARRAY (SMALL'RANGE) OF BASE;       -- ERROR: 'RANGE.
     PACKAGE GEN_PACK IS
     END GEN_PACK;

     PROCEDURE GEN_PROC (X : INTEGER) IS
     BEGIN
          NULL;
     END GEN_PROC;

     FUNCTION GEN_FUNC (X : INTEGER) RETURN BOOLEAN IS
     BEGIN
          RETURN (X=5);
     END GEN_FUNC;

BEGIN    -- BC1201L
     NULL;
END BC1201L;
