-- BC1201F.ADA

-- CHECK THAT A RANGE CONSTRAINT IS NOT ALLOWED ON THE
--   COMPONENT TYPE OF A GENERIC FORMAL ARRAY TYPE.

-- PWB  2/3/86

PROCEDURE BC1201F IS

     TYPE FLT IS DIGITS 5;
     TYPE FIX IS DELTA 0.1 RANGE -1.0 .. 1.0;

     GENERIC
          TYPE INDEX IS ( <> );
          TYPE FORMAL_ARRAY IS
               ARRAY ( INDEX )
               OF INTEGER RANGE 1..10;         -- ERROR: CONSTRAINT.
          TYPE FLT_ARRAY IS
               ARRAY ( INDEX )
               OF FLT RANGE -1.0 .. 1.0;       -- ERROR: CONSTRAINT.
     PROCEDURE GEN_PROC ( X : INTEGER );

     GENERIC
          TYPE FORMAL_STRING IS
               ARRAY ( POSITIVE RANGE <> )
               OF CHARACTER RANGE 'A' .. 'Z';  -- ERROR: CONSTRAINT.
          TYPE FIX_ARRAY IS
               ARRAY ( POSITIVE RANGE <> )
               OF FIX RANGE 0.0 .. 0.5;        -- ERROR: CONSTRAINT.
     PACKAGE GEN_PACK IS
     END GEN_PACK;

     GENERIC
          TYPE FORMAL_TABLE IS
               ARRAY ( POSITIVE RANGE <>,
                       INTEGER RANGE <>)
               OF BOOLEAN RANGE TRUE .. FALSE; -- ERROR: CONSTRAINT.
     FUNCTION GEN_FUNC ( X : INTEGER ) RETURN INTEGER;

     PROCEDURE GEN_PROC ( X : INTEGER ) IS
     BEGIN
          NULL;
     END GEN_PROC;

     FUNCTION GEN_FUNC ( X : INTEGER ) RETURN INTEGER IS
     BEGIN
          IF X = INTEGER'FIRST THEN
               RETURN INTEGER'LAST;
          ELSE
               RETURN X - 1;
          END IF;
     END GEN_FUNC;

BEGIN     -- BC1201F
     NULL;
END BC1201F;
