-- BC1208A.ADA

-- OBJECTIVE:
--     CHECK THAT THE DISCRIMINANTS OF A FORMAL GENERIC PARAMETER MUST
--     ALL HAVE DIFFERENT IDENTIFIERS.

-- HISTORY:
--     BCB 03/29/88  CREATED ORIGINAL TEST.

PROCEDURE BC1208A IS

     GENERIC
          TYPE DTYPE1 (D1 : INTEGER; D2 : BOOLEAN) IS PRIVATE; -- OK.
          TYPE DTYPE2 (D1 : INTEGER; D1 : BOOLEAN) IS PRIVATE;
                                    -- ERROR: TWO DISCRIMINANTS WITH
                                    --        THE SAME IDENTIFIER.

          TYPE DTYPE3 (D2 : BOOLEAN; D2 : BOOLEAN) IS PRIVATE;
                                    -- ERROR: TWO DISCRIMINANTS WITH
                                    --        THE SAME IDENTIFIER;
     PACKAGE P IS
     END P;

BEGIN
     NULL;
END BC1208A;
