-- BC1202E.ADA

-- CHECK THAT A GENERIC FORMAL PARAMETER MAY BE AN OBJECT, TYPE OR
-- SUBPROGRAM. NOT ALLOWED ARE SUBTYPES, DERIVED TYPES, RECORD TYPES
-- AND EXCEPTION DECLARATIONS.

-- KEI 3/4/82
-- RJK 1/23/84     ADDED  TO ACVC
-- JWC 6/28/85   RENAMED FROM BC10AEA-B.ADA

PROCEDURE BC1202E IS

     GENERIC
          I : INTEGER;                  -- OK.
          TYPE T1 IS PRIVATE;           -- OK.
          TYPE T2 IS LIMITED PRIVATE;   -- OK;

          WITH FUNCTION G1 (P : INTEGER) RETURN INTEGER; -- OK.
          WITH PROCEDURE P1 IS <>;      -- OK.
          TYPE LINE IS RANGE <>;        -- OK.
          SUBTYPE S_LINE IS RANGE 1..8; -- ERROR: SUBTYPE

          TYPE LIM IS LIMITED PRIVATE;  -- OK.
          TYPE DAY IS (<>);             -- OK.

     PACKAGE PACK IS
     END PACK;

BEGIN
     NULL;
END BC1202E;
