-- BC1201J.ADA

-- CHECK THAT A RANGE OF FORM L..R IS NOT ALLOWED 
-- AS AN INDEX RANGE IN A GENERIC FORMAL ARRAY TYPE DECLARATION. 

-- PWB  2/10/86

PROCEDURE BC1201J IS

     TYPE ENUM IS (ONE, TWO, THREE);
     
     GENERIC
          TYPE BASE IS PRIVATE;
          TYPE ARRAY_1 IS 
               ARRAY (1 .. 10) OF BASE;           -- ERROR: INDEX RANGE.
          TYPE ARRAY_2 IS 
               ARRAY (10 .. 1) OF BASE;           -- ERROR: INDEX RANGE.
     PROCEDURE GEN_PROC (X : INTEGER);

     GENERIC
          TYPE BASE IS (<>);
          TYPE ARRAY_1 IS 
               ARRAY (FALSE .. TRUE) OF BASE;     -- ERROR: INDEX RANGE.
          TYPE ARRAY_2 IS 
               ARRAY (ONE .. THREE) OF BASE;      -- ERROR: INDEX RANGE.
     FUNCTION GEN_FUNC (X : INTEGER) 
          RETURN BOOLEAN;

     GENERIC
          TYPE BASE IS RANGE <>;
          LEFT  : INTEGER;
          RIGHT : INTEGER;
          TYPE ARRAY_1 IS 
               ARRAY (LEFT .. RIGHT) OF BASE;     -- ERROR: INDEX RANGE.
     PACKAGE GEN_PACK IS
     END GEN_PACK;

     PROCEDURE GEN_PROC (X : INTEGER) IS
     BEGIN
          NULL;
     END GEN_PROC;

     FUNCTION GEN_FUNC (X : INTEGER) RETURN BOOLEAN IS
     BEGIN
          RETURN (X=5);
     END GEN_FUNC;

BEGIN    -- BC1201J
     NULL;
END BC1201J;
