-- BC1201C.ADA

-- CHECK THAT A NORMAL NUMERIC TYPE DECLARATION IS FORBIDDEN IN A
-- GENERIC PART.

-- ASL 8/7/81

PROCEDURE BC1201C IS

     TYPE I IS NEW INTEGER;

     GENERIC
          TYPE FLT IS DIGITS 1;                      -- ERROR: 1.

     PACKAGE P IS
     END P;
BEGIN
     NULL;
END BC1201C;
