-- BC1203A.ADA

-- CHECK THAT A GENERIC FORMAL TYPE CANNOT BE USED IN ITS OWN
-- ACCESS_TYPE_DEFINITION OR ARRAY_TYPE_DEFINITION.

-- DAT 9/16/81

PROCEDURE BC1203A IS
BEGIN
     DECLARE
          TYPE T2 IS NEW INTEGER;
          TYPE A2 IS ACCESS T2;

          GENERIC
               TYPE D IS ( <> );
               TYPE T1 IS ARRAY (D) OF D;    -- OK.
               TYPE T2 IS ARRAY (D) OF T2;   -- ERROR: T2 CONTAINS T2.
               TYPE AT1 IS ACCESS T1;        -- OK.
               TYPE A2 IS ACCESS A2;         -- ERROR: A2 ACCESSES A2.
          PACKAGE PK IS END PK;
     BEGIN
          NULL;
     END;

END BC1203A;
