-- BC1201B.ADA

-- CHECK THAT A NORMAL NUMERIC TYPE DECLARATION IS FORBIDDEN IN A
-- GENERIC PART.

-- ASL 8/7/81

PROCEDURE BC1201B IS

     TYPE I IS NEW INTEGER;

     GENERIC
          TYPE INT IS RANGE 1..10;                   -- ERROR: 1..10.

     PACKAGE P IS
     END P;
BEGIN
     NULL;
END BC1201B;
