-- BC1201G.ADA

-- CHECK THAT AN ACCURACY CONSTRAINT IS NOT ALLOWED ON A
-- COMPONENT TYPE SPECIFICATION IN A GENERIC FORMAL
-- ARRAY TYPE DECLARATION.

-- PWB  2/3/86

PROCEDURE BC1201G IS

     TYPE FLOAT_5  IS DIGITS 5;
     TYPE FIXED_01 IS DELTA 0.01 RANGE -1.0 .. 1.0;

     GENERIC
          TYPE FLOAT_4_ARRAY IS
               ARRAY ( INTEGER RANGE <> )
               OF FLOAT_5 DIGITS 4;               -- ERROR: CONSTRAINT.
     PROCEDURE GEN_PROC ( X : INTEGER );

     GENERIC
          TYPE FIXED_1_ARRAY IS
               ARRAY ( BOOLEAN )
               OF FIXED_01 DELTA 0.1;             -- ERROR: CONSTRAINT.
     FUNCTION GEN_FUNC ( X : INTEGER ) RETURN INTEGER;

     PROCEDURE GEN_PROC ( X : INTEGER ) IS
     BEGIN
          NULL;
     END GEN_PROC;

     FUNCTION GEN_FUNC ( X : INTEGER ) RETURN INTEGER IS
     BEGIN
          IF X = INTEGER'LAST THEN
               RETURN INTEGER'FIRST;
          ELSE
               RETURN X + 1;
          END IF;
     END GEN_FUNC;

BEGIN     -- BC1201G
     NULL;
END BC1201G;
