-- BC1202A.ADA

-- CHECK THAT A GENERIC FORMAL TYPE PARAMETER CANNOT HAVE A RECORD
-- TYPE DEFINITION.

-- ASL 8/7/81
-- SPS 4/19/82

PROCEDURE BC1202A IS
 
     GENERIC
          TYPE R1 IS
               RECORD                        -- ERROR: RECORD TYPE.
                    COMP : INTEGER;
               END RECORD;
     PACKAGE P IS
     END P;
BEGIN
     NULL;
END BC1202A;
