-- BC1201E.ADA

-- CHECK THAT IF THE DECLARATION OF GENERIC FORMAL TYPES INCLUDES
-- A DISCRIMINANT PART, THE GENERIC TYPE DEFINITION MUST BE A PRIVATE
-- TYPE DEFINITION AND THE DISCRIMINANT PART MUST NOT INCLUDE A DEFAULT
-- EXPRESSION FOR A DISCRIMINANT.

-- KEI 3/4/82
-- RJK 1/24/84     ADDED TO ACVC
-- JWC 6/28/85   RENAMED FROM BC12ACB-B.ADA

PROCEDURE BC1201E IS

     TYPE N IS NEW INTEGER;

     GENERIC
          TYPE BUFFER (SIZE : INTEGER) IS PRIVATE;          -- OK.
          TYPE STORAGE (SPACE : INTEGER := 1) IS PRIVATE;   -- ERROR:

     PACKAGE P1 IS
     END P1;

BEGIN
     NULL;
END BC1201E;
