-- BC1202C.ADA

-- CHECK THAT A GENERIC FORMAL TYPE PARAMETER CANNOT HAVE AN
-- INCOMPLETE TYPE DEFINITION.

-- ASL 8/7/81
-- SPS 4/19/82

PROCEDURE BC1202C IS
 
     GENERIC
          TYPE INCOMPLETE;                   -- ERROR: INCOMP TYPE.
          TYPE INCOMPLETE IS RANGE <>;
     PACKAGE P IS
     END P;
BEGIN
     NULL;
END BC1202C;
