-- BC1201A.ADA

-- CHECK THAT A GENERIC FORMAL TYPE PARAMETER WITH A GENERIC SCALAR,
-- ARRAY OR ACCESS TYPE DEFINITION CANNOT HAVE A DISCRIMINANT PART.

-- ASL 8/7/81

PROCEDURE BC1201A IS

     TYPE I IS NEW INTEGER;

     GENERIC
          TYPE ARR(D : I) IS ARRAY(I RANGE <>) OF I; -- ERROR: (D : I).
          TYPE S1(D : I) IS (<>);                    -- ERROR: (D : I).
          TYPE S2(D : I) IS RANGE <>;                -- ERROR: (D : I).
          TYPE ACC(D : I) IS ACCESS I;               -- ERROR: (D : I).

     PACKAGE P IS
     END P;
BEGIN
     NULL;
END BC1201A;
