-- BC1303D.ADA

-- CHECK THAT A GENERIC FORMAL SUBPROGRAM PARAMETER MAY NOT BE 
-- NAMED "AND THEN".

-- SPS 10/18/82

PROCEDURE BC1303D IS

     GENERIC
          TYPE BOL IS (<>);
          WITH FUNCTION "AND THEN" (X, Y: BOL)     -- ERROR: "AND THEN".
               RETURN BOOLEAN;               
     PACKAGE GP IS END GP;

BEGIN
     NULL;
END BC1303D;
