-- BC1303A.ADA

-- CHECK THAT A GENERIC FORMAL SUBPROGRAM PARAMETER MAY NOT BE 
-- NAMED "/=".

-- DAT 10/6/81
-- SPS 10/18/82

PROCEDURE BC1303A IS

     GENERIC
          TYPE T IS LIMITED PRIVATE;
          WITH FUNCTION "/=" (X, Y : T) RETURN BOOLEAN; -- ERROR: "/=".
     PACKAGE GP1 IS END GP1;

BEGIN
     NULL;
END BC1303A;
