-- BC1303B.ADA

-- CHECK THAT A GENERIC FORMAL SUBPROGRAM PARAMETER MAY NOT BE 
-- NAMED "IN".

-- SPS 10/18/82

PROCEDURE BC1303B IS

     GENERIC
          TYPE T IS LIMITED PRIVATE;
          TYPE AR IS ARRAY (INTEGER) OF T;
          WITH FUNCTION "IN" (X: T; Y: AR)               -- ERROR: "IN".
               RETURN BOOLEAN;
     PACKAGE GP IS END GP;

BEGIN
     NULL;
END BC1303B;
