-- BC1303C.ADA

-- CHECK THAT A GENERIC FORMAL SUBPROGRAM PARAMETER MAY NOT BE 
-- NAMED "NOT IN".

-- SPS 10/18/82

PROCEDURE BC1303C IS

     GENERIC
          TYPE T IS LIMITED PRIVATE;
          TYPE AR IS ARRAY (INTEGER) OF T;
          WITH FUNCTION "NOT IN" (X: T; Y: AR)       -- ERROR: "NOT IN".
               RETURN BOOLEAN;               
     PACKAGE GP IS END GP;

BEGIN
     NULL;
END BC1303C;
