-- BC1303E.ADA

-- CHECK THAT A GENERIC FORMAL SUBPROGRAM PARAMETER MAY NOT BE 
-- NAMED "OR ELSE".

-- SPS 10/18/82

PROCEDURE BC1303E IS

     GENERIC
          TYPE BOL IS (<>);
          WITH FUNCTION "OR ELSE" (X, Y: BOL)       -- ERROR: "OR ELSE".
               RETURN BOOLEAN;               
     PACKAGE GP IS END GP;

BEGIN
     NULL;
END BC1303E;
