-- BC1310B.ADA

-- OBJECTIVE:
--     CHECK THAT A DEFAULT SUBPROGRAM NAME CANNOT BE AN ENTRY
--     FAMILY NAME.

-- HISTORY:
--     BCB 08/04/88  CREATED ORIGINAL TEST.

PROCEDURE BC1310B IS

     TYPE ENUM IS (ONE, TWO, THREE);

     TASK T IS
          ENTRY S(ENUM);
     END T;

     GENERIC
          WITH PROCEDURE R IS T.S;                     -- ERROR:
     PACKAGE P IS
     END P;

     TASK BODY T IS
     BEGIN
          ACCEPT S(ONE);
     END T;

BEGIN
     NULL;
END BC1310B;
