-- BC2001C.ADA

-- CHECK THAT A GENERIC SUBPROGRAM  BODY CANNOT BE PRECEDED
-- BY A COPY OF THE GENERIC PART USED IN THE CORRESPONDING GENERIC
-- DECLARATION.

-- ASL 8/7/81
-- SPS 4/21/82

PROCEDURE BC2001C IS
BEGIN
     DECLARE
          GENERIC 
          PROCEDURE PROC1;

          GENERIC                            
          PROCEDURE PROC1 IS                  -- ERROR: GENERIC PART.
          BEGIN
               NULL;
          END PROC1;
     BEGIN
          NULL;
     END;


END BC2001C;
