-- BC2001B.ADA

-- CHECK THAT A SUBPROGRAM BODY PRECEDED BY A GENERIC
-- PART CANNOT SERVE AS A GENERIC DECLARATION WHEN THE DECLARATION IS 
-- OMITTED.

-- ASL 8/7/81
-- SPS 4/21/82

PROCEDURE BC2001B IS
BEGIN
     DECLARE
          GENERIC
          PROCEDURE PROC2 IS                 -- ERROR: NOT DECLARED.
          BEGIN
               NULL;
          END PROC2;
     BEGIN
          NULL;
     END;


END BC2001B;
