-- BC3002A.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION A GENERIC ACTUAL PARAMETER
-- CANNOT BE OMITTED IF THE CORRESPONDING FORMAL (OBJECT OR SUBPROGRAM)
-- PARAMETER HAS NO DEFAULT.

-- ASL 8/14/81

PROCEDURE BC3002A IS

     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;

     FUNCTION FUN RETURN INTEGER IS
     BEGIN
          RETURN 0;
     END FUN;

     GENERIC
          GFP : INTEGER;
          WITH FUNCTION FUN RETURN INTEGER;
          WITH PROCEDURE PROC;
     PACKAGE P IS
     END P;

     PACKAGE BAD1 IS NEW P(6,FUN);           -- ERROR: MISSING PROC.
     PACKAGE BAD2 IS NEW P(PROC => PROC, FUN => FUN); -- ERROR:
                                             -- MISSING GFP.
     PACKAGE BAD3 IS NEW P(2,PROC => PROC);  -- ERROR: MISSING FUN.
BEGIN
     NULL;
END BC3002A;
