-- BC3009C.ADA

-- CHECK THAT A GENERIC UNIT MAY NOT REQUIRE AN INSTANTIATION
-- OF ITSELF.

-- CASE OF DETECTION OF CIRCULAR INSTANTIATIONS BETWEEN PACKAGE 
-- SPEC AND BODY.

-- RFB 05/24/84
-- EG  05/31/84

--
-- UNIT 1
--
PACKAGE BC3009C IS

     GENERIC
     PROCEDURE F;

     GENERIC
     PROCEDURE G;

     GENERIC
     PROCEDURE Q;

     GENERIC
     PACKAGE P IS
          PROCEDURE NF IS NEW F;             -- WARN: INCOMPLETE
     END;

END BC3009C;

--
-- UNIT 2
--
PACKAGE BODY BC3009C IS

     PROCEDURE F IS
          PACKAGE NP IS NEW P;              -- ERROR: CIRCULAR(2 LEVELS)
     BEGIN 
          NULL; 
     END;

     PROCEDURE Q IS
          PACKAGE NP IS NEW P;
     BEGIN
          NULL;
     END;

     PACKAGE BODY P IS
          PROCEDURE NG IS NEW G;
     END;

     PROCEDURE G IS
          PROCEDURE NQ IS NEW Q;            -- ERROR: CIRCULAR(3 LEVELS)
     BEGIN 
          NULL; 
     END;

BEGIN

     NULL;

END BC3009C;
