-- BC3002C.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, NAMED GENERIC ACTUAL
-- PARAMETERS CANNOT PRECEDE NOR BE INTERLEAVED WITH POSITIONAL
-- GENERIC ACTUAL PARAMETERS.

-- ASL 8/14/81

PROCEDURE BC3002C IS

     GENERIC
          GFP1 : INTEGER;
          GFP2 : INTEGER;
          GFP3 : INTEGER;
     PACKAGE P IS
     END P;

     PACKAGE BAD1 IS NEW P(GFP1 => 1,2,3);   -- ERROR: POSITIONALS.
     PACKAGE BAD2 IS NEW P(1,GFP2 => 2,3);   -- ERROR: INTERLEAVING.
BEGIN
     NULL;
END BC3002C;
