-- BC3002B.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION THE NUMBER OF GENERIC ACTUAL
-- PARAMETERS CANNOT EXCEED THE NUMBER OF GENERIC FORMAL PARAMETERS
-- IN THE CORRESPONDING GENERIC PART.

-- ASL 8/14/81

PROCEDURE BC3002B IS

     GENERIC 
          GFP1 : INTEGER;
          GFP2 : CHARACTER;
          GFP3 : BOOLEAN;
     PACKAGE P IS
     END P;

     PACKAGE BAD1 IS NEW P(6,'A',TRUE,0);    -- ERROR: EXTRA ACTUAL.
     PACKAGE BAD2 IS
          NEW P(GFP3 => FALSE,
                GFP1 => 25,
                GFP2 => 'B',
                GFP4 => 1);                  -- ERROR: EXTRA ACTUAL.
     PACKAGE BAD3 IS
          NEW P(5,
                'X',
                FALSE,
                GFP3 => TRUE);               -- ERROR: EXTRA ACTUAL.

BEGIN
     NULL;
END BC3002B;
