-- BC3006A.ADA

-- CHECK THAT THE NAME FOLLOWING NEW IN A GENERIC INSTANTIATION MUST BE
-- THE NAME OF A GENERIC SUBPROGRAM/PACKAGE.

-- ASL 8/17/81

PROCEDURE BC3006A IS

     PROCEDURE ORDPROC;
     PACKAGE ORDPACK IS
     END ORDPACK;

     GENERIC
     PROCEDURE PROCFORM;

     PROCEDURE PROCFORM IS
     BEGIN
          NULL;
     END PROCFORM;

     GENERIC
     PACKAGE PACKFORM IS
     END PACKFORM;

     PROCEDURE ORDPROC IS
     BEGIN
          NULL;
     END ORDPROC;
BEGIN
     DECLARE
          PROCEDURE PROCINST IS NEW PROCFORM; -- OK.
          PACKAGE PACKINST IS NEW PACKFORM;   -- OK.
          
          PROCEDURE BADPROC1 IS NEW PROCINST; -- ERROR: PROCINST.
          PACKAGE BADPACK1 IS NEW PACKINST;   -- ERROR: PACKINST.
          PROCEDURE BADPROC2 IS NEW ORDPROC;  -- ERROR: ORDPROC.
          PACKAGE BADPACK2 IS NEW ORDPACK;    -- ERROR: ORDPACK.
     BEGIN
          NULL;
     END;
END BC3006A;
