-- BC3002D.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, A POSITIONAL OR NAMED GENERIC
-- ACTUAL PARAMETER AND ANOTHER NAMED GENERIC ACTUAL PARAMETER CANNOT
-- BE SPECIFIED FOR THE SAME GENERIC FORMAL PARAMETER.

-- ASL 8/14/81
-- SPS 4/26/82

PROCEDURE BC3002D IS

     GENERIC
          GFP1 : INTEGER := 1;
          GFP2 : INTEGER := 2;
          GFP3 : INTEGER := 3;
     PACKAGE P IS
     END P;

     PACKAGE BAD1 IS 
          NEW P(1,
                GFP1 => 1,                  -- ERROR: DUPL. ASSOC.
                GFP3 => 3);
     PACKAGE BAD2 IS
          NEW P(GFP1 => 1,
                GFP2 => 2,
                GFP2 => 2);                  -- ERROR: DUPL. ASSOC.
     PACKAGE BAD3 IS NEW P(1,2,GFP2 => 3);   -- ERROR: DUPL. ASSOC.
BEGIN
     NULL;
END BC3002D;
