-- BC3003A.ADA

-- CHECK THAT GENERIC INSTANTIATIONS OF THE FORM P(A,,B) ARE
-- FORBIDDEN, EVEN WHEN THE OMITTED GENERIC PARAMETER HAS A
-- DEFAULT.

-- ASL 8/14/81

PROCEDURE BC3003A IS

     PROCEDURE PROC;

     GENERIC 
          GFP1 : INTEGER;
          GFP2 : INTEGER := 5;
          GFP3 : INTEGER;
          WITH PROCEDURE GPROC1 IS PROC;
          WITH PROCEDURE PROC IS <>;
          WITH PROCEDURE GPROC2;
     PACKAGE P IS
     END P;

     PACKAGE BAD1 IS 
          NEW P(3,,7,PROC,PROC,PROC);        -- ERROR: ,,.
     PACKAGE BAD2 IS 
          NEW P(1,2,3,,PROC,PROC);           -- ERROR: ,,.
     PACKAGE BAD3 IS
          NEW P(7,8,9,PROC,,PROC);           -- ERROR: ,,.

     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;
BEGIN
     NULL;
END BC3003A;
