-- BC3009A.ADA

-- CHECK THAT A GENERIC UNIT MAY NOT REQUIRE AN INSTANTIATION
-- OF ITSELF.

-- CASE OF DETECTION OF CIRCULAR INSTANTIATIONS WITHIN SINGLE UNIT.

-- RFB 05/24/84
-- EG  05/31/84

PROCEDURE BC3009A IS

     GENERIC
     PROCEDURE F;

     GENERIC
     PROCEDURE G;

     GENERIC
     PROCEDURE T;

     GENERIC
     PACKAGE P IS
          PROCEDURE NF IS NEW F;
     END;

     GENERIC
     PACKAGE Q IS
          PACKAGE NQ IS NEW Q;     -- ERROR: INSTANTIATION OF "SELF"
                                   --    (Q IS GEN SPEC, NOT GEN DECL)
     END;

     PROCEDURE F IS
          PACKAGE NP IS NEW P;     -- ERROR: CIRCULAR (2 LEVELS)
     BEGIN 
          NULL; 
     END;

     PROCEDURE T IS
          PACKAGE NP IS NEW P;
     BEGIN
          NULL;
     END;

     PACKAGE BODY P IS
          PROCEDURE NG IS NEW G;
     END;

     PROCEDURE G IS
          PROCEDURE NT IS NEW T;   -- ERROR: CIRCULAR (3 LEVELS)
     BEGIN 
          NULL; 
     END;

BEGIN

     NULL;

END BC3009A;
