-- BC3013A.ADA

-- CHECK THAT A SUBPROGRAM SPECIFICATION CANNOT BE USED
-- IN A GENERIC SUBPROGRAM INSTANTIATION.

-- DAT 9/18/81

PROCEDURE BC3013A IS

     GENERIC
     PROCEDURE PR (X : INTEGER);

     GENERIC 
     FUNCTION F (X : INTEGER) RETURN INTEGER;

     GENERIC
     FUNCTION F1 RETURN INTEGER;

     PROCEDURE PR (X : INTEGER) IS BEGIN NULL; END;

     FUNCTION F (X : INTEGER) RETURN INTEGER IS
     BEGIN RETURN 0; END;

     FUNCTION F1 RETURN INTEGER IS BEGIN RETURN 0; END;

     PACKAGE PKG IS
          PROCEDURE I1 (X : INTEGER) IS NEW PR; -- ERROR: FORMAL PART.
          PROCEDURE I2 IS NEW PR;               -- OK.
          FUNCTION I3 IS NEW F;                 -- OK.
          FUNCTION I4 (X : INTEGER) RETURN INTEGER
               IS NEW F;                        -- ERROR: FORMAL PART.
          FUNCTION I5 IS NEW F1;                -- OK.
          FUNCTION I6 RETURN INTEGER IS NEW F1; -- ERROR: RETURN.
     END PKG;

BEGIN
     NULL;
END BC3013A;
