-- BC3002E.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, THE FORMAL PARAMETER
-- IDENTIFIER IN A NAMED GENERIC ASSOCIATION CANNOT BE DIFFERENT
-- FROM ALL OF THE IDENTIFIERS OF THE GENERIC FORMAL PARAMETERS
-- IN THE CORRESPONDING GENERIC PART.

-- ASL 8/14/81


PROCEDURE BC3002E IS

     WRONG : INTEGER;

     GENERIC
          GFP1 : INTEGER;
          GFP2 : INTEGER;
          GFP3 : INTEGER;
     PACKAGE P IS
     END P;

     PACKAGE BAD1 IS 
          NEW P(GFP1 => 1,
                WRONG => 2,                  -- ERROR: WRONG NAME.
                GFP3 => 3);
     PACKAGE BAD2 IS
          NEW P(GFP3 => 3,
                GFP1 => 1,
                WRONG => 2);                 -- ERROR: WRONG NAME.
     PACKAGE BAD3 IS NEW P(1,2,WRONG => 3);  -- ERROR: WRONG NAME.
BEGIN
     NULL;
END BC3002E;
