-- BC3011C.ADA

-- CHECK THAT TYPE CHECKING FOR GENERIC PACKAGES IS PERFORMED
-- AT GENERIC DECLARATION TIME, RATHER THAT AT INSTANTIATION.

-- DAT 9/18/81

PROCEDURE BC3011C IS

     GENERIC
          TYPE S IS RANGE <> ;
          TYPE T IS RANGE <> ;
     PACKAGE PKG IS
          VS : S := S'FIRST;
          VT : T := T'FIRST;
          B : BOOLEAN := VS = VT;             -- ERROR: TYPE MISMATCH.
          VT2 : T := VS;                      -- ERROR: TYPE MISMATCH.
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN
          VT := VS;                           -- ERROR: TYPE MISMATCH.
     END PKG;

BEGIN
     NULL;
END BC3011C;
