-- BC3103A.ADA

-- CHECK THAT AN ACTUAL IN OUT PARAMETER CANNOT BE A SUBCOMPONENT OF A
-- VARIABLE THAT IS A RECORD COMPONENT, AN ARRAY COMPONENT, OR AN OBJECT
-- DECLARED WITH AN OBJECT DECLARATION, IF THE VARIABLE HAS AN
-- UNCONSTRAINED TYPE WITH DEFAULT DISCRIMINANTS, AND THE SUBCOMPONENT
-- DEPENDS ON A DISCRIMINANT.  THE SUBCOMPONENT SHOULD BE AS FOLLOWS:
--     A) A COMPONENT OF THE VARIABLE AND THE COMPONENT:
--          1) IS IN A VARIANT PART OF THE VARIABLE;
--          2) IS AN ARRAY WITH AT LEAST ONE BOUND SPECIFIED BY A
--             DISCRIMINANT OF THE VARIABLE;
--          3) HAS A CONSTRAINED RECORD OR PRIVATE TYPE WITH AT LEAST
--             ONE DISCRIMINANT SPECIFIED BY A DISCRIMINANT OF THE
--             VARIABLE;
--          4) HAS AN ACCESS TYPE WITH AN EXPLICIT INDEX OR DISCRIMINANT
--             CONSTRAINT USING A DISCRIMINANT OF THE VARIABLE;
--     B) A SUBCOMPONENT OF ONE OF THE ABOVE COMPONENTS.

-- TBN  9/24/86

PROCEDURE BC3103A IS

     SUBTYPE INT IS INTEGER RANGE 1 .. 10;
     TYPE ARRAY1 IS ARRAY (INT RANGE <>) OF INTEGER;
     TYPE PTR1 IS ACCESS ARRAY1;

     PACKAGE PAC IS
          TYPE PRI_REC (D : INT) IS PRIVATE;
     PRIVATE
          TYPE PRI_REC (D : INT) IS
               RECORD
                    A : INTEGER;
               END RECORD;
     END PAC;

     USE PAC;

     TYPE REC3 (D : INT := 1) IS
          RECORD
               NAME : STRING (1 .. D);
          END RECORD;

     TYPE PTR2 IS ACCESS REC3;

     TYPE REC1 (D : INT := 2) IS
          RECORD
               CASE D IS
                    WHEN 1|2|3|4|5 =>
                         NAME : STRING (1 .. D);
                    WHEN OTHERS =>
                         ADDRESS : STRING (D .. 20);
               END CASE;
          END RECORD;

     TYPE REC4 (D : INT := 2) IS
          RECORD
               ARA1 : ARRAY1 (1 .. D);
               COMP_REC1 : REC3 (D);
               PRI_REC1 : PRI_REC (D);
               ACC_ARA : PTR1 (1 .. D);
               ACC_REC : PTR2 (D);
               SUB_COMP : REC3 (D);
          END RECORD;

     TYPE REC2 IS
          RECORD
               VAR_REC1 : REC1;
               VAR_REC4 : REC4;
          END RECORD;

     TYPE ARRAY2 IS ARRAY (1 .. 2) OF REC1;
     TYPE ARRAY3 IS ARRAY (1 .. 2) OF REC4;

     OBJ_VAR1 : REC1;
     OBJ_VAR4 : REC4;
     OBJ_REC : REC2;
     OBJ_ARA1 : ARRAY2;
     OBJ_ARA2 : ARRAY3;

     GENERIC
          TYPE T IS PRIVATE;
          A : IN OUT T;
     PROCEDURE PROC (B : IN OUT INTEGER);

     PROCEDURE PROC (B : IN OUT INTEGER) IS
     BEGIN
          IF B /= 1 THEN
               B := B + 1;
          ELSE
               B := 1;
          END IF;
     END PROC;

     PROCEDURE PROC1 IS NEW PROC (STRING, OBJ_VAR1.NAME);      -- ERROR:
     PROCEDURE PROC2 IS
          NEW PROC (STRING, OBJ_REC.VAR_REC1.NAME);            -- ERROR:
     PROCEDURE PROC3 IS
          NEW PROC (STRING, OBJ_ARA1 (1).NAME);                -- ERROR:
     PROCEDURE PROC4 IS NEW PROC (ARRAY1, OBJ_VAR4.ARA1);      -- ERROR:
     PROCEDURE PROC5 IS
          NEW PROC (ARRAY1, OBJ_REC.VAR_REC4.ARA1);            -- ERROR:
     PROCEDURE PROC6 IS
          NEW PROC (ARRAY1, OBJ_ARA2 (1).ARA1);                -- ERROR:
     PROCEDURE PROC7 IS
          NEW PROC (REC3, OBJ_VAR4.COMP_REC1);                 -- ERROR:
     PROCEDURE PROC8 IS
          NEW PROC (REC3, OBJ_REC.VAR_REC4.COMP_REC1);         -- ERROR:
     PROCEDURE PROC9 IS
          NEW PROC (REC3, OBJ_ARA2 (1).COMP_REC1);             -- ERROR:
     PROCEDURE PRO10 IS
          NEW PROC (PRI_REC, OBJ_VAR4.PRI_REC1);               -- ERROR:
     PROCEDURE PRO11 IS
          NEW PROC (PRI_REC, OBJ_REC.VAR_REC4.PRI_REC1);       -- ERROR:
     PROCEDURE PRO12 IS
          NEW PROC (PRI_REC, OBJ_ARA2 (1).PRI_REC1);           -- ERROR:
     PROCEDURE PRO13 IS NEW PROC (PTR1, OBJ_VAR4.ACC_ARA);     -- ERROR:
     PROCEDURE PRO14 IS
          NEW PROC (PTR1, OBJ_REC.VAR_REC4.ACC_ARA);           -- ERROR:
     PROCEDURE PRO15 IS
          NEW PROC (PTR1, OBJ_ARA2 (1).ACC_ARA);               -- ERROR:
     PROCEDURE PRO16 IS NEW PROC (PTR2, OBJ_VAR4.ACC_REC);     -- ERROR:
     PROCEDURE PRO17 IS
          NEW PROC (PTR2, OBJ_REC.VAR_REC4.ACC_REC);           -- ERROR:
     PROCEDURE PRO18 IS
          NEW PROC (PTR2, OBJ_ARA2 (1).ACC_REC);               -- ERROR:
     PROCEDURE PRO19 IS
          NEW PROC (STRING, OBJ_VAR4.SUB_COMP.NAME);           -- ERROR:
     PROCEDURE PRO20 IS
          NEW PROC (STRING, OBJ_REC.VAR_REC4.SUB_COMP.NAME);   -- ERROR:
     PROCEDURE PRO21 IS
          NEW PROC (STRING, OBJ_ARA2 (1).SUB_COMP.NAME);       -- ERROR:

BEGIN
     NULL;
END BC3103A;
