-- BC3205F.ADA

-- CHECK THAT AN INSTANTIATION IS ILLEGAL IF A FORMAL PARAMETER
-- OF A PRIVATE OR LIMITED PRIVATE TYPE WITHOUT DISCRIMINANTS
-- IS USED:
--   A) IN AN ALLOCATOR,
--   B) IN AN OBJECT DECLARATION DECLARING A VARIABLE,
--   C) IN A RECORD COMPONENT DECLARATION, OR
--   D) IN AN ARRAY TYPE DEFINITION
-- WHEN THE ACTUAL PARAMETER IS AN UNCONSTRAINED ARRAY TYPE OR
-- AN UNCONSTRAINED TYPE WITH DISCRIMINANTS THAT DO NOT HAVE DEFAULTS
-- (SEE ADA COMMENTARY AI-00037).

-- CASE OF NESTED GENERICS AND CONSTRAINT REQUIREMENTS FOR PRIVATE
-- TYPES.

-- RFB 05/24/84
-- EG  05/31/84
-- JBG 4/29/85

PACKAGE BC3205F IS

     GENERIC
          TYPE TO IS PRIVATE;
     PACKAGE GPO_OBJ IS

          GENERIC
               TYPE TI IS PRIVATE;
          PACKAGE GPI_OBJ IS
               X : TI;
          END GPI_OBJ;

          PACKAGE GP IS NEW GPI_OBJ(TO);     -- INFO: POTENTIALLY
     END GPO_OBJ;                            --       ILLEGAL.

     GENERIC
          TYPE TO IS PRIVATE;
     PACKAGE GPO_ALLOC IS

          GENERIC
               TYPE TI IS PRIVATE;
          PACKAGE GPI_ALLOC IS
               TYPE ACC IS ACCESS TI;
               X : ACC := NEW TI;
          END GPI_ALLOC;

          PACKAGE GP IS NEW GPI_ALLOC(TO);         -- INFO: POTENTIALLY
     END GPO_ALLOC;                                --       ILLEGAL.

     GENERIC
          TYPE TO IS PRIVATE;
     PACKAGE GPO_RECCOMP IS

          GENERIC
               TYPE TI IS PRIVATE;
          PACKAGE GPI_RECCOMP IS
               TYPE REC IS
                    RECORD
                         COMP : TI;
                    END RECORD;
          END GPI_RECCOMP;

          PACKAGE GP IS NEW GPI_RECCOMP(TO);        -- INFO: POTENTIALLY
     END GPO_RECCOMP;                               --       ILLEGAL.

     GENERIC
          TYPE TO IS PRIVATE;
     PACKAGE GPO_ARCOMP IS

          GENERIC
               TYPE TI IS LIMITED PRIVATE;
          PACKAGE GPI_ARCOMP IS
               TYPE ARR IS ARRAY (1..5) OF TI;
          END;

          PACKAGE GP IS NEW GPI_ARCOMP(TO);         -- INFO: POTENTIALLY
     END GPO_ARCOMP;                                --       ILLEGAL.

     TYPE DREC (D : INTEGER := 3) IS RECORD NULL; END RECORD;
     TYPE REC (D : INTEGER)  IS RECORD NULL; END RECORD;

     PACKAGE P1_OBJ IS NEW GPO_OBJ (DREC);        -- OK. AI-00037.
     PACKAGE P1_ALLOC IS NEW GPO_ALLOC (DREC);    -- OK. AI-00037.
     PACKAGE P1_RECCOMP IS NEW GPO_RECCOMP (DREC);-- OK. AI-00037.
     PACKAGE P1_ARCOMP IS NEW GPO_ARCOMP (DREC);  -- OK. AI-00037.

     PACKAGE P2_OBJ IS NEW GPO_OBJ (REC);         -- ERROR: REC.
     PACKAGE P2_ALLOC IS NEW GPO_ALLOC (REC);     -- ERROR: REC.
     PACKAGE P2_RECCOMP IS NEW GPO_RECCOMP (REC); -- ERROR: REC.
     PACKAGE P2_ARCOMP IS NEW GPO_ARCOMP (REC);   -- ERROR: REC.

     PACKAGE P3_OBJ IS NEW GPO_OBJ (STRING);        -- ERROR: STRING
     PACKAGE P3_ALLOC IS NEW GPO_ALLOC (STRING);    -- ERROR: STRING
     PACKAGE P3_RECCOMP IS NEW GPO_RECCOMP (STRING);-- ERROR: STRING
     PACKAGE P3_ARCOMP IS NEW GPO_ARCOMP (STRING);  -- ERROR: STRING

     PACKAGE OK_OBJ IS NEW GPO_OBJ (INTEGER);
     PACKAGE OK_ALLOC IS NEW GPO_ALLOC (INTEGER);
     PACKAGE OK_RECCOMP IS NEW GPO_RECCOMP(INTEGER);
     PACKAGE OK_ARCOMP IS NEW GPO_ARCOMP(INTEGER);

     USE OK_OBJ, OK_ALLOC, OK_RECCOMP, OK_ARCOMP;

     PACKAGE P4_OBJ IS NEW GPI_OBJ (DREC);         -- OK. AI-00037.
     PACKAGE P4_ALLOC IS NEW GPI_ALLOC (DREC);     -- OK. AI-00037.
     PACKAGE P4_RECCOMP IS NEW GPI_RECCOMP (DREC); -- OK. AI-00037.
     PACKAGE P4_ARCOMP IS NEW GPI_ARCOMP (DREC);   -- OK. AI-00037.

     PACKAGE P5_OBJ IS NEW GPI_OBJ (REC);          -- ERROR: REC.
     PACKAGE P5_ALLOC IS NEW GPI_ALLOC (REC);      -- ERROR: REC.
     PACKAGE P5_RECCOMP IS NEW GPI_RECCOMP (REC);  -- ERROR: REC.
     PACKAGE P5_ARCOMP IS NEW GPI_ARCOMP (REC);    -- ERROR: REC.

     PACKAGE P6_OBJ IS NEW GPI_OBJ (STRING);       -- ERROR: STRING.
     PACKAGE P6_ALLOC IS NEW GPI_ALLOC (STRING);   -- ERROR: STRING.
     PACKAGE P6_RECCOMP IS NEW GPI_RECCOMP (STRING);-- ERROR: STRING.
     PACKAGE P6_ARCOMP IS NEW GPI_ARCOMP (STRING); -- ERROR: STRING.

END BC3205F;
