-- BC3220B.ADA

-- CHECK THAT WHEN INSTANTIATING WITH A STATIC DISCRETE TYPE USED TO
-- DECLARE AN INDEX SUBTYPE, THE INDEX SUBTYPE IS CONSIDERED STATIC
-- OUTSIDE THE INSTANTIATED UNIT.

-- JBG 12/6/84

PROCEDURE BC3220B IS

     GENERIC
          TYPE T IS (<>);
     PACKAGE SET_OF IS
          TYPE SET IS ARRAY (T) OF BOOLEAN;
     END SET_OF;

     TYPE ENUM IS (A, B, C);
     TYPE STAT IS ARRAY (ENUM) OF BOOLEAN;
     TYPE NONSTATIC IS ARRAY (A..ENUM(C)) OF BOOLEAN;

     PACKAGE ENUM_SET IS NEW SET_OF (ENUM);

     ES : ENUM_SET.SET := (TRUE, OTHERS => FALSE); -- OK.
     ST : STAT := (TRUE, OTHERS => FALSE);         -- OK.
     NS : NONSTATIC := (TRUE, OTHERS => FALSE);    -- ERROR: NON-STATIC.

     GENERIC
          TYPE T IS (<>);
     PACKAGE CHECK IS
          TYPE ARR IS ARRAY (T) OF BOOLEAN;
          X : ARR := (TRUE, OTHERS => FALSE);      -- ERROR: NON-STATIC.
     END CHECK;
BEGIN
     NULL;
END BC3220B;
