-- BC3201A.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, A GENERIC ACTUAL TYPE
-- PARAMETER MUST NOT BE A LIMITED PRIVATE TYPE (OR A TYPE WITH
-- LIMITED PRIVATE COMPONENTS) IF THE GENERIC FORMAL IS A NONLIMITED 
-- PRIVATE TYPE PARAMETER.

-- ASL 8/24/81
-- SPS 7/8/82
-- SPS 12/10/82

PROCEDURE BC3201A IS

     PACKAGE P IS
          TYPE LIM IS LIMITED PRIVATE;
     PRIVATE
          TYPE LIM IS (X,Y,Z);
     END P;

     USE P;

     TYPE LIMREC IS
          RECORD
               COMP : LIM;
          END RECORD;
     TYPE VARREC (D:INTEGER ) IS
          RECORD
               CASE D IS
               WHEN 1..2 =>
                    C1 : LIM;
               WHEN OTHERS =>
                    C2 : INTEGER;
               END CASE;
          END RECORD;
     SUBTYPE CVARREC IS VARREC (D=>3);

     TYPE LIMARR IS ARRAY(INTEGER RANGE 1..2) OF LIM;

     GENERIC
          TYPE GFT IS PRIVATE;
     PACKAGE TEMPLATE IS
     END TEMPLATE;
    
     PACKAGE INST1 IS NEW TEMPLATE(LIM);     -- ERROR: LIM.
     PACKAGE INST2 IS NEW TEMPLATE(LIMREC);  -- ERROR: LIMREC.
     PACKAGE INST3 IS NEW TEMPLATE(LIMARR);  -- ERROR: LIMARR.
     PACKAGE INST4 IS NEW TEMPLATE(CVARREC); -- ERROR: CVARREC.
     PACKAGE INST5 IS NEW TEMPLATE(VARREC);  -- ERROR: VARREC.

BEGIN
     NULL;
END BC3201A;
