-- BC3201B.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, A GENERIC ACTUAL TYPE
-- PARAMETER MUST NOT BE A TASK TYPE (OR A TYPE WITH TASK
-- COMPONENTS) IF THE GENERIC FORMAL IS A NONLIMITED PRIVATE TYPE
-- PARAMETER.

-- ASL 8/24/81
-- SPS 7/8/82
-- SPS 12/10/82

 PROCEDURE BC3201B IS

     TASK TYPE T;

     TYPE TASKREC IS
          RECORD
               COMP : T;
          END RECORD;

     TYPE TASKARR IS ARRAY(1..2) OF T;

     SUBTYPE INT IS INTEGER RANGE 1 .. 2;
     TYPE VREC (D : INT) IS
          RECORD
               CASE D IS
               WHEN 1 =>
                    C1 : TASKREC;
               WHEN 2 =>
                    C2 : BOOLEAN;
               END CASE;
          END RECORD;
     SUBTYPE CVREC IS VREC (D=>2);

     TASK BODY T IS
     BEGIN
          NULL;
     END T;

     GENERIC
          TYPE GFT IS PRIVATE;
     PACKAGE TEMPLATE IS
     END TEMPLATE;

     PACKAGE INST1 IS NEW TEMPLATE(T);       -- ERROR: T.
     PACKAGE INST2 IS NEW TEMPLATE(TASKREC); -- ERROR: TASKREC.
     PACKAGE INST3 IS NEW TEMPLATE(TASKARR); -- ERROR: TASKARR.
     PACKAGE INST4 IS NEW TEMPLATE(CVREC);   -- ERROR: CVREC.
     PACKAGE INST5 IS NEW TEMPLATE(VREC);    -- ERROR: VREC.
BEGIN
     NULL;
END BC3201B;
