-- BC3301B.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, A GENERIC ACTUAL TYPE
-- PARAMETER MUST BE A DISCRETE TYPE (I.E. AN ENUMERATION OR 
-- INTEGER TYPE) IF THE CORRESPONDING FORMAL TYPE PARAMETER IS
-- DEFINED BY A GENERIC TYPE DEFINITION OF FORM "(<>)".

-- CHECK WHEN THE ACTUAL PARAMETER IS A GENERIC FORMAL PRIVATE TYPE OF
-- AN ENCLOSING GENERIC UNIT.

-- SPS 7/14/82

PROCEDURE BC3301B IS

     GENERIC
          TYPE PV IS PRIVATE;
          TYPE LP IS LIMITED PRIVATE;
          TYPE I IS (<>);
          TYPE ARR IS ARRAY(INTEGER) OF I;
          TYPE ACC IS ACCESS I;

     PACKAGE PK IS
          TYPE NEW_I IS NEW I;

          GENERIC
               TYPE GFT IS (<>);
          PACKAGE GP IS END GP;

          PACKAGE OK1 IS NEW GP(I);               -- OK.
          PACKAGE OK2 IS NEW GP(NEW_I);           -- OK.

          PACKAGE Z1 IS NEW GP(ARR);              -- ERROR: ARR.
          PACKAGE Z2 IS NEW GP(ACC);              -- ERROR: ACC.
          PACKAGE Z3 IS NEW GP(PV);               -- ERROR: PV.
          PACKAGE Z4 IS NEW GP(LP);               -- ERROR: LP.
     END PK;
BEGIN
     NULL;
END BC3301B;
