-- BC3302B.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, A GENERIC ACTUAL TYPE
-- PARAMETER MUST BE AN INTEGER TYPE IF THE CORRESPONDING GENERIC 
-- FORMAL TYPE PARAMETER IS DEFINED BY A GENERIC TYPE DEFINITION
-- OF FORM "RANGE <>".

-- CHECK WHEN THE ACTUAL PARAMETER IS A GENERIC FORMAL PRIVATE OR
-- DISCRETE TYPE DECLARED IN AN ENCLOSING GENERIC UNIT.

-- SPS 7/14/82

PROCEDURE BC3302B IS

     GENERIC
          TYPE PV IS PRIVATE;
          TYPE LP IS LIMITED PRIVATE;
          TYPE I IS (<>);
          TYPE INT IS RANGE <>;
          TYPE ARR IS ARRAY(INTEGER) OF INT;
          TYPE ACC IS ACCESS INT;

     PACKAGE PK IS
          TYPE NEW_INT IS NEW INT;
          TYPE NEW_I IS NEW I;

          GENERIC
               TYPE GFT IS RANGE <>;
          PACKAGE GP IS END GP;

          PACKAGE OK1 IS NEW GP(INT);             -- OK.
          PACKAGE OK2 IS NEW GP(NEW_INT);         -- OK.

          PACKAGE Z1 IS NEW GP(ARR);              -- ERROR: ARR.
          PACKAGE Z2 IS NEW GP(ACC);              -- ERROR: ACC.
          PACKAGE Z3 IS NEW GP(PV);               -- ERROR: PV.
          PACKAGE Z4 IS NEW GP(LP);               -- ERROR: LP.
          PACKAGE Z5 IS NEW GP(I);                -- ERROR: I.
          PACKAGE Z6 IS NEW GP(NEW_I);            -- ERROR: NEW_I.
     END PK;
BEGIN
     NULL;
END BC3302B;
