-- BC3301A.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION, A GENERIC ACTUAL TYPE
-- PARAMETER MUST BE A DISCRETE TYPE (I.E. AN ENUMERATION OR 
-- INTEGER TYPE) IF THE CORRESPONDING FORMAL TYPE PARAMETER IS
-- DEFINED BY A GENERIC TYPE DEFINITION OF FORM "(<>)".

-- ASL 8/24/81

PROCEDURE BC3301A IS

     TYPE NEW_CHAR IS NEW CHARACTER;
     TYPE NEW_INT IS NEW INTEGER;
     SUBTYPE SUB_INT IS INTEGER RANGE 1..5;
     TYPE NEW_SUB_INT IS NEW SUB_INT;
     TYPE COLOR IS (RED,BLUE,YELLOW);
     TYPE NEW_COLOR IS NEW COLOR;

     TYPE ARR IS ARRAY(INTEGER RANGE 1..1) OF INTEGER;
     SUBTYPE STR IS STRING(1..1);

     TYPE REC(D : COLOR) IS
          RECORD
               COMP : COLOR;
          END RECORD;

     TYPE ACC IS ACCESS COLOR;

     PACKAGE P IS
          TYPE PRIV IS PRIVATE;
          TYPE LIM IS LIMITED PRIVATE;
     PRIVATE
          TYPE PRIV IS NEW INTEGER;
          TYPE LIM IS NEW COLOR;
     END;

     USE P;

     GENERIC
          TYPE GFT IS (<>);
     PACKAGE GP IS
     END GP;

     PACKAGE OK1 IS NEW GP(BOOLEAN);         -- OK.
     PACKAGE OK2 IS NEW GP(CHARACTER);       -- OK.
     PACKAGE OK3 IS NEW GP(NEW_CHAR);        -- OK.
     PACKAGE OK4 IS NEW GP(INTEGER);         -- OK.
     PACKAGE OK5 IS NEW GP(NEW_INT);         -- OK.
     PACKAGE OK6 IS NEW GP(SUB_INT);         -- OK.
     PACKAGE OK7 IS NEW GP(NEW_SUB_INT);     -- OK.
     PACKAGE OK8 IS NEW GP(COLOR);           -- OK.
     PACKAGE OK9 IS NEW GP(NEW_COLOR);       -- OK.

     PACKAGE Z1 IS NEW GP(FLOAT);            -- ERROR: FLOAT.
     PACKAGE Z2 IS NEW GP(ARR);              -- ERROR: ARR.
     PACKAGE Z3 IS NEW GP(STR);              -- ERROR: STR.
     PACKAGE Z4 IS NEW GP(REC);              -- ERROR: REC.
     PACKAGE Z5 IS NEW GP(ACC);              -- ERROR: ACC.
     PACKAGE Z6 IS NEW GP(PRIV);             -- ERROR: PRIV.           
     PACKAGE Z7 IS NEW GP(LIM);              -- ERROR: LIM.
BEGIN
     NULL;
END BC3301A;
