-- BC3401A.ADA

-- CHECK THAT IN A GENERIC INSTANTIATION,  A GENERIC ACTUAL TYPE
-- PARAMETER MUST BE AN ARRAY TYPE IF THE CORRESPONDING GENERIC
-- FORMAL TYPE PARAMETER IS DEFINED BY A GENERIC ARRAY TYPE
-- DEFINITION.

-- ASL 9/3/81

PROCEDURE BC3401A IS

     TYPE ARR IS ARRAY(INTEGER) OF INTEGER;
     TYPE NEW_ARR IS NEW ARR;

     TYPE COLOR IS (RED,BLUE,YELLOW);

     TYPE REC IS
          RECORD
               COMP : ARR;
          END RECORD;

     TYPE ACC IS ACCESS ARR;

     PACKAGE P IS
          TYPE PRIV IS PRIVATE;
          TYPE LIM IS LIMITED PRIVATE;
     PRIVATE
          TYPE PRIV IS NEW ARR;
          TYPE LIM IS NEW ARR;
     END;

     USE P;

     GENERIC
          TYPE GFT IS ARRAY(INTEGER) OF INTEGER;
     PACKAGE GP IS
     END GP;

     PACKAGE OK1 IS NEW GP(ARR);              -- OK.
     PACKAGE OK2 IS NEW GP(NEW_ARR);          -- OK.

     PACKAGE Z1 IS NEW GP(FLOAT);             -- ERROR: FLOAT.
     PACKAGE Z2 IS NEW GP(INTEGER);           -- ERROR: INTEGER.
     PACKAGE Z3 IS NEW GP(BOOLEAN);           -- ERROR: BOOLEAN.
     PACKAGE Z4 IS NEW GP(CHARACTER);         -- ERROR: CHARACTER.
     PACKAGE Z5 IS NEW GP(COLOR);             -- ERROR: COLOR.
     PACKAGE Z6 IS NEW GP(STRING);            -- ERROR: STR.
     PACKAGE Z7 IS NEW GP(REC);               -- ERROR: REC.
     PACKAGE Z8 IS NEW GP(ACC);               -- ERROR: ACC.
     PACKAGE Z9 IS NEW GP(PRIV);              -- ERROR: PRIV.   
     PACKAGE Z10 IS NEW GP(LIM);              -- ERROR: LIM.
BEGIN
     NULL;
END BC3401A;
