-- BC3403C.ADA

-- WHEN A GENERIC FORMAL TYPE IS AN ARRAY TYPE, CHECK THAT CORRESPONDING
-- INDEX POSITIONS HAVE THE SAME BASE TYPE.

-- CHECK WHEN THE INDEX BASE TYPE IS A GENERIC FORMAL PARAMETER DECLARED
-- IN AN ENCLOSING GENERIC UNIT.

-- SPS 6/8/82

PROCEDURE BC3403C IS

     GENERIC
          TYPE INDEX IS (<>);
     PACKAGE PACK IS 
          SUBTYPE IND IS INDEX;
          TYPE NIND IS NEW INDEX;
          SUBTYPE NATURAL IS INTEGER RANGE 1..INTEGER'LAST;
          TYPE AI IS ARRAY (INDEX) OF NATURAL;
          TYPE AIU IS ARRAY (INDEX RANGE <>) OF NATURAL;
          TYPE AIND IS ARRAY (IND) OF NATURAL;
          TYPE ANIND IS ARRAY (NIND) OF NATURAL;
          TYPE AN IS ARRAY (NATURAL) OF NATURAL;
          TYPE A_I IS ARRAY (INTEGER) OF NATURAL;
          TYPE AB IS ARRAY (BOOLEAN) OF NATURAL;
          TYPE AC IS ARRAY (CHARACTER) OF NATURAL;

          GENERIC
               TYPE AR IS ARRAY (INDEX) OF NATURAL;
          PACKAGE P IS END P;

          PACKAGE P1 IS NEW P (AI);          -- OK.
          PACKAGE P2 IS NEW P (A_I);         -- ERROR: INTEGER.
          PACKAGE P3 IS NEW P (AN);          -- ERROR: NATURAL.
          PACKAGE P4 IS NEW P (AB);          -- ERROR: BOOLEAN.
          PACKAGE P5 IS NEW P (AC);          -- ERROR: CHARACTER.
          PACKAGE P6 IS NEW P (AIND);        -- OK.
          PACKAGE P7 IS NEW P (ANIND);       -- ERROR: NIND.

     END PACK;

BEGIN
     NULL;
END BC3403C;
