-- BC3402B.ADA

-- CHECK THAT A FORMAL AND ACTUAL GENERIC ARRAY TYPE MUST HAVE THE SAME
-- NUMBER OF DIMENSIONS.

-- CHECK WHERE THE ACTUAL PARAMETER IS A FORMAL PARAMETER OF AN
-- ENCLOSING GENERIC UNIT.

-- SPS 6/8/82

PROCEDURE BC3402B IS
     SUBTYPE NATURAL IS INTEGER RANGE 1..INTEGER'LAST;
     GENERIC
          TYPE ARR1 IS ARRAY (INTEGER) OF NATURAL;
          TYPE ARR2 IS ARRAY (INTEGER, INTEGER) OF NATURAL;
          TYPE ARR3 IS ARRAY (INTEGER, INTEGER, INTEGER) OF NATURAL;
     PACKAGE PACK IS

          GENERIC
               TYPE T IS ARRAY (INTEGER) OF NATURAL;
          PACKAGE P IS END P;

          GENERIC
               TYPE T IS ARRAY (INTEGER, INTEGER) OF NATURAL;
          PACKAGE PP IS END PP;

          GENERIC
               TYPE T IS ARRAY (INTEGER, INTEGER, INTEGER) OF NATURAL;
          PACKAGE PPP IS END PPP;

          PACKAGE P1 IS NEW P (ARR1);             -- OK.
          PACKAGE P2 IS NEW P (ARR2);             -- ERROR: ARR2.
          PACKAGE P3 IS NEW P (ARR3);             -- ERROR: ARR3.

          PACKAGE PP1 IS NEW PP (ARR1);           -- ERROR: ARR1.
          PACKAGE PP2 IS NEW PP (ARR2);           -- OK.
          PACKAGE PP3 IS NEW PP (ARR3);           -- ERROR: ARR3.

          PACKAGE PPP1 IS NEW PPP (ARR1);         -- ERROR: ARR1.
          PACKAGE PPP2 IS NEW PPP (ARR2);         -- ERROR: ARR2.
          PACKAGE PPP3 IS NEW PPP (ARR3);         -- OK.

     END PACK;

BEGIN
     NULL;
END BC3402B;
