-- BC3404C.ADA

-- CHECK THAT THE COMPONENT BASE TYPE OF A GENERIC ARRAY TYPE PARAMETER
-- MUST BE THE SAME AS THE COMPONENT BASE TYPE OF THE ACTUAL PARAMETER.

-- CHECK WHEN THE COMPONENT TYPE OF THE FORMAL ARRAY TYPE IS A GENERIC 
-- FORMAL PARAMETER DECLARED IN AN ENCLOSING GENERIC UNIT.

-- SPS 6/23/82
-- JRK 3/26/84

PROCEDURE BC3404C IS

     GENERIC
          TYPE COMP IS (<>);
     PACKAGE PACK IS
          SUBTYPE CC IS COMP RANGE COMP'FIRST .. COMP'VAL(2);
          TYPE NCOMP IS NEW COMP;
          SUBTYPE NATURAL IS INTEGER RANGE 1..INTEGER'LAST;
          TYPE AR_COMP IS ARRAY (NATURAL) OF COMP;
          TYPE AR_CC IS ARRAY (NATURAL) OF CC;
          TYPE AR_B IS ARRAY (NATURAL) OF BOOLEAN;
          TYPE AR_NCOMP IS ARRAY (NATURAL) OF NCOMP;
          TYPE AR_I IS ARRAY (NATURAL) OF INTEGER;
          TYPE AR_C IS ARRAY (NATURAL) OF CHARACTER;

          GENERIC
               TYPE FT IS ARRAY (NATURAL) OF COMP;
          PACKAGE P IS END P;

          PACKAGE P1 IS NEW P (AR_COMP);     -- OK.
          PACKAGE P2 IS NEW P (AR_CC);       -- OK.
          PACKAGE P3 IS NEW P (AR_NCOMP);    -- ERROR: AR_NCOMP.
          PACKAGE P4 IS NEW P (AR_C);        -- ERROR: AR_C.
          PACKAGE P5 IS NEW P (AR_B);        -- ERROR: AR_B.
          PACKAGE P6 IS NEW P (AR_I);        -- ERROR: AR_I.

     END PACK;

BEGIN
     NULL;
END BC3404C;
