-- BC3401B.ADA

-- CHECK THAT IF A GENERIC FORMAL TYPE IS AN ARRAY TYPE, THE ACTUAL
-- PARAMETER MUST ALSO BE AN ARRAY TYPE.

-- CHECK WHEN THE ACTUAL IS A GENERIC FORMAL PARAMETER APPEARING IN AN
-- ENCLOSING GENERIC DECLARATION.

-- SPS 6/8/82

PROCEDURE BC3401B IS

     SUBTYPE NATURAL IS INTEGER RANGE 1..INTEGER'LAST;

     GENERIC
          TYPE PV IS PRIVATE;
          TYPE LP IS LIMITED PRIVATE;
          TYPE INT IS RANGE <>;
          TYPE DESC IS (<>);
          TYPE ARR IS ARRAY (INTEGER) OF NATURAL;
     PACKAGE PACK IS

          GENERIC
               TYPE AR IS ARRAY (INTEGER) OF NATURAL;
          PACKAGE P IS END P;

          PACKAGE P1 IS NEW P (ARR);         -- OK.
          PACKAGE P2 IS NEW P (PV);          -- ERROR: PV.
          PACKAGE P3 IS NEW P (LP);          -- ERROR: LP.
          PACKAGE P4 IS NEW P (INT);         -- ERROR: INT.
          PACKAGE P5 IS NEW P (DESC);        -- ERROR: DESC.

     END PACK;

BEGIN
     NULL;
END BC3401B;
