-- BC3502A.ADA

-- CHECK THAT WHEN A GENERIC FORMAL TYPE IS AN ACCESS TYPE,
-- THE FORMAL TYPE IS ONLY MATCHED WHEN ITS DESIGNATED BASE TYPE
-- IS THE SAME AS THE DESIGNATED TYPE OF THE ACTUAL PARAMETER.

-- CHECK FOR WHEN THE DESIGNATED TYPE IS NOT A GENERIC FORMAL TYPE.

-- SPS 5/24/82

PROCEDURE BC3502A IS

     SUBTYPE T IS INTEGER;
     TYPE U IS NEW INTEGER;
     TYPE A IS ACCESS T;
     TYPE AU IS ACCESS U;
     GENERIC
          TYPE FT IS ACCESS NATURAL;
     PACKAGE P IS END P;

     PACKAGE P1 IS NEW P (A);                -- OK.
     PACKAGE P2 IS NEW P (AU);               -- ERROR: AU.

     TYPE ENUM IS (E1, E2, E3, E4);
     TYPE EN IS (E1, E2, E3, E4);
     TYPE ENU IS NEW ENUM;
     SUBTYPE E IS ENUM;
     TYPE AENUM IS ACCESS ENUM;
     TYPE AEN IS ACCESS EN;
     TYPE AENU IS ACCESS ENU;
     TYPE AE IS ACCESS E;

     GENERIC
          TYPE FT IS ACCESS ENUM;
     PACKAGE PP IS END PP;

     PACKAGE P3 IS NEW PP (AENUM);           -- OK.
     PACKAGE P4 IS NEW PP (AE);              -- OK.
     PACKAGE P5 IS NEW PP (AEN);             -- ERROR: AEN.
     PACKAGE P6 IS NEW PP (AU);              -- ERROR: AU.
     PACKAGE P7 IS NEW PP (AENU);            -- ERROR: AENU.

BEGIN
     NULL;
END BC3502A;
