-- BC3502K.ADA

-- CHECK THAT WHEN A GENERIC FORMAL TYPE IS AN ACCESS TYPE, THE FORMAL
-- TYPE IS ONLY MATCHED WHEN ITS DESIGNATED BASE TYPE IS THE SAME AS THE
-- DESIGNATED BASE TYPE OF THE ACTUAL PARAMTER.

-- CHECK WHEN THE DESIGNATED BASE TYPE OF THE FORMAL IS A GENERIC FORMAL
-- TYPE APPEARING IN AN ENCLOSING GENERIC DECLARATION.

-- SPS 5/26/82

PROCEDURE BC3502K IS

     GENERIC
          TYPE T IS (<>);
     PACKAGE PACK IS

          GENERIC
               TYPE FT IS ACCESS T;
          PACKAGE P IS END P;

          TYPE A IS ACCESS T;
          TYPE AI IS ACCESS INTEGER;
          TYPE AB IS ACCESS BOOLEAN;

          PACKAGE P1 IS NEW P (A);           -- OK.
          PACKAGE P2 IS NEW P (AI);          -- ERROR: AI.
          PACKAGE P3 IS NEW P (AB);          -- ERROR: AB.

     END PACK;

BEGIN
     NULL;
END BC3502K;
