-- BC3501A.ADA

-- CHECK THAT IF A FORMAL GENERIC TYPE FT IS AN ACCESS TYPE, THE
-- CORRESPONDING ACTUAL TYPE PARAMETER MUST BE AN ACCESS TYPE.
-- CHECK THAT FT DOES NOT MATCH AN ACTUAL TYPE THAT IS THE BASE TYPE OF
-- THE FORMAL PARAMETER'S DESIGNATED TYPE.  CHECK WHEN THE DESIGNATED
-- TYPE IS NOT A GENERIC FORMAL TYPE DECLARED IN THE SAME FORMAL PART AS
-- FT.

-- DAT 9/24/81
-- SPS 5/18/82

PROCEDURE BC3501A IS


     TYPE AI IS ACCESS INTEGER;
     GENERIC
          TYPE FT IS ACCESS INTEGER;
     PACKAGE Q IS END Q;

     PACKAGE Q1 IS NEW Q (AI);               -- OK.
     PACKAGE Q2 IS NEW Q (INTEGER);          -- ERROR: INTEGER IS NOT AN
                                             -- ACCESS TYPE.

     TYPE AC IS ACCESS CHARACTER;
     GENERIC
          TYPE FT IS ACCESS CHARACTER;
     PACKAGE QA IS END QA;

     PACKAGE Q3 IS NEW QA (AC);              -- OK.
     PACKAGE Q4 IS NEW QA (CHARACTER);       -- ERROR: CHARACTER IS NOT
                                             -- AN ACCESS TYPE.

     TYPE AB IS ACCESS BOOLEAN;
     GENERIC
          TYPE FT IS ACCESS BOOLEAN;
     PACKAGE QB IS END QB;

     PACKAGE Q5 IS NEW QB (AB);              -- OK.
     PACKAGE Q6 IS NEW QB (BOOLEAN);         -- ERROR: BOOLEAN IS NOT AN
                                             -- ACCESS TYPE.

     TYPE ENUM IS (E1, E2, E3, E4);
     TYPE AE IS ACCESS ENUM;
     GENERIC
          TYPE FT IS ACCESS ENUM;
     PACKAGE QC IS END QC;

     PACKAGE Q7 IS NEW QC (AE);              -- OK.
     PACKAGE Q8 IS NEW QC (ENUM);            -- ERROR: ENUM IS NOT AN
                                             -- ACCESS TYPE.

BEGIN
     NULL;
END BC3501A;
