-- BC3501K.ADA

-- CHECK THAT IF A FORMAL GENERIC TYPE FT IS AN ACCESS TYPE, THE
-- CORRESPONDING ACTUAL TYPE PARAMETER MUST BE AN ACCESS TYPE.

-- CHECK THAT FT DOES NOT MATCH AN ACTUAL PARAMETER THAT IS THE BASE
-- TYPE OF FT'S DESIGNATED TYPE.  

-- CHECK WHEN THE DESIGNATED TYPE IS A GENERIC FORMAL TYPE DECLARED IN 
-- THE SAME FORMAL PART AS FT.

-- CHECK WHEN THE DESIGNATED TYPE IS A FIXED OR FLOAT TYPE.

-- SPS 7/19/82

PROCEDURE BC3501K IS

     GENERIC
          TYPE T IS DELTA <>;
          TYPE FT IS ACCESS T;
     PACKAGE P IS END P;

     GENERIC
          TYPE T IS DIGITS <>;
          TYPE FT IS ACCESS T;
     PACKAGE PQ IS END PQ;

     TYPE AFL IS ACCESS FLOAT;
     PACKAGE PQ1 IS NEW PQ (FLOAT, AFL);     -- OK.
     PACKAGE PQ2 IS NEW PQ (FLOAT, FLOAT);   -- ERROR: FLOAT IS NOT AN
                                             -- ACCESS TYPE.

     TYPE FX IS DELTA 0.1 RANGE 1.0 .. 3.0;
     TYPE AFX IS ACCESS FX;
     PACKAGE P1 IS NEW P (FX, AFX);          -- OK.
     PACKAGE P2 IS NEW P (FX, FX);           -- ERROR: FX IS
                                             -- NOT AN ACCESS TYPE.

BEGIN
     NULL;
END BC3501K;
