-- BC3501I.ADA

-- CHECK THAT IF A FORMAL GENERIC TYPE FT IS AN ACCESS TYPE, THE
-- CORRESPONDING ACTUAL TYPE PARAMETER MUST BE AN ACCESS TYPE.  CHECK
-- THAT FT DOES NOT MATCH AN ACTUAL PARAMETER THAT IS THE BASE TYPE OF
-- FT'S DESIGNATED TYPE.  CHECK WHEN FT'S DESIGNATED TYPE AND THE ACTUAL
-- TYPE ARE GENERIC FORMAL TYPES APPEARING IN AN ENCLOSING GENERIC
-- DECLARATION.

-- SPS 5/24/82

PROCEDURE BC3501I IS

     GENERIC
          TYPE T IS PRIVATE;
          TYPE U IS PRIVATE;
     PACKAGE PACK IS
          TYPE A IS ACCESS T;
          TYPE AU IS ACCESS U;

          GENERIC 
               TYPE FT IS ACCESS T;
          PACKAGE P IS END P;

          PACKAGE P1 IS NEW P(A);            -- OK.
          PACKAGE P2 IS NEW P(T);            -- ERROR: T IS NOT AN
                                             -- ACCESS TYPE.
          PACKAGE P3 IS NEW P(U);            -- ERROR: U IS NOT AN
                                             -- ACCESS TYPE.

          GENERIC
               TYPE T IS PRIVATE;
               TYPE FT IS ACCESS T;
          PACKAGE PP IS END PP;

          PACKAGE P4 IS NEW PP (U, AU);      -- OK.
          PACKAGE P5 IS NEW PP (U, U);       -- ERROR: U IS NOT AN
                                             -- ACCESS TYPE.
     END PACK;

BEGIN
     NULL;
END BC3501I;
