-- BC3501J.ADA

-- CHECK THAT IF A FORMAL GENERIC TYPE FT IS AN ACCESS TYPE, THE
-- CORRESPONDING ACTUAL TYPE PARAMETER MUST BE AN ACCESS TYPE.

-- CHECK THAT FT DOES NOT MATCH AN ACTUAL TYPE THAT IS THE BASE TYPE OF
-- THE FORMAL PARAMETER'S DESIGNATED TYPE.  

-- CHECK WHEN THE DESIGNATED TYPE IS NOT A GENERIC FORMAL TYPE DECLARED 
-- IN THE SAME FORMAL PART AS FT.

-- CHECK WHEN THE DESIGNATED TYPE IS A FIXED OR FLOAT TYPE.

-- SPS 5/18/82

PROCEDURE BC3501J IS

     TYPE AF IS ACCESS FLOAT;

     GENERIC
          TYPE FT IS ACCESS FLOAT;
     PACKAGE Q IS END Q;

     PACKAGE Q1 IS NEW Q (AF);               -- OK.
     PACKAGE Q2 IS NEW Q (FLOAT);            -- ERROR: FLOAT IS NOT AN
                                             -- ACCESS TYPE.

     TYPE FX IS DELTA 0.1 RANGE 1.0 .. 3.0;
     TYPE AFX IS ACCESS FX;

     GENERIC
          TYPE FT IS ACCESS FX;
     PACKAGE QA IS END QA;

     PACKAGE Q3 IS NEW QA (AFX);             -- OK.
     PACKAGE Q4 IS NEW QA (FX);              -- ERROR: FX IS NOT
                                             -- AN ACCESS TYPE.

BEGIN
     NULL;
END BC3501J;
