-- BC3501B.ADA

-- CHECK THAT IF A FORMAL GENERIC TYPE FT IS AN ACCESS TYPE, THE
-- CORRESPONDING ACTUAL TYPE PARAMETER MUST BE AN ACCESS TYPE.
-- CHECK THAT FT DOES NOT MATCH AN ACTUAL PARAMETER THAT IS THE BASE
-- TYPE OF FT'S DESIGNATED TYPE.  CHECK WHEN THE DESIGNATED TYPE IS A
-- GENERIC FORMAL TYPE DECLARED IN THE SAME FORMAL PART AS FT.

-- SPS 5/18/82

PROCEDURE BC3501B IS

     GENERIC
          TYPE T IS (<>);
          TYPE FT IS ACCESS T;
     PACKAGE P IS END P;

     TYPE AI IS ACCESS INTEGER;
     PACKAGE P1 IS NEW P (INTEGER, AI);      -- OK.
     PACKAGE P2 IS NEW P (INTEGER, INTEGER); -- ERROR: INTEGER IS NOT AN
                                             -- ACCESS TYPE.

     TYPE AC IS ACCESS CHARACTER;
     PACKAGE P3 IS NEW P (CHARACTER, AC);    -- OK.
     PACKAGE P4 IS NEW P (CHARACTER, CHARACTER); -- ERROR: CHARACTER IS
                                             -- NOT AN ACCESS TYPE.

     TYPE AB IS ACCESS BOOLEAN;
     PACKAGE P5 IS NEW P (BOOLEAN, AB);      -- OK.
     PACKAGE P6 IS NEW P (BOOLEAN, BOOLEAN); -- ERROR: BOOLEAN IS NOT AN
                                             -- ACCESS TYPE.

     TYPE ENUM IS (E1, E2, E3, E4);
     TYPE AE IS ACCESS ENUM;
     PACKAGE P7 IS NEW P (ENUM, AE);         -- OK.
     PACKAGE P8 IS NEW P (ENUM, ENUM);       -- ERROR: ENUM IS NOT AN
                                             -- ACCESS TYPE.

BEGIN
     NULL;
END BC3501B;
