-- BC3502O.ADA

-- CHECK THAT WHEN A GENERIC FORMAL TYPE IS AN ACCESS TYPE,
-- THE FORMAL TYPE IS ONLY MATCHED WHEN ITS DESIGNATED BASE TYPE
-- IS THE SAME AS THE DESIGNATED BASE TYPE OF THE ACTUAL PARAMETER.

-- CHECK WHEN THE DESIGNATED TYPE IS A GENERIC FORMAL TYPE DECLARED
-- IN THE SAME FORMAL PART AS FT.

-- CHECK WHEN THE DESIGNATED TYPE IS A FIXED OR FLOAT TYPE.

-- SPS 7/19/82

PROCEDURE BC3502O IS

     SUBTYPE FL IS FLOAT;
     TYPE NFL IS NEW FLOAT;
     TYPE AFL IS ACCESS FL;
     TYPE ANFL IS ACCESS NFL;
     TYPE AFLOAT IS ACCESS FLOAT;

     TYPE FX IS DELTA 0.1 RANGE 1.0 .. 3.0;
     TYPE FXX IS DELTA 0.1 RANGE 1.0 .. 3.0;
     TYPE NFX IS NEW FX;
     SUBTYPE SFX IS FX;
     TYPE AFX IS ACCESS FX;
     TYPE AFXX IS ACCESS FXX;
     TYPE ANFX IS ACCESS NFX;
     TYPE ASFX IS ACCESS SFX;

     GENERIC
          TYPE T IS DIGITS <>;
          TYPE FT IS ACCESS T;
     PACKAGE P IS END P;

     GENERIC
          TYPE T IS DELTA <>;
          TYPE FT IS ACCESS T;
     PACKAGE PP IS END PP;

     PACKAGE P1 IS NEW P (FLOAT, AFLOAT);    -- OK.
     PACKAGE P2 IS NEW P (FLOAT, AFL);       -- OK.
     PACKAGE P3 IS NEW P (FLOAT, ANFL);      -- ERROR: ANFL.

     PACKAGE PP1 IS NEW PP (FX, AFX);        -- OK.
     PACKAGE PP2 IS NEW PP (FX, AFXX);       -- ERROR: AFXX.
     PACKAGE PP3 IS NEW PP (FX, ANFX);       -- ERROR: ANFX.
     PACKAGE PP4 IS NEW PP (FX, ASFX);       -- OK.

BEGIN
     NULL;
END BC3502O;
