-- BC3502M.ADA

-- CHECK THAT WHEN A GENERIC FORMAL TYPE IS AN ACCESS TYPE, THE FORMAL
-- TYPE IS ONLY MATCHED WHEN ITS DESIGNATED BASE TYPE IS THE SAME AS THE
-- DESIGNATED BASE TYPE OF THE ACTUAL PARAMTER.

-- CHECK WHEN BOTH THE DESIGNATED BASE TYPE OF THE ACTUAL AND THE FORMAL
-- ARE GENERIC FORMAL TYPES APPEARING IN AN ENCLOSING GENERIC 
-- DECLARATION.

-- SPS 5/26/82

PROCEDURE BC3502M IS

     GENERIC
          TYPE T IS (<>);
          TYPE U IS RANGE <>;
     PACKAGE PACK IS

          GENERIC
               TYPE FT IS ACCESS T;
          PACKAGE P IS END P;

          TYPE A IS ACCESS T;
          TYPE AU IS ACCESS U;
          TYPE AI IS ACCESS INTEGER;
          TYPE AN IS ACCESS NATURAL;

          PACKAGE P1 IS NEW P (A);           -- OK.
          PACKAGE P2 IS NEW P (AI);          -- ERROR: AI.
          PACKAGE P3 IS NEW P (AN);          -- ERROR: AN.
          PACKAGE P4 IS NEW P (AU);          -- ERROR: AU.
     END PACK;

BEGIN
     NULL;
END BC3502M;
