-- BD2A35A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR AN INTEGER TYPE MUST
--     BE REJECTED IF THE SIZE IS TOO SMALL FOR THE VALUES OF
--     THE TYPE.

-- HISTORY:
--     JKC 03/29/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A35A IS

     TYPE INTEGER_TYPE IS RANGE 1..100;
     FOR INTEGER_TYPE'SIZE USE 4;                   -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A35A;
