-- BD2A55B.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR A FIXED TYPE MUST BE REJECTED
--     IF THE SIZE IS TOO SMALL TO REPRESENT ALL THE VALUES (WHERE A
--     'SMALL SPECIFICATION HAS BEEN GIVEN).

-- HISTORY:
--     DHH 08/22/88 CREATED ORIGINAL TEST.

PROCEDURE BD2A55B IS

     TYPE FIXED_TYPE IS DELTA 0.5 RANGE 0.0 .. 4.0;
     FOR FIXED_TYPE'SMALL USE 0.125;
     FOR FIXED_TYPE'SIZE USE 4;                     -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A55B;
