-- BD2A85B.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR AN ACCESS TYPE MUST BE
--     REJECTED IF THE SIZE SPECIFICATION IS TOO SMALL (WHERE A
--     COLLECTION SIZE SPECIFICATION HAS BEEN GIVEN).

-- HISTORY:
--     DHH 08/22/88 CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
PROCEDURE BD2A85B IS

     UNITS_PER_INTEGER : CONSTANT := (SYSTEM.STORAGE_UNIT - 1)/
                                      SYSTEM.STORAGE_UNIT;
     TYPE ACCESS_TYPE IS ACCESS INTEGER;
     FOR ACCESS_TYPE'STORAGE_SIZE USE 36 * UNITS_PER_INTEGER;

     FOR ACCESS_TYPE'SIZE USE 3;                    -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A85B;
