-- BD2A12A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION CANNOT BE GIVEN FOR AN
--     UNCONSTRAINED ARRAY TYPE THAT HAS A NONSTATIC INDEX TYPE.

-- HISTORY:
--     JKC 03/17/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A12A IS

     I : ARRAY (1..2) OF INTEGER;
     SUBTYPE INDEX IS INTEGER RANGE I'RANGE;
     TYPE A IS ARRAY (INDEX RANGE <>) OF INTEGER;
     FOR A'SIZE USE 128;                                  -- ERROR:

BEGIN
     NULL;
END BD2A12A;
