-- BD2A25A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR AN ENUMERATION TYPE,
--     WHERE AN ENUMERATION REPRESENTATION CLAUSE HAS AND HAS
--     NOT BEEN GIVEN, MUST BE REJECTED IF THE SIZE IS TOO SMALL
--     TO REPRESENT ALL THE VALUES.

-- HISTORY:
--     JKC 03/29/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A25A IS

     TYPE BASIC_ENUM IS (A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,
                         U,V,W,X,Y,Z);
     FOR BASIC_ENUM'SIZE USE 4;                     -- ERROR: TOO SMALL.

     TYPE ENUM IS (RED, BLUE, YELLOW, GREEN);
     FOR ENUM USE (RED=>1, BLUE=>2, YELLOW=>3, GREEN=>20);
     FOR ENUM'SIZE USE 2;                           -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A25A;
