-- BD2A45A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR A FLOATING TYPE MUST
--     BE REJECTED IF IT IS TOO SMALL FOR THE VALUES OF THE TYPE.

-- HISTORY:
--     JKC 03/29/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A45A IS

     TYPE FLOAT_TYPE IS DIGITS 5;
     FOR FLOAT_TYPE'SIZE USE 2;                    -- ERROR:  TOO SMALL.

BEGIN
     NULL;
END BD2A45A;
