-- BD2A77A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION IS REJECTED IF IT IS TOO SMALL
--     FOR A RECORD TYPE.

-- HISTORY:
--     JKC 04/01/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A77A IS

     TYPE RECORD_TYPE IS
          RECORD
               UNIT1: INTEGER := 1;
               UNIT2: INTEGER := 2;
               UNIT3: INTEGER := 3;
          END RECORD;
     FOR RECORD_TYPE'SIZE USE INTEGER'SIZE/2;       -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A77A;
