-- BD2A55A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR A FIXED TYPE MUST BE REJECTED
--     IF THE SIZE IS TOO SMALL TO REPRESENT ALL THE VALUES (WHERE NO
--     'SMALL SPECIFICATION HAS BEEN GIVEN).

-- HISTORY:
--     JKC 03/31/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A55A IS

     TYPE FIXED_TYPE IS DELTA 0.25 RANGE 1.0..100.0;
     FOR FIXED_TYPE'SIZE USE 4;                     -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A55A;
