-- BD2A67A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION IS REJECTED IF IT IS TOO SMALL
--     FOR AN ARRAY TYPE.

-- HISTORY:
--     JKC 03/31/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A67A IS

     TYPE ARRAY_TYPE IS ARRAY (1..4) OF INTEGER;
     FOR ARRAY_TYPE'SIZE USE INTEGER'SIZE;          -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A67A;
