-- BD2A85A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION FOR AN ACCESS TYPE MUST BE
--     REJECTED IF THE SIZE SPECIFICATION IS TOO SMALL (WHERE NO
--     COLLECTION SIZE SPECIFICATION HAS BEEN GIVEN).

-- HISTORY:
--     JKC 03/31/88  CREATED ORIGINAL TEST.

PROCEDURE BD2A85A IS

     TYPE ARRAY_TYPE IS ARRAY (1..100) OF INTEGER;
     TYPE ACCESS_TYPE IS ACCESS ARRAY_TYPE;
     FOR ACCESS_TYPE'SIZE USE 2;                    -- ERROR: TOO SMALL.

BEGIN
     NULL;
END BD2A85A;
