-- BD2B02A.ADA

-- OBJECTIVE:
--     CHECK THAT TWO COLLECTION SIZE SPECIFICATIONS, EVEN IF THE SAME,
--     CANNOT BE GIVEN FOR THE SAME TYPE.

-- HISTORY:
--     JKC 04/06/88  CREATED ORIGINAL TEST.

PROCEDURE BD2B02A IS

     TYPE ARRAY_TYPE IS ARRAY (1..4) OF INTEGER;
     TYPE ACCESS_TYPE IS ACCESS ARRAY_TYPE;
     FOR ACCESS_TYPE'STORAGE_SIZE USE 1024;
     FOR ACCESS_TYPE'STORAGE_SIZE USE 1024;        -- ERROR:  DUPLICATE.

     TYPE A_TYPE IS ACCESS ARRAY_TYPE;
     FOR A_TYPE'STORAGE_SIZE USE 1024;
     FOR A_TYPE'STORAGE_SIZE USE 2048;             -- ERROR:  DUPLICATE.

BEGIN
     NULL;
END BD2B02A;
