-- BD2B03A.ADA

-- OBJECTIVE:
--     CHECK THAT A COLLECTION SIZE SPECIFICATION CANNOT BE GIVEN:
--     - IN A PACKAGE SPECIFICATION FOR A TYPE DECLARED IN AN INNER
--       PACKAGE SPECIFICATION;
--     - IN A PACKAGE OR TASK SPECIFICATION FOR A TYPE DECLARED IN AN
--       ENCLOSING PACKAGE SPECIFICATION OR DECLARATIVE PART;
--     - IN A PACKAGE BODY FOR A TYPE DECLARED IN THE CORRESPONDING
--       PACKAGE SPECIFICATION;
--     - IN A DECLARATIVE PART AFTER THE OCCURRENCE OF THE BODY.

-- HISTORY:
--     JKC 04/06/88  CREATED ORIGINAL TEST.

PROCEDURE BD2B03A IS

     PACKAGE P IS
          TYPE ACC2 IS ACCESS INTEGER;
          TYPE ACC6 IS ACCESS STRING;

          PACKAGE INNER_P IS
               TYPE ARRAY_TYPE IS ARRAY (1..4) OF INTEGER;
               TYPE ACC1 IS ACCESS ARRAY_TYPE;
          END INNER_P;

          USE INNER_P;

          FOR ACC1'STORAGE_SIZE USE 512;                       -- ERROR:

          PACKAGE INNER_Q IS
               FOR ACC2'STORAGE_SIZE USE 512;                  -- ERROR:
          END INNER_Q;

     END P;

     PACKAGE BODY P IS
          FOR ACC6'STORAGE_SIZE USE 1024;                      -- ERROR:
     END P;

     PACKAGE Q IS
          TYPE ACC4 IS ACCESS INTEGER;

          TASK T IS
               FOR ACC4'STORAGE_SIZE USE 1024;                 -- ERROR:
          END T;
     END Q;

     PACKAGE BODY Q IS
          TASK BODY T IS
          BEGIN
               NULL;
          END T;
     END Q;

BEGIN
     DECLARE
          TYPE ACC3 IS ACCESS INTEGER;

          PACKAGE S IS
               FOR ACC3'STORAGE_SIZE USE 1024;                 -- ERROR:
          END S;

          TYPE ACC5 IS ACCESS STRING;
          TYPE ACC7 IS ACCESS STRING;

          TASK T2 IS
               FOR ACC5'STORAGE_SIZE USE 1024;                 -- ERROR:
          END T2;

          FUNCTION F RETURN INTEGER IS
          BEGIN
               RETURN 5;
          END F;

          FOR ACC7'STORAGE_SIZE USE 1024;                      -- ERROR:

          TASK BODY T2 IS
          BEGIN
               NULL;
          END T2;

     BEGIN
          NULL;
     END;

END BD2B03A;
