-- BD2B01C.ADA

-- OBJECTIVE:
--     CHECK THAT A COLLECTION SIZE SPECIFICATION CANNOT BE GIVEN FOR
--     A DERIVED ACCESS TYPE.

-- HISTORY:
--     JKC 04/05/88  CREATED ORIGINAL TEST.

PROCEDURE BD2B01C IS

     TYPE ARRAY_TYPE IS ARRAY (1..100) OF INTEGER;
     TYPE ACCESS_TYPE IS ACCESS ARRAY_TYPE;
     TYPE D_ACCESS IS NEW ACCESS_TYPE;
     FOR D_ACCESS'STORAGE_SIZE USE 512;                       -- ERROR:

BEGIN
     NULL;
END BD2B01C;
