-- BD2B14A.ADA

-- OBJECTIVE:
--     CHECK THAT THE EXPRESSION IN A COLLECTION SIZE SPECIFICATION
--     MUST BE A SIMPLE EXPRESSION.

-- HISTORY:
--     JKC 04/06/88  CREATED ORIGINAL TEST.

PROCEDURE BD2B14A IS

     TYPE T IS NEW INTEGER;

     FUNCTION "<" (U,V : T) RETURN T IS
     BEGIN
          RETURN 1024;
     END "<";

     FUNCTION ">" (W,X : T) RETURN T IS
     BEGIN
          RETURN 1024;
     END ">";

     FUNCTION "OR" (Y,Z : T) RETURN T IS
     BEGIN
          RETURN 1024;
     END "OR";

     FUNCTION "AND" (A,B : T) RETURN T IS
     BEGIN
          RETURN 1024;
     END "AND";

BEGIN
     DECLARE
          TYPE INT IS NEW INTEGER;
          SZ1 : CONSTANT T := 2;
          SZ2 : CONSTANT T := 2;

          TYPE ARRAY_TYPE IS ARRAY (1..10) OF INTEGER;

          TYPE ACCESS1 IS ACCESS INTEGER;
          FOR ACCESS1'STORAGE_SIZE USE SZ1 < SZ2;            -- ERROR:

          TYPE ACCESS2 IS ACCESS INTEGER;
          FOR ACCESS2'STORAGE_SIZE USE 3 OR SZ1;             -- ERROR:

          TYPE ACCESS3 IS ACCESS STRING;
          FOR ACCESS3'STORAGE_SIZE USE SZ1 AND SZ2;          -- ERROR:

          TYPE ACCESS4 IS ACCESS ARRAY_TYPE;
          FOR ACCESS4'STORAGE_SIZE USE SZ1 > SZ2;            -- ERROR:


     BEGIN
          NULL;
     END;

END BD2B14A;
