-- BD2D02A.ADA

-- OBJECTIVE:
--     CHECK THAT TWO 'SMALL SPECIFICATIONS (EVEN IF IDENTICAL) CANNOT
--     BE GIVEN FOR THE SAME TYPE.

-- HISTORY:
--     BCB 04/05/88  CREATED ORIGINAL TEST.

PROCEDURE BD2D02A IS

     CHECK_SMALL1 : CONSTANT := 0.25;
     CHECK_SMALL2 : CONSTANT := 0.125;

     TYPE FIX1 IS DELTA 2.0**(-1) RANGE -1.0 .. 1.0;
     TYPE FIX2 IS DELTA 2.0**(-1) RANGE -1.0 .. 1.0;

     FOR FIX1'SMALL USE CHECK_SMALL1;
     FOR FIX1'SMALL USE CHECK_SMALL2;      -- ERROR: SECOND 'SMALL
                                           --        SPECIFICATION.

     FOR FIX2'SMALL USE CHECK_SMALL1;
     FOR FIX2'SMALL USE CHECK_SMALL1;      -- ERROR: SECOND 'SMALL
                                           --        SPECIFICATION.

BEGIN
     NULL;
END BD2D02A;
