-- BD2D01C.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SMALL SPECIFICATION CANNOT BE GIVEN FOR A NAME
--     DECLARED BY AN OBJECT OR A SUBTYPE DECLARATION.

-- HISTORY:
--     BCB 04/05/88  CREATED ORIGINAL TEST.

PROCEDURE BD2D01C IS

     CHECK_SMALL : CONSTANT := 0.25;

     TYPE FIX IS DELTA 2.0**(-1) RANGE -1.0 .. 1.0;

     TYPE FX IS DELTA 2.0**(-1) RANGE -1.0 .. 1.0;
     SUBTYPE SFX IS FX;

     F1 : FIX;

     FOR F1'SMALL USE CHECK_SMALL;            -- ERROR: OBJECT.
     FOR SFX'SMALL USE CHECK_SMALL;           -- ERROR: SUBTYPE.

BEGIN
     NULL;
END BD2D01C;
