-- BD2D01D.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SMALL SPECIFICATION CANNOT BE GIVEN FOR A PRIVATE
--     OR INCOMPLETE TYPE PRIOR TO THE FULL DECLARATION.

-- HISTORY:
--     DHH 08/22/88 CREATED ORIGINAL TEST.

PACKAGE BD2D01D IS

     TYPE INCOM;
     TYPE ACC_INCOM IS ACCESS INCOM;

     TYPE PRIV IS PRIVATE;
     TYPE PRIV1 IS PRIVATE;

     FOR INCOM'SMALL USE 0.125;                         -- ERROR:

     TYPE INCOM IS DELTA 0.25 RANGE -1.0 .. 1.0;

     FOR PRIV'SMALL USE 0.125;                          -- ERROR:

PRIVATE
     FOR PRIV1'SMALL USE 0.125;                         -- ERROR:

     TYPE PRIV IS DELTA 0.25 RANGE -1.0 .. 1.0;
     TYPE PRIV1 IS DELTA 0.25 RANGE -1.0 .. 1.0;

END BD2D01D;
