-- BD3001A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION REPRESENTATION CLAUSE CANNOT BE GIVEN
--     FOR AN EXPANDED NAME THAT DENOTES AN ENUMERATION TYPE.

-- HISTORY:
--     JKC 04/12/88  CREATED ORIGINAL TEST.

PROCEDURE BD3001A IS

     TYPE ENUM IS (A,B,C,D,E);

     FOR BD3001A.ENUM USE (1,2,3,4,5);                       -- ERROR:

BEGIN
     NULL;
END BD3001A;
