-- BD3013A.ADA

-- OBJECTIVE:
--     CHECK THAT THE CODES IN AN ENUMERATION REPRESENTATION
--     AGGREGATE MUST BE DISTINCT AND OBEY THE PREDEFINED ORDERING
--     RELATION FOR THE TYPE.

-- HISTORY:
--     JKC 04/12/88  CREATED ORIGINAL TEST.

PROCEDURE BD3013A IS

     TYPE ENUM1 IS (A,B,C);
     FOR ENUM1 USE (1,2,2);                           -- ERROR:

     TYPE ENUM2 IS (D,E);
     FOR ENUM2 USE (3,2);                             -- ERROR:

     TYPE ENUM3 IS (R,S);
     FOR ENUM3 USE (S=>0, R=>1);                      -- ERROR:
BEGIN
     NULL;
END BD3013A;
