-- BD3002A.ADA

-- OBJECTIVE:
--     CHECK THAT TWO ENUMERATION REPRESENTATION CLAUSES CANNOT BE GIVEN
--     FOR THE SAME TYPE.

-- HISTORY:
--     JKC 04/12/88  CREATED ORIGINAL TEST.

PROCEDURE BD3002A IS

     TYPE BASIC_E IS (RED, YELLOW, BLUE, GREEN, ORANGE);

     FOR BASIC_E USE (RED=>1, YELLOW=>2, BLUE=>3, GREEN=>4, ORANGE=>5);
     FOR BASIC_E USE (1,2,3,4,5);                   -- ERROR: DUPLICATE.

     TYPE ENUM IS (A,B,C);

     FOR ENUM USE (11,12,13);
     FOR ENUM USE (0,1,2);                          -- ERROR: DUPLICATE.

BEGIN
     NULL;
END BD3002A;
