-- BD3003B.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION REPRESENTATION SPECIFICATION
--     CANNOT BE GIVEN IN A DECLARATIVE PART AFTER THE OCCURRENCE
--     OF A BODY.

-- HISTORY:
--     JKC 04/12/88  CREATED ORIGINAL TEST.

PROCEDURE BD3003B IS

BEGIN
     DECLARE
          TYPE ENUM IS (A,B,C,D,E);
          FUNCTION F RETURN INTEGER IS
          BEGIN
               RETURN 5;
          END F;

          FOR ENUM USE (0,1,2,3,4);                       -- ERROR:

     BEGIN
          NULL;
     END;
END BD3003B;
