-- BD4011A.ADA

-- OBJECTIVE:
--     CHECK THAT A 'RANGE ATTRIBUTE CANNOT BE USED IN A COMPONENT
--     CLAUSE.

-- HISTORY:
--     BCB 04/11/88  CREATED ORIGINAL TEST.

PROCEDURE BD4011A IS

     INTSIZE : CONSTANT := INTEGER'SIZE-1;

     TYPE I IS ARRAY(0 .. INTSIZE) OF INTEGER;

     SUBTYPE T IS INTEGER RANGE 0 .. INTSIZE;

     TYPE REC IS RECORD
          INT : INTEGER;
     END RECORD;

     TYPE REC2 IS RECORD
          INT2 : INTEGER;
     END RECORD;

     FOR REC USE RECORD
          INT AT 0 RANGE I'RANGE;          -- ERROR: 'RANGE ATTRIBUTE.
     END RECORD;

     FOR REC2 USE RECORD
          INT2 AT 0 RANGE T'RANGE;         -- ERROR: 'RANGE ATTRIBUTE.
     END RECORD;

BEGIN
     NULL;
END BD4011A;
