-- BD4008B.ADA

-- OBJECTIVE:
--     CHECK THAT NO COMPONENT CLAUSE IS ALLOWED FOR A COMPONENT
--     HAVING A RECORD OR PRIVATE TYPE WITH DISCRIMINANTS, WHEN:

--     - THE DISCRIMINANT CONSTRAINT CONTAINS A NON_STATIC EXPRESSION;
--     - THE DISCRIMINANT CONSTRAINT ONLY HAS STATIC EXPRESSIONS, BUT
--       A DISCRIMINANT SUBTYPE IS NON-STATIC;
--     - THE DISCRIMINANT CONSTRAINT IS STATIC, BUT A SUBCOMPONENT HAS
--       A NON-STATIC CONSTRAINT;
--     - THE COMPONENT IS UNCONSTRAINED, BUT THERE IS A NON-STATIC
--       DISCRIMINANT SUBTYPE.

-- HISTORY:
--     DHH 08/23/88 CREATED ORIGINAL TEST.

PROCEDURE BD4008B IS

     P : INTEGER := 1;
     Q : INTEGER := 2;

     SUBTYPE NONSTATIC IS INTEGER RANGE P .. Q;

     DISCRIM : INTEGER := 1;

     TYPE ARR IS ARRAY(INTEGER RANGE <>) OF BOOLEAN;

     TYPE REC(PARAM : INTEGER) IS
          RECORD
               NULL;
          END RECORD;
---------------------
     TYPE A(PARAM : INTEGER) IS
          RECORD
               COMPONENT : REC(PARAM);      -- NON-STATIC EXPRESSION.
          END RECORD;
---------------------

     TYPE B_MAJOR(PARAM : NONSTATIC) IS
          RECORD
               NULL;
          END RECORD;

     TYPE B(B_PARAM : INTEGER) IS
          RECORD
               COMPONENT : B_MAJOR(1);      -- NON-STATIC SUBTYPE.
          END RECORD;
---------------------

     TYPE C_MAJOR(PARAM : INTEGER) IS
          RECORD
               COMPONENT_2 : ARR(PARAM .. 5);
          END RECORD;

     TYPE C(C_PARAM : INTEGER) IS
          RECORD
               COMPONENT : C_MAJOR(1);      -- NON-STATIC SUBCOMPONENT.
          END RECORD;
---------------------

     TYPE D_MAJOR(PARAM : NONSTATIC := 1) IS
          RECORD
               NULL;
          END RECORD;

     TYPE D IS
          RECORD
               COMPONENT : D_MAJOR;         -- NON-STATIC SUBTYPE.
          END RECORD;

---------------------
     FOR A USE
          RECORD AT MOD 2;
               COMPONENT AT 0 RANGE 0 .. INTEGER'SIZE - 1;    -- ERROR:
          END RECORD;

     FOR B USE
          RECORD AT MOD 2;
               COMPONENT AT 0 RANGE 0 .. INTEGER'SIZE - 1;    -- ERROR:
          END RECORD;

     FOR C USE
          RECORD AT MOD 2;
               COMPONENT AT 0 RANGE 0 .. INTEGER'SIZE - 1;    -- ERROR:
          END RECORD;

     FOR D USE
          RECORD AT MOD 2;
               COMPONENT AT 0 RANGE 0 .. INTEGER'SIZE - 1;    -- ERROR:
          END RECORD;

BEGIN
     NULL;
END BD4008B;
