
-- BD4007A.ADA

-- OBJECTIVE:
--     CHECK THAT TWO COMPONENT CLAUSES, EVEN IF IDENTICAL, CANNOT BE
--     GIVEN FOR THE SAME COMPONENT.  ALSO, CHECK THE CASE IN WHICH
--     THE COMPONENT IS NONEXISTENT.

-- HISTORY:
--     BCB 04/11/88  CREATED ORIGINAL TEST.
--     DHH 03/28/89  ADDED CHECK FOR COMPONENT WHICH DOES NOT EXIST IN
--                   ANY VARIANT

PROCEDURE BD4007A IS

     TYPE REC1 IS RECORD
          INT1 : INTEGER;
     END RECORD;

     TYPE REC2 IS RECORD
          INT2 : INTEGER;
     END RECORD;

     TYPE REC3 (D : POSITIVE) IS RECORD
          CASE D IS
               WHEN 1 .. 10 => CHAR3 : CHARACTER;
               WHEN OTHERS => BOOL3 : BOOLEAN;
          END CASE;
     END RECORD;

     TYPE REC4 IS NEW REC3(4);
     TYPE REC5 IS NEW REC3(5);

     FOR REC1 USE RECORD
          INT1 AT 0 RANGE 0 .. INTEGER'SIZE-1;
          INT1 AT 0 RANGE 0 .. INTEGER'SIZE-1;
                                   -- ERROR: SECOND COMPONENT CLAUSE.
     END RECORD;

     FOR REC2 USE RECORD
          INT2 AT 0 RANGE 0 .. INTEGER'SIZE-1;
          INT2 AT 8 RANGE INTEGER'SIZE .. 2*INTEGER'SIZE-1;
                                   -- ERROR: SECOND COMPONENT CLAUSE.
     END RECORD;

     FOR REC4 USE RECORD
          CHAR3 AT 0 RANGE 0 .. CHARACTER'SIZE-1;
          BOOL3 AT 0 RANGE 0 .. BOOLEAN'SIZE-1;
          BOOL3 AT 0
              RANGE CHARACTER'SIZE .. CHARACTER'SIZE+BOOLEAN'SIZE-1;
                                   -- ERROR: SECOND COMPONENT CLAUSE FOR
                                   --        NONEXISTENT COMPONENT.
     END RECORD;

     FOR REC5 USE RECORD
          CHAR3 AT 0 RANGE 0 .. CHARACTER'SIZE-1;
          BOOL4 AT 0
              RANGE CHARACTER'SIZE .. CHARACTER'SIZE+BOOLEAN'SIZE-1;
                                   -- ERROR: COMPONENT CLAUSE FOR
                                   --        NONEXISTENT COMPONENT.
     END RECORD;

BEGIN
     NULL;
END BD4007A;
