-- BD4009A.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD REPRESENTATION CLAUSE CANNOT SPECIFY
--     OVERLAPPING STORAGE FOR TWO DIFFERENT COMPONENTS IF THEY DO NOT
--     BELONG TO DIFFERENT VARIANTS.

-- HISTORY:
--     BCB 04/11/88  CREATED ORIGINAL TEST.

PROCEDURE BD4009A IS

     TYPE INT IS RANGE 0 .. 1;

     TYPE REC(DISC : INT) IS RECORD
          CASE DISC IS
               WHEN 0 =>
                    I1 : INTEGER;
                    C1 : CHARACTER;
               WHEN 1 =>
                    I2 : INTEGER;
          END CASE;
     END RECORD;

     FOR REC USE RECORD
          I1 AT 0 RANGE 0 .. INTEGER'SIZE-1;
          C1 AT 0 RANGE 0 .. CHARACTER'SIZE-1;
                                          -- ERROR: OVERLAPPING STORAGE.
          I2 AT 0 RANGE 0 .. INTEGER'SIZE-1;       -- OK.
     END RECORD;

BEGIN
     NULL;
END BD4009A;
