-- BD4001A.ADA

-- OBJECTIVE:
--     CHECK THAT A RECORD REPRESENTATION CLAUSE CANNOT BE GIVEN FOR
--     AN EXPANDED NAME THAT DENOTES A RECORD TYPE.  USE ONE INTEGER
--     COMPONENT; SPECIFY AT 8 RANGE 0 .. INTEGER'SIZE-1.

-- HISTORY:
--     BCB 04/12/88  CREATED ORIGINAL TEST.

PROCEDURE BD4001A IS

     TYPE PREC IS RECORD
          INT : INTEGER;
     END RECORD;

     FOR BD4001A.PREC USE RECORD
          INT AT 8 RANGE 0 .. INTEGER'SIZE-1;
                                         -- ERROR: RECORD REPRESENTATION
                                         -- CLAUSE FOR AN EXPANDED NAME.
     END RECORD;

BEGIN
     NULL;
END BD4001A;
