-- BD4008A.ADA

-- OBJECTIVE:
--     CHECK THAT A COMPONENT CLAUSE IS NOT ALLOWED FOR A COMPONENT WITH
--     A NONSTATIC CONSTRAINT OR A SUBCOMPONENT WITH A NONSTATIC
--     CONSTRAINT.  INCLUDE CHECKS FOR A RANGE CONSTRAINT WITH A
--     NONSTATIC EXPRESSION, A STATIC RANGE CONSTRAINT IMPOSED ON A
--     NONSTATIC SCALAR SUBTYPE, A NONSTATIC INDEX CONSTRAINT, A STATIC
--     INDEX CONSTRAINT BUT A NONSTATIC INDEX SUBTYPE.

-- HISTORY:
--     BCB 07/07/88  CREATED ORIGINAL TEST.

WITH SYSTEM;

PROCEDURE BD4008A IS

     UNITS_PER_INTEGER : CONSTANT :=
                      (INTEGER'SIZE + SYSTEM.STORAGE_UNIT - 1) /
                      SYSTEM.STORAGE_UNIT;

     TYPE ENUM IS (ONE, TWO, THREE, FOUR);

     TYPE FLT IS DIGITS 5 RANGE -1.0 .. 1.0;

     TYPE FIX IS DELTA 0.5 RANGE -1.0 .. 1.0;

     TYPE ARR IS ARRAY(INTEGER RANGE <>) OF INTEGER;

     VAR1 : ENUM := ONE;
     VAR2 : INTEGER := 0;
     VAR3 : FLT := 0.0;
     VAR4 : FIX := 0.0;
     VAR5 : INTEGER := 5;

     SUBTYPE SUBENUM IS ENUM RANGE VAR1 .. THREE;

     TYPE ARR_SUBENUM IS ARRAY(SUBENUM RANGE <>) OF INTEGER;

     TYPE RR1(D : INTEGER) IS RECORD
          NULL;
     END RECORD;

     TYPE RR2 IS RECORD
          COMP : RR1(VAR5);
     END RECORD;

     TYPE ARR_REC IS ARRAY(INTEGER RANGE <>) OF RR2;

     TYPE REC1 IS RECORD
          ENUMVAR : ENUM RANGE VAR1 .. THREE;
     END RECORD;

     TYPE REC2 IS RECORD
          INTVAR : INTEGER RANGE VAR2 .. 100;
     END RECORD;

     TYPE REC3 IS RECORD
          FLTVAR : FLT RANGE VAR3 .. 1.0;
     END RECORD;

     TYPE REC4 IS RECORD
          FIXVAR : FIX RANGE VAR4 .. 1.0;
     END RECORD;

     TYPE REC5 IS RECORD
          REC5_VAR : SUBENUM RANGE TWO .. THREE;
     END RECORD;

     TYPE REC6 (DISC : INTEGER := 5) IS RECORD
          ARR_VAR1 : ARR(1..VAR5);
     END RECORD;

     TYPE REC7 (DISC : INTEGER := 5) IS RECORD
          ARR_VAR2 : ARR(1..DISC);
     END RECORD;

     TYPE REC8 (DISC : INTEGER := 5) IS RECORD
          ARR_VAR3 : ARR_SUBENUM(ONE..THREE);
     END RECORD;

     TYPE SUBREC1 IS RECORD
          SUBREC1_VAR : REC1;
     END RECORD;

     TYPE SUBREC2 IS RECORD
          SUBREC2_VAR : REC2;
     END RECORD;

     TYPE SUBREC3 IS RECORD
          SUBREC3_VAR : REC3;
     END RECORD;

     TYPE SUBREC4 IS RECORD
          SUBREC4_VAR : REC4;
     END RECORD;

     TYPE SUBREC5 IS RECORD
          SUBREC5_VAR : REC5;
     END RECORD;

     TYPE SUBREC6 IS RECORD
          SUBREC6_VAR : REC6;
     END RECORD;

     TYPE SUBREC7 IS RECORD
          SUBREC7_VAR : REC7;
     END RECORD;

     FOR REC1 USE RECORD AT MOD 8;
          ENUMVAR AT UNITS_PER_INTEGER
              RANGE 0 .. ENUM'SIZE-1;     -- ERROR: COMPONENT.
     END RECORD;

     FOR REC2 USE RECORD AT MOD 8;
          INTVAR AT UNITS_PER_INTEGER
              RANGE 0 .. INTEGER'SIZE-1;  -- ERROR: COMPONENT.
     END RECORD;

     FOR REC3 USE RECORD AT MOD 16;
          FLTVAR AT UNITS_PER_INTEGER
              RANGE 0 .. FLT'SIZE-1;      -- ERROR: COMPONENT.
     END RECORD;

     FOR REC4 USE RECORD AT MOD 8;
          FIXVAR AT UNITS_PER_INTEGER
              RANGE 0 .. FIX'SIZE-1;      -- ERROR: COMPONENT.
     END RECORD;

     FOR REC5 USE RECORD AT MOD 8;
          REC5_VAR AT UNITS_PER_INTEGER
              RANGE 0 .. ENUM'SIZE-1;     -- ERROR: COMPONENT.
     END RECORD;

     FOR REC6 USE RECORD AT MOD 16;
          ARR_VAR1 AT UNITS_PER_INTEGER
              RANGE 0 .. (5*INTEGER'SIZE)-1; -- ERROR: COMPONENT.
     END RECORD;

     FOR REC7 USE RECORD AT MOD 8;
          ARR_VAR2 AT UNITS_PER_INTEGER
              RANGE 0 .. (5*INTEGER'SIZE)-1; -- ERROR: COMPONENT.
     END RECORD;

     FOR REC8 USE RECORD AT MOD 8;
          ARR_VAR3 AT UNITS_PER_INTEGER
              RANGE 0 .. (3*ENUM'SIZE)-1; -- ERROR: COMPONENT.
     END RECORD;

     FOR SUBREC1 USE RECORD AT MOD 16;
          SUBREC1_VAR AT UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. ENUM'SIZE-1;
     END RECORD;

     FOR SUBREC2 USE RECORD AT MOD 8;
          SUBREC2_VAR AT UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. INTEGER'SIZE-1;
     END RECORD;

     FOR SUBREC3 USE RECORD AT MOD 8;
          SUBREC3_VAR AT UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. FLT'SIZE-1;
     END RECORD;

     FOR SUBREC4 USE RECORD AT MOD 16;
          SUBREC4_VAR AT UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. FIX'SIZE-1;
     END RECORD;

     FOR SUBREC5 USE RECORD AT MOD 32;
          SUBREC5_VAR AT 2*UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. (2*INTEGER'SIZE)-1;
     END RECORD;

     FOR SUBREC6 USE RECORD AT MOD 8;
          SUBREC6_VAR AT UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. (5*INTEGER'SIZE)-1;
     END RECORD;

     FOR SUBREC7 USE RECORD AT MOD 8;
          SUBREC7_VAR AT UNITS_PER_INTEGER  -- ERROR: SUBCOMPONENT.
              RANGE 0 .. (5*INTEGER'SIZE)-1;
     END RECORD;

BEGIN
     NULL;
END BD4008A;
