-- BD4002A.ADA

-- OBJECTIVE:
--     CHECK THAT TWO RECORD REPRESENTATION CLAUSES, EVEN IF IDENTICAL,
--     CANNOT BE GIVEN FOR THE SAME TYPE.

-- HISTORY:
--     BCB 04/11/88  CREATED ORIGINAL TEST.

PROCEDURE BD4002A IS

     TYPE REC1 IS RECORD
          INT1 : INTEGER;
     END RECORD;

     TYPE REC2 IS RECORD
          INT2 : INTEGER;
     END RECORD;

     FOR REC1 USE RECORD
          INT1 AT 0 RANGE 0 .. INTEGER'SIZE-1;
     END RECORD;

     FOR REC1 USE RECORD                     -- ERROR: SECOND RECORD
                                             -- REPRESENTATION CLAUSE.
          INT1 AT 0 RANGE 0 .. INTEGER'SIZE-1;
     END RECORD;

     FOR REC2 USE RECORD
          INT2 AT 0 RANGE 0 .. INTEGER'SIZE-1;
     END RECORD;

     FOR REC2 USE RECORD                     -- ERROR: SECOND RECORD
                                             -- REPRESENTATION CLAUSE.
          INT2 AT 1 RANGE 0 .. INTEGER'SIZE-1;
     END RECORD;

BEGIN
     NULL;
END BD4002A;
