-- BD5005A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CANNOT BE GIVEN, WITHIN THE
--     PROCEDURE P, FOR AN EXPANDED NAME OF THE FORM P.OBJ, WHERE
--     OBJ IS AN OBJECT DECLARED IMMEDIATELY WITHIN P.

-- HISTORY:
--     JKC 04/18/88  CREATED ORIGINAL TEST.

WITH SPPRT13;
WITH SYSTEM; USE SYSTEM;
PROCEDURE BD5005A IS

     PROCEDURE P (X : INTEGER) IS
          OBJ : INTEGER := 100;
          FOR P.OBJ USE AT SPPRT13.VARIABLE_ADDRESS;   -- ERROR:
     BEGIN
          NULL;
     END P;

BEGIN
     NULL;
END BD5005A;
