-- BD5001A.ADA

-- OBJECTIVE:
--     CHECK THAT THE EXPRESSION IN AN ADDRESS CLAUSE MUST HAVE THE
--     TYPE SYSTEM.ADDRESS.

-- HISTORY:
--     DJ  07/27/87  CREATED ORIGINAL TEST.
--     DWC 09/25/87  REFORMATTED TEST.

WITH SYSTEM;
PROCEDURE BD5001A IS

     SUBTYPE BAD_ADDRESS_TYPE IS INTEGER;
     BAD_ADDRESS1 : BAD_ADDRESS_TYPE := 0;
     BAD_ADDRESS2 : POSITIVE := 1;
     BAD_ADDRESS3 : INTEGER := 0;
     BAD_ADDRESS4 : NATURAL := 0;
     BAD_ADDRESS5 : FLOAT := 0.0;

     OBJECT1 : INTEGER;
     FOR OBJECT1 USE AT BAD_ADDRESS1;  -- ERROR:  ADDRESS MUST BE
                                       -- OF SYSTEM.ADDRESS.

     OBJECT2 : INTEGER;
     FOR OBJECT2 USE AT BAD_ADDRESS2;  -- ERROR:  ADDRESS MUST BE
                                       -- OF SYSTEM.ADDRESS.

     OBJECT3 : INTEGER;
     FOR OBJECT3 USE AT BAD_ADDRESS3;  -- ERROR:  ADDRESS MUST BE
                                       -- OF SYSTEM.ADDRESS.

     OBJECT4 : INTEGER;
     FOR OBJECT4 USE AT BAD_ADDRESS4;  -- ERROR:  ADDRESS MUST BE
                                       -- OF SYSTEM.ADDRESS.

     OBJECT5 : INTEGER;
     FOR OBJECT5 USE AT BAD_ADDRESS5;  -- ERROR:  ADDRESS MUST BE
                                       -- OF SYSTEM.ADDRESS.

     BEGIN
          NULL;
END BD5001A;
