-- BD5005D.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CANNOT BE GIVEN, IMMEDIATELY WITHIN
--     THE SPECIFICATION OF TASK T, FOR AN EXPANDED NAME OF THE FORM
--     T.E, WHERE E IS AN ENTRY OF T.

-- HISTORY:
--     JET 08/23/88  CREATED ORIGINAL TEST.

WITH SYSTEM, SPPRT13;
PROCEDURE BD5005D IS

     TASK T IS
          ENTRY E;
          FOR T.E USE AT SPPRT13.ENTRY_ADDRESS;  -- ERROR: NOT ALLOWED.
     END T;

     TASK BODY T IS
     BEGIN
          ACCEPT E DO
               NULL;
          END E;
     END T;

BEGIN
     NULL;
END BD5005D;
