-- BD5002A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE IS ILLEGAL IF A WITH CLAUSE
--     NAMING THE PREDEFINED PACKAGE SYSTEM DOES NOT APPLY TO THE UNIT
--     CONTAINING THE ADDRESS CLAUSE.
--          A)  FOR OBJECTS.

-- HISTORY:
--     DJ  08/03/87  CREATED ORIGINAL TEST.
--     DWC 09/25/87  REFORMATTED TEST.

WITH SPPRT13; USE SPPRT13;
PROCEDURE BD5002A IS

    TEST_OBJECT : INTEGER;
    FOR TEST_OBJECT USE AT VARIABLE_ADDRESS;     -- ERROR:  PACKAGE
                                                 -- SYSTEM NOT VISIBLE.
BEGIN
     NULL;
END BD5002A;
