-- BD5002F.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE IS ILLEGAL IF A WITH CLAUSE
--     NAMING THE PREDEFINED PACKAGE SYSTEM DOES NOT APPLY TO THE UNIT
--     CONTAINING THE ADDRESS CLAUSE.
--          F)  FOR TASK ENTRIES.

-- HISTORY:
--     DJ  08/11/87  CREATED ORIGINAL TEST.
--     DWC 09/25/87  REFORMATTED TEST.

WITH SPPRT13; USE SPPRT13;
PROCEDURE BD5002F IS

     TASK TASK1 IS ENTRY ENTRY1;
          FOR ENTRY1 USE AT ENTRY_ADDRESS;    -- ERROR:  PACKAGE
                                              -- SYSTEM IS NOT VISIBLE.
     END TASK1;

     TASK BODY TASK1 IS
     BEGIN
          ACCEPT ENTRY1;
     END TASK1;

BEGIN -- BD5002F

     NULL;

END BD5002F;
