-- BD5102A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CANNOT BE SPECIFIED FOR AN
--     ENTRY FAMILY.

-- HISTORY:
--     DJ  09/08/87  CREATED ORIGINAL TEST.
--     DWC 09/29/87  REFORMATTED TEST AND DELETED PACKAGE BODY.

WITH SYSTEM;
WITH SPPRT13; USE SPPRT13;

PACKAGE BD5102A IS

     TYPE INTERRUPT_LEVEL IS RANGE 0 .. 2;

     TASK TASK1 IS
          ENTRY FAMILY_ENTRY1 (INTERRUPT_LEVEL);
          FOR FAMILY_ENTRY1 USE AT ENTRY_ADDRESS;      -- ERROR:  CANNOT
                                                       -- GIVE ADDRESS
                                                       -- CLAUSE FOR
                                                       -- FAMILY ENTRY.
     END TASK1;

END BD5102A;
