-- BD5102B.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CANNOT BE SPECIFIED FOR AN ENTRY
--     FAMILY OF A TASK TYPE.

-- HISTORY:
--     JET 08/24/88  CREATED ORIGINAL TEST.

WITH SYSTEM, SPPRT13;
PROCEDURE BD5102B IS

     TASK TYPE T IS
          ENTRY E(1..5);
          FOR E USE AT SPPRT13.ENTRY_ADDRESS;    -- ERROR: ENTRY FAMILY.
     END T;

     TASK BODY T IS
     BEGIN
          ACCEPT E(1) DO
               NULL;
          END E;
     END T;

BEGIN
     NULL;
END BD5102B;
