-- BD5104A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE FOR AN ENTRY CANNOT BE GIVEN IN THE
--     DECLARATIVE PART OF THE TASK BODY.

-- HISTORY:
--     DJ  09/08/87  CREATED ORIGINAL TEST.
--     DWC 09/29/87  REFORMATTED TEST.

WITH SYSTEM;
WITH SPPRT13; USE SPPRT13;

PACKAGE BD5104A IS

     TASK TASK1 IS
          ENTRY ENTRY1;
     END TASK1;

END BD5104A;

PACKAGE BODY BD5104A IS

     TASK BODY TASK1 IS
          FOR ENTRY1 USE AT ENTRY_ADDRESS;    -- ERROR:  ADDRESS CLAUSE
     BEGIN                                    -- CANNOT BE GIVEN IN
          ACCEPT ENTRY1;                      -- TASK BODY.
     END TASK1;

END BD5104A;
