-- BD5103A.ADA

-- OBJECTIVE:
--     CHECK THAT THE NAME IN AN ADDRESS CLAUSE FOR AN ENTRY CANNOT
--     BE AN EXPANDED NAME.

-- HISTORY:
--     DJ  09/08/87  CREATED ORIGINAL TEST.
--     DWC 09/29/87  REFORMATTED TEST.

WITH SYSTEM;
WITH SPPRT13; USE SPPRT13;

PACKAGE BD5103A IS

     TASK TASK1 IS
          ENTRY ENTRY1;
     END TASK1;

     TASK TASK2 IS
          ENTRY ENTRY1;
     END TASK2;

     FOR TASK1.ENTRY1 USE AT ENTRY_ADDRESS;    -- ERROR:  EXPANDED NAME.

END BD5103A;
