-- BD7001A.ADA

-- OBJECTIVE:
--     CHECK THAT THE PACKAGE SYSTEM IS NOT DECLARED WITHIN STANDARD.

-- HISTORY:
--     JET 08/24/88  CREATED ORIGINAL TEST.

PROCEDURE BD7001A IS

     A1 : ADDRESS;                   -- ERROR: NO SUCH TYPE IN STANDARD.
     A2 : SYSTEM.ADDRESS;            -- ERROR: NO SUCH TYPE IN STANDARD.
     A3 : STANDARD.SYSTEM.ADDRESS;   -- ERROR: NO SUCH TYPE IN STANDARD.

BEGIN
     NULL;
END BD7001A;
