-- BD7101H.ADA

-- OBJECTIVE:
--     CHECK THAT NO INTEGER TYPE CAN BE DECLARED WITH VALUES LESS
--     THAN MIN_INT OR WITH VALUES GREATER THAN MAX_INT.  (USE
--     MIN_INT - 1 .. MIN_INT + 1 AND MAX_INT - 1 .. MAX_INT + 1.)

-- HISTORY:
--     LDC  06/14/88 CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;

PROCEDURE BD7101H IS

     TYPE MIN_MAX1 IS RANGE MIN_INT .. MAX_INT;        -- OK.
     TYPE MIN_MAX2 IS RANGE MIN_INT +1 .. MAX_INT -1;  -- OK.

     TYPE MAX IS RANGE MAX_INT -1 .. MAX_INT +1;       -- ERROR:
     TYPE MIN IS RANGE MIN_INT -1 .. MIN_INT +1;       -- ERROR:

BEGIN
     NULL;
END BD7101H;
