-- BD7205A.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREFIX OF THE 'STORAGE_SIZE ATTRIBUTE CANNOT BE
--     A SUBPROGRAM.

-- HISTORY:
--     JET 08/25/88  CREATED ORIGINAL TEST.

PROCEDURE BD7205A IS

     I : INTEGER;

     PROCEDURE PROC IS
     BEGIN
          NULL;
     END PROC;

     FUNCTION FUNC RETURN INTEGER IS
     BEGIN
          RETURN 0;
     END FUNC;

BEGIN

     I := PROC'STORAGE_SIZE;               -- ERROR: PROCEDURE.
     I := FUNC'STORAGE_SIZE;               -- ERROR: FUNCTION.

END BD7205A;
