-- BD7201C.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREFIX OF THE 'ADDRESS ATTRIBUTE CANNOT DENOTE A
--     NAMED NUMBER, EXCEPTION, TYPE OR SUBTYPE WHICH IS NOT A TASK, AND
--     AN ATTRIBUTE WHICH IS NOT A FUNCTION.

-- HISTORY:
--     JET 08/24/88  CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
PROCEDURE BD7201C IS

     A : ADDRESS;

     CONST : CONSTANT := 0;
     TYPE T IS RANGE 0..10;
     SUBTYPE ST IS T;

BEGIN
     A := CONST'ADDRESS;                    -- ERROR: NAMED NUMBER.
     A := CONSTRAINT_ERROR'ADDRESS;         -- ERROR: EXCEPTION.
     A := T'ADDRESS;                        -- ERROR: TYPE.
     A := ST'ADDRESS;                       -- ERROR: SUBTYPE.
     A := INTEGER'FIRST'ADDRESS;            -- ERROR: ATTRIBUTE.
END BD7201C;
