-- BD7204A.ADA

-- OBJECTIVE:
--     THE PREFIX OF THE 'POSITION, 'LAST_BIT, AND 'FIRST_BIT ATTRIBUTES
--     CANNOT DENOTE AN ARRAY COMPONENT AND CANNOT BE A NAME DECLARED BY
--     A RENAMING DECLARATION.

-- HISTORY:
--     JET 08/24/88  CREATED ORIGINAL TEST.

PROCEDURE BD7204A IS

     TYPE ARR IS ARRAY (1..10) OF INTEGER;
     A : ARR := (OTHERS => 0);

     TYPE REC_TYPE IS RECORD
          I : INTEGER;
     END RECORD;
     REC : REC_TYPE := (I => 0);

     R : INTEGER RENAMES REC.I;

     I : INTEGER;

BEGIN
     I := A(1)'POSITION;               -- ERROR: ARRAY COMPONENT.
     I := A(1)'FIRST_BIT;              -- ERROR: ARRAY COMPONENT.
     I := A(10)'LAST_BIT;              -- ERROR: ARRAY COMPONENT.

     I := R'POSITION;                  -- ERROR: RENAMED OBJECT.
     I := R'FIRST_BIT;                 -- ERROR: RENAMED OBJECT.
     I := R'LAST_BIT;                  -- ERROR: RENAMED OBJECT.
END BD7204A;
