-- BD7301A.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREFIX OF THE ATTRIBUTES 'MACHINE_ROUNDS AND
--     'MACHINE_OVERFLOWS CANNOT BE AN INTEGER TYPE.

-- HISTORY:
--     DHH 08/31/88  CREATED ORIGINAL TEST.

PROCEDURE BD7301A IS

     SUBTYPE A IS INTEGER;

     TYPE B IS NEW INTEGER;

     BOOL0 : BOOLEAN := A'MACHINE_ROUNDS;              -- ERROR:
     BOOL1 : BOOLEAN := B'MACHINE_ROUNDS;              -- ERROR:

     BOOL2 : BOOLEAN := A'MACHINE_OVERFLOWS;           -- ERROR:
     BOOL3 : BOOLEAN := B'MACHINE_OVERFLOWS;           -- ERROR:

BEGIN
     NULL;
END BD7301A;
