-- BE2112B.ADA

-- CHECK THAT THE INSTANTIATION OF SEQUENTIAL_IO IS REQUIRED FOR
-- THE EMPLOYMENT OF THE FOLLOWING SUBPROGRAMS:
--
--   CREATE            CLOSE             OPEN
--   RESET             MODE              NAME
--   FORM              IS_OPEN           END_OF_FILE
--   DELETE.

-- ABW  8/13/82
-- JBG 8/30/83

WITH SEQUENTIAL_IO ;

PROCEDURE BE2112B IS

     PACKAGE PKG IS
          TYPE FILE_TYPE IS LIMITED PRIVATE ;
     PRIVATE
          TYPE FILE_TYPE IS NEW INTEGER ;
     END PKG ;
     USE PKG ;
     FILE : FILE_TYPE ;
     TYPE FILE_MODE IS (IN_FILE,OUT_FILE,INOUT_FILE) ;

BEGIN

     SEQUENTIAL_IO.CREATE (FILE, OUT_FILE) ;       -- ERROR: CREATE
     SEQUENTIAL_IO.CLOSE (FILE) ;                  -- ERROR: CLOSE
     SEQUENTIAL_IO.OPEN (FILE) ;                   -- ERROR: OPEN
     SEQUENTIAL_IO.RESET (FILE) ;                  -- ERROR: RESET

     DECLARE

AA : SEQUENTIAL_IO.FILE_MODE := SEQUENTIAL_IO.MODE (FILE) ;  -- ERROR:
                                                   -- FILE_MODE, MODE
          BB : CONSTANT STRING :=
                   SEQUENTIAL_IO.NAME (FILE) ;     -- ERROR: NAME
          CC : CONSTANT STRING :=
                   SEQUENTIAL_IO.FORM (FILE) ;     -- ERROR: FORM
          DD : BOOLEAN :=
                SEQUENTIAL_IO.IS_OPEN (FILE) ;     -- ERROR: IS_OPEN
          EE : BOOLEAN :=
            SEQUENTIAL_IO.END_OF_FILE (FILE) ;     -- ERROR: END_OF_FILE

     BEGIN

          SEQUENTIAL_IO.DELETE (FILE) ;            -- ERROR: DELETE

     END ;

END BE2112B ;
