-- BE2116A.ADA

-- OBJECTIVE:
--     CHECK THAT THE MODE INOUT_FILE IS NOT ALLOWED FOR SEQUENTIAL_IO.

-- HISTORY:
--     JLH 07/07/88  CREATED ORIGINAL TEST.

WITH SEQUENTIAL_IO;

PROCEDURE BE2116A IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO (INTEGER);
     USE SEQ_IO;

     FILE : FILE_TYPE;

BEGIN

     CREATE (FILE, INOUT_FILE);          -- ERROR: MODE INOUT_FILE.

     NULL;

     OPEN (FILE, INOUT_FILE);            -- ERROR: MODE INOUT_FILE.

     NULL;

     RESET (FILE, INOUT_FILE);           -- ERROR: MODE INOUT_FILE.

END BE2116A;
