-- BE2210A.ADA

-- OBJECTIVE:
--     CHECK THAT FORTRAN-LIKE READ AND WRITE STATEMENTS ARE ILLEGAL FOR
--     SEQUENTIAL_IO.

-- HISTORY:
--     JLH 07/14/88  CREATED ORIGINAL TEST.

WITH SEQUENTIAL_IO;

PROCEDURE BE2210A IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO (INTEGER);
     USE SEQ_IO;

     FILE : FILE_TYPE;
     ITEM : INTEGER;

BEGIN

     READ (UNIT = 'FILE', FMT = 10) ITEM                 -- ERROR: READ.

     NULL;

     READ (UNIT = 'FILE', FMT = 20, IOSTAT = IERR) ITEM  -- ERROR: READ.

     NULL;

     READ ('FILE', 20, IERR) ITEM                        -- ERROR: READ.

     NULL;

     WRITE (UNIT = 'FILE', 1000) ITEM                   -- ERROR: WRITE.

     NULL;

     WRITE ('FILE', FMT = 30, END = 99) ITEM            -- ERROR: WRITE.

     NULL;

     WRITE ('FILE', 100, IERR) ITEM                     -- ERROR: WRITE.

     NULL;

END BE2210A;
