-- BE2208A.ADA

-- CHECK THAT SET_INDEX, INDEX, AND SIZE ARE NOT PERMITTED FOR
-- SEQUENTIAL FILES.

-- DLD 8/17/82

WITH SEQUENTIAL_IO;
WITH DIRECT_IO;

PROCEDURE BE2208A IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO(INTEGER);
          USE SEQ_IO;
     SEQ_FILE : FILE_TYPE;
     PACKAGE DIR_IO IS NEW DIRECT_IO (INTEGER);
          USE DIR_IO;
     I : INTEGER;

BEGIN

     SET_INDEX(SEQ_FILE, 3);  -- ERROR: SET_INDEX FOR SEQ FILES
     I := INDEX(SEQ_FILE);    -- ERROR: INDEX FOR SEQ FILES
     I := SIZE(SEQ_FILE);     -- ERROR: SIZE FOR SEQ FILES

END BE2208A;
