-- BE2413A.ADA

-- OBJECTIVE:
--     CHECK THAT FORTRAN-LIKE READ AND WRITE STATEMENTS ARE ILLEGAL FOR
--     DIRECT_IO.

-- HISTORY:
--     JLH 07/14/88  CREATED ORIGINAL TEST.

WITH DIRECT_IO;

PROCEDURE BE2413A IS

     PACKAGE DIR_IO IS NEW DIRECT_IO (INTEGER);
     USE DIR_IO;

     FILE : FILE_TYPE;
     ITEM : INTEGER;

BEGIN

     READ (UNIT = 'FILE', FMT = 10, REC = 2) ITEM        -- ERROR: READ.

     NULL;

     READ (UNIT = 'FILE', FMT = 20, IOSTAT = IERR) ITEM  -- ERROR: READ.

     NULL;

     READ ('FILE', 20, IERR) ITEM                        -- ERROR: READ.

     NULL;

     WRITE (UNIT = 'FILE', 1000, REC = 2) ITEM          -- ERROR: WRITE.

     NULL;

     WRITE ('FILE', FMT = 30, END = 99) ITEM            -- ERROR: WRITE.

     NULL;

     WRITE ('FILE', 100, REC = 3, IERR)                 -- ERROR: WRITE.

     NULL;

END BE2413A;
