-- BE3105A.ADA

-- CHECK THAT THE MODE INOUT_FILE IS NOT ALLOWED FOR TEXT_IO.

-- ABW  8/24/82
-- SPS 9/16/82
-- SPS 11/9/82

WITH TEXT_IO ;
USE TEXT_IO ;
PROCEDURE BE3105A IS

     FILE1 : FILE_TYPE ;

BEGIN

     CREATE (FILE1,INOUT_FILE) ;             -- ERROR: INOUT_FILE

END BE3105A ;
