-- BE3205A.ADA

-- CHECK THAT THE STANDARD INPUT AND OUTPUT FILES CANNOT BE
-- OPENED, CLOSED, RESET, OR DELETED.

-- ABW  8/25/82
-- SPS  11/9/82
-- JBG 3/17/83

WITH TEXT_IO;
USE TEXT_IO;
PROCEDURE BE3205A IS
BEGIN

     OPEN (STANDARD_INPUT, IN_FILE, "X3205A");    -- ERROR: OPEN.
     OPEN (STANDARD_OUTPUT, OUT_FILE, "X3205B");  -- ERROR: OPEN.

     RESET (STANDARD_INPUT);                      -- ERROR: RESET.
     RESET (STANDARD_OUTPUT);                     -- ERROR: RESET.

     CLOSE (STANDARD_INPUT);                      -- ERROR: CLOSE.
     CLOSE (STANDARD_OUTPUT);                     -- ERROR: CLOSE.

     DELETE (STANDARD_INPUT);                     -- ERROR: DELETE.
     DELETE (STANDARD_OUTPUT);                    -- ERROR: DELETE.

END BE3205A;
