-- BE3301C.ADA

-- OBJECTIVE:
--     CHECK THAT SET_LINE_LENGTH AND SET_PAGE_LENGTH DO NOT TAKE
--     PARAMETERS OF TYPE INTEGER.  ALSO CHECK THAT LINE_LENGTH AND
--     PAGE_LENGTH RETURN VALUES OF TYPE COUNT.

-- HISTORY:
--     JLH 08/27/87  CREATED ORIGINAL TEST.

WITH TEXT_IO; USE TEXT_IO;

PROCEDURE BE3301C IS

     TWO : CONSTANT INTEGER := 2;
     TEN : CONSTANT INTEGER := 10;
     ITEM : INTEGER;

BEGIN

     SET_LINE_LENGTH (TWO);    -- ERROR: PARAMETER OF TYPE INTEGER.

     NULL;

     SET_PAGE_LENGTH (TEN);    -- ERROR: PARAMETER OF TYPE INTEGER.

     NULL;

     ITEM := LINE_LENGTH;      -- ERROR: TYPES DO NOT MATCH.

     NULL;

     ITEM := PAGE_LENGTH;      -- ERROR: TYPES DO NOT MATCH.

END BE3301C;
