-- BE3501A.ADA

-- CHECK THAT PUT DOES NOT ACCEPT MORE THAN ONE ITEM.

-- SPS 9/30/82

WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE BE3501A IS

     FT : FILE_TYPE;

BEGIN

     PUT (FT, 'C', 'D', 'E');      -- ERROR: MULTIPLE ITEMS.
     PUT (FT, "THIS STRING IS",
              "ACTUALLY TWO");     -- ERROR: MULTIPLE ITEMS.
     PUT ('A', 'B', 'C');          -- ERROR: MULTIPLE ITEMS.
     PUT ("ANOTHERS STRING THAT",
          "ACTUALLY TWO STRINGS"); -- ERROR: MULTIPLE ITEMS.

END BE3501A;
