-- BE3606C.ADA

-- CHECK THAT PUT_LINE DOES NOT EXIST FOR CHARACTER PARAMETERS

-- JBG 12/28/82

WITH TEXT_IO; USE TEXT_IO;

PROCEDURE BE3606C IS
     FT : FILE_TYPE;
BEGIN
     CREATE (FT);
     PUT_LINE (FT, 'A');      -- ERROR: 'A'
END BE3606C;
