-- BE3902A.ADA

-- CHECK THAT ENUMERATION_IO CAN BE INSTANTIATED FOR PREDEFINED AND USER
-- DEFINED ENUMERATION TYPES.  CHECK THAT OTHER NON-DISCRETE
-- TYPES ARE NOT ACCEPTED.

-- SPS 10/7/82

WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE BE3902A IS

     TYPE WEEKDAY IS (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY);
     TYPE FLAG_COLOR IS (RED, WHITE, BLUE);
     TYPE CH IS NEW CHARACTER RANGE 'A'.. 'C';
     TYPE NB IS NEW BOOLEAN;
     TYPE INT IS NEW INTEGER;
     TYPE RC IS RECORD NULL; END RECORD;
     TYPE AC IS ACCESS CH;
     TYPE AR IS ARRAY (1.. 10) OF WEEKDAY;

     PACKAGE NE1 IS NEW ENUMERATION_IO (WEEKDAY);      -- OK.
     PACKAGE NE2 IS NEW ENUMERATION_IO (FLAG_COLOR);   -- OK.
     PACKAGE NE3 IS NEW ENUMERATION_IO (CH);           -- OK.
     PACKAGE NE4 IS NEW ENUMERATION_IO (CHARACTER);    -- OK.
     PACKAGE NE5 IS NEW ENUMERATION_IO (NB);           -- OK.
     PACKAGE NE6 IS NEW ENUMERATION_IO (BOOLEAN);      -- OK.
     PACKAGE NE7 IS NEW ENUMERATION_IO (INT);          -- OK.
     PACKAGE NE8 IS NEW ENUMERATION_IO (INTEGER);      -- OK.
     PACKAGE NE9 IS NEW ENUMERATION_IO (RC);           -- ERROR: RC.
     PACKAGE NE10 IS NEW ENUMERATION_IO (AC);          -- ERROR: AC.
     PACKAGE NE11 IS NEW ENUMERATION_IO (AR);          -- ERROR: AR.

BEGIN
     NULL;
END BE3902A;
