-- C24002A.ADA

-- CHECK THAT BOTH CAPITAL E AND LOWER CASE E MAY BE USED IN
-- INTEGER LITERALS (FOR COMPILERS THAT SUPPORT BOTH).
-- CHECK THAT NUMERIC LITERALS YIELD THE CORRECT VALUES.

-- JRK 10/27/80
-- TBN 10/16/85     RENAMED FROM C24002A.ADA AND ADDED BASED
--                  LITERAL EXAMPLES.

WITH REPORT;
PROCEDURE C24002A IS

        USE REPORT;

        X,Y : INTEGER;
        A,B : INTEGER;

BEGIN
        TEST("C24002A", "CHECK THAT BOTH CAPITAL AND LOWER CASE E " &
                        "WORK IN INTEGER LITERALS AND THAT NUMERIC " &
                        "LITERALS YIELD THE CORRECT VALUE");

        X := 12E1;
        Y := 12e1;

        IF (X /= Y) OR (X /= 120) THEN
                FAILED("CAPITAL E NOT SAME AS LOWER CASE E " &
                       "IN INTEGER LITERALS");
        END IF;

        A := 16#E#E1;
        B := 16#E#e1;

        IF (A /= B) OR (A /= 224) THEN
                FAILED("CAPITAL E NOT SAME AS LOWER CASE E " &
                       "IN BASED INTEGER LITERALS");
        END IF;

        RESULT;
END C24002A;
