-- C24002C.ADA

-- CHECK THAT BOTH CAPITAL E AND LOWER CASE E MAY BE USED IN
-- FIXED POINT LITERALS (FOR COMPILERS THAT SUPPORT BOTH).
-- CHECK THAT NUMERIC LITERALS YIELD THE CORRECT VALUES.

-- DCB 04/22/80
-- JRK 10/27/80
-- TBN 10/16/85     RENAMED FROM C24002C.ADA AND ADDED BASED
--                  LITERAL EXAMPLES.

WITH REPORT;
PROCEDURE C24002C IS

        USE REPORT;

        TYPE FIXED IS DELTA 0.1 RANGE 0.0 .. 300.0;
        X,Y : FIXED;
        A,B : FIXED;

BEGIN
        TEST("C24002C", "CHECK THAT BOTH CAPITAL AND LOWER CASE E " &
                        "WORK IN FIXED POINT LITERALS AND THAT " &
                        "NUMERIC LITERALS YIELD THE CORRECT VALUE");

        X := 1.2E1;
        Y := 1.2e1;

        IF (X /= Y) OR (X /= 12.0) THEN
                FAILED("CAPITAL E NOT SAME AS LOWER CASE E " &
                       "IN REAL LITERALS");
        END IF;

        A := 16#F.F#E1;
        B := 16#F.F#e1;

        IF (A /= B) OR (A /= 255.0) THEN
                FAILED("CAPITAL E NOT SAME AS LOWER CASE E " &
                       "IN BASED REAL LITERALS");
        END IF;

        RESULT;
END C24002C;
