-- C24002B.ADA

-- CHECK THAT BOTH CAPITAL E AND LOWER CASE E MAY BE USED IN
-- FLOATING POINT LITERALS (FOR COMPILERS THAT SUPPORT BOTH).
-- CHECK THAT NUMERIC LITERALS YIELD THE CORRECT VALUES.

-- DCB 12/17/79
-- JRK 10/27/80
-- TBN 10/16/85     RENAMED FROM C24002B.ADA AND ADDED BASED
--                  LITERAL EXAMPLES.

WITH REPORT;
PROCEDURE C24002B IS

        USE REPORT;

        X,Y : FLOAT;
        A,B : FLOAT;

BEGIN
        TEST("C24002B", "CHECK THAT BOTH CAPITAL AND LOWER CASE E " &
                        "WORK IN FLOATING POINT LITERALS AND THAT " &
                        "NUMERIC LITERALS YIELD THE CORRECT VALUE");

        X := 1.2E2;
        Y := 1.2e2;

        IF (X /= 120.0) OR (Y /= 120.0) THEN
                FAILED("CAPITAL E NOT SAME AS LOWER CASE E " &
                       "IN REAL LITERALS");
        END IF;

        A := 16#F.FF#E+2;
        B := 16#F.FF#e+2;

        IF (A /= B) OR (A /= 4095.0) THEN
                FAILED("CAPITAL E NOT SAME AS LOWER CASE E " &
                       "IN BASED REAL LITERALS");
        END IF;

        RESULT;
END C24002B;
