-- C24207A.ADA

-- CHECK THAT LETTERS IN A BASED LITERAL MAY APPEAR IN UPPER OR LOWER 
-- CASE.

-- TBN 2/28/86

WITH REPORT; USE REPORT;
PROCEDURE C24207A IS

     TYPE FLOAT IS DIGITS 5;
     INT_1 : INTEGER := 15#AbC# ;
     INT_2 : INTEGER := 15#aBc# ;
     FLO_1 : FLOAT := 16#FeD.C#e1;
     FLO_2 : FLOAT := 16#fEd.c#E1;

BEGIN
     TEST("C24207A", "CHECK THAT LETTERS IN A BASED LITERAL MAY " &
                     "APPEAR IN UPPER OR LOWER CASE");

     IF INT_1 /= INT_2 THEN
          FAILED ("UPPER AND LOWER CASE LETTERS NOT ALLOWED - 1");
     END IF;

     IF FLO_1 /= FLO_2 THEN
          FAILED ("UPPER AND LOWER CASE LETTERS NOT ALLOWED - 2");
     END IF;

     INT_1 := 14#aBc#E1;
     INT_2 := 14#AbC#e1;
     FLO_1 := 16#CdEf.aB#E0;
     FLO_2 := 16#cDeF.Ab#e0;

     IF INT_1 /= INT_2 THEN
          FAILED ("UPPER AND LOWER CASE LETTERS NOT ALLOWED - 3");
     END IF;

     IF FLO_1 /= FLO_2 THEN
          FAILED ("UPPER AND LOWER CASE LETTERS NOT ALLOWED - 4");
     END IF;
     
     RESULT;
END C24207A;
