-- C24211A.ADA

-- OBJECTIVE:
--     CHECK THAT LEGAL FORMS INVOLVING A DIGIT FOLLOWED BY A COLON ARE
--     CORRECTLY ANALYZED USING A TWO CHARACTER LOOK-AHEAD.

-- HISTORY:
--     DHH 01/19/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C24211A IS

     TYPE FIXED IS DELTA 0.0125 RANGE -1.0 .. 100.0;

     A : INTEGER RANGE 0 .. 2:10::= 1;
     B : INTEGER RANGE 0 .. 2#10#:= 1;
     X : FIXED RANGE 0.0 .. 16:3.0::= 1.0;
     Y : FIXED RANGE 0.0 .. 16#3.0#:= 1.0;
     IN2 : INTEGER;
     BOOL : BOOLEAN:=3:10:=3:10:;

BEGIN

     TEST("C24211A", "CHECK THAT LEGAL FORMS INVOLVING A DIGIT " &
                     "FOLLOWED BY A COLON ARE CORRECTLY ANALYZED " &
                     "USING A TWO CHARACTER LOOK-AHEAD");

     IF IDENT_INT(A) /= B THEN
          FAILED("CALCULATIONS OF BASED INTEGER LITERALS WHEN " &
                 "REPRESENTED BY SHARPS DO NOT MATCH CALCULATIONS " &
                 "OF BASED INTEGER LITERALS REPRESENTED BY COLONS");
     END IF;
     A := A + 1;


     IF EQUAL(3,3) THEN
          Y := X + Y;
     ELSE
          Y := X - Y;
     END IF;

     IF (2 * X) = Y THEN
          NULL;
     ELSE
          FAILED("CALCULATIONS OF BASED REAL LITERALS WHEN " &
                 "REPRESENTED BY SHARPS DO NOT MATCH CALCULATIONS " &
                 "OF BASED REAL LITERALS REPRESENTED BY COLONS");
     END IF;
     IF NOT BOOL THEN
          FAILED("BOOLEAN VALUE BASED ON REAL LITERAL WAS CALCULATED " &
                 "INCORRECTLY");
          IN2:=2:10:;
     ELSE
          BOOL := FALSE;
          IN2:=3:10:;
     END IF;
     IF BOOL THEN
          A := A + 1;
     ELSE
          A := A - 1;
     END IF;

     RESULT;
END C24211A;
