-- C25004A.ADA

-- CHECK THAT THE TYPE OF AN OVERLOADED CHARACTER LITERAL IS CORRECTLY 
-- DETERMINED, USING THE VISIBILITY OF ENUMERATION TYPES AND OPERATIONS
-- ON THESE TYPES.

-- TBN 4/21/86

WITH REPORT; USE REPORT;
PROCEDURE C25004A IS

     TYPE ENUM IS ('A', 'B', 'C');

     V_ENUM : ENUM := 'A';
     CHAR : CHARACTER := 'A';
     BOOL_1 : BOOLEAN := 'A' = 'D';
     BOOL_2 : BOOLEAN := 'C' < 'D';

     PACKAGE P IS
          TYPE T IS ('D', 'E', 'F', 'A', 'B', 'C');
     END P;

     SUBTYPE ST IS P.T;
BEGIN
     TEST ("C25004A", "CHECK THAT THE TYPE OF AN OVERLOADED " &
                      "CHARACTER LITERAL IS CORRECTLY DETERMINED");

     IF 'A' = 'D' THEN
          FAILED ("NON-VISIBLE LITERALS AND OPERATORS USED");
     END IF;

     CHAR := 'C';
     V_ENUM := ENUM'SUCC ('B');
     IF V_ENUM /= 'C' THEN
          FAILED ("INCORRECT EVALUATION OF ENUM'SUCC ('B')");
     END IF;

     IF 'B' > 'F' THEN
          FAILED ("NON-VISIBLE LITERALS AND OPERATORS USED");
     END IF;

     RESULT;

END C25004A;
