-- C25003A.ADA

-- CHECK THAT LEXICALLY CONFUSING FORMS WITH APOSTROPHES ARE ANALYZED
-- CORRECTLY.

-- TBN 3/19/86

WITH REPORT; USE REPORT;
PROCEDURE C25003A IS

     TYPE ENUM IS (ONE, TWO, THREE);
     SUBTYPE INT IS INTEGER RANGE 1 .. 10;

BEGIN

     TEST ("C25003A", "CHECK THAT LEXICALLY CONFUSING FORMS ARE " &
                      "ANALYZED CORRECTLY");

     IF'B'IN'A'..'C'THEN
          NULL;
     ELSE
          FAILED ("LEXICALLY CONFUSING FORMS ARE NOT ANALYZED " &
                  "CORRECTLY - 1");
     END IF;
     IF INT'BASE'FIRST/=INTEGER'FIRST THEN
          FAILED ("LEXICALLY CONFUSING FORMS ARE NOT ANALYZED " &
                  "CORRECTLY - 2");
     END IF;
     IF'('=')'THEN
          FAILED ("LEXICALLY CONFUSING FORMS ARE NOT ANALYZED " &
                  "CORRECTLY - 3");
     END IF;
     IF ENUM'VAL(ENUM'POS(TWO))/=TWO THEN
          FAILED ("LEXICALLY CONFUSING FORMS ARE NOT ANALYZED " &
                  "CORRECTLY - 4");
     END IF;
     IF'''IN'B'..'Z'THEN
          FAILED ("LEXICALLY CONFUSING FORMS ARE NOT ANALYZED " &
                  "CORRECTLY - 5");
     END IF;

     IF CHARACTER'POS('(') = CHARACTER'POS(''') THEN
          FAILED ("LEXICALLY CONFUSING FORMS ARE NOT ANALYZED " &
                  "CORRECTLY - 6");
     END IF;

     RESULT;

END C25003A;
