-- C26002B.ADA

-- CHECK THAT DOUBLED " CAN BE USED
--   WITHIN STRING LITERALS AS A DATA CHARACTER.

-- DCB 12/14/79
-- JRK 10/29/80
-- JWC 6/28/85   RENAMED TO -AB

WITH REPORT;
PROCEDURE C26002B IS

     USE REPORT;

     DQ : CHARACTER;
     S1 : STRING(1..1);
     S3 : STRING(1..3);
     S5 : STRING(1..5);

BEGIN
     TEST ("C26002B", "DOUBLED QUOTE CAN BE USED " &
           "WITHIN STRING LITERALS AS A DATA CHARACTER");

     DQ := '"';

     S1 := """";
     IF S1(1) /= DQ THEN
          FAILED ("DOUBLE QUOTE CHARACTER IN STRING - 1");
     END IF;

     S3 := "A""C";
     IF S3(2) /= DQ THEN
          FAILED ("DOUBLE QUOTE CHARACTER IN STRING - 2");
     END IF;

     S5 := """B""D""";
     IF S5(1) /= DQ OR S5(3) /= DQ OR S5(5) /= DQ THEN
          FAILED ("DOUBLE QUOTE CHARACTER IN STRING - 3");
     END IF;

     RESULT;
END C26002B;
