-- C27002A.ADA

-- CHECK THAT LEGAL ADA STATEMENTS AND PRAGMAS CONTAINED IN
--      COMMENTS HAVE NO EFFECT.

-- DCB 12/16/79
-- JRK 10/29/80
-- SPS 12/13/82

-- THE FOLLOWING PRAGMA MUST BE GIVEN BEFORE THE LIBRARY UNIT.
-- PRAGMA MEMORY_SIZE(7997);

WITH SYSTEM;
WITH REPORT;
PROCEDURE C27002A IS

        USE REPORT;

        I1 : INTEGER;

BEGIN
        TEST("C27002A","ADA STATEMENTS AND PRAGMAS INSIDE COMMENTS " &
             "HAVE NO EFFECT");

        I1 := 2;        -- I1 INITIALIZED.

        I1 := I1 + 3;   -- I1 := I1 + 4;

        IF I1 /= 5 THEN
                FAILED("ADA STMTS INSIDE COMMENTS NOT IGNORED");
        END IF;

        IF SYSTEM.MEMORY_SIZE = 7997 THEN
                FAILED("ADA PRAGMAS INSIDE COMMENTS NOT IGNORED");
        END IF;

        RESULT;
END C27002A;
