-- C27001A.ADA

-- CHECK THAT A COMMENT IS TERMINATED BY THE END OF THE LINE,
-- AND NOT BY THE NEXT -- (ELSE THIS COMMENT WILL BE TREATED AS CODE).

-- DCB 1/16/80

WITH REPORT;
PROCEDURE C27001A IS

        USE REPORT;

        I1 : INTEGER;

BEGIN
        TEST("C27001A","COMMENTS TERMINATED BY END OF LINE");

        I1 := 5;        -- I1 INITIALIZED.

        -- BELOW CHECKS THAT A COMMENT IS TERMINATED BY END OF LINE
        I1 := I1 + 7;

        IF I1 /= 12 THEN
                FAILED("COMMENTS NOT TERMINATED BY END OF LINE");
        END IF;

        RESULT;
END C27001A;
