-- C2A021B.ADA

-- CHECK THAT A STRING LITERAL DELIMITED BY PERCENT SIGNS MUST CONTAIN A
-- DOUBLED PERCENT CHARACTER IF THE STRING VALUE IS TO CONTAIN A PERCENT
-- CHARACTER.

-- JBG 5/25/85

WITH REPORT; USE REPORT;
PROCEDURE C2A021B IS
     X : STRING (1..5) := %%%%%345%;
     Y : STRING (1..5) := IDENT_STR ("%%345");
BEGIN
     TEST ("C2A021B", "CHECK USE OF PERCENT SIGN INSIDE STRINGS " &
                      "DELIMITED WITH PERCENT SIGNS");

     IF X /= Y THEN
          FAILED ("STRING LITERALS NOT EQUAL");
     END IF;

     RESULT;
END C2A021B;
