-- C35404A.ADA

-- OBJECTIVE:
--     CHECK THAT PREDEFINED INTEGER IS ITS OWN BASE TYPE.

-- HISTORY:
--     BCB 01/21/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C35404A IS

BEGIN
     TEST ("C35404A", "CHECK THAT PREDEFINED INTEGER IS ITS OWN BASE " &
                      "TYPE");

     IF INTEGER'FIRST /= INTEGER'BASE'FIRST
          THEN FAILED ("INTEGER'FIRST DOES NOT EQUAL " &
                       "INTEGER'BASE'FIRST");
     END IF;

     IF INTEGER'LAST /= INTEGER'BASE'LAST
          THEN FAILED ("INTEGER'LAST DOES NOT EQUAL " &
                       "INTEGER'BASE'LAST");
     END IF;

     IF INTEGER'SIZE /= INTEGER'BASE'SIZE
          THEN FAILED ("INTEGER'SIZE DOES NOT EQUAL " &
                       "INTEGER'BASE'SIZE");
     END IF;

     IF INTEGER'WIDTH /= INTEGER'BASE'WIDTH
          THEN FAILED ("INTEGER'WIDTH DOES NOT EQUAL " &
                       "INTEGER'BASE'WIDTH");
     END IF;

     RESULT;
END C35404A;
