-- C35508B.ADA

-- CHECK THAT THE ATTRIBUTE 'WIDTH' YIELDS THE CORRECT RESULTS WHEN 
-- THE PREFIX IS A GENERIC FORMAL DISCRETE TYPE WHOSE ACTUAL 
-- PARAMETER IS A BOOLEAN TYPE.   

-- RJW 3/19/86  COMPLETELY REVISED.

WITH REPORT; USE REPORT;

PROCEDURE  C35508B  IS

BEGIN

     TEST( "C35508B" , "CHECK THAT THE ATTRIBUTE 'WIDTH' YIELDS " &
                       "THE CORRECT RESULTS WHEN THE PREFIX IS A " &
                       "GENERIC FORMAL DISCRETE TYPE WHOSE ACTUAL " &
                       "PARAMETER IS A BOOLEAN TYPE" );

     DECLARE
          SUBTYPE FRANGE IS BOOLEAN 
               RANGE IDENT_BOOL(FALSE) .. IDENT_BOOL(FALSE);
          SUBTYPE TRANGE IS BOOLEAN 
               RANGE IDENT_BOOL(TRUE) .. IDENT_BOOL(TRUE);
          TYPE NEWBOOL IS NEW BOOLEAN;

          GENERIC
               TYPE B IS (<>);
               W : INTEGER;
          PROCEDURE P (STR : STRING);

          PROCEDURE P (STR : STRING) IS
               SUBTYPE NOBOOL IS B RANGE 
                    B'VAL (IDENT_INT(1)) .. B'VAL (IDENT_INT(0));
          BEGIN
               IF B'WIDTH /= W THEN 
                    FAILED ( "INCORRECT B'WIDTH FOR " & STR );
               END IF;
               IF NOBOOL'WIDTH /= 0 THEN
                    FAILED ( "INCORRECT NOBOOL'WIDTH FOR " & STR );
               END IF;
          END P;

          PROCEDURE PROC1 IS NEW P (BOOLEAN, 5);
          PROCEDURE PROC2 IS NEW P (FRANGE, 5);
          PROCEDURE PROC3 IS NEW P (TRANGE, 4);
          PROCEDURE PROC4 IS NEW P (NEWBOOL, 5);

     BEGIN
          PROC1 ( "BOOLEAN" );
          PROC2 ( "FRANGE" );
          PROC3 ( "TRANGE");
          PROC4 ( "NEWBOOL" );
     END;                    

     RESULT;
END C35508B;
