-- C35502O.ADA

-- CHECK THAT 'FIRST AND 'LAST GIVE CORRECT RESULTS FOR TYPES
-- AND SUBTYPES.

-- DAT 3/17/81
-- R. WILLIAMS 11/11/86      RENAMED FROM C35104A.ADA.

WITH REPORT; USE REPORT;
PROCEDURE C35502O IS

     TYPE E IS (E1, E2, E3, E4, E5);

     SUBTYPE S IS E RANGE E2 .. E4;

BEGIN
     TEST ("C35502O", "CHECK THAT 'FIRST AND 'LAST WORK FOR"
          & " ENUMERATION TYPES AND SUBTYPES");

     IF E'FIRST /= E1 OR E'LAST /= E5
     OR E'BASE'FIRST /= E1 OR E'BASE'LAST /= E5
     OR S'BASE'FIRST /= E1 OR S'BASE'LAST /= E5
     OR S'FIRST /= E2 OR S'LAST /= E4
     OR BOOLEAN'FIRST /= FALSE OR BOOLEAN'LAST /= TRUE
     THEN
          FAILED ("'FIRST OR 'LAST GIVES WRONG RESULTS");
     END IF;

     RESULT;
END C35502O;
