-- C35508A.ADA

-- CHECK THAT THE ATTRIBUTE 'WIDTH' YIELDS THE CORRECT RESULTS WHEN 
-- THE PREFIX IS A BOOLEAN TYPE.   

-- RJW 3/14/86  COMPLETELY REVISED.

WITH REPORT; USE REPORT;

PROCEDURE  C35508A  IS

BEGIN

     TEST( "C35508A" , "CHECK THAT THE ATTRIBUTE 'WIDTH' YIELDS " &
                       "THE CORRECT RESULTS WHEN THE PREFIX IS A " &
                       "BOOLEAN TYPE" );

     DECLARE
          TYPE NEWBOOL IS NEW BOOLEAN;
          SUBTYPE FRANGE IS BOOLEAN 
               RANGE IDENT_BOOL(FALSE) .. IDENT_BOOL(FALSE);
          SUBTYPE TRANGE IS BOOLEAN 
               RANGE IDENT_BOOL(TRUE) .. IDENT_BOOL(TRUE);
          SUBTYPE NOBOOL IS BOOLEAN 
               RANGE IDENT_BOOL(TRUE) .. IDENT_BOOL(FALSE);

     BEGIN

          IF BOOLEAN'WIDTH /= 5 THEN
               FAILED( "INCORRECT WIDTH FOR BOOLEAN" );
          END IF;

          IF NEWBOOL'WIDTH /= 5 THEN
               FAILED( "INCORRECT WIDTH FOR NEWBOOL" );
          END IF;

          IF FRANGE'WIDTH /= 5 THEN
               FAILED( "INCORRECT WIDTH FOR FRANGE" );
          END IF;

          IF TRANGE'WIDTH /= 4 THEN
               FAILED( "INCORRECT WIDTH FOR TRANGE" );
          END IF;

          IF NOBOOL'WIDTH /= 0 THEN
               FAILED( "INCORRECT WIDTH FOR NOBOOL" );
          END IF;
     
     END;                    

     RESULT;
END C35508A;
