-- C35502A.ADA

-- CHECK THAT THE ATTRIBUTE 'WIDTH' YIELDS THE CORRECT RESULTS 
-- WHEN THE PREFIX IS AN ENUMERATION TYPE OTHER THAN A BOOLEAN OR 
-- A CHARACTER TYPE.   

-- RJW 5/05/86

WITH REPORT; USE REPORT;

PROCEDURE  C35502A  IS

BEGIN

     TEST( "C35502A" , "CHECK THAT THE ATTRIBUTE 'WIDTH' YIELDS " &
                       "THE CORRECT RESULTS WHEN THE PREFIX " &
                       "IS AN ENUMERATION TYPE OTHER THAN " &
                       "A BOOLEAN OR A CHARACTER TYPE" );

     DECLARE
          TYPE ENUM IS (A, BC, ABC, A_B_C, ABCD);

          SUBTYPE SUBENUM IS ENUM RANGE A .. ABC;
          SUBTYPE NOENUM IS ENUM RANGE ABC .. A;
          
          TYPE NEWENUM IS NEW ENUM;
         
     BEGIN

          IF ENUM'WIDTH /= IDENT_INT(5) THEN
               FAILED( "INCORRECT WIDTH FOR ENUM" );
          END IF;

          IF NEWENUM'WIDTH /= IDENT_INT(5) THEN
               FAILED( "INCORRECT WIDTH FOR NEWENUM" );
          END IF;

          IF SUBENUM'WIDTH /= IDENT_INT(3) THEN
               FAILED( "INCORRECT WIDTH FOR SUBENUM" );
          END IF;

          IF NOENUM'WIDTH /= IDENT_INT(0) THEN
               FAILED( "INCORRECT WIDTH FOR NOENUM" );
          END IF;

     END;                    

     RESULT;
END C35502A;
