-- C35704C.ADA

-- CHECK THAT DIFFERENT FLOATING POINT TYPES FROM DIFFERENT PARENTS
-- CAN BE USE IN FLOATING POINT RANGE CONSTRAINTS IN TYPE DEFINITIONS.

-- JCR 4/7/82

WITH REPORT;
PROCEDURE C35704C IS

     USE REPORT;

BEGIN
     TEST ("C35704C", "DIFFERENT FLOATING POINT TYPES " &
           "FROM DIFFERENT PARENTS IN FLOATING POINT RANGE " &
           "CONSTRAINT IN TYPE DEFINITION");

     DECLARE

          TYPE F IS DIGITS 5 RANGE -5.0 .. 5.0;
          TYPE F1 IS DIGITS 5 RANGE -5.0 .. 5.0;
     
          TYPE G1 IS DIGITS 5 RANGE  F'FIRST..F1'LAST;
          TYPE G2 IS DIGITS 5 RANGE F1'FIRST..F'LAST;
     
     BEGIN


          IF G1'FIRST /= G1(F'FIRST) OR G1'FIRST /= G1(G2'FIRST) OR
          G1'FIRST /= G1(F1'FIRST) OR G1'LAST /= G1(F'LAST) OR
          G1'LAST /= G1(G2'LAST) OR G1'LAST /= G1(F1'LAST)

          THEN FAILED ("USING FLOAT FROM DIFF PARENTS");

          END IF;
     END;

     RESULT;

END C35704C;
