-- C35713A.ADA

-- OBJECTIVE:
--     CHECK THAT PREDEFINED FLOAT IS ITS OWN BASE TYPE.

-- HISTORY:
--     BCB 01/21/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C35713A IS

BEGIN
     TEST ("C35713A", "CHECK THAT PREDEFINED FLOAT IS ITS OWN BASE " &
                      "TYPE");

     IF FLOAT'DIGITS /= FLOAT'BASE'DIGITS
          THEN FAILED ("FLOAT'DIGITS DOES NOT EQUAL " &
                       "FLOAT'BASE'DIGITS");
     END IF;

     IF FLOAT'MANTISSA /= FLOAT'BASE'MANTISSA
          THEN FAILED ("FLOAT'MANTISSA DOES NOT EQUAL " &
                       "FLOAT'BASE'MANTISSA");
     END IF;

     IF FLOAT'SIZE /= FLOAT'BASE'SIZE
          THEN FAILED ("FLOAT'SIZE DOES NOT EQUAL " &
                       "FLOAT'BASE'SIZE");
     END IF;

     IF FLOAT'MACHINE_RADIX /= FLOAT'BASE'MACHINE_RADIX
          THEN FAILED ("FLOAT'MACHINE_RADIX DOES NOT EQUAL " &
                       "FLOAT'BASE'MACHINE_RADIX");
     END IF;

     IF FLOAT'MACHINE_EMAX /= FLOAT'BASE'MACHINE_EMAX
          THEN FAILED ("FLOAT'MACHINE_RADIX DOES NOT EQUAL " &
                       "FLOAT'BASE'MACHINE_RADIX");
     END IF;

     IF FLOAT'MACHINE_EMIN /= FLOAT'BASE'MACHINE_EMIN
          THEN FAILED ("FLOAT'MACHINE_EMIN DOES NOT EQUAL " &
                       "FLOAT'BASE'MACHINE_EMIN");
     END IF;

     IF FLOAT'MACHINE_ROUNDS /= FLOAT'BASE'MACHINE_ROUNDS
          THEN FAILED ("FLOAT'MACHINE_ROUNDS DOES NOT EQUAL " &
                       "FLOAT'BASE'MACHINE_ROUNDS");
     END IF;

     IF FLOAT'MACHINE_OVERFLOWS /= FLOAT'BASE'MACHINE_OVERFLOWS
          THEN FAILED ("FLOAT'MACHINE_OVERFLOWS DOES NOT EQUAL " &
                       "FLOAT'BASE'MACHINE_OVERFLOWS");
     END IF;

     RESULT;
END C35713A;
