-- C35704B.ADA

-- CHECK THAT DIFFERENT FLOATING POINT TYPES FROM SAME PARENT CAN BE
-- USED IN A FLOATING POINT RANGE CONSTRAINT IN A TYPE DEFINITION.

-- JCR 4/7/82

WITH REPORT;
PROCEDURE C35704B IS

     USE REPORT;

BEGIN
     TEST ("C35704B", "DIFFERENT FLOATING POINT TYPES " &
           "FROM THE SAME PARENT IN FLOATING POINT" &
           "TYPE DEFINITION'S RANGE CONSTRAINT");

     DECLARE
          TYPE F IS  DIGITS 5 RANGE -5.0 .. 5.0;

          TYPE F1 IS NEW F;

          TYPE G1 IS DIGITS 5 RANGE F1'FIRST..F'LAST;
          TYPE G2 IS DIGITS 5 RANGE F'FIRST..F1'LAST;

     BEGIN

          IF G1'FIRST /= G1(G2'FIRST) OR G1'LAST /= G1(G2'LAST) OR
             G2'FIRST /= G2(F'FIRST) OR G2'LAST /= G2(F'LAST)
          THEN 
               FAILED ("USING DIFF FLOATING POINT TYPES " &
                       "FROM SAME PARENT");

          END IF;

     END;

     RESULT;

END C35704B;
