-- C35704D.ADA

-- CHECK THAT A COMBINATION OF FIXED AND FLOAT CAN BE USED IN A
-- FLOATING POINT RANGE CONSTRAINT IN A TYPE DEFINITION.

-- JCR 4/7/82

WITH REPORT;
PROCEDURE C35704D IS

     USE REPORT;

BEGIN
     TEST ("C35704D","MIXED FIXED AND FLOAT IN FLOATING " &
           "POINT RANGE CONSTRAINT IN A TYPE DEFINITION");

     DECLARE

          TYPE F IS DIGITS 5;
          TYPE R IS DELTA 0.5 RANGE -5.0 .. 5.0;

          T1 : CONSTANT F := -4.0;
          T2 : CONSTANT F := 4.0;

          R1 : CONSTANT R := -4.0;
          R2 : CONSTANT R := 4.0;

          TYPE G1 IS DIGITS 5 RANGE T1..R2;
          TYPE G2 IS DIGITS 5 RANGE R1..T2;

     BEGIN

          IF (ABS(G1'FIRST)- 4.0) /= 0.0  OR
             (ABS(G1'LAST) - 4.0) /= 0.0  OR
             (ABS(G2'FIRST)- 4.0) /= 0.0  OR
             (ABS(G2'LAST) - 4.0) /= 0.0
     
          THEN FAILED ("MIXED FIXED AND FLOAT IN FLOAT RANGE " &
                       "CONSTRAINT");
     
          END IF;

     END;

     RESULT;
 

END C35704D;
