-- C35704A.ADA

-- CHECK THAT FIXED POINT VALUES CAN BE USED IN FLOATING POINT RANGE
-- CONSTRAINT IN TYPE DEFINITION.

-- BAW 9/5/80
-- JCR 4/7/82

WITH REPORT;
PROCEDURE C35704A IS

     USE REPORT;

BEGIN
     TEST ("C35704A","CHECK THAT L AND R CAN BE FIXED POINT" &
           " IN A FLOATING POINT TYPE DEFINITION");

     DECLARE


          TYPE F IS DELTA 0.5 RANGE -5.0..5.0;

          F1 : CONSTANT F := -4.0;
          F2 : CONSTANT F := 4.0;

          TYPE G1 IS DIGITS 5 RANGE F1..F2;
     BEGIN

          IF (ABS(G1'FIRST)-4.0) /= 0.0 OR
             (ABS(G1'LAST)-4.0)  /= 0.0
          THEN FAILED ("ERROR IN USING FIXED-POINT IN RANGE " &
                       "CONSTRAINT");
          END IF;

     END;
     RESULT;

END C35704A;
