-- C35801D.ADA

-- CHECK THAT THE ATTRIBUTES FIRST AND LAST RETURN VALUES HAVING THE
-- SAME BASE TYPE AS THE PREFIX WHEN THE PREFIX IS A GENERIC FORMAL 
-- SUBTYPE WHOSE ACTUAL ARGUMENT IS A FLOATING POINT TYPE.

-- R.WILLIAMS 8/21/86

WITH REPORT; USE REPORT;
PROCEDURE C35801D IS
     TYPE REAL IS DIGITS 3 RANGE -100.0 .. 100.0;

     TYPE NFLT IS NEW FLOAT;

     GENERIC
          TYPE F IS DIGITS <>;
     PROCEDURE P (STR : STRING);

     PROCEDURE P (STR : STRING) IS

          SUBTYPE SF IS F RANGE -1.0 .. 1.0;
          F1 : SF := 0.0;
          F2 : SF := 0.0;
          
     BEGIN
          IF EQUAL (3, 3) THEN
               F1 := SF'FIRST;
               F2 := SF'LAST;
          END IF;

          IF F1 /= -1.0 OR F2 /= 1.0 THEN
               FAILED ( "WRONG RESULTS FROM " & STR & "'FIRST OR " &
                        STR & "'LAST" );
          END IF;
     END P;
     
     PROCEDURE NP1 IS NEW P (FLOAT);

     PROCEDURE NP2 IS NEW P (NFLT);

     PROCEDURE NP3 IS NEW P (REAL);

BEGIN
     TEST ( "C35801D", "CHECK THAT THE ATTRIBUTES FIRST AND " &
                       "LAST RETURN VALUES HAVING THE SAME " &
                       "BASE TYPE AS THE PREFIX WHEN THE " &
                       "PREFIX IS A GENERIC FORMAL SUBTYPE " &
                       "WHOSE ACTUAL ARGUMENT IS A FLOATING " &
                       "POINT TYPE" );


     NP1 ("FLOAT");
     NP2 ("NFLT");
     NP3 ("REAL");

     RESULT;     
END C35801D;
