-- C35904A.ADA

-- OBJECTIVE:
--     CHECK THAT INCOMPATIBLE FIXED POINT CONSTRAINTS RAISE
--     APPROPRIATE EXCEPTIONS.

-- HISTORY:
--     RJK 05/17/83  CREATED ORIGINAL TEST.
--     PWB 02/03/86  CORRECTED TEST ERROR:
--                   ADDED POSSIBLITY OF NUMERIC_ERROR
--                   IN DECLARATIONS OF SFX3 AND SFX4.
--     BCB 10/21/87  CHANGED HEADER TO STANDARD FORMAT.  CHANGED RANGE
--                   CONSTRAINTS OF SUBTYPE SFX1.  CHANGED UPPER BOUND
--                   OF THE CONSTRAINT OF SFX4.  CHANGED RANGE
--                   CONSTRAINTS OF FIX.

WITH REPORT; USE REPORT;
PROCEDURE C35904A IS

     TYPE FIX IS DELTA 0.5 RANGE -3.0 .. 3.0;

BEGIN

     TEST ("C35904A", "CHECK THAT INCOMPATIBLE FIXED POINT " &
                      "CONSTRAINTS RAISE APPROPRIATE EXCEPTION");

-- TEST FOR CORRECT SUBTYPE DEFINITION FOR COMPATIBILITY BETWEEN TYPE
-- AND SUBTYPE CONSTRAINTS.

     BEGIN

          DECLARE

               SUBTYPE SFX1 IS FIX DELTA 1.0 RANGE 0.0 .. 2.0;   -- OK.
               SFX1_VAR : SFX1;

          BEGIN
               SFX1_VAR := 1.0;
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
                FAILED ("FIXED POINT CONSTRAINTS ARE NOT IN ERROR");
          WHEN OTHERS =>
                FAILED ("EXCEPTION SHOULD NOT BE RAISED WHILE " &
                        "CHECKING DELTA CONSTRAINT");
     END;

-- TEST FOR INCORRECT SUBTYPE DEFINITION ON ACCURACY BETWEEN TYPE AND
-- SUBTYPE DEFINITIONS.

     BEGIN

          DECLARE

               SUBTYPE SFX IS FIX DELTA 0.1;  -- DELTA IS SMALLER FOR
                                              -- SUBTYPE THAN FOR TYPE.

          BEGIN
               FAILED ("NO EXCEPTION RAISED FOR INCOMPATIBLE DELTA");
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("INCORRECT EXCEPTION RAISED WHILE CHECKING " &
                       "DELTA CONSTRAINT");
     END;

-- TEST THAT CONSTRAINT_ERROR OR NUMERIC_ERROR IS RAISED
-- FOR A RANGE VIOLATION.

     BEGIN

          DECLARE

               SUBTYPE SFX3 IS FIX DELTA 0.5 RANGE -5.0 .. 1.0; -- LOWER
                                                               -- BOUND.

          BEGIN
               FAILED ("NO EXCEPTION RAISED FOR FIXED POINT LOWER " &
                       "BOUND CONSTRAINT VIOLATION");
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR  =>
               COMMENT ("CONSTRAINT_ERROR RAISED WHILE CHECKING " &
                        "FIXED POINT LOWER BOUND CONSTRAINT");

          WHEN NUMERIC_ERROR  =>
               COMMENT ("NUMERIC_ERROR RAISED WHILE CHECKING " &
                        "FIXED POINT LOWER BOUND CONSTRAINT");

          WHEN OTHERS =>
               FAILED ("INCORRECT EXCEPTION RAISED WHILE CHECKING " &
                       "FIXED POINT LOWER BOUND CONSTRAINT");
     END;

-- TEST THAT CONSTRAINT_ERROR OR NUMERIC_ERROR IS RAISED
-- FOR A RANGE VIOLATION.

     BEGIN

          DECLARE

               SUBTYPE SFX4 IS FIX DELTA 0.5 RANGE 0.0 .. 5.0; -- UPPER
                                                               -- BOUND.

          BEGIN
               FAILED ("NO EXCEPTION RAISED FOR FIXED POINT UPPER " &
                       "BOUND CONSTRAINT VIOLATION");
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR  =>
               COMMENT ("CONSTRAINT_ERROR RAISED WHILE CHECKING " &
                        "FIXED POINT UPPER BOUND CONSTRAINT");

          WHEN NUMERIC_ERROR  =>
               COMMENT ("NUMERIC_ERROR RAISED WHILE CHECKING " &
                        "FIXED POINT UPPER BOUND CONSTRAINT");

          WHEN OTHERS =>
               FAILED ("INCORRECT EXCEPTION RAISED WHILE CHECKING " &
                       "FIXED POINT UPPER BOUND CONSTRAINT");
     END;

     RESULT;

END C35904A;
