-- C35902A.ADA

-- CHECK THAT THE CORRECT DEFAULT VALUE OF 'SMALL IS USED FOR
-- FIXED TYPES.

-- PWB  03/05/86

WITH REPORT; USE REPORT;

PROCEDURE C35902A IS

     D_16TH : CONSTANT := 0.0625;          -- (2 ** -4)
     D_TINY : CONSTANT := 16#0.000001#;    -- (2 ** -24)
     D_2DEC : CONSTANT := 0.01;
     D_3DEC : CONSTANT := 0.001;
     TWO_TO_NEG_7  : CONSTANT := 2#0.0000001#;
     TWO_TO_NEG_10 : CONSTANT := 4#0.00001#;

     TYPE FIX_16THS IS DELTA D_16TH RANGE -1.0 .. 1.0;
     TYPE FIX_TINY IS DELTA D_TINY RANGE -1.0 .. 1.0;
     TYPE FIX_2DEC IS DELTA D_2DEC RANGE -1.0 .. 1.0;
     TYPE FIX_3DEC IS DELTA D_3DEC RANGE -1.0 .. 1.0;

     GENERIC
          TYPE FIXED IS DELTA <>;
          I : INTEGER;
     PROCEDURE GEN_PROC;

     PROCEDURE GEN_PROC IS
     BEGIN
          IF I = 1 THEN
               IF FIXED'SMALL /= D_TINY THEN
                    FAILED ("INCORRECT VALUE FOR SMALL--GENERIC 1");
               END IF;
          ELSIF I = 2 THEN
               IF FIXED'SMALL /= TWO_TO_NEG_10 THEN
                    FAILED ("INCORRECT VALUE FOR SMALL--GENERIC 2");
               END IF;
          END IF;
     END GEN_PROC;

     PROCEDURE CHECK_1 IS NEW GEN_PROC (FIX_TINY, 1);
     PROCEDURE CHECK_2 IS NEW GEN_PROC (FIX_3DEC, 2);

BEGIN  -- C35902A

     TEST ("C35902A", "DEFAULT VALUE OF 'SMALL FOR FIXED TYPES");

     IF FIX_16THS'SMALL /= D_16TH THEN
          FAILED ("INCORRECT VALUE FOR SMALL--16THS");
     END IF;

     IF FIX_2DEC'SMALL /= TWO_TO_NEG_7 THEN
          FAILED ("INCORRECT VALUE FOR SMALL--2DEC");
     END IF;

     CHECK_1;
     CHECK_2;

     RESULT;

END C35902A;
