-- C35902B.ADA

-- CHECK THAT THE EXPRESSION FOLLOWING DELTA AND THE BOUNDS IN A FIXED 
-- POINT TYPE DECLARATION CAN ALL BE OF DIFFERENT REAL TYPES, 
-- INCLUDING FLOATING POINT.

-- RJW 6/20/86

WITH REPORT; USE REPORT;

PROCEDURE C35902B IS

BEGIN

     TEST ( "C35902B", "CHECK THAT THE EXPRESSION FOLLOWING DELTA " &
                       "AND THE BOUNDS IN A FIXED POINT TYPE " &
                       "DECLARATION CAN ALL BE OF DIFFERENT REAL " &
                       "TYPES, INCLUDING FLOATING POINT" );

     DECLARE
          TYPE FIX1 IS DELTA 0.1 RANGE -1.0 .. 2.0;   
          FI1 : CONSTANT FIX1 := 0.1;
          
          TYPE NFIX1 IS NEW FIX1;
          NFI1 : CONSTANT NFIX1 := 1.0;

          FL1 : CONSTANT FLOAT := 0.5;

          TYPE NFLT IS NEW FLOAT;
          NFL1 : CONSTANT NFLT := 0.125;

          UR : CONSTANT := 1.0/2;

          TYPE FIX2 IS DELTA FI1 RANGE -1.0 .. NFI1;
          FI2 : CONSTANT FIX2 := -0.5;

          TYPE FIX3 IS DELTA FL1 RANGE NFI1 .. 2.0;
          TYPE FIX4 IS DELTA 0.125  RANGE NFL1 .. NFI1 + 0.125;
          TYPE FIX5 IS DELTA UR RANGE FI2 .. NFI1;
     BEGIN
          IF FIX1'DELTA NOT IN 0.0625 .. 0.125 THEN
               FAILED ( "INCORRECT VALUE FOR FIX1'DELTA" );
          END IF;

          IF FIX1'LARGE /= 1.9375 THEN
               FAILED ( "INCORRECT VALUE FOR FIX1'LARGE" );
          END IF;

          IF FIX1'SMALL /= 0.0625 THEN
               FAILED ( "INCORRECT VALUE FOR FIX1'SMALL" );
          END IF;

          IF FIX1'MANTISSA /= 5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX1'MANTISSA" );
          END IF;

          IF FIX1'FIRST /= -1.0 THEN
               FAILED ( "INCORRECT VALUE FOR FIX1'FIRST" );
          END IF;

          IF FIX2'DELTA NOT IN 0.0625 .. 0.125 THEN
               FAILED ( "INCORRECT VALUE FOR FIX2'DELTA" );
          END IF;

          IF FIX2'LARGE /= 0.875 AND FIX2'LARGE /= 0.9375 THEN
               FAILED ( "INCORRECT VALUE FOR FIX2'LARGE" );
          END IF;

          IF FIX2'SMALL /= 0.125 AND FIX2'SMALL /= 0.0625 THEN
               FAILED ( "INCORRECT VALUE FOR FIX2'SMALL" );
          END IF;

          IF FIX2'MANTISSA /= 3 AND FIX2'MANTISSA /= 4 THEN
               FAILED ( "INCORRECT VALUE FOR FIX2'MANTISSA" );
          END IF;

          IF FIX3'DELTA /= 0.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX3'DELTA" );
          END IF;

          IF FIX3'LARGE /= 1.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX3'LARGE" );
          END IF;

          IF FIX3'SMALL /= 0.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX3'SMALL" );
          END IF;

          IF FIX3'MANTISSA /= 2 THEN
               FAILED ( "INCORRECT VALUE FOR FIX3'MANTISSA" );
          END IF;

          IF FIX3'FIRST /= 1.0 THEN
               FAILED ( "INCORRECT VALUE FOR FIX3'FIRST" );
          END IF;

          IF FIX4'DELTA /= 0.125 THEN
               FAILED ( "INCORRECT VALUE FOR FIX4'DELTA" );
          END IF;

          IF FIX4'LARGE /= 1.875 THEN
               FAILED ( "INCORRECT VALUE FOR FIX4'LARGE" );
          END IF;

          IF FIX4'SMALL /= 0.125 THEN
               FAILED ( "INCORRECT VALUE FOR FIX4'SMALL" );
          END IF;

          IF FIX4'MANTISSA /= 4 THEN
               FAILED ( "INCORRECT VALUE FOR FIX4'MANTISSA" );
          END IF;

          IF FIX4'FIRST /= 0.125 THEN
               FAILED ( "INCORRECT VALUE FOR FIX4'FIRST" );
          END IF;

          IF FIX4'LAST /= 1.125 THEN
               FAILED ( "INCORRECT VALUE FOR FIX4'LAST" );
          END IF;

          IF FIX5'DELTA /= 0.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX5'DELTA" );
          END IF;

          IF FIX5'LARGE /= 0.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX5'LARGE" );
          END IF;

          IF FIX5'SMALL /= 0.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX5'SMALL" );
          END IF;

          IF FIX5'MANTISSA /= 1 THEN
               FAILED ( "INCORRECT VALUE FOR FIX5'MANTISSA" );
          END IF;

          IF FIX5'FIRST /= -0.5 THEN
               FAILED ( "INCORRECT VALUE FOR FIX5'FIRST" );
          END IF;

     END;
     
     RESULT;

END C35902B;
