-- C35904B.ADA

-- CHECK THAT INCOMPATIBLE FIXED POINT CONSTRAINTS RAISE
-- CONSTRAINT_ERROR FOR GENERIC FORMAL TYPES.

-- RJW 6/20/86
-- DWC 07/24/87     -- ADDED NUMERIC_ERROR HANDLERS.

WITH REPORT; USE REPORT;
PROCEDURE C35904B IS

     GENERIC
          TYPE FIX IS DELTA <>;
     PROCEDURE PROC (STR : STRING);

     PROCEDURE PROC (STR : STRING) IS
          SUBTYPE SFIX IS FIX DELTA 0.1 RANGE -1.0 .. 1.0;
     BEGIN
          FAILED ( "NO EXCEPTION RAISED FOR " & STR );
     END PROC;

BEGIN

     TEST ( "C35904B", "CHECK THAT INCOMPATIBLE FIXED POINT " &
                       "CONSTRAINTS RAISE CONSTRAINT_ERROR " &
                       "FOR GENERIC FORMAL TYPES" );

-- TEST FOR INCORRECT SUBTYPE DEFINITION ON ACCURACY BETWEEN TYPE AND
-- SUBTYPE DEFINITIONS.

     BEGIN

          DECLARE

               TYPE FIX1 IS DELTA 0.5          -- DELTA IS SMALLER FOR
                         RANGE -2.0 .. 2.0;    -- SUBTYPE THEN FOR
                                               -- TYPE.

               PROCEDURE NPROC IS NEW PROC (FIX1);

          BEGIN
               NPROC ( "INCOMPATIBLE DELTA" );
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("INCORRECT EXCEPTION RAISED WHILE CHECKING " &
                       "DELTA CONSTRAINT");
     END;

-- TEST THAT CONSTRAINT_ERROR/NUMERIC_ERROR IS RAISED
-- FOR A RANGE VIOLATION.

     BEGIN

          DECLARE

               TYPE FIX2 IS DELTA 0.1 RANGE 0.0 .. 2.0; -- LOWER
                                                        -- BOUND.

               PROCEDURE NPROC IS NEW PROC (FIX2);

          BEGIN
               NPROC ("FIXED POINT LOWER BOUND CONSTRAINT VIOLATION");
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               COMMENT ("CONSTRAINT_ERROR RAISED FOR " &
                        "LOWER BOUND VIOLATION");
          WHEN NUMERIC_ERROR =>
               COMMENT ("NUMERIC_ERROR RAISED FOR " &
                        "LOWER BOUND VIOLATION");
          WHEN OTHERS =>
               FAILED ("INCORRECT EXCEPTION RAISED WHILE CHECKING " &
                       "FIXED POINT LOWER BOUND CONSTRAINT");
     END;

-- TEST THAT CONSTRAINT_ERROR/NUMERIC_ERROR IS RAISED
-- FOR A RANGE VIOLATION.

     BEGIN

          DECLARE

               TYPE FIX3 IS DELTA 0.1 RANGE -2.0 .. 0.0;  -- UPPER
                                                          -- BOUND.

               PROCEDURE NPROC IS NEW PROC (FIX3);
          BEGIN
               NPROC ("FIXED POINT UPPER BOUND CONSTRAINT VIOLATION");
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               COMMENT ("CONSTRAINT_ERROR RAISED FOR " &
                        "UPPER BOUND VIOLATION");
          WHEN NUMERIC_ERROR =>
               COMMENT ("NUMERIC_ERROR RAISED FOR " &
                        "UPPER BOUND VIOLATION");
          WHEN OTHERS =>
               FAILED ("INCORRECT EXCEPTION RAISED WHILE CHECKING " &
                       "FIXED POINT UPPER BOUND CONSTRAINT");
     END;

     RESULT;

END C35904B;
