-- C35A03A.ADA

-- CHECK THAT FOR FIXED POINT TYPES THE MANTISSA ATTRIBUTE YIELDS THE
-- CORRECT VALUES.

-- CASE A: BASIC TYPES THAT FIT THE CHARACTERISTICS OF DURATION'BASE.

-- WRG 7/22/86

WITH REPORT; USE REPORT;
PROCEDURE C35A03A IS

     -- THE NAME OF EACH TYPE OR SUBTYPE ENDS WITH THAT TYPE'S
     -- 'MANTISSA VALUE.

     TYPE LEFT_OUT_M1       IS DELTA 0.25  RANGE -0.5 .. 0.5;
     TYPE LEFT_EDGE_M1      IS DELTA 0.5   RANGE -1.0 .. 1.0;
     TYPE RIGHT_EDGE_M1     IS DELTA 1.0   RANGE -2.0 .. 2.0;
     TYPE RIGHT_OUT_M1      IS DELTA 2.0   RANGE -4.0 .. 4.0;
     TYPE MIDDLE_M2         IS DELTA 0.5   RANGE -2.0 .. 2.0;
     TYPE MIDDLE_M3         IS DELTA 0.5   RANGE  0.0 .. 2.5;
     TYPE MIDDLE_M15        IS DELTA 2.0 **(-6) RANGE  -512.0 ..  512.0;
     TYPE MIDDLE_M16        IS DELTA 2.0 **(-6) RANGE -1024.0 .. 1024.0;
     TYPE LIKE_DURATION_M23 IS DELTA 0.020 RANGE -86_400.0 .. 86_400.0;
     TYPE DECIMAL_M18       IS DELTA 0.1   RANGE -10_000.0 .. 10_000.0;
     TYPE DECIMAL_M4        IS DELTA 100.0 RANGE   -1000.0 ..   1000.0;

     -------------------------------------------------------------------

     SUBTYPE ST_LEFT_EDGE_M6 IS MIDDLE_M15
          DELTA 2.0 ** (-6) RANGE IDENT_INT (1) * (-1.0) .. 1.0;
     SUBTYPE ST_MIDDLE_M14   IS MIDDLE_M16
          DELTA 2.0 ** (-5) RANGE -512.0 .. IDENT_INT (1) * 512.0;
     SUBTYPE ST_MIDDLE_M2    IS LIKE_DURATION_M23
          DELTA 0.5 RANGE -2.0 .. 2.0;
     SUBTYPE ST_MIDDLE_M3    IS LIKE_DURATION_M23
          DELTA 0.5 RANGE  0.0 .. 2.5;
     SUBTYPE ST_DECIMAL_M7   IS DECIMAL_M18
          DELTA  10.0 RANGE -1000.0 .. 1000.0;
     SUBTYPE ST_DECIMAL_M3   IS DECIMAL_M4
          DELTA 100.0 RANGE  -500.0 ..  500.0;

BEGIN

     TEST ("C35A03A", "CHECK THAT FOR FIXED POINT TYPES THE MANTISSA " &
                      "ATTRIBUTE YIELDS THE CORRECT VALUES - BASIC " &
                      "TYPES");

     IF IDENT_INT (LEFT_OUT_M1'MANTISSA) /= 1 THEN
          FAILED ("LEFT_OUT_M1'MANTISSA =" &
                  INTEGER'IMAGE(LEFT_OUT_M1'MANTISSA) );
     END IF;

     IF IDENT_INT (LEFT_EDGE_M1'MANTISSA) /= 1 THEN
          FAILED ("LEFT_EDGE_M1'MANTISSA =" &
                  INTEGER'IMAGE(LEFT_EDGE_M1'MANTISSA) );
     END IF;

     IF IDENT_INT (RIGHT_EDGE_M1'MANTISSA) /= 1 THEN
          FAILED ("RIGHT_EDGE_M1'MANTISSA =" &
                  INTEGER'IMAGE(RIGHT_EDGE_M1'MANTISSA) );
     END IF;

     IF IDENT_INT (RIGHT_OUT_M1'MANTISSA) /= 1 THEN
          FAILED ("RIGHT_OUT_M1'MANTISSA =" &
                  INTEGER'IMAGE(RIGHT_OUT_M1'MANTISSA) );
     END IF;

     IF IDENT_INT (MIDDLE_M2'MANTISSA) /= 2 THEN
          FAILED ("MIDDLE_M2'MANTISSA =" &
                  INTEGER'IMAGE(MIDDLE_M2'MANTISSA) );
     END IF;

     IF IDENT_INT (MIDDLE_M3'MANTISSA) /= 3 THEN
          FAILED ("MIDDLE_M3'MANTISSA =" &
                  INTEGER'IMAGE(MIDDLE_M3'MANTISSA) );
     END IF;

     IF IDENT_INT (MIDDLE_M15'MANTISSA) /= 15 THEN
          FAILED ("MIDDLE_M15'MANTISSA =" &
                  INTEGER'IMAGE(MIDDLE_M15'MANTISSA) );
     END IF;

     IF IDENT_INT (MIDDLE_M16'MANTISSA) /= 16 THEN
          FAILED ("MIDDLE_M16'MANTISSA =" &
                  INTEGER'IMAGE(MIDDLE_M16'MANTISSA) );
     END IF;

     IF IDENT_INT (LIKE_DURATION_M23'MANTISSA) /= 23 THEN
          FAILED ("LIKE_DURATION_M23'MANTISSA =" &
                  INTEGER'IMAGE(LIKE_DURATION_M23'MANTISSA) );
     END IF;

     IF IDENT_INT (DECIMAL_M18'MANTISSA) /= 18 THEN
          FAILED ("DECIMAL_M18'MANTISSA =" &
                  INTEGER'IMAGE(DECIMAL_M18'MANTISSA) );
     END IF;

     IF IDENT_INT (DECIMAL_M4'MANTISSA) /= 4 THEN
          FAILED ("DECIMAL_M4'MANTISSA =" &
                  INTEGER'IMAGE(DECIMAL_M4'MANTISSA) );
     END IF;

     -------------------------------------------------------------------

     IF IDENT_INT (ST_LEFT_EDGE_M6'MANTISSA) /= 6 THEN
          IF ST_LEFT_EDGE_M6'MANTISSA =
             IDENT_INT (MIDDLE_M15'MANTISSA) THEN
               FAILED ("ST_LEFT_EDGE_M6'MANTISSA = " &
                       "MIDDLE_15'MANTISSA =" &
                       INTEGER'IMAGE(ST_LEFT_EDGE_M6'MANTISSA) );
          ELSE
               FAILED ("ST_LEFT_EDGE_M6'MANTISSA =" &
                       INTEGER'IMAGE(ST_LEFT_EDGE_M6'MANTISSA) );
          END IF;
     END IF;

     IF IDENT_INT (ST_MIDDLE_M14'MANTISSA) /= 14 THEN
          IF ST_MIDDLE_M14'MANTISSA =
             IDENT_INT (MIDDLE_M16'MANTISSA) THEN
               FAILED ("ST_MIDDLE_M14'MANTISSA = " &
                       "MIDDLE_M16'MANTISSA =" &
                       INTEGER'IMAGE(ST_MIDDLE_M14'MANTISSA) );
          ELSE
               FAILED ("ST_MIDDLE_M14'MANTISSA =" &
                       INTEGER'IMAGE(ST_MIDDLE_M14'MANTISSA) );
          END IF;
     END IF;

     IF IDENT_INT (ST_MIDDLE_M2'MANTISSA) /= 2 THEN
          IF ST_MIDDLE_M2'MANTISSA =
             IDENT_INT (LIKE_DURATION_M23'MANTISSA) THEN
               FAILED ("ST_MIDDLE_M2'MANTISSA = " &
                       "LIKE_DURATION_M23'MANTISSA =" &
                       INTEGER'IMAGE(ST_MIDDLE_M2'MANTISSA) );
          ELSE
               FAILED ("ST_MIDDLE_M2'MANTISSA =" &
                       INTEGER'IMAGE(ST_MIDDLE_M2'MANTISSA) );
          END IF;
     END IF;

     IF IDENT_INT (ST_MIDDLE_M3'MANTISSA) /= 3 THEN
          IF ST_MIDDLE_M3'MANTISSA =
             IDENT_INT (LIKE_DURATION_M23'MANTISSA) THEN
               FAILED ("ST_MIDDLE_M3'MANTISSA = " &
                       "LIKE_DURATION_M23'MANTISSA =" &
                       INTEGER'IMAGE(ST_MIDDLE_M3'MANTISSA) );
          ELSE
               FAILED ("ST_MIDDLE_M3'MANTISSA =" &
                       INTEGER'IMAGE(ST_MIDDLE_M3'MANTISSA) );
          END IF;
     END IF;

     IF IDENT_INT (ST_DECIMAL_M7'MANTISSA) /= 7 THEN
          IF ST_DECIMAL_M7'MANTISSA =
             IDENT_INT (DECIMAL_M18'MANTISSA) THEN
               FAILED ("ST_DECIMAL_M7'MANTISSA = " &
                       "DECIMAL_M18'MANTISSA =" &
                       INTEGER'IMAGE(ST_DECIMAL_M7'MANTISSA) );
          ELSE
               FAILED ("ST_DECIMAL_M7'MANTISSA =" &
                       INTEGER'IMAGE(ST_DECIMAL_M7'MANTISSA) );
          END IF;
     END IF;

     IF IDENT_INT (ST_DECIMAL_M3'MANTISSA) /= 3 THEN
          IF ST_DECIMAL_M3'MANTISSA =
             IDENT_INT (DECIMAL_M4'MANTISSA) THEN
               FAILED ("ST_DECIMAL_M3'MANTISSA = " &
                       "DECIMAL_M4'MANTISSA =" &
                       INTEGER'IMAGE(ST_DECIMAL_M3'MANTISSA) );
          ELSE
               FAILED ("ST_DECIMAL_M3'MANTISSA =" &
                       INTEGER'IMAGE(ST_DECIMAL_M3'MANTISSA) );
          END IF;
     END IF;

     RESULT;

END C35A03A;
