-- C35A03N.ADA

-- CHECK THAT FOR FIXED POINT TYPES THE MANTISSA ATTRIBUTE YIELDS THE
-- CORRECT VALUES.

-- CASE N: BASIC TYPES THAT FIT THE CHARACTERISTICS OF DURATION'BASE,
--         FOR GENERICS.

-- WRG 7/25/86

WITH REPORT; USE REPORT;
PROCEDURE C35A03N IS

     -- THE NAME OF EACH TYPE OR SUBTYPE ENDS WITH THAT TYPE'S
     -- 'MANTISSA VALUE.

     TYPE LEFT_OUT_M1       IS DELTA 0.25  RANGE -0.5 .. 0.5;
     TYPE LEFT_EDGE_M1      IS DELTA 0.5   RANGE -1.0 .. 1.0;
     TYPE RIGHT_EDGE_M1     IS DELTA 1.0   RANGE -2.0 .. 2.0;
     TYPE RIGHT_OUT_M1      IS DELTA 2.0   RANGE -4.0 .. 4.0;
     TYPE MIDDLE_M2         IS DELTA 0.5   RANGE -2.0 .. 2.0;
     TYPE MIDDLE_M3         IS DELTA 0.5   RANGE  0.0 .. 2.5;
     TYPE MIDDLE_M15        IS DELTA 2.0 **(-6) RANGE  -512.0 ..  512.0;
     TYPE MIDDLE_M16        IS DELTA 2.0 **(-6) RANGE -1024.0 .. 1024.0;
     TYPE LIKE_DURATION_M23 IS DELTA 0.020 RANGE -86_400.0 .. 86_400.0;
     TYPE DECIMAL_M18       IS DELTA 0.1   RANGE -10_000.0 .. 10_000.0;
     TYPE DECIMAL_M4        IS DELTA 100.0 RANGE   -1000.0 ..   1000.0;

     -------------------------------------------------------------------

     SUBTYPE ST_LEFT_EDGE_M6 IS MIDDLE_M15
          DELTA 2.0 ** (-6) RANGE IDENT_INT (1) * (-1.0) .. 1.0;
     SUBTYPE ST_MIDDLE_M14   IS MIDDLE_M16
          DELTA 2.0 ** (-5) RANGE -512.0 .. IDENT_INT (1) * 512.0;
     SUBTYPE ST_MIDDLE_M2    IS LIKE_DURATION_M23
          DELTA 0.5 RANGE -2.0 .. 2.0;
     SUBTYPE ST_MIDDLE_M3    IS LIKE_DURATION_M23
          DELTA 0.5 RANGE  0.0 .. 2.5;
     SUBTYPE ST_DECIMAL_M7   IS DECIMAL_M18
          DELTA  10.0 RANGE -1000.0 .. 1000.0;
     SUBTYPE ST_DECIMAL_M3   IS DECIMAL_M4
          DELTA 100.0 RANGE  -500.0 ..  500.0;

     -------------------------------------------------------------------

     GENERIC
          TYPE T IS DELTA <>;
     FUNCTION F RETURN INTEGER;

     FUNCTION F RETURN INTEGER IS
     BEGIN
          RETURN IDENT_INT (T'MANTISSA);
     END F;

     -------------------------------------------------------------------

     FUNCTION F_LEFT_OUT_M1       IS NEW F (LEFT_OUT_M1      );
     FUNCTION F_LEFT_EDGE_M1      IS NEW F (LEFT_EDGE_M1     );
     FUNCTION F_RIGHT_EDGE_M1     IS NEW F (RIGHT_EDGE_M1    );
     FUNCTION F_RIGHT_OUT_M1      IS NEW F (RIGHT_OUT_M1     );
     FUNCTION F_MIDDLE_M2         IS NEW F (MIDDLE_M2        );
     FUNCTION F_MIDDLE_M3         IS NEW F (MIDDLE_M3        );
     FUNCTION F_MIDDLE_M15        IS NEW F (MIDDLE_M15       );
     FUNCTION F_MIDDLE_M16        IS NEW F (MIDDLE_M16       );
     FUNCTION F_LIKE_DURATION_M23 IS NEW F (LIKE_DURATION_M23);
     FUNCTION F_DECIMAL_M18       IS NEW F (DECIMAL_M18      );
     FUNCTION F_DECIMAL_M4        IS NEW F (DECIMAL_M4       );
     FUNCTION F_ST_LEFT_EDGE_M6   IS NEW F (ST_LEFT_EDGE_M6  );
     FUNCTION F_ST_MIDDLE_M14     IS NEW F (ST_MIDDLE_M14    );
     FUNCTION F_ST_MIDDLE_M2      IS NEW F (ST_MIDDLE_M2     );
     FUNCTION F_ST_MIDDLE_M3      IS NEW F (ST_MIDDLE_M3     );
     FUNCTION F_ST_DECIMAL_M7     IS NEW F (ST_DECIMAL_M7    );
     FUNCTION F_ST_DECIMAL_M3     IS NEW F (ST_DECIMAL_M3    );

BEGIN

     TEST ("C35A03N", "CHECK THAT FOR FIXED POINT TYPES THE MANTISSA " &
                      "ATTRIBUTE YIELDS THE CORRECT VALUES - BASIC " &
                      "TYPES, GENERICS");

     IF F_LEFT_OUT_M1 /= 1 THEN
          FAILED ("GENERIC 'MANTISSA FOR LEFT_OUT_M1 =" &
                  INTEGER'IMAGE (F_LEFT_OUT_M1) );
     END IF;

     IF F_LEFT_EDGE_M1 /= 1 THEN
          FAILED ("GENERIC 'MANTISSA FOR LEFT_EDGE_M1 =" &
                  INTEGER'IMAGE (F_LEFT_EDGE_M1) );
     END IF;

     IF F_RIGHT_EDGE_M1 /= 1 THEN
          FAILED ("GENERIC 'MANTISSA FOR RIGHT_EDGE_M1 =" &
                  INTEGER'IMAGE (F_RIGHT_EDGE_M1) );
     END IF;

     IF F_RIGHT_OUT_M1 /= 1 THEN
          FAILED ("GENERIC 'MANTISSA FOR RIGHT_OUT_M1 =" &
                  INTEGER'IMAGE (F_RIGHT_OUT_M1) );
     END IF;

     IF F_MIDDLE_M2 /= 2 THEN
          FAILED ("GENERIC 'MANTISSA FOR MIDDLE_M2 =" &
                  INTEGER'IMAGE (F_MIDDLE_M2) );
     END IF;

     IF F_MIDDLE_M3 /= 3 THEN
          FAILED ("GENERIC 'MANTISSA FOR MIDDLE_M3 =" &
                  INTEGER'IMAGE (F_MIDDLE_M3) );
     END IF;

     IF F_MIDDLE_M15 /= 15 THEN
          FAILED ("GENERIC 'MANTISSA FOR MIDDLE_M15 =" &
                  INTEGER'IMAGE (F_MIDDLE_M15) );
     END IF;

     IF F_MIDDLE_M16 /= 16 THEN
          FAILED ("GENERIC 'MANTISSA FOR MIDDLE_M16 =" &
                  INTEGER'IMAGE (F_MIDDLE_M16) );
     END IF;

     IF F_LIKE_DURATION_M23 /= 23 THEN
          FAILED ("GENERIC 'MANTISSA FOR LIKE_DURATION_M23 =" &
                  INTEGER'IMAGE (F_LIKE_DURATION_M23) );
     END IF;

     IF F_DECIMAL_M18 /= 18 THEN
          FAILED ("GENERIC 'MANTISSA FOR DECIMAL_M18 =" &
                  INTEGER'IMAGE (F_DECIMAL_M18) );
     END IF;

     IF F_DECIMAL_M4 /= 4 THEN
          FAILED ("GENERIC 'MANTISSA FOR DECIMAL_M4 =" &
                  INTEGER'IMAGE (F_DECIMAL_M4) );
     END IF;

     -------------------------------------------------------------------

     IF F_ST_LEFT_EDGE_M6 /= 6 THEN
          FAILED ("GENERIC 'MANTISSA FOR ST_LEFT_EDGE_M6 =" &
                  INTEGER'IMAGE (F_ST_LEFT_EDGE_M6) );
     END IF;

     IF F_ST_MIDDLE_M14 /= 14 THEN
          FAILED ("GENERIC 'MANTISSA FOR ST_MIDDLE_M14 =" &
                  INTEGER'IMAGE (F_ST_MIDDLE_M14) );
     END IF;

     IF F_ST_MIDDLE_M2 /= 2 THEN
          FAILED ("GENERIC 'MANTISSA FOR ST_MIDDLE_M2 =" &
                  INTEGER'IMAGE (F_ST_MIDDLE_M2) );
     END IF;

     IF F_ST_MIDDLE_M3 /= 3 THEN
          FAILED ("GENERIC 'MANTISSA FOR ST_MIDDLE_M3 =" &
                  INTEGER'IMAGE (F_ST_MIDDLE_M3) );
     END IF;

     IF F_ST_DECIMAL_M7 /= 7 THEN
          FAILED ("GENERIC 'MANTISSA FOR ST_DECIMAL_M7 =" &
                  INTEGER'IMAGE (F_ST_DECIMAL_M7) );
     END IF;

     IF F_ST_DECIMAL_M3 /= 3 THEN
          FAILED ("GENERIC 'MANTISSA FOR ST_DECIMAL_M3 =" &
                  INTEGER'IMAGE (F_ST_DECIMAL_M3) );
     END IF;

     RESULT;

END C35A03N;
