-- C36172C.ADA

-- CHECK THAT NO EXCEPTION IS RAISED FOR A NULL ARRAY WHOSE DIFFERENCE
-- IN BOUNDS LIES OUTSIDE THE INDEX BASE TYPE.

-- JBG 6/5/85

WITH REPORT; USE REPORT;
PROCEDURE C36172C IS
BEGIN
     TEST ("C36172C", "CHECK THAT NO EXCEPTION IS RAISED FOR A NULL " &
                      "ARRAY WHOSE DIFFERENCE IN BOUNDS LIES OUTSIDE " &
                      "THE INDEX BASE TYPE");

     BEGIN
          DECLARE
               V : STRING (INTEGER'LAST .. -2);
          BEGIN
               IF NOT EQUAL (V'FIRST, V'FIRST) THEN
                    FAILED ("IMPOSSIBLE");
               END IF;
          END;
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               FAILED ("CONSTRAINT_ERROR RAISED");
          WHEN NUMERIC_ERROR =>
               FAILED ("NUMERIC_ERROR RAISED - SEE AI-00325");
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED");
     END;

     RESULT;
END C36172C;
