-- C36202A.ADA

-- OBJECTIVE:
--     CHECK THAT NUMERIC_ERROR/CONSTRAINT_ERROR MAY BE RAISED WHEN
--     A'LENGTH IS USED IN A CONTEXT WHICH REQUIRES AN INTEGER VALUE,
--     AND THE NUMBER OF COMPONENTS FOR A DIMENSION EXCEEDS
--     INTEGER'LAST.  THIS TEST IS FOR TYPE INTEGER.

-- HISTORY:
--     DAT 02/12/81
--     JBG 10/26/82
--     JBG 08/01/83
--     JWC 06/28/85  RENAMED FROM E36202A-B.ADA
--     EG  10/30/85  FIX NUMERIC_ERROR/CONSTRAINT_ERROR ACCORDING TO
--                   AI-00387.
--     JRK 06/24/86  FIXED COMMENTS ABOUT NUMERIC_ERROR/
--                   CONSTRAINT_ERROR.
--     JET 01/05/88  ADDED CODE TO PREVENT OPTIMIZATION.

WITH REPORT;
PROCEDURE C36202A IS

     USE REPORT;

     TYPE NULL_ARRAY IS ARRAY (1 .. 0) OF
          BOOLEAN RANGE TRUE .. FALSE;

BEGIN
     TEST ("C36202A", "CHECK WHETHER 'LENGTH OF LONG ARRAYS RAISES " &
                      "NUMERIC_ERROR/CONSTRAINT_ERROR");

     DECLARE
          TYPE AMAZE IS ARRAY (IDENT_INT (-1) .. INTEGER'LAST) OF
                        NULL_ARRAY;
          I : INTEGER;
     BEGIN
          I := AMAZE'LENGTH - INTEGER(7) ;

          IF EQUAL (I, I) THEN
               COMMENT ("NO EXCEPTION RAISED");
          END IF;

     EXCEPTION
          WHEN CONSTRAINT_ERROR => COMMENT ("CONSTRAINT_ERROR RAISED " &
                                            "BY 'LENGTH");
          WHEN NUMERIC_ERROR => COMMENT ("NUMERIC_ERROR RAISED " &
                                         "BY 'LENGTH");
          WHEN OTHERS => FAILED ("WRONG EXCEPTION 1");
     END;

     RESULT;

EXCEPTION
     WHEN NUMERIC_ERROR => COMMENT ("NUMERIC_ERROR RAISED WHEN ARRAY " &
                                    "TYPE WAS DECLARED");
                           RESULT;
     WHEN CONSTRAINT_ERROR => COMMENT ("CONSTRAINT_ERROR RAISED WHEN " &
                                       "ARRAY TYPE WAS DECLARED");
                              RESULT;
     WHEN STORAGE_ERROR => FAILED ("STORAGE_ERROR RAISED FOR LONG " &
                                   "ARRAY TYPE WITH NULL COMPONENTS");
                           RESULT;
     WHEN OTHERS => FAILED ("OTHER EXCEPTION RAISED WHEN ARRAY " &
                            "TYPE WAS DECLARED");
                    RESULT;
END C36202A;
