-- C36202B.ADA

-- OBJECTIVE:
--     CHECK THAT NUMERIC_ERROR/CONSTRAINT_ERROR MAY BE RAISED
--     WHEN A'LENGTH IS USED IN A CONTEXT WHICH REQUIRES AN INTEGER
--     VALUE, AND THE NUMBER OF COMPONENTS FOR A DIMENSION EXCEEDS
--     INTEGER'LAST.  THIS TEST CHECKS THE LARGEST INTEGER TYPE
--     SUPPORTED BY THE IMPLEMENTATION.

-- HISTORY:
--     DAT 02/12/81
--     JBG 10/26/82
--     JBG 08/01/83
--     JWC 06/28/85  RENAMED FROM E36202B-B.ADA
--     EG  10/30/85  FIX NUMERIC_ERROR/CONSTRAINT_ERROR ACCORDING TO
--                   AI-00387.
--     JRK 06/24/86  FIXED COMMENTS ABOUT NUMERIC_ERROR/
--                   CONSTRAINT_ERROR.
--     JET 01/05/88  ADDED CODE TO PREVENT OPTIMIZATION.

WITH REPORT; WITH SYSTEM;
PROCEDURE C36202B IS

     USE REPORT; USE SYSTEM;

     TYPE NULL_ARRAY IS ARRAY (1 .. 0) OF
          BOOLEAN RANGE TRUE .. FALSE;
     TYPE LARGEST IS RANGE SYSTEM.MIN_INT..SYSTEM.MAX_INT;

     FUNCTION IDENT (X : LARGEST) RETURN LARGEST IS
     BEGIN
          IF EQUAL (3,3) THEN
               RETURN X;
          ELSE
               RETURN LARGEST(0);
          END IF;
     END IDENT;

BEGIN
     TEST ("C36202B", "CHECK WHETHER 'LENGTH OF LONG ARRAYS RAISES " &
                      "NUMERIC_ERROR/CONSTRAINT_ERROR FOR LARGEST " &
                      "INTEGER TYPE");

     DECLARE
          TYPE AMAZE IS ARRAY (LARGEST(IDENT_INT(-1))..LARGEST'LAST) OF
                        NULL_ARRAY;
          I : LARGEST;
     BEGIN
          I := AMAZE'LENGTH - LARGEST(7) ;

          IF IDENT(I) = I THEN
               COMMENT ("NO EXCEPTION RAISED");
          END IF;

     EXCEPTION
          WHEN CONSTRAINT_ERROR => COMMENT ("CONSTRAINT_ERROR " &
                                            "RAISED BY 'LENGTH");
          WHEN NUMERIC_ERROR => COMMENT ("NUMERIC_ERROR RAISED " &
                                         "BY 'LENGTH");
          WHEN OTHERS => FAILED ("WRONG EXCEPTION 1");
     END;

     RESULT;

EXCEPTION
     WHEN NUMERIC_ERROR => COMMENT ("NUMERIC_ERROR RAISED WHEN ARRAY " &
                                    "TYPE WAS DECLARED");
                           RESULT;
     WHEN CONSTRAINT_ERROR => COMMENT ("CONSTRAINT_ERROR RAISED WHEN " &
                                       "ARRAY TYPE WAS DECLARED");
                              RESULT;
     WHEN STORAGE_ERROR => FAILED ("STORAGE_ERROR RAISED FOR LONG " &
                                   "ARRAY TYPE WITH NULL COMPONENTS");
                           RESULT;
     WHEN OTHERS => FAILED ("OTHER EXCEPTION RAISED WHEN ARRAY " &
                            "TYPE WAS DECLARED");
                    RESULT;
END C36202B;
