-- C36302A.ADA

-- CHECK THAT A STRING VARIABLE MAY BE DECLARED WITH AN INDEX
-- STARTING WITH AN INTEGER GREATER THAN 1.

-- DAT 2/17/81
-- JWC 6/28/85   RENAMED TO -AB

WITH REPORT;
PROCEDURE C36302A IS

     USE REPORT;

     S5 : STRING (5 .. 10);
     SX : STRING (INTEGER'LAST - 5 .. INTEGER'LAST);

BEGIN
     TEST ("C36302A", "STRING VARIABLE INDICES NEEDN'T START AT 1");

     IF S5'FIRST /= 5
     OR S5'LAST /= 10
     OR S5'LENGTH /= 6
     OR SX'FIRST /= INTEGER'LAST - 5
     OR SX'LAST /= INTEGER'LAST
     OR SX'LENGTH /= 6
     THEN
          FAILED ("WRONG STRING ATTRIBUTES");
     END IF;

     RESULT;
END C36302A;
