-- C36301B.ADA

-- CHECK THAT PREDEFINED STRING ATTRIBUTES ARE CORRECTLY IMPLEMENTED.

-- CASE B: STRING OF LENGTH INTEGER'LAST

-- DAT 2/17/81
-- JBG 12/28/82

WITH REPORT;
PROCEDURE C36301B IS

     USE REPORT;

     SUBTYPE STR2 IS STRING (1..INTEGER'LAST);

BEGIN
     TEST("C36301B", "CHECK ATTRIBUTES OF LONGEST STRING");

     IF STR2'FIRST /= 1 THEN
          FAILED ("STR'FIRST NOT 1");
     END IF;

     IF STR2'LAST /= INTEGER'LAST THEN
          FAILED ("STR'LAST NOT INTEGER'LAST");
     END IF;

     IF STR2'LENGTH /= INTEGER'LAST THEN
          FAILED ("'LENGTH NOT INTEGER'LAST");
     END IF;

     RESULT;
END C36301B;
