-- C37003B.ADA

-- OBJECTIVE:
--     CHECK THAT FOR A RECORD WITH MULTIPLE DISCRIMINANTS WHICH HAVE
--     DEFAULT EXPRESSIONS, THE EXPRESSIONS ARE EVALUATED ONCE FOR
--     EACH DISCRIMINANT IN THE ASSOCIATION.

-- HISTORY:
--     DHH 08/04/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C37003B IS

     X : INTEGER := 0;

     FUNCTION F1 RETURN INTEGER IS
     BEGIN
          X := X + 1;
          RETURN X;
     END F1;

BEGIN
     TEST("C37003B", "CHECK THAT FOR A RECORD WITH MULTIPLE " &
                     "DISCRIMINANTS WHICH HAVE DEFAULT EXPRESSIONS, " &
                     "THE  EXPRESSIONS ARE EVALUATED ONCE FOR EACH " &
                     "DISCRIMINANT IN THE ASSOCIATION");

     DECLARE
          TYPE REC(D1, D2, D3, D4, D5 : INTEGER := F1) IS
               RECORD
                    Y : INTEGER := (D1 + D2 + D3 + D4 + D5);
               END RECORD;

          REC_F1 : REC;

     BEGIN
          IF REC_F1.Y /= IDENT_INT(15) THEN
               FAILED("MULTIPLE DISCRIMINANTS NOT EVALUATED " &
                      "SEPARATELY");
          END IF;
     END;

     RESULT;
END C37003B;
