-- C37105A.ADA

-- CHECK THAT RECORDS WITH ONLY DISCRIMINANTS ARE OK.

-- DAT 5/18/81
-- JWC 6/28/85   RENAMED TO -AB

WITH REPORT; USE REPORT;

PROCEDURE C37105A IS
BEGIN
     TEST ("C37105A", "RECORDS WITH ONLY DISCRIMINANTS");

     DECLARE
          TYPE R1 (D : BOOLEAN) IS RECORD
               NULL; END RECORD;
          TYPE R2 (D, E : BOOLEAN) IS RECORD
               NULL; END RECORD;
          TYPE R3 (A,B,C,D : INTEGER; W,X,Y,Z : CHARACTER) IS
               RECORD NULL; END RECORD;
          OBJ1 : R1 (IDENT_BOOL(TRUE));
          OBJ2 : R2 (IDENT_BOOL(FALSE), IDENT_BOOL(TRUE));
          OBJ3 : R3 (1,2,3,4,'A','B','C',IDENT_CHAR('D'));
     BEGIN
          IF OBJ1 = (D => (FALSE))
          OR OBJ2 /= (FALSE, (TRUE))
          OR OBJ3 /= (1,2,3,4,'A','B','C',('D'))
          THEN FAILED ("DISCRIMINANT-ONLY RECORDS DON'T WORK");
          END IF;
     END;

     RESULT;
END C37105A;
