-- C37411A.ADA

-- OBJECTIVE:
--     CHECK THAT THE OPERATIONS OF ASSIGNMENT, COMPARISON, MEMBERSHIP
--     TESTS, QUALIFICATION, TYPE CONVERSION, 'BASE, 'SIZE AND 'ADDRESS,
--     ARE DEFINED FOR NULL RECORDS.

-- HISTORY:
--     DHH 03/04/88 CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE C37411A IS
     TYPE S IS
          RECORD
               NULL;
          END RECORD;

     SUBTYPE SS IS S;

     U,V,W : S;
     X : SS;

BEGIN

     TEST("C37411A", "CHECK THAT THE OPERATIONS OF ASSIGNMENT, " &
                     "COMPARISON, MEMBERSHIP TESTS, QUALIFICATION, " &
                     "TYPE CONVERSION, 'BASE, 'SIZE AND 'ADDRESS, " &
                     "ARE DEFINED FOR NULL RECORDS");
     IF S'BASE'SIZE < SS'SIZE THEN
          FAILED("SUBTYPE SIZE GREATER THAN BASE SIZE");
     END IF;

     U := W;
     IF U /= W THEN
          FAILED("EQUALITY/ASSIGNMENT DOES NOT PERFORM CORRECTLY");
     END IF;

     IF V NOT IN S THEN
          FAILED("MEMBERSHIP DOES NOT PERFORM CORRECTLY");
     END IF;

     IF X /= SS(V) THEN
          FAILED("TYPE CONVERSION DOES NOT PERFORM CORRECTLY");
     END IF;

     IF S'(U) /= S'(W) THEN
          FAILED("QUALIFIED EXPRESSION DOES NOT PERFORM CORRECTLY");
     END IF;

     IF X'SIZE /= V'SIZE THEN
          FAILED("'BASE'SIZE DOES NOT PERFORM CORRECTLY WHEN PREFIX " &
                 "IS AN OBJECT");
     END IF;

     IF X'ADDRESS = V'ADDRESS THEN
          COMMENT("NULL RECORDS HAVE THE SAME ADDRESS");
     ELSE
          COMMENT("NULL RECORDS DO NOT HAVE THE SAME ADDRESS");
     END IF;

     RESULT;
END C37411A;
