-- C38004A.ADA
 
-- CHECK THAT AN INDEX OR DISCRIMINANT CONSTRAINT FOR AN ACCESS TYPE
-- CAN REFERENCE A DISCRIMINANT VALUE IN A RECORD COMPONENT
-- DECLARATION AND THAT SLICING AND INDEXING CAN BE APPLIED TO SUCH
-- A COMPONENT.

-- ASL 6/24/81
 
WITH REPORT;
PROCEDURE C38004A IS
 
     USE REPORT;
 
     TYPE HSTRING IS ACCESS STRING;
 
     TYPE TEXT(L : INTEGER) IS
          RECORD
               VALUE : HSTRING(1..L);
          END RECORD;
 
     T : TEXT(IDENT_INT(6));
 
BEGIN
 
     TEST ("C38004A", "ACCESS TYPE CONSTRAINT CAN REFERENCE " &
               "DISCRIMINANT VALUE IN RECORD COMPONENT DECLARATION " &
               "AND SLICING AND INDEXING CAN BE APPLIED");
 
     T := (6,VALUE => NEW STRING(1..IDENT_INT(6)));
     T.VALUE.ALL := IDENT_STR("ABCDEF");
 
     IF NOT EQUAL(3,3) THEN
          T.VALUE.ALL := ("ZZZZZZ");
     END IF;
 
     IF T.VALUE.ALL /= "ABCDEF" THEN
          FAILED ("ERROR IN ASSIGNING VALUE TO COMPONENT");
     END IF;
 
     IF T.VALUE(3..5)  /= "CDE" THEN
          FAILED("ERROR IN SLICING COMPONENT");
     END IF;
 
     IF T.VALUE(4) /= 'D' THEN
          FAILED ("ERROR IN INDEXING COMPONENT");
     END IF;
 
     RESULT;
 
END C38004A;
