-- C38004B.ADA
 
-- CHECK THAT AN INDEX OR DISCRIMINANT CONSTRAINT FOR A GENERIC
-- FORMAL ACCESS TYPE CAN REFERENCE A DISCRIMINANT VALUE IN A 
-- RECORD COMPONENT DECLARATION AND THAT SLICING AND INDEXING 
-- CAN BE APPLIED TO SUCH A COMPONENT.

-- AH  9/2/86
 
WITH REPORT; USE REPORT;
PROCEDURE C38004B IS

     TYPE P_HSTRING IS ACCESS STRING;

     GENERIC
          TYPE HSTRING IS ACCESS STRING;
     PACKAGE P IS 
          TYPE TEXT(L : INTEGER) IS
               RECORD
                    VALUE : HSTRING(1..L);
               END RECORD;
 
          T : TEXT(IDENT_INT(6));
     END P;

PACKAGE NP IS NEW P (HSTRING => P_HSTRING);

USE NP;
BEGIN
 
     TEST ("C38004B", "ACCESS TYPE CONSTRAINT CAN REFERENCE " &
               "DISCRIMINANT VALUE IN RECORD COMPONENT DECLARATION " &
               "AND SLICING AND INDEXING CAN BE APPLIED");
 
     T := (6,VALUE => NEW STRING(1..IDENT_INT(6)));
     T.VALUE.ALL := IDENT_STR("ZZZZZZ");
 
     IF EQUAL(3,3) THEN
          T.VALUE.ALL := ("ABCDEF");
     END IF;
 
     IF T.VALUE.ALL /= "ABCDEF" THEN
          FAILED ("ERROR IN ASSIGNING VALUE TO COMPONENT");
     END IF;
 
     IF T.VALUE(3..5)  /= "CDE" THEN
          FAILED("ERROR IN SLICING COMPONENT");
     END IF;
 
     IF T.VALUE(4) /= 'D' THEN
          FAILED ("ERROR IN INDEXING COMPONENT");
     END IF;
 
     RESULT;
 
END C38004B;
