-- C38006A.ADA

-- CHECK THAT OBJECTS ACCESSED BY CONSTANTS CAN BE MODIFIED.

-- DAT 3/6/81
-- SPS 10/25/82

WITH REPORT; USE REPORT;

PROCEDURE C38006A IS

     TYPE AI IS ACCESS INTEGER;

     C : CONSTANT AI := NEW INTEGER'(1);

BEGIN
     TEST ("C38006A", "OBJECTS ACCESSED BY CONSTANTS MAY BE ASSIGNED");

     FOR I IN 1 .. 10 LOOP
          IF C.ALL /= I AND I > 1 THEN
               FAILED ("OBJECT ACCESSED THRU CONSTANT NOT CHANGED");
               EXIT;
          END IF;
          C.ALL := C.ALL + 1;
     END LOOP;

     RESULT;
END C38006A;
