-- C38108C2.ADA

-- PACKAGE BODY FOR USE WITH C38108C1M.
-- SPECIFICATION IS IN C38108C0.

-- AH  8/20/86

PACKAGE BODY C38108C0 IS
     TYPE INC (D : INTEGER) IS
          RECORD
               C : INTEGER;
          END RECORD;
     
     PROCEDURE ASSIGN (X : IN INTEGER; Y : IN OUT L) IS
     BEGIN
          Y := NEW INC(1);
          Y.C := X;
     END ASSIGN;

     FUNCTION "=" (X, Y : IN L) RETURN BOOLEAN IS
     BEGIN
          RETURN (X.C = Y.C);          
     END "=";

END C38108C0;
