-- C38108D1.ADA

-- PACKAGE BODY SUBUNIT USED WITH C38108D0M.

-- AH  8/20/86

SEPARATE (C38108D0M)
PACKAGE BODY C38108D1 IS
     TYPE INC (D : INTEGER) IS
          RECORD
               C : INTEGER;
          END RECORD;
     
     PROCEDURE ASSIGN (X : IN INTEGER; Y : IN OUT L) IS
     BEGIN
          Y := NEW INC(1);
          Y.C := X;
     END ASSIGN;

     FUNCTION "=" (X, Y : IN L) RETURN BOOLEAN IS
     BEGIN
          RETURN (X.C = Y.C);          
     END "=";

END C38108D1;
