-- C38102C.ADA

-- OBJECTIVE:
--     CHECK THAT INCOMPLETE TYPES CAN BE FIXED.

-- HISTORY:
--     DAT 03/24/81  CREATED ORIGINAL TEST.
--     SPS 10/25/82
--     BCB 10/21/87  CHANGED HEADER TO STANDARD FORMAT.  CHANGED VARIOUS
--                   VALUES TO CORRECT CONSTRAINT PROBLEMS.  CHANGED
--                   THE VALUE OF F'DELTA, USING A POWER OF TWO.

WITH REPORT; USE REPORT;

PROCEDURE C38102C IS
BEGIN
     TEST ("C38102C", "INCOMPLETE TYPE CAN BE FIXED");

     DECLARE

          TYPE F;
          TYPE G;
          TYPE AF IS ACCESS F;
          TYPE F IS DELTA 0.25 RANGE -2.0 .. 2.0;
          TYPE G IS NEW F RANGE -1.0 .. 1.5;
          TYPE AG IS ACCESS G RANGE -0.75 .. 1.25;

          XF : AF := NEW F '(1.0);
          XG : AG := NEW G '(G (XF.ALL/2));

     BEGIN
          IF XG.ALL NOT IN G THEN
               FAILED ("ACCESS TO FIXED");
          END IF;
     END;

     RESULT;
END C38102C;
