-- C38108D0M.ADA

-- CHECK THAT AN INCOMPLETE TYPE CAN BE DECLARED IN THE PRIVATE PART OF
-- A PACKAGE, WITH THE FULL DECLARATION OCCURRING LATER IN A 
-- PACKAGE BODY SUBUNIT.

-- OTHER FILES: C38108D1.ADA (PACKAGE BODY SUBUNIT.)

-- AH  8/20/86

WITH REPORT; USE REPORT;

PROCEDURE C38108D0M IS
     PACKAGE C38108D1 IS
          TYPE L IS LIMITED PRIVATE;
          PROCEDURE ASSIGN (X : IN INTEGER; Y : IN OUT L);
          FUNCTION "=" (X, Y : IN L) RETURN BOOLEAN;
     PRIVATE
          TYPE INC (D : INTEGER);
          TYPE L IS ACCESS INC;
     END C38108D1;

     PACKAGE BODY C38108D1 IS SEPARATE;

USE C38108D1;
BEGIN

     TEST ("C38108D", "CHECK THAT INCOMPLETE TYPE CAN BE DECLARED IN " &
                      "PRIVATE PART WITH FULL DECLARATION IN " &
                      "A PACKAGE BODY SUBUNIT");

DECLARE
     VAL_1, VAL_2 : L;
BEGIN
     ASSIGN (2, VAL_1);
     ASSIGN (2, VAL_2);
     IF NOT "=" (VAL_1, VAL_2) THEN
          FAILED ("INCOMPLETE TYPE NOT FULLY DECLARED");
     END IF;
END;

     RESULT;
END C38108D0M;
