-- C38102D.ADA

-- CHECK THAT AN INCOMPLETE TYPE CAN BE REDECLARED AS A TASK TYPE.

-- AH    8/14/86

WITH REPORT; USE REPORT;
PROCEDURE C38102D IS
     GLOBAL : INTEGER := 0;
BEGIN
     TEST("C38102D", "INCOMPLETE TYPES CAN BE TASKS");
     DECLARE
          TYPE T1;
          TASK TYPE T1 IS
               ENTRY E(LOCAL : IN OUT INTEGER);
          END T1;
          T1_OBJ : T1;
          TASK BODY T1 IS
          BEGIN
               ACCEPT E(LOCAL : IN OUT INTEGER) DO
                    LOCAL := IDENT_INT(2);
               END E;
          END T1;
     BEGIN
          T1_OBJ.E(GLOBAL);
     END;

     IF GLOBAL /= IDENT_INT(2) THEN
          FAILED ("TASK NOT EXECUTED");
     END IF;
     RESULT;
END C38102D;
