-- C38108C0.ADA

-- SPECIFICATION OF LIBRARY PACKAGE USED WITH C38108C1M.

-- AH  8/20/86

PACKAGE C38108C0 IS
     TYPE L IS LIMITED PRIVATE;
     PROCEDURE ASSIGN (X : IN INTEGER; Y : IN OUT L);
     FUNCTION "=" (X, Y : IN L) RETURN BOOLEAN;
PRIVATE
     TYPE INC (D : INTEGER);
     TYPE L IS ACCESS INC;
END C38108C0;
