-- C38108C1M.ADA

-- CHECK THAT AN INCOMPLETE TYPE CAN BE DELCARED IN A SEPARATELY
-- COMPILED PACKAGE SPECIFICATION AND ITS FULL DECLARATION CAN LATER BE 
-- GIVEN IN A SEPARATELY COMPILED BODY.

-- AH  8/20/86

-- C38108C0    THE PACKAGE SPECIFICATION.
-- C38108C1M   THE MAIN PROGRAM.
-- C38108C2    THE PACKAGE BODY.

WITH REPORT; USE REPORT;
WITH C38108C0; USE C38108C0;
PROCEDURE C38108C1M IS
     VAL_1, VAL_2 : L;
BEGIN

     TEST ("C38108C", "CHECK THAT INCOMPLETE TYPE CAN BE DECLARED IN " &
                      "PRIVATE PART WITHOUT FULL DECLARATION - " &
                      "LIBRARY PACKAGE");

     ASSIGN (2, VAL_1);
     ASSIGN (2, VAL_2);
     IF NOT "=" (VAL_1, VAL_2) THEN
          FAILED ("INCOMPLETE TYPE NOT FULLY DECLARED");
     END IF;

     RESULT;
END C38108C1M;
