-- C39008A.ADA

-- OBJECTIVE:
--     CHECK THAT PROGRAM_ERROR IS RAISED BY AN ATTEMPT TO ACTIVATE
--     A TASK BEFORE ITS BODY HAS BEEN ELABORATED.  CHECK THE CASE IN
--     WHICH A TASK VARIABLE IS DECLARED IN A PACKAGE SPECIFICATION AND
--     THE PACKAGE BODY OCCURS BEFORE THE TASK BODY.

-- HISTORY:
--     BCB 01/21/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C39008A IS

BEGIN
     TEST ("C39008A", "CHECK THAT PROGRAM_ERROR IS RAISED BY AN " &
                      "ATTEMPT TO ACTIVATE A TASK BEFORE ITS BODY " &
                      "HAS BEEN ELABORATED.  CHECK THE CASE IN WHICH " &
                      "A TASK VARIABLE IS DECLARED IN A PACKAGE " &
                      "SPECIFICATION AND THE PACKAGE BODY OCCURS " &
                      "BEFORE THE TASK BODY");

     BEGIN
          DECLARE
               TASK TYPE T;

               PACKAGE P IS
                    X : T;
               END P;

               PACKAGE BODY P IS
               END P;                                  -- PROGRAM_ERROR.

               TASK BODY T IS
               BEGIN
                    COMMENT ("TASK MESSAGE");
               END T;
          BEGIN
               FAILED ("PROGRAM_ERROR WAS NOT RAISED");
          END;
     EXCEPTION
          WHEN PROGRAM_ERROR =>
               COMMENT ("PROGRAM_ERROR WAS RAISED");
          WHEN OTHERS =>
               FAILED ("AN EXCEPTION OTHER THAN PROGRAM_ERROR WAS " &
                       "RAISED");
     END;

     RESULT;
END C39008A;
