-- C39006C1.ADA

-- PACKAGE BODY SUBUNIT FOR C39006C0M.ADA.

-- TBN  8/19/86

SEPARATE (C39006C0M)
PACKAGE BODY C39006C1 IS
BEGIN
     IF VAR = IDENT_INT(1) THEN
          ADD1 (VAR);
          FAILED ("PROGRAM_ERROR NOT RAISED");
     END IF;
EXCEPTION
     WHEN PROGRAM_ERROR =>
          NULL;
     WHEN OTHERS =>
          FAILED ("UNEXPECTED EXCEPTION RAISED");
END C39006C1;
