-- C39006C0M.ADA

-- CHECK THAT PROGRAM_ERROR IS RAISED IF AN ATTEMPT IS MADE TO CALL A
-- SUBPROGRAM WHOSE BODY HAS NOT YET BEEN ELABORATED.  CHECK THE
-- FOLLOWING:
--     D) THE SUBPROGRAM IS CALLED DURING ELABORATION OF AN OPTIONAL
--        PACKAGE BODY SUBUNIT THAT IS IN C39006C1.ADA.

-- SEPARATE FILES ARE:
--     C39006C0M     THE MAIN PROCEDURE.
--     C39006C1      A SUBUNIT PACKAGE BODY.

-- TBN  8/19/86
-- LDC  5/26/88   CHANGED TEST NAME PARAMETER FROM C39006C0M TO
--                C39006C IN THE TEST CALL.

WITH REPORT; USE REPORT;
PROCEDURE C39006C0M IS

     PACKAGE CALL_TEST_FIRST IS
     END CALL_TEST_FIRST;

     PACKAGE BODY CALL_TEST_FIRST IS
     BEGIN
          TEST ("C39006C", "CHECK THAT PROGRAM_ERROR IS RAISED IF " &
                             "THE SUBPROGRAM WHOSE BODY HAS NOT BEEN " &
                             "ELABORATED IS CALLED DURING " &
                             "ELABORATION OF AN OPTIONAL PACKAGE " &
                             "BODY SUBUNIT");
     END CALL_TEST_FIRST;

     PROCEDURE ADD1 (A : IN OUT INTEGER);

     PACKAGE C39006C1 IS
          VAR : INTEGER := IDENT_INT(1);
     END C39006C1;

     PACKAGE BODY C39006C1 IS SEPARATE;

     PROCEDURE ADD1 (A : IN OUT INTEGER) IS
     BEGIN
          A := A + IDENT_INT(1);
     END ADD1;

BEGIN
     RESULT;
END C39006C0M;
