-- C39006F3M.ADA

-- CHECK THAT NO PROGRAM_ERROR IS RAISED IF A SUBPROGRAM'S BODY HAS BEEN
-- ELABORATED BEFORE IT IS CALLED.  CHECK THE FOLLOWING:
--     B) FOR A SUBPROGRAM LIBRARY UNIT USED IN ANOTHER UNIT, NO
--        PROGRAM_ERROR IS RAISED IF PRAGMA ELABORATE NAMES THE
--        SUBPROGRAM.

-- SEPARATE FILES ARE:
--      C39006F0     A LIBRARY FUNCTION.
--      C39006F1     A LIBRARY PACKAGE SPECIFICATION.
--      C39006F2     A LIBRARY PACKAGE BODY.
--      C39006F3M    THE MAIN PROCEDURE.
 
-- TBN  8/22/86

WITH C39006F1;
WITH REPORT; USE REPORT;

PROCEDURE C39006F3M IS
BEGIN
     RESULT;
END C39006F3M;
