-- C39006G.ADA

-- OBJECTIVE:
--     CHECK THAT PROGRAM_ERROR IS RAISED BY AN ATTEMPT TO CALL A
--     SUBPROGRAM WHOSE BODY IS NOT YET ELABORATED.  USE A PACKAGE
--     WITH OPTIONAL BODY, WHERE THE SUBPROGRAM IS CALLED IN THE BODY.

-- HISTORY:
--     BCB 08/01/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C39006G IS

     PROCEDURE INIT (X : IN OUT INTEGER);

     PACKAGE P IS
     END P;

     PACKAGE BODY P IS
          X : INTEGER := IDENT_INT(5);
     BEGIN
          TEST ("C39006G", "CHECK THAT PROGRAM_ERROR IS RAISED BY " &
                           "AN ATTEMPT TO CALL A SUBPROGRAM WHOSE " &
                           "BODY IS NOT YET ELABORATED.  USE A " &
                           "PACKAGE WITH OPTIONAL BODY, WHERE THE " &
                           "SUBPROGRAM IS CALLED IN THE BODY");
          INIT(X);
          FAILED ("NO EXCEPTION RAISED");
          IF X /= IDENT_INT(10) THEN
               COMMENT ("TOTALLY IRRELEVANT");
          END IF;
          RESULT;
     EXCEPTION
          WHEN PROGRAM_ERROR =>
               RESULT;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION WAS RAISED");
               RESULT;
     END P;

     PROCEDURE INIT (X : IN OUT INTEGER) IS
     BEGIN
          X := IDENT_INT(10);
     END INIT;

BEGIN
     NULL;
END C39006G;
