-- C39005A.ADA

-- OBJECTIVE:
--     CHECK THAT A SUBPROGRAM DECLARATION, SINGLE TASK DECLARATION,
--     TASK TYPE DECLARATION, USE CLAUSE, PACKAGE DECLARATION, GENERIC
--     DECLARATION, AND GENERIC INSTANTIATION ARE ALLOWED AFTER THE
--     OCCURRENCE OF A BODY.

-- HISTORY:
--     TBN  08/12/86  CREATED ORIGINAL TEST.
--     VCL  10/26/87  MODIFIED THIS HEADER; ADDED THE OTHER FIVE TYPES
--                    OF BODIES SO THAT ALL SIX TYPES OF BODIES ARE
--                    INCLUDED IN THIS TEST.
--     LDC  08/22/88  INSERTED PRAGMA ELABORATE (REPORT).

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);

PACKAGE C39005A_INIT IS END C39005A_INIT;

PACKAGE BODY C39005A_INIT IS
BEGIN
     TEST ("C39005A", "CHECK THAT A SUBPROGRAM DECLARATION, SINGLE " &
                      "TASK DECLARATION, TASK TYPE DECLARATION, USE " &
                      "CLAUSE, PACKAGE DECLARATION, GENERIC " &
                      "DECLARATION, AND GENERIC INSTANTIATION ARE " &
                      "ALLOWED AFTER THE OCCURRENCE OF A BODY");
END C39005A_INIT;

WITH C39005A_INIT;
WITH REPORT; USE REPORT;
PROCEDURE C39005A IS
     FUNCTION FUNC_OB RETURN INTEGER IS
     BEGIN
          RETURN IDENT_INT (1);
     END FUNC_OB;

     PACKAGE PACK_OB IS
          X : INTEGER := 0;
     END PACK_OB;

     PACKAGE BODY PACK_OB IS
     BEGIN
          X := IDENT_INT(2);
     END PACK_OB;

     TASK TASK_OB IS
          ENTRY E (X : OUT INTEGER);
     END TASK_OB;

     TASK BODY TASK_OB IS
     BEGIN
          ACCEPT E (X : OUT INTEGER)  DO
               X := IDENT_INT (3);
          END E;
     END TASK_OB;

     FUNCTION C39005A_FUNC_OB RETURN INTEGER;

     FUNCTION C39005A_FUNC_OB RETURN INTEGER IS SEPARATE;

     PACKAGE C39005A_PACK_OB IS
          X : INTEGER;
     END C39005A_PACK_OB;

     PACKAGE BODY C39005A_PACK_OB IS SEPARATE;

     TASK C39005A_TASK_OB IS
          ENTRY E (X : OUT INTEGER);
     END C39005A_TASK_OB;

     TASK BODY C39005A_TASK_OB IS SEPARATE;

     PROCEDURE ADD1 (X : IN OUT INTEGER);

     PROCEDURE ADD1 (X : IN OUT INTEGER) IS
     BEGIN
          X := X + IDENT_INT(1);
     END ADD1;

     FUNCTION INIT RETURN INTEGER IS
     BEGIN
          RETURN (IDENT_INT(0));
     END INIT;

     TASK T1;

     TASK BODY T1 IS
     BEGIN
          IF INIT /= 0 THEN
               FAILED ("INCORRECT RESULTS FROM FUNCTION INIT");
          END IF;
     END T1;

     PACKAGE P IS
          A : INTEGER := 1;
     END P;

     USE P;

     TASK TYPE T2 IS
          ENTRY E;
     END T2;

     TASK BODY T2 IS
     BEGIN
          ACCEPT E DO
               IF A /= 1 THEN
                    FAILED ("INCORRECT RESULTS FROM USE CLAUSE");
               END IF;
          END E;
     END T2;

     GENERIC
          S : STRING;
     PROCEDURE PROC1;

     PROCEDURE PROC1 IS
     BEGIN
          IF S /= "WHAT" THEN
               FAILED ("INCORRECT RESULTS FROM INSTANTIATION");
          END IF;
     END PROC1;

     PROCEDURE PROC2 IS NEW PROC1 ("WHAT");
BEGIN
     DECLARE
          TASK_1 : T2;
          ID     : INTEGER;
     BEGIN
          IF FUNC_OB /= 1 THEN
               FAILED ("INCORRECT RESULTS FROM FUNCTION " &
                       "FUNC_OB");
          END IF;
          IF PACK_OB.X /= 2 THEN
               FAILED ("INCORRECT RESULTS FROM PACKAGE " &
                       "PACK_OB");
          END IF;
          TASK_OB.E (ID);
          IF  ID /= 3 THEN
               FAILED ("INCORRECT RESULTS FROM TASK TASK_OB");
          END IF;
          IF C39005A_FUNC_OB /= 4 THEN
               FAILED ("INCORRECT RESULTS FROM SEPARATE FUNCTION " &
                       "C39005A_FUNC_OB");
          END IF;
          IF C39005A_PACK_OB.X /= 5 THEN
               FAILED ("INCORRECT RESULTS FROM SEPARATE PACKAGE " &
                       "C39005A_PACK_OB");
          END IF;
          C39005A_TASK_OB.E (ID);
          IF  ID /= 6 THEN
               FAILED ("INCORRECT RESULTS FROM SEPARATE TASK " &
                       "C39005A_TASK_OB");
          END IF;

          TASK_1.E;

          PROC2;

          ADD1 (A);
          IF A /= 2 THEN
               FAILED ("INCORRECT RESULTS FROM ADD1");
          END IF;
     END;

     RESULT;
END C39005A;


SEPARATE (C39005A)
FUNCTION C39005A_FUNC_OB RETURN INTEGER IS
BEGIN
     RETURN IDENT_INT (4);
END C39005A_FUNC_OB;

SEPARATE (C39005A)
PACKAGE BODY C39005A_PACK_OB IS
BEGIN
     X := IDENT_INT (5);
END C39005A_PACK_OB;

SEPARATE (C39005A)
TASK BODY C39005A_TASK_OB IS
BEGIN
     ACCEPT E (X : OUT INTEGER) DO
          X := IDENT_INT (6);
     END E;
END C39005A_TASK_OB;
