-- C41108A.ADA

-- OBJECTIVE:
--     CHECK THAT EXPRESSIONS IN THE PREFIX ARE ALL EVALUATED BEFORE
--     OR AFTER THE INDEX EXPRESSIONS.

-- HISTORY:
--     BCB 01/21/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C41108A IS

     TYPE D IS ARRAY(1..2,1..2) OF INTEGER;

     TYPE REC IS RECORD
          A : D;
     END RECORD;

     ARR : ARRAY(1..5, 1..5) OF REC;

     INDEX : INTEGER := 1;

     B : STRING(1..4);

     FUNCTION F1 RETURN INTEGER IS
     BEGIN
          B(INDEX) := 'A';
          INDEX := INDEX + 1;
          RETURN 1;
     END F1;

     FUNCTION F2 RETURN INTEGER IS
     BEGIN
          B(INDEX) := 'B';
          INDEX := INDEX + 1;
          RETURN 1;
     END F2;

     FUNCTION F3 RETURN INTEGER IS
     BEGIN
          B(INDEX) := 'C';
          INDEX := INDEX + 1;
          RETURN 1;
     END F3;

     FUNCTION F4 RETURN INTEGER IS
     BEGIN
          B(INDEX) := 'D';
          INDEX := INDEX + 1;
          RETURN 1;
     END F4;

BEGIN
     TEST ("C41108A", "CHECK THAT EXPRESSIONS IN THE PREFIX ARE ALL " &
                      "EVALUATED BEFORE OR AFTER THE INDEX " &
                      "EXPRESSIONS");

     ARR(F1, F2).A(F3, F4) := IDENT_INT (10);

     IF B(1..2) = "AB" OR B(1..2) = "BA"
          THEN COMMENT ("EXPRESSIONS IN THE PREFIX ARE ALL EVALUATED " &
                        "BEFORE THE INDEX EXPRESSIONS");
     ELSIF B(1..2) = "CD" OR B(1..2) = "DC"
          THEN COMMENT ("EXPRESSIONS IN THE PREFIX ARE ALL EVALUATED " &
                        "AFTER THE INDEX EXPRESSIONS");
     ELSE FAILED ("EXPRESSIONS IN THE PREFIX ARE NOT ALL EVALUATED " &
                  "BEFORE OR AFTER THE INDEX EXPRESSIONS");
     END IF;

     RESULT;
END C41108A;
