-- C41101D.ADA

-- FOR INDEXED COMPONENTS OF THE FORM F(...), CHECK THAT 
--   THE NUMBER OF INDEX VALUES, THE TYPE OF THE INDEX
--   VALUES, AND THE REQUIRED TYPE OF THE INDEXED COMPONENT
--   ARE USED TO RESOLVE AN OVERLOADING OF F.

-- WKB 8/12/81
-- JBG 10/12/81
-- SPS 11/1/82

WITH REPORT;
PROCEDURE C41101D IS

     USE REPORT;

     TYPE T1 IS ARRAY (1..10) OF INTEGER;
     TYPE T2 IS ARRAY (1..10, 1..10) OF INTEGER;
     I : INTEGER;

     TYPE U1 IS (MON,TUE,WED,THU,FRI);
     TYPE U2 IS ARRAY (U1 RANGE MON..THU) OF INTEGER;

     TYPE V1 IS ARRAY (1..10) OF BOOLEAN;
     B : BOOLEAN;

     FUNCTION F RETURN T1 IS
     BEGIN
          RETURN (1..10 => 1);
     END F;

     FUNCTION F RETURN T2 IS
     BEGIN
          RETURN (1..10 => (1..10 => 2));
     END F;

     FUNCTION G RETURN U2 IS
     BEGIN
          RETURN (MON..THU => 3);
     END G;

     FUNCTION G RETURN T1 IS
     BEGIN
          RETURN (1..10 => 4);
     END G;

     FUNCTION H RETURN T1 IS
     BEGIN
          RETURN (1..10 => 5);
     END H;

     FUNCTION H RETURN V1 IS
     BEGIN
          RETURN (1..10 => FALSE);
     END H;

BEGIN

     TEST ("C41101D", "WHEN INDEXING FUNCTION RESULTS, INDEX TYPE, " &
                      "NUMBER OF INDICES, AND COMPONENT TYPE ARE " &
                      "USED FOR OVERLOADING RESOLUTION");

     I := F(7);              -- NUMBER OF INDEX VALUES.
     IF I /= IDENT_INT(1) THEN
          FAILED ("WRONG VALUE - 1");
     END IF;

     I := G(3);              -- INDEX TYPE.
     IF I /= IDENT_INT(4) THEN
          FAILED ("WRONG VALUE - 2");
     END IF;

     B := H(5);              -- COMPONENT TYPE.
     IF B /= IDENT_BOOL(FALSE) THEN
          FAILED ("WRONG VALUE - 3");
     END IF;

     RESULT;

END C41101D;
