-- C41106A.ADA

-- CHECK THAT ARRAYS HAVING BOUNDS OF INTEGER'FIRST, INTEGER'LAST,
--   SYSTEM.MIN_INT, AND SYSTEM.MAX_INT CAN BE INDEXED AT
--   THOSE BOUNDS.

-- WKB 7/29/81
-- SPS 11/1/82

WITH SYSTEM;
WITH REPORT;
USE REPORT;
PROCEDURE C41106A IS

BEGIN
     TEST ("C41106A", "ARRAYS HAVING BOUNDS OF INTEGER'FIRST, " &
                      "INTEGER'LAST, SYSTEM.MIN_INT, AND SYSTEM." &
                      "MAX_INT CAN BE INDEXED AT THOSE BOUNDS");

     DECLARE

          A1 : ARRAY (INTEGER'FIRST .. INTEGER'FIRST + 4) OF INTEGER
               := (1,2,3,4,5);
          A2 : ARRAY (INTEGER'LAST - 4 .. INTEGER'LAST) OF BOOLEAN
               := (TRUE,TRUE,TRUE,TRUE,FALSE);
          TYPE T IS RANGE SYSTEM.MIN_INT .. SYSTEM.MAX_INT;
          SUBTYPE ST1 IS T RANGE SYSTEM.MIN_INT
               ..SYSTEM.MIN_INT +4;
          SUBTYPE ST2 IS T RANGE SYSTEM.MAX_INT -4
               ..SYSTEM.MAX_INT;
          A3 : ARRAY (ST1)
               OF INTEGER := (5,4,3,2,1);
          A4 : ARRAY (ST2)
               OF CHARACTER := ('A','B','C','D','E');

     BEGIN

          IF A1 (INTEGER'FIRST) /= 1 THEN
               FAILED ("WRONG VALUE USING INTEGER'FIRST");
          END IF;

          IF A2 (INTEGER'LAST) /= FALSE THEN
               FAILED ("WRONG VALUE USING INTEGER'LAST");
          END IF;

          IF A3 (SYSTEM.MIN_INT) /= 5 THEN
               FAILED ("WRONG VALUE USING SYSTEM.MIN_INT");
          END IF;

          IF A4 (SYSTEM.MAX_INT) /= 'E' THEN
               FAILED ("WRONG VALUE USING SYSTEM.MAX_INT");
          END IF;

     END;

     RESULT;
END C41106A;
