-- C41207A.ADA

-- OBJECTIVE:
--     CHECK THAT THE DISCRETE RANGE IN A SLICE CAN HAVE THE FORM
--     A'RANGE, WHERE A IS A CONSTRAINED ARRAY SUBTYPE OR AN ARRAY
--     OBJECT.

-- HISTORY:
--     BCB 07/13/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C41207A IS

     TYPE ARR IS ARRAY(INTEGER RANGE <>) OF INTEGER;

     SUBTYPE A1 IS ARR(1..5);

     ARR_VAR : ARR(1..10) := (90,91,92,93,94,95,96,97,98,99);

     A2 : ARRAY(1..5) OF INTEGER := (80,81,82,83,84);

BEGIN
     TEST ("C41207A", "CHECK THAT THE DISCRETE RANGE IN A SLICE CAN " &
                      "HAVE THE FORM A'RANGE, WHERE A IS A " &
                      "CONSTRAINED ARRAY SUBTYPE OR AN ARRAY OBJECT");

     ARR_VAR (A1'RANGE) := (1,2,3,4,5);

     IF NOT (EQUAL(ARR_VAR(1),1) AND EQUAL(ARR_VAR(2),2) AND
         EQUAL(ARR_VAR(3),3) AND EQUAL(ARR_VAR(4),4) AND
         EQUAL(ARR_VAR(5),5)) THEN
          FAILED ("IMPROPER RESULT FROM SLICE ASSIGNMENT USING THE " &
                  "RANGE OF A CONSTRAINED ARRAY SUBTYPE");
     END IF;

     ARR_VAR (A2'RANGE) := (6,7,8,9,10);

     IF (NOT EQUAL(ARR_VAR(1),6) OR NOT EQUAL(ARR_VAR(2),7) OR
         NOT EQUAL(ARR_VAR(3),8) OR NOT EQUAL(ARR_VAR(4),9) OR
         NOT EQUAL(ARR_VAR(5),10)) THEN
          FAILED ("IMPROPER RESULT FROM SLICE ASSIGNMENT USING THE " &
                  "RANGE OF AN ARRAY OBJECT");
     END IF;

     RESULT;
END C41207A;
