-- C41206A.ADA

-- CHECK THAT A RANGE L..R, WHERE L=SUCC(R) CAN BE USED TO FORM
--   A NULL SLICE FROM AN ARRAY WHEN:
--        BOTH L AND R SATISFY THE INDEX CONSTRAINT;
--        L SATISFIES THE INDEX CONSTRAINT, R DOES NOT (BUT IT
--             BELONGS TO THE BASE TYPE OF THE INDEX);
--        L SATISFIES THE CONSTRAINT IMPOSED BY THE TYPE MARK OF
--             THE INDEX, BUT NOT THE CONSTRAINT ASSOCIATED WITH
--             THE INDEX;
--        THE ARRAY IS NULL, AND L IS IN THE RANGE OF THE INDEX SUBTYPE.

-- WKB 8/10/81

WITH REPORT;
USE REPORT;
PROCEDURE C41206A IS

     TYPE SMALL IS RANGE 1..100;
     TYPE T IS ARRAY (SMALL RANGE <> ) OF INTEGER;
     SUBTYPE T1 IS T(5..10);
     A : T1 := (5,6,7,8,9,10);
     B : T(8..7) := (8..7 => 1);

BEGIN
     TEST ("C41206A", "USING A RANGE L..R, WHERE L=SUCC(R), " &
                      "TO FORM A NULL SLICE FROM AN ARRAY");

     BEGIN
          IF A (7..6) /= B OR A (SMALL(IDENT_INT(7))..6) /= B THEN
               FAILED ("SLICE NOT NULL - 1");
          END IF;
     EXCEPTION
          WHEN OTHERS => FAILED ("EXCEPTION RAISED - 1");
     END;

     BEGIN
          IF A (5..4) /= B OR A (SMALL(IDENT_INT(5))..4) /= B THEN
               FAILED ("SLICE NOT NULL - 2");
          END IF;
     EXCEPTION
          WHEN OTHERS => FAILED ("EXCEPTION RAISED - 2");
     END;

     BEGIN
          IF A (50..49) /= B OR A (SMALL(IDENT_INT(50))..49) /= B THEN
               FAILED ("SLICE NOT NULL - 3");
          END IF;
     EXCEPTION
          WHEN OTHERS => FAILED ("EXCEPTION RAISED - 3");
     END;

     BEGIN
          IF B (50..49) /= B OR B (SMALL(IDENT_INT(50))..49) /= B THEN
               FAILED ("SLICE NOT NULL - 4");
          END IF;
     EXCEPTION
          WHEN OTHERS => FAILED ("EXCEPTION RAISED - 4");
     END;

     RESULT;
END C41206A;
