-- C41324A.ADA

-- CHECK THAT IMPLICITLY DECLARED RELATIONAL OPERATORS AND ARITHMETIC
-- OPERATORS (+, -, *, /, ABS) MAY BE SELECTED FROM OUTSIDE THE
-- PACKAGE USING AN EXPANDED NAME, FOR A FIXED POINT TYPE.

-- TBN  7/16/86

WITH REPORT; USE REPORT;
PROCEDURE C41324A IS

     PACKAGE P IS
          TYPE FIXED IS DELTA 0.125 RANGE -1.0E1 .. 1.0E1;
          OBJ_FIX_1 : FIXED := -5.5;
          OBJ_FIX_2 : FIXED := 1.5;
          OBJ_FIX_3 : FIXED := 10.0;
     END P;

     FIX_VAR : P.FIXED;
     FIX_VAR_1 : P.FIXED := P."-"(P.FIXED'(5.5));
     FIX_VAR_2 : P.FIXED := P.FIXED'(1.5);
     FIX_VAR_3 : P.FIXED := P.FIXED'(1.0E1);

BEGIN
     TEST ("C41324A", "CHECK THAT IMPLICITLY DECLARED RELATIONAL " &
                      "OPERATORS AND ARITHMETIC OPERATORS (+, -, *, " &
                      "/, ABS) MAY BE SELECTED FROM OUTSIDE THE " &
                      "PACKAGE USING AN EXPANDED NAME, FOR A FIXED " &
                      "POINT TYPE");

     IF P."=" (FIX_VAR_1, P."-"(P.FIXED'(6.0))) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 1");
     END IF;

     IF P."/=" (FIX_VAR_1, P.OBJ_FIX_1) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 2");
     END IF;

     IF P."<" (FIX_VAR_2, P.OBJ_FIX_1) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 3");
     END IF;

     IF P.">" (FIX_VAR_2, P.OBJ_FIX_3) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 4");
     END IF;

     IF P."<=" (FIX_VAR_3, P.FIXED'(9.9)) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 5");
     END IF;

     IF P."<=" (FIX_VAR_3, P.FIXED'(10.0)) THEN
          NULL;
     ELSE
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 6");
     END IF;

     IF P.">=" (P.OBJ_FIX_2, FIX_VAR_3) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 7");
     END IF;

     IF P.">=" (P.OBJ_FIX_2, FIX_VAR_2) THEN
          NULL;
     ELSE
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 8");
     END IF;

     FIX_VAR := P."+" (FIX_VAR_1, P.OBJ_FIX_2);
     IF P."/=" (FIX_VAR, P."-"(P.FIXED'(4.0))) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 9");
     END IF;

     FIX_VAR := P."-" (FIX_VAR_2, P.OBJ_FIX_1);
     IF P."/=" (FIX_VAR, P.FIXED'(7.0)) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 10");
     END IF;

     FIX_VAR := P."*" (FIX_VAR_2, 2);
     IF P."/=" (FIX_VAR, P.FIXED'(3.0)) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 11");
     END IF;

     FIX_VAR := P."*" (3, FIX_VAR_2);
     IF P."/=" (FIX_VAR, P.FIXED'(4.5)) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 12");
     END IF;

     FIX_VAR := P."/" (FIX_VAR_3, 2);
     IF P."/=" (FIX_VAR, P.FIXED'(5.0)) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 13");
     END IF;

     FIX_VAR := P."ABS" (FIX_VAR_1);
     IF P."/=" (FIX_VAR, P.FIXED'(5.5)) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 14");
     END IF;

     RESULT;
END C41324A;
