-- C41326A.ADA

-- CHECK THAT IMPLICITLY DECLARED EQUALITY AND INEQUALITY OPERATORS
-- MAY BE SELECTED FROM OUTSIDE A PACKAGE USING AN EXPANDED NAME, FOR
-- AN ACCESS TYPE.

-- TBN  7/18/86

WITH REPORT; USE REPORT;
PROCEDURE C41326A IS

     PACKAGE P IS
          TYPE CELL IS
               RECORD
                    VALUE : INTEGER;
               END RECORD;
          TYPE LINK IS ACCESS CELL;

          OBJ_LINK_1 : LINK := NEW CELL'(VALUE => 1);
          OBJ_LINK_2 : LINK := OBJ_LINK_1;
     END P;

     VAR_LINK_1 : P.LINK := NEW P.CELL'(VALUE => 1);
     VAR_LINK_2 : P.LINK := NEW P.CELL'(VALUE => 2);

BEGIN
     TEST ("C41326A", "CHECK THAT IMPLICITLY DECLARED EQUALITY AND " &
                      "INEQUALITY OPERATORS MAY BE SELECTED FROM " &
                      "OUTSIDE A PACKAGE USING AN EXPANDED NAME, " &
                      "FOR AN ACCESS TYPE");

     IF P."=" (VAR_LINK_1, P.OBJ_LINK_1) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 1");
     END IF;

     IF P."/=" (P.OBJ_LINK_1, P.OBJ_LINK_2) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 2");
     END IF;

     IF P."=" (VAR_LINK_2.ALL, P.OBJ_LINK_1.ALL) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 3");
     END IF;

     VAR_LINK_2.VALUE := 1;
     IF P."/=" (VAR_LINK_2.ALL, P.OBJ_LINK_1.ALL) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 4");
     END IF;

     RESULT;
END C41326A;
