-- C41321A.ADA

-- CHECK THAT IMPLICITLY DECLARED RELATIONAL OPERATORS, LOGICAL 
-- OPERATORS, AND THE "NOT" OPERATOR MAY BE SELECTED FROM OUTSIDE
-- THE PACKAGE USING AN EXPANDED NAME, FOR A DERIVED BOOLEAN TYPE.

-- TBN  7/16/86

WITH REPORT; USE REPORT;
PROCEDURE C41321A IS

     PACKAGE P IS
          TYPE DERIVED_BOOLEAN IS NEW BOOLEAN RANGE FALSE .. TRUE;
          DERIVED_FALSE : DERIVED_BOOLEAN := FALSE;
          DERIVED_TRUE : DERIVED_BOOLEAN := TRUE;
     END P;

     DBOOL_FALSE : P.DERIVED_BOOLEAN := P.FALSE;
     DBOOL_TRUE : P.DERIVED_BOOLEAN := P.TRUE;

BEGIN
     TEST ("C41321A", "CHECK THAT IMPLICITLY DECLARED RELATIONAL " &
                      "OPERATORS, LOGICAL OPERATORS, AND THE 'NOT' " &
                      "OPERATOR MAY BE SELECTED FROM OUTSIDE THE " &
                      "PACKAGE USING AN EXPANDED NAME, FOR A DERIVED " &
                      "BOOLEAN TYPE");

     IF P."=" (DBOOL_FALSE, P.DERIVED_TRUE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 1");
     END IF;

     IF P."/=" (DBOOL_TRUE, P.DERIVED_TRUE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 2");
     END IF;

     IF P."<" (P.DERIVED_TRUE, P.DERIVED_FALSE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 3");
     END IF;

     IF P.">" (DBOOL_TRUE, P.DERIVED_TRUE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 4");
     END IF;

     IF P."<=" (P.DERIVED_TRUE, DBOOL_FALSE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 5");
     END IF;

     IF P."<=" (P.DERIVED_TRUE, DBOOL_TRUE) THEN
          NULL;
     ELSE
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 6");
     END IF;

     IF P.">=" (P.DERIVED_TRUE, DBOOL_TRUE) THEN
          NULL;
     ELSE
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 7");
     END IF;

     FOR J IN P.DERIVED_BOOLEAN'(P.TRUE) .. P.DERIVED_BOOLEAN'(P.TRUE)
          LOOP
               IF P.">=" (DBOOL_FALSE, J) THEN
                    FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 8");
               END IF;
          END LOOP;

     IF P."AND" (DBOOL_FALSE, P.DERIVED_TRUE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 9");
     END IF;

     IF P."OR" (DBOOL_FALSE, P.DERIVED_FALSE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 10");
     END IF;

     IF P."XOR" (DBOOL_TRUE, P.DERIVED_TRUE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 11");
     END IF;

     IF P."NOT" (P.DERIVED_TRUE) THEN
          FAILED ("INCORRECT RESULTS FROM EXPANDED NAME - 12");
     END IF;

     RESULT;
END C41321A;
