-- C42007D.ADA

-- CHECK THAT THE BOUNDS OF A STRING LITERAL ARE DETERMINED CORRECTLY.
-- IN PARTICULAR, CHECK THAT THE LOWER BOUND IS GIVEN BY 'FIRST OF THE
-- INDEX SUBTYPE WHEN THE STRING LITERAL IS USED AS:

--   D) THE INITIALIZATION EXPRESSION OF A CONSTANT WHOSE TYPE MARK
--      DENOTES AN UNCONSTRAINED TYPE.

-- TBN  7/28/86

WITH REPORT; USE REPORT;
PROCEDURE C42007D IS

BEGIN

     TEST("C42007D", "CHECK THE BOUNDS OF A STRING LITERAL WHEN USED " &
                     "AS THE INITIALIZATION EXPRESSION OF A CONSTANT " &
                     "WHOSE TYPE MARK DENOTES AN UNCONSTRAINED TYPE");

     BEGIN

CASE_D :  DECLARE

               SUBTYPE POSIT IS INTEGER RANGE IDENT_INT(11) .. 13;
               TYPE STR IS ARRAY (POSIT RANGE <>) OF CHARACTER;

               STRING_1 : CONSTANT STR := "WHO";

          BEGIN

               IF STRING_1'FIRST /= IDENT_INT(11) THEN
                    FAILED ("LOWER BOUND NOT GIVEN BY 'FIRST");
               END IF;

               IF STRING_1'LAST /= IDENT_INT(13) THEN
                    FAILED ("UPPER BOUND NOT CORRECT");
               END IF;

               IF STRING_1 /= (IDENT_CHAR('W'), IDENT_CHAR('H'),
                                                   IDENT_CHAR('O')) THEN
                    FAILED ("STRING CONTAINS THE WRONG VALUES");
               END IF;

          END CASE_D;
     END;

     RESULT;

END C42007D;
