-- C42007A.ADA

-- CHECK THAT THE BOUNDS OF A STRING LITERAL ARE DETERMINED CORRECTLY.
-- IN PARTICULAR, CHECK THAT THE LOWER BOUND IS GIVEN BY 'FIRST OF THE
-- INDEX SUBTYPE WHEN THE STRING LITERAL IS USED AS:

--   A) AN ACTUAL PARAMETER IN A SUBPROGRAM OR ENTRY CALL, AND THE
--      FORMAL PARAMETER IS UNCONSTRAINED.

-- TBN 6/2/86

WITH REPORT; USE REPORT;
PROCEDURE C42007A IS

     SUBTYPE I5_10 IS INTEGER RANGE IDENT_INT(5) .. IDENT_INT(10);
     TYPE STR5_10 IS ARRAY (I5_10 RANGE <>) OF CHARACTER;

     PROCEDURE PROC1 (A : STR5_10) IS

     BEGIN
          IF A'FIRST /= IDENT_INT(5) THEN
               FAILED ("LOWER BOUND INCORRECTLY GIVEN BY 'FIRST");
          ELSIF A'LAST /= 9 THEN
               FAILED ("UPPER BOUND INCORRECTLY GIVEN BY 'LAST");
          ELSIF A /= ('H', 'E', 'L', 'L', 'O') THEN
               FAILED ("STRING LITERAL NOT PASSED CORRECTLY");
          END IF;
     END PROC1;

BEGIN
     TEST("C42007A", "CHECK THE BOUNDS OF A STRING LITERAL WHEN USED " &
                     "AS AN ACTUAL PARAMETER IN A SUBPROGRAM CALL " &
                     "AND THE FORMAL PARAMETER IS UNCONSTRAINED");

     PROC1 ("HELLO");
     RESULT;
END C42007A;
