-- C42007H.ADA

-- CHECK THAT THE BOUNDS OF A STRING LITERAL ARE DETERMINED CORRECTLY.
-- IN PARTICULAR, CHECK THAT THE LOWER BOUND IS GIVEN BY THE LOWER
-- BOUND OF THE APPLICABLE INDEX CONSTRAINT WHEN THE STRING LITERAL
-- IS USED AS:

--      AN ACTUAL PARAMETER IN A GENERIC INSTANTIATION, AND THE FORMAL
--      PARAMETER IS CONSTRAINED.

-- TBN  7/30/86

WITH REPORT; USE REPORT;
PROCEDURE C42007H IS

BEGIN

     TEST("C42007H", "CHECK THE BOUNDS OF A STRING LITERAL WHEN USED " &
                     "AS AN ACTUAL PARAMETER IN A GENERIC " &
                     "INSTANTIATION, AND THE FORMAL PARAMETER IS " &
                     "CONSTRAINED");
     BEGIN

CASE_H :  DECLARE

               SUBTYPE STH IS INTEGER RANGE -10 .. 0;
               TYPE BASE IS ARRAY(STH RANGE <>) OF CHARACTER;
               SUBTYPE TB IS BASE(IDENT_INT(-8) .. -5);

               GENERIC
                    B1 : TB;
               PROCEDURE PROC1;

               PROCEDURE PROC1 IS
               BEGIN
                    IF B1'FIRST /= IDENT_INT(-8) THEN
                         FAILED ("LOWER BOUND INCORRECTLY DETERMINED");
                    END IF;
                    IF B1'LAST /= IDENT_INT(-5) THEN
                         FAILED ("UPPER BOUND INCORRECTLY DETERMINED");
                    END IF;
                    IF B1 /= ("WHEN") THEN
                         FAILED ("INCORRECT STRING LITERAL");
                    END IF;
               END PROC1;

               PROCEDURE PROC2 IS NEW PROC1 ("WHEN");

          BEGIN
               PROC2;
          END CASE_H;

     END;

     RESULT;

END C42007H;
