-- C43003A.ADA

-- CHECK THAT WHEN INITIALIZING AN ARRAY OF ACCESS OBJECTS, WITH
-- AN AGGREGATE CONTAINING A SINGLE ALLOCATOR, ALL ELEMENTS
-- ARE INITIALIZED TO THE SAME INITIAL VALUE.
-- THAT IS, CHECK THAT ALL COMPONENTS OF THE ARRAY DESIGNATE
-- DISTINCT OBJECTS.

-- DAT 3/18/81
-- SPS 10/26/82
-- JBG 12/27/82
-- R. WILLIAMS 11/11/86     RENAMED FROM C38007A-B.ADA.

WITH REPORT; USE REPORT;

PROCEDURE C43003A IS

     TYPE AI IS ACCESS INTEGER;

     TYPE AAI IS ARRAY (1..5) OF AI;

     A : AAI := AAI'(OTHERS => NEW INTEGER '(2));

BEGIN
     TEST ("C43003A", "CHECK THAT ALLOCATORS IN INITIALIZATIONS"
          & " FOR ARRAYS OF ACCESS VALUES ARE EVALUATED ONCE" &
          " FOR EACH COMPONENT");

     FOR I IN 1..5
     LOOP
          FOR J IN I+1..5
          LOOP
               IF A(I) = A(J) THEN
                    FAILED ("DID NOT EVALUATE ALLOCATOR FOR EACH " &
                            "COMPONENT");
                    EXIT;
               END IF;
          END LOOP;
     END LOOP;

     RESULT;
END C43003A;
