-- C43104A.ADA

-- OBJECTIVE:
--     CHECK THAT WITH THE TYPE OF THE AGGREGATE RESOLVED, THE
--     DISCRIMINANT MAY BE USED TO DECIDE TO WHICH OF THE VARIANT'S
--     SUBTYPES THE AGGREGATE BELONGS.

-- HISTORY:
--     DHH 08/08/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C43104A IS

     TYPE INT IS RANGE 0 .. 10;

     TYPE VAR_REC(BOOL : BOOLEAN := TRUE) IS
          RECORD
               CASE BOOL IS
                    WHEN TRUE =>
                         X : INTEGER;
                    WHEN FALSE =>
                         Y : INT;
               END CASE;
          END RECORD;

     SUBTYPE S_TRUE IS VAR_REC(TRUE);
     SUBTYPE S_FALSE IS VAR_REC(FALSE);

     PROCEDURE CHECK(P : IN S_TRUE) IS
     BEGIN
          IF P.BOOL = FALSE THEN
               FAILED("WRONG PROCEDURE ENTERED");
          END IF;

     EXCEPTION
          WHEN OTHERS =>
               FAILED("EXCEPTION RAISED INSIDE PROCEDURE");

     END CHECK;

BEGIN
     TEST("C43104A", "CHECK THAT WITH THE TYPE OF THE AGGREGATE " &
                     "RESOLVED, THE DISCRIMINANT MAY BE USED TO " &
                     "DECIDE TO WHICH OF THE VARIANT'S SUBTYPES " &
                     "THE AGGREGATE BELONGS");

     CHECK((TRUE, 1));

     BEGIN

          CHECK((FALSE, 2));
          FAILED("PROCEDURE CALL USING '(FALSE, 2)' DID NOT RAISE " &
                 "EXCEPTION");

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED("INCORRECT EXCEPTION RAISED ON PROCEDURE CALL " &
                      "USING '(FALSE,2)'");
     END;

     RESULT;
END C43104A;
