-- C43204I.ADA

-- OBJECTIVE:
--     CHECK THAT AN AGGREGATE WITH AN OTHERS CLAUSE CAN APPEAR AS THE
--     EXPRESSION IN AN ASSIGNMENT STATEMENT, AND THAT THE BOUNDS OF
--     THE AGGREGATE ARE DETERMINED CORRECTLY.

-- HISTORY:
--     JET 08/15/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C43204I IS

     TYPE ARR11 IS ARRAY (INTEGER RANGE -3 .. 3) OF INTEGER;
     TYPE ARR12 IS ARRAY (IDENT_INT(-3) .. IDENT_INT(3)) OF INTEGER;
     TYPE ARR13 IS ARRAY (IDENT_INT(1) .. IDENT_INT(-1)) OF INTEGER;
     TYPE ARR21 IS ARRAY (INTEGER RANGE -1 .. 1,
                          INTEGER RANGE -1 .. 1) OF INTEGER;
     TYPE ARR22 IS ARRAY (IDENT_INT(-1) .. IDENT_INT(1),
                          IDENT_INT(-1) .. IDENT_INT(1)) OF INTEGER;
     TYPE ARR23 IS ARRAY (INTEGER RANGE -1 .. 1,
                          IDENT_INT(-1) .. IDENT_INT(1)) OF INTEGER;
     TYPE ARR24 IS ARRAY (IDENT_INT(1) .. IDENT_INT(-1),
                          IDENT_INT(-1) .. IDENT_INT(1)) OF INTEGER;

     VA11 : ARR11;
     VA12 : ARR12;
     VA13 : ARR13;
     VA21 : ARR21;
     VA22 : ARR22;
     VA23 : ARR23;
     VA24 : ARR24;

BEGIN
     TEST ("C43204I", "CHECK THAT AN AGGREGATE WITH AN OTHERS CLAUSE " &
                      "CAN APPEAR AS THE EXPRESSION IN AN ASSIGNMENT " &
                      "STATEMENT, AND THAT THE BOUNDS OF THE " &
                      "AGGREGATE ARE DETERMINED CORRECTLY");

     VA11 := (1,1, OTHERS => IDENT_INT(2));
     VA12 := (OTHERS => IDENT_INT(2));
     VA13 := (OTHERS => IDENT_INT(2));
     VA21 := ((1,1,1), OTHERS => (-1..1 => IDENT_INT(2)));
     VA22 := (-1 => (1,1,1), 0..1 => (OTHERS => IDENT_INT(2)));
     VA23 := (OTHERS => (OTHERS => IDENT_INT(2)));
     VA24 := (OTHERS => (OTHERS => IDENT_INT(2)));

     IF VA11 /= (1, 1, 2, 2, 2, 2, 2) THEN
          FAILED("INCORRECT VALUE OF VA11");
     END IF;

     IF VA12 /= (2, 2, 2, 2, 2, 2, 2) THEN
          FAILED("INCORRECT VALUE OF VA12");
     END IF;

     IF VA13'LENGTH /= 0 THEN
          FAILED("INCORRECT VALUE OF VA13");
     END IF;

     IF VA21 /= ((1,1,1), (2,2,2), (2,2,2)) THEN
          FAILED("INCORRECT VALUE OF VA21");
     END IF;

     IF VA22 /= ((1,1,1), (2,2,2), (2,2,2)) THEN
          FAILED("INCORRECT VALUE OF VA22");
     END IF;

     IF VA23 /= ((2,2,2), (2,2,2), (2,2,2)) THEN
          FAILED("INCORRECT VALUE OF VA23");
     END IF;

     IF VA24'LENGTH /= 0 OR VA24'LENGTH(2) /= 3 THEN
          FAILED("INCORRECT VALUE OF VA24");
     END IF;

     RESULT;

EXCEPTION
     WHEN OTHERS =>
          FAILED ("UNEXPECTED CONSTRAINT_ERROR OR OTHER EXCEPTION " &
                  "RAISED");

          RESULT;
END C43204I;
