-- C43224A.ADA

-- OBJECTIVE:
--     CHECK THAT A NON-STATIC CHOICE OF AN ARRAY AGGREGATE CAN BE A
--     'RANGE ATTRIBUTE.

-- HISTORY:
--     DHH 08/15/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C43224A IS

     M, O : INTEGER := IDENT_INT(2);
     N : INTEGER := IDENT_INT(3);

     TYPE ARR IS ARRAY(INTEGER RANGE <>) OF INTEGER;
     TYPE D3_ARR IS ARRAY(INTEGER RANGE <>, INTEGER RANGE <>,
                          INTEGER RANGE <>) OF INTEGER;

     SUBTYPE ARR1 IS ARR(IDENT_INT(2) .. IDENT_INT(3));
     SUBTYPE ARR2 IS D3_ARR(1 .. M, 1 .. N, 1 ..O);

     SUB : ARR1;
     SUB1 : ARR2;

     PROCEDURE PROC(ARRY : IN OUT ARR) IS
     BEGIN
          ARRY := (ARR1'RANGE => IDENT_INT(7));
          IF ARRY(IDENT_INT(ARRY'FIRST)) /= IDENT_INT(7) THEN
               FAILED("RANGE NOT INITIALIZED - 1");
          END IF;
     END PROC;

     PROCEDURE PROC1(ARRY : IN OUT D3_ARR) IS
     BEGIN
          ARRY := (ARR2'RANGE(1) => (ARRY'RANGE(2) =>
                  (ARRY'RANGE(3) => IDENT_INT(7))));

          IF ARRY(IDENT_INT(1), IDENT_INT(2), IDENT_INT(1)) /=
                  IDENT_INT(7) THEN
               FAILED("RANGE NOT INITIALIZED - 2");
          END IF;
     END PROC1;

BEGIN
     TEST("C43224A", "CHECK THAT A NON-STATIC CHOICE OF AN ARRAY " &
                     "AGGREGATE CAN BE A 'RANGE ATTRIBUTE");

     PROC(SUB);
     PROC1(SUB1);

     RESULT;
END C43224A;
