-- C43205D.ADA

-- CHECK THAT THE BOUNDS OF A POSITIONAL AGGREGATE ARE DETERMINED
-- CORRECTLY. IN PARTICULAR, CHECK THAT THE LOWER BOUND IS GIVEN BY
-- 'FIRST OF THE INDEX SUBTYPE WHEN THE POSITIONAL AGGREGATE IS USED AS:

--   D) THE INITIALIZATION EXPRESSION OF A CONSTANT WHOSE TYPE MARK
--      DENOTES AN UNCONSTRAINED ARRAY.

-- EG  01/26/84

WITH REPORT;

PROCEDURE C43205D IS

     USE REPORT;

BEGIN

     TEST("C43205D", "CASE D : INITIALIZATION OF UNCONSTRAINED " &
                     "ARRAY CONSTANT");

     BEGIN

CASE_D :  DECLARE

               SUBTYPE STD IS INTEGER RANGE IDENT_INT(11) .. 13;
               TYPE TD IS ARRAY (STD RANGE <>) OF INTEGER;

               D1 : CONSTANT TD := (-1, -2, -3);

          BEGIN

               IF D1'FIRST /= 11 THEN
                    FAILED ("CASE D : LOWER BOUND INCORRECTLY " &
                            "GIVEN BY 'FIRST");
               ELSIF D1'LAST /= 13 THEN
                    FAILED ("CASE D : UPPER BOUND INCORRECTLY " &
                            "GIVEN BY 'LAST");
               ELSIF D1 /= (-1, -2, -3) THEN
                    FAILED ("CASE D : ARRAY DOES NOT CONTAIN " &
                            "THE CORRECT VALUES");
               END IF;

          END CASE_D;

     END;

     RESULT;

END C43205D;
