-- C43222A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ARRAY AGGREGATE NEED NOT BE RESOLVABLE TO A
--     CONSTRAINED SUBTYPE.

-- HISTORY:
--     DHH 08/12/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C43222A IS

BEGIN
     TEST("C43222A", "CHECK THAT AN ARRAY AGGREGATE NEED NOT BE " &
                     "RESOLVABLE TO A CONSTRAINED SUBTYPE");

     DECLARE
          TYPE A IS ARRAY(INTEGER RANGE <>) OF INTEGER;
          B : BOOLEAN := (1, 2, 3) = A'(1, 2, 3);
     BEGIN
          IF IDENT_BOOL(B) /= IDENT_BOOL(TRUE) THEN
               FAILED("INITIALIZATION FAILURE");
          END IF;
     END;

     RESULT;
END C43222A;
