-- C45123C.ADA

-- CHECK TRUTH TABLES FOR 'AND THEN' AND 'OR ELSE' ON
-- DERIVED BOOLEANS.

-- ABW 7/8/82
-- SPS 2/17/83
-- JWC 6/28/85   RENAMED FROM C45105B-B.ADA

WITH  REPORT ;
PROCEDURE  C45123C  IS

     USE REPORT;

     TYPE NEW_BOOL IS NEW BOOLEAN;
     F : NEW_BOOL := NEW_BOOL(IDENT_BOOL(FALSE));
     T : NEW_BOOL := NEW_BOOL(IDENT_BOOL(TRUE));

BEGIN

     TEST( "C45123C" , "CHECK THE TRUTH TABLES FOR 'AND THEN' AND " &
                       "'OR ELSE' ON DERIVED BOOLEANS." );

          IF F AND THEN F THEN FAILED("F AND THEN F = T");
          END IF;
          IF F AND THEN T THEN FAILED("F AND THEN T = T");
          END IF;
          IF T AND THEN F THEN FAILED("T AND THEN F = T");
          END IF;
          IF T AND THEN T THEN NULL; ELSE FAILED("T AND THEN T = F");
          END IF;

          IF F OR ELSE F THEN FAILED("F OR ELSE F  = T");
          END IF;
          IF F OR ELSE T THEN NULL; ELSE FAILED("F OR ELSE T  = F");
          END IF;
          IF T OR ELSE F THEN NULL; ELSE FAILED("T OR ELSE F  = F");
          END IF;
          IF T OR ELSE T THEN NULL; ELSE FAILED("T OR ELSE T  = F");
          END IF;

     RESULT;

END C45123C;
