-- C45122D.ADA

-- CHECK THAT THE OPERATION OF 'AND THEN' AND 'OR ELSE' ON
-- DERIVED BOOLEAN VARIABLES IS SHORT-CIRCUITED FOR THE
-- APPROPRIATE VALUES OF THE FIRST OPERAND.

-- ABW 7/8/82
-- JBG 4/26/85

WITH REPORT; USE REPORT;
PROCEDURE C45122D IS

     TYPE NEW_BOOL IS NEW BOOLEAN;
     F : NEW_BOOL := NEW_BOOL (IDENT_BOOL(FALSE));
     T : NEW_BOOL := NEW_BOOL (IDENT_BOOL(TRUE));

     EX : EXCEPTION;

     FUNCTION RAISE_EXCEPTION RETURN NEW_BOOL IS
     BEGIN
          RAISE EX;
          RETURN TRUE;
     END RAISE_EXCEPTION;

BEGIN

     TEST ( "C45122D" , "CHECK THE SHORT-CIRCUITED OPERATION " &
                        "FOR DERIVED BOOLEANS" );

     BEGIN

          IF F AND THEN RAISE_EXCEPTION THEN
               FAILED( "'AND THEN' INCORRECTLY EVALUATED" );
          END IF;

     EXCEPTION
          WHEN OTHERS =>
               FAILED( "EXCEPTION RAISED - 'AND THEN' " &
                       "NOT SHORT-CIRCUITED" );
     END;

     BEGIN

          IF T OR ELSE RAISE_EXCEPTION THEN
               NULL;
          ELSE
               FAILED( "'OR ELSE' INCORRECTLY EVALUATED" );
          END IF;

     EXCEPTION
          WHEN OTHERS =>
               FAILED( "EXCEPTION RAISED - 'OR ELSE' " &
                       "NOT SHORT-CIRCUITED" );
     END;

     RESULT;

END C45122D;
