-- C45104A.ADA


-- CHECK THAT PARENTHESIZED CONDITIONS ARE PERMITTED


--  RM    6 OCTOBER 1980
-- JWC 7/8/85   RENAMED TO -AB


WITH  REPORT ;
PROCEDURE  C45104A  IS

     USE REPORT;

     A : INTEGER := 7 ;
     B : BOOLEAN := TRUE ;

BEGIN

     TEST( "C45104A" , "CHECK THAT PARENTHESIZED CONDITIONS ARE" &
                       " PERMITTED" ) ;

     IF  ( A + 1 < A )  THEN  FAILED( "WRONG VALUE (INFIX OP.)"  );
     END IF;
     IF  ( NOT( B )  )  THEN  FAILED( "WRONG VALUE (PREFIX OP.)" );
     END IF;

     RESULT;

END C45104A;
