-- C45122B.ADA


-- CHECK THAT THE EVALUATION OF  'AND THEN'  AND  'OR ELSE'  IS INDEED
--    SHORT-CIRCUITED FOR THE APPROPRIATE VALUES OF THE FIRST
--    OPERAND.

-- (PART1: SIMPLE CASES;   PART2: CHAINS;   PART3: COMBINATIONS)

-- PART 2 :   CHAINS OF  'AND THEN' , 'OR ELSE'  OPERATORS


-- RM   1 OCTOBER 1980
-- JWC 9/30/85    RENAMED FROM C45103B-AB.ADA


WITH  REPORT ;
PROCEDURE  C45122B  IS

     USE REPORT;

     FLOW_INDEX : INTEGER := 0 ;

     TYPE  R  IS
          RECORD
               F: INTEGER ;
          END RECORD;

     TYPE  A_R  IS  ACCESS  R ;

     P          : A_R  :=  NULL ;

     PROCEDURE  BUMP  IS
     BEGIN
          FLOW_INDEX  :=  FLOW_INDEX + 1 ;
     END BUMP ;

     FUNCTION  SIDE_EFFECT_GT( X , Y : INTEGER )  RETURN  BOOLEAN  IS
     BEGIN
          BUMP ;
          RETURN ( X > Y ) ;
     END SIDE_EFFECT_GT ;

BEGIN

     TEST( "C45122B" , "CHECK THE SHORT-CIRCUIT OPERATORS" ) ;

     -- (PART1: SIMPLE CASES;   PART2: CHAINS;   PART3: COMBINATIONS)

     -- PART 2 :   CHAINS OF  'AND THEN' , 'OR ELSE'  OPERATORS

     COMMENT( "STARTING THE CASE  'AND THEN' CHAINS " );
     FLOW_INDEX := 0 ;

     FOR  J  IN  0..4 LOOP

          IF  SIDE_EFFECT_GT( J , 0 )  AND THEN    -- "IF  J > 0 "
              SIDE_EFFECT_GT( J , 1 )  AND THEN
              SIDE_EFFECT_GT( J , 2 )  AND THEN
              SIDE_EFFECT_GT( J , 3 )  AND THEN
              SIDE_EFFECT_GT( J , 4 )
          THEN
               FAILED( " 'AND THEN' CHAIN - WRONG RESULT" );
          END IF;

     END LOOP;

     IF  FLOW_INDEX < 15  THEN
          FAILED( " 'AND THEN' CHAIN - TOO FEW EVALUATIONS" );
     ELSIF  FLOW_INDEX > 15  THEN
          FAILED( " 'AND THEN' CHAIN - TOO MANY EVALUATIONS" );
     END IF;

     COMMENT( "STARTING THE CASE  'OR ELSE' CHAINS " );
     FLOW_INDEX := 0 ;

     FOR  J  IN  1..5 LOOP

          IF  NOT( SIDE_EFFECT_GT( J , 4 )  OR ELSE
                   SIDE_EFFECT_GT( J , 3 )  OR ELSE
                   SIDE_EFFECT_GT( J , 2 )  OR ELSE
                   SIDE_EFFECT_GT( J , 1 )  OR ELSE
                   SIDE_EFFECT_GT( J , 0 )          )
          THEN
               FAILED( " 'OR ELSE' CHAIN - WRONG RESULT" );
          END IF;

     END LOOP;

     IF  FLOW_INDEX < 15  THEN
          FAILED( " 'OR ELSE' CHAIN - TOO FEW EVALUATIONS" );
     ELSIF  FLOW_INDEX > 15  THEN
          FAILED( " 'OR ELSE' CHAIN - TOO MANY EVALUATIONS" );
     END IF;


     RESULT;

END C45122B;
