-- C45101E.ADA


-- CHECK THE TRUTH TABLES FOR  'AND' , 'OR' , 'XOR' ON LITERALS.


--    RM    26 SEPT 1980  ( C45101B.ADA )
--    RM    05 JAN  1982
-- JWC 7/8/85   RENAMED TO -AB


WITH  REPORT ;
PROCEDURE  C45101E  IS

     USE REPORT;

BEGIN

     TEST( "C45101E" , "CHECK THE TRUTH TABLES FOR 'AND' , 'OR' ," &
                       " AND 'XOR'  ON LITERALS");

     IF  FALSE AND FALSE  THEN FAILED("F AND F = T"); END IF;
     IF  FALSE AND TRUE   THEN FAILED("F AND T = T"); END IF;
     IF  TRUE  AND FALSE  THEN FAILED("T AND F = T"); END IF;
     IF  TRUE  AND TRUE   THEN NULL; ELSE FAILED("T AND T = F"); END IF;

     IF  FALSE OR  FALSE  THEN FAILED("F OR F  = T"); END IF;
     IF  FALSE OR  TRUE   THEN NULL; ELSE FAILED("F OR T  = F"); END IF;
     IF  TRUE  OR  FALSE  THEN NULL; ELSE FAILED("T OR F  = F"); END IF;
     IF  TRUE  OR  TRUE   THEN NULL; ELSE FAILED("T OR T  = F"); END IF;

     IF  FALSE XOR FALSE  THEN FAILED("F XOR F = T"); END IF;
     IF  FALSE XOR TRUE   THEN NULL; ELSE FAILED("F XOR T = F"); END IF;
     IF  TRUE  XOR FALSE  THEN NULL; ELSE FAILED("T XOR F = F"); END IF;
     IF  TRUE  XOR TRUE   THEN FAILED("T XOR T = T"); END IF;

     RESULT;

END C45101E;
