-- C45264B.ADA

-- CHECK THAT EQUALITY COMPARISONS YIELD CORRECT RESULTS FOR ONE
-- DIMENSIONAL AND MULTI-DIMENSIONAL ARRAY TYPES.
-- THIS TEST CHECKS THE CASE WHERE THE ARRAY HAS A BOUND THAT DEPENDS ON
-- A DISCRIMINANT WITH DEFAULTS.

-- JWC 11/18/85

WITH REPORT; USE REPORT;

PROCEDURE C45264B IS

BEGIN

     TEST("C45264B","CHECK THAT EQUALITY COMPARISONS YIELD CORRECT " &
                    "RESULTS FOR ONE DIMENSIONAL AND MULTI-"         &
                    "DIMENSIONAL ARRAY TYPES");

     DECLARE

          SUBTYPE SUBINT IS INTEGER RANGE 1 .. 5;
          TYPE REC (DISC : SUBINT := 1) IS
               RECORD
                    COMP : STRING(IDENT_INT(3) .. DISC);
               END RECORD;
          TYPE ARR IS ARRAY (1 .. 3) OF REC;

          A1, A2 : ARR;

     BEGIN

          IF A1 /= A2 THEN
               FAILED ("NULL ARRAYS, RESULT NOT EQUAL");
          END IF;

          A1(2) := (5, "ABC");

          IF A1 = A2 THEN
               FAILED ("NON-NULL ARRAY AND NULL ARRAY, RESULT EQUAL");
          END IF;

          A2(2) := (5, "ABD");

          IF A1 = A2 THEN
               FAILED ("ARRAYS DIFFER BY LAST ELEMENT, RESULT EQUAL");
          END IF;

          A2(2) := (4, "AB");

          IF A1 = A2 THEN
               FAILED ("ARRAYS OF DIFFERENT LENGTH, RESULT EQUAL");
          END IF;

          A1(2) := (4, "AB");

          IF A1 /= A2 THEN
               FAILED ("DISCRIMINANTS AND COMPONENTS ARE THE SAME, " &
                       "RESULT NOT EQUAL");
          END IF;

     END;

     RESULT;

END C45264B;
