-- C45253A.ADA

-- CHECK THAT FOR FIXED POINT TYPES "A IN T" AND "A NOT IN T" GIVE
-- APPROPRIATE RESULTS, EVEN WHEN USER-DEFINED ORDERING OPERATORS EXIST
-- FOR T.

-- WRG 8/27/86

WITH REPORT; USE REPORT;
PROCEDURE C45253A IS

     TYPE FIXED IS DELTA 0.25 RANGE 0.0 .. 1000.0;
     TYPE T IS NEW FIXED;

     FUNCTION "<" (LEFT, RIGHT : T) RETURN BOOLEAN IS
     BEGIN
          RETURN FIXED (LEFT) >= FIXED (RIGHT);
     END "<";

     FUNCTION "<=" (LEFT, RIGHT : T) RETURN BOOLEAN IS
     BEGIN
          RETURN FIXED (LEFT) > FIXED (RIGHT);
     END "<=";

     FUNCTION ">" (LEFT, RIGHT : T) RETURN BOOLEAN IS
     BEGIN
          RETURN FIXED (LEFT) <= FIXED (RIGHT);
     END ">";

     FUNCTION ">=" (LEFT, RIGHT : T) RETURN BOOLEAN IS
     BEGIN
          RETURN FIXED (LEFT) < FIXED (RIGHT);
     END ">=";

BEGIN

     TEST ("C45253A", "CHECK THAT FOR FIXED POINT TYPES ""A IN T"" " &
                      "AND ""A NOT IN T"" GIVE APPROPRIATE RESULTS, " &
                      "EVEN WHEN USER-DEFINED ORDERING OPERATORS " &
                      "EXIST FOR T");

     IF IDENT_INT (1) * 0.0 NOT IN T THEN
          FAILED ("0.0 NOT IN T");
     END IF;

     IF IDENT_INT (1) * 1000.0 NOT IN T THEN
          FAILED ("1000.0 NOT IN T");
     END IF;

     IF IDENT_INT (1) * (-0.25) IN T THEN
          FAILED ("-0.25 IN T");
     END IF;

     IF IDENT_INT (1) * 1000.25 IN T THEN
          FAILED ("1000.25 IN T");
     END IF;

     IF IDENT_INT (1) * (-1000.0) IN T THEN
          FAILED ("-1000.0 IN T");
     END IF;

     RESULT;

END C45253A;
