-- C45281A.ADA

-- CHECK THAT EQUALITY AND INEQUALITY ARE EVALUATED CORRECTLY FOR ACCESS
-- TYPES.

-- TBN  8/8/86

WITH REPORT; USE REPORT;
PROCEDURE C45281A IS

     TYPE STR_NAME IS ACCESS STRING;

     TYPE GENDER IS (F, M);
     TYPE PERSON (SEX : GENDER) IS
          RECORD
               NAME : STRING (1..6) := "NONAME";
          END RECORD;

     TYPE PERSON_NAME IS ACCESS PERSON;
     SUBTYPE MALE IS PERSON_NAME (M);
     SUBTYPE FEMALE IS PERSON_NAME (F);

     S : STR_NAME (1..10) := NEW STRING'("0123456789");
     T : STR_NAME (1..10) := S;
     A : MALE;
     B : FEMALE;
     C : PERSON_NAME;

BEGIN
     TEST ("C45281A", "CHECK THAT EQUALITY AND INEQUALITY ARE " &
                      "EVALUATED CORRECTLY FOR ACCESS TYPES");

     IF "/=" (LEFT => S, RIGHT => T) THEN
          FAILED ("INCORRECT RESULTS FOR ACCESS VALUES - 1");
     END IF;
     T := NEW STRING'("0123456789");
     IF "=" (S, T) THEN
          FAILED ("INCORRECT RESULTS FOR ACCESS VALUES - 2");
     END IF;

     IF A /= B THEN
          FAILED ("INCORRECT RESULTS FOR NULL ACCESS VALUES - 3");
     END IF;
     IF A /= C THEN
          FAILED ("INCORRECT RESULTS FOR NULL ACCESS VALUES - 4");
     END IF;

     A := NEW PERSON'(M, "THOMAS");
     IF "=" (LEFT => A, RIGHT => B) THEN
          FAILED ("INCORRECT RESULTS FOR ACCESS VALUES - 5");
     END IF;
     C := A;
     IF C /= A THEN
          FAILED ("INCORRECT RESULTS FOR ACCESS VALUES - 6");
     END IF;
     C := NEW PERSON'(M, "THOMAS");
     IF A = C THEN
          FAILED ("INCORRECT RESULTS FOR ACCESS VALUES - 7");
     END IF;

     RESULT;
END C45281A;
