-- C45272A.ADA

-- CHECK THAT EQUALITY AND INEQUALITY ARE EVALUATED CORRECTLY FOR 
-- RECORDS WHOSE COMPONENTS HAVE CHANGEABLE DISCRIMINANTS, INCLUDING
-- RECORDS DESIGNATED BY ACCESS VALUES.

-- TBN  8/7/86

WITH REPORT; USE REPORT;
PROCEDURE C45272A IS

     SUBTYPE INT IS INTEGER RANGE 0 .. 20;
     TYPE VARSTR (LEN : INT := 0) IS
          RECORD
               VAL : STRING (1..LEN);
          END RECORD;
     TYPE VARREC IS
          RECORD
               A, B : VARSTR;
          END RECORD;

     TYPE CELL2;
     TYPE LINK IS ACCESS CELL2;
     TYPE CELL1 (NAM_LEN : INT := 0) IS
          RECORD
               NAME : STRING (1..NAM_LEN);
          END RECORD;
     TYPE CELL2 IS
          RECORD
               ONE : CELL1;
               TWO : CELL1;
               NEW_LINK : LINK;
          END RECORD;

     X, Y : VARREC;
     FRONT : LINK := NEW CELL2'((5, "XXYZZ"), (5, "YYYZZ"), NULL);
     BACK : LINK := NEW CELL2'((5, "XXYZZ"), (5, "YYYZZ"), NULL);

BEGIN
     TEST ("C45272A", "CHECK THAT EQUALITY AND INEQUALITY ARE " &
                      "EVALUATED CORRECTLY FOR RECORDS WHOSE " &
                      "COMPONENTS HAVE CHANGEABLE DISCRIMINANTS");

     X := ((5, "AAAXX"), (5, "BBBYY"));
     Y := ((5, "AAAZZ"), (5, "BBBYY"));
     IF X = Y THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 1");
     END IF;

     X.A := (3, "HHH");
     Y.A := (IDENT_INT(3), IDENT_STR("HHH"));
     IF X /= Y THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 2");
     END IF;

     IF FRONT.ALL /= BACK.ALL THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 3");
     END IF;

     BACK.NEW_LINK := FRONT;
     IF FRONT.ALL = BACK.ALL THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 4");
     END IF;

     FRONT.NEW_LINK := FRONT;
     IF FRONT.ALL /= BACK.ALL THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 5");
     END IF;

     FRONT.ONE := (5, "XXXXX");
     BACK.ONE := (5, "ZZZZZ");
     IF FRONT.ALL = BACK.ALL THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 6");
     END IF;

     FRONT.ONE := (3, "XXX");
     BACK.ONE := (3, "XXX");
     IF FRONT.ALL /= BACK.ALL THEN
          FAILED ("INCORRECT RESULTS FOR RECORDS - 7");
     END IF;

     RESULT;
END C45272A;
