-- C45323A.ADA

-- OBJECTIVE:
--     CHECK THAT THE NONASSOCIATIVITY OF REAL ARITHMETIC IS PRESERVED
--     FOR FLOATING POINT PRECISION 5, EVEN WHEN OPTIMIZATION WOULD
--     BENEFIT IF FLOATING POINT ADDITION WERE ASSOCIATIVE.

-- HISTORY:
--     JET 08/10/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C45323A IS

     TYPE FLOAT5 IS DIGITS 5;

     A, B, C, D, E : FLOAT5;

     FUNCTION IDENT(F : FLOAT5) RETURN FLOAT5 IS
     BEGIN
          RETURN F * FLOAT5(IDENT_INT(1));
     END IDENT;

BEGIN
     TEST ("C45323A", "CHECK THAT THE NONASSOCIATIVITY OF REAL " &
                      "ARITHMETIC IS PRESERVED FOR FLOATING POINT " &
                      "PRECISION 5, EVEN WHEN OPTIMIZATION WOULD " &
                      "BENEFIT IF FLOATING POINT ADDITION WERE " &
                      "ASSOCIATIVE");

     B := 2#0.1010_1010_1010_1010_10#E3;
     A := -B;
     C := 2#0.1000_0000_0000_0000_00#E-18;
     D := B + C;
     E := A + B + C;

     IF IDENT(A) + IDENT(B) /= 0.0 THEN
          FAILED("INCORRECT VALUE OF A + B");
     END IF;

     IF IDENT(E) /= IDENT(C) THEN
          FAILED("C DOES NOT EQUAL E");
     END IF;

     RESULT;
END C45323A;
