-- C45413A.ADA

-- CHECK THAT UNARY PLUS AND MINUS YIELD AND ACCEPT RESULTS BELONGING TO
-- THE BASE TYPE.

-- JBG 2/24/84

WITH REPORT; USE REPORT;
PROCEDURE C45413A IS

     TYPE INT IS RANGE 1..10;

     X, Y : INT := INT(IDENT_INT(9));

BEGIN

     TEST ("C45413A", "CHECK SUBTYPE OF UNARY PLUS/MINUS");

     BEGIN

          IF -X /= INT'VAL(-9) THEN
               FAILED ("INCORRECT RESULT - UNARY MINUS");
          END IF;

     EXCEPTION

          WHEN CONSTRAINT_ERROR =>
               FAILED ("UNARY MINUS DOES NOT YIELD RESULT " &
                       "BELONGING TO THE BASE TYPE");
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED - 1");
     END;

     BEGIN

          IF -(INT'VAL(-9)) /= 9 THEN
               FAILED ("WRONG RESULT - UNARY MINUS");
          END IF;

     EXCEPTION

          WHEN CONSTRAINT_ERROR =>
               FAILED ("UNARY MINUS ARGUMENT NOT IN BASE TYPE");
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED - 2");
     END;

     BEGIN

          IF +(INT'VAL(11)) /= 11 THEN
               FAILED ("UNEXPECTED FAILURE");
          END IF;

     EXCEPTION

          WHEN CONSTRAINT_ERROR =>
               FAILED ("CONSTRAINT_ERROR FOR UNARY PLUS OR =");
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED - 3");
     END;

     RESULT;

END C45413A;
