-- C45412A.ADA

-- OBJECTIVE:
--     CHECK THAT NUMERIC_ERROR OR CONSTRAINT_ERROR IS RAISED BY
--     UNARY "-" IF THE RANGE OF INTEGER INDICATES A NONSYMMETRIC
--     RANGE OF VALUES.

-- HISTORY:
--     JET 01/26/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C45412A IS

     A : INTEGER;

BEGIN
     TEST ("C45412A", "CHECK THAT NUMERIC_ERROR OR CONSTRAINT_ERROR " &
                      "IS RAISED BY UNARY ""-"" IF THE RANGE OF " &
                      "INTEGER INDICATES A NONSYMMETRIC RANGE OF " &
                      "VALUES");

     IF INTEGER'FIRST + INTEGER'LAST /= IDENT_INT(0) THEN
          BEGIN
               A := -INTEGER'FIRST;

               FAILED ("NO EXCEPTION RAISED BY UNARY ""-"" " &
                       "ON INTEGER'FIRST");

               IF NOT EQUAL (A,A) THEN
                    COMMENT ("DON'T OPTIMIZE 'A'");
               END IF;
          EXCEPTION
               WHEN NUMERIC_ERROR | CONSTRAINT_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED ("WRONG EXCEPTION RAISED BY UNARY ""-"" " &
                            "ON INTEGER'FIRST");
          END;
     ELSE
          COMMENT ("PREDEFINED INTEGER BASE TYPE IS SYMMETRIC");
     END IF;

     RESULT;

END C45412A;
