-- C45534B.ADA

-- OBJECTIVE:
--     CHECK THAT NUMERIC_ERROR (OR CONSTRAINT_ERROR) IS RAISED WHEN A
--     FIXED POINT VALUE IS DIVIDED BY ZERO (EITHER AN INTEGER ZERO OR
--     A FIXED POINT ZERO).

-- HISTORY:
--     BCB 07/14/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C45534B IS

     TYPE FIX IS DELTA 2.0**(-1) RANGE -2.0 .. 2.0;
     TYPE FIX2 IS DELTA 2.0**(-1) RANGE -3.0 .. 3.0;

     A : FIX := 1.0;
     B : FIX;
     ZERO : FIX := 0.0;
     ZERO2 : FIX2 := 0.0;

     FUNCTION IDENT_FLT (ONE, TWO : FIX) RETURN BOOLEAN IS
     BEGIN
          RETURN ONE = FIX (TWO * FIX (IDENT_INT(1)));
     END IDENT_FLT;

BEGIN
     TEST ("C45534B", "CHECK THAT NUMERIC_ERROR (OR CONSTRAINT_ERROR " &
                      ") IS RAISED WHEN A FIXED POINT VALUE IS " &
                      "DIVIDED BY ZERO (EITHER AN INTEGER ZERO OR A " &
                      "FIXED POINT ZERO)");

     BEGIN
          B := A / IDENT_INT (0);
          FAILED ("NO EXCEPTION RAISED FOR DIVISION BY INTEGER ZERO");
          IF IDENT_FLT (B,B) THEN
               COMMENT ("DON'T OPTIMIZE B");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR | CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED");
     END;

     BEGIN
          B := FIX (A / ZERO);
          FAILED ("NO EXCEPTION RAISED FOR DIVISION BY FIXED POINT " &
                  "ZERO - 1");
          IF IDENT_FLT (B,B) THEN
               COMMENT ("DON'T OPTIMIZE B");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR | CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED");
      END;

     BEGIN
          B := FIX (A / ZERO2);
          FAILED ("NO EXCEPTION RAISED FOR DIVISION BY FIXED POINT " &
                  "ZERO - 2");
          IF IDENT_FLT (B,B) THEN
               COMMENT ("DON'T OPTIMIZE B");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR | CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED");
      END;

     RESULT;
END C45534B;
