-- C45624B.ADA

-- OBJECTIVE:
--     FOR FLOATING POINT TYPES, CHECK WHETHER NUMERIC_ERROR (OR
--     CONSTRAINT_ERROR) IS RAISED IF THE RESULT OF A FLOATING POINT
--     EXPONENTIATION IS OUTSIDE THE RANGE OF THE BASE TYPE AND
--     MACHINE_OVERFLOWS IS FALSE.  THIS TESTS DIGITS 6.

-- HISTORY:
--     BCB 07/14/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C45624B IS

     TYPE FLT IS DIGITS 6;

     F : FLT;

     FUNCTION EQUAL_FLT (ONE, TWO : FLT) RETURN BOOLEAN IS
     BEGIN
          RETURN ONE = TWO * FLT (IDENT_INT(1));
     END EQUAL_FLT;

BEGIN
     TEST ("C45624B", "FOR FLOATING POINT TYPES, CHECK WHETHER " &
                      "NUMERIC_ERROR (OR CONSTRAINT_ERROR) IS RAISED " &
                      "IF MACHINE_OVERFLOWS IS FALSE.  THIS TESTS " &
                      "DIGITS 6");

     IF FLT'MACHINE_OVERFLOWS THEN
          NOT_APPLICABLE ("THIS TEST IS NOT APPLICABLE DUE TO " &
                          "MACHINE_OVERFLOWS BEING TRUE");
     ELSE
          BEGIN
               F := FLT'BASE'LAST**IDENT_INT (2);
               COMMENT ("NEITHER NUMERIC_ERROR OR CONSTRAINT_ERROR " &
                        "WAS RAISED WHEN MACHINE_OVERFLOWS WAS FALSE");
               IF NOT EQUAL_FLT(F,F**IDENT_INT(1)) THEN
                    COMMENT ("DON'T OPTIMIZE F");
               END IF;
          EXCEPTION
               WHEN NUMERIC_ERROR =>
                    COMMENT ("NUMERIC_ERROR WAS RAISED WHEN MACHINE_" &
                             "OVERFLOWS WAS FALSE");
               WHEN CONSTRAINT_ERROR =>
                    COMMENT ("CONSTRAINT_ERROR WAS RAISED WHEN " &
                             "MACHINE_OVERFLOWS WAS FALSE");
               WHEN OTHERS =>
                    FAILED ("AN EXCEPTION OTHER THAN NUMERIC_ERROR " &
                            "OR CONSTRAINT_ERROR WAS RAISED");
          END;
     END IF;

     RESULT;
END C45624B;
