-- C45652A.ADA

-- OBJECTIVE:
--     CHECK THAT NUMERIC_ERROR (OR CONSTRAINT_ERROR) IS RAISED FOR
--     ABSOLUTE VALUE OF FIXED POINT TYPES IF THE RESULT LIES OUTSIDE
--     THE BASE TYPE.

-- HISTORY:
--     BCB 02/03/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SYSTEM;

PROCEDURE C45652A IS

     DEL : CONSTANT := 2.0**(-SYSTEM.MAX_MANTISSA);

     TYPE FIX IS DELTA DEL RANGE -1.0+DEL .. 1.0-DEL;

     A : FIX;

     FUNCTION FIXEQUAL(ONE, TWO : FIX) RETURN BOOLEAN IS
     BEGIN
          RETURN ONE = TWO * IDENT_INT (1);
     END FIXEQUAL;

BEGIN
     TEST ("C45652A", "CHECK THAT NUMERIC_ERROR (OR CONSTRAINT_ERROR)" &
                      " IS RAISED FOR ABSOLUTE VALUE OF FIXED POINT " &
                      "TYPES IF THE RESULT LIES OUTSIDE THE BASE " &
                      "TYPE");

     BEGIN
          A := ABS(-1.5);
          FAILED ("NEITHER CONSTRAINT_ERROR OR NUMERIC_ERROR WAS " &
                  "RAISED");
          IF FIXEQUAL(A,A) THEN
               COMMENT ("DON'T OPTIMIZE A");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR =>
               COMMENT ("NUMERIC_ERROR WAS RAISED");
          WHEN CONSTRAINT_ERROR =>
               COMMENT ("CONSTRAINT_ERROR WAS RAISED");
          WHEN OTHERS =>
               FAILED ("AN EXCEPTION OTHER THAN NUMERIC_ERROR OR " &
                       "CONSTRAINT_ERROR WAS RAISED");
     END;

     RESULT;
END C45652A;
