-- C45612A.ADA

-- OBJECTIVE:
--     CHECK THAT EXPONENTIATION TO LARGE POWERS OF TYPE INTEGER IS
--     CORRECTLY EVALUATED.

-- HISTORY:
--     BCB 02/02/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C45612A IS

     A : INTEGER := 2;

     B : INTEGER;

BEGIN
     TEST ("C45612A", "CHECK THAT EXPONENTIATION TO LARGE POWERS OF " &
                      "TYPE INTEGER IS CORRECTLY EVALUATED");

     IF (1**INTEGER'LAST) /= IDENT_INT (1)
          THEN FAILED ("IMPROPER VALUE FOR 1**INTEGER'LAST");
     END IF;

     IF (1**(INTEGER'LAST-1)) /= IDENT_INT (1)
          THEN FAILED ("IMPROPER VALUE FOR 1**(INTEGER'LAST-1)");
     END IF;

     IF (INTEGER'LAST MOD 2) /= IDENT_INT (0) THEN
          IF ((-1)**INTEGER'LAST) /= IDENT_INT (-1)
               THEN FAILED ("IMPROPER VALUE FOR -1**INTEGER'LAST");
          END IF;
          IF ((-1)**(INTEGER'LAST-1)) /= IDENT_INT (1)
               THEN FAILED ("IMPROPER VALUE FOR -1**(INTEGER'LAST-1)");
          END IF;
     ELSE
          IF ((-1)**INTEGER'LAST) /= IDENT_INT (1)
               THEN FAILED ("IMPROPER VALUE FOR -1**INTEGER'LAST");
          END IF;
          IF ((-1)**(INTEGER'LAST-1)) /= IDENT_INT (-1)
               THEN FAILED ("IMPROPER VALUE FOR -1**(INTEGER'LAST-1)");
          END IF;
     END IF;

     IF (0**INTEGER'LAST) /= IDENT_INT (0)
          THEN FAILED ("IMPROPER VALUE FOR 0**INTEGER'LAST");
     END IF;

     IF (0**(INTEGER'LAST-1)) /= IDENT_INT (0)
          THEN FAILED ("IMPROPER VALUE FOR 0**(INTEGER'LAST-1)");
     END IF;

     B := INTEGER'SIZE-2;

     FOR I IN 1 .. B-1
          LOOP
               A := A * 2;
          END LOOP;

     IF (2**(INTEGER'SIZE-2)) /= A
          THEN FAILED ("IMPROPER VALUE FOR 2**(INTEGER'SIZE-2)");
     END IF;

     RESULT;
END C45612A;
