-- C46022A.ADA

-- OBJECTIVE:
--     CHECK THAT FLOATING POINT CONVERSIONS ARE PERFORMED CORRECTLY
--     FOR LARGE UNIVERSAL_INTEGER LITERALS, AND NEITHER NUMERIC_ERROR
--     OR CONSTRAINT_ERROR IS RAISED BY THESE CONVERSIONS, FOR 5-DIGIT
--     PRECISION.

-- HISTORY:
--     JET 02/12/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C46022A IS

     TYPE FLOAT5 IS DIGITS 5;

BEGIN
     TEST ("C46022A", "CHECK THAT FLOATING POINT CONVERSIONS ARE " &
                      "PERFORMED CORRECTLY FOR LARGE UNIVERSAL_" &
                      "INTEGER LITERALS, AND NEITHER NUMERIC_ERROR " &
                      "OR CONSTRAINT_ERROR IS RAISED BY THESE " &
                      "CONVERSIONS, FOR 5-DIGIT PRECISION");

     BEGIN
          IF FLOAT5(4_722_348_468_471_135_731_712)  /=
                    4_722_348_468_471_135_731_712.0 THEN
               FAILED ("INCORRECT VALUE (1)");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR | CONSTRAINT_ERROR =>
               FAILED ("NUMERIC/CONSTRAINT_ERROR RAISED FOR " &
                       "CONVERSION (1)");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED FOR " &
                       "CONVERSION (1)");
     END;

     BEGIN
          IF FLOAT5(-4_722_348_468_471_135_731_712)  /=
                    -4_722_348_468_471_135_731_712.0 THEN
               FAILED ("INCORRECT VALUE (2)");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR | CONSTRAINT_ERROR =>
               FAILED ("NUMERIC/CONSTRAINT_ERROR RAISED FOR " &
                       "CONVERSION (2)");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED FOR " &
                       "CONVERSION (2)");
     END;

     RESULT;

END C46022A;
