-- C46023A.ADA

-- OBJECTIVE:
--     CHECK THAT FLOATING POINT CONVERSIONS ARE PERFORMED CORRECTLY
--     WHEN THE OPERAND TYPE IS A FLOATING POINT TYPE WITH PRECISION 5.

-- HISTORY:
--     JET 02/16/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C46023A IS

     TYPE FLOAT1 IS DIGITS 1;
     TYPE FLOAT5 IS DIGITS 5;
     SUBTYPE SUBFLOAT1 IS FLOAT5 DIGITS 1;

     F1 : FLOAT1;
     F5 : FLOAT5;

     GENERIC
          TYPE F IS DIGITS <>;
     FUNCTION IDENT (A : F) RETURN F;

     FUNCTION IDENT (A : F) RETURN F IS
     BEGIN
          RETURN A * F(IDENT_INT(1));
     END IDENT;

     FUNCTION IDENT1 IS NEW IDENT(FLOAT1);
     FUNCTION IDENT5 IS NEW IDENT(FLOAT5);

BEGIN
     TEST ("C46023A", "CHECK THAT FLOATING POINT CONVERSIONS ARE " &
                      "PERFORMED CORRECTLY WHEN THE OPERAND TYPE " &
                      "IS A FLOATING POINT TYPE WITH PRECISION 5");

     F5 := IDENT5(2#0.10101#E-1);
     IF FLOAT1(F5) /= 2#0.10101#E-1 THEN
          FAILED ("INCORRECT RESULT FROM CONVERSION (1)");
     END IF;

     F5 := IDENT5(2#0.1010_1010_1010_1010_10#E-1);
     IF FLOAT1(F5) NOT IN 2#0.10101#E-1 .. 2#0.10110#E-1 THEN
          FAILED ("INCORRECT RESULT FROM CONVERSION (2)");
     END IF;

     F1 := IDENT1(2#0.10101#E-1);
     IF FLOAT5(F1) /= 2#0.10101#E-1 THEN
          FAILED ("INCORRECT RESULT FROM CONVERSION (3)");
     END IF;

     IF SUBFLOAT1'MANTISSA < SUBFLOAT1'BASE'MANTISSA THEN
          COMMENT ("SUBFLOAT1 HAS LESS PRECISION THAN ITS BASE TYPE");
          F5 := SUBFLOAT1'BASE'LARGE;
          IF SUBFLOAT1(F5) /= IDENT5(F5) THEN
               FAILED ("SUBFLOAT5 DOES NOT USE THE ACCURACY OF THE " &
                       "BASE TYPE");
          END IF;
     ELSIF SUBFLOAT1'MANTISSA = SUBFLOAT1'BASE'MANTISSA THEN
          COMMENT ("SUBFLOAT1 HAS THE SAME PRECISION AS ITS BASE TYPE");
     ELSE
          FAILED ("SUBFLOAT1 HAS GREATER PRECISION THAN ITS BASE TYPE");
     END IF;

     F5 := IDENT5(1.0 / 3.0);

     IF FLOAT5(IDENT1(FLOAT1(F5))) < F5 AND
        FLOAT5(IDENT1(FLOAT1(-F5))) > -F5 THEN
          COMMENT ("CONVERSION ROUNDS TOWARD ZERO");
     ELSIF FLOAT5(IDENT1(FLOAT1(F5))) > F5 AND
           FLOAT5(IDENT1(FLOAT1(-F5))) < -F5 THEN
          COMMENT ("CONVERSION ROUNDS AWAY FROM ZERO");
     ELSIF FLOAT5(IDENT1(FLOAT1(F5))) < F5 AND
           FLOAT5(IDENT1(FLOAT1(-F5))) < -F5 THEN
          COMMENT ("CONVERSION TRUNCATES DOWN");
     ELSIF FLOAT5(IDENT1(FLOAT1(F5))) > F5 AND
           FLOAT5(IDENT1(FLOAT1(-F5))) > -F5 THEN
          COMMENT ("CONVERSION TRUNCATES UP");
     ELSIF FLOAT5(IDENT1(FLOAT1(F5))) = F5 AND
           FLOAT5(IDENT1(FLOAT1(-F5))) = -F5 THEN
          COMMENT ("CONVERSION HAS NO EFFECT");
     ELSE
          COMMENT ("CONVERSION HAS VARYING EFFECT");
     END IF;

     RESULT;

END C46023A;
