-- C48008C.ADA

-- FOR ALLOCATORS OF THE FORM "NEW T X", CHECK THAT CONSTRAINT_ERROR IS
-- RAISED IF T IS AN UNCONSTRAINED ARRAY TYPE WITH INDEX SUBTYPE(S) S, X
-- IS AN INDEX CONSTRAINT, AND THE BOUNDS OF X ARE NOT COMPATIBLE WITH
-- AN INDEX SUBTYPE OF T.

-- RM 01/08/80
-- NL 10/13/81
-- EG 07/05/84

WITH REPORT;

PROCEDURE C48008C IS

     USE REPORT;

BEGIN

     TEST("C48008C","FOR ALLOCATORS OF THE FORM 'NEW T X', CHECK " &
                    "THAT CONSTRAINT_ERROR IS RAISED WHEN " &
                    "APPROPRIATE - UNCONSTRAINED ARRAY TYPE");

     DECLARE

          SUBTYPE  TWO  IS  INTEGER RANGE 1..2;
          TYPE  TF IS ARRAY( TWO RANGE <> ,  TWO RANGE <> ) OF INTEGER;
          TYPE  ATF  IS  ACCESS TF;
          VF  : ATF;

     BEGIN

          BEGIN
               VF  :=  NEW TF ( 0..1 , 1..2 );
               FAILED ("NO EXCEPTION RAISED - CASE 1");
          EXCEPTION
               WHEN CONSTRAINT_ERROR =>  
                    NULL;
               WHEN OTHERS =>
                    FAILED ("WRONG EXCEPTION RAISED - CASE 1");
          END;

          BEGIN
               VF := NEW TF(1 .. 2, 2 .. IDENT_INT(3));
               FAILED ("NO EXCEPTION RAISED - CASE 2");
          EXCEPTION
               WHEN CONSTRAINT_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED ("WRONG EXCEPTION RAISED - CASE 2");
          END;

     END;

     RESULT;

END C48008C;
