-- C48004A.ADA

-- CHECK THAT THE FORM "NEW T" IS PERMITTED IF T IS A SCALAR SUBTYPE.

-- RM  01/12/80
-- JBG 03/03/83
-- EG  07/05/84

WITH REPORT;

PROCEDURE  C48004A  IS

     USE REPORT;

BEGIN

     TEST("C48004A","CHECK THAT THE FORM 'NEW T' IS PERMITTED IF " &
                    "T IS A SCALAR SUBTYPE");

     DECLARE

          SUBTYPE TA IS INTEGER RANGE 1 .. 7;
          TYPE ATA IS ACCESS TA;
          VA : ATA;

     BEGIN

          VA := NEW TA;
          VA.ALL := IDENT_INT(6);
          IF VA.ALL /= 6 THEN
               FAILED ("INCORRECT VALUE");
          END IF;

     END;

     RESULT;

END C48004A;
