-- C48009C.ADA

-- FOR ALLOCATORS OF THE FORM "NEW T'(X)", CHECK THAT CONSTRAINT_ERROR
-- IS RAISED IF T IS A CONSTRAINED RECORD OR PRIVATE TYPE, (X) IS AN
-- AGGREGATE OR A VALUE OF TYPE T, AND ONE OF THE DISCRIMINANT VALUES IN
-- X:
--   1) DOES NOT EQUAL THE CORRESPONDING DISCRIMINANT VALUE FOR T.
--   2) DOES NOT EQUAL THE CORRESPONDING DISCRIMINANT VALUE SPECIFIED
--      IN THE DECLARATION OF THE ALLOCATOR'S BASE TYPE.
--   3) DOES NOT EQUAL THE CORRESPONDING DISCRIMINANT VALUE IN THE
--      ACCESS TO ACCESS CASE.

-- RM  01/08/80
-- NL  10/13/81
-- SPS 10/26/82
-- EG  07/05/84

WITH REPORT;

PROCEDURE C48009C IS

     USE REPORT;

BEGIN

     TEST("C48009C","FOR ALLOCATORS OF THE FORM 'NEW T'(X)', CHECK " &
                    "THAT CONSTRAINT_ERROR IS RAISED WHEN "          &
                    "APPROPRIATE - CONSTRAINED RECORD TYPES");

     DECLARE

          TYPE TC0(A, B : INTEGER) IS
               RECORD
                    C : INTEGER RANGE 1 .. 7;
               END RECORD;
          SUBTYPE TC IS TC0(2, 3);
          TYPE ATC IS ACCESS TC0(2, 3);
          SUBTYPE TC4_5 IS TC0(IDENT_INT(4), IDENT_INT(5));
          VC : ATC;

     BEGIN

          BEGIN
               VC := NEW TC'(102, 3, 4);
               FAILED ("NO EXCEPTION RAISED - CASE 1");
          EXCEPTION
               WHEN CONSTRAINT_ERROR => NULL;
               WHEN OTHERS           =>  
                    FAILED("WRONG EXCEPTION RAISED - CASE 1");
          END;

          BEGIN
               VC := NEW TC4_5'(IDENT_INT(4), IDENT_INT(5), 1);
               FAILED ("NO EXCEPTION RAISED - CASE 2");
          EXCEPTION
               WHEN CONSTRAINT_ERROR => NULL;
               WHEN OTHERS           =>  
                    FAILED("WRONG EXCEPTION RAISED - CASE 2");
          END;

     END;

     DECLARE

          TYPE UR(A : INTEGER) IS
               RECORD
                    NULL;
               END RECORD;
          TYPE A_UR IS ACCESS UR;
          SUBTYPE CA_UR IS A_UR(2);
          TYPE A_CA_UR IS ACCESS CA_UR;

          V : A_CA_UR;

     BEGIN

          V := NEW CA_UR'(NEW UR'(A => IDENT_INT(3)));
          FAILED ("NO EXCEPTION RAISED - CASE 3");

     EXCEPTION

          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED - CASE 3");

     END;

     RESULT;

END C48009C;
