-- C49020A.ADA

-- CHECK THAT ENUMERATION LITERALS (INCLUDING CHARACTER LITERALS) CAN BE
-- USED IN STATIC EXPRESSIONS TOGETHER WITH RELATIONAL AND EQUALITY 
-- OPERATORS.

-- L.BROWN   09/30/86

WITH REPORT; USE REPORT;
PROCEDURE  C49020A  IS

     CAS_BOL : BOOLEAN := TRUE;
     OBJ1 : INTEGER := 4;
     TYPE ENUM IS (RED,GREEN,BLUE,OFF,ON,'A','B');

BEGIN
     TEST("C49020A","ENUMERATION LITERALS (INCLUDING CHARACTER "&
                    "LITERALS) TOGETHER WITH RELATIONAL OPERATORS "&
                    "CAN BE USED IN STATIC EXPRESSION");

     CASE CAS_BOL IS
          WHEN (RED <= BLUE) =>
               OBJ1 := 5;
          WHEN (BLUE = GREEN) =>
               FAILED("INCORRECT VALUE RETURNED BY ENUMERATION "&
                      "EXPRESSION 1");
     END CASE;

     CAS_BOL := TRUE;

     CASE CAS_BOL IS
          WHEN (GREEN >= ON) =>
               FAILED("INCORRECT VALUE RETURNED BY ENUMERATION "&
                      "EXPRESSION 2");
          WHEN (ENUM'('A') < ENUM'('B')) =>
               OBJ1 := 6;
     END CASE;

     CAS_BOL := TRUE;

     CASE CAS_BOL IS
          WHEN (BLUE > 'B') =>
               FAILED("INCORRECT VALUE RETURNED BY ENUMERATION "&
                      "EXPRESSION 3");
          WHEN (OFF /= 'A') =>
               OBJ1 := 7;
     END CASE;

     RESULT;

END C49020A;
