-- C49026A.ADA

-- CHECK THAT A QUALIFIED EXPRESSION CAN APPEAR IN A STATIC EXPRESSION.

-- L.BROWN  10/07/86

WITH REPORT; USE REPORT;

PROCEDURE  C49026A  IS

     TYPE ENUM IS (RED,GREEN,BLUE,YELLOW);
     TYPE INT1 IS RANGE 1 .. 50;
     TYPE FLT1 IS DIGITS 3 RANGE 1.0 .. 5.0;
     TYPE FIX1 IS DELTA 0.125 RANGE 0.0 .. 10.0;
     TYPE INT2 IS RANGE 1 .. INT1'(25);
     TYPE FLT2 IS DIGITS 3 RANGE 1.0 .. FLT1'(2.0);
     TYPE FIX2 IS DELTA 0.125 RANGE 0.0 .. FIX1'(5.0);
     TYPE FLT3 IS DIGITS INT1'(3);
     TYPE FIX3 IS DELTA FIX1'(0.125) RANGE 0.0 .. 5.0;
     OBJ1 : INTEGER := 2;
     CAS_OBJ : ENUM := GREEN;

BEGIN

     TEST("C49026A","QUALIFIED EXPRESSIONS CAN APPEAR IN STATIC "&
                    "EXPRESSIONS");

     CASE CAS_OBJ IS
          WHEN ENUM'(GREEN) =>
               OBJ1 := 3;
          WHEN OTHERS =>
               FAILED("INCORRECT VALUE FOR QUALIFIED EXPRESSION 1");
     END CASE;

     RESULT;

END C49026A;
