-- C49021A.ADA

-- CHECK THAT BOOLEAN LITERALS CAN BE USED IN STATIC EXPRESSIONS 
-- TOGETHER WITH THE LOGICAL OPERATORS, THE NOT OPERATOR, AND THE
-- RELATIONAL AND EQUALITY OPERATORS.

-- L.BROWN  09/25/86

WITH REPORT; USE REPORT;
PROCEDURE  C49021A  IS

     CAS_BOL : BOOLEAN := TRUE;
     X1 : CONSTANT := BOOLEAN'POS((TRUE AND FALSE)OR(TRUE AND TRUE));
     X2 : CONSTANT := BOOLEAN'POS((TRUE <= FALSE)AND(FALSE >= FALSE));

BEGIN
     TEST("C49021A","BOOLEAN LITERALS TOGETHER WITH CERTAIN OPERATORS,"&
                    "CAN BE USED IN STATIC EXPRESSIONS.");
     IF X1 /= 1  THEN
          FAILED("INCORRECT VALUE RETURNED BY BOOLEAN EXPRESSION 1");
     END IF;

     IF X2 /= 0  THEN
          FAILED("INCORRECT VALUE RETURNED BY BOOLEAN EXPRESSION 2");
     END IF;

     CASE CAS_BOL IS
          WHEN ((TRUE AND FALSE) XOR (TRUE XOR TRUE)) =>
               FAILED("INCORRECT VALUE RETURNED BY BOOLEAN " &
                      "EXPRESSION 2");
          WHEN OTHERS =>
               CAS_BOL := TRUE;
     END CASE;

     CASE CAS_BOL IS
          WHEN ((TRUE > FALSE) OR (FALSE <= TRUE)) =>
               CAS_BOL := TRUE;
          WHEN OTHERS =>
               FAILED("INCORRECT VALUE RETURNED BY BOOLEAN " &
                      "EXPRESSION 3");
     END CASE;

     CASE CAS_BOL IS
          WHEN NOT((TRUE OR FALSE) = (FALSE AND TRUE)) =>
               CAS_BOL := TRUE;
          WHEN OTHERS =>
               FAILED("INCORRECT VALUE RETURNED BY BOOLEAN " &
                      "EXPRESSION 4");
     END CASE;

     CASE CAS_BOL IS
          WHEN (((TRUE = FALSE) OR (FALSE AND TRUE)) /= (TRUE < TRUE))=>
               FAILED("INCORRECT VALUE RETURNED BY BOOLEAN " &
                      "EXPRESSION 5");
          WHEN OTHERS =>
               CAS_BOL := TRUE;
     END CASE;

     RESULT;

END C49021A;
