-- C4A014A.ADA

-- CHECK THAT ROUNDING IS DONE CORRECTLY FOR STATIC UNIVERSAL REAL
-- EXPRESSIONS, AND CHECK THE METHOD OF ROUNDING USED.

-- JBG 5/3/85
-- JBG 11/3/85   DECLARE INTEGER CONSTANTS INSTEAD OF UNIVERSAL INTEGER

WITH REPORT; USE REPORT;
PROCEDURE C4A014A IS

     TYPE ACC_STRING IS ACCESS STRING;
     MODE : ACC_STRING;

     C15  : CONSTANT := 1.5;
     C25  : CONSTANT := 2.5;
     CN15 : CONSTANT := -1.5;
     CN25 : CONSTANT := -2.5;

     C15R  : CONSTANT INTEGER := INTEGER(C15);
     C25R  : CONSTANT INTEGER := INTEGER(C25);
     CN15R : CONSTANT INTEGER := INTEGER(CN15);
     CN25R : CONSTANT INTEGER := INTEGER(CN25);

     C15_1   : BOOLEAN := 1 = C15R;
     C15_2   : BOOLEAN := 2 = C15R;
     C25_2   : BOOLEAN := 2 = C25R;
     C25_3   : BOOLEAN := 3 = C25R;

     CN15_N1 : BOOLEAN := -1 = CN15R;
     CN15_N2 : BOOLEAN := -2 = CN15R;
     CN25_N2 : BOOLEAN := -2 = CN25R;
     CN25_N3 : BOOLEAN := -3 = CN25R;

BEGIN

     TEST ("C4A014A", "CHECK ROUNDING TO INTEGER FOR UNIVERSAL REAL " &
                      "EXPRESSIONS");

     IF 1 /= INTEGER(1.4) THEN
          FAILED ("INTEGER(1.4) DOES NOT EQUAL 1");
     END IF;

     IF 2 /= INTEGER(1.6) THEN
          FAILED ("INTEGER(1.6) DOES NOT EQUAL 2");
     END IF;

     IF -1 /= INTEGER(-1.4) THEN
          FAILED ("INTEGER(-1.4) DOES NOT EQUAL -1");
     END IF;

     IF -2 /= INTEGER(-1.6) THEN
          FAILED ("INTEGER(-1.6) DOES NOT EQUAL -2");
     END IF;

     COMMENT ("1.5 IS ROUNDED TO" & INTEGER'IMAGE(C15R));
     COMMENT ("2.5 IS ROUNDED TO" & INTEGER'IMAGE(C25R));
     COMMENT ("-1.5 IS ROUNDED TO " & INTEGER'IMAGE(CN15R));
     COMMENT ("-2.5 IS ROUNDED TO " & INTEGER'IMAGE(CN25R));


     IF C15_2 AND C25_3 AND CN15_N1 AND CN25_N2 THEN
          MODE := NEW STRING'("ROUND TO +INFINITY");
     ELSIF C15_1 AND C25_2 AND CN15_N2 AND CN25_N3 THEN
          MODE := NEW STRING'("ROUND TO -INFINITY");
     ELSIF C15_1 AND C25_2 AND CN15_N1 AND CN25_N2 THEN
          MODE := NEW STRING'("ROUND TO ZERO");
     ELSIF C15_2 AND C25_3 AND CN15_N2 AND CN25_N3 THEN
          MODE := NEW STRING'("ROUND AWAY FROM ZERO");
     ELSIF C15_2 AND C25_2 THEN
          MODE := NEW STRING'("ROUND TO EVEN - CHECK RESULTS FOR " &
                              "NEGATIVE VALUES");
     ELSIF C15_1 AND C25_3 THEN
          MODE := NEW STRING'("ROUND TO ODD - CHECK RESULTS FOR " &
                              "NEGATIVE VALUES");
     ELSE
          MODE := NEW STRING'("UNKNOWN");
     END IF;

     COMMENT ("THE ROUNDING APPROACH USED IS APPARENTLY: " & MODE.ALL);

     IF NOT (C15_1 OR C15_2) OR (NOT (C25_2 OR C25_3)) THEN
          FAILED ("ROUNDING OF POSITIVE VALUES NOT CORRECT");
     END IF;

     IF NOT (CN15_N1 OR CN15_N2) OR (NOT (CN25_N2 OR CN25_N3)) THEN
          FAILED ("ROUNDING OF NEGATIVE VALUES NOT CORRECT");
     END IF;

     RESULT;

END C4A014A;
