-- C4A007A.TST

-- USE OF MAX_INT IN NUMBER DECLARATION

-- BAW 29 SEPT 80

WITH REPORT;
PROCEDURE C4A007A IS

     USE REPORT;

     X : CONSTANT := $MAX_INT - ($MAX_INT MOD 2);
     Y : CONSTANT := ($MAX_INT / 2) * 2;

BEGIN TEST("C4A007A","USING THE INTEGER VALUE  MAX_INT IN NUMBER " &
           " DECLARATIONS ");

      IF X /= Y
      THEN FAILED("USING THE INTEGER VALUE MAX_INT GIVES " &
                  " GIVES WRONG RESULTS ");
      END IF;

      RESULT;

END C4A007A;
