-- C4A013A.ADA

-- CHECK THAT NUMERIC_ERROR/CONSTRAINT_ERROR IS RAISED FOR A NONSTATIC
-- UNIVERSAL_REAL EXPRESSION IF THE VALUE WOULD LIE OUTSIDE THE RANGE OF
-- THE BASE TYPE OF THE MOST ACCURATE PREDEFINED FLOATING POINT TYPE AND
-- MACHINE_OVERFLOWS IS TRUE FOR THAT TYPE.

-- BAW 29 SEPT 80
-- TBN 10/30/85     RENAMED FROM C4A013A.ADA.
-- JRK 1/13/86      COMPLETELY REVISED TO CHECK NONSTATIC UNIVERSAL_REAL
--                  EXPRESSIONS WHOSE RESULTS OVERFLOW.  REVISED
--                  NUMERIC_ERROR/CONSTRAINT_ERROR ACCORDING TO
--                  AI-00387.

WITH SYSTEM, REPORT;
USE SYSTEM, REPORT;

PROCEDURE C4A013A IS

     TYPE F IS DIGITS MAX_DIGITS;

     B : BOOLEAN;

BEGIN
     TEST ("C4A013A", "CHECK NONSTATIC UNIVERSAL_REAL EXPRESSIONS " &
                      "WHOSE RESULTS OVERFLOW");

     BEGIN
          B := 1.0 < 1.0 / (1.0 * INTEGER'POS (IDENT_INT (0)));

          IF F'MACHINE_OVERFLOWS THEN
               FAILED ("MACHINE_OVERFLOWS IS TRUE, BUT NO EXCEPTION " &
                       "WAS RAISED");
          ELSE COMMENT ("MACHINE_OVERFLOWS IS FALSE AND NO EXCEPTION " &
                        "WAS RAISED");
          END IF;

          IF NOT B THEN  -- USE B TO PREVENT DEAD VARIABLE OPTIMIZATION.
               COMMENT ("1.0 < 1.0 / 0.0 YIELDS FALSE");
          END IF;
     EXCEPTION
          WHEN NUMERIC_ERROR =>
               COMMENT ("NUMERIC_ERROR RAISED");
          WHEN CONSTRAINT_ERROR =>
               COMMENT ("CONSTRAINT_ERROR RAISED");
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED");
     END;

     RESULT;
END C4A013A;
