-- C51002A.ADA

-- CHECK THAT THE STATEMENTS IN A SEQUENCE OF STATEMENTS ARE
--    EXECUTED IN SUCCESSION, THAT SINGLE AND MULTIPLE LABELS
--    HAVE NO EFFECT, AND THAT LABELS ARE PERMITTED AT THE
--    BEGINNING OF A SEQUENCE_OF_STATEMENTS IN THE FOLLOWING
--    BODY CONTEXTS:  PACKAGE, PROCEDURE, BLOCK, IF, CASE, AND LOOP.

-- DCB 02/27/80
-- JRK 10/30/80
-- SPS 3/15/83

WITH REPORT;
PROCEDURE C51002A IS

     USE REPORT;

     I1, I2, I4 : INTEGER;
     FLOW_COUNT : INTEGER := 0;                 -- 0

     PACKAGE P IS
          C1 : CHARACTER;
     END P;

     PACKAGE BODY P IS
     BEGIN   -- LABEL AT START OF PACKAGE BODY.
<<L10>>   FLOW_COUNT := FLOW_COUNT + 1;         -- 1
     END P;

BEGIN     -- LABEL AT START OF PROCEDURE BODY.
<<L0>>
     TEST("C51002A", "SEQUENTIAL EXECUTION OF STATEMENTS " &
                             "AND NON-INTERFERENCE OF LABELS");

     FLOW_COUNT := FLOW_COUNT + 2;              -- 3
     I1 := 3;
<<L1>>
     FLOW_COUNT := FLOW_COUNT + FLOW_COUNT;     -- 6
<<L2>> <<L3>> <<L4>>
     FLOW_COUNT := FLOW_COUNT * FLOW_COUNT;     -- 36
<<L5>>
     FLOW_COUNT := FLOW_COUNT + 4;              -- 40

     BEGIN     -- LABEL AT START OF BLOCK BODY.
<<L6>>
          FLOW_COUNT := FLOW_COUNT + 1;
     END;

     IF TRUE THEN    -- LABEL AT START OF IF BODY.
<<L7>>
          FLOW_COUNT := FLOW_COUNT + 1;
     END IF;

     CASE I1 IS        -- LABEL AT START OF CASE BODY.
          WHEN 3 =>
<<L8>>         FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               NULL;
     END CASE;

     WHILE I1 <= 3 LOOP     -- LABEL AT START OF LOOP BODY.
<<L9>>    I1 := 4;
          FLOW_COUNT := FLOW_COUNT + 1;
     END LOOP;

     IF FLOW_COUNT /= 44 THEN
          FAILED("SEQUENCE OF STMTS NOT EXECUTED IN SUCCESSION");
     END IF;

     RESULT;
END C51002A;
