-- C52005F.ADA

-- CHECK THAT THE CONSTRAINT_ERROR EXCEPTION IS RAISED
--    WHEN A DYNAMIC EXPRESSION VALUE IS OUTSIDE THE STATIC RANGE
--    OF FIXED POINT ASSIGNMENTS.

-- JRK 7/21/80
-- SPS 3/21/83

WITH REPORT;
PROCEDURE C52005F IS

     USE REPORT;

BEGIN
     TEST ("C52005F", "CHECK THAT CONSTRAINT_ERROR EXCEPTION IS RAISED"
         & " ON DYNAMIC OUT OF RANGE FIXED POINT ASSIGNMENTS");

-----------------------

     DECLARE
          TYPE REAL IS DELTA 0.01 RANGE 0.00 .. 9.99;
          FX : REAL := 4.50;
          FX1 : REAL RANGE 0.00 .. 7.00 := 4.50;

     BEGIN
          IF EQUAL(3,3) THEN
               FX := 7.01;
          END IF;
          FX1 := FX;

          FAILED ("EXCEPTION NOT RAISED FOR OUT OF RANGE FIXED ASSNMT");

     EXCEPTION
     WHEN CONSTRAINT_ERROR =>
          IF FX1 /= 4.50 THEN
               FAILED ("VALUE ALTERED BEFORE FIXED PT RANGE EXCEPTION");
          END IF;

     END;

-------------------------

     DECLARE
          TYPE REAL IS DELTA 0.01 RANGE 0.00 .. 9.99;
          FX : REAL := 4.50;
          FX2 : REAL RANGE 0.00 .. 7.00 := 4.50;

     BEGIN
          IF EQUAL(3,3) THEN
               FX := 7.00;
          END IF;
          FX2 := FX;

     EXCEPTION
     WHEN CONSTRAINT_ERROR =>
          FAILED ("EXCEPTION RAISED ON LEGAL FIXED PT ASSNMT");

     END;

-------------------------

     RESULT;
END C52005F;
