-- C52001B.ADA

-- CHECK THAT AN ASSIGNMENT STATEMENT REPLACES THE CURRENT VALUE
--    OF THE TARGET VARIABLE FOR FLOAT TYPE VALUES.

-- DCB 1/31/80
-- JRK 10/30/80
-- SPS 3/21/83

WITH REPORT;
PROCEDURE C52001B IS

     USE REPORT;

     TYPE FLT IS DIGITS 3 RANGE -1.0E10 .. 1.0E10;

     FL1, FL2 : FLT;

     FL3 : FLOAT;

BEGIN
     TEST ("C52001B", "CHECK THAT ASSIGNMENT STMTS WORK FOR FLOAT "&
                      "TYPES");

     FL1 := 0.0;
     FL2 := -1.0;
     IF EQUAL(3,3) THEN
          FL1 := 23.25;
     END IF;
     IF EQUAL(2,2) THEN
          FL2 := FL1;
     END IF;
     IF FL2 /= 23.25 OR FL1 /= FL2 THEN
          FAILED ("USER DEFINED FLOAT TYPE ASSIGNMENT NOT WORKING");
     END IF;

     FL3 := 0.0;
     IF EQUAL(3,3) THEN
          FL3 := 83.5;
     END IF;
     IF  FL3 /= 83.5 THEN
         FAILED("PREDEFINED FLOAT TYPE ASSIGNMENT NOT WORKING");
     END IF;

     RESULT;
END C52001B;
