-- C52005C.ADA

-- CHECK THAT THE CONSTRAINT_ERROR EXCEPTION IS RAISED
--    WHEN A STATIC EXPRESSION VALUE IS OUTSIDE THE STATIC RANGE
--    OF FIXED POINT ASSIGNMENTS.

-- DCB 2/6/80
-- JRK 7/21/80
-- SPS 3/21/83

WITH REPORT;
PROCEDURE C52005C IS

     USE REPORT;

BEGIN
     TEST ("C52005C", "CHECK THAT CONSTRAINT_ERROR EXCEPTION IS RAISED"
         & " ON STATIC OUT OF RANGE FIXED POINT ASSIGNMENTS");

-----------------------

     DECLARE
          TYPE REAL IS DELTA 0.01 RANGE 0.00 .. 9.99;
          FX1 : REAL RANGE 0.00 .. 7.00 := 4.50;

     BEGIN
          FX1 := 7.01;

          FAILED ("EXCEPTION NOT RAISED FOR OUT OF RANGE FIXED ASSNMT");

     EXCEPTION
     WHEN CONSTRAINT_ERROR =>
          IF FX1 /= 4.50 THEN
               FAILED ("VALUE ALTERED BEFORE FIXED PT RANGE EXCEPTION");
          END IF;

     END;

-------------------------

     DECLARE
          TYPE REAL IS DELTA 0.01 RANGE 0.00 .. 9.99;
          FX2 : REAL RANGE 0.00 .. 7.00 := 4.50;

     BEGIN
          FX2 := 7.00;

     EXCEPTION
     WHEN CONSTRAINT_ERROR =>
          FAILED ("EXCEPTION RAISED ON LEGAL FIXED PT ASSNMT");

     END;

-------------------------

     RESULT;
END C52005C;
