-- C52009B.ADA
 
-- CHECK THAT A RECORD VARIABLE DESIGNATED BY AN ACCESS VALUE CANNOT
-- HAVE ITS DISCRIMINANT ALTERED, EVEN BY A COMPLETE RECORD
-- ASSIGNMENT, AND EVEN THOUGH THE THE TARGET ACCESS VARIABLE IS NOT 
-- CONSTRAINED TO A SPECIFIC DISCRIMINANT VALUE.  ATTEMPTING TO
-- CHANGE THE TARGET'S DISCRIMINANT RAISES CONSTRAINT_ERROR AND LEAVES 
-- THE TARGET RECORD UNALTERED.  THIS TEST USES NON-STATIC DISCRIMINANT 
-- VALUES AND A TYPE WITH DEFAULT DISCRIMINANTS.
 
-- ASL 7/6/81
-- SPS 10/26/82
-- JBG 1/10/84

WITH REPORT;
PROCEDURE C52009B IS
 
     USE REPORT;
 
     TYPE REC(DISC : INTEGER := 5) IS
          RECORD
               COMP : INTEGER := 0;
          END RECORD;
 
     TYPE REC_NAME IS ACCESS REC;
 
     HR : REC_NAME := NEW REC;
 
BEGIN
 
     TEST ("C52009B", "CANNOT CHANGE, THROUGH ASSIGNMENT, THE " &
           "(DYNAMIC) DISCRIMINANT VALUE OF A RECORD DESIGNATED " &
           "BY AN ACCESS VALUE");
 
     BEGIN
          HR.ALL := (DISC => IDENT_INT(5), COMP => 3);
          IF HR.ALL /= (IDENT_INT(5),3) THEN
               FAILED ("LEGAL ASSIGNMENT FAILED");
          END IF;
     EXCEPTION
          WHEN CONSTRAINT_ERROR => 
               FAILED ("CONSTRAINT_ERROR RAISED WHEN DISCRIMINANT " &
                       "VALUE NOT CHANGED");
     END;

     BEGIN
          HR.ALL := (DISC => IDENT_INT(4), COMP => 2);
          FAILED ("RECORD ASSIGNED VALUE WITH DIFFERENT DISCRIMINANT " &
                  "VALUE");
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               COMMENT ("DETECTED ATTEMPT TO CHANGE DISCRIMINANT " &
                        "VALUE");
          WHEN OTHERS => FAILED ("WRONG EXCEPTION");
     END;
 
     RESULT;
 
END C52009B;
