-- C52001C.ADA

-- CHECK THAT AN ASSIGNMENT STATEMENT REPLACES THE CURRENT VALUE
--    OF THE TARGET VARIABLE FOR FIXED TYPE VALUES.

-- DCB 1/30/80
-- JRK 10/30/80
-- SPS 3/21/83

WITH REPORT;
PROCEDURE C52001C IS

     USE REPORT;

     TYPE FIXED IS DELTA 0.1 RANGE -100.0 .. 100.0;

     FX1, FX2 : FIXED;

BEGIN
     TEST ("C52001C", "CHECK THAT ASSIGNMENT STMTS WORK FOR FIXED "&
                      "TYPES");

     FX1 := 0.0;
     FX2 := -1.0;
     IF EQUAL(3,3) THEN
          FX1 := 33.5;
     END IF;
     IF EQUAL(2,2) THEN
          FX2 := FX1;
     END IF;
     IF FX2 /= 33.5 OR FX1 /= FX2 THEN
          FAILED ("FIXED TYPE ASSIGNMENT NOT WORKING");
     END IF;

     RESULT;
END C52001C;
