-- C52104Y.ADA

-- CHECK THAT LENGTHS MUST MATCH IN ARRAY AND SLICE ASSIGNMENTS.
--    MORE SPECIFICALLY, TEST THAT ATTEMPTED ASSIGNMENTS BETWEEN
--    ARRAYS WITH NON-MATCHING LENGTHS LEAVE THE DESTINATION ARRAY
--    INTACT AND CAUSE  CONSTRAINT_ERROR  TO BE RAISED.
--    (OVERLAPS BETWEEN THE OPERANDS OF THE ASSIGNMENT STATEMENT
--    ARE TREATED ELSEWHERE.)

-- THIS IS A SPECIAL CASE IN

--    DIVISION  D :  NULL ARRAYS WHOSE LENGTHS ARE NOT DETERMINABLE
--                   STATICALLY

-- WHICH (THE SPECIAL CASE) TREATS TWO-DIMENSIONAL ARRAYS WHOSE LENGTH
--    ALONG ONE DIMENSION IS GREATER THAN  INTEGER'LAST  AND WHOSE
--    LENGTH ALONG THE OTHER DIMENSION IS  0 .
--    AN ADDITIONAL OBJECTIVE OF THIS TEST IS TO CHECK WHETHER LENGTH
--    COMPARISONS (AND LENGTH COMPUTATIONS) CAUSE  NUMERIC_ERROR
--    TO BE RAISED.

-- RM  07/31/81
-- SPS 03/22/83
-- JBG 06/16/83
-- EG  10/28/85  FIX NUMERIC_ERROR/CONSTRAINT_ERROR ACCORDING TO
--               AI-00387.

WITH REPORT;
PROCEDURE  C52104Y  IS

     USE  REPORT ;

BEGIN

     TEST( "C52104Y" , "CHECK THAT IN ARRAY ASSIGNMENTS AND IN SLICE" &
                       " ASSIGNMENTS, THE LENGTHS MUST MATCH" );

     -- IN THIS TEST WE CAN'T USE AGGREGATE ASSIGNMENT (EXCEPT WHEN
     --    THE AGGREGATES ARE STRING LITERALS); THEREFORE:
     --
     --    (1) ARRAYS WILL BE INITIALIZED BY INDIVIDUAL ASSIGNMENTS;
     --    (2) CAN'T USE NON-NULL CONSTANT ARRAYS.


     -- WE ASSUME THAT IN AN ARRAY_TYPE_DEFINITION THE INDEX PORTION
     --    AND THE COMPONENT_TYPE PORTION ARE FUNCTIONALLY ORTHOGONAL
     --    ALSO AT THE IMPLEMENTATION LEVEL, I.E. THAT THE CORRECTNESS
     --    OF THE ACCESSING MECHANISM FOR ARRAYS DOES NOT DEPEND ON
     --    COMPONENT_TYPE.  ACCORDINGLY WE ARE TESTING FOR SOME BUT
     --    NOT ALL KINDS OF COMPONENT_TYPE.  (COMPONENT_TYPES INCLUDED:
     --    INTEGER , CHARACTER , BOOLEAN .)


     -------------------------------------------------------------------

     --   (10) MULTIDIMENSIONAL ARRAY OBJECTS WHOSE TYPEMARKS WERE
     --        DEFINED USING THE "BOX" COMPOUND SYMBOL.
     --        (TWO-DIMENSIONAL ARRAYS OF BOOLEANS.)

NUM_ERR:
     BEGIN          -- THIS BLOCK CATCHES NUMERIC_ERROR IF IT IS
                    -- RAISED BY THE SUBTYPE DECLARATION.

DCL_ARR:  DECLARE

               TYPE  TABOX5  IS  ARRAY( INTEGER RANGE <> ,
                                        INTEGER RANGE <> )  OF BOOLEAN ;
               PRAGMA PACK (TABOX5);

               SUBTYPE  TABOX52  IS  TABOX5(
                         IDENT_INT(13)..IDENT_INT(       13       ) ,
                         IDENT_INT(-6)..IDENT_INT( INTEGER'LAST-4 ) );

          BEGIN

               COMMENT ("NO NUMERIC_ERROR FOR NON-NULL ARRAY SUBTYPE " &
                        "WHEN ONE DIMENSION HAS INTEGER'LAST + 3 " &
                        "COMPONENTS");

OBJ_DCL:       DECLARE   -- THIS BLOCK DECLARES ONE NULL ARRAY AND ONE
                         -- PACKED BOOLEAN ARRAY WITH INTEGER'LAST + 3
                         -- COMPONENTS;  STORAGE ERROR MAY BE RAISED.

                    ARRX51  :  TABOX5(
                         IDENT_INT(13)..IDENT_INT(       12       ) ,
                         IDENT_INT(-6)..IDENT_INT( INTEGER'LAST-4 ) );
                    ARRX52  :  TABOX52 ;     -- BIG ARRAY HERE.

               BEGIN

                    COMMENT ("NO NUMERIC OR STORAGE ERROR WHEN ARRAY "&
                            "WITH INTEGER'LAST+3 COMPONENTS ALLOCATED");

               -- NULL ARRAY ASSIGNMENT:

                    ARRX52 := ARRX51 ;
                    FAILED( "EXCEPTION NOT RAISED  (10)" );

               EXCEPTION

                    WHEN CONSTRAINT_ERROR =>
                         COMMENT ("CONSTRAINT_ERROR RAISED WHEN " &
                                  "CHECKING LENGTHS FOR ARRAY HAVING " &
                                  "> INTEGER'LAST COMPONENTS ON ONE " &
                                  "DIMENSION");

                    WHEN NUMERIC_ERROR  =>
                         COMMENT ("NUMERIC_ERROR RAISED WHEN CHECKING "&
                                  "LENGTHS FOR ARRAY HAVING > INTEGER"&
                                  "'LAST COMPONENTS ON ONE DIMENSION");

                    WHEN  OTHERS  =>
                         FAILED( "OTHER EXCEPTION RAISED - SUBTEST 10");

               END OBJ_DCL;

          EXCEPTION

               WHEN STORAGE_ERROR =>
                    COMMENT ("STORAGE_ERROR RAISED WHEN DECLARING ONE "&
                             "PACKED BOOLEAN ARRAY WITH INTEGER'LAST "&
                             "+ 3 COMPONENTS");
               WHEN NUMERIC_ERROR =>
                    COMMENT ("NUMERIC_ERROR RAISED WHEN DECLARING ONE "&
                             "PACKED BOOLEAN ARRAY WITH INTEGER'LAST "&
                             "+ 3 COMPONENTS");
               WHEN CONSTRAINT_ERROR =>
                    COMMENT ("CONSTRAINT_ERROR RAISED WHEN DECLARING "&
                             "ONE PACKED BOOLEAN ARRAY WITH "&
                             "INTEGER'LAST + 3 COMPONENTS");
               WHEN OTHERS =>
                    FAILED ("SOME EXCEPTION RAISED - 3");

          END DCL_ARR;

     EXCEPTION

          WHEN NUMERIC_ERROR =>
               COMMENT ("NUMERIC_ERROR RAISED WHEN DECLARING AN " &
                        "ARRAY SUBTYPE WITH INTEGER'LAST + 3 " &
                        "COMPONENTS");

          WHEN CONSTRAINT_ERROR =>
               COMMENT ("CONSTRAINT_ERROR RAISED WHEN DECLARING AN " &
                        "ARRAY SUBTYPE WITH INTEGER'LAST + 3 " &
                        "COMPONENTS");

          WHEN STORAGE_ERROR =>
               FAILED ("STORAGE_ERROR RAISED FOR TYPE DECLARATION");

          WHEN  OTHERS  =>
               FAILED( "OTHER EXCEPTION RAISED - 4");

     END NUM_ERR;

     RESULT ;

END C52104Y;
