-- C52101A.ADA

-- CHECK THAT ARRAY SUBTYPE CONVERSION IS APPLIED AFTER AN ARRAY VALUE
-- IS DETERMINED.

-- BHS 6/22/84

WITH REPORT;
PROCEDURE C52101A IS

     USE REPORT;

     TYPE DAY IS (MON, TUE, WED, THU, FRI, SAT, SUN);
     SUBTYPE WEEKDAY IS DAY RANGE MON..FRI;

     TYPE ARR IS ARRAY  (WEEKDAY RANGE <>) OF INTEGER;
     TYPE ARR_DAY IS ARRAY (DAY RANGE <>) OF INTEGER;

     NORM     : ARR (MON..FRI);          -- INDEX SUBTYPE WEEKDAY
     NORM_DAY : ARR_DAY (MON..FRI);      -- INDEX SUBTYPE DAY

BEGIN
     TEST ("C52101A", "CHECK THAT ARRAY SUBTYPE CONVERSION " &
                      "APPLIED AFTER ARRAY VAL. DETERMINED");

     BEGIN   -- ILLEGAL CASE
          NORM := (WED..SUN => 0);        -- ERROR: INDEX SUBTYPE

          FAILED ("EXCEPTION NOT RAISED FOR INDEX SUBTYPE ERROR");

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               COMMENT ("IMPROPER AGGREGATE BOUNDS DETECTED");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED");

     END;


     BEGIN    -- LEGAL CASE
          NORM_DAY := (WED..FRI => 0, SAT..SUN => 1);
          IF NORM_DAY /= ( 0, 0, IDENT_INT(0), IDENT_INT(1),
                                               IDENT_INT(1)) THEN
               FAILED ("INCORRECT ASSIGNMENT IN LEGAL CASE");
          END IF;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               FAILED ("CONSTRAINT_ERROR RAISED ON LEGAL INDEX " &
                       "SUBTYPE CONVERSION");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED IN LEGAL CASE");

     END;


     RESULT;

END C52101A;
