-- C53004B.ADA


-- CHECK THAT CONDITIONS OF A TYPE DERIVED FROM  'BOOLEAN'  ARE ALLOWED
--     IN IF_STATEMENTS.


--  RM 07/22/82
-- SPS 2/7/83

WITH REPORT;
PROCEDURE C53004B IS

     USE REPORT;

     TYPE  NEW_BOOL  IS NEW BOOLEAN ;

     I9 : CONSTANT INTEGER := 9;
     NBF: CONSTANT NEW_BOOL:= NEW_BOOL(IDENT_BOOL(FALSE));
     FLOW_COUNT  : INTEGER := 0 ;

BEGIN

     TEST ( "C53004B" , "DERIVED-BOOLEAN CONDITIONS IN  'IF' " );

     IF  NEW_BOOL'( FALSE )  THEN
          FAILED("  WRONG BRANCH TAKEN  -  NEW_BOOL'( FALSE )  ");
     END IF;

     IF  NBF  THEN
          FAILED("  WRONG BRANCH TAKEN  -  NBF  ");
     END IF;

     IF  NEW_BOOL( I9 < 5 )  THEN
          FAILED(" WRONG BRANCH TAKEN - NEW_BOOL'( I9<5 ) ");
     END IF;

     IF  NBF AND TRUE  THEN
          FAILED(" WRONG BRANCH TAKEN - IF  NBF AND TRUE  ");
     END IF;

     IF  NOT(NBF) AND THEN FALSE  THEN
          FAILED(" WRONG BRANCH TAKEN - IF  NOT NBF AND THEN FALSE ");
     END IF;

     IF  NBF OR ELSE FALSE  THEN
          FAILED(" WRONG BRANCH TAKEN - IF  NBF OR ELSE FALSE  ");
     END IF;


     RESULT;


END C53004B;
