-- C54A23A.ADA

-- CHECK THAT CASE CHOICES MAY BE CONSTANT NAMES

-- DAT 3/18/81
-- SPS 4/7/82

WITH REPORT; USE REPORT;

PROCEDURE C54A23A IS

     C1 : CONSTANT INTEGER := 1;
     C2 : CONSTANT INTEGER := 2;
     C3 : CONSTANT INTEGER := 3;

BEGIN
     TEST ("C54A23A", "CASE CHOICES MAY BE CONSTANTS");

     CASE IDENT_INT (C3) IS
          WHEN C1 | C2
               => FAILED ("WRONG CASE CHOICE 1");
          WHEN 3 => NULL;
          WHEN OTHERS => FAILED ("WRONG CASE CHOICE 2");
     END CASE;

     RESULT;
END C54A23A;
