-- C54A13A.ADA

-- OBJECTIVE:
--     CHECK THAT IF A CASE EXPRESSION IS A DECLARED VARIABLE OR
--     CONSTANT, OR ONE OF THESE IN PARENTHESES, AND ITS SUBTYPE IS
--     NONSTATIC, THEN ANY VALUE OF THE EXPRESSION'S BASE TYPE MAY
--     APPEAR AS A CHOICE.

-- HISTORY:
--     BCB 02/29/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C54A13A IS

     SUBTYPE INT IS INTEGER RANGE IDENT_INT(5) .. IDENT_INT(10);

     A : INT := 8;
     B : CONSTANT INT := 7;
     C, D : INTEGER;

     FUNCTION IDENT(X : INT) RETURN INT IS
     BEGIN
          IF EQUAL(3,3) THEN
               RETURN X;
          ELSE
               RETURN 0;
          END IF;
     END IDENT;

BEGIN
     TEST ("C54A13A", "CHECK THAT IF A CASE EXPRESSION IS A DECLARED " &
                      "VARIABLE OR CONSTANT, OR ONE OF THESE IN " &
                      "PARENTHESES, AND ITS SUBTYPE IS NONSTATIC, " &
                      "THEN ANY VALUE OF THE EXPRESSION'S BASE TYPE " &
                      "MAY APPEAR AS A CHOICE");

     CASE A IS
          WHEN 0 => C := IDENT_INT(5);
          WHEN 8 => C := IDENT_INT(10);
          WHEN 30000 => C := IDENT_INT(15);
          WHEN -30000 => C := IDENT_INT(20);
          WHEN OTHERS => C := IDENT_INT(25);
     END CASE;

     IF C /= IDENT_INT(10) THEN
          FAILED ("IMPROPER VALUE FOR CASE EXPRESSION - 1");
     END IF;

     CASE B IS
          WHEN 0 => D := IDENT_INT(5);
          WHEN 100 => D := IDENT_INT(10);
          WHEN 30000 => D := IDENT_INT(15);
          WHEN -30000 => D := IDENT_INT(20);
          WHEN OTHERS => D := IDENT_INT(25);
     END CASE;

     IF D /= IDENT_INT(25) THEN
          FAILED ("IMPROPER VALUE FOR CASE EXPRESSION - 2");
     END IF;

     CASE (A) IS
          WHEN 0 => C := IDENT_INT(5);
          WHEN 8 => C := IDENT_INT(10);
          WHEN 30000 => C := IDENT_INT(15);
          WHEN -30000 => C := IDENT_INT(20);
          WHEN OTHERS => C := IDENT_INT(25);
     END CASE;

     IF C /= IDENT_INT(10) THEN
          FAILED ("IMPROPER VALUE FOR CASE EXPRESSION - 3");
     END IF;

     CASE (B) IS
          WHEN 0 => D := IDENT_INT(5);
          WHEN 110 => D := IDENT_INT(10);
          WHEN 30000 => D := IDENT_INT(15);
          WHEN -30000 => D := IDENT_INT(20);
          WHEN OTHERS => D := IDENT_INT(25);
     END CASE;

     IF D /= IDENT_INT(25) THEN
          FAILED ("IMPROPER VALUE FOR CASE EXPRESSION - 4");
     END IF;

     RESULT;
END C54A13A;
