-- C54A26A.ADA

-- CHECK THAT CHOICES WITHIN AND BETWEEN ALTERNATIVES CAN
-- APPEAR IN NON-MONOTONIC ORDER.

-- DAT 3/19/81

WITH REPORT; USE REPORT;

PROCEDURE C54A26A IS

     TYPE E IS (Z, Y, X, W);

BEGIN
     TEST ("C54A26A", "CASE CHOICES NEED NOT APPEAR IN ORDER");

     CASE E'VAL (IDENT_INT (3)) IS
          WHEN W => NULL;
          WHEN X | Z => NULL;
          WHEN Y => NULL;
     END CASE;

     CASE IDENT_BOOL (TRUE) IS
          WHEN TRUE | FALSE => NULL;
     END CASE;

     CASE IDENT_INT (4) IS
          WHEN 4 | 1 | -100 .. -50 => NULL;
          WHEN 3 | 2 | 99 => NULL;
          WHEN 8 => NULL;
          WHEN -6 => NULL;
          WHEN 1000 => NULL;
          WHEN OTHERS => NULL;
     END CASE;

     RESULT;
END C54A26A;
