-- C54A11A.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREDEFINED EQUALITY OPERATION DETERMINES WHICH
--     CASE ALTERNATIVE IS SELECTED.

-- HISTORY:
--     BCB 02/29/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C54A11A IS

     PACKAGE P IS
          TYPE T IS LIMITED PRIVATE;
          FUNCTION "=" (X, Y : T) RETURN BOOLEAN;
     PRIVATE
          TYPE T IS NEW INTEGER;
     END P;

     PACKAGE BODY P IS
          X : T := 1;
          Y : INTEGER;
          FUNCTION "=" (X, Y : T) RETURN BOOLEAN IS
          BEGIN
               RETURN (INTEGER (X) - 1) = INTEGER (Y);
          END;
     BEGIN
          TEST ("C54A11A", "CHECK THAT THE PREDEFINED EQUALITY " &
                           "OPERATION DETERMINES WHICH CASE " &
                           "ALTERNATIVE IS SELECTED");

          CASE X IS
               WHEN 0 => Y := IDENT_INT(5);
               WHEN 1 => Y := IDENT_INT(10);
               WHEN OTHERS => Y := IDENT_INT(100);
          END CASE;

          IF EQUAL(Y,IDENT_INT(5)) THEN
               FAILED ("USES REDEFINED EQUALITY OPERATION");
          ELSIF EQUAL(Y,IDENT_INT(10)) THEN
               COMMENT ("USES PREDEFINED EQUALITY OPERATION");
          ELSE
               FAILED ("VALUE OTHER THAN 0 OR 1 RETURNED");
          END IF;

          RESULT;
     END P;

     USE P;

BEGIN
     NULL;
END C54A11A;
