-- C54A27A.ADA

-- CHECK THAT RELATIONAL AND LOGICAL OPERATORS
-- ARE ALLOWED AS CASE CHOICES IF PARENTHESIZED.
-- OVERLOADED OR REDECLARED DEFINITIONS ARE NOT TESTED.

-- DAT 3/19/81
-- SPS 10/26/82
-- JBG 5/17/83

WITH REPORT;
USE REPORT;

PROCEDURE C54A27A IS

     T : CONSTANT BOOLEAN := TRUE;
     F : CONSTANT BOOLEAN := FALSE;

BEGIN
     TEST ("C54A27A", "RELATIONAL AND LOGICAL OPERATORS" &
                      " ARE ALLOWED AS CASE CHOICES IF PARENTHESIZED" );

     CASE IDENT_BOOL(T)IS
          WHEN (T < F) =>
               FAILED ("WRONG CASE CHOICE 1");
          WHEN (T OR (T >= F) = (F /= T)) =>
               NULL;
     END CASE;

     RESULT;
END C54A27A;
