-- C54A13C.ADA

-- OBJECTIVE:
--     CHECK THAT IF A CASE EXPRESSION IS A QUALIFIED EXPRESSION, A
--     TYPE CONVERSION, OR ONE OF THESE IN PARENTHESES, AND ITS
--     SUBTYPE IS NONSTATIC, THEN ANY VALUE OF THE EXPRESSION'S
--     BASE TYPE MAY APPEAR AS A CHOICE.

-- HISTORY:
--     BCB 07/13/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C54A13C IS

     L : INTEGER := 1;
     R : INTEGER := 100;

     SUBTYPE INT IS INTEGER RANGE L .. R;

     A : INT := 50;

     B : INTEGER := 50;

     C : INTEGER;

BEGIN
     TEST ("C54A13C", "CHECK THAT IF A CASE EXPRESSION IS A " &
                      "QUALIFIED EXPRESSION, A TYPE CONVERSION, " &
                      "OR ONE OF THESE IN PARENTHESES, AND ITS " &
                      "SUBTYPE IS NONSTATIC, THEN ANY VALUE OF THE " &
                      "EXPRESSION'S BASE TYPE MAY APPEAR AS A CHOICE");

     CASE INT'(A) IS
          WHEN 0 => C := IDENT_INT (5);
          WHEN 50 => C := IDENT_INT (10);
          WHEN -3000 => C := IDENT_INT (15);
          WHEN OTHERS => C := IDENT_INT (20);
     END CASE;

     IF C /= IDENT_INT (10) THEN
          FAILED ("INCORRECT CHOICE MADE FOR QUALIFIED EXPRESSION IN " &
                  "CASE");
     END IF;

     CASE INT(B) IS
          WHEN 0 => C := IDENT_INT (5);
          WHEN 50 => C := IDENT_INT (10);
          WHEN -3000 => C := IDENT_INT (15);
          WHEN OTHERS => C := IDENT_INT (20);
     END CASE;

     IF C /= IDENT_INT (10) THEN
          FAILED ("INCORRECT CHOICE MADE FOR TYPE CONVERSION IN CASE");
     END IF;

     CASE (INT'(A)) IS
          WHEN 0 => C := IDENT_INT (5);
          WHEN 50 => C := IDENT_INT (10);
          WHEN -3000 => C := IDENT_INT (15);
          WHEN OTHERS => C := IDENT_INT (20);
     END CASE;

     IF C /= IDENT_INT (10) THEN
          FAILED ("INCORRECT CHOICE MADE FOR QUALIFIED EXPRESSION IN " &
                  "PARENTHESES IN CASE");
     END IF;

     CASE (INT(B)) IS
          WHEN 0 => C := IDENT_INT (5);
          WHEN 50 => C := IDENT_INT (10);
          WHEN -3000 => C := IDENT_INT (15);
          WHEN OTHERS => C := IDENT_INT (20);
     END CASE;

     IF C /= IDENT_INT (10) THEN
          FAILED ("INCORRECT CHOICE MADE FOR TYPE CONVERSION IN " &
                  "PARENTHESES IN CASE");
     END IF;

     RESULT;
END C54A13C;
