-- C54A24A.ADA

-- CHECK THAT NULL SUBRANGE CHOICES MAY OCCUR IN CASE STATEMENT, WITH
-- OUT-OF-BOUNDS RANGE BOUNDS, AND WHERE VACUOUS CHOICES ARE NULL.
-- CHECK THAT AN UNNEEDED OTHERS CHOICE IS PERMITTED.

-- DAT 1/29/81
-- JBG 8/21/83

WITH REPORT;
PROCEDURE C54A24A IS

     USE REPORT;

     TYPE T IS RANGE 1 .. 1010;
     SUBTYPE ST IS T RANGE 5 .. 7;

     V : ST := 6;

BEGIN
     TEST ("C54A24A", "CHECK NULL CASE SUBRANGE CHOICES, WITH " &
           "OUTRAGEOUS BOUNDS");

     CASE V IS
          WHEN -1000 .. -1010 => NULL;
          WHEN T RANGE -5 .. -6 => NULL;
          WHEN 12 .. 11 | ST RANGE 1000 .. 99 => NULL;
          WHEN ST RANGE -99 .. -999 => NULL;
          WHEN ST RANGE 6 .. 6 => V := V - 1;
          WHEN T RANGE ST'BASE'LAST .. ST'BASE'FIRST => NULL;
          WHEN 5 | 7 => NULL;
          WHEN ST RANGE T'BASE'LAST .. T'BASE'FIRST => NULL;
          WHEN T'BASE'LAST .. T'BASE'FIRST => NULL;
          WHEN OTHERS => V := V + 1;
     END CASE;
     IF V /= 5 THEN
          FAILED ("IMPROPER CASE EXECUTION");
     END IF;

     RESULT;
END C54A24A;
