-- C54A04A.ADA

-- CHECK THAT PRIVATE (DISCRETE) TYPES MAY BE USED IN CASE EXPRESSIONS
--     WITHIN THE DEFINING PACKAGE.

-- DAT 1/29/81

WITH REPORT;
PROCEDURE C54A04A IS

     USE REPORT;

     PACKAGE P IS

          TYPE T IS PRIVATE;
          TYPE LT IS LIMITED PRIVATE;

     PRIVATE

          TYPE T IS ('Z', X);
          TYPE LT IS NEW INTEGER RANGE 0 .. 1;

     END P;

     VT : P.T;
     VLT : P.LT;

     PACKAGE BODY P IS

     BEGIN
          TEST ("C54A04A", "PRIVATE DISCRETE TYPES MAY APPEAR IN " &
                "CASE EXPRESSIONS IN PACKAGE BODY");

          VT := 'Z';
          VLT := LT (IDENT_INT (1));

          CASE VT IS
               WHEN X => FAILED ("WRONG CASE 1");
               WHEN 'Z' => NULL; -- OK
          END CASE;

          CASE VLT IS
               WHEN 1 => NULL; -- OK
               WHEN 0 => FAILED ("WRONG CASE 2");
          END CASE;
     END P;

BEGIN

     -- TEST CALLED FROM PACKAGE BODY, ALREADY ELABORATED.

     RESULT;
END C54A04A;
