-- C55B03A.ADA

-- CHECK THAT THE LOOP_PARAMETER IS ASSIGNED VALUES IN ASCENDING ORDER 
--   IF REVERSE IS ABSENT, AND DESCENDING ORDER IF REVERSE IS PRESENT.

-- DAS 1/12/81
-- SPS 3/2/83

WITH REPORT;
PROCEDURE C55B03A IS

     USE REPORT;
     I1 : INTEGER;

BEGIN
     TEST( "C55B03A" , "CHECK CORRECT ORDER OF VALUE SEQUENCING" & 
           " FOR A LOOP_PARAMETER" );

     I1 := 0;
     FOR I IN IDENT_INT(1)..IDENT_INT(5) LOOP
          I1 := I1 + 1;
          IF ( I /= I1 ) THEN
               FAILED ( "LOOP_PARAMETER ASCENDING INCORRECTLY" );
          END IF;
     END LOOP;

     I1 := 6;
     FOR I IN REVERSE IDENT_INT(1)..IDENT_INT(5) LOOP
          I1 := I1 - 1;
          IF ( I /= I1 ) THEN
               FAILED ( "LOOP_PARAMETER DESCENDING INCORRECTLY" );
          END IF;
     END LOOP;

     RESULT;

END C55B03A;
