--  C55B04A.ADA

-- CHECK THAT A LOOP IS NOT ENTERED IF THE LOWER BOUND OF THE DISCRETE
--   RANGE IS GREATER THAN THE UPPER BOUND, WHETHER REVERSE IS PRESENT
--   OR NOT.

-- CHECK THAT LOOP BOUNDS ARE EVALUATED ONLY ONCE, UPON ENTRY TO 
--   THE LOOP.

-- DAS  01/12/81
-- SPS 3/2/83
-- JBG 8/21/83

WITH REPORT;
PROCEDURE C55B04A IS

     USE REPORT;

     C10 : CONSTANT INTEGER := 10;
     I10 : INTEGER;

BEGIN
     TEST ( "C55B04A", "CHECK OPERATION OF A FOR LOOP OVER A NULL " & 
                       "DISCRETE RANGE" );

     -- NOTE: EXIT STATEMENTS ARE INCLUDED TO AID IN RECOVERY FROM
     --   TEST FAILURE.

     -- SUBTESTS INVOLVING STATIC BOUNDS:

     FOR I IN 10..1 LOOP
          FAILED ( "LOOPING OVER NULL RANGE 10..1" );
          EXIT;
     END LOOP;

     FOR I IN REVERSE INTEGER RANGE -1..-10 LOOP
          FAILED ( "LOOPING OVER NULL RANGE -1..-10" );
          EXIT;
     END LOOP;

     FOR I IN (C10 + 3)..(-3 * C10 + 27) LOOP     -- 13..-3
          FAILED ("LOOPING OVER NULL RANGE (C10 + 3)..(-3 * C10 + 27)");
          EXIT;
     END LOOP;


     -- SUBTESTS INVOLVING DYNAMIC BOUNDS:

     I10 := IDENT_INT(10);

     FOR I IN REVERSE I10..(I10-1) LOOP           -- 10..9
          FAILED ( "LOOPING OVER NULL RANGE I10..(I10-1)");
          EXIT;
     END LOOP;


     FOR I IN (C10 - I10)..(I10 - 11) LOOP        -- 0..-1
          FAILED ( "LOOPING OVER NULL RANGE (C10 - I10)..(I10 - 11)" );
          EXIT;
     END LOOP;


     -- SUBTEST OF BOUNDS EVALUTION ONLY AT ENTRY:

     FOR I IN 1..I10 LOOP
          I10 := I10 - 1;
     END LOOP;
     IF (I10 /= 0) THEN
          FAILED ( "LOOP BOUNDS NOT FIXED AT LOOP ENTRY" );
     END IF;

     RESULT;

END C55B04A;
