-- C55B10A.ADA

-- OBJECTIVE:
--     CHECK THAT, IN 'FOR I IN L .. R LOOP', IF EITHER L OR R IS AN
--     OVERLOADED ENUMERATION LITERAL, THE OVERLOADING IS CORRECTLY
--     RESOLVED AND THE LOOP PARAMETER HAS THE APPROPRIATE TYPE.

-- HISTORY:
--     DHH 08/15/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C55B10A IS

     TYPE ENUM IS (ALPH, BET, NEITHER);

     GLOBAL : ENUM := NEITHER;

     TYPE ALPHA IS (A, B, C, D, E);
     TYPE BETA IS (G, F, E, D, C);

     PROCEDURE VAR(DEC : ALPHA) IS
     BEGIN
          IF EQUAL(3, 3) THEN
               GLOBAL := ALPH;
          END IF;
     END;

     PROCEDURE VAR(DEC : BETA) IS
     BEGIN
          IF EQUAL(3, 3) THEN
               GLOBAL := BET;
          END IF;
     END;

BEGIN
     TEST("C55B10A", "CHECK THAT, IN 'FOR I IN L .. R LOOP', IF " &
                     "EITHER L OR R IS AN OVERLOADED ENUMERATION " &
                     "LITERAL, THE OVERLOADING IS CORRECTLY RESOLVED " &
                     "AND THE LOOP PARAMETER HAS THE APPROPRIATE TYPE");

     FOR I IN A .. E LOOP
          VAR(I);

          IF GLOBAL /= ALPH THEN
               FAILED("WRONG TYPE FOR ALPHA");
          END IF;
     END LOOP;

     FOR I IN G .. E LOOP
          VAR(I);

          IF GLOBAL /= BET THEN
               FAILED("WRONG TYPE FOR BETA");
          END IF;
     END LOOP;

     RESULT;
END C55B10A;
