-- C55C01A.ADA


-- CHECK THAT THE EXPRESSION FOLLOWING  'WHILE'  CAN HAVE A TYPE
--     DERIVED FROM BOOLEAN.


--  RM  07/22/82


WITH  REPORT ;
PROCEDURE C55C01A IS

     USE  REPORT ;

     TYPE  NEWBOOL  IS NEW BOOLEAN ;
     BNEW : NEWBOOL ;
     B : BOOLEAN ;

BEGIN

     TEST ( "C55C01A" , "DERIVED-BOOLEAN CONDITIONS IN  'WHILE' " );

     BNEW := NEWBOOL(IDENT_BOOL( FALSE ));
     WHILE (BNEW) LOOP
          FAILED( "LOOP1" );
          EXIT ;
     END LOOP;

     B := IDENT_BOOL(FALSE);
     WHILE NEWBOOL (B) LOOP
          FAILED( "LOOP2" );
          EXIT ;
     END LOOP;

     WHILE (NEWBOOL'PRED( NOT(BNEW) )) LOOP
          FAILED( "LOOP3" );
          EXIT ;
     END LOOP;

     WHILE  BNEW OR ELSE TRUE  LOOP
          B := TRUE ;
          EXIT ;
     END LOOP;
     IF  B  THEN  NULL;
     ELSE
          FAILED( "LOOP4" );
     END IF;


     RESULT;


END C55C01A ;
