-- C55C02B.ADA

-- CHECK THAT THE WHILE CONDITION IS EVALUATED EACH TIME.

-- DAT 1/29/81
-- SPS 3/2/83

WITH REPORT;
PROCEDURE C55C02B IS

     USE REPORT;

     I : INTEGER := 0;

     FT : ARRAY (FALSE .. TRUE) OF BOOLEAN 
          := (IDENT_BOOL (FALSE), IDENT_BOOL (TRUE));

BEGIN
     TEST ("C55C02B", "WHILE CONDITION IS EVALUATED EACH TIME THROUGH");

     WHILE I /= 10 LOOP
          I := I + 1;
     END LOOP;
     IF I /= 10 THEN
          FAILED ("BAD LOOP FLOW - OPTIMIZABLE CONDITION");
     END IF;

     I := 10;
     WHILE FT (IDENT_BOOL (I /= 14)) LOOP
          I := I + 1;
     END LOOP;
     IF I /= 14 THEN
          FAILED ("BAD LOOP FLOW - DYNAMIC CONDITION");
     END IF;

     RESULT;
END C55C02B;
