-- C55C02A.ADA

-- CHECK THAT WHILE LOOPS WITH FALSE CONDITIONS ARE NEVER EXECUTED.

-- DAT 1/29/81
-- DLD 8/06/82

WITH REPORT;
PROCEDURE C55C02A IS

     USE REPORT;

BEGIN
     TEST ("C55C02A", "INITIAL FALSE CONDITIONS IN WHILE LOOPS");

     WHILE FALSE LOOP
          FAILED ("STATIC FALSE WHILE LOOP ENTERED");
          EXIT;
     END LOOP;

     WHILE IDENT_BOOL (FALSE) LOOP
          FAILED ("DYNAMIC FALSE WHILE LOOP ENTERED");
          EXIT;
     END LOOP;

     RESULT;
END C55C02A;
