-- C58004F.ADA

-- CHECK THAT FOR GENERIC FUNCTIONS, THE VALUE SPECIFIED IN THE RETURN
--    STATEMENT IS ACTUALLY RETURNED.

-- SPS 3/7/83
-- JBG 9/13/83

WITH REPORT;
PROCEDURE C58004F IS

     USE REPORT;

     I1, I2, I3 : INTEGER;

     GENERIC
     FUNCTION ADDM (IA1, IA2 : INTEGER) RETURN INTEGER;

     FUNCTION ADDM (IA1, IA2 : INTEGER) RETURN INTEGER IS

          FUNCTION MULT (IM1, IM2 : INTEGER) RETURN INTEGER IS

               I : INTEGER;

          BEGIN
               I := IM1 * IM2;


               IF I > 0 THEN RETURN(I);
               END IF;

               RETURN(0);

          END MULT;

     BEGIN

          RETURN (MULT(IA1,IA2) + IA2);

     END ADDM;

     FUNCTION ADM IS NEW ADDM;

BEGIN
     TEST ("C58004F", "CHECK THAT FOR FUNCTIONS, THE VALUE SPECIFIED" &
           " IN THE RETURN STATEMENT IS ACTUALLY RETURNED");
     I1 := 2;
     I2 := 3;
     I3 := 0;

     I3 := ADM(I1, I2);          -- SAME AS (I1 * I2) + I2

     IF I3 /= 9 THEN
          FAILED ("VALUE IN RETURN STATEMENT NOT RETURNED CORRECTLY");
     END IF;

     RESULT;
END C58004F;
