-- C58004D.ADA

-- CHECK THAT A RETURN STATEMENT TERMINATES EXECUTION
--    OF THE INNERMOST ENCLOSING SUBPROGRAM.

-- CHECKS GENERIC SUBPROGRAMS.

-- SPS 3/7/83
-- JRK 1/31/84

WITH REPORT;
PROCEDURE C58004D IS

     USE REPORT;

     I1, I2 : INTEGER;

     GENERIC
     PROCEDURE ADDM (IA1 : IN OUT INTEGER; IA2 : IN INTEGER);

     PROCEDURE ADDM (IA1 : IN OUT INTEGER; IA2 : IN INTEGER) IS

          GENERIC
          PROCEDURE MULT (IM1 : IN OUT INTEGER; IM2 : IN INTEGER);

          PROCEDURE MULT (IM1 : IN OUT INTEGER; IM2 : IN INTEGER) IS
          BEGIN
               IM1 := IM1 * IM2;

               IF IM1 > 0 THEN RETURN;
               END IF;

               IM1 := 0;
          END MULT;

          PROCEDURE MLT IS NEW MULT;

     BEGIN
          MLT (IA1, IA2);
          IA1 := IA1 + IA2;

          IF IA1 > 0 THEN RETURN;
          END IF;

          IA1 := 0;
     END ADDM;

     PROCEDURE ADM IS NEW ADDM;

BEGIN
     TEST ("C58004D","CHECK THAT RETURN TERMINATES EXECUTION OF ONLY" &
           " THE INNERMOST ENCLOSING GENERIC SUBPROGRAM");

     I1 := 2;
     I2 := 3;
     ADM (I1,I2);     -- SAME AS I1 := (I1 * I2) + I2

     IF I1 = 0 THEN
          FAILED ("RETURN DOES NOT TERMINATE SUBPROGRAM");
     ELSIF I1 = 6 THEN
          FAILED
          ("RETURN TERMINATES ALL SUBPROGRAMS NOT JUST INNERMOST");
     ELSIF I1 /= 9 THEN
          FAILED ("RETURN STATEMENT NOT WORKING CORRECTLY");
     END IF;

     RESULT;
END C58004D;
