-- C58004A.ADA

-- CHECK THAT A RETURN STATEMENT TERMINATES EXECUTION
--    OF THE INNERMOST ENCLOSING SUBPROGRAM.

-- DCB 2/8/80
-- SPS 3/7/83

WITH REPORT;
PROCEDURE C58004A IS

     USE REPORT;

     I1, I2 : INTEGER;

     PROCEDURE ADDM (IA1 : IN OUT INTEGER; IA2 : IN INTEGER) IS

          PROCEDURE MULT (IM1 : IN OUT INTEGER; IM2 : IN INTEGER) IS

          BEGIN
               IM1 := IM1 * IM2;

               IF IM1 > 0 THEN RETURN;
               END IF;

               IM1 := 0;
          END MULT;

     BEGIN
          MULT (IA1, IA2);
          IA1 := IA1 + IA2;

          IF IA1 > 0 THEN RETURN;
          END IF;

          IA1 := 0;
     END ADDM;

BEGIN
     TEST ("C58004A","CHECK THAT RETURN TERMINATES EXECUTION OF ONLY" &
           " THE INNERMOST ENCLOSING SUBPROGRAM");

     I1 := 2;
     I2 := 3;
     ADDM (I1,I2);     -- SAME AS I1 := (I1 * I2) + I2

     IF I1 = 0 THEN
          FAILED ("RETURN DOES NOT TERMINATE SUBPROGRAM");
     ELSIF I1 = 6 THEN
          FAILED
          ("RETURN TERMINATES ALL SUBPROGRAMS NOT JUST INNERMOST");
     ELSIF I1 /= 9 THEN
          FAILED ("RETURN STATEMENT NOT WORKING CORRECTLY");
     END IF;

     RESULT;
END C58004A;
