-- C61003B.ADA

-- CHECK THAT A SUBPROGRAM DECLARATION AND A SUBPROGRAM BODY CAN BE
--   GIVEN SEPARATELY IN THE SAME DECLARATIVE PART, BUT THAT THE
--   SUBPROGRAM DECLARATION MUST PRECEDE THE SUBPROGRAM BODY.

-- DAS  1/20/81
-- SPS 10/19/83

WITH REPORT;
PROCEDURE C61003B IS

     USE REPORT;

     XX, YY, ZZ      : INTEGER := 15;

     PROCEDURE P2 (X : IN INTEGER;  Y : IN OUT INTEGER;
                   Z : OUT INTEGER);

     FUNCTION F2  (X : IN INTEGER) RETURN INTEGER;

     PROCEDURE P1 (X : IN INTEGER;  Y : IN OUT INTEGER;
                   Z : OUT INTEGER) IS
     BEGIN
          P2 (X, Y, Z);
     END P1;

     PROCEDURE P2 (X : IN INTEGER; Y : IN OUT INTEGER;
                   Z : OUT INTEGER) IS
     BEGIN
          Y := Y + X;
          Z := X + Y;
     END P2;

     FUNCTION F1 (X : IN INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN F2 (X);
     END F1;

     FUNCTION F2 (X : IN INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN (X + 1);
     END F2;

BEGIN
     TEST ("C61003B", "CHECK THAT A SUBPROGRAM DECLARATION AND " &
                      "A SUBPROGRAM BODY CAN BE GIVEN SEPARATELY " &
                      "IN THE SAME DECLARATIVE PART");

     P1 (XX, YY, ZZ);
     IF ((XX /= 15) OR (YY /= 30) OR (ZZ /= 45)) THEN
          FAILED ("PROCEDURE P2 NOT INVOKED PROPERLY");
     END IF;

     IF (F1(5) /= 6) THEN
          FAILED ("FUNCTION F2 NOT INVOKED PROPERLY");
     END IF;

     RESULT;
END C61003B;
