-- C62004A.ADA

-- CHECK THAT ALIASING IS PERMITTED FOR PARAMETERS OF COMPOSITE TYPES,
--   E.G., THAT A MATRIX ADDITION PROCEDURE CAN BE CALLED WITH THREE
--   IDENTICAL ARGUMENTS.  (NOTE: ALIASING MAY NOT WORK FOR ARGUMENTS
--   TO ALL SUBROUTINES SINCE PARAMETER PASSING IS IMPLEMENTATION
--   DEPENDENT.  HOWEVER, THIS TEST IS NOT ERRONEOUS.)

-- DAS  1/26/81

WITH REPORT;
PROCEDURE C62004A IS

     USE REPORT;

     TYPE MATRIX IS ARRAY (1..3,1..3) OF INTEGER;

     A    : MATRIX  := ((1,2,3),(4,5,6),(7,8,9));

     PROCEDURE MAT_ADD (X,Y : IN MATRIX; SUM : OUT MATRIX) IS
     BEGIN
          FOR I IN 1..3 LOOP
               FOR J IN 1..3 LOOP
                    SUM(I,J) := X(I,J) + Y(I,J);
               END LOOP;
          END LOOP;
     END MAT_ADD;

BEGIN

     TEST ("C62004A", "CHECK THAT ALIASING IS PERMITTED FOR" &
                      " PARAMETERS OF COMPOSITE TYPES");

     MAT_ADD (A, A, A);

     IF (A /= ((2,4,6),(8,10,12),(14,16,18))) THEN
          FAILED ("THE RESULT OF THE MATRIX ADDITION IS INCORRECT");
     END IF;

     RESULT;

END C62004A;
