-- C62006A.ADA

-- CHECK THAT THE DISCRIMINANTS OF AN OUT FORMAL PARAMETER, AS WELL AS
-- THE DISCRIMINANTS OF THE SUBCOMPONENTS OF AN OUT FORMAL PARAMETER,
-- MAY BE READ INSIDE THE PROCEDURE.

-- SPS 2/17/84

WITH REPORT; USE REPORT;
PROCEDURE C62006A IS
BEGIN

     TEST ("C62006A", "CHECK THAT THE DISCRIMINANTS OF AN OUT FORMAL " &
           "PARAMETER CAN BE READ INSIDE THE PROCEDURE");

     DECLARE

          TYPE R1 (D1 : INTEGER) IS RECORD
               NULL;
          END RECORD;

          TYPE R2 (D2 : POSITIVE) IS RECORD
               C : R1 (2);
          END RECORD;

          R : R2 (5);

          PROCEDURE P (REC : OUT R2) IS
          BEGIN

               IF REC.D2 /= 5 THEN
                    FAILED ("UNABLE TO CORRECTLY READ DISCRIMINANT OF" &
                            " OUT PARAMETER");
               END IF;

               IF REC.C.D1 /= 2 THEN
                    FAILED ("UNABLE TO CORRECTLY READ DISCRIMINANT " &
                            " OF THE SUBCOMPONENT OF AN OUT PARAMETER");
               END IF;
          END P;

     BEGIN
          P (R);
     END;

     RESULT;

END C62006A;
