-- C62009A.ADA

-- CHECK THAT DEFAULT INITIALIZATIONS ARE NOT PERFORMED FOR PARAMETERS
-- HAVING MODE OUT.

-- JBG 6/2/85

WITH REPORT; USE REPORT;
PROCEDURE C62009A IS

     TYPE REC IS
          RECORD
               A : INTEGER RANGE 1..10 := IDENT_INT(0);
          END RECORD;

     VAR : REC := (A => IDENT_INT(2));

     PROCEDURE CHECK (X : OUT REC) IS
     BEGIN
          X.A := 1;
     END CHECK;

BEGIN

     TEST ("C62009A", "CHECK THAT DEFAULT INITIALIZATIONS ARE NOT " &
                      "PERFORMED FOR OUT PARAMETERS");

-- CHECK THAT DEFAULT INITIALIZATION RAISES EXCEPTION
     BEGIN
          DECLARE
               LOCAL : REC;        -- SHOULD RAISE EXCEPTION.
          BEGIN
               IF EQUAL (LOCAL.A, LOCAL.A) THEN
                    FAILED ("NO EXCEPTION RAISED FOR DEFAULT " &
                            "INITIALIZATION");
               END IF;
          END;
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED - 1");
     END;

-- CHECK NO INITIALIZATION FOR OUT PARAMETER
     BEGIN
          CHECK (VAR);
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("EXCEPTION RAISED FOR OUT PARAMETER");
     END;

     IF VAR /= (A => 1) THEN
          FAILED ("WRONG VALUE RETURNED FOR OUT PARAMETER");
     END IF;

     RESULT;
END C62009A; 
