-- C63004A.ADA

-- CHECK THAT A PROCEDURE WITHOUT A RETURN STATEMENT RETURNS CORRECTLY.

-- DAS  1/23/81
-- JBG  5/16/83

WITH REPORT;
PROCEDURE C63004A IS

     USE REPORT;

     I    : INTEGER := 0;     -- INITIAL VALUE NOT IMPORTANT

     PROCEDURE PROC1 (N : IN INTEGER; R : IN OUT INTEGER) IS
     BEGIN
          IF (N > 1) THEN
               PROC1 ((N-1),R);
               R := R * N;
          ELSE R := 1;
          END IF;
     END PROC1;

BEGIN

     TEST ("C63004A", "CHECK THAT A PROCEDURE WITHOUT A RETURN" &
                      " STATEMENT RETURNS CORRECTLY");

     PROC1 (IDENT_INT(4), I);
     IF (I /= (4 * 3 * 2)) THEN
          FAILED ("INCORRECT RETURN FROM RECURSIVE PROCEDURE PROC1");
     END IF;

     RESULT;

END C63004A;
