-- C64005A.ADA

-- CHECK THAT A SUBPROGRAM CAN BE CALLED
-- RECURSIVELY AND THAT NON-LOCAL VARIABLES AND 
-- CONSTANTS ARE PROPERLY ACCESSED FROM WITHIN
-- RECURSIVE INVOCATIONS.

-- CVP 5/1/81

WITH REPORT;
PROCEDURE C64005A IS

     USE REPORT;

     TWENTY : CONSTANT INTEGER := 20;
     C1 : CONSTANT INTEGER := 1;
     I1, I2 : INTEGER := 0;

     PROCEDURE RECURSE (I1A : INTEGER; I2 : IN OUT INTEGER) IS
          C1 : CONSTANT INTEGER := 5;
     BEGIN
          IF I1A < TWENTY THEN
               RECURSE (I1A+C1, I2);
               I1 := I1 + C64005A.C1;
               I2 := I2 + I1A;
          END IF;
     END RECURSE;

BEGIN
     TEST ("C64005A", "RECURSIVE SUBPROGRAMS WITH " &
           "NON-LOCAL DATA ACCESS");

     RECURSE (0, I2);

     IF I1 /= 4 OR I2 /= 30 THEN
          FAILED ("RECURSIVE PROCEDURE INVOCATIONS " &
                  "WITH GLOBAL DATA ACCESS NOT PERFORMED " &
                  "CORRECTLY");
     END IF;

     RESULT;
END C64005A;
