-- C64107A.ADA

-- CHECK THAT ACTUAL PARAMETERS ARE EVALUATED AND IDENTIFIED AT THE
--   TIME OF CALL.

-- DAS  1/29/81
-- SPS 12/13/82

WITH REPORT;
PROCEDURE C64107A IS

     USE REPORT;

     TYPE VECTOR IS ARRAY (1..10) OF INTEGER;
     TYPE PTRINT IS ACCESS INTEGER;

     I    : INTEGER := 1;
     A    : VECTOR  := (1,2,3,4,5,6,7,8,9,10);
     P1   : PTRINT  := NEW INTEGER'(2);
     P2   : PTRINT  := P1;

     PROCEDURE PROC1 (I : OUT INTEGER; J : OUT INTEGER) IS
     BEGIN
          I := 10;
          J := -1;
     END PROC1;

     PROCEDURE PROC2 (P : OUT PTRINT; I : OUT INTEGER) IS
     BEGIN
          P := NEW INTEGER'(3);
          I := 5;
     END PROC2;

BEGIN

     TEST ("C64107A", "CHECK THAT ACTUAL PARAMETERS ARE EVALUATED" &
                      " AND IDENTIFIED AT THE TIME OF CALL");

     PROC1 (I, A(I));
     IF (A /= (-1,2,3,4,5,6,7,8,9,10)) THEN
          FAILED ("A(I) EVALUATED UPON RETURN");
     END IF;

     PROC2 (P1, P1.ALL);
     IF (P2.ALL /= 5) THEN
          FAILED ("P1.ALL EVALUATED UPON RETURN");
     END IF;

     RESULT;

END C64107A;
