-- C64105A.ADA

-- CHECK THAT CONSTRAINT_ERROR IS NOT RAISED AT THE TIME OF CALL WHEN 
--   THE VALUE OF AN ACTUAL OUT SCALAR PARAMETER DOES NOT SATISFY THE 
--   RANGE CONSTRAINTS OF THE FORMAL PARAMETER.

-- DAS  1/29/81
-- CPP  8/6/84

WITH REPORT;
PROCEDURE C64105A IS

     USE REPORT;

     SUBTYPE SUBINT1 IS INTEGER RANGE -10..10;
     SUBTYPE SUBINT2 IS INTEGER RANGE -20..20;

     I10  : SUBINT1 := 10;
     I20  : SUBINT2 := 20;

     PROCEDURE P1 (I : OUT SUBINT1) IS
     BEGIN
          I := SUBINT1'FIRST;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("EXCEPTION RAISED IN PROCEDURE P1");
     END P1;

BEGIN

     TEST ("C64105A", "CHECK THAT CONSTRAINT_ERROR IS NOT RAISED" &
                      " AT THE TIME OF CALL WHEN THE VALUE OF AN" &
                      " ACTUAL OUT SCALAR PARAMETER DOES NOT" &
                      " SATISFY THE RANGE CONSTRAINTS OF THE FORMAL" &
                      " PARAMETER");

     DECLARE
     BEGIN
          P1 (SUBINT1(I20));
          IF I20 /= IDENT_INT(-10) THEN
               FAILED ("OUT PARAM DID NOT GET CORRECT VALUE - 1");
          END IF;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("EXCEPTION RAISED ON CALL TO P1 - 1");
     END;

     DECLARE
     BEGIN
          I20 := IDENT_INT(20);
          P1 (I20);
          IF I20 /= IDENT_INT(-10) THEN
               FAILED ("OUT PARAM DID NOT GET CORRECT VALUE - 2");
          END IF;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("EXCEPTION RAISED ON CALL TO P1 - 2");
     END;

     RESULT;

END C64105A;
