-- C64104J.ADA

-- OBJECTIVE:
--     CHECK THAT CONSTRAINT_ERROR IS RAISED UNDER THE APPROPRIATE
--     CIRCUMSTANCES FOR ACCESS PARAMETERS, NAMELY WHEN THE
--     ACTUAL INDEX BOUNDS OR DISCRIMINANTS ARE NOT EQUAL
--     TO THE FORMAL CONSTRAINTS BEFORE THE CALL (FOR IN AND IN OUT
--     MODES), AND WHEN THE FORMAL CONSTRAINTS ARE NOT EQUAL TO THE
--     ACTUAL CONSTRAINTS UPON RETURN (FOR IN OUT AND OUT MODES).

--         (G) AFTER RETURN, OUT MODE, UNCONSTRAINED FORMAL, STATIC ONE
--             DIMENSIONAL BOUNDS.

-- HISTORY:
--     JRK 03/18/81  CREATED ORIGINAL TEST.
--     NL  10/13/81
--     BCB 11/12/87  CHANGED HEADING TO STANDARD FORMAT.  ADDED CODE TO
--                   ENSURE THAT SUBPROGRAMS ARE ACTUALLY CALLED.

WITH REPORT;
PROCEDURE C64104J IS

     USE REPORT;

BEGIN
     TEST ("C64104J", "CHECK THAT CONSTRAINT_ERROR IS RAISED " &
           "APPROPRIATELY FOR ACCESS PARAMETERS");

     --------------------------------------------------

     DECLARE

          TYPE A IS ACCESS STRING;

          CALLED : BOOLEAN := FALSE;

          V : A (1..3) := NEW STRING (1..3);

          PROCEDURE P (X : OUT A) IS
          BEGIN
               CALLED := TRUE;
               X := NEW STRING (2..3);
          EXCEPTION
              WHEN OTHERS =>
                    FAILED ("EXCEPTION RAISED IN PROCEDURE");
          END P;

     BEGIN

          P (V);
          FAILED ("EXCEPTION NOT RAISED AFTER RETURN");

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               IF NOT CALLED THEN
                    FAILED ("SUBPROGRAM P WAS NOT CALLED");
               END IF;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED");
     END;

     --------------------------------------------------

     RESULT;

END C64104J;
