-- C65003A.ADA

-- CHECK THAT IF NO RETURN STATEMENT IS EXECUTED, A FUNCTION RAISES
-- PROGRAM_ERROR.  DETERMINE WHERE THE EXCEPTION IS RAISED.

-- THIS LACK OF AN EXECUTABLE RETURN IS DETECTABLE AT COMPILE TIME IN
-- THIS TEST.

-- JBG 10/14/83
-- SPS 2/22/84

WITH REPORT; USE REPORT;
PROCEDURE C65003A IS

     EXCEPTION_RAISED : BOOLEAN := FALSE;
     FUNCTION RETURN_IN_EXCEPTION RETURN INTEGER IS
     BEGIN
          IF FALSE THEN
               RETURN 5;
          END IF;
     EXCEPTION
          WHEN PROGRAM_ERROR =>
               COMMENT ("PROGRAM_ERROR RAISED IN FUNCTION BODY - " &
                        "RETURN_IN_EXCEPTION");
               EXCEPTION_RAISED := TRUE;
               RETURN 5;
     END RETURN_IN_EXCEPTION;

     FUNCTION NO_RETURN RETURN INTEGER IS
          NO_RETURN_EXCEPTION : EXCEPTION;
     BEGIN
          RAISE NO_RETURN_EXCEPTION;
          RETURN 5;
     EXCEPTION
          WHEN NO_RETURN_EXCEPTION =>
               NULL;
     END NO_RETURN;

BEGIN

     TEST ("C65003A", "CHECK THAT PROGRAM_ERROR IS RAISED IF A " &
                      "FUNCTION RETURNS WITHOUT EXECUTING A RETURN " &
                      "STATEMENT");

     BEGIN

          IF RETURN_IN_EXCEPTION = RETURN_IN_EXCEPTION THEN
               IF NOT EXCEPTION_RAISED THEN
                    FAILED ("PROGRAM_ERROR NOT RAISED - " &
                            "RETURN_IN_EXCEPTION");
               END IF;
          END IF;

     EXCEPTION
     
          WHEN PROGRAM_ERROR =>
               COMMENT ("PROGRAM_ERROR RAISED AT POINT OF CALL " &
                        "- RETURN_IN_EXCEPTION");

     END;


     BEGIN

          IF NO_RETURN = NO_RETURN THEN
               FAILED ("PROGRAM_ERROR NOT RAISED - NO_RETURN");
          END IF;

     EXCEPTION
     
          WHEN PROGRAM_ERROR =>
               COMMENT ("PROGRAM_ERROR RAISED WHEN NO RETURN IN " &
                        "EXCEPTION HANDLER");
     END;

     RESULT;

END C65003A;
