-- C67005D.ADA

-- CHECK THAT EQUALITY CAN BE REDEFINED FOR AN ARBITRARY TYPE BY USING A
-- SEQUENCE OF RENAMING DECLARATIONS.

-- JBG 9/11/84

WITH REPORT; USE REPORT;
PROCEDURE C67005D IS

     FUNCTION MY_EQUALS  (L, R : INTEGER) RETURN BOOLEAN IS
     BEGIN
          RETURN FALSE;
     END MY_EQUALS;

     GENERIC
          TYPE LP IS LIMITED PRIVATE;
          WITH FUNCTION "=" (L, R : LP) RETURN BOOLEAN;
     PACKAGE EQUALITY_OPERATOR IS
          PACKAGE INNER IS
               FUNCTION "=" (L, R : LP) RETURN BOOLEAN RENAMES
                             EQUALITY_OPERATOR."=";
          END INNER;
     END EQUALITY_OPERATOR;

BEGIN
     TEST ("C67005D", "CHECK REDEFINITION OF ""="" BY RENAMING");

     DECLARE

          CHK1 : BOOLEAN := 3 = IDENT_INT(3);     -- PREDEFINED "="

          -- REDEFINE INTEGER "=".

          PACKAGE INT_EQUALITY IS NEW
               EQUALITY_OPERATOR (INTEGER, MY_EQUALS);
          FUNCTION "=" (L, R : INTEGER) RETURN BOOLEAN RENAMES
               INT_EQUALITY.INNER."=";

          CHK2 : BOOLEAN := 3 = IDENT_INT(3);     -- REDEFINED "=".

     BEGIN

          IF NOT CHK1 THEN
               FAILED ("PREDEFINED ""="" NOT USED");
          END IF;

          IF CHK2 THEN
               FAILED ("REDEFINED ""="" NOT USED");
          END IF;

     END;

     RESULT;

END C67005D;
