-- C67005C.ADA

-- CHECK THAT A DECLARATION OF "=" NEED NOT HAVE PARAMETERS
-- OF A LIMITED TYPE IN A RENAMING DECLARATION. THIS TEST CHECKS
-- ACCESS TYPES.

-- BRYCE BARDIN (HUGHES AIRCRAFT) 7/2/84
-- CPP 7/12/84

WITH REPORT;  USE REPORT;
PROCEDURE C67005C IS

     GENERIC
          TYPE T IS LIMITED PRIVATE;
          WITH FUNCTION EQUAL (LEFT, RIGHT : T) RETURN BOOLEAN IS <>;
     PACKAGE EQUALITY IS
          FUNCTION "=" (LEFT, RIGHT : T) RETURN BOOLEAN;
          -- PRAGMA INLINE ("=");
     END EQUALITY;

     PACKAGE BODY EQUALITY IS
          FUNCTION "=" (LEFT, RIGHT : T) RETURN BOOLEAN IS
          BEGIN
               RETURN EQUAL (LEFT, RIGHT);
          END "=";
     END EQUALITY;

     PACKAGE STARTER IS
          TYPE INT IS PRIVATE;
          FUNCTION VALUE_OF (I : INTEGER) RETURN INT;
          FUNCTION EQUAL (LEFT, RIGHT : INT) RETURN BOOLEAN;
     PRIVATE
          TYPE INT IS ACCESS INTEGER;
     END STARTER;

     PACKAGE BODY STARTER IS
          FUNCTION VALUE_OF (I : INTEGER) RETURN INT IS
          BEGIN
               RETURN NEW INTEGER'(I);
          END VALUE_OF;

          FUNCTION EQUAL (LEFT, RIGHT : INT) RETURN BOOLEAN IS
          BEGIN
               RETURN LEFT.ALL = RIGHT.ALL;
          END EQUAL;
     END STARTER;

     PACKAGE ABSTRACTION IS
          TYPE INT IS NEW STARTER.INT;
          PACKAGE INT_EQUALITY IS NEW EQUALITY (INT, EQUAL);
          FUNCTION "=" (LEFT, RIGHT : INT) RETURN BOOLEAN
               RENAMES INT_EQUALITY."=";
     END ABSTRACTION;    
     USE ABSTRACTION;

BEGIN

     TEST ("C67005C", "RENAMING OF EQUALITY OPERATOR WITH " &
           "NON-LIMITED PARAMETERS");

     DECLARE

          I : INT := VALUE_OF(1);
          J : INT := VALUE_OF(0);

          PROCEDURE CHECK (B : BOOLEAN) IS
          BEGIN
               IF I = J AND B THEN
                    COMMENT ("I = J");
               ELSIF I /= J AND NOT B THEN
                    COMMENT ("I /= J");
               ELSE
                    FAILED ("WRONG ""="" OPERATOR");
               END IF;
          END CHECK;

     BEGIN

          CHECK(FALSE);
          I := VALUE_OF(0);
          CHECK(TRUE);
     
          RESULT;

     END;

END C67005C;
