-- C74208A.ADA

-- OBJECTIVE:
--     CHECK THAT 'SIZE AND 'ADDRESS FOR OBJECTS OF LIMITED AND
--     NON-LIMITED TYPES ARE AVAILABLE BOTH INSIDE AND OUTSIDE THE
--     PACKAGE DECLARING THE TYPES.

-- HISTORY:
--     BCB 03/14/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;

PROCEDURE C74208A IS

     PACKAGE P IS
          TYPE T IS PRIVATE;
          TYPE U IS LIMITED PRIVATE;
     PRIVATE
          TYPE T IS RANGE 1 .. 100;
          TYPE U IS RANGE 1 .. 100;
     END P;

     A : P.T;
     B : P.U;
     ASIZE, BSIZE : INTEGER;
     AADDRESS, BADDRESS : ADDRESS;

     FUNCTION IDENT_ADR(X : ADDRESS) RETURN ADDRESS IS
          Y : P.T;
     BEGIN
          IF EQUAL(3,3) THEN
               RETURN X;
          END IF;
          RETURN Y'ADDRESS;
     END IDENT_ADR;

     PACKAGE BODY P IS
          X : T;
          Y : U;
          XSIZE, YSIZE : INTEGER;
          XADDRESS, YADDRESS : ADDRESS;
     BEGIN
          TEST ("C74208A", "CHECK THAT 'SIZE AND 'ADDRESS FOR " &
                           "OBJECTS OF LIMITED AND NON-LIMITED TYPES " &
                           "ARE AVAILABLE BOTH INSIDE AND OUTSIDE " &
                           "THE PACKAGE DECLARING THE TYPES");

          XSIZE := X'SIZE;
          YSIZE := Y'SIZE;
          XADDRESS := X'ADDRESS;
          YADDRESS := Y'ADDRESS;

          IF NOT EQUAL(XSIZE,X'SIZE) THEN
               FAILED ("IMPROPER VALUE FOR X'SIZE");
          END IF;

          IF XADDRESS /= IDENT_ADR(X'ADDRESS) THEN
               FAILED ("IMPROPER VALUE FOR X'ADDRESS");
          END IF;

          IF NOT EQUAL(YSIZE,Y'SIZE) THEN
               FAILED ("IMPROPER VALUE FOR Y'SIZE");
          END IF;

          IF YADDRESS /= IDENT_ADR(Y'ADDRESS) THEN
               FAILED ("IMPROPER VALUE FOR Y'ADDRESS");
          END IF;
     END P;

BEGIN
     ASIZE := A'SIZE;
     BSIZE := B'SIZE;
     AADDRESS := A'ADDRESS;
     BADDRESS := B'ADDRESS;

     IF NOT EQUAL(ASIZE,A'SIZE) THEN
          FAILED ("IMPROPER VALUE FOR A'SIZE");
     END IF;

     IF AADDRESS /= IDENT_ADR(A'ADDRESS) THEN
          FAILED ("IMPROPER VALUE FOR A'ADDRESS");
     END IF;

     IF NOT EQUAL(BSIZE,B'SIZE) THEN
          FAILED ("IMPROPER VALUE FOR B'SIZE");
     END IF;

     IF BADDRESS /= IDENT_ADR(B'ADDRESS) THEN
          FAILED ("IMPROPER VALUE FOR B'ADDRESS");
     END IF;

     RESULT;
END C74208A;
