-- C74307A.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXPLICIT CONSTRAINT MAY BE GIVEN IN THE SUBTYPE
--     INDICATION OF THE FULL DECLARATION OF A DEFERRED CONSTANT.

-- HISTORY:
--     BCB 03/14/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C74307A IS

     PACKAGE P IS
          TYPE T (D : INTEGER) IS PRIVATE;
          C : CONSTANT T;
     PRIVATE
          TYPE T (D : INTEGER) IS RECORD
               NULL;
          END RECORD;
          C : CONSTANT T(2) := (D => 2);
     END P;

     USE P;

BEGIN
     TEST ("C74307A", "CHECK THAT AN EXPLICIT CONSTRAINT MAY BE " &
                      "GIVEN IN THE SUBTYPE INDICATION OF THE FULL " &
                      "DECLARATION OF A DEFERRED CONSTANT");

     IF C.D /= 2 THEN
          FAILED ("IMPROPER RESULTS FOR C.D");
     END IF;

     RESULT;
END C74307A;
