-- C74302A.ADA

-- CHECK THAT MULTIPLE DECLARATIONS MAY BE USED FOR DEFERRED CONSTANT
-- DECLARATIONS, EVEN IF THE FULL DECLARATIONS ARE GIVEN INDIVIDUALLY.

-- CHECK THAT MULTIPLE DECLARATIONS MAY BE USED FOR THE FULL
-- DECLARATIONS, EVEN IF THE DEFERRED CONSTANT DECLARATIONS ARE GIVEN
-- INDIVIDUALLY.

-- CHECK THAT THE ORDER OF FULL DECLARATIONS NEED NOT DUPLICATE THE
-- ORDER OF DEFERRED CONSTANT DECLARATIONS.

-- DSJ  5/09/83
-- SPS 10/24/83
-- EG  12/19/83
-- JRK 12/20/83

WITH REPORT;
PROCEDURE C74302A IS

     USE REPORT;

BEGIN

     TEST("C74302A", "CHECK THAT MULTIPLE DECLARATIONS MAY BE USED " &
                     "FOR DEFERRED CONSTANT DECLARATIONS, AND THAT " &
                     "THE ORDER OF FULL DECLARATIONS NEED NOT BE "   &
                     "THE SAME AS THE ORDER OF DEFERRED CONSTANTS");

     DECLARE

          PACKAGE PACK1 IS

               TYPE T IS PRIVATE;

               A, B, C, D, E : CONSTANT T;

               F : CONSTANT T;
               G : CONSTANT T;
               H : CONSTANT T;
               I : CONSTANT T;

          PRIVATE

               TYPE T IS NEW INTEGER;

               B : CONSTANT T := T(IDENT_INT(2));
               I : CONSTANT T := T(IDENT_INT(1));
               F : CONSTANT T := T(IDENT_INT(2));

               E, D, H  : CONSTANT T := T(IDENT_INT(4));

               A, G, C  : CONSTANT T := T(IDENT_INT(5));

          END PACK1;

          USE PACK1;

     BEGIN

          IF A/=G THEN
               FAILED("VALUES OF DEFERRED CONSTANTS A AND G NOT EQUAL");
          END IF;

          IF D/=H THEN
               FAILED("VALUES OF DEFERRED CONSTANTS D AND H NOT EQUAL");
          END IF;

          IF B/=F THEN
               FAILED("VALUES OF DEFERRED CONSTANTS B AND F NOT EQUAL");
          END IF;

     END;

     RESULT;

END C74302A;
