-- C83031E.ADA

-- OBJECTIVE:
--     CHECK THAT AN IMPLICIT DECLARATION OF A PREDEFINED OPERATOR IS
--     HIDDEN BY A GENERIC FORMAL SUBPROGRAM DECLARATION WHICH DECLARES
--     A HOMOGRAPH OF THE OPERATOR.

-- HISTORY:
--     BCB 09/19/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE C83031E IS

BEGIN
     TEST ("C83031E", "CHECK THAT AN IMPLICIT DECLARATION OF A " &
                      "PREDEFINED OPERATOR IS HIDDEN BY A GENERIC " &
                      "FORMAL SUBPROGRAM DECLARATION WHICH DECLARES " &
                      "A HOMOGRAPH OF THE OPERATOR");

     DECLARE             -- CHECK SUBPROGRAM DECLARATIONS OF OPERATORS
          TYPE INT IS RANGE -20 .. 20;

          GENERIC
               WITH FUNCTION "*" (LEFT, RIGHT : INT) RETURN INT;
          PACKAGE P IS
          END P;

          PACKAGE BODY P IS
          BEGIN
               IF 2 * INT(IDENT_INT(2)) /= 1 THEN
                    FAILED ("INCORRECT VALUE RETURNED IN CALL TO " &
                            "EXPLICIT '*' OPERATOR - 1");
               END IF;
          END P;

          FUNCTION MULT (X, Y : INT) RETURN INT IS
          BEGIN
               RETURN X / Y;
          END MULT;

          PACKAGE NEW_P IS NEW P (MULT);
     BEGIN
          NULL;
     END;

     RESULT;
END C83031E;
