-- C83024E0.ADA

-- OBJECTIVE:
--     CHECK THAT A DECLARATION IN THE DECLARATIVE REGION OF A GENERIC
--     PACKAGE HIDES AN OUTER DECLARATION OF A HOMOGRAPH. ALSO CHECK
--     THAT THE OUTER DECLARATION IS DIRECTLY VISIBLE IN BOTH
--     DECLARATIVE REGIONS BEFORE THE DECLARATION OF THE INNER HOMOGRAPH
--     AND THE OUTER DECLARATION IS VISIBLE BY SELECTION AFTER THE INNER
--     HOMOGRAPH DECLARATION, IF THE GENERIC PACKAGE BODY IS SEPARATELY
--     COMPILED, BUT NOT AS A SUBUNIT.

-- HISTORY:
--     BCB 08/30/88  CREATED ORIGINAL TEST.

GENERIC
     TYPE T IS PRIVATE;
     X : T;
FUNCTION C83024E_GEN_FUN RETURN T;

FUNCTION C83024E_GEN_FUN RETURN T IS
BEGIN
     RETURN X;
END C83024E_GEN_FUN;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE C83024E_P1 IS
     A : INTEGER := IDENT_INT(2);
     B : INTEGER := A;

     GENERIC
          X : IN OUT INTEGER;
     PACKAGE C83024E_PACK1 IS
          C : INTEGER := A;
          A : INTEGER := IDENT_INT(3);
     END C83024E_PACK1;
END C83024E_P1;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE C83024E_P2 IS
     A : INTEGER := IDENT_INT(2);
     B : INTEGER := A;
     OBJ : INTEGER := IDENT_INT(3);

     GENERIC
          X : IN INTEGER := A;
          A : IN OUT INTEGER;
     PACKAGE C83024E_PACK2 IS
          C : INTEGER := A;
     END C83024E_PACK2;
END C83024E_P2;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE C83024E_P3 IS
     A : INTEGER := IDENT_INT(2);
     B : INTEGER := A;

     GENERIC
          X : IN OUT INTEGER;
     PACKAGE C83024E_PACK3 IS
     END C83024E_PACK3;
END C83024E_P3;

WITH REPORT; USE REPORT;
WITH C83024E_GEN_FUN;
PRAGMA ELABORATE(REPORT,C83024E_GEN_FUN);
PACKAGE C83024E_P4 IS
     OBJ : INTEGER := IDENT_INT(1);
     FLO : FLOAT := 6.25;

     FUNCTION F IS NEW C83024E_GEN_FUN (INTEGER, OBJ);
     FUNCTION F IS NEW C83024E_GEN_FUN (FLOAT, FLO);

     GENERIC
          X : IN OUT INTEGER;
          F : IN FLOAT;
     PACKAGE C83024E_PACK4 IS
     END C83024E_PACK4;
END C83024E_P4;
