-- C83E02B.ADA


-- CHECK THAT WITHIN THE BODY OF A SUBPROGRAM A FORMAL PARAMETER CAN BE
--    USED IN AN EXCEPTION HANDLER.

--    RM   10 JULY 1980


WITH REPORT;
PROCEDURE  C83E02B  IS

     USE REPORT;

     Z : INTEGER := 0 ;

     PROCEDURE  P1 ( A , B : INTEGER;  C : IN OUT INTEGER ) IS
          E : EXCEPTION ;
     BEGIN
          RAISE  E ;
          FAILED( "FAILURE TO RAISE  E " );
     EXCEPTION
          WHEN  E  =>
               C := A + B ;
          WHEN  OTHERS  =>
               FAILED( "WRONG EXCEPTION RAISED" );
     END ;


BEGIN

     TEST( "C83E02B" , "CHECK THAT WITHIN THE BODY OF A SUBPROGRAM " &
                       " A FORMAL PARAMETER CAN BE USED IN AN EXCEP" &
                       "TION HANDLER" ) ;

     P1 ( 3 , 14 , Z );

     IF  Z /= 17  THEN
          FAILED( "ACCESSING ERROR OR COMPUTATION ERROR" );
     END IF;

     RESULT;

END C83E02B;
