-- C83F03C1.ADA


-- SEPARATELY COMPILED PACKAGE FOR USE WITH  C83F03C2M

-- THIS PACKAGE IS A FULL-FLEDGED COMPILATION UNIT (AS OPPOSED TO
--    BEING A SUBUNIT; SUBUNITS ARE TESTED IN  C83F03D0M ,
--    C83F03D1 ). THE PRESENT FILE CONTAINS THE BODY OF THE PACKAGE.

-- FOR THIS FILE, THE FILE NAME AND THE UNIT NAME ARE NOT THE SAME.


--    RM    05 SEPTEMBER 1980


PACKAGE BODY  C83F03C0  IS

     Y4 : INTEGER := 200 ;

     TYPE  T4  IS  ( G , H , I ) ;

     PROCEDURE  BUMP  IS
     BEGIN
          FLOW_INDEX := FLOW_INDEX + 1 ;
     END BUMP ;

     PACKAGE BODY  P  IS
     BEGIN

          GOTO  T3 ;

          BUMP ;
          BUMP ;

          <<T3>>   BUMP ;  GOTO  T4 ;
          BUMP ;
          <<LABEL_IN_OUTER>>   BUMP ;  GOTO  ENDING ;
          BUMP ;
          <<Y3>>   BUMP ;  GOTO  Y4 ;
          BUMP ;
          <<Y4>>   BUMP ;  GOTO  LABEL_IN_OUTER ;
          BUMP ;
          <<T4>>   BUMP ;  GOTO  Y3 ;
          BUMP ;

          << ENDING >>  NULL;

     END P ;

BEGIN

     << LABEL_IN_OUTER >>  NULL ;

END  C83F03C0 ;
