-- C83F03D0M.ADA

-- MAIN PROGRAM REQUIRING A SEPARATELY COMPILED PACKAGE BODY SUBUNIT
--    ( C83F03D1.ADA )

-- CHECK THAT IF A PACKAGE BODY IS NESTED INSIDE A SEPARATELY COMPILED
--    PACKAGE BODY
--    THE INNER PACKAGE BODY CAN CONTAIN A LABEL IDENTIFIER IDENTICAL
--    TO A LABEL IDENTIFIER IN THE OUTER PACKAGE BODY OR TO AN IDENTI-
--    FIER DECLARED IN THE OUTER PACKAGE BODY OR IN ITS SPECIFICATION
--    OR IN ITS ENVIRONMENT.

-- CASE 2:  PACKAGE BODY IS A COMPILATION SUBUNIT


--    RM    08 SEPTEMBER 1980
--    JRK   14 NOVEMBER  1980


WITH REPORT;
PROCEDURE  C83F03D0M  IS

     USE REPORT ;

     X1 : INTEGER := 17 ;

     TYPE  T1  IS  ( A, B, C ) ;

     Z : T1 := A ;

     FLOW_INDEX : INTEGER := 0 ;


     PACKAGE  C83F03D1  IS

          Y3 : INTEGER := 100 ;

          TYPE  T3  IS  ( D , E , F ) ;

          PACKAGE  P  IS
               AA : BOOLEAN := FALSE ;
          END  P ;

     END  C83F03D1 ;


     Y1 : INTEGER := 100 ;


     PACKAGE BODY  C83F03D1  IS SEPARATE ;


BEGIN

     TEST( "C83F03D" , "CHECK THE RECOGNITION OF LABELS IN NESTED" &
                       " PACKAGES SEPARATELY COMPILED AS SUBUNITS" );

     << LABEL_IN_MAIN >>

     IF  FLOW_INDEX /= 10
     THEN  FAILED( "INCORRECT FLOW OF CONTROL" );
     END IF;

     RESULT;   --  POSS. ERROR DURING ELABORATION OF  P


END C83F03D0M;
