-- C83F03C2M.ADA


-- MAIN PROGRAM REQUIRING A SEPARATELY COMPILED PACKAGE
--    ( C83F03C0 ; SPECIFICATION IN  C83F03C0.ADA ,
--                 BODY IN           C83F03C1.ADA )

-- CHECK THAT IF A PACKAGE BODY IS NESTED INSIDE A SEPARATELY COMPILED
--    PACKAGE BODY
--    THE INNER PACKAGE BODY CAN CONTAIN A LABEL IDENTIFIER IDENTICAL
--    TO A LABEL IDENTIFIER IN THE OUTER PACKAGE BODY OR TO AN IDENTI-
--    FIER DECLARED IN THE OUTER PACKAGE BODY OR IN ITS SPECIFICATION.

-- CASE 1:  PACKAGE IS A FULL-FLEDGED COMPILATION UNIT


--    RM    05 SEPTEMBER 1980


WITH REPORT , C83F03C0 ;
PROCEDURE  C83F03C2M  IS

     USE  REPORT , C83F03C0 ;

BEGIN

     TEST( "C83F03C" , "CHECK THAT IF A PACKAGE BODY IS NESTED" &
                       " INSIDE A SEPARATELY COMPILED PACKAGE BODY" &
                       " LIBRARY UNIT, THE INNER" &
                       " PACKAGE BODY CAN CONTAIN A LABEL IDENTIFIER" &
                       " IDENTICAL TO A LABEL IDENTIFIER IN THE OUTER" &
                       " PACKAGE BODY OR TO AN IDENTIFIER DECLARED IN" &
                       " THE OUTER PACKAGE BODY OR IN ITS SPECIFICA" &
                       "TION" ) ;

     IF  FLOW_INDEX /= 5
     THEN  FAILED( "INCORRECT FLOW OF CONTROL" );
     END IF;

     RESULT;   --  POSS. ERROR DURING ELABORATION OF  P


END C83F03C2M;
