-- C83F03C0.ADA


-- SEPARATELY COMPILED PACKAGE FOR USE WITH  C83F03C2M

-- THIS PACKAGE IS A FULL-FLEDGED COMPILATION UNIT (AS OPPOSED TO
--    BEING A SUBUNIT; SUBUNITS ARE TESTED IN  C83F03D0M ,
--    C83F03D1 ). THE PRESENT FILE CONTAINS THE SPECIFICATION
--    OF THE PACKAGE.  THE PACKAGE BODY IS IN  C83F03C1.ADA .


--    RM    04 SEPTEMBER 1980


PACKAGE  C83F03C0  IS

     Y3 : INTEGER := 100 ;

     TYPE  T3  IS  ( D , E , F ) ;

     FLOW_INDEX : INTEGER := 0 ;

     PACKAGE  P  IS
     
          AA : BOOLEAN := FALSE ;
     
     END  P ;

END  C83F03C0 ;
