-- C83F01C1.ADA


-- SEPARATELY COMPILED PACKAGE FOR USE WITH  C83F01C2M

-- THIS PACKAGE IS A FULL-FLEDGED COMPILATION UNIT (AS OPPOSED TO
--    BEING A SUBUNIT; SUBUNITS ARE TESTED IN  C83F01D0M ,
--    C83F01D1 ). THE PRESENT FILE CONTAINS THE BODY OF THE PACKAGE.

-- FOR THIS FILE, THE FILE NAME AND THE UNIT NAME ARE NOT THE SAME.


--    RM    13 AUGUST 1980
--    RM    22 AUGUST 1980
--    RM    28 AUGUST 1980  ('FAILED(.)' MOVED TO MAIN)


PACKAGE BODY  C83F01C0  IS

     Y4 : INTEGER := 200 ;

     PACKAGE BODY  P  IS
     BEGIN

          X1 :=  NOT X1  AND  Y1  AND  Y3 ;
          Z  :=  Z + T1 ;
          Y2 := X2 * Y2 ;
          Y4 := X2 * Y4 ;

          -- INCORRECT INTERPRETATIONS IN THE FIRST TWO
          --    ASSIGNMENTS  MANIFEST THEMSELVES AT
          --    COMPILE TIME AS TYPE ERRORS.

          -- ALL 4 ASSIGNMENTS ARE TESTED IN THE MAIN PROGRAM (RATHER
          --    THAN HERE) TO PRECLUDE FALSE NEGATIVES (WHERE THE LACK
          --    OF ELABORATION-TIME ERROR MESSAGES SIMPLY MEANS THAT THE
          --    PACKAGE WAS NOT ELABORATED).


     END P ;

END C83F01C0 ;
