-- C83F01D1.ADA


-- SEPARATELY COMPILED PACKAGE BODY FOR USE WITH  C83F01D0M


--    RM    13 AUGUST 1980
--    RM    29 AUGUST 1980



SEPARATE (C83F01D0M)
PACKAGE BODY  C83F01D1  IS

     Y4 : INTEGER := 200 ;

     PACKAGE BODY  P  IS
     BEGIN

          X1 :=  NOT X1  AND  Y1  AND  Y3 ;
          Z  :=  Z + T1 ;
          Y2 := X2 * Y2 ;
          Y4 := X2 * Y4 ;

          -- ALL 4 ASSIGNMENTS ARE TESTED IN THE MAIN PROGRAM (RATHER
          --    THAN HERE) TO PRECLUDE FALSE NEGATIVES (WHERE THE LACK
          --    OF ELABORATION-TIME ERROR MESSAGES SIMPLY MEANS THAT THE
          --    PACKAGE WAS NOT ELABORATED).

          -- INCORRECT INTERPRETATIONS IN THE FIRST TWO
          --    ASSIGNMENTS  MANIFEST THEMSELVES AT
          --    COMPILE TIME AS TYPE ERRORS.

     END P ;

END C83F01D1 ;
