-- C83F01C0.ADA


-- SEPARATELY COMPILED PACKAGE FOR USE WITH  C83F01C2M

-- THIS PACKAGE IS A FULL-FLEDGED COMPILATION UNIT (AS OPPOSED TO
--    BEING A SUBUNIT; SUBUNITS ARE TESTED IN  C83F01D0M ,
--    C83F01D1 ). THE PRESENT FILE CONTAINS THE SPECIFICATION
--    OF THE PACKAGE. THE BODY IS IN FILE C83F01C1.


--    RM    13 AUGUST 1980
--    RM    22 AUGUST 1980


PACKAGE  C83F01C0  IS

     Y3 : INTEGER := 100 ;

     PACKAGE  P  IS
     
          X1 : BOOLEAN := FALSE ;
          X2 : INTEGER RANGE 1..23 := 11 ;
          Y1 , Y3 : BOOLEAN := TRUE ;
          Y2 , Y4 : INTEGER := 5 ;
          T1 : INTEGER := 6 ;
          Z  : INTEGER := 7 ;
     
     END  P ;

END  C83F01C0 ;
