-- C83F01C2M.ADA


-- MAIN PROGRAM REQUIRING A SEPARATELY COMPILED PACKAGE
--    ( C83F01C0 ; SPECIFICATION IN  C83F01C0.ADA ,
--                 BODY IN           C83F01C1.ADA )

-- CHECK THAT INSIDE A PACKAGE BODY NESTED WITHIN A SEPARATELY COMPILED
--    PACKAGE BODY AN ATTEMPT TO REFERENCE AN IDENTIFIER DECLARED IN THE
--    CORRESPONDING PACKAGE SPECIFICATION
--    IS SUCCESSFUL EVEN IF THE SAME IDENTIFIER IS DECLARED IN THE
--    OUTER PACKAGE (SPECIFICATION OR BODY).

-- CASE 1:  PACKAGE IS A FULL-FLEDGED COMPILATION UNIT


--    RM    11 AUGUST 1980
--    RM    22 AUGUST 1980
--    RM    29 AUGUST 1980 (MOVED 'FAILED(.)' FROM C83F01C1.ADA TO HERE)


WITH REPORT , C83F01C0 ;
PROCEDURE  C83F01C2M  IS

     USE  REPORT , C83F01C0 ;

BEGIN

     TEST( "C83F01C" , "CHECK THAT INSIDE A  PACKAGE BODY" &
                       " NESTED WITHIN A SEPARATELY" &
                       " COMPILED PACKAGE BODY LIBRARY UNIT," &
                       " AN ATTEMPT TO REFERENCE AN IDENTIFIER" &
                       " DECLARED IN THE CORRESPONDING PACKAGE SPECI" &
                       "FICATION  IS SUCCESSFUL EVEN IF THE SAME IDEN" &
                       "TIFIER IS DECLARED IN THE OUTER PACKAGE" &
                       " (SPECIFICATION OR BODY)" ) ;

     IF  NOT P.X1    OR
         P.Z  /= 13  OR
         P.Y2 /= 55  OR
         P.Y4 /= 55
     THEN FAILED( "INCORRECT ACCESSING" );
     END IF;

     RESULT ;


END C83F01C2M;
