-- C85017A.ADA

-- OBJECTIVE:
--     CHECK THAT RENAMING A PREDEFINED OPERATION WITH AN IDENTIFIER
--     AND THEN RENAMING THE IDENTIFIER AS AN OPERATOR SYMBOL ALLOWS THE
--     NEW NAME TO BE USED IN A STATIC EXPRESSION.

-- HISTORY:
--     JET 03/24/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C85017A IS

     FUNCTION PLUS (L,R : INTEGER) RETURN INTEGER RENAMES "+";
     FUNCTION MINUS (L,R : INTEGER) RETURN INTEGER RENAMES "-";

     FUNCTION "-" (L,R : INTEGER) RETURN INTEGER RENAMES PLUS;
     FUNCTION "+" (L,R : INTEGER) RETURN INTEGER RENAMES MINUS;

     I1 : CONSTANT INTEGER := 10 + 10;
     I2 : CONSTANT INTEGER := 10 - 10;

     TYPE INT IS RANGE I1 .. I2;
BEGIN
     TEST("C85017A","CHECK THAT RENAMING A PREDEFINED OPERATION WITH " &
                    "AN IDENTIFIER AND THEN RENAMING THE IDENTIFIER " &
                    "AS AN OPERATOR SYMBOL ALLOWS THE NEW NAME TO BE " &
                    "USED IN A STATIC EXPRESSION");

     IF I1 /= IDENT_INT(0) THEN
          FAILED ("INCORRECT VALUE OF I1: " & INTEGER'IMAGE(I1));
     END IF;

     IF I2 /= IDENT_INT(20) THEN
          FAILED ("INCORRECT VALUE OF I2: " & INTEGER'IMAGE(I2));
     END IF;

     RESULT;
END C85017A;
