-- C85004B.ADA

-- OBJECTIVE:
--     CHECK THAT A RENAMED CONSTANT OBJECT, "IN" PARAMETER OF A
--     SUBPROGRAM OR ENTRY, "IN" FORMAL GENERIC, RECORD DISCRIMINANT,
--     LOOP PARAMETER, DEFERRED CONSTANT, OR RENAMED CONSTANT HAS THE
--     CORRECT VALUE.

-- HISTORY:
--     JET 07/25/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C85004B IS

     TYPE A IS ARRAY (POSITIVE RANGE <>) OF INTEGER;
     SUBTYPE P IS POSITIVE RANGE 1 .. 10;

     C1 : CONSTANT INTEGER := 1;
     X1 : INTEGER RENAMES C1;
     X2 : INTEGER RENAMES X1;

     TYPE REC (D : P := 1) IS
          RECORD
               I : A(1..D);
          END RECORD;
     TYPE ACCREC1 IS ACCESS REC;
     TYPE ACCREC2 IS ACCESS REC(10);

     R1 : REC;
     R2 : REC(10);
     AR1 : ACCREC1 := NEW REC;
     AR2 : ACCREC2 := NEW REC(10);

     X3 : P RENAMES R1.D;
     X4 : P RENAMES R2.D;
     X5 : P RENAMES AR1.D;
     X6 : P RENAMES AR2.D;

     C2 : CONSTANT A(1..3) := (1, 2, 3);
     X7 : INTEGER RENAMES C2(1);

     GENERIC
          K1 : IN INTEGER;
     PACKAGE GENPKG IS
          TYPE K IS PRIVATE;
          K2 : CONSTANT K;
     PRIVATE
          TYPE K IS RANGE 1..100;
          K2 : CONSTANT K := 5;
     END GENPKG;

     TASK FOOEY IS
          ENTRY ENT1 (I : IN INTEGER);
     END FOOEY;

     TASK BODY FOOEY IS
     BEGIN
          ACCEPT ENT1 (I : IN INTEGER) DO
               DECLARE
                    TX1 : INTEGER RENAMES I;
               BEGIN
                    IF TX1 /= IDENT_INT(2) THEN
                         FAILED ("INCORRECT VALUE");
                    END IF;
               END;
          END ENT1;
     END FOOEY;

     PACKAGE BODY GENPKG IS
          KX1 : INTEGER RENAMES K1;
          KX2 : K RENAMES K2;
     BEGIN
          IF KX1 /= IDENT_INT(4) THEN
               FAILED ("INCORRECT VALUE OF KX1");
          END IF;

          IF KX2 /= K(IDENT_INT(5)) THEN
               FAILED ("INCORRECT VALUE OF KX2");
          END IF;
     END GENPKG;

     PROCEDURE PROC (I : IN INTEGER) IS
          PX1 : INTEGER RENAMES I;
     BEGIN
          IF PX1 /= IDENT_INT(3) THEN
               FAILED ("INCORRECT VALUE OF PX1");
          END IF;
     END PROC;

     PACKAGE PKG IS NEW GENPKG(4);

BEGIN
     TEST ("C85004B", "CHECK THAT A RENAMED CONSTANT OBJECT, 'IN' " &
           "PARAMETER OF A SUBPROGRAM OR ENTRY, 'IN' FORMAL GENERIC, " &
           "RECORD DISCRIMINANT, LOOP PARAMETER, DEFERRED CONSTANT, " &
           "OR RENAMED CONSTANT HAS THE CORRECT VALUE");

     FOOEY.ENT1(2);

     PROC(3);

     IF X1 /= IDENT_INT(1) THEN
          FAILED ("INCORRECT VALUE OF X1");
     END IF;

     IF X2 /= IDENT_INT(1) THEN
          FAILED ("INCORRECT VALUE OF X2");
     END IF;

     IF X3 /= IDENT_INT(1) THEN
          FAILED ("INCORRECT VALUE OF X3");
     END IF;

     IF X4 /= IDENT_INT(10) THEN
          FAILED ("INCORRECT VALUE OF X4");
     END IF;

     IF X5 /= IDENT_INT(1) THEN
          FAILED ("INCORRECT VALUE OF X5");
     END IF;

     IF X6 /= IDENT_INT(10) THEN
          FAILED ("INCORRECT VALUE OF X6");
     END IF;

     IF X7 /= IDENT_INT(1) THEN
          FAILED ("INCORRECT VALUE OF X7");
     END IF;

     FOR I IN 1..IDENT_INT(2) LOOP
          DECLARE
               X8 : INTEGER RENAMES I;
          BEGIN
               IF X8 /= IDENT_INT(I) THEN
                    FAILED ("INCORRECT VALUE OF X8");
               END IF;
          END;
     END LOOP;

     RESULT;

END C85004B;
