-- C85019A.ADA

-- CHECK THAT A CHARACTER OR OTHER ENUMERATION LITERAL MAY BE RENAMED 
-- AS A FUNCTION.

-- RJW 6/4/86

WITH REPORT; USE REPORT;

PROCEDURE C85019A IS

BEGIN

     TEST( "C85019A", "CHECK THAT A CHARACTER OR OTHER ENUMERATION " &
                      "LITERAL MAY BE RENAMED AS A FUNCTION" );

     DECLARE
          FUNCTION SEA RETURN CHARACTER RENAMES 'C';

          TYPE COLOR IS (RED, YELLOW, BLUE, GREEN);
          
          FUNCTION TEAL RETURN COLOR RENAMES BLUE;

     BEGIN
          IF SEA /= 'C' THEN
               FAILED ( "SEA IS NOT EQUAL TO 'C'" );
          END IF;

          IF TEAL /= BLUE THEN
               FAILED ( "TEAL IS NOT EQUAL TO BLUE" );
          END IF;

     END;

     RESULT;

END C85019A;
