-- C85005F.ADA

-- OBJECTIVE:
--     CHECK THAT, FOR A RENAMED VARIABLE DESIGNATED BY AN ACCESS VALUE,
--     A CHANGE IN THE ACCESS VALUE DOES NOT AFFECT WHICH VARIABLE IS
--     DENOTED BY THE NEW NAME.

-- HISTORY:
--     JET 07/26/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C85005F IS
     TYPE ACC IS ACCESS INTEGER;

     BUMP : INTEGER := 0;

     A : ACC := NULL;

     FUNCTION GET_POINTER RETURN ACC IS
     BEGIN
          BUMP := IDENT_INT(BUMP) + 1;
          RETURN NEW INTEGER'(BUMP);
     END GET_POINTER;

BEGIN
     TEST ("C85005F", "CHECK THAT, FOR A RENAMED VARIABLE DESIGNATED " &
                      "BY AN ACCESS VALUE, A CHANGE IN THE ACCESS " &
                      "VALUE DOES NOT AFFECT WHICH VARIABLE IS " &
                      "DENOTED BY THE NEW NAME");

     A := GET_POINTER;

     DECLARE
          X1 : INTEGER RENAMES A.ALL;
          X2 : INTEGER RENAMES GET_POINTER.ALL;
     BEGIN
          A := GET_POINTER;

          IF X1 /= 1 THEN
               FAILED("CHANGING ACCESS VALUE CHANGED RENAMED VARIABLE");
          END IF;

          IF X2 /= 2 THEN
               FAILED("INCORRECT RESULT FROM FUNCTION AS PREFIX");
          END IF;
     END;

     RESULT;
END C85005F;
