-- C85016A.ADA

-- OBJECTIVE:
--     CHECK THAT THE ATTRIBUTES 'SUCC, 'PRED, 'IMAGE, AND 'VALUE CAN BE
--     RENAMED AND THAT USING THE NEW NAMES PRODUCES THE CORRECT
--     RESULTS.

-- HISTORY:
--     JET 03/24/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C85016A IS
     FUNCTION SUCC (I: INTEGER) RETURN INTEGER RENAMES INTEGER'SUCC;
     FUNCTION PRED (I: INTEGER) RETURN INTEGER RENAMES INTEGER'PRED;
     FUNCTION IMAGE (I: INTEGER) RETURN STRING RENAMES INTEGER'IMAGE;
     FUNCTION VALUE (I: STRING) RETURN INTEGER RENAMES INTEGER'VALUE;
BEGIN
     TEST ("C85016A", "CHECK THAT THE ATTRIBUTES 'SUCC, 'PRED, " &
                      "'IMAGE, AND 'VALUE CAN BE RENAMED AND THAT " &
                      "USING THE NEW NAMES PRODUCES THE CORRECT " &
                      "RESULTS");

     IF SUCC(100) /= IDENT_INT(101) THEN
          FAILED ("INCORRECT RETURN VALUE FROM SUCC(100)");
     END IF;

     IF PRED(100) /= IDENT_INT(99) THEN
          FAILED ("INCORRECT RETURN VALUE FROM PRED(100)");
     END IF;

     IF IMAGE(100) /= IDENT_STR(" 100") THEN
          FAILED ("INCORRECT RETURN VALUE FROM IMAGE(100)");
     END IF;

     IF VALUE("100") /= IDENT_INT(100) THEN
          FAILED ("INCORRECT RETURN VALUE FROM VALUE(""100"")");
     END IF;

     IF SUCC(-100) /= IDENT_INT(-99) THEN
          FAILED ("INCORRECT RETURN VALUE FROM SUCC(-100)");
     END IF;

     IF PRED(-100) /= IDENT_INT(-101) THEN
          FAILED ("INCORRECT RETURN VALUE FROM PRED(-100)");
     END IF;

     IF IMAGE(-100) /= IDENT_STR("-100") THEN
          FAILED ("INCORRECT RETURN VALUE FROM IMAGE(-100)");
     END IF;

     IF VALUE("-100") /= IDENT_INT(-100) THEN
          FAILED ("INCORRECT RETURN VALUE FROM VALUE(""-100"")");
     END IF;

     RESULT;
END C85016A;
