-- C85006F.ADA

-- OBJECTIVE:
--     CHECK THAT A RENAMED SLICE CAN BE SLICED AND INDEXED FOR PURPOSES
--     OF ASSIGNMENT AND TO READ THE VALUE.

-- HISTORY:
--     JET 07/26/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C85006F IS

     S : STRING(1..30) := "IT WAS A DARK AND STORMY NIGHT";

     ADJECTIVES : STRING RENAMES S(10..24);

BEGIN
     TEST ("C85006F", "CHECK THAT A RENAMED SLICE CAN BE SLICED AND " &
                      "INDEXED FOR PURPOSES OF ASSIGNMENT AND TO " &
                      "READ THE VALUE");

     ADJECTIVES(19..24) := "STARRY";

     IF ADJECTIVES /= IDENT_STR("DARK AND STARRY") THEN
          FAILED ("INCORRECT VALUE OF SLICE AFTER ASSIGNMENT (1)");
     END IF;

     IF S /= IDENT_STR("IT WAS A DARK AND STARRY NIGHT") THEN
          FAILED ("INCORRECT VALUE OF ORIGINAL STRING (1)");
     END IF;

     ADJECTIVES(17) := ''';

     IF ADJECTIVES /= IDENT_STR("DARK AN' STARRY") THEN
          FAILED ("INCORRECT VALUE OF SLICE AFTER ASSIGNMENT (2)");
     END IF;

     IF S /= IDENT_STR("IT WAS A DARK AN' STARRY NIGHT") THEN
          FAILED ("INCORRECT VALUE OF ORIGINAL STRING (2)");
     END IF;

     IF ADJECTIVES(10..13) /= IDENT_STR("DARK") THEN
          FAILED ("INCORRECT VALUE OF SLICE WHEN READING");
     END IF;

     RESULT;

END C85006F;
