-- C86005B.ADA

-- OBJECTIVE:
--     CHECK THAT A GENERIC LIBRARY PACKAGE CAN HAVE THE SAME NAME
--     AS ONE OF THE NON-GRAPHIC CHARACTERS.

-- HISTORY:
--     DHH 06/13/88 CREATED ORIGINAL TEST.

GENERIC
PACKAGE SOH IS
     SUBTYPE O IS INTEGER RANGE 0 .. 10;
END SOH;

WITH SOH;
GENERIC
PACKAGE ACK IS
     PACKAGE ACK1 IS NEW SOH;
     INT : ACK1.O := 10;
END ACK;

WITH ACK;
GENERIC
PACKAGE VT IS
    PACKAGE VT1 IS NEW ACK;
    X : INTEGER := VT1.INT*5;
END VT;

WITH VT;
GENERIC
PACKAGE DLE IS
    PACKAGE DLE1 IS NEW VT;
    Y : DLE1.VT1.ACK1.O := DLE1.X/10;
END DLE;

GENERIC
PACKAGE NAK IS
     PROCEDURE SWAP(X,Y: IN OUT INTEGER);
END NAK;

PACKAGE BODY NAK IS
     PROCEDURE SWAP(X,Y: IN OUT INTEGER) IS
          T : INTEGER;
     BEGIN
          T := X;
          X := Y;
          Y := T;
     END SWAP;
END NAK;


WITH DLE; WITH NAK;
WITH REPORT; USE REPORT;
GENERIC
PACKAGE SUB IS
     PROCEDURE PROC;
END SUB;

PACKAGE BODY SUB IS
     PROCEDURE PROC IS
          PACKAGE NAK1 IS NEW NAK;
          PACKAGE SUB1 IS NEW DLE;
     BEGIN
          NAK1.SWAP(SUB1.Y, SUB1.DLE1.VT1.INT);
          IF SUB1.Y /= IDENT_INT(10) THEN
               FAILED("NON-GRAPHIC PROCEDURE - B-10");
          END IF;
          IF SUB1.DLE1.VT1.INT /= IDENT_INT(5) THEN
               FAILED("NON-GRAPHIC PROCEDURE - B-5");
          END IF;
     END PROC;
END SUB;

WITH NAK;
WITH REPORT; USE REPORT;
GENERIC
PACKAGE US IS
     PROCEDURE PROC1;
END;

PACKAGE BODY US IS
     PROCEDURE PROC1 IS
          SUBTYPE INT IS INTEGER RANGE 0 .. 10;
          A : INT := IDENT_INT(10);
          B : INT := IDENT_INT(0);
          PACKAGE US1 IS NEW NAK;

     BEGIN
          US1.SWAP(A,B);
          IF A /= IDENT_INT(0) THEN
               FAILED("NON-GRAPHIC PROCEDURE - C-0");
          END IF;
          IF B /= IDENT_INT(10) THEN
               FAILED("NON-GRAPHIC PROCEDURE - C-10");
          END IF;
     END PROC1;
END US;

WITH SUB; WITH US;
WITH REPORT; USE REPORT;
PROCEDURE C86005B IS

     PACKAGE SUB2 IS NEW SUB;
     PACKAGE US2 IS NEW US;

BEGIN
     TEST("C86005B", "CHECK THAT A GENERIC LIBRARY PACKAGE CAN HAVE " &
                     "THE SAME NAME AS ONE OF THE NON-GRAPHIC " &
                     "CHARACTERS. USE SOH, ACK, VT, DLE, NAK, SUB, " &
                     "AND US");

     SUB2.PROC;
     US2.PROC1;

     RESULT;
END C86005B;
