-- C86005A.ADA

-- OBJECTIVE:
--     CHECK THAT A LIBRARY PACKAGE CAN HAVE THE SAME NAME AS ONE OF THE
--     NON-GRAPHIC CHARACTERS.

-- HISTORY:
--     DHH 03/15/88 CREATED ORIGINAL TEST.

PACKAGE NUL IS
     SUBTYPE O IS INTEGER RANGE 0 .. 10;
END NUL;

WITH NUL;
PACKAGE ENQ IS
     INT : NUL.O := 10;
END ENQ;

WITH ENQ;
PACKAGE LF IS
    X : INTEGER := ENQ.INT*5;
END LF;

WITH NUL; WITH LF;
PACKAGE SI IS
    Y : NUL.O := LF.X/10;
END SI;

PACKAGE RS IS
     PROCEDURE SWAP(X,Y: IN OUT INTEGER);
END RS;

PACKAGE BODY RS IS
     PROCEDURE SWAP(X,Y: IN OUT INTEGER) IS
          T : INTEGER;
     BEGIN
          T := X;
          X := Y;
          Y := T;
     END SWAP;
END RS;


WITH NUL; WITH ENQ; WITH SI; WITH RS;
WITH REPORT; USE REPORT;

PACKAGE DC4 IS
     PROCEDURE PROC;
END DC4;

PACKAGE BODY DC4 IS
     PROCEDURE PROC IS
     BEGIN
          RS.SWAP(SI.Y, ENQ.INT);
          IF SI.Y /= IDENT_INT(10) THEN
               FAILED("NON-GRAPHIC PROCEDURE - B-10");
          END IF;
          IF ENQ.INT /= IDENT_INT(5) THEN
               FAILED("NON-GRAPHIC PROCEDURE - B-5");
          END IF;
     END PROC;
END DC4;

WITH NUL; WITH ENQ; WITH SI; WITH RS;
WITH REPORT; USE REPORT;
PACKAGE EM IS
     PROCEDURE PROC1;
END;

PACKAGE BODY EM IS
     PROCEDURE PROC1 IS
          SUBTYPE INT IS INTEGER RANGE 0 .. 10;
          A : INT := IDENT_INT(10);
          B : INT := IDENT_INT(0);
     BEGIN
          RS.SWAP(A,B);
          IF A /= IDENT_INT(0) THEN
               FAILED("NON-GRAPHIC PROCEDURE - C-0");
          END IF;
          IF B /= IDENT_INT(10) THEN
               FAILED("NON-GRAPHIC PROCEDURE - C-10");
          END IF;
     END PROC1;
END EM;

WITH DC4; WITH EM;
WITH REPORT; USE REPORT;
PROCEDURE C86005A IS
BEGIN
     TEST("C86005A", "CHECK THAT A LIBRARY PACKAGE CAN HAVE THE SAME " &
                     "NAME AS ONE OF THE NON-GRAPHIC CHARACTERS");

     DC4.PROC;
     EM.PROC1;

     RESULT;
END C86005A;
