-- C86004B2M.ADA

-- OBJECTIVE:
--     CHECK THAT IF THE SPECIFICATION OF A LIBRARY SUBPROGRAM HAS A
--     "WITH" CLAUSE FOR A LIBRARY SUBPROGRAM M, THEN IN THE FORMAL PART
--     AND IN THE BODY (IN ANOTHER FILE), "STANDARD.M" IS A LEGAL NAME
--     FOR THE SUBPROGRAM M.

-- SEPARATE FILES ARE:
--     C86004B0  A LIBRARY FUNCTION AND A LIBRARY SUBPROGRAM
--               SPECIFICATION.
--     C86004B1  A LIBRARY SUBPROGRAM BODY FOR THE C86004B0
--               SPECIFICATION.
--     C86004B2M MAIN PROCEDURE USING THE SUBPROGRAM OF C86004B1.

-- HISTORY:
--     DHH 08/15/88 CREATED ORIGINAL TEST.

WITH C86004B1;
WITH REPORT; USE REPORT;
PROCEDURE C86004B2M IS
BEGIN
     C86004B1(IDENT_INT(0));
END C86004B2M;
