-- C86004C2M.ADA

-- OBJECTIVE:
--     CHECK THAT IF THE SPECIFICATION OF A LIBRARY SUBPROGRAM HAS A
--     "WITH" CLAUSE FOR A GENERIC SUBPROGRAM INSTANTIATION M, THEN IN
--     THE FORMAL PART AND IN THE BODY (A SUBUNIT IN ANOTHER FILE),
--     "STANDARD.M" IS A LEGAL NAME FOR THE SUBPROGRAM M.

-- SEPARATE FILES ARE:
--     C86004C0  A GENERIC LIBRARY FUNCTION AND A LIBRARY SUBPROGRAM
--               DECLARING A SEPARATE SUBUNIT.
--     C86004C1  A SUBUNIT FOR THE C86004C0 PARENT.
--     C86004C2M MAIN PROCEDURE USING THE SUBPROGRAM OF C86004C0.

-- HISTORY:
--     DHH 09/14/88 CREATED ORIGINAL TEST.

WITH C86004C01;
WITH REPORT; USE REPORT;
PROCEDURE C86004C2M IS
BEGIN
     C86004C01(IDENT_INT(0));
END C86004C2M;
