-- C86004C1.ADA

-- OBJECTIVE:
--     SUBUNIT FOR THE C86004C01 PARENT.

-- HISTORY:
--     DHH 09/14/88 CREATED ORIGINAL TEST.

SEPARATE (C86004C01)
PROCEDURE C86004C1 IS
BEGIN
     TEST("C86004C", "CHECK THAT IF THE SPECIFICATION OF A " &
                     "SUBPROGRAM HAS A ""WITH"" CLAUSE FOR A GENERIC " &
                     "SUBPROGRAM INSTANTIANTION M, THEN IN THE " &
                     "FORMAL PART AND IN THE BODY (A SUBUNIT IN " &
                     "ANOTHER FILE), ""STANDARD.M"" IS " &
                     "A LEGAL NAME FOR THE SUBPROGRAM M");

     IF B /= STANDARD.C86004C0(0) THEN
          FAILED("STANDARD.SUBPROGRAM - B");
     END IF;

     IF A /= STANDARD.C86004C0(10) THEN
          FAILED("STANDARD.SUBPROGRAM - A");
     END IF;

     RESULT;
END C86004C1;
