-- C86005E.ADA

-- OBJECTIVE:
--     CHECK THAT A PARAMETERLESS LIBRARY FUNCTION RETURNING THE
--     PREDEFINED TYPE CHARACTER CAN HAVE THE SAME NAME AS ONE OF THE
--     NON-GRAPHIC CHARACTERS. USE EOT, HT, SO, DC3, CAN, AND GS.

-- HISTORY:
--     DHH 06/13/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
FUNCTION EOT RETURN CHARACTER IS
BEGIN
     IF EQUAL(3,3) THEN
          RETURN 'A';
     ELSE
          RETURN 'B';
     END IF;
END EOT;

WITH EOT; WITH REPORT; USE REPORT;
FUNCTION HT RETURN CHARACTER IS
BEGIN
     IF EOT /= 'A' THEN
          FAILED("FUNCTION EOT RETURNING WRONG VALUE");
     END IF;
     RETURN 'A';
END HT;

WITH HT; WITH REPORT; USE REPORT;
FUNCTION SO RETURN CHARACTER IS
BEGIN
     IF HT /= 'A' THEN
          FAILED("FUNCTION HT RETURNING WRONG VALUE");
     END IF;
     RETURN 'A';
END SO;

WITH SO; WITH REPORT; USE REPORT;
FUNCTION DC3 RETURN CHARACTER IS
BEGIN
     IF SO /= 'A' THEN
          FAILED("FUNCTION DC3 RETURNING WRONG VALUE");
     END IF;
     RETURN 'A';
END DC3;

WITH DC3; WITH REPORT; USE REPORT;
FUNCTION CAN RETURN CHARACTER IS
BEGIN
     IF DC3 /= 'A' THEN
          FAILED("FUNCTION DC3 RETURNING WRONG VALUE");
     END IF;
     RETURN 'A';
END CAN;


WITH CAN; WITH REPORT; USE REPORT;
FUNCTION GS RETURN CHARACTER IS
BEGIN
     IF CAN /= 'A' THEN
          FAILED("FUNCTION CAN RETURNING WRONG VALUE");
     END IF;
     RETURN 'A';
END GS;

WITH GS; WITH REPORT; USE REPORT;
PROCEDURE C86005E IS
     A : CHARACTER;
BEGIN
     TEST("C86005E", "CHECK THAT A PARAMETERLESS LIBRARY FUNCTION " &
                     "RETURNING THE PREDEFINED TYPE CHARACTER CAN " &
                     "HAVE THE SAME NAME AS ONE OF THE NON-GRAPHIC " &
                     "CHARACTERS. USE EOT, HT, SO, DC3, CAN, AND GS.");

     IF GS /= 'A' THEN
          FAILED("FUNCTION GS RETURNING WRONG VALUE");
     END IF;
     RESULT;
END C86005E;
