-- C86002B1.ADA


-- SEPARATELY COMPILED SUBPROGRAM FOR USE WITH  C86002B2M

-- RM 01/19/80


WITH  REPORT ;  USE  REPORT ;
FUNCTION  STANDARD (X , Y : BOOLEAN)  RETURN BOOLEAN  IS
BEGIN
     RETURN IDENT_BOOL( FALSE );
END ;
