-- C86004B1.ADA

-- OBJECTIVE:
--     LIBRARY SUBPROGRAM BODY FOR C86004B TEST.

-- HISTORY:
--     DHH 08/15/88 CREATED ORIGINAL TEST.

PROCEDURE C86004B1(INTGR : INTEGER := STANDARD.C86004B0(4)) IS

     SUBTYPE INT IS INTEGER RANGE 0 .. 10;
     A : INT := STANDARD.C86004B0(10);
     B : INT := STANDARD.C86004B0(INTGR);

BEGIN
     TEST("C86004B", "CHECK THAT IF THE SPECIFICATION OF A LIBRARY " &
                     "SUBPROGRAM HAS A ""WITH"" CLAUSE FOR A LIBRARY " &
                     "SUBPROGRAM M, THEN IN THE FORMAL PART AND IN " &
                     "THE BODY (IN ANOTHER FILE), ""STANDARD.M"" IS " &
                      "A LEGAL NAME FOR THE SUBPROGRAM M");

     IF B /= STANDARD.C86004B0(0) THEN
          FAILED("STANDARD.SUBPROGRAM - B");
     END IF;

     IF A /= STANDARD.C86004B0(10) THEN
          FAILED("STANDARD.SUBPROGRAM - A");
     END IF;

     RESULT;
END C86004B1;
