-- C86004A.ADA

-- OBJECTIVE:
--     CHECK THAT IF A LIBRARY SUBPROGRAM DECLARATION IS PRECEDED BY A
--     "WITH" CLAUSE FOR A GENERIC LIBRARY PROCEDURE M, THEN IN THE
--     BODY OF THE SUBPROGRAM, "STANDARD.M" IS A LEGAL NAME
--     FOR THE GENERIC PROCEDURE.

-- HISTORY:
--     DHH 03/14/88 CREATED ORIGINAL TEST.

-- BEGIN BUILDING LIBRARY PROCEDURES

GENERIC
     TYPE ITEM IS (<>);
PROCEDURE C86004A_SWAP(X,Y: IN OUT ITEM);

PROCEDURE C86004A_SWAP(X,Y: IN OUT ITEM) IS
     T : ITEM;
BEGIN
     T := X;
     X := Y;
     Y := T;
END C86004A_SWAP;

WITH C86004A_SWAP; WITH REPORT; USE REPORT;
PROCEDURE C86004A1 IS
     SUBTYPE INT IS INTEGER RANGE 0 .. 10;
     A : INT := IDENT_INT(10);
     B : INT := IDENT_INT(0);
     PROCEDURE SWITCH IS NEW STANDARD.C86004A_SWAP(INT);
BEGIN
     SWITCH(A,B);

     IF A /= IDENT_INT(0) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - 1");
     END IF;

     IF B /= IDENT_INT(10) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - 2");
     END IF;
END C86004A1;

WITH C86004A_SWAP; WITH REPORT; USE REPORT;
PROCEDURE C86004A2;

PROCEDURE C86004A2 IS
     SUBTYPE INT IS INTEGER RANGE 0 .. 10;
     A : INT := IDENT_INT(10);
     B : INT := IDENT_INT(0);
BEGIN
     DECLARE
          PROCEDURE SWITCH IS NEW STANDARD.C86004A_SWAP(INT);
     BEGIN
          SWITCH(A,B);
     END;
     IF A /= IDENT_INT(0) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - B-0");
     END IF;
     IF B /= IDENT_INT(10) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - B-10");
     END IF;
END C86004A2;

WITH C86004A1; WITH C86004A2;
WITH REPORT; USE REPORT;
PROCEDURE C86004A IS
BEGIN
     TEST("C86004A", "CHECK THAT IF A LIBRARY SUBPROGRAM DECLARATION " &
                     "IS PRECEDED BY A ""WITH"" CLAUSE FOR A GENERIC " &
                     "LIBRARY PROCEDURE M, THEN IN THE BODY OF THE " &
                     "SUBPROGRAM, ""STANDARD.M"" IS A " &
                     "LEGAL NAME FOR THE GENERIC PROCEDURE");
     C86004A1;
     C86004A2;

     RESULT;
END C86004A;
