-- C86001E.ADA

-- CHECK THAT LIBRARY UNITS CAN HAVE THE FOLLOWING NAMES:
--   PRIORITY, SELECT_ERROR.
-- CHECK THAT LIBRARY SUBPROGRAMS CAN HAVE THE FOLLOWING NAMES:
--   TRUE, FALSE.

-- JRK 2/24/83
-- JRK 1/9/84
-- JRK 6/5/84


WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE PRIORITY IS
     I1 : INTEGER := IDENT_INT (1);
END PRIORITY;


WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE SELECT_ERROR IS
     I2 : INTEGER := IDENT_INT (2);
END SELECT_ERROR;


WITH REPORT; USE REPORT;
PROCEDURE FALSE (I : IN INTEGER; J : OUT INTEGER) IS
BEGIN
     J := I + IDENT_INT (101);
END FALSE;


WITH REPORT; USE REPORT;
FUNCTION TRUE (I : INTEGER) RETURN INTEGER IS
BEGIN
     RETURN I + IDENT_INT (102);
END TRUE;


WITH PRIORITY, SELECT_ERROR; 
USE  PRIORITY, SELECT_ERROR;
WITH FALSE, TRUE;
WITH REPORT; USE REPORT;

PROCEDURE C86001E IS

     I : INTEGER := 10;

BEGIN
     TEST ("C86001E", "CHECK THAT LIBRARY UNITS CAN HAVE CERTAIN " &
                      "SPECIAL NAMES");

     IF I1 /= 1 THEN
          FAILED ("CAN'T ACCESS LIBRARY PACKAGE NAMED PRIORITY");
     END IF;

     IF I2 /= 2 THEN
          FAILED ("CAN'T ACCESS LIBRARY PACKAGE NAMED SELECT_ERROR");
     END IF;

     FALSE (I, I);
     IF I /= 111 THEN
          FAILED ("CAN'T ACCESS LIBRARY PROCEDURE NAMED FALSE");
     END IF;

     IF TRUE (20) /= 122 THEN
          FAILED ("CAN'T ACCESS LIBRARY FUNCTION NAMED TRUE");
     END IF;

     RESULT;
END C86001E;
