-- C86002A1.ADA


-- SEPARATELY COMPILED PACKAGE (BODY) FOR USE WITH  C86002A2M

-- RM 01/19/80


WITH  REPORT ;  USE  REPORT ;
PACKAGE BODY  STANDARD  IS             -- NON-STANDARD, OF COURSE

     FUNCTION  "+" ( X , Y : BOOLEAN)  RETURN BOOLEAN  IS
     BEGIN
          RETURN IDENT_BOOL( FALSE );
     END "+" ;

END ;
