-- C86007A.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXPANDED NAME FOR AN ENTITY DECLARED IN THE VISIBLE
--     PART OF A LIBRARY PACKAGE CAN START WITH THE NAME "STANDARD".

-- HISTORY:
--     DHH 03/15/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PACKAGE C86007A_PACK IS
     SUBTYPE ITEM IS INTEGER RANGE 0 .. 10;
     Y : STANDARD.C86007A_PACK.ITEM := IDENT_INT(5);
     TYPE ACC IS ACCESS STANDARD.C86007A_PACK.ITEM;
     PROCEDURE SWAP(X,Y: IN OUT ITEM);
     PROCEDURE PROC;
END C86007A_PACK;

PACKAGE BODY C86007A_PACK IS
     PROCEDURE SWAP(X,Y: IN OUT STANDARD.C86007A_PACK.ITEM) IS
          T : STANDARD.C86007A_PACK.ITEM;
     BEGIN
          T := X;
          X := Y;
          Y := T;
     END SWAP;

     PROCEDURE PROC IS
          X : STANDARD.C86007A_PACK.ITEM := IDENT_INT(10);
          W : STANDARD.C86007A_PACK.ACC;
     BEGIN

          W := NEW STANDARD.C86007A_PACK.ITEM;
          W.ALL := X;
          STANDARD.C86007A_PACK.SWAP(X, STANDARD.C86007A_PACK.Y);
          IF STANDARD.C86007A_PACK.Y /= IDENT_INT(10) THEN
               FAILED("FAILED STANDARD.NAME CALL PROCEDURE - B-10");
          END IF;
          IF X /= IDENT_INT(5) THEN
               FAILED("FAILED STANDARD.NAME CALL PROCEDURE - B-5");
          END IF;
     END PROC;
END C86007A_PACK;

WITH C86007A_PACK; WITH REPORT; USE REPORT;
PROCEDURE C86007A IS
BEGIN
     TEST("C86007A", "CHECK THAT AN EXPANDED NAME FOR AN ENTITY " &
                     "DECLARED IN THE VISIBLE PART OF A LIBRARY " &
                     "PACKAGE CAN START WITH THE NAME ""STANDARD""");

     STANDARD.C86007A_PACK.PROC;

     RESULT;
END C86007A;
