-- C86006A.ADA

-- OBJECTIVE:
--     CHECK THAT THE IDENTIFIERS "BOOLEAN, TRUE, FALSE" ARE DECLARED
--     IN THE PACKAGE "STANDARD", ALONG WITH THE OPERATORS OF THE TYPE
--     BOOLEAN.

-- HISTORY:
--     DHH 03/15/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE C86006A IS

     A,B : STANDARD.BOOLEAN := STANDARD.FALSE;
     C,D : STANDARD.BOOLEAN := STANDARD.TRUE;
BEGIN

     TEST("C86006A", "CHECK THAT THE IDENTIFIERS ""BOOLEAN, TRUE, " &
                     "FALSE"" ARE DECLARED IN THE PACKAGE " &
                     """STANDARD"", ALONG WITH THE OPERATORS OF THE " &
                     "TYPE BOOLEAN");

     IF STANDARD."NOT"(C) THEN
          FAILED("STANDARD.NOT FAILED");
     END IF;

     IF STANDARD."AND"(C,A) THEN
          FAILED("STANDARD.AND FAILED");
     END IF;

     IF STANDARD."OR"(A,B) THEN
          FAILED("STANDARD.OR FAILED");
     END IF;

     IF STANDARD."XOR"(A,B) THEN
          FAILED("STANDARD.XOR FAILED");
     END IF;

     IF STANDARD."<"(A,B) THEN
          FAILED("STANDARD.< FAILED");
     END IF;

     IF STANDARD.">"(A,B) THEN
          FAILED("STANDARD.> FAILED");
     END IF;

     IF STANDARD."/="(A,B) THEN
          FAILED("STANDARD./= FAILED");
     END IF;

     IF STANDARD."="(A,C) THEN
          FAILED("STANDARD.= FAILED");
     END IF;

     IF STANDARD.">="(A,C) THEN
          FAILED("STANDARD.>= FAILED");
     END IF;

     IF STANDARD."<="(C,A) THEN
          FAILED("STANDARD.<= FAILED");
     END IF;

     RESULT;

END C86006A;
