-- C87A05A.ADA
    
-- CHECK THAT FUNCTION CALLS AND INDEXED COMPONENT EXPRESSIONS CAN BE 
-- DISTINGUISHED BY THE RULES OF OVERLOADING RESOLUTION.
--
-- PART 1 : CORRECT RESOLUTION IS INDEXED COMPONENT EXPRESSION
  
-- TRH  13 JULY 82
-- DSJ  09 JUNE 83
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87A05A IS
     
     OK : BOOLEAN := TRUE;
     TYPE VECTOR IS ARRAY (1 .. 5) OF BOOLEAN;
  
     PROCEDURE P (ARG : BOOLEAN) IS          -- THIS IS CORRECT P
     BEGIN 
          OK := ARG;
     END P;
  
     PROCEDURE P (ARG : CHARACTER) IS
     BEGIN 
          OK := FALSE;
     END P;

     FUNCTION Y RETURN VECTOR IS             -- THIS IS CORRECT Y
     BEGIN
          RETURN (VECTOR'RANGE => TRUE);
     END Y;

     FUNCTION Y (ARG : INTEGER) RETURN FLOAT IS
     BEGIN 
          OK := FALSE;
          RETURN 0.0;
     END Y;
       
     FUNCTION Y (ARG : CHARACTER) RETURN CHARACTER IS
     BEGIN 
          OK := FALSE;
          RETURN 'A';
     END Y;
   
     FUNCTION Y (ARG : FLOAT) RETURN FLOAT IS
     BEGIN 
          OK := FALSE;
          RETURN 0.0;
     END Y;
       
     FUNCTION Y RETURN BOOLEAN IS
     BEGIN 
          OK := FALSE;
          RETURN FALSE;
     END Y;
       
     FUNCTION Y (ARG : CHARACTER := 'A') RETURN BOOLEAN IS
     BEGIN 
          OK := FALSE;
          RETURN FALSE;
     END Y;
    
     FUNCTION Z RETURN INTEGER IS            -- THIS IS CORRECT Z
     BEGIN 
          RETURN 3;
     END Z;
       
     FUNCTION Z RETURN FLOAT IS
     BEGIN 
          OK := FALSE;
          RETURN 3.0;
     END Z;
   
BEGIN
     TEST ("C87A05A","OVERLOADING RESOLUTION FOR DISTINGUISHING " &
           "FUNCTION CALLS FROM INDEXED COMPONENTS WHERE INDEXED " &
           "COMPONENTS ARE CORRECT");
  
     P (Y (Z) );
  
     IF NOT OK THEN 
          FAILED ("RESOLUTION INCORRECT");
     END IF;
    
     RESULT;
END C87A05A;
