-- C87B14D.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN SUBTYPE INDICATIONS WITH INDEX CONSTRAINTS, IF A BOUND IS OF
-- TYPE UNIVERSAL_INTEGER, IT IS IMPLICITLY CONVERTED TO THE
-- INDEX BASE TYPE.
  
-- TRH  7 JULY 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B14D IS
     
     TYPE WHOLE IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
     TYPE LIST  IS ARRAY (WHOLE RANGE <>) OF BOOLEAN;
  
BEGIN
     TEST ("C87B14D","OVERLOADED EXPRESSIONS IN INDEX CONSTRAINTS " &
           "OF SUBTYPE INDICATIONS WITH UNIVERSAL_INTEGER BOUNDS");
   
     DECLARE
          FUNCTION "+" (X, Y : WHOLE) RETURN WHOLE 
               RENAMES "*";
   
          SUBTYPE LIST1 IS LIST (1 + 1 .. 1 + 1);
          SUBTYPE LIST2 IS LIST (1     .. 3 + 3);
          SUBTYPE LIST3 IS LIST (1 + 1 ..     2);
  
     BEGIN
          IF LIST1'FIRST /= 1 OR LIST1'LAST /= 1 OR
             LIST2'FIRST /= 1 OR LIST2'LAST /= 9 OR
             LIST3'FIRST /= 1 OR LIST3'LAST /= 2 THEN 
             FAILED ("RESOLUTION INCORRECT - IMPLICIT CONVERSION " &
                     "OF UNIVERSAL_INTEGER TYPE TO INDEX CONSTRAINT " &
                     "BASE TYPE");
          END IF;
     END;
    
     RESULT;
END C87B14D;
