-- C87B06A.ADA

-- OBJECTIVE:
--     CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
--     FOR EACH INTEGER TYPE, THERE EXISTS AN IMPLICIT CONVERSION THAT
--     CONVERTS A UNIVERSAL INTEGER VALUE INTO THE CORRESPONDING VALUE
--     OF THE INTEGER TYPE. THIS TEST USES LITERALS AS UNIVERSAL INTEGER
--     VALUES.

-- HISTORY:
--     TRH 08/11/82 CREATED ORIGINAL TEST.
--     DHH 10/20/87 SHORTENED LINES CONTAINING MORE THAN 72 CHARACTERS.

WITH REPORT; USE REPORT;

PROCEDURE C87B06A IS

     TYPE MINOR IS NEW INTEGER RANGE 0 .. 17;
     TYPE FIXED IS NEW DURATION;
     TYPE REAL  IS NEW FLOAT;

     ERR : BOOLEAN := FALSE;

     PROCEDURE P (X : BOOLEAN) IS
     BEGIN
          ERR := TRUE;
     END P;
     PROCEDURE P (X : FIXED) IS
     BEGIN
          ERR := TRUE;
     END P;

     PROCEDURE P (X : REAL) IS
     BEGIN
          ERR := TRUE;
     END P;

     PROCEDURE P (X : FLOAT) IS
     BEGIN
          ERR := TRUE;
     END P;

     PROCEDURE P (X : STRING) IS
     BEGIN
          ERR := TRUE;
     END P;

     PROCEDURE P (X : MINOR) IS
     BEGIN
          NULL;
     END P;

BEGIN
     TEST("C87B06A","OVERLOADING RESOLUTION WITH IMPLICIT CONVERSION " &
          "OF UNIVERSAL INTEGER VALUES TO INTEGER VALUES. " &
          "CONVERSIONS TO INTEGER VALUES EXISTS FOR ANY INTEGER TYPE");

     P (2);
     P (2 * 2 + 2);

     IF ERR THEN
          FAILED("INCORRECT IMPLICIT CONVERSION FROM UNIVERSAL " &
                 " INTEGER VALUES TO INTEGER TYPE VALUES");
     END IF;

     RESULT;
END C87B06A;
