-- C87B27A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE TYPE OF A STRING LITERAL MUST BE DETERMINED FROM THE FACT
-- THAT A STRING LITERAL IS A VALUE OF A ONE DIMENSIONAL ARRAY OF
-- CHARACTER COMPONENTS.
  
-- TRH  18 AUG 82
-- DSJ  07 JUN 83
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B27A IS
 
     TYPE ENUMLIT   IS (A, B, C, D, E, F);
     TYPE NEW_CHAR  IS NEW CHARACTER RANGE 'G' .. 'Z';
     TYPE CHARS3    IS ('G','H','I','K','M','N','P','R','S','T');
     TYPE CHARS4    IS ('S','T','R','I','N','G','Z','A','P');
     TYPE NEW_STR   IS ARRAY  (A .. F) OF NEW_CHAR;
     TYPE STRING3   IS ARRAY  (11..16) OF CHARS3;
     TYPE STRING4   IS ARRAY  (21..26) OF CHARS4;
     TYPE ENUM_VEC  IS ARRAY  (1 .. 6) OF ENUMLIT;
     TYPE CHAR_GRID IS ARRAY  (D .. F, 1 .. 3) OF NEW_CHAR;
     TYPE STR_LIST  IS ARRAY  (1 .. 6) OF STRING (1 .. 1);
     ERR : BOOLEAN  := FALSE;
 
     PROCEDURE P (X : NEW_STR) IS
     BEGIN
          NULL;
     END P;
 
     PROCEDURE P (X : ENUM_VEC) IS
     BEGIN
          ERR := TRUE;
     END P;
 
     PROCEDURE P (X : CHAR_GRID) IS
     BEGIN
          ERR := TRUE;
     END P;
 
     PROCEDURE P (X : STR_LIST) IS
     BEGIN
          ERR := TRUE;
     END P;
 
BEGIN
     TEST ("C87B27A","OVERLOADING RESOLUTION OF STRING LITERALS");
    
     P ("STRING");
 
     IF ERR THEN
          FAILED ("RESOLUTION INCORRECT FOR STRING LITERALS");
     END IF;
 
     RESULT;
END C87B27A;
