-- C87B04B.ADA

-- OBJECTIVE:
--      CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:

--      IN AN ACCURACY CONSTRAINT OF A SUBTYPE INDICATION, THE
--      EXPRESSIONS FOR THE LOWER AND UPPER BOUNDS MUST BE COMPATIBLE
--      WITH THE SUBTYPE'S EXPLICIT TYPEMARK.

-- HISTORY:
--      TRH 06/29/82  CREATED ORIGINAL TEST.
--      BCB 11/12/87  CHANGED HEADER TO STANDARD FORMAT.  CORRECTED
--                    CONSTRAINT ERRORS.

WITH REPORT; USE REPORT;

PROCEDURE C87B04B IS

     TYPE EXACT IS DIGITS 5     RANGE -1.0 .. 1.0;
     TYPE HEX IS DELTA  2.0 ** (-4) RANGE -1.0 .. 1.0;

     FUNCTION F1 RETURN EXACT IS
     BEGIN
          RETURN 0.0;
     END F1;

     FUNCTION F1 RETURN FLOAT IS
     BEGIN
          FAILED ("RESOLUTION INCORRECT - ACCURACY CONSTRAINT OF " &
                  "SUBTYPE INDICATION - F1");
          RETURN 0.0;
     END F1;

     FUNCTION "+" (X : INTEGER) RETURN HEX IS
     BEGIN
          RETURN 0.0;
     END "+";

     FUNCTION "+" (X : INTEGER) RETURN FLOAT IS
     BEGIN
          FAILED ("RESOLUTION INCORRECT - ACCURACY CONSTRAINT OF " &
                  "SUBTYPE INDICATION - +");
          RETURN 0.0;
     END "+";

BEGIN
     TEST ("C87B04B","OVERLOADED EXPRESSIONS IN ACCURACY CONTRAINTS" &
           " OF FLOATING/FIXED POINT SUBTYPE INDICATIONS");

     DECLARE
          SUBTYPE CLOSE IS EXACT DIGITS 4    RANGE -1.0 .. F1;
          SUBTYPE BIN IS HEX DELTA 2.0 ** (-1) RANGE "+" (0) .. 0.5;

     BEGIN
          NULL;
     END;

     RESULT;
END C87B04B;
