-- C87B07C.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- FOR THE ATTRIBUTE OF THE FORM T'VALUE (X), THE OPERAND X MUST 
-- BE OF THE PREDEFINED TYPE STRING. THE RESULT IS OF TYPE T.
  
-- TRH  13 SEPT 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B07C IS
 
     TYPE CHAR IS NEW CHARACTER;
     TYPE LITS IS (' ', '+', '1');
     TYPE WORD IS ARRAY (POSITIVE RANGE <>) OF CHARACTER;
     TYPE LINE IS ARRAY (POSITIVE RANGE <>) OF CHAR;
     TYPE LIST IS ARRAY (POSITIVE RANGE <>) OF LITS;
     TYPE STR  IS ARRAY (POSITIVE RANGE <>) OF STRING (1 .. 1);
     TYPE STR2 IS NEW STRING;
     TYPE FLAG IS (PASS, FAIL);
     
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : IN FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
               FAILED ("THE 'VALUE' ATTRIBUTE TAKES AN OPERAND" &
                       " OF THE TYPE PREDEFINED STRING");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION F IS NEW F1 (STR2,   " +1 ",               FAIL);
     FUNCTION F IS NEW F1 (LIST,   " +1 ",               FAIL);
     FUNCTION F IS NEW F1 (WORD,   (' ', '+', '1', ' '), FAIL);
     FUNCTION F IS NEW F1 (STR,    (" ", "+", "1", " "), FAIL);
     FUNCTION F IS NEW F1 (LINE,   (' ', '+', '1', ' '), FAIL);
     FUNCTION F IS NEW F1 (STRING, " +1 ",               PASS);
    
BEGIN
     TEST ("C87B07C","OVERLOADED OPERANDS TO THE 'VALUE' ATTRIBUTE");
    
     DECLARE
          TYPE INT IS NEW INTEGER;
          FUNCTION "-" (X : INT) RETURN INT 
               RENAMES "+";
 
     BEGIN
          IF INT'VALUE (F) /= -1 THEN
               FAILED ("THE ATTRIBUTE T'VALUE MUST RETURN A VALUE" &
                       " OF TYPE T");
          END IF;
     END;
 
     RESULT;
END C87B07C;
