-- C87B34B.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
    
-- THE "IN" (OR MEMBERSHIP) OPERATOR OF THE FORM:  X IN L .. R
-- REQUIRES THE OPERANDS X, L AND R TO BE OF THE SAME SCALAR TYPE.
  
-- TRH  19 JULY 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B34B IS
 
     TYPE FLAG IS (PASS, FAIL);
  
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : IN FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
             FAILED ("RESOLUTION INCORRECT FOR 'IN' MEMBERSHIP TEST");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION X IS NEW F1 (FLOAT,     2.0, PASS);
     FUNCTION L IS NEW F1 (FLOAT,    -1.0, PASS);
     FUNCTION R IS NEW F1 (FLOAT,     1.0, PASS);
     FUNCTION X IS NEW F1 (STRING,    "B", FAIL);
     FUNCTION L IS NEW F1 (STRING,    "A", FAIL);
     FUNCTION R IS NEW F1 (STRING,    "C", FAIL);
     FUNCTION X IS NEW F1 (INTEGER,     5, FAIL);
     FUNCTION L IS NEW F1 (INTEGER,     1, FAIL);
     FUNCTION L IS NEW F1 (CHARACTER, 'A', FAIL);
     FUNCTION R IS NEW F1 (CHARACTER, 'E', FAIL);
     FUNCTION X IS NEW F1 (BOOLEAN,  TRUE, FAIL);
     FUNCTION R IS NEW F1 (BOOLEAN,  TRUE, FAIL);
    
BEGIN
     TEST ("C87B34B","OVERLOADED MEMBERSHIP OPERANDS");
 
     IF X IN L .. R THEN 
        FAILED ("RESOLUTION INCORRECT FOR MEMBERSHIP OPERATOR");
     END IF;
 
     RESULT;
END C87B34B;
