-- C87B07D.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE ATTRIBUTES OF THE FORM T'SUCC (X) AND T'PRED (X) TAKE AN
-- OPERAND X OF TYPE T AND RETURN A VALUE OF TYPE T.
  
-- TRH  15 SEPT 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B07D IS
 
     TYPE NEW_INT IS NEW INTEGER;
     TYPE WHOLE   IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
  
     FUNCTION "+" (X, Y : WHOLE)   RETURN WHOLE 
          RENAMES "*";
     FUNCTION "+" (X, Y : NEW_INT) RETURN NEW_INT
          RENAMES "-";
    
BEGIN
     TEST ("C87B07D","OVERLOADED OPERANDS TO THE ATTRIBUTES " &
           "'PRED' AND 'SUCC'");
    
     IF INTEGER'SUCC (1 + 1) /= 3  OR INTEGER'SUCC (3 + 3) + 1 /= 8  OR
        NEW_INT'SUCC (1 + 1) /= 1  OR NEW_INT'SUCC (3 + 3) + 1 /= 0  OR
        WHOLE'SUCC   (1 + 1) /= 2  OR WHOLE'SUCC   (3 + 3) + 1 /= 10 OR
        INTEGER'PRED (1 + 1) /= 1  OR INTEGER'PRED (3 + 3) + 1 /= 6  OR
        NEW_INT'PRED (1 + 1) /= -1 OR NEW_INT'PRED (3 + 3) + 1 /= -2 OR
        WHOLE'PRED   (1 + 1) /= 0  OR WHOLE'PRED   (3 + 3) + 1 /= 8  
        THEN FAILED ("RESOLUTION INCORRECT FOR OPERAND OR RESULT OF" &
                     " THE 'PRED' OR 'SUCC' ATTRIBUTE");
     END IF;
     
     RESULT;
END C87B07D;
