-- C87B48A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- NAMED ACTUAL PARAMETERS CAN RESOLVE OVERLOADING OF SUBPROGRAMS.
-- THIS TEST USES FUNCTIONS AND OPERATOR SYMBOLS ONLY.
  
-- TRH  13 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B48A IS
 
     ERR, B1, B2 : BOOLEAN := FALSE;
 
     PACKAGE A IS
          FUNCTION "-"    (X : BOOLEAN) RETURN BOOLEAN;
          FUNCTION TOGGLE (X : BOOLEAN) RETURN BOOLEAN
               RENAMES "-";
     END A;
     
     PACKAGE BODY A IS
          FUNCTION "-" (X : BOOLEAN) RETURN BOOLEAN IS
          BEGIN
               RETURN NOT X;
          END "-";
     END A;
 
     PACKAGE B IS
          FUNCTION "-"    (Y : BOOLEAN) RETURN BOOLEAN;
          FUNCTION TOGGLE (Y : BOOLEAN) RETURN BOOLEAN
               RENAMES "-";
     END B;
     
     PACKAGE BODY B IS
          FUNCTION "-" (Y : BOOLEAN) RETURN BOOLEAN IS
          BEGIN
               ERR := TRUE;
               RETURN NOT Y;
          END "-";
     END B;
 
     PACKAGE C IS
          FUNCTION "-"    (Z : BOOLEAN) RETURN BOOLEAN;
          FUNCTION TOGGLE (Z : BOOLEAN) RETURN BOOLEAN
               RENAMES "-";
     END C;
     
     PACKAGE BODY C IS
          FUNCTION "-" (Z : BOOLEAN) RETURN BOOLEAN IS
          BEGIN
               ERR := TRUE;
               RETURN NOT Z;
          END "-";
     END C;
   
     USE A, B, C;
 
BEGIN
     TEST ("C87B48A","RESOLUTION OF OVERLOADED SUBPROGRAMS BY NAMED " &
           "ACTUAL PARAMETERS");
 
     B1 := "-"    (X => FALSE);
     B2 := TOGGLE (X => FALSE);
   
     IF ERR OR ELSE NOT B1 OR ELSE NOT B2 THEN 
          FAILED ("RESOLUTION INCORRECT FOR OVERLOADED SUBPROGRAMS" &
                  " WITH NAMED ACTUAL PARAMETERS");
     END IF;
 
     RESULT;
END C87B48A;
