-- C87B35B.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE FOLLOWING RULES:
--
-- IF THE RESULT OF A PREDEFINED DIVISION FOR FIXED POINT TYPES IS
-- NOT EXPLICITLY CONVERTED TO SOME NUMERIC TYPE, THEN THE RIGHT
-- HAND OPERAND OF A FIXED POINT MULTIPLICATION MUST BE OF THE TYPE
-- PREDEFINED INTEGER.
--
-- IF THE RESULT OF A PREDEFINED MULTIPLICATION FOR FIXED POINT TYPES
-- IS NOT EXPLICITLY CONVERTED TO SOME NUMERIC TYPE, THEN ONE OF THE
-- OPERANDS OF A FIXED POINT MULTIPLICATION MUST BE OF THE TYPE
-- PREDEFINED INTEGER.
  
-- TRH  19 JULY 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B35B IS
 
     TYPE REAL IS DELTA 1.0 RANGE 0.0 .. 4.0;
     R1, R2, R3  : REAL;
     ERR : BOOLEAN := FALSE;
   
     FUNCTION F1 (X : INTEGER) RETURN INTEGER IS
     BEGIN 
          RETURN X;
     END F1;
       
     FUNCTION F1 (X : INTEGER) RETURN FLOAT IS
     BEGIN 
          ERR := TRUE;
          RETURN 1.0;
     END F1;
    
     FUNCTION F1 (X : INTEGER) RETURN REAL IS
     BEGIN 
          ERR := TRUE;
          RETURN 1.0;
     END F1;
 
BEGIN
     TEST ("C87B35B","PREDEFINED INTEGER OPERANDS IN PREDEFINED" &
           "DIVISION AND MULTIPLICATION FOR FIXED POINT TYPES");
  
     DECLARE
          FUNCTION "+" (X, Y : INTEGER) RETURN INTEGER
               RENAMES STANDARD."*";
    
     BEGIN
          R1 := 1.0 / F1 (1);
          R2 := 1.0 * F1 (1);
          R3 := F1 (1) * 1.0;
 
          IF 2.0 / (1 + 1) /= REAL'(2.0) THEN
             FAILED ("RESOLUTION INCORRECT FOR FIXED POINT DIVISION" &
                     " OR MULTIPLICATION - 1");
          END IF;
          IF 2.0 * (1 + 1) /= REAL'(2.0) THEN
             FAILED ("RESOLUTION INCORRECT FOR FIXED POINT DIVISION" &
                     " OR MULTIPLICATION - 2");
          END IF;
          IF (1 + 1) * 2.0 /= REAL'(2.0) THEN
             FAILED ("RESOLUTION INCORRECT FOR FIXED POINT DIVISION" &
                     " OR MULTIPLICATION - 3");
          END IF;
          IF ERR                         THEN
             FAILED ("RESOLUTION INCORRECT FOR FIXED POINT DIVISION" &
                     " OR MULTIPLICATION - 4");
          END IF;
     END;
 
     RESULT;
END C87B35B;
