-- C87B30A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE EXPRESSION OF A COMPONENT ASSOCIATION MUST MATCH THE TYPE OF THE 
-- ASSOCIATED RECORD COMPONENT.
  
-- TRH  9 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B30A IS
 
     TYPE REC IS
          RECORD
               W, X : FLOAT;
               Y, Z : INTEGER;
          END RECORD;
 
     TYPE FLAG IS (PASS, FAIL);
     
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : IN FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
               FAILED ("COMPONENT ASSOCIATION EXPRESSION MUST MATCH " &
                       "RECORD COMPONENT TYPE");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION F IS NEW F1 (FLOAT,     2.0, PASS);
     FUNCTION F IS NEW F1 (STRING,    "B", FAIL);
     FUNCTION F IS NEW F1 (INTEGER,     5, FAIL);
     FUNCTION F IS NEW F1 (BOOLEAN,  TRUE, FAIL);
     FUNCTION F IS NEW F1 (CHARACTER, 'E', FAIL);
 
     FUNCTION G IS NEW F1 (FLOAT,     2.0, FAIL);
     FUNCTION G IS NEW F1 (STRING,    "B", FAIL);
     FUNCTION G IS NEW F1 (INTEGER,     5, PASS);
     FUNCTION G IS NEW F1 (BOOLEAN,  TRUE, FAIL);
     FUNCTION G IS NEW F1 (CHARACTER, 'E', FAIL);
    
BEGIN
     TEST ("C87B30A","OVERLOADED EXPRESSIONS IN RECORD AGGREGATE " &
           "COMPONENT ASSOCIATIONS");
    
     DECLARE
          R1 : REC := (F, F, G, G);
          R2 : REC := (X => F, Y => G, Z => G, W => F);
          R3 : REC := (F, F, Z => G, Y => G);
   
     BEGIN
          NULL;
     END;
 
     RESULT;
END C87B30A;
