-- C87B42A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- A CONDITIONAL EXPRESSION MUST BE OF A BOOLEAN TYPE.
  
-- TRH  27 JULY 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B42A IS
 
     TYPE BIT     IS NEW BOOLEAN;
     TYPE BOOLEAN IS (FALSE, TRUE);
     TYPE LIT     IS (FALSE, TRUE);
     TYPE FLAG    IS (PASS, FAIL);
 
     GENERIC 
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS 
     BEGIN
          IF STAT = FAIL THEN 
               FAILED ("CONDITIONAL EXPRESSION MUST BE OF A BOOLEAN" &
                       " TYPE");
          END IF;
          RETURN ARG;
     END F1;
 
     FUNCTION F IS NEW F1 (BOOLEAN, FALSE,  FAIL);
     FUNCTION F IS NEW F1 (BIT,     FALSE,  PASS);
     FUNCTION F IS NEW F1 (LIT,     FALSE,  FAIL);
     FUNCTION F IS NEW F1 (STRING, "FALSE", FAIL);
     FUNCTION F IS NEW F1 (INTEGER,   -11,  FAIL);
     FUNCTION F IS NEW F1 (FLOAT,    +0.0,  FAIL);
    
BEGIN
     TEST ("C87B42A","OVERLOADED CONDITIONAL EXPRESSIONS");
 
     WHILE (F OR NOT F)
     LOOP
          IF (F OR ELSE NOT F) THEN
               NULL;
          END IF;
          EXIT WHEN (F AND NOT F);
          EXIT WHEN (F OR  NOT F);
          EXIT WHEN (F);
          EXIT WHEN (NOT F);
     END LOOP;
 
     RESULT;
END C87B42A;
