-- C87B11B.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A SUBTYPE INDICATION, THE DELTA EXPRESSION FOR A FIXED POINT
-- NUMBER MUST BE OF SOME REAL TYPE. 
  
-- TRH  29 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B11B IS
  
     TYPE DELT3 IS DELTA 3.0 RANGE -30.0 .. 30.0;
     
     FUNCTION "+" (X : FLOAT) RETURN INTEGER IS
     BEGIN 
           FAILED ("DELTA EXPRESSION MUST BE OF A REAL TYPE");
           RETURN 2;
     END "+";
  
BEGIN
     TEST ("C87B11B","OVERLOADED DELTA EXPRESSIONS IN " &
           "FIXED POINT SUBTYPE INDICATIONS");
   
     DECLARE
          SUBTYPE DELT2 IS DELT3 DELTA "+"(6.0);
          SUBTYPE DELT1 IS DELT3 DELTA "+"(10.0) RANGE -10.0 .. 10.0;
  
     BEGIN
          NULL;
     END;
    
     RESULT;
END C87B11B;
