-- C87B37A.ADA

-- CHECK THAT AN IMPLICIT CONVERSION FROM UNIVERSAL INTEGER IS NOT
-- APPLIED IF THERE IS A LEGAL INTERPRETATION WITHOUT THE IMPLICIT
-- CONVERSION. 

-- JBG 10/26/83

WITH REPORT; USE REPORT;
PROCEDURE C87B37A IS
     WHICH_FUNC : INTEGER := 0;

     FUNCTION F (X : BOOLEAN) RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END F;

     FUNCTION F (X : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN 2;
     END F;

     FUNCTION F (X : INTEGER) RETURN FLOAT IS
     BEGIN
          RETURN 3.0;
     END F;

     FUNCTION "<" (L, R : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN 4;
     END "<";

BEGIN

     TEST ("C87B37A", "CHECK THAT IMPLICIT CONVERSIONS ARE ONLY USED " &
                      "WHEN NECESSARY FOR UNIVERSAL INTEGER");

     WHICH_FUNC := F (5 < 5);      -- NO IMPLICIT CONVERSION
     IF WHICH_FUNC /= 1 THEN
          FAILED ("CALLED WRONG F -- 1 ");
     END IF;

     WHICH_FUNC := INTEGER (FLOAT'(F (5 < 5)));   -- IMPLICIT CONVERSION
     IF WHICH_FUNC /= 3 THEN
          FAILED ("CALLED WRONG F --2");
     END IF;

     RESULT;

END C87B37A;
