-- C87B48B.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- POSITIONAL ACTUAL PARAMETERS CAN RESOLVE OVERLOADING OF SUBPROGRAMS.
  
-- TRH  16 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B48B IS
 
     TYPE FLAG IS (PASS, FAIL);
     TYPE INT  IS NEW INTEGER;
     TYPE BIT  IS NEW BOOLEAN;
     TYPE WHL  IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
     
     GENERIC
          TYPE T1 IS PRIVATE;
          TYPE T2 IS PRIVATE;
          TYPE T3 IS PRIVATE;
          TYPE T4 IS PRIVATE;
          STAT : IN FLAG;
     PROCEDURE P1 (W : T1; X : T2; Y : T3; Z : T4);
 
     PROCEDURE P1 (W : T1; X : T2; Y : T3; Z : T4) IS
     BEGIN 
          IF STAT = FAIL THEN 
               FAILED ("RESOLUTION INCORRECT FOR OVERLOADED SUB" &
                       "PROGRAMS WITH POSITIONAL ACTUAL PARAMETERS");
          END IF;
     END P1;
  
     PROCEDURE P IS NEW P1 (WHL, INT, WHL, BIT, PASS);
     PROCEDURE P IS NEW P1 (WHL, WHL, BIT, INT, FAIL);
     PROCEDURE P IS NEW P1 (WHL, INT, BIT, WHL, FAIL);
     PROCEDURE P IS NEW P1 (INT, BIT, WHL, WHL, FAIL);
     PROCEDURE P IS NEW P1 (BIT, WHL, WHL, INT, FAIL);
     PROCEDURE P IS NEW P1 (BIT, INT, WHL, WHL, FAIL);
    
BEGIN
     TEST ("C87B48B","OVERLOADING RESOLUTION OF SUBPROGRAMS WITH" &
           " POSITIONAL ACTUAL PARAMETERS");
    
     BEGIN
          P (0, 0, 0, TRUE);
     END;
 
     RESULT;
END C87B48B;
