-- C87B43A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A CASE STATEMENT, THE TYPE OF EACH CHOICE MUST MATCH THE TYPE 
-- OF THE EXPRESSION.
  
-- TRH  3 AUG 82
-- DSJ 10 JUN 83
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B43A IS
     
     TYPE WHOLE IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
 
     FUNCTION "+" (X, Y : INTEGER) RETURN INTEGER 
          RENAMES "*";
 
     ERR : BOOLEAN := FALSE;
     X   : WHOLE   := 6;
  
BEGIN
     TEST ("C87B43A","TYPE OF CASE CHOICE MUST MATCH TYPE OF " &
           "EXPRESSION");
   
     CASE X IS
          WHEN (2 + 3) => ERR := TRUE;
          WHEN (3 + 3) => NULL; 
          WHEN OTHERS  => ERR := TRUE;
     END CASE;
 
     IF ERR THEN
        FAILED ("CASE STATEMENT CHOICE MUST MATCH TYPE OF EXPRESSION");
     END IF;
    
     RESULT;
END C87B43A;
