-- C87B09B.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A SUBTYPE INDICATION, THE DIGITS EXPRESSION FOR A FLOATING POINT
-- NUMBER MUST BE OF SOME INTEGRAL TYPE. 
  
-- TRH  29 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B09B IS
  
     TYPE EXACT IS DIGITS 5;
     
     FUNCTION "+" (X : INTEGER) RETURN FLOAT IS
     BEGIN 
           FAILED ("DIGITS EXPRESSION MUST BE OF AN INTEGRAL TYPE");
           RETURN 2.0;
     END "+";

BEGIN
     TEST ("C87B09B","OVERLOADED DIGITS EXPRESSIONS IN " &
           "FLOATING POINT SUBTYPE INDICATIONS");
   
     DECLARE
          SUBTYPE APPROX IS EXACT DIGITS "+" (2);
          SUBTYPE CLOSE  IS EXACT DIGITS "+" (4)   RANGE -1.0 .. 1.0;
  
     BEGIN
          NULL;
     END;
    
     RESULT;
END C87B09B;
