-- C87B11A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A FIXED POINT TYPE DEFINITION, THE DELTA EXPRESSION MUST
-- BE OF SOME REAL TYPE.
  
-- TRH  30 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B11A IS
     
     FUNCTION "+" (X : FLOAT) RETURN INTEGER IS
     BEGIN 
           FAILED ("DELTA EXPRESSION MUST BE OF A REAL TYPE");
           RETURN 2;
     END "+";
  
BEGIN
     TEST ("C87B11A","OVERLOADED DELTA EXPRESSIONS IN " &
           "FIXED POINT TYPE DEFINITIONS");
   
     DECLARE
          TYPE SEMI IS DELTA "+" (0.5) RANGE -2.0 .. 2.0;
          TYPE DECI IS DELTA "+" (0.1) RANGE -1.0 .. 1.0;
  
     BEGIN
          NULL;
     END;
    
     RESULT;
END C87B11A;
