-- C87B62C.ADA

-- OBJECTIVE:
--     CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
--       IN A LENGTH CLAUSE THAT SPECIFIES 'SMALL, THE EXPRESSION
--       MUST BE OF SOME REAL TYPE.

-- HISTORY:
--     TRH 09/08/82  CREATED ORIGINAL TEST.
--     PWB 02/19/86  ADDED COMMENTS TO CLARIFY NON-APPLICABILITY;
--                   REMOVED TEXT NOT RELATED TO TEST OBJECTIVE.
--     BCB 01/04/88  MODIFIED HEADER.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT; USE REPORT;

PROCEDURE C87B62C IS

     TYPE POS_INT IS NEW INTEGER RANGE 1 .. INTEGER'LAST;
     TYPE POS_FIX IS DELTA 0.1 RANGE 0.0 .. 10.0;
     ERR : BOOLEAN := FALSE;

     FUNCTION "+" (X : POS_INT) RETURN POS_FIX IS
     BEGIN
          ERR := TRUE;
          RETURN POS_FIX (X);
     END "+";

     FUNCTION "+" (X : POS_FIX) RETURN POS_INT IS
     BEGIN
          ERR := TRUE;
          RETURN POS_INT (X);
     END "+";

BEGIN
     TEST ("C87B62C","OVERLOADED EXPRESSION WITHIN LENGTH CLAUSE " &
           "- SPECIFICATION OF ATTRIBUTE T'SMALL");

     DECLARE
          TYPE JUST_LIKE_FIXED IS DELTA 0.1 RANGE -1.0 .. 1.0;
          TYPE FIXED IS DELTA 0.1   RANGE -1.0 .. 1.0;

          FIKST_SMALL : CONSTANT := JUST_LIKE_FIXED'SMALL;
          TYPE CHECK IS DELTA 0.1 RANGE -1.0 .. 1.0;

          FOR CHECK'SMALL USE FIKST_SMALL;
          FOR FIXED'SMALL       USE + FIKST_SMALL;

     BEGIN
          IF ERR THEN
               FAILED ("RESOLUTION INCORRECT FOR EXPRESSION IN " &
                       "LENGTH CLAUSE USING 'SMALL");
          END IF;
     END;

     RESULT;
END C87B62C;
