-- C87B07E.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- FOR THE ATTRIBUTE OF THE FORM T'IMAGE (X), THE OPERAND X MUST
-- BE OF TYPE T. THE RESULT IS OF THE PREDEFINED TYPE STRING.
  
-- TRH  15 SEPT 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B07E IS
 
     TYPE NEW_INT IS NEW INTEGER;
     TYPE NUMBER  IS NEW INTEGER;
     TYPE NEW_STR IS NEW STRING;
  
     FUNCTION "+" (X : NEW_INT) RETURN NEW_INT
          RENAMES "-";
     FUNCTION "-" (X : NUMBER)  RETURN NUMBER
          RENAMES "+";
 
     PROCEDURE P (X : NEW_STR) IS
     BEGIN
          FAILED ("THE IMAGE ATTRIBUTE MUST RETURN A VALUE OF THE" &
                  " PREDEFINED TYPE STRING");
     END P;
 
     PROCEDURE P (X : STRING) IS
     BEGIN
          NULL;
     END P;
    
BEGIN
     TEST ("C87B07E","OVERLOADED OPERANDS TO THE IMAGE ATTRIBUTE");
    
     IF INTEGER'IMAGE (+12) & INTEGER'IMAGE (-12) &
        NEW_INT'IMAGE (+12) & NEW_INT'IMAGE (-12) &
        NUMBER'IMAGE  (+12) & NUMBER'IMAGE  (-12)  /=
        " 12-12-12-12 12 12" THEN
        FAILED ("RESOLUTION INCORRECT FOR THE 'IMAGE' ATTRIBUTE");
     END IF;
   
     P (INTEGER'IMAGE (+1) & NEW_INT'IMAGE (+1) & NUMBER'IMAGE (-1));
     
     RESULT;
END C87B07E;
