-- C87B37D.ADA

-- CHECK THAT AN IMPLICIT CONVERSION FROM UNIVERSAL  INTEGER
-- IS NOT APPLIED IF THERE IS A LEGAL INTERPRETATION WITHOUT
-- THE IMPLICIT CONVERSION. 

-- SELECTION (NOT INVOLVING .ALL)

-- RFB 04/09/84
-- EG  05/31/84

WITH REPORT; USE REPORT;

PROCEDURE C87B37D IS

     FUNCTION "<" (L, R : INTEGER) RETURN INTEGER IS
     BEGIN
          RETURN 4;
     END "<";

     PROCEDURE CHECK (B : BOOLEAN; S : STRING) IS
     BEGIN
          IF NOT B THEN 
               FAILED(S); 
          END IF;
     END;

BEGIN

     TEST ("C87B37D","CHECK THAT IMPLICIT CONVERSIONS ARE ONLY USED " &
                     "WHEN NECESSARY FOR UNIVERSAL INTEGER");

     DECLARE        -- CASES INVOLVING SELECTION (OTHER THAN .ALL)

          TYPE REC1 IS RECORD
               IA : INTEGER;
               IX : INTEGER;
          END RECORD;

          TYPE REC2 IS RECORD
               IA : INTEGER;
               IB : INTEGER;
          END RECORD;

          WHICH_FUNC : INTEGER;

          FUNCTION F (X : BOOLEAN) RETURN REC1 IS
          BEGIN
               RETURN (IA | IX => 1);
          END;

          FUNCTION F (X : INTEGER) RETURN REC1 IS
          BEGIN
               RETURN (IA | IX => 2);
          END;

          FUNCTION F (X : INTEGER) RETURN REC2 IS
          BEGIN
               RETURN (IA | IB => 3);
          END;

     BEGIN

          WHICH_FUNC := F(5 < 5).IA;         -- NO IMPLICIT CONVERSION
          CHECK(WHICH_FUNC = 1, "CALLED WRONG F : SELECTION #1");

          WHICH_FUNC := F(5 < 5).IB;         -- IMPLICIT CONVERSION
          CHECK(WHICH_FUNC = 3, "CALLED WRONG F : SELECTION #2");

     END;

     RESULT;

END C87B37D;
