-- C87B18A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE TYPES OF THE EXPRESSIONS IN A DISCRIMINANT CONSTRAINT IN
-- A SUBTYPE INDICATION MUST MATCH THE DISCRIMINANT'S EXPLICIT
-- TYPEMARK.
  
-- TRH  1 JULY 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B18A IS
     
     ERR : BOOLEAN := FALSE;
 
     FUNCTION F1 RETURN INTEGER IS
     BEGIN 
          RETURN 1;
     END F1;

     FUNCTION F1 RETURN FLOAT IS
     BEGIN 
          ERR := TRUE;
          RETURN 0.0;
     END F1;
 
     FUNCTION F2 RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END F2;

     FUNCTION F2 RETURN STRING IS
     BEGIN 
          ERR := TRUE;
          RETURN "STRING";
     END F2;
  
BEGIN
     TEST ("C87B18A","OVERLOADED EXPRESSIONS IN DISCRIMINANT " &
           "CONSTRAINTS");
   
     DECLARE
          TYPE REC (X : INTEGER := 0; Y : BOOLEAN := TRUE) IS
               RECORD
                    NULL;
               END RECORD;
 
          R1 : REC (F1, F2);
          R2 : REC (Y => F2, X => F1);

     BEGIN
          IF ERR THEN 
               FAILED ("RESOLUTION INCORRECT - DISCRIMINANT " &
                       "CONSTRAINT MUST MATCH DISCRIMINANT TYPE");
          END IF;
     END;
    
     RESULT;
END C87B18A;
