-- C87B04C.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A RANGE CONSTRAINT OF A SUBTYPE INDICATION, THE EXPRESSIONS
-- FOR THE LOWER AND UPPER BOUNDS MUST BE COMPATIBLE WITH THE SUBTYPE'S
-- EXPLICIT TYPEMARK.
  
-- TRH  29 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B04C IS
  
     TYPE DAY IS (MON, TUE, WED, THU, FRI, SAT, SUN);
     TYPE ORB IS (SUN, MOON, MARS, EARTH);
  
     TYPE GRADE IS ('A', 'B', 'C', 'D', 'F');
     TYPE VOWEL IS ('C', 'E', 'A', 'O', 'I', 'U', 'Y');
  
BEGIN
     TEST ("C87B04C","OVERLOADED EXPRESSIONS IN RANGE CONSTRAINTS" &
          " OF ENUMERATION SUBTYPE INDICATIONS");
  
     DECLARE
          SUBTYPE PASSING IS GRADE RANGE 'A' .. 'C';
          SUBTYPE DISTANT IS ORB   RANGE SUN .. MARS;
  
     BEGIN
          IF DISTANT'POS (DISTANT'FIRST) /= 0 OR
             PASSING'POS (PASSING'FIRST) /= 0 THEN 
             FAILED ("RESOLUTION INCORRECT FOR OVERLOADED " &
                     " ENUMERATION LITERALS");
          END IF;
     END;
    
     RESULT;
END C87B04C;
