-- C87B10A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A RANGE CONSTRAINT OF A FIXED POINT OR FLOATING POINT TYPE
-- DEFINITION, BOTH BOUNDS MUST BE OF SOME REAL TYPE, ALTHOUGH
-- THE TWO BOUNDS DO NOT HAVE TO BE OF THE SAME TYPE.
  
-- TRH 7/28/82
-- DSJ 6/10/83
-- JBG 9/19/84
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B10A IS

     SUBTYPE DUR IS DURATION;

     FUNCTION "+" (X : FLOAT) RETURN INTEGER IS
     BEGIN
          FAILED ("RANGE CONSTRAINT FOR REAL TYPE DEFINITIONS " &
                  "MUST HAVE REAL BOUNDS");
          RETURN -10;
     END "+";

     FUNCTION "+" (X, Y : FLOAT) RETURN INTEGER IS
     BEGIN 
          FAILED ("RANGE CONSTRAINT FOR REAL TYPE DEFINITIONS " &
                  "MUST HAVE REAL BOUNDS");
          RETURN -10;
     END "+";
  
BEGIN
     TEST ("C87B10A","RANGE BOUNDS IN REAL TYPE DEFINITIONS MUST BE" &
           " OF SOME (NOT NECESSARILY THE SAME) REAL TYPE");
   
     DECLARE
          TYPE R1 IS DIGITS  2 RANGE 0.0 .. 1.0 + FLOAT'(1.0);
          TYPE R2 IS DELTA 0.1 RANGE FLOAT'(1.0) + 1.0 .. DUR'(2.0);
          TYPE R3 IS DIGITS  2 RANGE +1.0 .. "+" (FLOAT'(2.0), 2.0);
          TYPE R4 IS DELTA 0.1 RANGE 0.0 + FLOAT'(0.0) .. +1.0;
 
  
     BEGIN
          IF 2.0 NOT IN R1 OR -1.0 IN R2 OR
               -1.0 IN R3 OR -0.9 IN R4 THEN
               FAILED ("RANGE BOUNDS IN REAL TYPE DEFINITIONS DO NOT "
                    & "HAVE TO BE OF THE SAME REAL TYPE");
          END IF;
     END;
    
     RESULT;
END C87B10A;
