-- C87B03A.ADA
     
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE EXPRESSION IN A NUMBER DECLARATION MUST BE EITHER OF THE TYPE
-- UNIVERSAL_INTEGER OR UNIVERSAL_REAL.
   
-- TRH  16 JUNE 82
     
WITH REPORT; USE REPORT;
    
PROCEDURE C87B03A IS
    
BEGIN
     TEST ("C87B03A","OVERLOADED EXPRESSIONS IN NUMBER DECLARATIONS");
  
     DECLARE
          FUNCTION "+" (X, Y : INTEGER) RETURN INTEGER
               RENAMES STANDARD."-";
           
          FUNCTION "+" (X, Y : FLOAT)   RETURN FLOAT
               RENAMES STANDARD."-";
  
          I1 : CONSTANT         := 1 + 1;
          I2 : CONSTANT INTEGER := 1 + 1;
   
          R1 : CONSTANT       := 1.0 + 1.0;
          R2 : CONSTANT FLOAT := 1.0 + 1.0;
  
     BEGIN
          IF I1 /= 2   OR I2 /= 0   OR 
             R1 /= 2.0 OR R2 /= 0.0 THEN
             FAILED ("OVERLOADED EXPRESSIONS IN NUMBER DECLARATIONS" &
                     " RESOLVED INCORRECTLY");
          END IF;
     END;
   
     RESULT;
END C87B03A;
