-- C87B08A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- FOR EACH REAL TYPE, THERE EXISTS AN IMPLICIT CONVERSION THAT
-- CONVERTS A UNIVERSAL REAL VALUE INTO THE CORRESPONDING VALUE 
-- OF THE REAL TYPE. THIS TEST USES LITERALS AS UNIVERSAL REAL
-- VALUES.
  
-- TRH  16 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B08A IS
 
     TYPE FIXED IS DELTA 0.1 RANGE -2.0 .. 2.0;
     TYPE FLT   IS DIGITS  2 RANGE -2.0 .. 2.0;
     TYPE FLAG  IS (PASS, FAIL);
 
     GENERIC
          TYPE T IS PRIVATE;
          STAT : IN FLAG;
     PROCEDURE P1 (X : T);
  
     PROCEDURE P1 (X : T) IS
     BEGIN
          IF STAT = FAIL THEN
               FAILED ("INCORRECT IMPLICIT CONVERSION FROM UNIVERSAL" &
                       " REAL VALUES TO REAL TYPE VALUES");
          END IF;
     END P1;
 
     PROCEDURE P IS NEW P1 (INTEGER,   FAIL);
     PROCEDURE P IS NEW P1 (FLT,       PASS);
     PROCEDURE P IS NEW P1 (STRING,    FAIL);
     PROCEDURE Q IS NEW P1 (FIXED,     PASS);
     PROCEDURE Q IS NEW P1 (BOOLEAN,   FAIL);
     PROCEDURE Q IS NEW P1 (CHARACTER, FAIL);
 
BEGIN
     TEST ("C87B08A","IMPLICIT CONVERSION OF UNIVERSAL REAL " &
           "VALUES TO REAL VALUES EXISTS FOR ANY REAL TYPE");
    
     P (0.0);
     P (1.0 + 1.0);
     Q (1.0);
     Q (1.0 - 1.0);
 
     RESULT;
END C87B08A;
