-- C87B34C.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
    
-- FOR A MEMBERSHIP RELATION WITH A TYPEMARK, THE TYPE OF THE
-- SIMPLE EXPRESSION MUST BE THE BASE TYPE OF THE TYPEMARK.
  
-- TRH  15 SEPT 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B34C IS
 
     TYPE VOWEL IS (A, E, I, O, U, VOCALIC_Y);
     TYPE ALPHA IS (A, 'A');
     TYPE GRADE IS (A, B, C, D, F);
     SUBTYPE BAD_GRADE IS GRADE RANGE D .. F;
     SUBTYPE PASSING   IS GRADE RANGE A .. C;
 
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          FAILED ("RESOLUTION INCORRECT - EXPRESSION IN MEMBER" &
                  "SHIP TEST WITH TYPEMARK MUST MATCH TYPEMARK");
          RETURN ARG;
     END F1;
 
     FUNCTION F IS NEW F1 (CHARACTER, 'A');
     FUNCTION F IS NEW F1 (DURATION,  1.0);
     FUNCTION F IS NEW F1 (INTEGER,   -10);
     FUNCTION F IS NEW F1 (BOOLEAN,   TRUE);
     FUNCTION F IS NEW F1 (STRING,    "A");
     FUNCTION F IS NEW F1 (FLOAT,     1.0);
     FUNCTION F IS NEW F1 (VOWEL,     A);
     FUNCTION F IS NEW F1 (ALPHA,     A);
    
BEGIN
     TEST ("C87B34C","OVERLOADED EXPRESSION IN MEMBERSHIP TEST " &
           "WITH A TYPEMARK");
 
     IF (F NOT IN GRADE) OR (F NOT IN BAD_GRADE)
          OR (F IN PASSING) THEN 
          FAILED ("RESOLUTION INCORRECT FOR MEMBERSHIP TEST " &
                  "WITH TYPEMARK");
     END IF;
    
     RESULT;
 
END C87B34C;
