-- C87B09C.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A FLOATING POINT TYPE DEFINITION, THE DIGITS EXPRESSION MUST
-- BE OF SOME INTEGRAL TYPE. SIMILARLY, THE DELTA EXPRESSION IN A
-- FIXED POINT TYPE DEFINITION MUST BE OF SOME REAL TYPE.
  
-- TRH  30 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B09C IS
     
     FUNCTION "+" (X : INTEGER) RETURN FLOAT IS
     BEGIN 
           FAILED ("DIGITS EXPRESSION MUST BE OF AN INTEGRAL TYPE");
           RETURN 2.0;
     END "+";

     FUNCTION "+" (X : FLOAT) RETURN INTEGER IS
     BEGIN 
           FAILED ("DELTA EXPRESSION MUST BE OF A REAL TYPE");
           RETURN 2;
     END "+";
  
BEGIN
     TEST ("C87B09C","OVERLOADED DIGITS/DELTA EXPRESSIONS IN " &
           "REAL TYPE DEFINITIONS");
   
     DECLARE
          TYPE EXACT IS DIGITS "+" (4);
          TYPE CENTI IS DELTA  "+" (0.01) RANGE -2.0 .. 2.0;
          TYPE CLOSE IS DIGITS "+" (2)    RANGE -1.0 .. 1.0;
          TYPE DECI  IS DELTA  "+" (0.1)  RANGE -1.0 .. 1.0;
  
     BEGIN
          NULL;
     END;
    
     RESULT;
END C87B09C;
