-- C87B07B.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- FOR THE ATTRIBUTE OF THE FORM T'VAL (X), THE OPERAND X MAY
-- BE OF ANY INTEGER TYPE. THE RESULT IS OF TYPE T.
  
-- TRH  15 SEPT 82
-- DSJ  06 JUNE 83
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B07B IS
 
     TYPE NEW_INT IS NEW INTEGER;
     TYPE WHOLE   IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
     TYPE FLAG IS (PASS, FAIL);
     
     FUNCTION "+" (X, Y : NEW_INT) RETURN NEW_INT
          RENAMES "-";
     FUNCTION "+" (X, Y : WHOLE)   RETURN WHOLE
          RENAMES "*";
 
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : IN FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
               FAILED ("THE 'VAL' ATTRIBUTE TAKES AN OPERAND " &
                       "OF AN INTEGER TYPE");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION F IS NEW F1 (CHARACTER, '1', FAIL);
     FUNCTION F IS NEW F1 (DURATION,  1.0, FAIL);
     FUNCTION F IS NEW F1 (FLOAT,     1.0, FAIL);
     FUNCTION F IS NEW F1 (STRING,    "1", FAIL);
     FUNCTION F IS NEW F1 (NEW_INT,   1,   PASS);
    
BEGIN
     TEST ("C87B07B","OVERLOADED OPERANDS TO THE 'VAL' ATTRIBUTE");
    
     IF (INTEGER'VAL (F) /= 1)          THEN
          FAILED ("RESOLUTION INCORRECT - THE 'VAL' ATTRIBUTE " &
                  "MUST RETURN A VALUE OF TYPE T - 1");
     END IF;

     IF (INTEGER'VAL (3 + 3) + 1 /= 7)  THEN
          FAILED ("RESOLUTION INCORRECT - THE 'VAL' ATTRIBUTE " &
                  "MUST RETURN A VALUE OF TYPE T - 2");
     END IF;

     IF (NEW_INT'VAL (F) /= 1)          THEN
          FAILED ("RESOLUTION INCORRECT - THE 'VAL' ATTRIBUTE " &
                  "MUST RETURN A VALUE OF TYPE T - 3");
     END IF;

     IF (NEW_INT'VAL  (3 + 3) + 1 /= 5) THEN
          FAILED ("RESOLUTION INCORRECT - THE 'VAL' ATTRIBUTE " &
                  "MUST RETURN A VALUE OF TYPE T - 4");
     END IF;

     IF (WHOLE'VAL    (F) /= 1)         THEN
          FAILED ("RESOLUTION INCORRECT - THE 'VAL' ATTRIBUTE " &
                  "MUST RETURN A VALUE OF TYPE T - 5");
     END IF;

     IF (WHOLE'VAL    (3 + 3) + 1 /= 6) THEN
          FAILED ("RESOLUTION INCORRECT - THE 'VAL' ATTRIBUTE " &
                  "MUST RETURN A VALUE OF TYPE T - 6");
     END IF;
 
     RESULT;
END C87B07B;
