-- C87B14C.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN SUBTYPE INDICATIONS WITH INDEX CONSTRAINTS, THE LOWER AND UPPER
-- BOUNDS MUST BE OF THE INDEX BASE TYPE.
--
-- TEST (C): INDEX CONSTRAINTS WITH OVERLOADED INFIX OPERATORS.
  
-- TRH  30 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B14C IS
     
     TYPE DAY  IS (MON, TUE, WED, THU, FRI, SAT, SUN);
     TYPE LIST IS ARRAY (DAY RANGE <>) OF BOOLEAN;
     TYPE GRID IS ARRAY (DAY RANGE <>, DAY RANGE <>) OF BOOLEAN;
     SUBTYPE WEEKEND IS DAY RANGE SAT .. SUN;
     SUBTYPE WEEKDAY IS DAY RANGE MON .. FRI;
   
     FUNCTION "*" (X, Y : INTEGER) RETURN WEEKDAY IS
     BEGIN 
          RETURN MON;
     END "*";

     FUNCTION "*" (X, Y : INTEGER) RETURN BOOLEAN IS
     BEGIN 
          FAILED ("RESOLUTION INCORRECT - INDEX CONSTRAINTS " &
                  " IN SUBTYPE INDICATIONS");
          RETURN TRUE;
     END "*";
  
     FUNCTION "+" (X, Y : INTEGER) RETURN WEEKEND IS
     BEGIN 
          RETURN SAT;
     END "+";

     FUNCTION "+" (X, Y : INTEGER) RETURN FLOAT IS
     BEGIN 
          FAILED ("RESOLUTION INCORRECT - INDEX CONSTRAINTS " &
                  " IN SUBTYPE INDICATIONS");
          RETURN 2.0;
     END "+";
  
BEGIN
     TEST ("C87B14C","OVERLOADED EXPRESSIONS IN INDEX CONSTRAINTS " &  
           "OF SUBTYPE INDICATIONS");
   
     DECLARE
          SUBTYPE LIST1 IS LIST (WED .. (0 + 0));
          SUBTYPE LIST2 IS LIST ( 0 * 0 .. TUE);
          SUBTYPE LIST3 IS LIST ((0 + 0) .. (0 + 0));
          SUBTYPE LIST4 IS LIST ((0 * 0) .. (0 + 0));
   
          SUBTYPE GRID1 IS GRID (MON .. (0 * 0), (0 * 0) .. TUE);
          SUBTYPE GRID2 IS GRID ((0 * 0) .. WED, FRI .. (0 + 0));
          SUBTYPE GRID3 IS GRID
              ((0 * 0) .. (0 * 0), (0 + 0) .. (0 + 0));
          SUBTYPE GRID4 IS GRID ((0 * 0) .. (0 + 0), TUE .. THU);
  
     BEGIN
          NULL;
     END;
    
     RESULT;
END C87B14C;
