-- C87B34A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE MEMBERSHIP TESTS "IN" AND "NOT IN" RESULT IN THE PREDEFINED
-- TYPE BOOLEAN. 
  
-- TRH  4 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B34A IS
     
     TYPE BIT   IS NEW BOOLEAN;
     TYPE FLAG  IS NEW BOOLEAN;
 
     ERR : BOOLEAN := FALSE;
 
     PROCEDURE P1 (X : BIT) IS
     BEGIN
          ERR := TRUE;
     END P1;
 
     PROCEDURE P1 (X : FLAG) IS
     BEGIN
          ERR := TRUE;
     END P1;
 
     PROCEDURE P1 (X : BOOLEAN) IS
     BEGIN
          NULL;
     END P1;
  
BEGIN
     TEST ("C87B34A","MEMBERSHIP TESTS 'IN' AND 'NOT IN' RETURN " &
           "TYPE PREDEFINED BOOLEAN");
   
     P1 (3 IN 1 .. 5);
     P1 (3 NOT IN 1 .. 5);
 
     IF ERR THEN
        FAILED ("MEMBERSHIP TESTS MUST RETURN PREDEFINED BOOLEAN TYPE");
     END IF;
    
     RESULT;
END C87B34A;
