-- C87B09A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN A FLOATING POINT TYPE DEFINITION, THE DIGITS EXPRESSION MUST 
-- BE OF SOME INTEGER TYPE.
  
-- TRH  30 JUNE 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B09A IS
     
     FUNCTION "+" (X : INTEGER) RETURN FLOAT IS
     BEGIN 
           FAILED ("DIGITS EXPRESSION MUST BE OF AN INTEGER TYPE");
           RETURN 2.0;
     END "+";

BEGIN
     TEST ("C87B09A","OVERLOADED DIGITS EXPRESSIONS IN " &
           "FLOATING POINT TYPE DEFINITIONS");
   
     DECLARE
          TYPE EXACT IS DIGITS "+" (3);
          TYPE CLOSE IS DIGITS "+" (1) RANGE -1.0 .. 1.0;
  
     BEGIN
          NULL;
     END;
    
     RESULT;
END C87B09A;
