-- C87B50A.ADA

-- CHECK THAT A FUNCTION RENAMING DECLARATION CAN RESOLVE AND RENAME AN
-- OVERLOADED ENUMERATION LITERAL.

-- GOM 11/29/84
-- JWC 7/12/85
-- PWB 03/06/86  CORRECTED ERROR: ADDED "USE" CLAUSE TO MAKE
--               "/=" VISIBLE.

WITH REPORT; USE REPORT;
PROCEDURE C87B50A IS

BEGIN
     TEST ("C87B50A", "CHECK THAT A FUNCTION RENAMING DECLARATION " &
                      "CAN RESOLVE AND RENAME AN OVERLOADED " &
                      "ENUMERATION LITERAL");

     DECLARE

          PACKAGE A IS
               TYPE COLORS IS (RED,GREEN);
               TYPE LIGHT  IS (BLUE,RED);
          END A;

          PACKAGE B IS
               FUNCTION RED RETURN A.COLORS RENAMES A.RED;
               FUNCTION GREEN RETURN A.COLORS RENAMES A.GREEN;
          END B;

          USE A;      -- TO MAKE /= VISIBLE.

     BEGIN

          IF (A.RED /= B.RED) OR (A.GREEN /= B.GREEN) THEN
               FAILED ("RENAMED VALUES NOT EQUAL");
          END IF;

     END;

     RESULT;
END C87B50A;
