-- C87B18B.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE EXPRESSION IN A NAMED OR POSITIONAL DISCRIMINANT ASSOCIATION
-- MUST MATCH THE TYPE OF THE CORRESPONDING DISCRIMINANT.
  
-- TRH  9 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B18B IS
 
     TYPE REC (W, X : CHARACTER; Y, Z : BOOLEAN) IS
          RECORD
               NULL;
          END RECORD;
 
     TYPE FLAG IS (PASS, FAIL);
     
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : IN FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
               FAILED ("DISCRIMINANT ASSOCIATION EXPRESSION MUST " &
                       "MATCH THE TYPE OF THE CORRESPONDING " &
                       "DISCRIMINANT");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION F IS NEW F1 (FLOAT,     2.0, FAIL);
     FUNCTION F IS NEW F1 (STRING,    "B", FAIL);
     FUNCTION F IS NEW F1 (INTEGER,     5, FAIL);
     FUNCTION F IS NEW F1 (BOOLEAN,  TRUE, FAIL);
     FUNCTION F IS NEW F1 (CHARACTER, 'E', PASS);
 
     FUNCTION G IS NEW F1 (FLOAT,     2.0, FAIL);
     FUNCTION G IS NEW F1 (STRING,    "B", FAIL);
     FUNCTION G IS NEW F1 (INTEGER,     5, FAIL);
     FUNCTION G IS NEW F1 (BOOLEAN,  TRUE, PASS);
     FUNCTION G IS NEW F1 (CHARACTER, 'E', FAIL);
    
BEGIN
     TEST ("C87B18B","OVERLOADED DISCRIMINANT ASSOCIATIONS");
    
     DECLARE
          SUBTYPE R1 IS REC (F, F, G, G);
          SUBTYPE R2 IS REC (X => F, Y => G, Z => G, W => F);
          SUBTYPE R3 IS REC (F, F, Z => G, Y => G);
   
     BEGIN
          NULL;
     END;
 
     RESULT;
END C87B18B;
