-- C87B47A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- ACTUAL PARAMETERS MUST MATCH THE EXPLICIT TYPEMARK OF THE
-- PARAMETER.
  
-- TRH  8 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B47A IS
 
     TYPE FLAG IS (PASS, FAIL);
     
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : IN FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
             FAILED ("ACTUAL PARAMETER MUST MATCH PARAMETER TYPE");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION F IS NEW F1 (FLOAT,     2.0, PASS);
     FUNCTION F IS NEW F1 (STRING,    "B", FAIL);
     FUNCTION F IS NEW F1 (INTEGER,     5, FAIL);
     FUNCTION F IS NEW F1 (BOOLEAN,  TRUE, FAIL);
     FUNCTION F IS NEW F1 (DURATION,  1.0, FAIL);
     FUNCTION F IS NEW F1 (CHARACTER, 'E', FAIL);
    
BEGIN
     TEST ("C87B47A","OVERLOADED ACTUAL PARAMETERS");
    
     DECLARE
          PROCEDURE P (X : FLOAT) IS
          BEGIN
               NULL;
          END P;
   
     BEGIN
          P (F);
          P (X => F);
     END;
 
     RESULT;
END C87B47A;
