-- C87B07A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- FOR THE ATTRIBUTE OF THE FORM T'POS (X), THE OPERAND X MUST 
-- BE A VALUE OF TYPE T. THE RESULT IS OF TYPE UNIVERSAL_INTEGER.
  
-- TRH  13 SEPT 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B07A IS
 
     TYPE NATURAL IS NEW INTEGER RANGE 1 .. INTEGER'LAST;
     TYPE WHOLE   IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
     TYPE COLOR   IS (BROWN, RED, WHITE);
     TYPE SCHOOL  IS (HARVARD, BROWN, YALE);
     TYPE SUGAR   IS (DEXTROSE, CANE, BROWN);
 
     FUNCTION "+" (X, Y : NATURAL) RETURN NATURAL
          RENAMES "*";
     FUNCTION "+" (X, Y : WHOLE) RETURN WHOLE
          RENAMES "-";
    
BEGIN
     TEST ("C87B07A","OVERLOADED OPERANDS TO THE 'POS' ATTRIBUTE");
  
     IF NATURAL'POS (1 + 1) /= 1 OR COLOR'POS  (BROWN) /= 0 OR
        WHOLE'POS   (1 + 1) /= 0 OR SCHOOL'POS (BROWN) /= 1 OR
        INTEGER'POS (1 + 1) /= 2 OR SUGAR'POS  (BROWN) /= 2 THEN
        FAILED ("RESOLUTION INCORRECT FOR OPERAND TO 'POS' ATTRIBUTE");
     END IF;
 
     IF NATURAL'POS (3 + 3) + 1 /= 10 OR    -- SECOND "+" IS UNIVERSAL.
        WHOLE'POS   (3 + 3) + 1 /=  1 OR    -- SECOND "+" IS UNIVERSAL.
        INTEGER'POS (3 + 3) + 1 /=  7 THEN  -- SECOND "+" IS UNIVERSAL.
        FAILED ("RESOLUTION INCORRECT - 'POS' ATTRIBUTE RETURNS " &
                "A UNIVERSAL_INTEGER VALUE");
     END IF;

     RESULT;
END C87B07A;
