-- C87B38A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
    
-- IN A QUALIFIED EXPRESSION, THE OPERAND MUST HAVE THE SAME TYPE
-- AS THE BASE TYPE OF THE TYPEMARK.
  
-- TRH  13 SEPT 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B38A IS
 
     SUBTYPE BOOL IS BOOLEAN;
     TYPE YES  IS NEW BOOLEAN RANGE TRUE  .. TRUE;
     TYPE NO   IS NEW BOOLEAN RANGE FALSE .. FALSE;
     TYPE BIT  IS NEW BOOLEAN;
     TYPE LIT  IS (FALSE, TRUE);   
     TYPE FLAG IS (PASS,  FAIL);
 
     GENERIC
          TYPE T IS PRIVATE;
          ARG  : IN T;
          STAT : FLAG;
     FUNCTION F1 RETURN T;
 
     FUNCTION F1 RETURN T IS
     BEGIN 
          IF STAT = FAIL THEN 
               FAILED ("RESOLUTION INCORRECT FOR OVERLOADED " &
                       " OPERANDS OF QUALIFIED EXPRESSIONS");
          END IF;
          RETURN ARG;
     END F1;
  
     FUNCTION F IS NEW F1 (LIT,     FALSE, FAIL);
     FUNCTION F IS NEW F1 (BIT,     TRUE,  FAIL);
     FUNCTION F IS NEW F1 (BOOLEAN, TRUE,  PASS);
     FUNCTION F IS NEW F1 (YES,     TRUE,  FAIL);
     FUNCTION F IS NEW F1 (NO,      FALSE, FAIL);
    
BEGIN
     TEST ("C87B38A","OVERLOADED OPERANDS IN QUALIFIED EXPRESSIONS ");
 
     DECLARE 
          B : BOOL;
 
     BEGIN
          B := BOOL' (F);
          B := BOOL' ((NOT F) OR ELSE (F AND THEN F));
     END;
 
     RESULT;
END C87B38A;
