-- C87B35C.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE EXPONENT OPERAND OF A FLOATING POINT EXPONENTIATION MUST BE
-- OF THE TYPE PREDEFINED INTEGER.
  
-- TRH  4 AUG 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B35C IS
 
     TYPE FIXED IS DELTA 0.01 RANGE 0.0 .. 4.0;
     ERR : BOOLEAN := FALSE;
   
     FUNCTION F1 (X : INTEGER) RETURN INTEGER IS
     BEGIN 
          RETURN X;
     END F1;
       
     FUNCTION F1 (X : INTEGER) RETURN FLOAT IS
     BEGIN 
          ERR := TRUE;
          RETURN 1.0;
     END F1;
    
     FUNCTION F1 (X : INTEGER) RETURN FIXED IS
     BEGIN 
          ERR := TRUE;
          RETURN 1.0;
     END F1;
 
BEGIN
     TEST ("C87B35C","EXPONENT OPERAND FOR FLOATING POINT " &
           "EXPONENTIATION MUST BE OF TYPE PREDEFINED INTEGER");
  
     DECLARE
          FUNCTION "+" (X, Y : INTEGER) RETURN INTEGER
               RENAMES STANDARD."*";
    
     BEGIN
          IF ( FLOAT'(2.0) ** F1(3)   /= 8.0 OR
               FLOAT'(2.0) ** (3 + 1) /= 8.0 ) THEN
               FAILED ("EXPONENT OF FLOATING POINT EXPONENTIATION "
                    & "MUST BE PREDEFINED INTEGER (A)");
          END IF;
          IF ( 2.0 ** F1(3)   /= FLOAT'(8.0) OR
               2.0 ** (3 + 1) /= FLOAT'(8.0) ) THEN
               FAILED ("EXPONENT OF FLOATING POINT EXPONENTIATION"
                    & "MUST BE PREDEFINED INTEGER (B)");
          END IF;
          IF ERR THEN
               FAILED ("EXPONENT OF FLOATING POINT EXPONENTIATION"
                    & "MUST BE PREDEFINED INTEGER (C)");
          END IF;
     END;
 
     RESULT;
END C87B35C;
