-- C87B28A.ADA
 
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- THE TYPE OF THE LITERAL "NULL" MUST BE DETERMINED FROM THE FACT 
-- THAT "NULL" IS A VALUE OF AN ACCESS TYPE.
  
-- TRH  13 AUG 82
-- JRK 2/2/84

WITH REPORT; USE REPORT;
   
PROCEDURE C87B28A IS
 
     ERR : BOOLEAN := FALSE;
 
     TYPE A2 IS ACCESS BOOLEAN;
     TYPE A3 IS ACCESS INTEGER;
     TYPE A1 IS ACCESS A2;
 
     FUNCTION F RETURN A1 IS
     BEGIN 
          RETURN NEW A2;
     END F;
 
     FUNCTION F RETURN A2 IS
     BEGIN
          ERR := TRUE;
          RETURN NEW BOOLEAN;
     END F;
 
     FUNCTION F RETURN A3 IS
     BEGIN
          ERR := TRUE;
          RETURN (NEW INTEGER);
     END F;
 
BEGIN
     TEST ("C87B28A", "OVERLOADING OF THE ACCESS TYPE LITERAL 'NULL'");
    
     F.ALL := NULL;
 
     IF ERR THEN
          FAILED ("RESOLUTION INCORRECT FOR THE ACCESS TYPE LITERAL " &
                  "'NULL'");
     END IF;
 
     RESULT;
END C87B28A;
