-- C87B05A.ADA
    
-- CHECK THAT OVERLOADING RESOLUTION USES THE RULE THAT:
--
-- IN AN INTEGER TYPE DEFINITION WITH A RANGE CONSTRAINT, THE BOUNDS
-- OF THE RANGE MUST BE OF SOME INTEGER TYPE.
  
-- TRH  1 JULY 82
  
WITH REPORT; USE REPORT;
   
PROCEDURE C87B05A IS
  
     ERR : BOOLEAN := FALSE;
     TYPE WHOLE IS NEW INTEGER RANGE 0 .. INTEGER'LAST;
     TYPE AGE   IS NEW INTEGER RANGE 0 .. 120;
     
     FUNCTION "+" (X : WHOLE) RETURN FLOAT IS
     BEGIN 
          ERR := TRUE;
          RETURN 2.0;
     END "+";

     FUNCTION "-" (X : AGE) RETURN BOOLEAN IS
     BEGIN 
          ERR := TRUE;
          RETURN FALSE;
     END "-";
  
BEGIN
     TEST ("C87B05A","OVERLOADED EXPRESSIONS IN RANGE BOUNDS " &
           " OF INTEGER TYPE DEFINITIONS");
   
     DECLARE
          TYPE ADULT IS RANGE 18 .. "+" (WHOLE'(120));
          TYPE MINOR IS RANGE "-" (AGE'(0))  .. "+" (WHOLE'(17));
          TYPE NEG10 IS RANGE "-" (AGE'(10)) .. "-" (AGE'(1));
  
     BEGIN
          IF ERR THEN 
               FAILED ("RESOLUTION INCORRECT - INTEGER TYPE " &
                       "DEFINITIONS MUST HAVE INTEGER TYPE "  &
                       "RANGE BOUNDS");
          END IF;
     END;
    
     RESULT;
END C87B05A;
