-- C91004C.ADA

-- CHECK THAT A TASK (TYPE) IDENTIFIER, WHEN USED WITHIN ITS OWN BODY
-- REFERS TO THE EXECUTING TASK.
--
-- TEST USING CONDITIONAL ENTRY CALL.

-- WEI  3/ 4/82
-- TLB 10/30/87  RENAMED FROM C910BDB.ADA.

WITH REPORT;
 USE REPORT;
PROCEDURE C91004C IS

     TASK TYPE TT1 IS
          ENTRY E1;
          ENTRY BYE;
     END TT1;

     OBJ_TT1 : ARRAY (NATURAL RANGE 1..2) OF TT1;

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     PROCEDURE PSPY_NUMB (DIGT: IN ARG) IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
     END PSPY_NUMB;

     TASK BODY TT1 IS
     BEGIN
          ACCEPT E1 DO
               PSPY_NUMB (1);
          END E1;

          SELECT
               TT1.E1;
          ELSE
               PSPY_NUMB (2);
          END SELECT;

          ACCEPT BYE;
     END TT1;

BEGIN

     TEST ("C91004C", "TASK IDENTIFIER IN OWN BODY");
     OBJ_TT1 (1).E1;
     OBJ_TT1 (1).BYE;

     IF SPYNUMB /=12 THEN
          FAILED ("WRONG TASK OBJECT REFERENCED");
          COMMENT ("ACTUAL ORDER WAS:" & INTEGER'IMAGE(SPYNUMB));
     END IF;

     ABORT OBJ_TT1 (2);

     RESULT;

END C91004C;
