-- C92005B.ADA

-- CHECK THAT FOR A TASK OBJECT CREATED BY AN ALLOCATOR THE
-- OBJECT VALUE IS SET DURING EXECUTION OF THE ALLOCATOR.

-- WEI  3/ 4/82
-- JBG 5/25/85

WITH REPORT;
 USE REPORT;
WITH SYSTEM;
PROCEDURE C92005B IS
     TYPE BIG_INT IS RANGE 0..SYSTEM.MAX_INT;
BEGIN
     TEST ("C92005B", "TASK VALUE SET BY EXECUTION OF ALLOCATOR");

BLOCK:
     DECLARE
          TASK TYPE TT1;

          TYPE ATT1 IS ACCESS TT1;

          TASK BODY TT1 IS
          BEGIN
               NULL;
          END TT1;

          PACKAGE PACK IS
          END PACK;

          PACKAGE BODY PACK IS
               POINTER_TT1 : ATT1 := NEW TT1;
               I : BIG_INT := POINTER_TT1.ALL'STORAGE_SIZE;
          BEGIN
               IF NOT EQUAL(INTEGER(I), INTEGER(I)) THEN
                    FAILED ("UNEXPECTED PROBLEM");
               END IF;
          END PACK;
     BEGIN
          NULL;
     EXCEPTION
          WHEN PROGRAM_ERROR | CONSTRAINT_ERROR =>
               FAILED ("TASK OBJECT VALUE NOT SET DURING " &
                       "EXECUTION OF ALLOCATOR");
     END BLOCK;

     RESULT;

END C92005B;
