-- C92005A.ADA

-- CHECK THAT FOR A NON-SINGLE TASK THE OBJECT VALUE IS SET DURING
-- ELABORATION OF THE CORRESPONDING OBJECT DECLARATION.

-- WEI  3/ 4/82
-- JBG 5/25/85
-- PWB  2/3/86    CORRECTED TEST ERROR; ADDED 'USE' CLAUSE TO MAKE "/="
--                FOR BIG_INT VISIBLE.

WITH REPORT, SYSTEM;
 USE REPORT;
PROCEDURE C92005A IS
BEGIN

     TEST ("C92005A", "TASK OBJECT VALUE DURING ELABORATION");

     DECLARE
          TASK TYPE TT1;

          OBJ_TT1 : TT1;

          PACKAGE PACK IS
               TYPE BIG_INT IS RANGE 0 .. SYSTEM.MAX_INT;
               I : BIG_INT;
          END PACK;

          PACKAGE BODY PACK IS
          BEGIN
               I := OBJ_TT1'STORAGE_SIZE;  -- O.K.
          EXCEPTION
               WHEN OTHERS =>
                    FAILED ("TASK OBJECT RAISED EXCEPTION");
          END PACK;

          USE PACK;

          TASK BODY TT1 IS
          BEGIN
               NULL;
          END TT1;

     BEGIN
          IF PACK.I /= OBJ_TT1'STORAGE_SIZE THEN
               COMMENT ("STORAGE SIZE CHANGED AFTER TASK ACTIVATED");
          END IF;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("EXCEPTION RAISED BY STORAGE_SIZE");
     END;

     RESULT;
END C92005A;
