-- C92006A.ADA

-- CHECK THAT TASK OBJECTS CAN BE INTERCHANGED BY ASSIGNMENT OF
-- CORRESPONDING ACCESS TYPE OBJECTS.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C920BIA-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C92006A IS

     TASK TYPE TT1 IS
          ENTRY E1;
          ENTRY E2;
     END TT1;

     TYPE ATT1 IS ACCESS TT1;
     POINTER_TT1_1, POINTER_TT1_2 : ATT1;

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     PROCEDURE PSPY_NUMB (DIGT: IN ARG) IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
     END PSPY_NUMB;

     PROCEDURE PROC (P1, P2 : IN OUT ATT1) IS
     -- SWAP TASK OBJECTS P1, P2.
          SCRATCH : ATT1;
     BEGIN
          SCRATCH := P1;
          P1 := P2;
          P2 := SCRATCH;

          P1.E2;  -- ENTRY2 SECOND OBJECT.
          P2.E1;  -- VICE VERSA.

     END PROC;

     TASK BODY TT1 IS
     BEGIN
          ACCEPT E1 DO
               PSPY_NUMB (1);
          END E1;
          ACCEPT E2 DO
               PSPY_NUMB (2);
          END E2;
     END TT1;

BEGIN

     TEST ("C92006A", "INTERCHANGING TASK OBJECTS");
     POINTER_TT1_1 := NEW TT1;
     POINTER_TT1_2 := NEW TT1;

     POINTER_TT1_2.ALL.E1;
     PROC (POINTER_TT1_1, POINTER_TT1_2);
     POINTER_TT1_2.E2;        -- E2 OF FIRST OBJECT
-- EACH ENTRY OF EACH TASK OBJECT SHOULD HAVE BEEN CALLED.

     IF SPYNUMB /= 1212 THEN
          FAILED ("FAILURE TO SWAP TASK OBJECTS " &
                  "IN PROCEDURE PROC");
          COMMENT ("ACTUAL ORDER WAS:" & INTEGER'IMAGE(SPYNUMB));
     END IF;

     RESULT;

END C92006A;
