-- C93004A.ADA

-- CHECK THAT A TASK BECOMES COMPLETED WHEN AN EXCEPTION OCCURS DURING
-- ITS ACTIVATION.

-- WEI  3/ 4/82

WITH REPORT;
 USE REPORT;
PROCEDURE C93004A IS
BEGIN

     TEST ("C93004A", "TASK COMPLETION CAUSED BY EXCEPTION");

BLOCK:
     DECLARE
          TYPE I0 IS RANGE 0..1;

          TASK T1 IS
               ENTRY BYE;
          END T1;

          TASK BODY T1 IS
               SUBTYPE I1 IS I0 RANGE 0 .. 2;     -- CONSTRAINT ERROR.
          BEGIN
               ACCEPT BYE;
          END T1;
     BEGIN
          FAILED ("NO EXCEPTION RAISED");
          IF NOT T1'TERMINATED THEN 
               FAILED ("TASK NOT TERMINATED");
               T1.BYE;
          END IF;
     EXCEPTION
          WHEN TASKING_ERROR =>
               NULL;
          WHEN CONSTRAINT_ERROR =>
               FAILED ("CONSTRAINT_ERROR RAISED");
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED");
     END BLOCK;

     RESULT;

END C93004A;
