-- C94002D.ADA

-- CHECK THAT A TASK DOES  N O T  DEPEND ON A UNIT IF IT IS DESIGNATED
-- BY A LOCAL ACCESS VARIABLE (OF THIS UNIT) WHOSE TYPE IS DECLARED
-- OUTSIDE THIS UNIT.

-- WEI  3/ 4/82
-- JBG 2/20/84
-- TBN 11/25/85     RENAMED FROM C940ACB-B.ADA.

WITH REPORT;
 USE REPORT;
PROCEDURE C94002D IS

     TASK TYPE TT1 IS
          ENTRY E1;
          ENTRY E2;
     END TT1;

     TYPE ATT1 IS ACCESS TT1;
     OUTER_TT1 : ATT1;

     TASK BODY TT1 IS
     BEGIN
          ACCEPT E1;
          ACCEPT E2;
     END TT1;

BEGIN
     TEST ("C94002D", "DEPENDENCY IS INDEPENDENT OF WHERE ACCESS " &
                      "VARIABLE IS DECLARED");

BLOCK1 :
     DECLARE
          POINTER_TT1 : ATT1 := NEW TT1;
     BEGIN
          OUTER_TT1 := POINTER_TT1;
          POINTER_TT1.ALL.E1;
     END BLOCK1;         -- MAY DEADLOCK HERE IF INCORRECT DEPENDENCY
                         -- RULE IS IMPLEMENTED.

     IF OUTER_TT1.ALL'TERMINATED THEN
          FAILED ("NON-DEPENDENT TASK IS TERMINATED " &
                  "IMMEDIATELY AFTER ENCLOSING UNIT HAS " &
                  "BEEN COMPLETED");
     END IF;

     OUTER_TT1.E2;       -- RELEASE TASK

     RESULT;

END C94002D;
