-- C94004B.ADA

-- CHECK THAT A MAIN PROGRAM TERMINATES WITHOUT WAITING FOR TASKS THAT
-- DEPEND ON A LIBRARY PACKAGE AND THAT SUCH TASKS ARE NOT TERMINATED BY
-- MAIN PROGRAM TERMINATION.

-- CASE B:  ACCESS TO TASK TYPE DECLARED IN LIBRARY PACKAGE; TASK
--          ACTIVATED IN MAIN PROGRAM.

-- JRK 10/8/81
-- SPS 11/21/82
-- JBG 12/6/84
-- JRK 11/21/85  RENAMED FROM C94004B-B.ADA; REVISED ACCORDING TO
--               AI-00399.
-- JRK 10/24/86  RENAMED FROM E94004B-B.ADA; REVISED ACCORDING TO
--               REVISED AI-00399.

WITH SYSTEM; USE SYSTEM;
PACKAGE C94004B_PKG IS

     TASK TYPE TT IS
          ENTRY E;
          PRAGMA PRIORITY (PRIORITY'FIRST);
     END TT;

END C94004B_PKG;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY C94004B_PKG IS

     TASK BODY TT IS
          I : INTEGER := IDENT_INT (120);
     BEGIN
          ACCEPT E;
          COMMENT ("DELAY LIBRARY TASK FOR TWO MINUTES");
          DELAY DURATION(I);
          -- MAIN PROGRAM SHOULD NOW BE TERMINATED.
          RESULT;
     END TT;

END C94004B_PKG;

WITH C94004B_PKG; USE C94004B_PKG;
PRAGMA ELABORATE (C94004B_PKG);
PACKAGE C94004B_TASK IS
     TYPE ACC_TASK IS ACCESS C94004B_PKG.TT;
END;

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH C94004B_TASK; WITH C94004B_PKG;
PROCEDURE C94004B IS

     T : C94004B_TASK.ACC_TASK;
     PRAGMA PRIORITY (PRIORITY'LAST);

BEGIN
     TEST ("C94004B", "CHECK THAT A MAIN PROGRAM TERMINATES " &
                      "WITHOUT WAITING FOR TASKS THAT DEPEND " &
                      "ON A LIBRARY PACKAGE AND THAT SUCH TASKS " &
                      "CONTINUE TO EXECUTE");

     COMMENT ("THE INVOKING SYSTEM'S JOB CONTROL LOG MUST BE " &
              "EXAMINED TO SEE IF THIS TEST REALLY TERMINATES");

     T := NEW C94004B_PKG.TT;
     T.E;      -- ALLOW TASK TO PROCEED.
     IF T'TERMINATED THEN
          FAILED ("LIBRARY DECLARED TASK PREMATURELY TERMINATED");
     END IF;

     -- RESULT PROCEDURE IS CALLED BY LIBRARY TASK.

END C94004B;
