-- C94004C.ADA

-- CHECK THAT A MAIN PROGRAM TERMINATES WITHOUT WAITING FOR TASKS THAT
-- DEPEND ON A LIBRARY PACKAGE AND THAT SUCH TASKS ARE NOT TERMINATED BY
-- MAIN PROGRAM TERMINATION.

-- CASE C:  TASK OBJECT DECLARED IN LIBRARY PACKAGE USED BY MAIN PROGRAM
--          AND WAITING AT A SELECTIVE WAIT WITH TERMINATE.

-- JRK 10/8/81
-- SPS 11/21/82
-- JBG 12/6/84
-- JRK 11/21/85  RENAMED FROM C94004C-B.ADA; REVISED ACCORDING TO
--               AI-00399.
-- JRK 10/24/86  RENAMED FROM E94004C-B.ADA; REVISED ACCORDING TO
--               REVISED AI-00399.

WITH SYSTEM; USE SYSTEM;
PACKAGE C94004C_PKG IS

     TASK TYPE TT IS
          ENTRY E;
          PRAGMA PRIORITY (PRIORITY'FIRST);
     END TT;

END C94004C_PKG;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY C94004C_PKG IS

     TASK BODY TT IS
          I : INTEGER := IDENT_INT (120);
     BEGIN
          ACCEPT E;
          COMMENT ("DELAY LIBRARY TASK FOR TWO MINUTES");
          DELAY DURATION(I);
          -- MAIN PROGRAM SHOULD NOW BE TERMINATED.
          RESULT;
          -- USE LOOP FOR SELECTIVE WAIT WITH TERMINATE.
          LOOP
               SELECT
                    ACCEPT E;
               OR
                    TERMINATE;
               END SELECT;
          END LOOP;
          -- FAILS IF JOB HANGS UP WITHOUT TERMINATING.
     END TT;

END C94004C_PKG;

WITH C94004C_PKG; USE C94004C_PKG;
PRAGMA ELABORATE (C94004C_PKG);
PACKAGE C94004C_TASK IS
     T : TT;
END;

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH C94004C_TASK;
PROCEDURE C94004C IS

     PRAGMA PRIORITY (PRIORITY'LAST);

BEGIN
     TEST ("C94004C", "CHECK THAT A MAIN PROGRAM TERMINATES " &
                      "WITHOUT WAITING FOR TASKS THAT DEPEND " &
                      "ON A LIBRARY PACKAGE AND THAT SUCH TASKS " &
                      "CONTINUE TO EXECUTE");

     COMMENT ("THE INVOKING SYSTEM'S JOB CONTROL LOG MUST BE " &
              "EXAMINED TO SEE IF THIS TEST REALLY TERMINATES");

     C94004C_TASK.T.E;      -- ALLOW TASK TO PROCEED.
     IF C94004C_TASK.T'TERMINATED THEN
          FAILED ("LIBRARY DECLARED TASK PREMATURELY TERMINATED");
     END IF;

     -- RESULT PROCEDURE IS CALLED BY LIBRARY TASK.

END C94004C;
