-- C94005A.ADA

-- CHECK THAT IF A TASK TYPE IS DECLARED IN A LIBRARY PACKAGE, A MAIN
--   PROGRAM THAT DECLARES OBJECTS OF THAT TYPE DOES WAIT FOR
--   TERMINATION OF SUCH OBJECTS.

-- THIS TEST CONTAINS RACE CONDITIONS.

-- JRK 10/8/81
-- SPS 11/21/82
-- JWC 11/15/85    MADE THE LIBRARY PACKAGE NAME UNIQUE, C94005A_PKG.


WITH SYSTEM; USE SYSTEM;
PACKAGE C94005A_PKG IS

     TASK TYPE TT IS
          ENTRY E;
          PRAGMA PRIORITY (PRIORITY'FIRST);
     END TT;

END C94005A_PKG;


WITH REPORT; USE REPORT;
PACKAGE BODY C94005A_PKG IS

     TASK BODY TT IS
          I : INTEGER := IDENT_INT (0);
     BEGIN
          ACCEPT E;
          FOR J IN 1..60 LOOP
               I := IDENT_INT (I);
               DELAY 1.0;
          END LOOP;
          RESULT;   -- FAILURE IF THIS MESSAGE IS NOT WRITTEN.
     END TT;

END C94005A_PKG;


WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH C94005A_PKG;
PROCEDURE C94005A IS

     T : C94005A_PKG.TT;

     PRAGMA PRIORITY (PRIORITY'LAST);

BEGIN
     TEST ("C94005A", "CHECK THAT IF A TASK TYPE IS DECLARED IN A " &
                      "LIBRARY PACKAGE, A MAIN PROGRAM THAT " &
                      "DECLARES OBJECTS OF THAT TYPE DOES WAIT FOR " &
                      "TERMINATION OF SUCH OBJECTS");

     COMMENT ("THE INVOKING SYSTEM'S JOB CONTROL LOG MUST BE " &
              "EXAMINED TO SEE IF THIS TEST REALLY TERMINATES");

     T.E;

     IF T'TERMINATED THEN
          COMMENT ("TEST INCONCLUSIVE BECAUSE TASK T PREMATURELY " &
                   "TERMINATED");
     END IF;

     -- TASK T SHOULD WRITE THE RESULT MESSAGE.

END C94005A;
