-- C94001E.ADA

-- CHECK THAT A TASK IS ALSO COMPLETED IF AN EXCEPTION IS RAISED BY
-- THE EXECUTION OF ITS SEQUENCE OF STATEMENTS.
-- THIS MUST HOLD FOR BOTH CASES WHERE A HANDLER IS PRESENT OR NOT.
--    VERSION WITH EXCEPTION HANDLER.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C940AGA-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C94001E IS

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     PROCEDURE PSPY_NUMB (DIGT: IN ARG) IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
     END PSPY_NUMB;

BEGIN

     TEST ("C94001E", "TASK COMPLETION BY EXCEPTION");

BLOCK:
     DECLARE

          TASK T1;

          TASK BODY T1 IS
               TYPE I1 IS RANGE 0 .. 1;
               OBJ_I1 : I1;
          BEGIN
               OBJ_I1 := I1(IDENT_INT(2));  -- CONSTRAINT_ERROR.
               PSPY_NUMB (1);
          EXCEPTION
               WHEN CONSTRAINT_ERROR => NULL;
               WHEN OTHERS => FAILED ("OTHER EXCEPTION RAISED");
          END T1;

     BEGIN
          NULL;
     END BLOCK;

     IF SPYNUMB /= 0 THEN
          FAILED ("TASK T1 NOT COMPLETED AFTER EXCEPTION");
          COMMENT ("ACTUAL ORDER WAS:" & INTEGER'IMAGE(SPYNUMB));
     END IF;

     RESULT;

END C94001E;
