-- C94001F.ADA

-- CHECK THAT A TASK IS ALSO COMPLETED IF AN EXCEPTION IS RAISED BY
-- THE EXECUTION OF ITS SEQUENCE OF STATEMENTS.
-- THIS MUST HOLD FOR BOTH CASES WHERE A HANDLER IS PRESENT OR NOT.
--   VERSION WITHOUT EXCEPTION HANDLER.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C940AGB-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C94001F IS

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     PROCEDURE PSPY_NUMB (DIGT: IN ARG) IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
     END PSPY_NUMB;

BEGIN

     TEST ("C94001F", "TASK COMPLETION BY EXCEPTION -- NO HANDLER");

BLOCK:
     DECLARE

          TASK T1;

          TASK BODY T1 IS
               TYPE I1 IS RANGE 0 .. 1;
               OBJ_I1 : I1;
          BEGIN
               OBJ_I1 := I1(IDENT_INT(2));  -- CONSTRAINT_ERROR.
               PSPY_NUMB (1);
          END T1;

     BEGIN
          NULL;          -- WAIT FOR TERMINATION.
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               FAILED ("PROPAGATED CONSTRAINT_ERROR OUT OF TASK");
          WHEN TASKING_ERROR =>
               FAILED ("RAISED TASKING_ERROR");
          WHEN OTHERS =>
               FAILED ("RAISED OTHER EXCEPTION");
     END BLOCK;

     IF SPYNUMB /= 0 THEN
          FAILED ("TASK T1 NOT COMPLETED AFTER EXCEPTION IN SEQUENCE " &
                  "OF STATEMENTS");
     END IF;

     RESULT;

END C94001F;
