-- C95033A.ADA

-- CHECK THAT - IN THE CASE OF AN ENTRY FAMILY - EXECUTION OF AN
-- ACCEPT STATEMENT STARTS WITH THE EVALUATION OF AN ENTRY INDEX.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C950BGA-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C95033A IS

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     PROCEDURE PSPY_NUMB (DIGT: IN ARG) IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
     END PSPY_NUMB;

     FUNCTION FINIT_POS (DIGT: IN ARG) RETURN NATURAL IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
          RETURN DIGT;
     END FINIT_POS;

     TASK T1 IS
          ENTRY E1 (NATURAL RANGE 1 .. 2);
          ENTRY BYE;
     END T1;

     TASK BODY T1 IS
     BEGIN
          ACCEPT E1 (FINIT_POS (1)) DO
               PSPY_NUMB (2);
          END E1;
          ACCEPT BYE;
     END T1;

BEGIN
     TEST ("C95033A", "EVALUATION OF ENTRY INDEX");

     T1.E1 (1);
     T1.BYE;
     IF SPYNUMB /= 12 THEN
          FAILED ("ENTRY INDEX NOT EVALUATED FIRST");
          COMMENT ("ACTUAL ORDER WAS:" & INTEGER'IMAGE(SPYNUMB));
     END IF;

     RESULT;

END C95033A;
