-- C95013A.ADA

-- CHECK THAT A RENDEZVOUS IN WHICH THE ACCEPT_STATEMENT HAS NO
--   "DO" PART IS CARRIED OUT.

-- THE SEMANTICS OF AN ACCEPT_STATEMENT THAT HAS NO "DO" PART ARE THAT
--   IT MUST WAIT UNTIL THE CORRESPONDING ENTRY IS CALLED.
--   THIS TEST ATTEMPTS TO EXECUTE SUCH AN ACCEPT_STATEMENT (ENTRY SYNC)
--   WITH AN EMPTY ENTRY CALL QUEUE, AND TO CHECK THAT THE ACCEPT
--   STATEMENT WAITS FOR A LATER SIMPLE ENTRY CALL.

-- THIS TEST CONTAINS RACE CONDITIONS.

-- JRK 11/6/81
-- SPS 11/2/82
-- SPS 11/21/82

WITH REPORT; USE REPORT;
WITH CALENDAR; USE CALENDAR;
WITH SYSTEM; USE SYSTEM;
PROCEDURE C95013A IS

     DELAY_TIME : CONSTANT DURATION := 60.0;
     BEFORE : TIME := CLOCK ;
     AFTER  : TIME := BEFORE;

     PRAGMA PRIORITY (PRIORITY'FIRST);

BEGIN
     TEST ("C95013A", "CHECK THAT A RENDEZVOUS IN WHICH THE " &
                      "ACCEPT_STATEMENT HAS NO ""DO"" PART " &
                      "IS CARRIED OUT");

     DECLARE

          TASK T IS
               ENTRY SYNC;
               ENTRY RESULT (A : OUT TIME);
               PRAGMA PRIORITY (PRIORITY'LAST);
          END T;

          TASK BODY T IS
               AFTER : TIME;
          BEGIN
               ACCEPT SYNC;
               AFTER := CLOCK ;
               ACCEPT RESULT (A : OUT TIME) DO
                    A := AFTER;
               END RESULT;
          END T;

     BEGIN

          BEFORE := CLOCK ;
          DELAY DELAY_TIME;
          T.SYNC;   -- THE TEST WILL BLOCK HERE IF THE ACCEPT SYNC IS
                    -- INCORRECT.  HOWEVER, A TIMED_ENTRY_CALL SHOULD
                    -- NOT BE USED HERE, SINCE MANY OTHER TASKING TESTS
                    -- EXPECT THIS MOST BASIC SYNCHRONIZATION METHOD TO
                    -- WORK CORRECTLY, AND THIS IS WHERE THE METHOD IS
                    -- TESTED.
          T.RESULT (AFTER);

     END;

     IF AFTER - BEFORE < DELAY_TIME THEN
          FAILED ("INSUFFICIENT DELAY");
     END IF;

     RESULT;
END C95013A;
