-- C95033B.ADA

-- CHECK THAT EXECUTION OF AN ENTRY CALL STARTS WITH THE EVALUATION OF
-- ANY ENTRY INDEX, FOLLOWED BY THE EVALUATION OF ANY EXPRESSION IN
-- THE PARAMETER LIST.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C950BHA-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C95033B IS

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     FUNCTION FINIT_POS (DIGT: IN ARG) RETURN NATURAL IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
          RETURN DIGT;
     END FINIT_POS;

     TASK T1 IS
          ENTRY E1 (NATURAL RANGE 1 .. 2) (P1 : IN NATURAL);
     END T1;

     TASK BODY T1 IS
     BEGIN
          ACCEPT E1 (1) (P1 : IN NATURAL);
     END T1;

BEGIN

     TEST ("C95033B", "EVALUATION OF ENTRY INDEX AND OF " &
                      "EXPRESSIONS IN PARAMETER LIST");

     T1.E1 (FINIT_POS (1)) (FINIT_POS (2));
     IF SPYNUMB /= 12 THEN
          FAILED ("ENTRY INDEX NOT EVALUATED FIRST");
          COMMENT ("ACTUAL ORDER WAS:" & INTEGER'IMAGE(SPYNUMB));
     END IF;

     RESULT;

END C95033B;
