-- C95009C.ADA

-- CHECK THAT A TASK  M U S T  DEADLOCK WHEN IT CALLS ONE OF ITS OWN
-- ENTRIES.  VERSION A: USE ONE TASK OBJECT.

-- WEI  3/ 4/82
-- JBG 6/3/85

WITH REPORT;
 USE REPORT;
PROCEDURE C95009C IS

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     FUNCTION FINIT_POS (DIGT: IN ARG) RETURN NATURAL IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
          RETURN DIGT;
     END FINIT_POS;

     TASK T1 IS
          ENTRY E1 (P1 : IN NATURAL);
     END T1;

     TASK BODY T1 IS
     BEGIN
          E1 (FINIT_POS (1));      -- TASK WILL BE ABORTED.
          ACCEPT E1 (P1 : IN NATURAL);
     END T1;

     TASK T2 IS
          ENTRY BYE;
     END T2;

     TASK BODY T2 IS
     BEGIN
          DELAY 5.0;
          IF SPYNUMB /= 1 THEN
               FAILED ("SCHEDULER DID NOT RUN T1 -- CHECK TEST");
          END IF;

          IF T1'TERMINATED THEN 
               FAILED ("NO DEADLOCK WITH TASK T1");
          ELSE 
               ABORT T1;
          END IF;

          ACCEPT BYE;
     END T2;

BEGIN

     TEST ("C95009C", "DEADLOCK DURING CALL OF OWN ENTRY");

     T2.BYE;

     RESULT;

EXCEPTION

     WHEN OTHERS =>
          FAILED ("UNEXPECTED EXCEPTION RAISED");
          RESULT;

END C95009C;
