-- C95073A.ADA

-- CHECK THAT ALIASING IS PERMITTED FOR PARAMETERS OF COMPOSITE TYPES,
-- E.G., THAT A MATRIX ADDITION PROCEDURE CAN BE CALLED WITH THREE
-- IDENTICAL ARGUMENTS.

-- JWC 7/29/85

WITH REPORT; USE REPORT;
PROCEDURE C95073A IS

     TYPE MATRIX IS ARRAY (1..3, 1..3) OF INTEGER;

     A : MATRIX := ((1,2,3), (4,5,6), (7,8,9));

     TASK T IS
          ENTRY MAT_ADD (X,Y : IN MATRIX; SUM : OUT MATRIX);
     END T;

     TASK BODY T IS
     BEGIN
          ACCEPT MAT_ADD (X,Y : IN MATRIX; SUM : OUT MATRIX) DO
               FOR I IN 1..3 LOOP
                    FOR J IN 1..3 LOOP
                         SUM (I,J) := X (I,J) + Y (I,J);
                    END LOOP;
               END LOOP;
          END MAT_ADD;
     END T;

BEGIN

     TEST ("C95073A", "CHECK THAT ALIASING IS PERMITTED FOR " &
                      "PARAMETERS OF COMPOSITE TYPES");

     T.MAT_ADD (A, A, A);

     IF A /= ((2,4,6), (8,10,12), (14,16,18)) THEN
          FAILED ("THE RESULT OF THE MATRIX ADDITION IS INCORRECT");
     END IF;

     RESULT;

END C95073A;
