-- C95011A.ADA

-- CHECK THAT A TASK NEED NOT CONTAIN ANY ACCEPT_STATEMENTS FOR AN
--   ENTRY.

-- THIS TEST CONTAINS SHARED VARIABLES.

-- JRK 11/5/81
-- JWC 6/28/85   RENAMED TO -AB

WITH REPORT; USE REPORT;
PROCEDURE C95011A IS

     V : INTEGER := 0;

BEGIN
     TEST ("C95011A", "CHECK THAT A TASK NEED NOT CONTAIN ANY " &
                      "ACCEPT_STATEMENTS FOR AN ENTRY");

     DECLARE

          SUBTYPE INT IS INTEGER RANGE 1..5;

          TASK T IS
               ENTRY E;
               ENTRY EF (INT) (I : INTEGER);
          END T;

          TASK BODY T IS
          BEGIN
               V := 1;
          END T;

     BEGIN

          NULL;

     END;

     IF V /= 1 THEN
          FAILED ("WRONG CONTROL FLOW VALUE");
     END IF;

     RESULT;
END C95011A;
