-- C95034B.ADA

-- CHECK THAT A CALLING TASK REMAINS SUSPENDED UNTIL THE ACCEPT
-- STATEMENT RECEIVING THIS ENTRY CALL HAS COMPLETED THE EXECUTION OF
-- ITS SEQUENCE OF STATEMENTS.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C950CBA-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C95034B IS

     SUBTYPE ARG IS NATURAL RANGE 0..9;
     SPYNUMB : NATURAL := 0;

     PROCEDURE PSPY_NUMB (DIGT: IN ARG) IS
     BEGIN
          SPYNUMB := 10*SPYNUMB+DIGT;
     END PSPY_NUMB;

     TASK T1 IS
          ENTRY E1;
     END T1;

     TASK BODY T1 IS
     BEGIN
          ACCEPT E1 DO
               PSPY_NUMB (1);
               DELAY 1.0;
               PSPY_NUMB (2);
          END E1;
     END T1;

     TASK T2 IS
          ENTRY BYE;
     END T2;

     TASK BODY T2 IS
     BEGIN
          T1.E1;
          PSPY_NUMB (3);
          ACCEPT BYE;
     END T2;

BEGIN

     TEST ("C95034B", "TASK SUSPENSION UNTIL COMPLETION OF ACCEPT " &
                      "STATEMENT");

     T2.BYE;

     IF SPYNUMB /= 123 THEN
          FAILED ("ERROR DURING TASK EXECUTION");
          COMMENT ("ACTUAL ORDER WAS:" & INTEGER'IMAGE(SPYNUMB));
     END IF;

     RESULT;

END C95034B;
