-- C95040A.ADA

-- CHECK THAT THE EXCEPTION TASKING_ERROR IS RAISED IF AN ENTRY OF A
-- COMPLETED TASK IS CALLED.

-- WEI  3/ 4/82
-- JWC 6/28/85   RENAMED FROM C950CHA-B.ADA

WITH REPORT;
 USE REPORT;
PROCEDURE C95040A IS
BEGIN

     TEST ("C95040A", "ENTRY CALL OF COMPLETED TASK");

BLOCK1 :
     DECLARE
          TASK T1 IS
               ENTRY E1;
          END T1;

          TASK BODY T1 IS
          BEGIN
               ACCEPT E1;
          END T1;
     BEGIN  -- BLOCK1
          T1.E1;
          T1.E1;

          FAILED ("DID NOT RAISE TASKING_ERROR");
     EXCEPTION
          WHEN TASKING_ERROR => NULL;
     END BLOCK1;

     RESULT;

END C95040A;
