-- C96008B.ADA

-- MISCELLANEOUS CHECKS ON THE PRE-DEFINED FUNCTIONS IN THE PACKAGE
-- CALENDAR.  SUBTESTS ARE:
--   (A) THE FUNCTION TIME_OF() MUST ADVANCE DAY WHEN CALLED WITH THE
--       SECONDS ARGUMENT HAVING THE VALUE 86_400.

-- CPP 8/16/84
-- JRK 12/4/84

WITH CALENDAR;  USE CALENDAR;
WITH REPORT;  USE REPORT;
PROCEDURE C96008B IS

     NOW1, NOW2 : TIME;
     YR : YEAR_NUMBER;
     MO : MONTH_NUMBER;
     DY : DAY_NUMBER;
     SEC : DAY_DURATION;

BEGIN

     TEST ("C96008B", "CHECK THAT TIME_OF() ADVANCES DAY");

     NOW1 := TIME_OF (1984, 8, 13, 86_400.0);
     NOW2 := TIME_OF (1984, 8, 14, 0.0);

     IF NOW1 /= NOW2 THEN
          FAILED ("TIME_OF DID NOT CONVERT 86_400 SECONDS TO A DAY");
     END IF;

     SPLIT (NOW2, YR, MO, DY, SEC);

     IF DY /= 14 THEN
          FAILED ("DAY OF NOW2 INCORRECT");
     END IF;
     IF SEC /= 0.0 THEN
          FAILED ("SECONDS OF NOW2 INCORRECT");
     END IF;

     SPLIT (NOW1, YR, MO, DY, SEC);

     IF DY /= 14 OR SEC /= 0.0 OR
        DAY (NOW1) /= 14 OR SECONDS (NOW1) /= 0.0 THEN
          FAILED ("TIME_OF DID NOT ADVANCE DAY");
     END IF;

     RESULT;
END C96008B;
