-- C97113A.ADA

-- CHECK THAT ALL CONDITIONS, OPEN DELAY ALTERNATIVE EXPRESSIONS, AND
--   OPEN ENTRY FAMILY INDICES ARE EVALUATED (EVEN WHEN SOME (PERHAPS
--   ALL BUT ONE) OF THE ALTERNATIVES CAN BE RULED OUT WITHOUT
--   COMPLETING THE EVALUATIONS).

-- RM 5/06/82
-- SPS 11/21/82
-- WRG 7/9/86    ADDED DELAY EXPRESSIONS AND ENTRY FAMILY INDICES.

WITH REPORT; USE REPORT;
PROCEDURE C97113A IS

     EXPR1_EVALUATED : BOOLEAN := FALSE;
     EXPR2_EVALUATED : BOOLEAN := FALSE;
     EXPR3_EVALUATED : BOOLEAN := FALSE;

     FUNCTION F1 RETURN BOOLEAN IS
     BEGIN
          EXPR1_EVALUATED := TRUE;
          RETURN TRUE;
     END F1;

     FUNCTION F2 (X : INTEGER) RETURN INTEGER IS
     BEGIN
          EXPR2_EVALUATED := TRUE;
          RETURN X;
     END F2;

     FUNCTION F3 (X : DURATION) RETURN DURATION IS
     BEGIN
          EXPR3_EVALUATED := TRUE;
          RETURN X;
     END F3;

BEGIN

     TEST ("C97113A", "CHECK THAT ALL CONDITIONS, OPEN DELAY " &
                      "ALTERNATIVE EXPRESSIONS, AND OPEN ENTRY " &
                      "FAMILY INDICES ARE EVALUATED");

     DECLARE

          TASK T IS
               ENTRY E1;
               ENTRY E2;
               ENTRY E3 (1..1);
          END T;

          TASK BODY T IS
          BEGIN
               --ENSURE THAT E1 HAS BEEN CALLED BEFORE PROCEEDING:
               WHILE E1'COUNT = 0 LOOP
                    DELAY 1.0;
               END LOOP;

               SELECT
                    ACCEPT E1;
               OR
                    WHEN F1 =>
                         ACCEPT E2;
               OR
                    ACCEPT E3 ( F2(1) );
               OR
                    DELAY F3 ( 1.0 );
               END SELECT;
          END T;

     BEGIN

          T.E1;

     END;

     IF NOT EXPR1_EVALUATED THEN
          FAILED ("GUARD NOT EVALUATED");
     END IF;

     IF NOT EXPR2_EVALUATED THEN
          FAILED ("ENTRY FAMILY INDEX NOT EVALUATED");
     END IF;

     IF NOT EXPR3_EVALUATED THEN
          FAILED ("OPEN DELAY ALTERNATIVE EXPRESSION NOT EVALUATED");
     END IF;

     RESULT;

END C97113A;
