-- C97305C.ADA

-- CHECK THAT IF THE RENDEZVOUS IS NOT IMMEDIATELY POSSIBLE BUT BECOMES
-- POSSIBLE BEFORE THE DELAY EXPIRES, THE TIMED ENTRY CALL IS ACCEPTED.

-- CASE A: SINGLE ENTRY; THE CALLED TASK IS EXECUTING AN ACCEPT
--         STATEMENT.

-- WRG 7/13/86

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;
PROCEDURE C97305C IS

     RENDEZVOUS_OCCURRED            : BOOLEAN  := FALSE;
     STATEMENTS_AFTER_CALL_EXECUTED : BOOLEAN  := FALSE;
     DELAY_IN_MINUTES               : CONSTANT POSITIVE := 30;

     PRAGMA PRIORITY (PRIORITY'LAST);             -- HIGHEST PRIORITY.

BEGIN

     TEST ("C97305C", "CHECK THAT IF THE RENDEZVOUS IS NOT " &
                      "IMMEDIATELY POSSIBLE BUT BECOMES POSSIBLE " &
                      "BEFORE THE DELAY EXPIRES, THE TIMED ENTRY " &
                      "CALL IS ACCEPTED");

     DECLARE

          TASK T IS
               PRAGMA PRIORITY (PRIORITY'FIRST);  -- LOWEST PRIORITY.
               ENTRY E (B : IN OUT BOOLEAN);
          END T;

          TASK BODY T IS
          BEGIN
               DELAY 10.0;
               ACCEPT E (B : IN OUT BOOLEAN) DO
                    B := IDENT_BOOL (TRUE);
               END E;
          END T;

     BEGIN

          SELECT
               T.E (RENDEZVOUS_OCCURRED);
               STATEMENTS_AFTER_CALL_EXECUTED := IDENT_BOOL (TRUE);
          OR
               DELAY DELAY_IN_MINUTES * 60.0;
               FAILED ("TIMED ENTRY CALL NOT ACCEPTED AFTER" &
                       POSITIVE'IMAGE(DELAY_IN_MINUTES) &
                       " MINUTES ELAPSED");

          END SELECT;

     END;

     IF NOT RENDEZVOUS_OCCURRED THEN
          FAILED ("RENDEZVOUS DID NOT OCCUR");
     END IF;

     IF NOT STATEMENTS_AFTER_CALL_EXECUTED THEN
          FAILED ("STATEMENTS AFTER ENTRY CALL NOT EXECUTED");
     END IF;

     RESULT;

END C97305C;
