-- C98001C.ADA

-- CHECK THAT A NONSTATIC EXPRESSION IN A PRAGMA PRIORITY IS NOT
-- EVALUATED.

-- TBN  12/18/86

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;
PROCEDURE C98001C IS

     FUNCTION FUN RETURN PRIORITY IS
     BEGIN
          FAILED ("NONSTATIC EXPRESSION EVALUATED");
          RETURN PRIORITY'FIRST;
     END FUN;

     PRAGMA PRIORITY (FUN);

BEGIN
     TEST ("C98001C", "CHECK THAT A NONSTATIC EXPRESSION IN A PRAGMA " &
                      "PRIORITY IS NOT EVALUATED");

     DECLARE
          TASK T IS
               ENTRY E;
               PRAGMA PRIORITY (FUN);
          END T;

          TASK BODY T IS
          BEGIN
               ACCEPT E DO
                    COMMENT ("TASK BODY EXECUTES");
               END E;
          END T;
     BEGIN
          T.E;
     END;

     RESULT;
END C98001C;
