-- C9A009F.ADA

-- CHECK THAT A TASK ABORTED DURING AN ENTRY CALL IS NOT TERMINATED
-- BEFORE THE END OF THE RENDEZVOUS.

-- JEAN-PIERRE ROSEN 16-MAR-1984
-- JBG 6/1/84

WITH REPORT,SYSTEM; 
USE REPORT,SYSTEM;
PROCEDURE C9A009F IS

     PRAGMA PRIORITY(PRIORITY'FIRST);

     TASK BLOCKING IS
          ENTRY START;
          ENTRY STOP;
          ENTRY RESTART;
          ENTRY NO_CALL;
     END BLOCKING;

     TASK BODY BLOCKING IS
     BEGIN
          SELECT
               ACCEPT STOP DO
                    ACCEPT START;
                    ACCEPT RESTART;
               END;
          OR TERMINATE;
          END SELECT;
     END;

BEGIN

     TEST("C9A009F", "ABORTED TASK NOT TERMINATED BEFORE END OF " &
                     "RENDEVOUS");

     DECLARE         -- T1 ABORTED WHILE IN RENDEVOUS WITH BLOCKING.

          TASK T1 IS
               PRAGMA PRIORITY(PRIORITY'LAST); -- THIS PRIORITY TO MAX
          END T1;                              -- THE CHANCE OF T1 BEING
                                               -- (WRONGLY) TERMINATED.
          TASK BODY T1 IS
          BEGIN
               BLOCKING.STOP;
               FAILED ("T1 NOT ABORTED");
          END;
     
     BEGIN
          BLOCKING.START;          -- ALLOWS T1 TO ENTER RENDEVOUS

          ABORT T1;

          IF T1'CALLABLE THEN
               FAILED("T1 STILL CALLABLE - 1");
          END IF;

          IF T1'TERMINATED THEN    -- T1 STILL IN RENDEVOUS
               FAILED("T1 PREMATURELY TERMINATED - 1");
          END IF;

          BLOCKING.RESTART;
     END;

     RESULT;

END C9A009F;
