-- C9A011A.ADA

-- OBJECTIVE:
--     CHECK THAT IF A CALLED TASK IS ABORTED WHILE IN RENDEZVOUS, THEN
--     "TASKING_ERROR" IS RAISED IN THE CALLING TASK.

-- HISTORY:
--     DHH 03/28/88 CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE C9A011A IS

     TASK TYPE CHOICE IS
          ENTRY E1;
     END CHOICE;

     T : CHOICE;

     TASK BODY CHOICE IS
          X : INTEGER;
     BEGIN
          ACCEPT E1 DO
               X := IDENT_INT(3);
               IF EQUAL(X,X) THEN
                    ABORT CHOICE;
               END IF;
          END E1;
     END CHOICE;

BEGIN

     TEST("C9A011A", "CHECK THAT IF A CALLED TASK IS ABORTED WHILE " &
                     "IN RENDEZVOUS, THEN ""TASKING_ERROR"" IS " &
                     "RAISED IN THE CALLING TASK");

     T.E1;
     FAILED("EXCEPTION NOT RAISED ON ABORT");

     RESULT;

EXCEPTION
     WHEN TASKING_ERROR =>
          RESULT;

     WHEN OTHERS =>
          FAILED("UNEXPECTED EXCEPTION RAISED ON ABORT");
          RESULT;
END C9A011A;
