-- C9A010A.ADA

-- TEST ABORT DURING RENDEZVOUS

-- ABORTING AN ABNORMAL (NOT YET TERMINATED) TASK.

-- JEAN-PIERRE ROSEN 09 MARCH 1984
-- JBG 6/1/84
-- JWC 6/28/85   RENAMED FROM C9A009E-B.ADA

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE C9A010A IS

BEGIN

     TEST("C9A010A", "ABORTING AN ABNORMAL TASK");

     DECLARE
     -- T1 CALLS T2.  WHILE IN RENDEVOUS, T2 ABORTS T1 AND WAITS FOR A
     -- CALL FROM THE MAIN PROGRAM.  WHEN THE CALL IS ACCEPTED, THE MAIN
     -- PROGRAM AGAIN ABORTS T1, WHICH IS NOW ABNORMAL, SINCE T1 HAS NOT
     -- YET COMPLETED ITS RENDEVOUS WITH T2.

          TASK T1 IS
               PRAGMA PRIORITY(PRIORITY'FIRST);
          END T1;

          TASK T2 IS
               ENTRY E1;
               ENTRY E2;
          END T2;

          TASK BODY T1 IS
          BEGIN
               T2.E1;
               FAILED("T1 NOT ABORTED");
          EXCEPTION
               WHEN TASKING_ERROR =>
                    FAILED ("TASKING_ERROR IN T1");
               WHEN OTHERS =>
                    FAILED ("OTHER EXCEPTION IN T1");
          END T1;

          TASK BODY T2 IS
          BEGIN
               ACCEPT E1 DO
                    ABORT  T1;
                    ACCEPT E2;     -- NOTE CALLER REMAINS IN RENDEVOUS
                    ACCEPT E2;     -- UNTIL TWO ENTRY CALLS ACCEPTED
               END E1;
          END T2;
     BEGIN
          T2.E2;    -- ONLY ACCEPTED AFTER T1 HAS BEEN ABORTED.
          ABORT T1; -- T1 IS ABNORMAL BECAUSE IT IS STILL IN RENDEVOUS.
          IF T1'CALLABLE THEN
               FAILED ("T1 CALLABLE AFTER BEING ABORTED");
          END IF;
          IF T1'TERMINATED THEN
               FAILED ("T1 TERMINATED ALTHOUGH IN RENDEVOUS");
          END IF;
          T2.E2; -- T1'S RENDEVOUS CAN NOW COMPLETE; T1 CAN TERMINATE.
     END;

     RESULT;

END C9A010A;
