-- CA1012B4M.ADA

-- CHECK THAT GENERIC SUBPROGRAM DECLARATIONS AND BODIES CAN BE
--   COMPILED SEPARATELY.

-- SEPARATE FILES ARE:
--   CA1012B0  A LIBRARY GENERIC PROCEDURE DECLARATION AND BODY.
--   CA1012B2  A LIBRARY GENERIC FUNCTION DECLARATION AND BODY.
--   CA1012B4M THE MAIN PROCEDURE.

-- WKB 7/20/81

WITH REPORT, CA1012B0, CA1012B2;
USE REPORT;
PROCEDURE CA1012B4M IS

     N : INTEGER := 1;

     SUBTYPE S50 IS INTEGER RANGE 1..50;

     PROCEDURE P IS NEW CA1012B0 (S50);

     FUNCTION F IS NEW CA1012B2 (INTEGER);

BEGIN
     TEST ("CA1012B", "SEPARATELY COMPILED GENERIC SUBPROGRAM " &
                      "DECLARATIONS AND BODIES");

     P(N);
     IF N /= 2 THEN
          FAILED ("PROCEDURE NOT INVOKED");
     END IF;

     N := 1;
     IF F(N) /= 2 THEN
          FAILED ("FUNCTION NOT INVOKED");
     END IF;

     RESULT;

END CA1012B4M;
