-- CA1020D3M.ADA

-- CHECK THAT WHEN A SUBPROGRAM BODY IS COMPILED AS A LIBRARY UNIT, IT
-- REPLACES ANY PREVIOUS LIBRARY SUBPROGRAM CREATED BY GENERIC
-- INSTANTIATION.

-- JBG 5/28/85

-- UNITS ARE:
--   CA1020D0 -- A GENERIC FUNCTION AND PROCEDURE PLUS THEIR
--               INSTANTIATIONS, CA1020D_PROC1 AND CA1020D_FUNC2
--   CA1020D1 -- REPLACEMENT SUBPROGRAM BODIES
--   CA1020D2 -- ADDITIONAL INSTANTIATIONS
--   CA1020D3M

WITH REPORT; USE REPORT;
WITH CA1020D_PROC1, CA1020D_FUNC2, CA1020D_PROC5, CA1020D_FUNC22;
PROCEDURE CA1020D3M IS
     TEMP : INTEGER := 0;
BEGIN
     TEST ("CA1020D", "CHECK THAT LIBRARY SUBPROGRAMS CREATED BY " &
                      "GENERIC INSTANTIATION CAN BE REPLACED BY " &
                      "WHEN NEW NON-GENERIC SUBPROGRAM BODIES ARE " &
                      "COMPILED");

     CA1020D_PROC1(TEMP);
     IF TEMP /= IDENT_INT(3) THEN
          FAILED ("PROC INSTANTIATION NOT REPLACED");
     END IF;

     IF CA1020D_FUNC2 /= 4 THEN
          FAILED ("FUNCTION INSTANTIATION NOT REPLACED");
     END IF;

     CA1020D_PROC5(TEMP);
     IF TEMP /= IDENT_INT(5) THEN
          FAILED ("NEW PROC INSTANTIATION NOT CORRECT");
     END IF;

     IF CA1020D_FUNC22 /= IDENT_INT(2) THEN
          FAILED ("NEW FUNC INSTANTIATION NOT CORRECT");
     END IF;

     RESULT;
END CA1020D3M;
