-- CA1013A6M.ADA

-- CHECK THAT A GENERIC PACKAGE OR SUBPROGRAM INSTANTIATION
-- CAN BE SUBMITTED FOR SEPARATE COMPILATION.

-- SEPARATE FILES ARE:
--   CA1013A0  A LIBRARY GENERIC PACKAGE.
--   CA1013A1  A LIBRARY GENERIC PROCEDURE.
--   CA1013A2  A LIBRARY GENERIC FUNCTION.
--   CA1013A3  A LIBRARY GENERIC PACKAGE INSTANTIATION.
--   CA1013A4  A LIBRARY GENERIC PROCEDURE INSTANTIATION.
--   CA1013A5  A LIBRARY GENERIC FUNCTION INSTANTIATION.
--   CA1013A6M THE MAIN PROCEDURE.

-- WKB 7/20/81
-- SPS 11/5/82

WITH REPORT;
WITH CA1013A3, CA1013A4, CA1013A5;
USE REPORT;
PROCEDURE CA1013A6M IS

     J : INTEGER := 1;

BEGIN
     TEST ("CA1013A", "GENERIC INSTANTIATIONS SUBMITTED " &
                      "FOR SEPARATE COMPILATION");

     IF CA1013A3.I /= 1 THEN
          FAILED ("PACKAGE NOT ACCESSED");
     END IF;

     CA1013A4 (J);
     IF J /= 2 THEN
          FAILED ("PROCEDURE NOT INVOKED");
     END IF;

     IF CA1013A5 /= 2 THEN
          FAILED ("FUNCTION NOT INVOKED");
     END IF;

     RESULT;
END CA1013A6M;
