-- CA1004A.ADA

-- CHECK THAT A PACKAGE DECLARATION AND BODY CAN BE
-- SUBMITTED TOGETHER FOR COMPILATION.

-- JRK 5/12/81


PACKAGE CA1004A_PKG IS

     I : INTEGER := 0;

     PROCEDURE P (I : IN OUT INTEGER);

END CA1004A_PKG;


PACKAGE BODY CA1004A_PKG IS

     PROCEDURE P (I : IN OUT INTEGER) IS
     BEGIN
          I := I + 1;
     END P;

BEGIN

     I := 10;

END CA1004A_PKG;


WITH REPORT, CA1004A_PKG;
USE REPORT;

PROCEDURE CA1004A IS

     I : INTEGER := IDENT_INT (0);

BEGIN
     TEST ("CA1004A", "A PACKAGE DECLARATION AND BODY SUBMITTED " &
           "TOGETHER");

     CA1004A_PKG.I := CA1004A_PKG.I + IDENT_INT(5);
     IF CA1004A_PKG.I /= 15 THEN
          FAILED ("PACKAGED VARIABLE NOT ACCESSIBLE OR " &
                  "PACKAGE BODY NOT EXECUTED");
     END IF;

     CA1004A_PKG.P (I);
     IF I /= 1 THEN
          FAILED ("PACKAGED PROCEDURE NOT EXECUTED");
     END IF;

     RESULT;
END CA1004A;
