-- CA1003A.ADA

-- CHECK THAT MORE THAN ONE COMPLETELY INDEPENDENT COMPILATION
-- UNIT CAN BE SUBMITTED IN A SINGLE FILE.

-- JRK 5/13/81
-- JBG 8/25/83

PROCEDURE CA1003A_P (I : IN OUT INTEGER) IS
BEGIN
     I := I + 1;
END CA1003A_P;


PACKAGE CA1003A_PKG IS
     I : INTEGER := 0;
END CA1003A_PKG;


FUNCTION CA1003A_F (I : INTEGER) RETURN INTEGER IS
BEGIN
     RETURN -I;
END CA1003A_F;


WITH REPORT, CA1003A_P, CA1003A_PKG, CA1003A_F;
USE REPORT;

PROCEDURE CA1003A IS

     I : INTEGER := IDENT_INT (0);

BEGIN
     TEST ("CA1003A", "INDEPENDENT UNITS IN A SINGLE FILE");

     CA1003A_P (I);
     IF I /= 1 THEN
          FAILED ("INDEPENDENT PROCEDURE NOT INVOKED");
     END IF;

     CA1003A_PKG.I := CA1003A_PKG.I + IDENT_INT(10);
     IF CA1003A_PKG.I /= 10 THEN
          FAILED ("INDEPENDENT PACKAGE VARIABLE ACCESSED INCORRECTLY");
     END IF;

     IF CA1003A_F(IDENT_INT(5)) /= -5 THEN
          FAILED ("INDEPENDENT FUNCTION NOT INVOKED");
     END IF;

     RESULT;
END CA1003A;
