-- CA1005A.ADA

-- CHECK THAT A SUBPROGRAM DECLARATION AND BODY CAN BE
-- SUBMITTED TOGETHER FOR COMPILATION.

-- JRK 5/14/81


FUNCTION CA1005A_F (I : INTEGER) RETURN INTEGER;


FUNCTION CA1005A_F (I : INTEGER) RETURN INTEGER IS
BEGIN
     RETURN I + 1;
END CA1005A_F;


PROCEDURE CA1005A_P (I : IN OUT INTEGER);


PROCEDURE CA1005A_P (I : IN OUT INTEGER) IS
BEGIN
     I := -I;
END CA1005A_P;


WITH REPORT, CA1005A_F, CA1005A_P;
USE REPORT;

PROCEDURE CA1005A IS

     I : INTEGER := IDENT_INT (7);

BEGIN
     TEST ("CA1005A", "SUBPROGRAM DECLARATIONS AND BODIES " &
           "SUBMITTED TOGETHER");

     IF CA1005A_F (IDENT_INT(2)) /= 3 THEN
          FAILED ("FUNCTION NOT EXECUTED");
     END IF;

     CA1005A_P (I);
     IF I /= -7 THEN
          FAILED ("PROCEDURE NOT EXECUTED");
     END IF;

     RESULT;
END CA1005A;
