-- CA1020E3M.ADA

-- OBJECTIVE:
--     CHECK THAT A SUBPROGRAM LIBRARY UNIT CAN BE REPLACED BY A GENERIC
--     INSTANTIATION HAVING THE SAME IDENTIFIER.  THIS FILE CONTAINS
--     GENERIC UNITS TO BE INSTANTIATED AS LIBRARY UNITS.

-- SEPARATE FILES ARE:
--     CA1020E0  -- GENERIC UNITS GENPROC_CA1020E AND GENFUNC_CA1020E.
--     CA1020E1  -- SUBPROGRAM LIBRARY UNIT BODIES (CA1020E_PROC1,
--                  CA1020E_FUNC1, CA1020E_PROC2, CA1020E_FUNC2).
--     CA1020E2  -- INSTANTIATIONS REPLACING UNITS COMPILED IN CA1020E1.
--     CA1020E3M -- MAIN PROGRAM.

-- HISTORY:
--     JBG 05/28/85  CREATED ORIGINAL TEST.
--     JET 07/29/88  ADDED CASES IN WHICH SUBPROGRAM PROFILES ARE NOT
--                   THE SAME AND ALSO WHEN SUBPROGRAM IS FIRST
--                   DECLARED WITHOUT A BODY.

WITH REPORT; USE REPORT;
WITH CA1020E_PROC1, CA1020E_FUNC1, CA1020E_PROC2, CA1020E_FUNC2;
PROCEDURE CA1020E3M IS
     TEMP : INTEGER := 0;
BEGIN
     TEST ("CA1020E", "CHECK THAT A SUBPROGRAM LIBRARY UNIT CAN BE " &
                      "REPLACED BY A GENERIC INSTANTIATION HAVING " &
                      "THE SAME IDENTIFIER");

     CA1020E_PROC1 (TEMP);
     IF TEMP /= IDENT_INT(1) THEN
          FAILED ("INSTANTIATION DID NOT REPLACE PROCEDURE");
     END IF;

     IF CA1020E_FUNC1 /= IDENT_INT(2) THEN
          FAILED ("INSTANTIATION DID NOT REPLACE FUNCTION");
     END IF;

     CA1020E_PROC2 (TEMP);
     IF TEMP /= IDENT_INT(5) THEN
          FAILED ("INSTANTIATION DID NOT REPLACE PROCEDURE");
     END IF;

     IF CA1020E_FUNC2 /= IDENT_INT(2) THEN
          FAILED ("INSTANTIATION DID NOT REPLACE FUNCTION");
     END IF;

     RESULT;
END CA1020E3M;
