-- CA1020E1.ADA

-- OBJECTIVE:
--     CHECK THAT A SUBPROGRAM LIBRARY UNIT CAN BE REPLACED BY A GENERIC
--     INSTANTIATION HAVING THE SAME IDENTIFIER.  THIS FILE CONTAINS
--     SUBPROGRAMS TO BE REPLACED BY LATER GENERIC INSTANTIATIONS.

-- HISTORY:
--     JBG 05/28/85  CREATED ORIGINAL TEST.
--     JET 07/29/88  ADDED CASES IN WHICH SUBPROGRAM PROFILES ARE NOT
--                   THE SAME AND ALSO WHEN SUBPROGRAM IS FIRST
--                   DECLARED WITHOUT A BODY.

PROCEDURE CA1020E_PROC1 (X : OUT INTEGER) IS
BEGIN
     X := 3;
END CA1020E_PROC1;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
FUNCTION CA1020E_FUNC1 RETURN INTEGER IS
BEGIN
     RETURN IDENT_INT(4);
END CA1020E_FUNC1;

PROCEDURE CA1020E_PROC2 (X : OUT INTEGER);
PROCEDURE CA1020E_PROC2 (X : OUT INTEGER) IS
BEGIN
     X := 3;
END CA1020E_PROC2;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
FUNCTION CA1020E_FUNC2 RETURN FLOAT IS
BEGIN
     RETURN FLOAT(IDENT_INT(4));
END CA1020E_FUNC2;
