-- CA1022A6M.ADA

-- CHECK THAT IF A SUBPROGRAM BODY IS INITIALLY COMPILED WITH A CONTEXT
-- CLAUSE AND A UNIT NAMED IN THE CONTEXT CLAUSE IS RECOMPILED, THEN AN
-- ATTEMPT TO COMPILE THE BODY AGAIN WILL SUCCEED IF THE CONTEXT CLAUSE
-- IS PRESENT.
-- CHECK THAT IF THE RECOMPILED UNIT IS NOT NEEDED IN THE SUBPROGRAM
-- BODY, THE BODY CAN BE SUCCESSFULLY RECOMPILED WITHOUT MENTIONING THE
-- RECOMPILED UNIT.

-- SEPARATE FILES ARE:
--     CA1022A0  A LIBRARY PACKAGE.
--     CA1022A1  A LIBRARY PROCEDURE.
--     CA1022A2  A LIBRARY FUNCTION.
--     CA1022A3  A LIBRARY PACKAGE (CA1022A0).
--     CA1022A4  A LIBRARY PROCEDURE (CA1022A1).
--     CA1022A5  A LIBRARY FUNCTION (CA1022A2).
--     CA1022A6M THE MAIN PROCEDURE.

-- BHS 7/23/84

WITH CA1022A1, CA1022A2;
WITH REPORT; USE REPORT;
PROCEDURE CA1022A6M IS

     I : INTEGER := 1;

BEGIN

     TEST ("CA1022A", "USE OF CONTEXT CLAUSES NAMING RECOMPILED " &
                      "UNITS WITH RECOMPILED SUBPROGRAMS");

     CA1022A1(I);
     IF I /= 5 THEN
          FAILED ("PROCEDURE CA1022A1 NOT INVOKED CORRECTLY");
     END IF;

     IF CA1022A2 THEN
          FAILED ("FUNCTION CA1022A2 NOT INVOKED CORRECTLY");
     END IF;

     RESULT;

END CA1022A6M;
