-- CA1006A.ADA

-- CHECK THAT A LIBRARY UNIT AND ITS SUBUNITS CAN BE
-- SUBMITTED TOGETHER FOR COMPILATION.

-- JRK 5/14/81

WITH REPORT;
USE REPORT;

PROCEDURE CA1006A IS

     I : INTEGER := IDENT_INT (0);

     PACKAGE CALL_TEST IS
     END CALL_TEST;

     PACKAGE BODY CALL_TEST IS
     BEGIN
          TEST ("CA1006A", "A LIBRARY UNIT AND ITS SUBUNITS " &
                "SUBMITTED TOGETHER");
     END CALL_TEST;

     FUNCTION F (I : INTEGER) RETURN INTEGER IS SEPARATE;

     PACKAGE PKG IS
          I : INTEGER := IDENT_INT (0);
          PROCEDURE P (I : IN OUT INTEGER);
     END PKG;

     PACKAGE BODY PKG IS SEPARATE;

     PROCEDURE P (I : IN OUT INTEGER) IS SEPARATE;

BEGIN

     IF PKG.I /= 10 THEN
          FAILED ("PACKAGE BODY STATEMENTS NOT EXECUTED");
     END IF;

     IF F(IDENT_INT(5)) /= -5 THEN
          FAILED ("FUNCTION NOT ELABORATED/EXECUTED");
     END IF;

     PKG.P (I);
     IF I /= 3 THEN
          FAILED ("PACKAGED PROCEDURE NOT ELABORATED/EXECUTED");
     END IF;

     I := IDENT_INT (-20);
     P (I);
     IF I /= -24 THEN
          FAILED ("PROCEDURE NOT ELABORATED/EXECUTED");
     END IF;

     RESULT;
END CA1006A;


SEPARATE (CA1006A)
FUNCTION F (I : INTEGER) RETURN INTEGER IS
BEGIN
     RETURN -I;
END F;


SEPARATE (CA1006A)
PACKAGE BODY PKG IS

     PROCEDURE P (I : IN OUT INTEGER) IS
     BEGIN
          I := I + 3;
     END P;

BEGIN
     I := I + 10;
END PKG;


SEPARATE (CA1006A)
PROCEDURE P (I : IN OUT INTEGER) IS
BEGIN
     I := I - 4;
END P;
