-- CA1008A1M.ADA

-- CHECK THAT A GENERIC PACKAGE DECLARATION CAN BE
--   COMPILED WITHOUT ITS BODY.

-- SEPARATE FILES ARE:
--   CA1008A0  A LIBRARY GENERIC PACKAGE DECLARATION.
--   CA1008A1M THE MAIN PROCEDURE.

-- WKB 7/20/81

WITH REPORT, CA1008A0;
USE REPORT;
PROCEDURE CA1008A1M IS

BEGIN
     TEST ("CA1008A", "A GENERIC PACKAGE SPECIFICATION CAN BE " &
                      "COMPILED WITHOUT ITS BODY");

     DECLARE
          PACKAGE PKG IS NEW CA1008A0 (INTEGER);
     BEGIN
          IF PKG.I /= 1 THEN
               FAILED ("INSTANTIATED PACKAGE NOT INVOKED");
          END IF;
     END;

     RESULT;
END CA1008A1M;
