-- CA1020E2.ADA

-- OBJECTIVE:
--     CHECK THAT A SUBPROGRAM LIBRARY UNIT CAN BE REPLACED BY A GENERIC
--     INSTANTIATION HAVING THE SAME IDENTIFIER.  THIS FILE CONTAINS
--     GENERIC INSTANTIATIONS REPLACING LIBRARY UNITS CREATED IN
--     CA1020E1.

-- HISTORY:
--     JBG 05/28/85  CREATED ORIGINAL TEST.
--     JET 07/29/88  ADDED CASES IN WHICH SUBPROGRAM PROFILES ARE NOT
--                   THE SAME AND ALSO WHEN SUBPROGRAM IS FIRST
--                   DECLARED WITHOUT A BODY.

WITH GENPROC_CA1020E;
PRAGMA ELABORATE (GENPROC_CA1020E);
PROCEDURE CA1020E_PROC1 IS NEW GENPROC_CA1020E(1);

WITH GENFUNC_CA1020E;
PRAGMA ELABORATE (GENFUNC_CA1020E);
FUNCTION CA1020E_FUNC1 IS NEW GENFUNC_CA1020E;

WITH GENPROC_CA1020E;
PRAGMA ELABORATE (GENPROC_CA1020E);
PROCEDURE CA1020E_PROC2 IS NEW GENPROC_CA1020E(5);

WITH GENFUNC_CA1020E;
PRAGMA ELABORATE (GENFUNC_CA1020E);
FUNCTION CA1020E_FUNC2 IS NEW GENFUNC_CA1020E;
