-- CA1020E0.ADA

-- OBJECTIVE:
--     CHECK THAT A SUBPROGRAM LIBRARY UNIT CAN BE REPLACED BY A GENERIC
--     INSTANTIATION HAVING THE SAME IDENTIFIER.  THIS FILE CONTAINS
--     GENERIC UNITS TO BE INSTANTIATED AS LIBRARY UNITS.

-- HISTORY:
--     JBG 05/28/85  CREATED ORIGINAL TEST.
--     JET 07/29/88  ADDED CASES IN WHICH SUBPROGRAM PROFILES ARE NOT
--                   THE SAME AND ALSO WHEN SUBPROGRAM IS FIRST
--                   DECLARED WITHOUT A BODY.

GENERIC
     C : INTEGER;
PROCEDURE GENPROC_CA1020E (X : OUT INTEGER);

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PROCEDURE GENPROC_CA1020E (X : OUT INTEGER) IS
BEGIN
     X := IDENT_INT(C);
END GENPROC_CA1020E;

GENERIC
FUNCTION GENFUNC_CA1020E RETURN INTEGER;

FUNCTION GENFUNC_CA1020E RETURN INTEGER IS
BEGIN
     RETURN 2;
END GENFUNC_CA1020E;
