-- CA1002A3M.ADA

-- CHECK THAT A SUBUNIT CAN HAVE THE SAME NAME AS A
-- LIBRARY UNIT OR AS AN IDENTIFIER DECLARED IN STANDARD.

-- SEPARATE FILES ARE:
--   CA1002A0  A LIBRARY PACKAGE SPECIFICATION (CA1002A0).
--   CA1002A1  A LIBRARY PACKAGE BODY (CA1002A0).
--   CA1002A2  A LIBRARY PROCEDURE BODY (CA1002A2).
--   CA1002A3M THE MAIN PROCEDURE.
--   CA1002A4  A SUBUNIT PACKAGE BODY (CA1002A0).
--   CA1002A5  A SUBUNIT PROCEDURE BODY (CA1002A2).
--   CA1002A6  A SUBUNIT PACKAGE BODY (ASCII).
--   CA1002A7  A SUBUNIT FUNCTION BODY (TRUE).
--   CA1002A8  A SUBUNIT PACKAGE BODY (TEXT_IO).
--   CA1002A9  A SUBUNIT FUNCTION BODY (UNCHECKED_CONVERSION).

-- ALGORITHM: SUBPROGRAM(S) (IN) SUBUNITS SHOULD BE INVOKED;
-- SUBPROGRAM(S) (IN) LIBRARY UNITS SHOULD NOT BE INVOKED.

-- JRK 5/12/81
-- SPS 11/9/82

WITH REPORT, CA1002A0, CA1002A2;
USE REPORT;

PROCEDURE CA1002A3M IS

     INVOKED : BOOLEAN;
     I : INTEGER;

     PACKAGE CALL_TEST IS
     END CALL_TEST;

     PACKAGE BODY CALL_TEST IS
     BEGIN
          TEST ("CA1002A", "SUBUNITS WITH THE SAME NAMES AS " &
                "LIBRARY UNITS AND NAMES IN STANDARD");
     END CALL_TEST;

     PACKAGE CA1002A0 IS
          PROCEDURE P;
     END CA1002A0;

     PACKAGE BODY CA1002A0 IS SEPARATE;

     PROCEDURE CA1002A2 IS SEPARATE;

     PACKAGE ASCII IS
          PROCEDURE P;
     END ASCII;

     PACKAGE BODY ASCII IS SEPARATE;

     FUNCTION TRUE (X : INTEGER) RETURN INTEGER IS SEPARATE;

     PACKAGE TEXT_IO IS
          FUNCTION LINE RETURN NATURAL;
     END TEXT_IO;

     PACKAGE BODY TEXT_IO IS SEPARATE;

     FUNCTION UNCHECKED_CONVERSION (S : INTEGER)
          RETURN INTEGER IS SEPARATE;

BEGIN

     INVOKED := FALSE;
     CA1002A0.P;
     IF NOT INVOKED THEN
          FAILED ("SUBUNIT CA1002A0.P NOT INVOKED");
     END IF;

     INVOKED := FALSE;
     CA1002A2;
     IF NOT INVOKED THEN
          FAILED ("SUBUNIT CA1002A2 NOT INVOKED");
     END IF;

     INVOKED := FALSE;
     ASCII.P;
     IF NOT INVOKED THEN
          FAILED ("SUBUNIT ASCII.P NOT INVOKED");
     END IF;

     INVOKED := FALSE;
     I := TRUE (-1);
     IF NOT INVOKED THEN
          FAILED ("SUBUNIT DURATION NOT INVOKED");
     END IF;

     INVOKED := FALSE;
     I := TEXT_IO.LINE;
     IF NOT INVOKED THEN
          FAILED ("SUBUNIT TEXT_IO.LINE NOT INVOKED");
     END IF;

     INVOKED := FALSE;
     I := UNCHECKED_CONVERSION (1);
     IF NOT INVOKED THEN
          FAILED ("SUBUNIT UNCHECKED_CONVERSION NOT INVOKED");
     END IF;

     RESULT;
END CA1002A3M;
