-- CA1105B3M.ADA

-- CHECK THAT A WITH_CLAUSE ASSOCIATED WITH A SUBUNIT CAN
--   NAME A LIBRARY UNIT SPECIFIED IN A WITH_CLAUSE OF
--   ANY ANCESTOR UNIT AS WELL AS THE ANCESTOR UNIT ITSELF.

-- SEPARATE FILES ARE:
--   CA1105B0  A LIBRARY PACKAGE.
--   CA1105B1  A LIBRARY PROCEDURE.
--   CA1105B2  A LIBRARY FUNCTION.
--   CA1105B3M THE MAIN PROCEDURE.
--   CA1105B4  A SUBUNIT PACKAGE BODY.
--   CA1105B5  A SUBUNIT PROCEDURE BODY.

-- WKB 6/23/81

WITH REPORT, CA1105B0;
USE REPORT;
PROCEDURE CA1105B3M IS

     PACKAGE CA1105B4 IS
          J : INTEGER := 0;
          PROCEDURE CA1105B5;
     END CA1105B4;

     PACKAGE BODY CA1105B4 IS SEPARATE;

BEGIN 
     TEST ("CA1105B", "CHECK THAT A WITH_CLAUSE ASSOCIATED WITH A " &
                      "SUBUNIT CAN NAME A LIBRARY UNIT SPECIFIED IN " &
                      "A WITH_CLAUSE OF ANY ANCESTOR UNIT");

     IF CA1105B0.I /= 0 THEN
          FAILED ("LIBRARY PACKAGE NOT ACCESSED - 1");
     END IF;

     IF CA1105B4.J /= 1 THEN
          FAILED ("LIBRARY PROCEDURE NOT INVOKED - 2");
     END IF;

     CA1105B4.CA1105B5;

     RESULT;
END CA1105B3M;
