-- CA1107A1M.ADA

-- CHECK THAT A NAME IN A WITH_CLAUSE OF A SUBUNIT REFERS
--   TO A LIBRARY UNIT RATHER THAN A LOCAL DECLARATION
--   WITHIN ONE OF ITS ANCESTORS, AND THAT THE LIBRARY UNIT
--   CAN BE ACCESSED VIA 'STANDARD.'.

-- SEPARATE FILES ARE:
--   CA1107A0  A LIBRARY PACKAGE.
--   CA1107A1M THE MAIN PROCEDURE.
--   CA1107A2  A SUBUNIT PROCEDURE BODY.

-- WKB 6/22/81

WITH REPORT;
USE REPORT;
PROCEDURE CA1107A1M IS

     PACKAGE CA1107A0 IS
          I : INTEGER := 2;
     END CA1107A0;

     PROCEDURE CA1107A2 IS SEPARATE;

BEGIN
     TEST ("CA1107A", "CHECK THAT A NAME IN A WITH_CLAUSE OF A " &
                      "SUBUNIT REFERS TO A LIBRARY UNIT RATHER THAN " &
                      "A LOCAL DECLARATION WITHIN ONE OF ITS " & 
                      "ANCESTORS");

     CA1107A2;

     RESULT;
END CA1107A1M;
