-- CA1102A2M.ADA

-- CHECK THAT MORE THAN ONE WITH_CLAUSE CAN APPEAR IN
--   A CONTEXT_SPECIFICATION.
-- CHECK THAT USE_CLAUSES CAN MENTION NAMES MADE
--   VISIBLE BY PRECEDING WITH_CLAUSES IN THE SAME
--   CONTEXT_SPECIFICATION.
-- CHECK THAT CONSECUTIVE USE_CLAUSES ARE ALLOWED.

-- SEPARATE FILES ARE:
--   CA1102A0  A LIBRARY PACKAGE DECLARATION.
--   CA1102A1  A LIBRARY PACKAGE BODY (CA1102A0).
--   CA1102A2M THE MAIN PROCEDURE.

-- WKB 6/12/81
-- BHS 7/19/84

WITH CA1102A0;
WITH REPORT; USE CA1102A0; USE REPORT;
PROCEDURE CA1102A2M IS


     INVOKED : BOOLEAN := FALSE;

BEGIN
     TEST ("CA1102A", "MORE THAN ONE WITH_CLAUSE; ALSO, A " &
           "USE_CLAUSE REFERING TO A PRECEDING WITH_CLAUSE " &
           "IN THE SAME CONTEXT_SPECIFICATION");

     P (INVOKED);
     IF NOT INVOKED THEN
          FAILED ("COMPILATION UNIT NOT MADE VISIBLE");
     END IF;

     RESULT;
END CA1102A2M;
