-- CA1106A.ADA

-- OBJECTIVE:
--     CHECK THAT A WITH CLAUSE FOR A PACKAGE BODY (GENERIC OR
--     NONGENERIC) OR FOR A GENERIC SUBPROGRAM BODY CAN NAME THE
--     CORRESPONDING SPECIFICATION, AND A USE CLAUSE CAN ALSO BE
--     GIVEN.

-- HISTORY:
--     JET 07/14/88  CREATED ORIGINAL TEST.

PACKAGE CA1106A_1 IS
     I : INTEGER := 0;
END CA1106A_1;

GENERIC
     TYPE TG IS RANGE <>;
PACKAGE CA1106A_2 IS
     J : TG := 0;
END CA1106A_2;

GENERIC
     TYPE TG IS RANGE <>;
FUNCTION CA1106A_3 RETURN TG;

WITH REPORT; USE REPORT;
WITH CA1106A_1; USE CA1106A_1;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY CA1106A_1 IS
BEGIN
     I := IDENT_INT(1);
END CA1106A_1;

WITH REPORT; USE REPORT;
WITH CA1106A_2;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY CA1106A_2 IS
BEGIN
     J := TG(IDENT_INT(2));
END CA1106A_2;

WITH REPORT; USE REPORT;
WITH CA1106A_3;
FUNCTION CA1106A_3 RETURN TG IS
BEGIN
     RETURN TG(IDENT_INT(3));
END CA1106A_3;

WITH REPORT; USE REPORT;
WITH CA1106A_1, CA1106A_2, CA1106A_3;
USE CA1106A_1;
PROCEDURE CA1106A IS

     PACKAGE CA1106A_2X IS NEW CA1106A_2 (INTEGER);
     FUNCTION CA1106A_3X IS NEW CA1106A_3 (INTEGER);

     USE CA1106A_2X;

BEGIN
     TEST ("CA1106A", "CHECK THAT A WITH CLAUSE FOR A PACKAGE BODY " &
                      "(GENERIC OR NONGENERIC) OR FOR A GENERIC " &
                      "SUBPROGRAM BODY CAN NAME THE CORRESPONDING " &
                      "SPECIFICATION, AND A USE CLAUSE CAN ALSO BE " &
                      "GIVEN");

     IF I /= 1 THEN
          FAILED ("INCORRECT VALUE FROM NONGENERIC PACKAGE");
     END IF;

     IF J /= 2 THEN
          FAILED ("INCORRECT VALUE FROM GENERIC PACKAGE");
     END IF;

     IF CA1106A_3X /= 3 THEN
          FAILED ("INCORRECT VALUE FROM GENERIC SUBPROGRAM");
     END IF;

     RESULT;
END CA1106A;
