-- CA2002A1.ADA

-- SUBUNIT BODIES FOR STUBS GIVEN IN PACKAGE CA2002A1 IN FILE
-- CA2002A0M. 

-- BHS 8/02/84

SEPARATE (CA2002A1)
PROCEDURE PROC (X : OUT INTEGER) IS
BEGIN
     X := 1;
END PROC;

SEPARATE (CA2002A1)
FUNCTION FUN RETURN BOOLEAN IS
BEGIN
     RETURN TRUE;
END FUN;

SEPARATE (CA2002A1)
PACKAGE BODY PKG IS
     PROCEDURE PKG_PROC (XX : IN OUT INTEGER) IS SEPARATE;
BEGIN
     I := 1;
END PKG;

SEPARATE (CA2002A1.PKG)
PROCEDURE PKG_PROC (XX : IN OUT INTEGER) IS
BEGIN
     XX := XX - 1;
END PKG_PROC;
