-- CA2001H3M.ADA

-- CHECK THAT IF A BODY_STUB IS DELETED FROM A COMPILATION UNIT,
--   THE PREVIOUSLY EXISTING SUBUNIT CAN NO LONGER BE ACCESSED.

-- SEPARATE FILES ARE;
--   CA2001H0  A LIBRARY FUNCTION (CA2001H0).
--   CA2001H1  A SUBUNIT PACKAGE BODY.
--   CA2001H2  A LIBRARY FUNCTION (CA2001H0).
--   CA2001H3M THE MAIN PROCEDURE.

-- WKB 6/25/81
-- JRK 6/26/81
-- SPS 11/2/82
-- JBG 8/25/83


WITH REPORT, CA2001H0;
USE REPORT;
PROCEDURE CA2001H3M IS

     I : INTEGER := -1;

BEGIN
     TEST ("CA2001H", "IF A BODY_STUB IS DELETED FROM A COMPILATION " &
                      "UNIT, THE PREVIOUSLY EXISTING SUBUNIT CAN NO " &
                      "LONGER BE ACCESSED");

     I := CA2001H0;

     IF I = 1 THEN
          FAILED ("SUBUNIT ACCESSED");
     END IF;

     IF I = 0 THEN
          FAILED ("OLD LIBRARY UNIT ACCESSED");
     END IF;

     IF I /= 2 THEN
          FAILED ("NEW LIBRARY UNIT NOT ACCESSED");
     END IF;

     RESULT;
END CA2001H3M;
