-- CA2007A0M.ADA

-- CHECK THAT SUBUNIT PACKAGES ARE ELABORATED IN THE ORDER IN
--   WHICH THEIR BODY STUBS APPEAR, NOT (NECESSARILY) IN THE
--   ORDER IN WHICH THEY ARE COMPILED.

-- SEPARATE FILES ARE:
--   CA2007A0M THE MAIN PROCEDURE.
--   CA2007A1  A SUBUNIT PACKAGE BODY.
--   CA2007A2  A SUBUNIT PACKAGE BODY.
--   CA2007A3  A SUBUNIT PACKAGE BODY.

-- WKB 7/1/81
-- JRK 7/1/81

WITH REPORT;
USE REPORT;
PROCEDURE CA2007A0M IS

     ELAB_ORDER : STRING (1..3) := "   ";
     NEXT : NATURAL := 1;

     PACKAGE CALL_TEST IS 
     END CALL_TEST;

     PACKAGE BODY CALL_TEST IS
     BEGIN
          TEST ("CA2007A", "CHECK THAT SUBUNIT PACKAGES ARE " &
                           "ELABORATED IN THE ORDER IN WHICH THEIR " &
                           "BODY STUBS APPEAR");
     END CALL_TEST;

     PACKAGE CA2007A3 IS
     END CA2007A3;

     PACKAGE BODY CA2007A3 IS SEPARATE;

     PACKAGE CA2007A2 IS
     END CA2007A2;

     PACKAGE BODY CA2007A2 IS SEPARATE;

     PACKAGE CA2007A1 IS
     END CA2007A1;

     PACKAGE BODY CA2007A1 IS SEPARATE;

BEGIN

     IF ELAB_ORDER /= "321" THEN
          FAILED ("INCORRECT ELABORATION ORDER");
     END IF;

     RESULT;
END CA2007A0M;
