-- CA2003A0M.ADA

-- CHECK THAT A SUBUNIT HAS VISIBILITY OF IDENTIFIERS DECLARED
--   PRIOR TO ITS BODY_STUB.

-- SEPARATE FILES ARE:
--   CA2003A0M THE MAIN PROCEDURE.
--   CA2003A1  A SUBUNIT PROCEDURE BODY.

-- WKB 6/26/81
-- JRK 6/26/81

WITH REPORT;
USE REPORT;
PROCEDURE CA2003A0M IS

     I : INTEGER := 1;

     PROCEDURE CA2003A1 IS SEPARATE;

     PACKAGE P IS
          I : INTEGER := 2;
     END P;

BEGIN
     TEST ("CA2003A", "A SUBUNIT HAS VISIBILITY OF IDENTIFIERS " &
                      "DECLARED BEFORE ITS BODY_STUB");


     CA2003A1;

     RESULT;
END CA2003A0M;
