-- CA2008A0M.ADA

-- CHECK THAT FOR AN OVERLOADED SUBPROGRAM, ONE OF THE
--   SUBPROGRAM BODIES CAN BE SPECIFIED WITH A BODY_STUB AND
--   COMPILED SEPARATELY.

-- SEPARATE FILES ARE:
--   CA2008A0M THE MAIN PROCEDURE.
--   CA2008A1  A SUBUNIT PROCEDURE BODY.
--   CA2008A2  A SUBUNIT FUNCTION BODY.

-- WKB 6/26/81
-- SPS 11/2/82

WITH REPORT;
USE REPORT;
PROCEDURE CA2008A0M IS

     I : INTEGER := 0;
     B : BOOLEAN := TRUE;

     PROCEDURE CA2008A1 (I : IN OUT INTEGER) IS
     BEGIN
          I := IDENT_INT (1);
     END CA2008A1;

     PROCEDURE CA2008A1 (B : IN OUT BOOLEAN) IS SEPARATE;

     FUNCTION CA2008A2 RETURN INTEGER IS SEPARATE;

     FUNCTION CA2008A2 RETURN BOOLEAN IS
     BEGIN
          RETURN IDENT_BOOL (FALSE);
     END CA2008A2;

BEGIN
     TEST ("CA2008A", "CHECK THAT AN OVERLOADED SUBPROGRAM " &
                      "CAN HAVE ONE OF ITS BODIES COMPILED SEPARATELY");

     CA2008A1 (I);
     IF I /= 1 THEN
          FAILED ("OVERLOADED PROCEDURE NOT INVOKED - 1");
     END IF;

     CA2008A1 (B);
     IF B THEN
          FAILED ("OVERLOADED PROCEDURE NOT INVOKED - 2");
     END IF;

     IF CA2008A2 /= 2 THEN
          FAILED ("OVERLOADED FUNCTION NOT INVOKED - 1");
     END IF;

     IF CA2008A2 THEN
          FAILED ("OVERLOADED FUNCTION NOT INVOKED - 2");
     END IF;

     RESULT;
END CA2008A0M;
