-- CA2002A2.ADA

-- SUBUNIT BODIES FOR STUBS GIVEN IN PACKAGE CA2002A2 IN FILE
-- CA2002A0M. 

-- BHS 8/02/84

SEPARATE (CA2002A2)
PROCEDURE PROC (Y : OUT INTEGER) IS
BEGIN
     Y := 2;
END PROC;

SEPARATE (CA2002A2)
FUNCTION FUN (Z : INTEGER := 3) RETURN BOOLEAN IS
BEGIN
     RETURN Z /= 3;
END FUN;

SEPARATE (CA2002A2)
PACKAGE BODY PKG IS
     PROCEDURE PKG_PROC (YY : IN OUT INTEGER) IS SEPARATE;
BEGIN
     I := 2;
END PKG;

SEPARATE (CA2002A2.PKG)
PROCEDURE PKG_PROC (YY : IN OUT INTEGER) IS
BEGIN
     YY := YY + 1;
END PKG_PROC;
