-- CA3006C5M.ADA

-- CHECK THAT IF A PACKAGE SPECIFICATION IS SUBSTANTIVELY MODIFIED,
--   AND THE NEW PACKAGE SPECIFICATION DOES NOT CONTAIN DECLARATIONS
--   THAT REQUIRE BODIES, THEN NO NEW PACKAGE BODY IS REQUIRED
--   AND THE OLD BODY IS DELETED.

-- SEPARATE FILES ARE:
--   CA3006C0  A LIBRARY PACKAGE DECLARATION (CA3006C0).
--   CA3006C1  A LIBRARY PACKAGE BODY (CA3006C0).
--   CA3006C2  A LIBRARY FUNCTION (CA3006C2).
--   CA3006C3  A LIBRARY PACKAGE DECLARATION (CA3006C0).
--   CA3006C4  A LIBRARY FUNCTION (CA3006C2).
--   CA3006C5M THE MAIN PROCEDURE.

-- JRK 8/11/81
-- SPS 11/2/82
-- JBG 8/25/83

WITH REPORT, CA3006C2;
USE REPORT;
PROCEDURE CA3006C5M IS

BEGIN
     TEST ("CA3006C", "SUBSTANTIVELY MODIFYING A SEPARATELY " &
                      "COMPILED PACKAGE DECLARATION THAT NOW " &
                      "NEEDS NO BODY REQUIRES DELETION OF THE " &
                      "OLD BODY");

     IF CA3006C2 /= -3 THEN
          FAILED ("OLD PACKAGE BODY NOT DELETED");
     END IF;

     RESULT;
END CA3006C5M;
