-- CA3004F4M.ADA

-- CHECK THAT, IF THE BODY OF AN INLINE FUNCTION IS MODIFIED,
-- AN OPTIONAL PACKAGE BODY CALLING THAT FUNCTION AS AN INLINE
-- FUNCTION BECOMES OBSOLETE AND THE MAIN PROGRAM IS EXECUTABLE
-- USING ONLY THE PACKAGE DECLARATION.

-- SEPARATE FILES ARE:
--   CA3004F0  A LIBRARY FUNCTION DECLARATION (CA3004F0).
--   CA3004F1  A LIBRARY FUNCTION BODY (CA3004F0).
--   CA3004F2  A LIBRARY PACKAGE DECL AND BODY.
--   CA3004F3  A LIBRARY FUNCTION BODY (CA3004F0).
--   CA3004F4M THE MAIN PROCEDURE.

-- IF THE INLINE PRAGMA IS SUPPORTED FOR FUNCTIONS, THEN THIS TEST
--   SHOULD EXECUTE AND GIVE A PASSED RESULT.
-- OTHERWISE, THIS TEST SHOULD EXECUTE AND GIVE A NOT-APPLICABLE RESULT.

-- WKB 07/13/81
-- EG  06/05/84
-- JRK 5/21/85

WITH REPORT; USE REPORT;
WITH CA3004F2;

PROCEDURE CA3004F4M IS
BEGIN
     TEST ("CA3004F", "MODIFYING THE BODY OF AN INLINE FUNCTION " &
                      "MAKES A CALLING OPTIONAL PACKAGE BODY " &
                      "OBSOLETE, YET ALLOWS EXECUTION");

     CASE CA3004F2.I IS
          WHEN 2 =>
               COMMENT ("INLINE PRAGMA OBEYED; CALLING PACKAGE " &
                        "BODY MADE OBSOLETE");
          WHEN 3 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PACKAGE " &
                       "BODY NOT MADE OBSOLETE");
          WHEN 7 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PACKAGE BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PACKAGE");
     END CASE;

     RESULT;
END CA3004F4M;
