-- CA3004E4M.ADA

-- CHECK THAT, IF THE BODY OF AN INLINE PROCEDURE IS MODIFIED,
-- AN OPTIONAL PACKAGE BODY CALLING THAT PROCEDURE AS AN INLINE
-- PROCEDURE BECOMES OBSOLETE AND THE MAIN PROGRAM IS EXECUTABLE
-- USING ONLY THE PACKAGE DECLARATION.

-- SEPARATE FILES ARE:
--   CA3004E0  A LIBRARY PACKAGE DECLARATION (CA3004E0).
--   CA3004E1  A LIBRARY PACKAGE BODY (CA3004E0).
--   CA3004E2  A LIBRARY PACKAGE DECL AND BODY.
--   CA3004E3  A LIBRARY PACKAGE BODY (CA3004E0).
--   CA3004E4M THE MAIN PROCEDURE.

-- IF THE INLINE PRAGMA IS SUPPORTED FOR PROCEDURES, THEN THIS TEST
--   SHOULD EXECUTE AND GIVE A PASSED RESULT.
-- OTHERWISE, THIS TEST SHOULD EXECUTE AND GIVE A NOT-APPLICABLE RESULT.

-- WKB 07/13/81
-- EG  06/05/84
-- JRK 5/21/85

WITH REPORT; USE REPORT;
WITH CA3004E2;

PROCEDURE CA3004E4M IS
BEGIN
     TEST ("CA3004E", "MODIFYING THE BODY OF AN INLINE " &
                      "PROCEDURE MAKES A CALLING OPTIONAL " &
                      "PACKAGE BODY OBSOLETE, YET ALLOWS " &
                      "EXECUTION");

     CASE CA3004E2.I IS
          WHEN 2 =>
               COMMENT ("INLINE PRAGMA OBEYED; CALLING PACKAGE " &
                        "BODY MADE OBSOLETE");
          WHEN 3 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PACKAGE " &
                       "BODY NOT MADE OBSOLETE");
          WHEN 7 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PACKAGE BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PACKAGE");
     END CASE;

     RESULT;
END CA3004E4M;
