-- CA3002A2M.ADA

-- CHECK THAT A UNIT CAN BE COMPILED IF A PACKAGE IT USES HAS BEEN
--   RECOMPILED BUT THE CORRESPONDING PACKAGE BODY HAS NOT BEEN
--   RECOMPILED, EVEN IF THE UNIT USES A SUBPROGRAM (DECLARED IN THE
--   PACKAGE SPECIFICATION AND) DEFINED IN THE YET-TO-BE RECOMPILED
--   BODY.

-- SEPARATE FILES ARE:
--   CA3002A0  A LIBRARY PACKAGE (CA3002A0).
--   CA3002A1  A LIBRARY PACKAGE SPECIFICATION (CA3002A0).
--   CA3002A2M THE MAIN PROCEDURE.
--   CA3002A3  A LIBRARY PACKAGE BODY (CA3002A0).

-- WKB 7/1/81
-- JRK 7/2/81
-- SPS 11/2/82

WITH REPORT, CA3002A0;
USE REPORT;
PROCEDURE CA3002A2M IS

BEGIN
     TEST("CA3002A", "COMPILING A UNIT BEFORE REQUIRED RECOMPILATION " &
                     "OF USED PACKAGE BODY");

     IF CA3002A0.I /= 1 THEN
          FAILED ("USED WRONG PACKAGE SPECIFICATION");
     END IF;

     IF CA3002A0.F THEN
          FAILED ("USED WRONG PACKAGE BODY");
     END IF;

     RESULT;
END CA3002A2M;
