-- CA3006D3M.ADA

-- CHECK THAT AN OPTIONAL PACKAGE BODY IS NO LONGER USED AFTER
-- RECOMPILING A UNIT NAMED IN THE BODY'S CONTEXT CLAUSE.

-- SEPARATE FILES ARE:
--     CA3006D0   A LIBRARY PACKAGE DECLARATION.
--     CA3006D1   A LIBRARY PACKAGE DECL AND BODY.
--     CA3006D2   A LIBRARY PACKAGE DECLARATION (CA3006D0).
--     CA3006D3M  THE MAIN PROCEDURE.

-- BHS 8/13/84
-- JRK 12/7/84

WITH REPORT, CA3006D1;
USE REPORT, CA3006D1;
PROCEDURE CA3006D3M IS
BEGIN

     TEST ("CA3006D", "AN OPTIONAL PACKAGE BODY IS NO LONGER " &
                      "USED AFTER RECOMPILING A UNIT NAMED IN " &
                      "ITS CONTEXT CLAUSE");

     IF J /= 2 THEN
          FAILED ("OLD OPTIONAL BODY USED");
     END IF;

     RESULT;

END CA3006D3M;
