-- CA3006E6M.ADA

-- CHECK THAT IF A PACKAGE BODY WAS PROVIDED FOR A PACKAGE DECLARATION
-- THAT DECLARES A TASK OBJECT BUT DOES NOT REQUIRE A BODY, AND IF THE
-- DECLARATION IS MODIFIED BUT STILL DOES NOT REQUIRE A BODY, THEN THE
-- ORIGINAL BODY IS NO LONGER USED.

-- SEPARATE FILES ARE:
--     CA3006E0   A LIBRARY PACKAGE (CA3006E_TASK).
--     CA3006E1   A LIBRARY PACKAGE DECLARATION.
--     CA3006E2   A LIBRARY PACKAGE BODY (CA3006E1).
--     CA3006E3   A LIBRARY FUNCTION.
--     CA3006E4   A LIBRARY PACKAGE DECLARATION (CA3006E1).
--     CA3006E5   A LIBRARY FUNCTION (CA3006E3).
--     CA3006E6M  THE MAIN PROCEDURE.

-- BHS 8/13/84
-- JRK 12/7/84

WITH REPORT, CA3006E3;
USE REPORT;
PROCEDURE CA3006E6M IS
BEGIN

     TEST ("CA3006E", "SUBSTANTIVELY MODIFYING A PACKAGE " &
                      "DECLARATION THAT DECLARES A TASK OBJECT BUT " &
                      "NEEDS NO BODY REQUIRES DELETION OF THE OLD " &
                      "BODY");

     IF CA3006E3 /= -5 THEN
          FAILED ("OLD BODY NOT DELETED");
     END IF;

     RESULT;

END CA3006E6M;
