-- CA3009A6.ADA

-- OBJECTIVE:
--     CHECK THAT WHEN COMPILING A SUBPROGRAM LIBRARY UNIT BODY OR
--     DECLARATION, NO DECLARATION IS ADDED TO THE LIBRARY IF AN
--     ERROR IS FOUND.

-- SEPARATE FILES ARE:
--     CA3009A0.ADA - SPECIFICATION FOR CA3009A_FUNC.
--     CA3009A1.ADA - ERRONEOUS SPEC FOR CA3009A_FUNC.
--     CA3009A2.ADA - BODY FOR CA3009A_FUNC.
--     CA3009A3.ADA - SPECIFICATION FOR CA3009A_PROC.
--     CA3009A4.ADA - BODY FOR CA3009A_PROC.
--     CA3009A5.ADA - ERRONEOUS BODY FOR CA3009A_PROC.
--     CA3009A6M.ADA - MAIN PROCEDURE.

-- HISTORY:
--     JET 07/14/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH CA3009A_FUNC, CA3009A_PROC;
PROCEDURE CA3009A6M IS

     I : INTEGER := 2;
     J : INTEGER := 3;

BEGIN
     TEST ("CA3009A", "CHECK THAT WHEN COMPILING A SUBPROGRAM " &
                      "LIBRARY UNIT BODY OR DECLARATION, NO " &
                      "DECLARATION IS ADDED TO THE LIBRARY IF AN " &
                      "ERROR IS FOUND");

     IF CA3009A_FUNC(X => 1) /= 1 THEN
          FAILED ("ORIGINAL FUNCTION SPEC WAS REPLACED BY ERRONEOUS " &
                  "ONE");
     END IF;

     CA3009A_PROC(I, J);
     IF I /= 2 THEN
          FAILED ("ORIGINAL PROCEDURE BODY WAS REPLACED BY ERRONEOUS " &
                  "ONE");
     END IF;

     RESULT;
END CA3009A6M;
