-- CA3009A5.ADA

-- OBJECTIVE:
--     CHECK THAT WHEN COMPILING A SUBPROGRAM LIBRARY UNIT BODY OR
--     DECLARATION, NO DECLARATION IS ADDED TO THE LIBRARY IF AN
--     ERROR IS FOUND.

-- SEPARATE FILES ARE:
--     CA3009A0.ADA - SPECIFICATION FOR CA3009A_FUNC.
--     CA3009A1.ADA - ERRONEOUS SPEC FOR CA3009A_FUNC.
--     CA3009A2.ADA - BODY FOR CA3009A_FUNC.
--     CA3009A3.ADA - SPECIFICATION FOR CA3009A_PROC.
--     CA3009A4.ADA - BODY FOR CA3009A_PROC.
--     CA3009A5.ADA - ERRONEOUS BODY FOR CA3009A_PROC.
--     CA3009A6M.ADA - MAIN PROCEDURE.

-- HISTORY:
--     JET 07/14/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CA3009A_PROC (X, Y : IN OUT INTEGER) IS
     Z : FOOEY;                              -- ERROR: FOOEY UNDECLARED.
BEGIN
     X := IDENT_INT(Y);
END CA3009A_PROC;
