-- CA5005A.ADA

-- OBJECTIVE:
--     CHECK WHETHER AN IMPLEMENTATION ELABORATES LIBRARY SUBPROGRAM
--     BODIES AS SOON AS POSSIBLE AFTER THE ELABORATION OF THEIR
--     SPECIFICATION, OR WHETHER IT DEFERS ELABORATION UNTIL AS LATE
--     AS POSSIBLE.

-- HISTORY:
--     JET 07/14/88  CREATED ORIGINAL TEST.

PACKAGE CA5005A_2 IS
END CA5005A_2;

FUNCTION CA5005A_1 RETURN INTEGER;

WITH REPORT; USE REPORT;
WITH CA5005A_1;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY CA5005A_2 IS
BEGIN
     TEST ("CA5005A", "CHECK WHETHER AN IMPLEMENTATION ELABORATES " &
                      "LIBRARY SUBPROGRAM BODIES AS SOON AS POSSIBLE " &
                      "AFTER THE ELABORATION OF THEIR SPECIFICATION, " &
                      "OR WHETHER IT DEFERS ELABORATION UNTIL AS " &
                      "LATE AS POSSIBLE");

     IF CA5005A_1 /= 1 THEN
          FAILED ("INCORRECT RETURN VALUE");
     ELSE
          COMMENT ("ELABORATION IS PERFORMED AS SOON AS POSSIBLE");
     END IF;

EXCEPTION
     WHEN PROGRAM_ERROR =>
          COMMENT ("ELABORATION IS PERFORMED AS LATE AS POSSIBLE");
     WHEN OTHERS =>
          FAILED ("UNEXPECTED EXCEPTION");
END CA5005A_2;

WITH REPORT; USE REPORT;
WITH CA5005A_2;
PROCEDURE CA5005A IS
BEGIN
     RESULT;
END CA5005A;

WITH REPORT; USE REPORT;
FUNCTION CA5005A_1 RETURN INTEGER IS
BEGIN
     RETURN IDENT_INT(1);
END CA5005A_1;
