-- CA5003B5M.ADA

-- CHECK THAT THE ELABORATION OF LIBRARY UNITS REQUIRED BY
--   A MAIN PROGRAM IS PERFORMED CONSISTENTLY WITH THE PARTIAL
--   ORDERING DEFINED BY THE COMPILATION ORDER RULES.
-- IN PARTICULAR, CHECK THAT A LIBRARY UNIT MENTIONED IN THE
--   WITH_CLAUSE OF A SUBUNIT IS ELABORATED PRIOR TO THE BODY OF 
--   THE ANCESTOR UNIT.

-- SEPARATE FILES ARE:
--   CA5003B0  A LIBRARY PACKAGE.
--   CA5003B1  A LIBRARY PACKAGE.
--   CA5003B2  A SUBUNIT PACKAGE BODY (_B1._B2).
--   CA5003B3  A LIBRARY PACKAGE DECLARATION.
--   CA5003B4  A SUBUNIT PACKAGE BODY (_B1._B2._B4).
--   CA5003B5M THE MAIN PROCEDURE.

-- LIBRARY PACKAGES MUST BE ELABORATED IN ORDER: _B0, _B3, _B1.
-- PARENT UNITS MUST BE ELABORATED BEFORE THEIR SUBUNITS.

-- WKB 7/22/81
-- JBG 10/6/83
-- BHS 8/02/84
-- JRK 9/20/84

WITH REPORT, CA5003B0;
USE REPORT, CA5003B0;
WITH CA5003B1;
PROCEDURE CA5003B5M IS

BEGIN
     TEST ("CA5003B", "CHECK THAT UNITS IN WITH_CLAUSES OF " &
                      "SUBUNITS ARE ELABORATED PRIOR TO THE " &
                      "BODY OF THE ANCESTOR UNIT");

     COMMENT ("ACTUAL ELABORATION ORDER WAS " & ORDER);

     IF ORDER /= "3124" THEN
          FAILED ("ILLEGAL ELABORATION ORDER");
     END IF;

     RESULT;
END CA5003B5M;
