-- CA5004A.ADA

-- CHECK THAT IF PRAGMA ELABORATE IS APPLIED TO A PACKAGE THAT DECLARES
-- A TASK OBJECT, THE IMPLICIT PACKAGE BODY IS ELABORATED AND THE TASK
-- IS ACTIVATED.

-- BHS 8/03/84
-- JRK 9/20/84


PACKAGE CA5004A0 IS

     TASK TYPE TSK IS
          ENTRY E (VAR : OUT INTEGER);
     END TSK;

END CA5004A0;


PACKAGE BODY CA5004A0 IS

     TASK BODY TSK IS
     BEGIN
          ACCEPT E (VAR : OUT INTEGER) DO
               VAR := 4;
          END E;
     END TSK;

END CA5004A0;


WITH CA5004A0; USE CA5004A0; PRAGMA ELABORATE (CA5004A0);
PACKAGE CA5004A1 IS

     T : TSK;

END CA5004A1;


PACKAGE CA5004A2 IS
END CA5004A2;


WITH REPORT; USE REPORT;
WITH CA5004A1; USE CA5004A1;
PRAGMA ELABORATE (CA5004A1, REPORT);
PACKAGE BODY CA5004A2 IS

     I : INTEGER := 1;

BEGIN

     TEST ("CA5004A", "APPLYING PRAGMA ELABORATE TO A PACKAGE " &
                      "DECLARING A TASK OBJECT CAUSES IMPLICIT " &
                      "BODY ELABORATION AND TASK ACTIVATION");

     SELECT
          T.E(I);
          IF I /= 4 THEN
               FAILED ("TASK NOT EXECUTED PROPERLY");
          END IF;
     OR
          DELAY 10.0;
          FAILED ("TASK NOT ACTIVATED AFTER 10 SECONDS");
     END SELECT;

END CA5004A2;


WITH CA5004A2;
WITH REPORT; USE REPORT;
PROCEDURE CA5004A IS
BEGIN

     RESULT;

END CA5004A;
