-- CA5003A0.ADA

-- WKB 7/22/81
-- JBG 10/6/83

PACKAGE CA5003A0 IS

     ORDER : STRING (1..5) := "     ";

     INDEX : NATURAL := 1;

     FUNCTION SHOW_ELAB (UNIT : CHARACTER) RETURN INTEGER;

END CA5003A0;


WITH REPORT;
USE REPORT;
PACKAGE BODY CA5003A0 IS

     FUNCTION SHOW_ELAB (UNIT : CHARACTER) RETURN INTEGER IS
     BEGIN
          ORDER (INDEX) := UNIT;
          INDEX := INDEX + 1;
          RETURN INDEX - 1;
     END SHOW_ELAB;

END CA5003A0;
