-- CB1002A.ADA

-- FOR EACH OF THE PREDEFINED EXCEPTIONS, CHECK THAT THE NAME
--    IS NOT A RESERVED WORD.

-- DCB 03/26/80
-- JRK 11/17/80
-- SPS 3/23/83

WITH REPORT;
PROCEDURE CB1002A IS

     USE REPORT;

     INDEX : INTEGER := 0;

     CONSTRAINT_ERROR,
     NUMERIC_ERROR,
     PROGRAM_ERROR,
     STORAGE_ERROR,
     TASKING_ERROR : INTEGER := 1;

BEGIN
     TEST("CB1002A","CHECK THAT NAMES OF PREDEFINED EXCEPTIONS" &
          " ARE NOT RESERVED WORDS");

     INDEX := CONSTRAINT_ERROR +
              NUMERIC_ERROR +
              PROGRAM_ERROR +
              STORAGE_ERROR +
              TASKING_ERROR;


     IF INDEX /= 5 THEN
          FAILED("INDEX VALUE IS INCORRECT");
     END IF;

     RESULT;
END CB1002A;
