-- CB1003A.ADA

-- OBJECTIVE:
--     CHECK THAT A PROGRAMMER-DEFINED EXCEPTION HAVING THE SAME NAME AS
--     A PREDEFINED EXCEPTION IS DISTINCT FROM THE PREDEFINED EXCEPTION.

-- HISTORY:
--     DCB 03/30/80
--     JRK 11/17/80
--     SPS 03/23/83
--     JET 01/06/87  UPDATED HEADER FORMAT AND ADDED CODE TO
--                   PREVENT OPTIMIZATION.

WITH REPORT;
PROCEDURE CB1003A IS

     USE REPORT;

     FLOW_COUNT : INTEGER := 0;

BEGIN
     TEST("CB1003A","CHECK THAT A PROGRAMMER-DEFINED EXCEPTION AND A" &
          " PREDEFINED EXCEPTION THAT HAS THE SAME NAME ARE DISTINCT");

     BEGIN

          DECLARE
               CONSTRAINT_ERROR : EXCEPTION;
               I8 : INTEGER RANGE 1..10 ;
          BEGIN
               FLOW_COUNT := FLOW_COUNT + 1;
               I8 := IDENT_INT(20); -- PREDEFINED EXCEPTION RAISED HERE.
               FAILED("PREDEFINED CONSTRAINT_ERROR NOT RAISED FOR " &
                      "RANGE ERROR");
               IF NOT EQUAL(I8,I8) THEN
                    COMMENT ("NO EXCEPTION RAISED");
               END IF;

          EXCEPTION
               WHEN CONSTRAINT_ERROR =>  -- HANDLER FOR USER-DEFINED
                                         -- EXCEPTION.
                    FAILED("PREDEFINED AND PROGRAMMER-DEFINED" &
                           " EXCEPTIONS NOT DISTINCT");
               WHEN OTHERS =>
                    FLOW_COUNT := FLOW_COUNT + 1;
                    RAISE;           -- PASS EXCEPTION TO OUTER SCOPE.
                    FAILED("EXCEPTION NOT RERAISED");
          END;

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>   -- PREDEFINED EXCEPTION.
               FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED");
     END;

     IF FLOW_COUNT /= IDENT_INT(3) THEN
          FAILED("INCORRECT FLOW_COUNT VALUE");
     END IF;

     RESULT;

EXCEPTION
     WHEN CONSTRAINT_ERROR =>
          FAILED("EXCEPTION RAISED IN WRONG SCOPE");
          RESULT;
     WHEN OTHERS =>
          FAILED("WRONG EXCEPTION RAISED IN WRONG SCOPE");
          RESULT;

END CB1003A;
