-- CB1004A.ADA

-- CHECK THAT EXCEPTIONS DECLARED IN RECURSIVE PROCEDURES ARE NOT
--    REPLICATED ANEW FOR EACH RECURSIVE ACTIVATION OF THE PROCEDURE.

-- DCB 03/30/80
-- JRK 11/17/80
-- SPS 3/23/83

WITH REPORT;
PROCEDURE CB1004A IS

     USE REPORT;

     FLOW_COUNT : INTEGER := 0;

     PROCEDURE P1(SWITCH1 : IN INTEGER) IS

          E1 : EXCEPTION;

          PROCEDURE P2 IS

          BEGIN
               FLOW_COUNT := FLOW_COUNT + 1;   -- 3
               P1(2);
               FAILED("EXCEPTION NOT PROPAGATED");

          EXCEPTION
               WHEN E1 =>
                    FLOW_COUNT := FLOW_COUNT + 1;   -- 6
               WHEN OTHERS =>
                    FAILED("WRONG EXCEPTION RAISED");
          END P2;

     BEGIN
          FLOW_COUNT := FLOW_COUNT + 1;   -- 2   -- 4
          IF SWITCH1 = 1 THEN
               P2;
          ELSIF SWITCH1 = 2 THEN
               FLOW_COUNT := FLOW_COUNT + 1;   -- 5
               RAISE E1;
               FAILED("EXCEPTION NOT RAISED");
          END IF;
     END P1;

BEGIN
     TEST("CB1004A","CHECK THAT EXCEPTIONS ARE NOT RECURSIVELY " &
                    "REPLICATED");

     FLOW_COUNT := FLOW_COUNT + 1;   -- 1
     P1(1);

     IF FLOW_COUNT /= 6 THEN
          FAILED("INCORRECT FLOW_COUNT VALUE");
     END IF;

     RESULT;

EXCEPTION
     WHEN OTHERS =>
          FAILED("EXCEPTION HANDLED IN WRONG SCOPE");
          RESULT;
END CB1004A;
