-- CB1010B.ADA

-- CHECK THAT STORAGE_ERROR IS RAISED WHEN STORAGE FOR ALLOCATED OBJECTS
-- IS EXCEEDED.

-- JRK 8/30/85

WITH REPORT; USE REPORT;

PROCEDURE CB1010B IS

     TYPE BIG_SPACE IS ARRAY (1 .. 1000) OF INTEGER;

     TYPE ELEMENT;

     TYPE LINK IS ACCESS ELEMENT;

     TYPE ELEMENT IS
          RECORD
               NEXT : LINK;
               DATA : BIG_SPACE;
          END RECORD;

     HEAD : LINK;
     TEMP : LINK;

BEGIN
     TEST ("CB1010B", "CHECK THAT STORAGE_ERROR IS RAISED WHEN " &
                      "STORAGE FOR ALLOCATED OBJECTS IS EXCEEDED");

     BEGIN

          LOOP
               TEMP := NEW ELEMENT;
               TEMP.NEXT := HEAD;
               HEAD := TEMP;
          END LOOP;

          FAILED ("NO EXCEPTION RAISED BY HEAP OVERFLOW");

     EXCEPTION
          WHEN STORAGE_ERROR =>
               IF HEAD = NULL THEN
                    FAILED ("UNABLE TO ALLOCATE ANYTHING");
               END IF;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED BY HEAP OVERFLOW");
     END;

     RESULT;
END CB1010B;
