-- CB1001A.ADA

-- CHECK THAT ALL PREDEFINED EXCEPTIONS MAY BE RAISED EXPLICITLY
--    AND MAY HAVE HANDLERS WRITTEN FOR THEM.

-- DCB 03/25/80
-- JRK 11/17/80
-- SPS 11/2/82

WITH REPORT;
PROCEDURE CB1001A IS

     USE REPORT;

     FLOW_COUNT : INTEGER := 0;

BEGIN
     TEST("CB1001A", "CHECK THAT ALL PREDEFINED EXCEPTIONS MAY BE " &
          "RAISED EXPLICITLY AND MAY HAVE HANDLERS WRITTEN FOR THEM");

     BEGIN
          RAISE CONSTRAINT_ERROR;
          FAILED("NO EXCEPTION RAISED WHEN CONSTRAINT_ERROR EXPECTED");

     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED WHEN CONSTRAINT_ERROR " &
                      "EXPECTED");
     END;

     BEGIN
          RAISE NUMERIC_ERROR;
          FAILED("NO EXCEPTION RAISED WHEN NUMERIC_ERROR EXPECTED");

     EXCEPTION
          WHEN NUMERIC_ERROR =>
               FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED WHEN NUMERIC_ERROR " &
                      "EXPECTED");
     END;

     BEGIN
          RAISE PROGRAM_ERROR;
          FAILED("NO EXCEPTION RAISED WHEN PROGRAM_ERROR EXPECTED");
     EXCEPTION
          WHEN PROGRAM_ERROR =>
               FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED WHEN PROGRAM_ERROR " &
                      "EXPECTED");
     END;

     BEGIN
          RAISE STORAGE_ERROR;
          FAILED("NO EXCEPTION RAISED WHEN STORAGE_ERROR EXPECTED");

     EXCEPTION
          WHEN STORAGE_ERROR =>
               FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED WHEN STORAGE_ERROR " &
                      "EXPECTED");
     END;

     BEGIN
          RAISE TASKING_ERROR;
          FAILED("NO EXCEPTION RAISED WHEN TASKING_ERROR EXPECTED");

     EXCEPTION
          WHEN TASKING_ERROR =>
               FLOW_COUNT := FLOW_COUNT + 1;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED WHEN TASKING_ERROR " &
                      "EXPECTED");
     END;

     IF FLOW_COUNT /= 5 THEN
          FAILED("WRONG FLOW_COUNT VALUE");
     END IF;

     RESULT;
END CB1001A;
