-- CB2005A.ADA

-- CHECK THAT A RETURN STATEMENT CAN APPEAR IN AN EXCEPTION HANDLER
-- AND IT CAUSES CONTROL TO LEAVE THE SUBPROGRAM, FOR BOTH
-- FUNCTIONS AND PROCEDURES.

-- DAT 4/13/81
-- JRK 4/24/81
-- SPS 10/26/82

WITH REPORT; USE REPORT;

PROCEDURE CB2005A IS

     I : INTEGER RANGE 0 .. 1;

     FUNCTION SETI RETURN INTEGER IS
     BEGIN
          I := I + 1;
          FAILED ("CONSTRAINT_ERROR NOT RAISED 1");
          RETURN 0;
     EXCEPTION
          WHEN OTHERS =>
               RETURN I;
               FAILED ("FUNCTION RETURN STMT DID NOT RETURN");
               RETURN 0;
     END SETI;

     PROCEDURE ISET IS
     BEGIN
          I := 2;
          FAILED ("CONSTRAINT_ERROR NOT RAISED 2");
          I := 0;
     EXCEPTION
          WHEN OTHERS => 
               RETURN;
               FAILED ("PROCEDURE RETURN STMT DID NOT RETURN");
     END ISET;

BEGIN
     TEST ("CB2005A", "RETURN IN EXCEPTION HANDLERS");

     I := 1;
     IF SETI /= 1 THEN
          FAILED ("WRONG VALUE RETURNED 1");
     END IF;

     I := 1;
     ISET;
     IF I /= 1 THEN
          FAILED ("WRONG VALUE RETURNED 2");
     END IF;

     RESULT;
END CB2005A;
