-- CB4013A.ADA

-- OBJECTIVE:
--     CHECK THAT AN UNHANDLED EXCEPTION RAISED IN A TASK BODY, BUT
--     OUTSIDE AN ACCEPT STATEMENT, RAISES NO EXCEPTION OUTSIDE THE
--     TASK.

-- HISTORY:
--     DHH 03/29/88 CREATED ORIGINAL TEST.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE CB4013A IS

     TASK TYPE CHOICE IS
          ENTRY E1;
          ENTRY STOP;
     END CHOICE;

     T : CHOICE;

     TASK BODY CHOICE IS
     BEGIN
          ACCEPT E1;
          IF EQUAL(3,3) THEN
               RAISE CONSTRAINT_ERROR;
          END IF;
          ACCEPT STOP;
     END CHOICE;

BEGIN

     TEST("CB4013A", "CHECK THAT AN UNHANDLED EXCEPTION RAISED IN " &
                     "A TASK BODY, BUT OUTSIDE AN ACCEPT STATEMENT, " &
                     "RAISES NO EXCEPTION OUTSIDE THE TASK");

     T.E1;
     DELAY 1.0;
     IF T'CALLABLE THEN
          FAILED("TASK NOT COMPLETED ON RAISING CONSTRAINT_ERROR");
          T.STOP;
     END IF;

     RESULT;

EXCEPTION
     WHEN TASKING_ERROR =>
          FAILED("TASKING_ERROR RAISED OUTSIDE TASK");
          RESULT;

     WHEN CONSTRAINT_ERROR =>
          FAILED("CONSTRAINT_ERROR PROPAGATED OUTSIDE TASK");
          RESULT;

     WHEN OTHERS =>
          FAILED("UNEXPECTED EXCEPTION RAISED");
          RESULT;
END CB4013A;
