-- CB4004A.ADA

-- CHECK THAT VARIOUS EXCEPTIONS IN THE BODY OF A SUBPROGRAM WITH
-- AN APPLICABLE HANDLER ARE HANDLED LOCALLY.

-- DAT 04/15/81
-- JRK 04/24/81
-- SPS 11/02/82
-- EG  10/30/85  ELIMINATE THE USE OF NUMERIC_ERROR IN TEST.

WITH REPORT; USE REPORT;

PROCEDURE CB4004A IS

     E, F : EXCEPTION;
     STORAGE_ERROR: EXCEPTION;

     I1 : INTEGER RANGE 1 .. 1;

     FUNCTION F1 (I : INTEGER) RETURN BOOLEAN IS
     BEGIN
          CASE I IS
               WHEN 1 => RAISE E;
               WHEN 2 => RAISE STORAGE_ERROR;
               WHEN 3 => I1 := 4;
               WHEN 4 => RAISE TASKING_ERROR;
               WHEN OTHERS => NULL;
          END CASE;
          RETURN FALSE;
     EXCEPTION
          WHEN E | F => RETURN I = 1;
          WHEN STORAGE_ERROR => RETURN I = 2;
          WHEN PROGRAM_ERROR | CONSTRAINT_ERROR =>
               RETURN I = 3;
          WHEN OTHERS => RETURN I = 4;
     END F1;

BEGIN
     TEST ("CB4004A", "EXCEPTIONS WITH LOCAL HANDLERS ARE HANDLED"
          & " THERE");

     BEGIN
          FOR L IN 1 .. 4 LOOP
               IF F1(L) /= TRUE THEN
                    FAILED ("LOCAL EXCEPTIONS DON'T WORK");
                    EXIT;
               END IF;
          END LOOP;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("WRONG HANDLER");
     END;

     RESULT;
END CB4004A;
