-- CB5001A.ADA

-- CHECK THAT AN EXCEPTION RAISED IN A RENDEVOUS IS PROPAGATED BOTH TO
-- THE CALLER AND TO THE CALLED TASK.

-- THIS VERSION CHECKS THAT THE EXCEPTION IS PROPAGATED THROUGH ONE
-- LEVEL OF RENDEVOUS.

-- JEAN-PIERRE ROSEN 09 MARCH 1984
-- JBG 6/1/84

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE CB5001A IS

BEGIN

     TEST("CB5001A", "CHECK THAT AN EXCEPTION IN A RENDEVOUS IS " &
                     "PROPAGATED TO CALLER AND CALLED TASKS -- ONE " &
                     "LEVEL");

     DECLARE
          TASK T2 IS
               ENTRY E2;
          END T2;
     
          TASK BODY T2 IS
               MY_EXCEPTION: EXCEPTION;
          BEGIN
               ACCEPT E2 DO 
                    IF EQUAL (1,1) THEN
                         RAISE MY_EXCEPTION; 
                    END IF;
               END E2;
               FAILED ("T2: EXCEPTION NOT RAISED");
          EXCEPTION
               WHEN MY_EXCEPTION => 
                    NULL;
               WHEN TASKING_ERROR =>
                    FAILED ("TASKING_ERROR RAISED IN T2");
               WHEN OTHERS =>
                    FAILED ("T2 RECEIVED ABNORMAL EXCEPTION");
          END T2;
     
     BEGIN 
          T2.E2;
          FAILED ("MAIN: EXCEPTION NOT RAISED");
     EXCEPTION
          WHEN CONSTRAINT_ERROR | NUMERIC_ERROR | PROGRAM_ERROR =>
               FAILED ("PREDEFINED ERROR RAISED IN MAIN");
          WHEN TASKING_ERROR =>
               FAILED ("TASKING_ERROR RAISED IN MAIN");
          WHEN OTHERS => 
               NULL;
     END;

     RESULT;

END CB5001A;
