-- CC1010B.ADA

-- CHECK THAT THE NAMES IN A GENERIC PACKAGE BODY ARE STATICALLY
-- IDENTIFIED (I.E., BOUND) AT THE POINT WHERE THE GENERIC BODY
-- TEXTUALLY OCCURS, AND ARE NOT DYNAMICALLY BOUND AT THE POINT
-- OF INSTANTIATION.

-- ASL 8/13/81

WITH REPORT;
PROCEDURE CC1010B IS

     USE REPORT;
     FREE : CONSTANT INTEGER := 5;
BEGIN
     TEST("CC1010B","PROPER VISIBILITY OF FREE IDENTIFIERS IN " &
          "GENERIC PACKAGE DECLARATIONS, BODIES AND INSTANTIATIONS");

     DECLARE
          GENERIC
               GFP : INTEGER := FREE;
          PACKAGE P IS
               SPECITEM : CONSTANT INTEGER := FREE;
          END P;
          
          FREE : CONSTANT INTEGER := 6;

          PACKAGE BODY P IS
               BODYITEM : INTEGER := FREE;
          BEGIN
               IF GFP /= 5 OR SPECITEM /= 5 OR BODYITEM /= 6 THEN
                    FAILED ("BINDINGS INCORRECT");
               END IF;
          END P;
     BEGIN
          DECLARE
               FREE : CONSTANT INTEGER := 7;
               PACKAGE INST IS NEW P;
          BEGIN
               NULL;
          END;
     END;

     RESULT;
END CC1010B;
