-- CC1107B.ADA

-- OBJECTIVE:
--     CHECK THAT A DEFAULT EXPRESSION MAY REFER TO AN EARLIER FORMAL
--     PARAMETER OF THE SAME GENERIC FORMAL PART.

-- HISTORY:
--     BCB 08/03/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;

PROCEDURE CC1107B IS

     J, I : INTEGER;

     X : INTEGER := IDENT_INT(0);

     VAL : INTEGER := IDENT_INT(10);

     GENERIC
          X : INTEGER := IDENT_INT(5);
          Y : INTEGER := X;
     FUNCTION F RETURN INTEGER;

     GENERIC
          X : INTEGER;
          Y : INTEGER := X;
     FUNCTION G RETURN INTEGER;

     FUNCTION F RETURN INTEGER IS
     BEGIN
          IF NOT EQUAL(X,Y) THEN
               FAILED ("WRONG VALUE FROM EARLIER FORMAL PARAMETER - 1");
          END IF;

          RETURN 0;
     END F;

     FUNCTION G RETURN INTEGER IS
     BEGIN
          IF NOT EQUAL(X,Y) THEN
               FAILED ("WRONG VALUE FROM EARLIER FORMAL PARAMETER - 2");
          END IF;

          RETURN 0;
     END G;

     FUNCTION NEW_F IS NEW F;

     FUNCTION NEW_G IS NEW G(VAL);

BEGIN
     TEST ("CC1107B", "CHECK THAT A DEFAULT EXPRESSION MAY REFER " &
                      "TO AN EARLIER FORMAL PARAMETER OF THE SAME " &
                      "GENERIC FORMAL PART");

     J := NEW_F;

     I := NEW_G;

     RESULT;
END CC1107B;
