-- CC1307A.ADA

-- CHECK THAT SUBPROGRAM PARAMETERS MAY HAVE AN OPERATOR_SYMBOL DEFAULT,
-- WHICH LOOKS THE SAME AS A DEFAULT STRING PARAMETER.

-- DAT 9/8/81

WITH REPORT; USE REPORT;

PROCEDURE CC1307A IS
BEGIN
     TEST ("CC1307A", "GENERIC SUBPROGRAM AND STRING DEFAULT PARAMETERS"
          & " MAY LOOK THE SAME");

     DECLARE
          GENERIC
               WITH FUNCTION CAT (X, Y : STRING) RETURN STRING
                    IS "&";
               S : STRING := "&";
          PACKAGE PK IS
               VAL : CONSTANT STRING := CAT (S, S);
          END PK;

          PACKAGE PK1 IS NEW PK;
     BEGIN
          IF PK1.VAL /= "&&" THEN
               FAILED ("INCORRECT GENERIC INSTANTIATION WITH DEFAULTS");
          END IF;
     END;

     RESULT;
END CC1307A;
