-- CD1009W.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION REPRESENTATION CLAUSE MAY BE GIVEN IN
--     THE PRIVATE PART OF A PACKAGE FOR A PRIVATE TYPE, WHOSE FULL
--     TYPE DECLARATION IS AN ENUMERATION TYPE, DECLARED IN THE
--     VISIBLE PART OF THE SAME PACKAGE.

-- HISTORY:
--     VCL  10/09/87  CREATED ORIGINAL TEST.
--     DHH  03/29/89  CHANGE FROM 'A' TEST TO 'C' TEST AND FROM '.DEP'
--                    '.ADA'.  ADDED CHECK ON REPRESENTATION CLAUSE.

WITH REPORT; USE REPORT;
WITH ENUM_CHECK;                      -- CONTAINS A CALL TO 'FAILED'.
PROCEDURE CD1009W IS
BEGIN
     TEST ("CD1009W", "AN ENUMERATION REPRESENTATION CLAUSE MAY BE " &
                      "GIVEN IN THE PRIVATE PART OF A PACKAGE FOR " &
                      "A PRIVATE TYPE, WHOSE FULL TYPE DECLARATION " &
                      "IS AN ENUMERATION TYPE, DECLARED IN " &
                      "THE VISIBLE PART OF THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               TYPE CHECK_TYPE_1 IS PRIVATE;
          PRIVATE
               TYPE CHECK_TYPE_1 IS (A0, A2, A4, A8);
               FOR CHECK_TYPE_1 USE (A0 => 0,
                                     A2 => 2,
                                     A4 => 4,
                                     A8 => 16);
               TYPE INT1 IS RANGE 0 .. 16;
               FOR INT1'SIZE USE CHECK_TYPE_1'SIZE;

               PROCEDURE CHECK_1 IS NEW ENUM_CHECK(CHECK_TYPE_1, INT1);
          END PACK;

          PACKAGE BODY PACK IS
          BEGIN
               CHECK_1 (A8, 16, "CHECK_TYPE_1");
          END PACK;

          USE PACK;
     BEGIN
          NULL;
     END;

     RESULT;
END CD1009W;
