-- CD1009Q.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SIZE' SPECIFICATION MAY BE GIVEN IN THE PRIVATE
--     PART OF A PACKAGE FOR AN INCOMPLETE TYPE, WHOSE FULL DECLARATION
--     IS A FIXED POINT TYPE, DECLARED IN THE VISIBLE PART OF THE SAME
--     PACKAGE.

-- HISTORY:
--     PWB 03/25/89  MODIFIED METHOD OF CHECKING OBJECT SIZE AGAINST
--                   TYPE SIZE; CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL  10/21/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009Q IS
BEGIN
     TEST ("CD1009Q", "A 'SIZE' CLAUSE MAY BE GIVEN IN THE " &
                      "PRIVATE PART OF A PACKAGE FOR A AN " &
                      "INCOMPLETE TYPE, WHOSE FULL DECLARATION IS A " &
                      "FIXED POINT TYPE, DECLARED IN THE VISIBLE " &
                      "PART OF THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               TYPE SPECIFIED IS DELTA 2.0 ** (-4) RANGE 0.0 .. 10.0;

               SPECIFIED_SIZE : CONSTANT := SPECIFIED'SIZE;

               TYPE CHECK_TYPE_1;
               TYPE ACC IS ACCESS CHECK_TYPE_1;

               TYPE CHECK_TYPE_1 IS DELTA 2.0 ** (-1) RANGE 0.0 .. 2.0;
          PRIVATE
               FOR CHECK_TYPE_1'SIZE
                              USE SPECIFIED_SIZE;
          END PACK;

          USE PACK;

          X : CHECK_TYPE_1 := CHECK_TYPE_1 ( IDENT_INT (1) );
     BEGIN
          IF CHECK_TYPE_1'SIZE /= SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_1'SIZE IS INCORRECT");
          END IF;

          IF X'SIZE < SPECIFIED_SIZE THEN
               FAILED ("OBJECT SIZE TOO SMALL -- CHECK_TYPE_1.  " &
                       "VALUE IS"  & INTEGER'IMAGE ( INTEGER(X) ) );
          END IF;

     END;

     RESULT;
END CD1009Q;
