-- CD1009P.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SIZE' CLAUSE MAY BE GIVEN IN THE PRIVATE PART
--     OF A PACKAGE FOR AN INCOMPLETE TYPE, WHOSE FULL DECLARATION
--     IS AN ENUMERATION TYPE, DECLARED IN THE VISIBLE PART OF THE SAME
--     PACKAGE.

-- HISTORY:
--     PWB 03/25/89  MODIFIED METHOD OF CHECKING OBJECT SIZE AGAINST
--                   TYPE SIZE; CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL  10/09/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009P IS
BEGIN
     TEST ("CD1009P", "A 'SIZE' CLAUSE MAY BE GIVEN IN THE VISIBLE " &
                      "PART OF A PACKAGE FOR AN INCOMPLETE TYPE, " &
                      "WHOSE FULL DECLARATION IS AN ENUMERATION " &
                      "TYPE, DECLARED IN THE VISIBLE PART OF THE " &
                      "SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE;

               TYPE CHECK_TYPE_1;
               TYPE ACC IS ACCESS CHECK_TYPE_1;

               TYPE CHECK_TYPE_1 IS (A0, A1, A2, A3);

          PRIVATE
               FOR CHECK_TYPE_1'SIZE
                              USE SPECIFIED_SIZE;
          END PACK;

          USE PACK;
     BEGIN
          IF CHECK_TYPE_1'SIZE > SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_1'SIZE IS TOO LARGE");
          END IF;
     END;

     RESULT;
END CD1009P;
