-- CD1009B.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SIZE CLAUSE MAY BE GIVEN IN THE VISIBLE
--     OR PRIVATE PART OF A PACKAGE FOR AN ENUMERATION TYPE DECLARED
--     IN THE VISIBLE PART OF THE SAME PACKAGE.

-- HISTORY:
--     PWB 03/25/89  MODIFIED METHOD OF CHECKING OBJECT SIZE AGAINST
--                   TYPE SIZE; CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL 10/07/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009B IS
BEGIN
     TEST ("CD1009B", "A 'SIZE CLAUSE MAY BE GIVEN IN THE VISIBLE " &
                      "OR PRIVATE PART OF A PACKAGE FOR AN " &
                      "ENUMERATION TYPE DECLARED IN THE VISIBLE " &
                      "PART OF THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE / 2;

               TYPE CHECK_TYPE_1 IS (A0, A1, A2, A3);
               FOR CHECK_TYPE_1'SIZE
                              USE SPECIFIED_SIZE;

               TYPE CHECK_TYPE_2 IS (A0, A1, A2, A3);
          PRIVATE
               FOR CHECK_TYPE_2'SIZE USE SPECIFIED_SIZE;
          END PACK;

          USE PACK;
          X : CHECK_TYPE_1 := A0;
          Y : CHECK_TYPE_2 := A2;
     BEGIN
          IF CHECK_TYPE_1'SIZE /= SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_1'SIZE IS INCORRECT");
          END IF;

          IF CHECK_TYPE_2'SIZE /= SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_2'SIZE IS INCORRECT");
          END IF;

          IF X'SIZE < SPECIFIED_SIZE THEN
               FAILED ("OBJECT'SIZE IS TOO SMALL --" &
                       CHECK_TYPE_1'IMAGE(X));
          END IF;

          IF Y'SIZE < SPECIFIED_SIZE THEN
               FAILED ("OBJECT'SIZE IS TOO SMALL --" &
                       CHECK_TYPE_2'IMAGE(Y));
          END IF;

     END;

     RESULT;
END CD1009B;
