-- CD1009R.ADA

-- OBJECTIVE:
--     CHECK THAT A 'STORAGE_SIZE' CLAUSE MAY BE GIVEN IN THE
--     PRIVATE PART OF A PACKAGE FOR AN INCOMPLETE TYPE, WHOSE FULL
--     DECLARATION IS AN ACCESS TYPE, DECLARED IN THE VISIBLE PART OF
--     THE SAME PACKAGE.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL 10/21/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009R IS
BEGIN
     TEST ("CD1009R", "A 'STORAGE_SIZE' CLAUSE MAY BE GIVEN IN THE " &
                      "PRIVATE PART OF A PACKAGE FOR AN INCOMPLETE " &
                      "TYPE, WHOSE FULL TYPE DECLARATION IS AN " &
                      "ACCESS TYPE, DECLARED IN THE VISIBLE PART OF " &
                      "THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE * 10;

               TYPE CHECK_TYPE_1;
               TYPE ACC IS ACCESS CHECK_TYPE_1;

               TYPE CHECK_TYPE_1 IS ACCESS INTEGER;
          PRIVATE
               FOR CHECK_TYPE_1'STORAGE_SIZE
                              USE SPECIFIED_SIZE;
          END PACK;

          USE PACK;
     BEGIN
          IF CHECK_TYPE_1'STORAGE_SIZE < SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_1'STORAGE_SIZE IS TOO SMALL");
          END IF;
     END;

     RESULT;
END CD1009R;
