-- CD1009J.ADA

-- OBJECTIVE:
--     CHECK THAT A 'STORAGE_SIZE' CLAUSE MAY BE GIVEN IN THE
--     VISIBLE OR PRIVATE PART OF A PACKAGE FOR AN ACCESS TYPE
--     DECLARED IN THE VISIBLE PART OF THE SAME PACKAGE.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL 10/07/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009J IS
BEGIN
     TEST ("CD1009J", "A 'STORAGE_SIZE' CLAUSE MAY BE GIVEN IN THE " &
                      "VISIBLE OR PRIVATE PART OF A PACKAGE FOR AN " &
                      "ACCESS TYPE DECLARED IN THE VISIBLE PART OF " &
                      "THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE * 10;

               TYPE CHECK_TYPE_1 IS ACCESS INTEGER;
               FOR CHECK_TYPE_1'STORAGE_SIZE
                              USE SPECIFIED_SIZE;

               TYPE CHECK_TYPE_2 IS ACCESS INTEGER;
          PRIVATE
               FOR CHECK_TYPE_2'STORAGE_SIZE USE SPECIFIED_SIZE;
          END PACK;

          USE PACK;
     BEGIN
          IF CHECK_TYPE_1'STORAGE_SIZE < SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_1'STORAGE_SIZE IS TOO SMALL");
          END IF;

          IF CHECK_TYPE_2'STORAGE_SIZE < SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_2'STORAGE_SIZE IS TOO SMALL");
          END IF;
     END;

     RESULT;
END CD1009J;
