-- CD1009L.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SMALL' CLAUSE MAY BE GIVEN IN THE VISIBLE OR
--     PRIVATE PART OF A PACKAGE FOR A FIXED POINT TYPE DECLARED
--     IN THE VISIBLE PART OF THE SAME PACKAGE.

-- HISTORY:
--     VCL 10/08/87  CREATED ORIGINAL TEST.
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP', CHANGED
--                    COMMENT FROM FLOATING POINT TO FIXED POINT.

WITH REPORT; USE REPORT;
PROCEDURE CD1009L IS
BEGIN
     TEST ("CD1009L", "A 'SMALL' CLAUSE MAY BE GIVEN IN THE VISIBLE " &
                      "OR PRIVATE PART OF A PACKAGE FOR A " &
                      "FIXED POINT TYPE DECLARED IN THE VISIBLE " &
                      "PART OF THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               TYPE SPECIFIED IS DELTA 2.0 ** (-2) RANGE 0.0 .. 1.0;

               SPECIFIED_SMALL : CONSTANT := SPECIFIED'SMALL;

               TYPE CHECK_TYPE_1 IS DELTA 2.0 ** (-1) RANGE 0.0 .. 1.0;
               FOR CHECK_TYPE_1'SMALL
                              USE SPECIFIED_SMALL;

               TYPE CHECK_TYPE_2 IS DELTA 2.0 ** (-1) RANGE 0.0 .. 1.0;
          PRIVATE
               FOR CHECK_TYPE_2'SMALL USE SPECIFIED_SMALL;
          END PACK;

          USE PACK;
     BEGIN
          IF CHECK_TYPE_1'SMALL /= SPECIFIED_SMALL THEN
               FAILED ("INCORRECT RESULTS FOR CHECK_TYPE_1'SMALL");
          END IF;

          IF CHECK_TYPE_2'SMALL /= SPECIFIED_SMALL THEN
               FAILED ("INCORRECT RESULTS FOR CHECK_TYPE_2'SMALL");
          END IF;
     END;

     RESULT;
END CD1009L;
