-- CD1009D.ADA

-- OBJECTIVE:
--     CHECK THAT A 'SIZE CLAUSE MAY BE GIVEN IN THE VISIBLE
--     OR PRIVATE PART OF A PACKAGE FOR A FIXED POINT TYPE DECLARED IN
--     THE VISIBLE PART OF THE SAME PACKAGE.

-- HISTORY:
--     PWB 03/25/89  MODIFIED METHOD OF CHECKING OBJECT SIZE AGAINST
--                   TYPE SIZE; CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL 10/07/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009D IS
BEGIN
     TEST ("CD1009D", "A 'SIZE CLAUSE MAY BE GIVEN IN THE VISIBLE " &
                      "OR PRIVATE PART OF A PACKAGE FOR A " &
                      "FIXED POINT TYPE DECLARED IN THE VISIBLE " &
                      "PART OF THE SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               TYPE SPECIFIED IS DELTA 2.0 ** (-4) RANGE 0.0 .. 10.0;

               SPECIFIED_SIZE : CONSTANT := SPECIFIED'SIZE;

               TYPE CHECK_TYPE_1 IS DELTA 2.0 ** (-1) RANGE 0.0 .. 1.0;
               FOR CHECK_TYPE_1'SIZE
                              USE SPECIFIED_SIZE;

               TYPE CHECK_TYPE_2 IS DELTA 2.0 ** (-1) RANGE 0.0 .. 1.0;
          PRIVATE
               FOR CHECK_TYPE_2'SIZE USE SPECIFIED_SIZE;
          END PACK;

          USE PACK;

          X: CHECK_TYPE_1 := 0.5;
          Y: CHECK_TYPE_2 := 0.5;

     BEGIN
          IF CHECK_TYPE_1'SIZE /= SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_1'SIZE IS INCORRECT");
          END IF;

          IF CHECK_TYPE_2'SIZE /= SPECIFIED_SIZE THEN
               FAILED ("CHECK_TYPE_2'SIZE IS INCORRECT");
          END IF;

          IF X'SIZE < SPECIFIED_SIZE THEN
               FAILED ("OBJECT SIZE IS TOO SMALL -- " &
                       "VALUE IS" & INTEGER'IMAGE ( INTEGER(X) ) );
          END IF;

          IF Y'SIZE < SPECIFIED_SIZE THEN
               FAILED ("OBJECT SIZE IS TOO SMALL -- " &
                       "VALUE IS" & INTEGER'IMAGE ( INTEGER(Y) ) );
          END IF;

     END;

     RESULT;
END CD1009D;
