-- CD1009S.ADA

-- OBJECTIVE:
--     CHECK THAT A 'STORAGE_SIZE' CLAUSE MAY BE GIVEN IN THE PRIVATE
--     PART OF A PACKAGE FOR A PRIVATE TYPE, WHOSE FULL TYPE
--     DECLARATION IS AN ACCESS TYPE, DECLARED IN THE VISIBLE PART
--     OF THE SAME PACKAGE.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     VCL 10/09/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1009S IS
BEGIN
     TEST ("CD1009S", "A 'STORAGE_SIZE' CLAUSE MAY BE GIVEN IN THE " &
                      "PRIVATE PART OF A PACKAGE FOR A PRIVATE TYPE, " &
                      "WHOSE FULL TYPE DECLARATION IS AN ACCESS " &
                      "TYPE, DECLARED IN THE VISIBLE PART OF THE " &
                      "SAME PACKAGE");
     DECLARE
          PACKAGE PACK IS
               SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE * 10;

               TYPE CHECK_TYPE_1 IS PRIVATE;

               PROCEDURE P;
          PRIVATE
               TYPE CHECK_TYPE_1 IS ACCESS INTEGER;
               FOR CHECK_TYPE_1'STORAGE_SIZE
                              USE SPECIFIED_SIZE;
          END PACK;

          PACKAGE BODY PACK IS
               PROCEDURE P IS
               BEGIN
                    IF CHECK_TYPE_1'STORAGE_SIZE < SPECIFIED_SIZE THEN
                         FAILED ("CHECK_TYPE_1'STORAGE_SIZE IS TOO " &
                                 "SMALL");
                    END IF;
               END P;
          END PACK;

          USE PACK;
     BEGIN
          P;
     END;

     RESULT;
END CD1009S;
