-- CD1C04B.ADA

-- OBJECTIVE:
--     CHECK THAT A TASK STORAGE SIZE CLAUSE CAN BE GIVEN FOR A
--     DERIVED TASK TYPE EVEN IF THE SIZE IS INHERITED FROM THE
--     PARENT, AND THAT THE CLAUSE FOR THE DERIVED TYPE OVERRIDES
--     THAT OF THE PARENT.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     JET 09/21/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1C04B IS

     SPECIFIED_SIZE : CONSTANT := 2048;

     TASK TYPE PARENT_TYPE IS
          ENTRY E;
     END PARENT_TYPE;

     FOR PARENT_TYPE'STORAGE_SIZE USE 4096;

     TYPE DERIVED_TYPE IS NEW PARENT_TYPE;

     FOR DERIVED_TYPE'STORAGE_SIZE USE SPECIFIED_SIZE;

     TASK BODY PARENT_TYPE IS
     BEGIN
          ACCEPT E DO
               COMMENT ("ENTRY E ACCEPTED");
          END E;
     END PARENT_TYPE;

BEGIN

     TEST("CD1C04B", "CHECK THAT A TASK STORAGE SIZE CLAUSE CAN " &
                     "BE GIVEN FOR A DERIVED TASK TYPE EVEN IF " &
                     "THE SIZE IS INHERITED FROM THE PARENT, AND " &
                     "THAT THE CLAUSE FOR THE DERIVED TYPE " &
                     "OVERRIDES THAT OF THE PARENT");

     IF PARENT_TYPE'STORAGE_SIZE < IDENT_INT (4096) THEN
          FAILED ("PARENT_TYPE'STORAGE_SIZE SHOULD NOT BE " &
                  "LESS THAN 4096.  ACTUAL SIZE IS" &
                  INTEGER'IMAGE(PARENT_TYPE'STORAGE_SIZE));
     END IF;

     IF DERIVED_TYPE'STORAGE_SIZE < IDENT_INT (SPECIFIED_SIZE) THEN
          FAILED ("DERIVED_TYPE'STORAGE_SIZE SHOULD NOT BE " &
                  "LESS THAN" & INTEGER'IMAGE(SPECIFIED_SIZE) &
                  ".  ACTUAL SIZE IS" &
                  INTEGER'IMAGE(DERIVED_TYPE'STORAGE_SIZE));
     END IF;

     RESULT;

END CD1C04B;
