-- CD1C03C.ADA

-- OBJECTIVE:
--     CHECK THAT THE COLLECTION SIZE OF A DERIVED TYPE IS
--     INHERITED FROM THE PARENT IF THE COLLECTION SIZE OF
--     THE PARENT WAS DETERMINED BY A COLLECTION SIZE CLAUSE.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     JET 09/16/87  CREATED ORIGINAL TEST.
--     RJW 02/10/88  RENAMED FROM CD1C03C.TST.  REMOVED MACRO -
--                   ACC_SIZE.

WITH REPORT; USE REPORT;
PROCEDURE CD1C03C IS

     SPECIFIED_SIZE : CONSTANT := 512;

     TYPE PARENT_TYPE IS ACCESS STRING;

     FOR PARENT_TYPE'STORAGE_SIZE USE SPECIFIED_SIZE;

     TYPE DERIVED_TYPE IS NEW PARENT_TYPE;

BEGIN

     TEST("CD1C03C", "CHECK THAT THE COLLECTION  SIZE OF A " &
                     "DERIVED TYPE IS INHERITED FROM THE PARENT " &
                     "IF THE COLLECTION SIZE OF THE PARENT WAS " &
                     "DETERMINED BY A COLLECTION SIZE CLAUSE");

     IF PARENT_TYPE'STORAGE_SIZE < IDENT_INT (SPECIFIED_SIZE) THEN
          FAILED ("PARENT_TYPE'STORAGE_SIZE SHOULD NOT BE " &
                  "LESS THAN SPECIFIED_SIZE.  " &
                  "ACTUAL SIZE IS" &
                  INTEGER'IMAGE(PARENT_TYPE'SIZE));
     END IF;

     IF DERIVED_TYPE'STORAGE_SIZE /=
                         IDENT_INT (PARENT_TYPE'STORAGE_SIZE) THEN
          FAILED ("DERIVED_TYPE'STORAGE_SIZE SHOULD BE " &
                  "EQUAL TO PARENT_TYPE'STORAGE_SIZE.  " &
                  "ACTUAL SIZE IS" &
                  INTEGER'IMAGE(DERIVED_TYPE'STORAGE_SIZE));
     END IF;

     RESULT;

END CD1C03C;
