-- CD1C03G.ADA

-- OBJECTIVE:
--     CHECK THAT THE SIZE OF A DERIVED ENUMERATION TYPE IS
--     INHERITED FROM THE PARENT IF THE SIZE OF THE PARENT WAS
--     DETERMINED BY AN ENUMERATION REPRESENTATION CLAUSE.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     JET 09/17/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1C03G IS

     TYPE NORMAL_TYPE IS (RED, BLUE, GREEN, YELLOW);

     TYPE PARENT_TYPE IS (RED, BLUE, GREEN, YELLOW);

     FOR PARENT_TYPE USE
          (RED => 256, BLUE => 257, GREEN => 258, YELLOW => 259);

     TYPE DERIVED_TYPE IS NEW PARENT_TYPE;

BEGIN

     TEST("CD1C03G", "CHECK THAT THE SIZE OF A DERIVED ENUMERATION " &
                     "TYPE IS INHERITED FROM THE PARENT IF THE " &
                     "SIZE OF THE PARENT WAS DETERMINED BY AN " &
                     "ENUMERATION REPRESENTATION CLAUSE");

     IF PARENT_TYPE'SIZE = IDENT_INT (NORMAL_TYPE'SIZE) THEN
          COMMENT ("PARENT_TYPE'SIZE WAS NOT AFFECTED BY THE " &
                   "REPRESENTATION CLAUSE");
     END IF;

     IF DERIVED_TYPE'SIZE /= IDENT_INT (PARENT_TYPE'SIZE) THEN
          FAILED ("DERIVED_TYPE'SIZE WAS NOT INHERITED FROM " &
                  "PARENT_TYPE");
     END IF;

     RESULT;

END CD1C03G;
