-- CD1C03F.ADA

-- OBJECTIVE:
--     CHECK THAT THE VALUE OF 'SMALL FOR A DERIVED FIXED POINT TYPE
--     IS INHERITED FROM THE PARENT IF THE VALUE OF 'SMALL FOR THE
--     PARENT WAS DETERMINED BY A 'SMALL SPECIFICATION CLAUSE.

-- HISTORY:
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.
--     JET 09/17/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD1C03F IS

     SPECIFIED_SMALL : CONSTANT := 0.25;

     TYPE FLT IS NEW FLOAT;

     TYPE PARENT_TYPE IS DELTA 1.0 RANGE 0.0 .. 100.0;

     FOR PARENT_TYPE'SMALL USE SPECIFIED_SMALL;

     TYPE DERIVED_TYPE IS NEW PARENT_TYPE;

     FUNCTION IDENT_FLT (F : FLT) RETURN FLT IS
     BEGIN
          IF EQUAL (3, 3) THEN
               RETURN F;
          ELSE
               RETURN 0.0;
          END IF;
     END;

BEGIN

     TEST("CD1C03F", "CHECK THAT THE VALUE OF 'SMALL FOR A " &
                     "DERIVED FIXED POINT TYPE IS INHERITED " &
                     "FROM THE PARENT IF THE VALUE OF 'SMALL " &
                     "FOR THE PARENT WAS DETERMINED BY A 'SMALL " &
                     "SPECIFICATION CLAUSE");

     IF PARENT_TYPE'SMALL /= IDENT_FLT (SPECIFIED_SMALL) THEN
          FAILED ("PARENT_TYPE'SMALL SHOULD BE EQUAL TO " &
                  "THE SPECIFIED VALUE");
     END IF;

     IF DERIVED_TYPE'SMALL /= IDENT_FLT (SPECIFIED_SMALL) THEN
          FAILED ("DERIVED_TYPE'SMALL SHOULD BE EQUAL TO " &
                  "THE SPECIFIED VALUE");
     END IF;

     RESULT;

END CD1C03F;
