-- CD1D01C.ADA

-- OBJECTIVE:
--     CHECK WHETHER A PRAGMA PACK IS OBEYED FOR A RECORD HAVING
--     BOOLEAN COMPONENTS SEPARATED BY INTEGER COMPONENTS.  CHECK
--     WHETHER THE SIZE IS AFFECTED AND, IF SO, WHETHER THE ORDER
--     OF THE COMPONENTS IS AFFECTED.

-- HISTORY:
--     JET 08/13/87 CREATED ORIGINAL TEST.
--     PWB 03/27/89 MODIFIED CHECK OF OBJECT SIZE AGAINST TYPE SIZE.

WITH REPORT; USE REPORT;
PROCEDURE CD1D01C IS

     TYPE MIX_REC IS RECORD
          B1: BOOLEAN;
          I1: INTEGER;
          B2: BOOLEAN;
          I2: INTEGER;
          B3, B4, B5: BOOLEAN;
          I3, I4: INTEGER;
          B6: BOOLEAN;
     END RECORD;

     TYPE PACKED_MIX_REC IS RECORD
          B1: BOOLEAN;
          I1: INTEGER;
          B2: BOOLEAN;
          I2: INTEGER;
          B3, B4, B5: BOOLEAN;
          I3, I4: INTEGER;
          B6: BOOLEAN;
     END RECORD;

     PRAGMA PACK (PACKED_MIX_REC);

     REC1: MIX_REC := (IDENT_BOOL(TRUE), 1, FALSE, 2, TRUE, FALSE, TRUE,
                       3, IDENT_INT(4), FALSE);

     REC2: PACKED_MIX_REC := (TRUE, IDENT_INT(1), FALSE, 2, TRUE, FALSE, TRUE,
                       3, 4, IDENT_BOOL(FALSE));

BEGIN

     TEST("CD1D01C", "CHECK WHETHER A PRAGMA PACK IS OBEYED FOR " &
                     "A RECORD HAVING BOOLEAN COMPONENTS SEPARATED " &
                     "BY INTEGER COMPONENTS.  CHECK WHETHER THE " &
                     "SIZE IS AFFECTED AND, IF SO, WHETHER THE " &
                     "ORDER OF THE COMPONENTS IS AFFECTED");

     IF MIX_REC'SIZE > PACKED_MIX_REC'SIZE THEN
          COMMENT ("PRAGMA PACK WAS OBEYED FOR A RECORD " &
                   "CONTAINING FOUR INTEGER AND SIX BOOLEAN " &
                   "COMPONENTS. THE SIZE OF THE ORIGINAL RECORD IS" &
                   INTEGER'IMAGE (MIX_REC'SIZE) & "; " &
                   "THE SIZE OF THE PACKED RECORD IS" &
                   INTEGER'IMAGE (PACKED_MIX_REC'SIZE));
     ELSIF MIX_REC'SIZE = PACKED_MIX_REC'SIZE THEN
          COMMENT ("PRAGMA PACK HAD NO EFFECT ON THE SIZE " &
                   "OF A RECORD CONTAINING FOUR INTEGER AND SIX " &
                   "BOOLEAN COMPONENTS. THE SIZE OF THE ORIGINAL " &
                   "RECORD AND OF THE PACKED RECORD IS" &
                   INTEGER'IMAGE (PACKED_MIX_REC'SIZE));
     ELSE
          FAILED ("THE SIZE OF THE PACKED RECORD IS GREATER " &
                  "THAN THAT OF THE ORIGINAL RECORD");
     END IF;

     IF PACKED_MIX_REC'SIZE = (INTEGER'SIZE * 4) + 6 THEN
          COMMENT ("THE SIZE OF THE PACKED RECORD IS MINIMAL");
     END IF;

     IF REC1.B1 /= REC2.B1 OR REC1.B2 /= REC2.B2 OR
        REC1.B3 /= REC2.B3 OR REC1.B4 /= REC2.B4 OR
        REC1.B5 /= REC2.B5 OR REC1.B6 /= REC2.B6 OR
        REC1.I1 /= REC2.I1 OR REC1.I2 /= REC2.I2 OR
        REC1.I3 /= REC2.I3 OR REC1.I4 /= REC2.I4 THEN
           FAILED ("INCORRECT VALUES FOR COMPONENTS OF PACKED " &
                   "RECORDS");
     END IF;

     IF REC1.B1'POSITION /= REC2.B1'POSITION OR
        REC1.B1'FIRST_BIT /= REC2.B1'FIRST_BIT OR
        REC1.B2'POSITION /= REC2.B2'POSITION OR
        REC1.B2'FIRST_BIT /= REC2.B2'FIRST_BIT OR
        REC1.B3'POSITION /= REC2.B3'POSITION OR
        REC1.B3'FIRST_BIT /= REC2.B3'FIRST_BIT OR
        REC1.B4'POSITION /= REC2.B4'POSITION OR
        REC1.B4'FIRST_BIT /= REC2.B4'FIRST_BIT OR
        REC1.B5'POSITION /= REC2.B5'POSITION OR
        REC1.B5'FIRST_BIT /= REC2.B5'FIRST_BIT OR
        REC1.B6'POSITION /= REC2.B6'POSITION OR
        REC1.B6'FIRST_BIT /= REC2.B6'FIRST_BIT OR
        REC1.I1'POSITION /= REC2.I1'POSITION OR
        REC1.I1'FIRST_BIT /= REC2.I1'FIRST_BIT OR
        REC1.I2'POSITION /= REC2.I2'POSITION OR
        REC1.I2'FIRST_BIT /= REC2.I2'FIRST_BIT OR
        REC1.I3'POSITION /= REC2.I3'POSITION OR
        REC1.I3'FIRST_BIT /= REC2.I3'FIRST_BIT OR
        REC1.I4'POSITION /= REC2.I4'POSITION OR
        REC1.I4'FIRST_BIT /= REC2.I4'FIRST_BIT THEN
          COMMENT ("COMPONENT ORDER WAS CHANGED");
     END IF;

     IF REC1'SIZE < MIX_REC'SIZE THEN
          FAILED ("OBJECT SIZE TOO SMALL -- MIX_REC. " &
                  "FIRST VALUE IS " &
                  BOOLEAN'IMAGE(IDENT_BOOL(REC1.B1)) );
     END IF;

     RESULT;

END CD1D01C;
