-- CD1D01A.ADA

-- OBJECTIVE:
--     CHECK WHETHER A PRAGMA PACK IS OBEYED FOR AN ARRAY HAVING
--     A BOOLEAN OR CHARACTER COMPONENT TYPE. CHECK WHETHER THE SIZE
--     IS AFFECTED AND, IF SO, WHETHER THE MINIMUM SPACE IS USED.

-- HISTORY:
--     RJW 08/12/87 CREATED ORIGINAL TEST.
--     DHH 04/04/89 CHANGED CHECK ON PACKED CHARACTER ARRAY FROM 70 TO
--                  10 * CHARACTER'SIZE.

WITH REPORT; USE REPORT;
PROCEDURE CD1D01A IS

     TYPE BOOL_ARRAY IS ARRAY (1 .. 10) OF BOOLEAN;

     TYPE PACKED_BOOL_ARRAY IS ARRAY (1 .. 10) OF BOOLEAN;

     PRAGMA PACK (PACKED_BOOL_ARRAY);

     TYPE CHAR_ARRAY IS ARRAY (1 .. 10) OF CHARACTER;

     TYPE PACKED_CHAR_ARRAY IS ARRAY (1 .. 10) OF CHARACTER;

     PRAGMA PACK (PACKED_CHAR_ARRAY);

BEGIN

     TEST("CD1D01A", "CHECK WHETHER A PRAGMA PACK IS OBEYED FOR " &
                     "FOR AN ARRAY HAVING A BOOLEAN OR CHARACTER " &
                     "COMPONENT TYPE. CHECK WHETHER THE SIZE " &
                     "IS AFFECTED AND, IF SO, WHETHER THE MINIMUM " &
                     "SPACE IS USED");

     IF BOOL_ARRAY'SIZE > PACKED_BOOL_ARRAY'SIZE THEN
          COMMENT ("PRAGMA PACK WAS OBEYED FOR A BOOLEAN ARRAY " &
                   "WITH TEN COMPONENTS. " &
                   "THE SIZE OF THE ORIGINAL ARRAY IS" &
                   INTEGER'IMAGE (BOOL_ARRAY'SIZE) & "; " &
                   "THE SIZE OF THE PACKED ARRAY IS" &
                   INTEGER'IMAGE (PACKED_BOOL_ARRAY'SIZE));
     ELSIF BOOL_ARRAY'SIZE = PACKED_BOOL_ARRAY'SIZE THEN
          COMMENT ("PRAGMA PACK HAD NO EFFECT ON A BOOLEAN ARRAY " &
                   "WITH TEN COMPONENTS. " &
                   "THE SIZE OF THE ORIGINAL ARRAY AND OF THE " &
                   "PACKED ARRAY IS" &
                   INTEGER'IMAGE (PACKED_BOOL_ARRAY'SIZE));
     ELSE
          FAILED ("THE SIZE OF THE PACKED BOOLEAN ARRAY IS GREATER " &
                  "THAN THAT OF THE ORIGINAL ARRAY");
     END IF;

     IF PACKED_BOOL_ARRAY'SIZE = 10 THEN
          COMMENT ("THE PACKED BOOLEAN ARRAY USES MINIMAL SIZE");
     END IF;

     IF CHAR_ARRAY'SIZE > PACKED_CHAR_ARRAY'SIZE THEN
          COMMENT ("PRAGMA PACK WAS OBEYED FOR A CHARACTER ARRAY " &
                   "WITH TEN COMPONENTS. " &
                   "THE SIZE OF THE ORIGINAL ARRAY IS" &
                   INTEGER'IMAGE (CHAR_ARRAY'SIZE) & "; " &
                   "THE SIZE OF THE PACKED ARRAY IS" &
                   INTEGER'IMAGE (PACKED_CHAR_ARRAY'SIZE));
     ELSIF CHAR_ARRAY'SIZE = PACKED_CHAR_ARRAY'SIZE THEN
          COMMENT ("PRAGMA PACK HAD NO EFFECT ON A CHARACTER ARRAY " &
                   "WITH TEN COMPONENTS. " &
                   "THE SIZE OF THE ORIGINAL ARRAY AND OF THE " &
                   "PACKED ARRAY IS" &
                   INTEGER'IMAGE (PACKED_CHAR_ARRAY'SIZE));
     ELSE
          FAILED ("THE SIZE OF THE PACKED CHARCTER ARRAY IS " &
                  "GREATER THAN THAT OF THE ORIGINAL ARRAY");
     END IF;

     IF PACKED_CHAR_ARRAY'SIZE <= 10 * CHARACTER'SIZE THEN
          COMMENT ("THE PACKED CHARACTER ARRAY USES MINIMAL SIZE");
     END IF;

     RESULT;

END CD1D01A;
