-- CD1D01D.ADA

-- OBJECTIVE:
--     CHECK WHETHER A PRAGMA PACK IS OBEYED FOR A RECORD
--     HAVING BOOLEAN COMPONENTS SEPARATED BY SMALL INTEGER
--     COMPONENTS.  CHECK WHETHER THE SIZE IS AFFECTED AND
--     WHETHER THE MINIMUM IS USED.

-- HISTORY:
--     JET 08/13/87 CREATED ORIGINAL TEST.
--     PWB 03/27/89 MODIFIED TESTING OF OBJECT SIZE.

WITH REPORT; USE REPORT;
PROCEDURE CD1D01D IS

     TYPE SMALL_INT IS RANGE -100 .. 100;

     TYPE MIX_REC IS RECORD
          B1: BOOLEAN;
          I1: SMALL_INT;
          B2: BOOLEAN;
          I2: SMALL_INT;
          B3, B4, B5: BOOLEAN;
          I3, I4: SMALL_INT;
          B6: BOOLEAN;
     END RECORD;

     TYPE PACKED_MIX_REC IS RECORD
          B1: BOOLEAN;
          I1: SMALL_INT;
          B2: BOOLEAN;
          I2: SMALL_INT;
          B3, B4, B5: BOOLEAN;
          I3, I4: SMALL_INT;
          B6: BOOLEAN;
     END RECORD;

     PRAGMA PACK (PACKED_MIX_REC);

     X : PACKED_MIX_REC := ( B1 => IDENT_BOOL(TRUE),
                             I1 => SMALL_INT(IDENT_INT(1)),
                             I2 | I3 | I4 => SMALL_INT(IDENT_INT(2)),
                             OTHERS => IDENT_BOOL(FALSE) );
BEGIN

     TEST("CD1D01D", "CHECK WHETHER A PRAGMA PACK IS OBEYED FOR " &
                     "A RECORD HAVING BOOLEAN COMPONENTS SEPARATED " &
                     "BY SMALL INTEGER COMPONENTS.  CHECK WHETHER " &
                     "THE SIZE IS AFFECTED AND WHETHER THE MINIMUM " &
                     "IS USED");

     IF MIX_REC'SIZE > PACKED_MIX_REC'SIZE THEN
          COMMENT ("PRAGMA PACK WAS OBEYED FOR A RECORD WITH FOUR " &
                   "SMALL-INTEGER AND SIX BOOLEAN COMPONENTS. " &
                   "THE SIZE OF THE ORIGINAL RECORD IS" &
                   INTEGER'IMAGE (MIX_REC'SIZE) & "; " &
                   "THE SIZE OF THE PACKED RECORD IS" &
                   INTEGER'IMAGE (PACKED_MIX_REC'SIZE));
     ELSIF MIX_REC'SIZE = PACKED_MIX_REC'SIZE THEN
          COMMENT ("PRAGMA PACK HAD NO EFFECT ON THE SIZE " &
                   "OF A RECORD WITH FOUR SMALL-INTEGER AND SIX " &
                   "BOOLEAN COMPONENTS. " &
                   "THE SIZE OF THE ORIGINAL RECORD AND OF THE " &
                   "PACKED RECORD IS" &
                   INTEGER'IMAGE (PACKED_MIX_REC'SIZE));
     ELSE
          FAILED ("THE SIZE OF A RECORD WITH FOUR SMALL-INTEGER " &
                  "AND SIX BOOLEAN COMPONENTS IS GREATER " &
                  "WHEN PACKED");
     END IF;

     IF X'SIZE < PACKED_MIX_REC'SIZE THEN
          FAILED ("PACKED OBJECT SIZE IS LESS THAN PACKED RECORD " &
                  "TYPE SIZE.  REPRESENTATIVE VALUE IS" &
                  SMALL_INT'IMAGE (X.I1) );
     END IF;

     IF PACKED_MIX_REC'SIZE = 4*SMALL_INT'SIZE + 6 THEN
          COMMENT ("THE SIZE OF THE PACKED RECORD IS MINIMAL");
     END IF;

     RESULT;

END CD1D01D;
