-- CD2A53A.ADA

-- OBJECTIVE:
--     CHECK THAT WHEN SIZE AND SMALL SPECIFICATIONS ARE GIVEN FOR A
--     FIXED POINT TYPE, THEN OPERATIONS ON VALUES OF SUCH A TYPE ARE
--     NOT AFFECTED BY THE REPRESENTATION CLAUSE.

-- HISTORY:
--     BCB 08/24/87  CREATED ORIGINAL TEST.
--     DHH 04/12/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA', CHANGED
--                   OPERATORS ON 'SIZE TESTS, AND CHANGED 'SIZE CLAUSE
--                   SO THAT IT IS NOT A POWER OF TWO.

WITH REPORT; USE REPORT;
PROCEDURE CD2A53A IS
     BASIC_SIZE : CONSTANT := 15;
     BASIC_SMALL : CONSTANT := 0.01;

     ZERO  : CONSTANT :=  0.0;

     TYPE CHECK_TYPE IS DELTA 1.0 RANGE -4.0 .. 4.0;

     FOR CHECK_TYPE'SMALL USE BASIC_SMALL;
     FOR CHECK_TYPE'SIZE USE BASIC_SIZE;

     CNEG1 : CHECK_TYPE := -2.7;
     CNEG2 : CHECK_TYPE := CHECK_TYPE (-1.0/3.0);
     CPOS1 : CHECK_TYPE := CHECK_TYPE (4.0/6.0);
     CPOS2 : CHECK_TYPE :=  2.7;
     CZERO : CHECK_TYPE;

     TYPE ARRAY_TYPE IS ARRAY (0 .. 3) OF CHECK_TYPE;
     CHARRAY : ARRAY_TYPE :=
          (-2.7, CHECK_TYPE (-1.0/3.0), CHECK_TYPE (4.0/6.0), 2.7);

     TYPE REC_TYPE IS RECORD
          COMPF : CHECK_TYPE := -2.7;
          COMPN : CHECK_TYPE := CHECK_TYPE (-1.0/3.0);
          COMPP : CHECK_TYPE := CHECK_TYPE (4.0/6.0);
          COMPL : CHECK_TYPE :=  2.7;
     END RECORD;

     CHREC : REC_TYPE;

     FUNCTION IDENT (FX : CHECK_TYPE) RETURN CHECK_TYPE IS
     BEGIN
          IF EQUAL (3, 3) THEN
               RETURN FX;
          ELSE
               RETURN 0.0;
          END IF;
     END IDENT;

     PROCEDURE PROC (CN1IN, CP1IN      :        CHECK_TYPE;
                     CN2INOUT,CP2INOUT : IN OUT CHECK_TYPE;
                     CZOUT             :    OUT CHECK_TYPE) IS
     BEGIN

          IF IDENT (CN1IN) + CP1IN NOT IN -2.04 .. -2.03 OR
             CP2INOUT  - IDENT (CP1IN) NOT IN 2.03 .. 2.04 THEN
               FAILED ("INCORRECT RESULTS FOR " &
                       "BINARY ADDING OPERATORS - 1");
          END IF;

          IF +IDENT (CN2INOUT) NOT IN -0.34 .. -0.33 OR
             IDENT (-CP1IN) NOT IN -0.67 .. -0.66 THEN
               FAILED ("INCORRECT RESULTS FOR " &
                       "UNARY ADDING OPERATORS - 1");
          END IF;

          IF CHECK_TYPE (CN1IN * IDENT (CP1IN)) NOT IN
             -1.81 .. -1.78 OR
             CHECK_TYPE (IDENT (CN2INOUT) / CP2INOUT) NOT IN
             -0.13 .. -0.12 THEN
               FAILED ("INCORRECT RESULTS FOR " &
                       "MULTIPLYING OPERATORS - 1");
          END IF;

          IF ABS IDENT (CN2INOUT) NOT IN 0.33 .. 0.34 OR
             IDENT (ABS CP1IN) NOT IN 0.66 .. 0.670 THEN
               FAILED ("INCORRECT RESULTS FOR " &
                       "ABSOLUTE VALUE OPERATORS - 1");
          END IF;

          IF IDENT (CP1IN) NOT IN 0.66 .. 0.670 OR
                 CN2INOUT IN -0.32 .. 0.0 OR
                 IDENT (CN2INOUT) IN -1.0 .. -0.35 THEN
               FAILED ("INCORRECT RESULTS FOR MEMBERSHIP " &
                       "OPERATORS - 1");
          END IF;

          CZOUT := 0.0;

     END PROC;

BEGIN
     TEST ("CD2A53A", "CHECK THAT WHEN SIZE AND SMALL SPECIFICATIONS " &
                      "ARE GIVEN FOR A FIXED POINT TYPE, THEN " &
                      "OPERATIONS ON VALUES OF SUCH A TYPE ARE NOT " &
                      "AFFECTED BY THE REPRESENTATION CLAUSE");

     PROC (CNEG1, CPOS1, CNEG2, CPOS2, CZERO);

     IF CNEG1'SIZE < IDENT_INT(BASIC_SIZE) THEN
          FAILED ("INCORRECT VALUE FOR CNEG1'SIZE");
     END IF;

     IF IDENT (CZERO) /= ZERO THEN
          FAILED ("INCORRECT VALUE FOR OUT PARAMETER");
     END IF;

     IF CHECK_TYPE'FIRST > IDENT (-3.99) THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'FIRST");
     END IF;

     IF CHECK_TYPE'LAST < IDENT (3.99) THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'LAST");
     END IF;

     IF CHECK_TYPE'SIZE /= IDENT_INT (BASIC_SIZE) THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'SIZE");
     END IF;

     IF CHECK_TYPE'SMALL /= BASIC_SMALL THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'SMALL");
     END IF;

     IF CHECK_TYPE'LARGE /= (2 ** CHECK_TYPE'MANTISSA -1) * 0.01 THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'LARGE");
     END IF;

     IF CHECK_TYPE'AFT /= 1 THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'AFT");
     END IF;

     IF CHECK_TYPE'FORE /= 2 THEN
          FAILED ("INCORRECT VALUE FOR CHECK_TYPE'FORE");
     END IF;

     IF IDENT (CNEG1) + CPOS1 NOT IN -2.04 .. -2.03 OR
        CPOS2  - IDENT (CPOS1) NOT IN 2.03 .. 2.04 THEN
          FAILED ("INCORRECT RESULTS FOR BINARY ADDING OPERATORS - 2");
     END IF;

     IF +IDENT (CNEG2) NOT IN -0.34 .. -0.33 OR
        IDENT (-CPOS1) NOT IN -0.67 .. -0.66 THEN
          FAILED ("INCORRECT RESULTS FOR UNARY ADDING OPERATORS - 2");
     END IF;

     IF CHECK_TYPE (CNEG1 * IDENT (CPOS1)) NOT IN
          -1.81 .. -1.78 OR
        CHECK_TYPE (IDENT (CNEG2) / CPOS2) NOT IN
          -0.13 .. -0.12 THEN
          FAILED ("INCORRECT RESULTS FOR MULTIPLYING OPERATORS - 2");
     END IF;

     IF ABS IDENT (CNEG2) NOT IN 0.33 .. 0.34 OR
        IDENT (ABS CPOS1) NOT IN 0.66 .. 0.670 THEN
          FAILED ("INCORRECT RESULTS FOR ABSOLUTE VALUE " &
                  "OPERATORS - 2");
     END IF;

     IF IDENT (CPOS1) NOT IN 0.66 .. 0.670 OR
            CNEG2 IN -0.32 .. 0.0 OR
            IDENT (CNEG2) IN -1.0 .. -0.35 THEN
          FAILED ("INCORRECT RESULTS FOR MEMBERSHIP " &
                  "OPERATORS - 2");
     END IF;

     IF CHARRAY(1)'SIZE < IDENT_INT (BASIC_SIZE) THEN
          FAILED ("INCORRECT VALUE FOR CHARRAY(1)'SIZE");
     END IF;

     IF IDENT (CHARRAY (0)) + CHARRAY (2) NOT IN
             -2.04 .. -2.03 OR
        CHARRAY (3)  - IDENT (CHARRAY (2)) NOT IN
             2.03 .. 2.04 THEN
          FAILED ("INCORRECT RESULTS FOR BINARY ADDING OPERATORS - 3");
     END IF;

     IF +IDENT (CHARRAY (1)) NOT IN -0.34 .. -0.33 OR
        IDENT (-CHARRAY (2)) NOT IN -0.67 .. -0.66 THEN
          FAILED ("INCORRECT RESULTS FOR UNARY ADDING OPERATORS - 3");
     END IF;

     IF CHECK_TYPE (CHARRAY (0) * IDENT (CHARRAY (2))) NOT IN
          -1.81 .. -1.78 OR
        CHECK_TYPE (IDENT (CHARRAY (1)) / CHARRAY (3)) NOT IN
          -0.13 .. -0.12 THEN
          FAILED ("INCORRECT RESULTS FOR MULTIPLYING OPERATORS - 3");
     END IF;

     IF ABS IDENT (CHARRAY (1)) NOT IN 0.33 .. 0.34 OR
        IDENT (ABS CHARRAY (2)) NOT IN 0.66 .. 0.670 THEN
          FAILED ("INCORRECT RESULTS FOR ABSOLUTE VALUE " &
                  "OPERATORS - 3");
     END IF;

     IF IDENT (CHARRAY (2)) NOT IN 0.66 .. 0.670 OR
            CHARRAY (1) IN -0.32 .. 0.0 OR
            IDENT (CHARRAY (1)) IN -1.0 .. -0.35 THEN
          FAILED ("INCORRECT RESULTS FOR MEMBERSHIP " &
                  "OPERATORS - 3");
     END IF;

     IF CHREC.COMPP'SIZE < IDENT_INT (BASIC_SIZE) THEN
          FAILED ("INCORRECT VALUE FOR CHREC.COMPP'SIZE");
     END IF;

     IF IDENT (CHREC.COMPF) + CHREC.COMPP NOT IN
             -2.04 .. -2.03 OR
        CHREC.COMPL  - IDENT (CHREC.COMPP) NOT IN
             2.03 .. 2.04 THEN
          FAILED ("INCORRECT RESULTS FOR BINARY ADDING OPERATORS - 4");
     END IF;

     IF +IDENT (CHREC.COMPN) NOT IN -0.34 .. -0.33 OR
        IDENT (-CHREC.COMPP) NOT IN -0.67 .. -0.66 THEN
          FAILED ("INCORRECT RESULTS FOR UNARY ADDING OPERATORS - 4");
     END IF;

     IF CHECK_TYPE (CHREC.COMPF * IDENT (CHREC.COMPP)) NOT IN
          -1.81 .. -1.78 OR
        CHECK_TYPE (IDENT (CHREC.COMPN) / CHREC.COMPL) NOT IN
          -0.13 .. -0.12 THEN
          FAILED ("INCORRECT RESULTS FOR MULTIPLYING OPERATORS - 4");
     END IF;

     IF ABS IDENT (CHREC.COMPN) NOT IN 0.33 .. 0.34 OR
        IDENT (ABS CHREC.COMPP) NOT IN 0.66 .. 0.670 THEN
          FAILED ("INCORRECT RESULTS FOR ABSOLUTE VALUE " &
                  "OPERATORS - 4");
     END IF;

     IF IDENT (CHREC.COMPP) NOT IN 0.66 .. 0.670 OR
            CHREC.COMPN IN -0.32 .. 0.0 OR
            IDENT (CHREC.COMPN) IN -1.0 .. -0.35 THEN
          FAILED ("INCORRECT RESULTS FOR MEMBERSHIP " &
                  "OPERATORS - 4");
     END IF;

     RESULT;
END CD2A53A;
