-- CD2B11D.ADA

-- OBJECTIVE:
--     CHECK THAT THE EXPRESSION IN A COLLECTION SIZE CLAUSE
--     FOR AN ACCESS TYPE NEED NOT BE STATIC.

-- HISTORY:
--     BCB 09/23/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;

PROCEDURE CD2B11D IS

     TYPE CHECK_TYPE IS ACCESS INTEGER;
     FOR CHECK_TYPE'STORAGE_SIZE USE 256;

     TYPE ACC_TYPE IS ACCESS INTEGER;
     FOR ACC_TYPE'STORAGE_SIZE USE IDENT_INT (256);

BEGIN

     TEST ("CD2B11D", "CHECK THAT THE EXPRESSION IN A COLLECTION " &
                      "SIZE SPECIFICATION FOR AN ACCESS TYPE "&
                      "NEED NOT BE STATIC");

     IF ACC_TYPE'STORAGE_SIZE < IDENT_INT (256) THEN
          FAILED ("INCORRECT VALUE FOR STORAGE_SIZE");
     END IF;

     RESULT;
END CD2B11D;
