-- CD2B16A.ADA

-- OBJECTIVE:
--     IF A COLLECTION SIZE CLAUSE IS GIVEN FOR A PARENT ACCESS TYPE,
--     THEN THE DERIVED TYPE HAS THE SAME COLLECTION SIZE, WHETHER THE
--     DERIVED TYPE IS DECLARED BEFORE OR AFTER THE PARENT COLLECTION
--     SIZE SPECIFICATION.

-- HISTORY:
--     DHH 09/29/87 CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE CD2B16A IS
BEGIN
     TEST ("CD2B16A", "IF A COLLECTION SIZE IS GIVEN FOR A " &
                      "PARENT ACCESS TYPE, THEN THE DERIVED TYPE HAS " &
                      "THE SAME COLLECTION SIZE, WHETHER THE " &
                      "DERIVED TYPE IS DECLARED BEFORE OR AFTER " &
                      "THE PARENT COLLECTION SIZE SPECIFICATION");

          DECLARE

               COLLECTION_SIZE : CONSTANT :=128;
               TYPE V IS ARRAY(1..4) OF INTEGER;

               TYPE CELL IS
                    RECORD
                         VALUE : V;
                    END RECORD;

               TYPE LINK IS ACCESS CELL;
               TYPE NEWLINK1 IS NEW LINK;

               FOR LINK'STORAGE_SIZE USE
                                     COLLECTION_SIZE;

               TYPE NEWLINK2 IS NEW LINK;

          BEGIN    -- ACTIVE DECLARE

               IF LINK'STORAGE_SIZE < COLLECTION_SIZE THEN
                    FAILED("STORAGE_SIZE SMALLER THAN STORAGE_SIZE " &
                           "SPECIFIED WAS ALLOCATED");
               END IF;

               IF LINK'STORAGE_SIZE /= NEWLINK1'STORAGE_SIZE THEN
                    FAILED("STORAGE_SIZE OF THE FIRST DERIVED TYPE" &
                           "IS NOT THE SAME SIZE AS THAT OF THE " &
                           "PARENT");
               END IF;

               IF LINK'STORAGE_SIZE /= NEWLINK2'STORAGE_SIZE THEN
                    FAILED("STORAGE_SIZE OF THE SECOND DERIVED TYPE" &
                           "IS NOT THE SAME SIZE AS THAT OF THE " &
                           "PARENT");
               END IF;

          END;    --ACTIVE DECLARE

     RESULT;
END CD2B16A;
