-- CD2D13A.ADA

-- OBJECTIVE:
--     CHECK THAT A SMALL CLAUSE CAN BE GIVEN IN THE VISIBLE
--     OR PRIVATE PART OF A PACKAGE FOR A FIXED POINT TYPE DECLARED
--     IN THE VISIBLE PART.

-- HISTORY:
--     BCB 09/01/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; WITH TEXT_IO;
WITH REPORT; USE REPORT;
PROCEDURE CD2D13A IS

     SPECIFIED_SMALL : CONSTANT := 2.0 ** (-4);

     PACKAGE P IS
          TYPE FIXED_IN_P IS DELTA 1.0 RANGE -4.0 .. 4.0;
          FOR FIXED_IN_P'SMALL USE SPECIFIED_SMALL;
          TYPE ALT_FIXED_IN_P IS DELTA 1.0 RANGE -4.0 .. 4.0;
     PRIVATE
          FOR ALT_FIXED_IN_P'SMALL USE SPECIFIED_SMALL;
     END P;

     USE P;

BEGIN

     TEST("CD2D13A", "A SMALL CLAUSE CAN BE GIVEN IN THE VISIBLE " &
                     "OR PRIVATE PART OF A PACKAGE FOR A FIXED " &
                     "POINT TYPE DECLARED IN THE VISIBLE PART");

     IF FIXED_IN_P'SMALL /= SPECIFIED_SMALL THEN
          FAILED ("INCORRECT VALUE FOR FIXED_IN_P'SMALL");
     END IF;

     IF ALT_FIXED_IN_P'SMALL /= SPECIFIED_SMALL THEN
          FAILED ("INCORRECT VALUE FOR ALT_FIXED_IN_P'SMALL");
     END IF;

     RESULT;

END CD2D13A;
