-- CD3015F.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION REPRESENTATION CLAUSE FOR A DERIVED
--     TYPE CAN BE GIVEN IN THE VISIBLE OR PRIVATE PART OF A GENERIC
--     PACKAGE FOR A DERIVED TYPE DECLARED IN THE VISIBLE PART, WHERE
--     NO ENUMERATION CLAUSE HAS BEEN GIVEN FOR THE PARENT.

-- HISTORY
--     DHH 10/01/87 CREATED ORIGINAL TEST
--     DHH 03/27/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA',CHANGED
--                   FROM 'A' TEST TO 'C' TEST AND ADDED CHECK FOR
--                   REPRESENTATION CLAUSE.

WITH REPORT; USE REPORT;
WITH ENUM_CHECK;            -- CONTAINS A CALL TO 'FAILED'.
PROCEDURE CD3015F IS

BEGIN

     TEST ("CD3015F", "CHECK THAT AN " &
                      "ENUMERATION REPRESENTATION CLAUSE FOR A " &
                      "DERIVED TYPE CAN BE GIVEN IN THE VISIBLE OR " &
                      "PRIVATE PART OF A GENERIC PACKAGE FOR A " &
                      "DERIVED TYPE DECLARED IN THE VISIBLE PART, " &
                      "WHERE NO ENUMERATION CLAUSE HAS BEEN GIVEN " &
                      "FOR THE PARENT");

     DECLARE

          GENERIC
          PACKAGE GENPACK IS

               TYPE MAIN IS (RED,BLUE,YELLOW,'R','B','Y');

               TYPE HUE IS NEW MAIN;
               TYPE NEWHUE IS NEW MAIN;

               FOR HUE USE (RED => 8, BLUE => 9, YELLOW => 10,
                     'R' => 11, 'B' => 12, 'Y' => 13);

          PRIVATE
               FOR NEWHUE USE (RED => 8, BLUE => 9, YELLOW => 10,
                     'R' => 11, 'B' => 12, 'Y' => 13);

               TYPE INT_HUE IS RANGE 8 .. 13;
               FOR INT_HUE'SIZE USE HUE'SIZE;

               TYPE INT_NEW IS RANGE 8 .. 13;
               FOR INT_NEW'SIZE USE NEWHUE'SIZE;

               PROCEDURE CHECK_HUE IS NEW ENUM_CHECK(HUE, INT_HUE);
               PROCEDURE CHECK_NEW IS NEW ENUM_CHECK(NEWHUE, INT_NEW);

          END GENPACK;

          PACKAGE BODY GENPACK IS

          BEGIN
               CHECK_HUE (RED, 8, "HUE");
               CHECK_HUE ('R', 11, "NEWHUE");
          END GENPACK;

          PACKAGE P IS NEW GENPACK;

     BEGIN
          NULL;
     END;

     RESULT;
END CD3015F;
