-- CD3022A.ADA

-- OBJECTIVE:
--     AN ENUMERATION REPRESENTATION CLAUSE WITH CONTIGUOUS OR
--     NONCONTIGUOUS CODES CAN BE GIVEN FOR A TYPE DERIVED FROM A
--     TYPE DECLARED IN A GENERIC INSTANTIATION. USE THE CASE IN WHICH
--     THE PARENT TYPE IS DERIVED FROM A GENERIC FORMAL TYPE.

-- HISTORY:
--     JKC 04/12/88  CREATED ORIGINAL TEST.
--     DHH 03/27/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA',CHANGED
--                   FROM 'A' TEST TO 'C' TEST AND ADDED CHECK FOR
--                   REPRESENTATION CLAUSE.

WITH REPORT; USE REPORT;
WITH ENUM_CHECK;            -- CONTAINS A CALL TO 'FAILED'.
PROCEDURE CD3022A IS

     GENERIC
          TYPE T IS (<>);
     PACKAGE GENERIC_P IS
          TYPE DT IS NEW T;
     END GENERIC_P;

     TYPE ENUM IS (R, S, T);

     PACKAGE INST IS NEW GENERIC_P(ENUM);

     TYPE D_ENUM IS NEW INST.DT;
     FOR D_ENUM USE (1,2,3);

     TYPE D_ENUM2 IS NEW INST.DT;
     FOR D_ENUM2 USE (10,20,30);

     TYPE INT_D_ENUM IS RANGE 1 .. 3;
     FOR INT_D_ENUM'SIZE USE D_ENUM'SIZE;

     TYPE INT_D_ENUM2 IS RANGE 10 .. 30;
     FOR INT_D_ENUM2'SIZE USE D_ENUM2'SIZE;

     PROCEDURE CHECK_D_ENUM IS NEW ENUM_CHECK(D_ENUM, INT_D_ENUM);
     PROCEDURE CHECK_D_ENUM2 IS NEW ENUM_CHECK(D_ENUM2, INT_D_ENUM2);

BEGIN
     TEST ("CD3022A", "AN ENUMERATION REPRESENTATION CLAUSE WITH " &
                      "CONTIGUOUS OR WITH NONCONTIGUOUS " &
                      "CODES CAN BE GIVEN FOR A TYPE DERIVED FROM " &
                      "AN ENUMERATION TYPE DECLARED IN A GENERIC " &
                      "INSTANTIATION.  THE PARENT TYPE IS DERIVED " &
                      "FROM A GENERIC FORMAL TYPE");

     CHECK_D_ENUM (R, 1, "D_ENUM");
     CHECK_D_ENUM2 (T, 30, "D_ENUM2");

     RESULT;
END CD3022A;
