-- CD3014C.ADA

-- OBJECTIVE:
--     CHECK THAT AN ENUMERATION REPRESENTATION CLAUSE CAN BE GIVEN IN
--     THE VISIBLE OR PRIVATE PART OF A PACKAGE FOR A TYPE DECLARED IN
--     THE VISIBLE PART.

-- HISTORY
--     DHH 09/30/87 CREATED ORIGINAL TEST
--     DHH 03/27/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA',CHANGED
--                   FROM 'A' TEST TO 'C' TEST AND ADDED CHECK FOR
--                   REPRESENTATION CLAUSE.

WITH REPORT; USE REPORT;
WITH ENUM_CHECK;        -- CONTAINS CALL TO 'FAILED'
PROCEDURE CD3014C IS

BEGIN

     TEST ("CD3014C", "CHECK THAT AN ENUMERATION " &
                      "REPRESENTATION CLAUSE CAN BE GIVEN IN THE " &
                      "VISIBLE OR PRIVATE PART OF A PACKAGE FOR " &
                      "A TYPE DECLARED IN THE VISIBLE PART");

     DECLARE
          PACKAGE PACK IS

               TYPE HUE IS (RED,BLUE,YELLOW);
               TYPE NEWHUE IS (RED,BLUE,YELLOW);

               FOR HUE USE
                         (RED => 8, BLUE => 16,
                                      YELLOW => 32);
               A : HUE := BLUE;
          PRIVATE

               FOR NEWHUE USE (RED => 8, BLUE => 16, YELLOW => 32);

               B : NEWHUE := RED;

               TYPE INT_HUE IS RANGE 8 .. 32;
               FOR INT_HUE'SIZE USE HUE'SIZE;

               TYPE INT_NEW IS RANGE 8 .. 32;
               FOR INT_NEW'SIZE USE NEWHUE'SIZE;

               PROCEDURE CHECK_HUE IS NEW ENUM_CHECK(HUE, INT_HUE);
               PROCEDURE CHECK_NEW IS NEW ENUM_CHECK(NEWHUE, INT_NEW);

          END PACK;

          PACKAGE BODY PACK IS
          BEGIN
               CHECK_HUE (RED, 8, "HUE");
               CHECK_NEW (YELLOW, 32, "NEWHUE");
          END PACK;

     BEGIN
          NULL;
     END;

     RESULT;
END CD3014C;
