-- CD4022A.ADA

-- OBJECTIVE:
--     CHECK THAT A COMPONENT CLAUSE GIVEN FOR A COMPONENT
--     WITH AN INTEGER SUBTYPE CAN SPECIFY LESS THAN THE USUAL AMOUNT
--     OF SPACE ALLOCATED TO A VARIABLE OF THAT SUBTYPE.

-- HISTORY:
--     BCB 09/14/88  CREATED ORIGINAL TEST.
--     DHH 03/27/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA',CHANGED
--                   FROM 'A' TEST TO 'C' TEST AND ADDED CHECK FOR
--                   REPRESENTATION CLAUSE.

WITH REPORT; USE REPORT;
WITH LENGTH_CHECK;                 -- CONTAINS A CALL TO 'FAILED'.
PROCEDURE CD4022A IS

     SUBTYPE SUBINTEGER IS INTEGER RANGE -1 .. 1;

     CHECK_SIZE : CONSTANT INTEGER := INTEGER'SIZE/2;

     TYPE REC IS RECORD
          RECVAR : SUBINTEGER;
     END RECORD;

     FOR REC USE RECORD
          RECVAR AT 0 RANGE 0 .. CHECK_SIZE-1;
     END RECORD;

     REC1 : REC := (RECVAR => 1);

     PROCEDURE LEN_REC IS NEW LENGTH_CHECK (REC);
BEGIN
     TEST ("CD4022A", "CHECK THAT A COMPONENT CLAUSE GIVEN " &
                      "FOR A COMPONENT WITH AN INTEGER SUBTYPE CAN " &
                      "SPECIFY LESS THAN THE USUAL AMOUNT OF SPACE " &
                      "ALLOCATED TO A VARIABLE OF THAT SUBTYPE");

     LEN_REC (REC1, CHECK_SIZE-1, "REC");
     RESULT;
END CD4022A;
