-- CD4031A.ADA

-- OBJECTIVE:
--     CHECK THAT IF A RECORD REPRESENTATION CLAUSE IS PERMITTED FOR A
--     VARIANT RECORD TYPE, THEN COMPONENTS BELONGING TO DIFFERENT
--     VARIANTS CAN BE GIVEN OVERLAPPING STORAGE.

-- HISTORY:
--     PWB 07/22/87  CREATED ORIGINAL TEST.
--     DHH 03/27/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA' AND
--                   ADDED CHECK FOR REPRESENTATION CLAUSE.

WITH REPORT; USE REPORT;
WITH SYSTEM;
WITH LENGTH_CHECK;                      -- CONTAINS A CALL TO 'FAILED'.
PROCEDURE CD4031A IS

     TYPE DISCRIMINAN IS RANGE -2 .. 1;
     TYPE INT IS RANGE -4 .. 3;
     TYPE LARGE_INT IS RANGE -8 .. 7;

     TYPE TEST_CLAUSE (DISC : DISCRIMINAN := 0) IS
          RECORD
               CASE DISC IS
                    WHEN 0 =>
                         INTEGER_COMP : LARGE_INT;
                    WHEN OTHERS  =>
                         CH_COMP_1 : INT;
                         CH_COMP_2 : INT;
               END CASE;
          END RECORD;

     FOR TEST_CLAUSE USE
          RECORD
               DISC AT 0
                           RANGE 0 .. 1;
               INTEGER_COMP AT 0
                           RANGE 2 .. 5;
               CH_COMP_1 AT 0
                           RANGE 2 .. 4;
               CH_COMP_2 AT 0
                           RANGE 5 .. 7;
          END RECORD;

     TYPE TEST_CL1 IS NEW TEST_CLAUSE(DISC => 0);
     TYPE TEST_CL2 IS NEW TEST_CLAUSE(DISC => 1);
     TEST_RECORD : TEST_CL1;
     TEST_RECORD1 : TEST_CL2;

     INTEGER_COMP_FIRST,
     CH_COMP_1_FIRST : INTEGER;

     PROCEDURE REC_LEN1 IS NEW LENGTH_CHECK (TEST_CL1);
     PROCEDURE REC_LEN2 IS NEW LENGTH_CHECK (TEST_CL2);

BEGIN
     TEST ("CD4031A", "IF RECORD REPRESENTATION CLAUSES ARE " &
                      "SUPPORTED FOR VARIANT RECORD TYPES, " &
                      "THEN COMPONENTS OF DIFFERENT VARIANTS " &
                      "CAN BE GIVEN OVERLAPPING STORAGE");

     TEST_RECORD := (0, -8);
     INTEGER_COMP_FIRST := TEST_RECORD.INTEGER_COMP'FIRST_BIT;
     REC_LEN1 (TEST_RECORD, 6, "TEST_RECORD FIRST");

     TEST_RECORD1 := (1, -4, -4);
     CH_COMP_1_FIRST := TEST_RECORD1.CH_COMP_1'FIRST_BIT;
     REC_LEN2 (TEST_RECORD1, 8, "TEST_RECORD SECOND");

     IF INTEGER_COMP_FIRST /= CH_COMP_1_FIRST THEN
          FAILED ("COMPONENTS DO NOT BEGIN AT SAME POINT");
     END IF;

     RESULT;
END CD4031A;
