-- CD4024C.ADA

-- OBJECTIVE:
--     CHECK THAT A COMPONENT CLAUSE GIVEN FOR A FIXED POINT
--     COMPONENT WITH ONLY A DELTA CONSTRAINT CAN SPECIFY LESS SPACE
--     THAN USUALLY ALLOCATED TO A VARIABLE OF THAT SUBTYPE.  THIS TEST
--     CHECKS AN UNSIGNED REPRESENTATION.

-- HISTORY:
--     BCB 09/14/88  CREATED ORIGINAL TEST.
--     DHH 03/29/89  CHANGE FROM 'A' TEST TO 'C' TEST AND FROM '.DEP'
--                   '.ADA'.  ADDED CHECK ON REPRESENTATION CLAUSE.

WITH SYSTEM; USE SYSTEM;
WITH LENGTH_CHECK;                      -- CONTAINS A CALL TO 'FAILED'.
WITH REPORT; USE REPORT;

PROCEDURE CD4024C IS

     TYPE FIX IS DELTA FINE_DELTA RANGE 0.0 .. 1.0;

     SUBTYPE SUBFIX IS FIX DELTA 2.0**(-7);

     CHECK_SIZE : CONSTANT INTEGER := 7;

     TYPE REC IS RECORD
          RECVAR : SUBFIX;
     END RECORD;

     FOR REC USE RECORD
          RECVAR AT 0 RANGE 0 .. CHECK_SIZE-1;
     END RECORD;

     T : REC := (RECVAR => 1.0);

     PROCEDURE CHECK_1 IS NEW LENGTH_CHECK (REC);
BEGIN
     TEST ("CD4024C", "CHECK THAT A COMPONENT CLAUSE GIVEN " &
                      "FOR A FIXED POINT COMPONENT WITH ONLY A DELTA " &
                      "CONSTRAINT CAN SPECIFY LESS SPACE THAN " &
                      "USUALLY ALLOCATED TO A VARIABLE OF THAT " &
                      "SUBTYPE.  THIS TEST CHECKS AN UNSIGNED " &
                      "REPRESENTATION");

     CHECK_1 (T, 7, "REC");

     RESULT;
END CD4024C;
