-- CD4061A.ADA

-- OBJECTIVE:
--     CHECK THAT A SIZE SPECIFICATION CAN BE GIVEN FOR A TYPE THAT
--     ALSO HAS A RECORD REPRESENTATION CLAUSE.

-- HISTORY:
--     BCB 04/11/88  CREATED ORIGINAL TEST.
--     DHH 03/30/88  CHANGED FROM 'E' TEST TO 'C'TEST, CHANGED EXTENSION
--                   FROM '.DEP' TO '.ADA', ADDED TEST OF REPRESENTATION
--                   CLAUSE, AND CHANGED INTEGER'SIZE TO 5;

WITH REPORT; USE REPORT;
WITH LENGTH_CHECK;                      -- CONTAINS A CALL TO 'FAILED'.
PROCEDURE CD4061A IS

     CHECK_SIZE : CONSTANT INTEGER := 5;

     TYPE LITTLE_INT IS RANGE -8 .. 7;

     TYPE REC IS RECORD
          INT : LITTLE_INT;
     END RECORD;

     FOR REC USE RECORD
          INT AT 0 RANGE 0 .. 4;
     END RECORD;

     FOR REC'SIZE USE CHECK_SIZE;

     REC1 : REC := (INT => -7);

     PROCEDURE CHECK_1 IS NEW LENGTH_CHECK (REC);

BEGIN
     TEST ("CD4061A", "CHECK THAT A SIZE SPECIFICATION CAN BE " &
                      "GIVEN FOR A TYPE THAT ALSO HAS A RECORD " &
                      "REPRESENTATION CLAUSE");

     IF REC'SIZE /= CHECK_SIZE THEN
          FAILED ("IMPROPER VALUE FOR REC'SIZE");
     END IF;
     CHECK_1 (REC1, 5, "REC");

     RESULT;
END CD4061A;
