-- CD5014M.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE VISIBLE PART
--     OF A GENERIC PACKAGE SPECIFICATION FOR A VARIABLE OF AN ACCESS
--     TYPE, WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART OF
--     THE SPECIFICATION.


-- HISTORY:
--     CDJ 07/24/87  CREATED ORIGINAL TEST.
--     BCB 10/01/87  CHANGED TEST TO STANDARD FORMAT.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH SPPRT13; USE SPPRT13;
WITH REPORT; USE REPORT;

PROCEDURE CD5014M IS

BEGIN

     TEST ("CD5014M", " AN ADDRESS CLAUSE CAN BE GIVEN " &
                      "IN THE VISIBLE PART OF A GENERIC PACKAGE " &
                      "SPECIFICATION FOR A VARIABLE OF AN ACCESS " &
                      "TYPE, WHERE THE VARIABLE IS DECLARED IN THE " &
                      "VISIBLE PART OF THE SPECIFICATION");

     DECLARE

     GENERIC
     PACKAGE PKG IS
          TYPE ACCESS_TYPE;
          TYPE POINTER_TYPE IS ACCESS ACCESS_TYPE;
          TYPE ACCESS_TYPE IS RECORD
               VAL1 : INTEGER;
               NEXT : POINTER_TYPE;
          END RECORD;
          POINTER_OBJ1 : POINTER_TYPE := NEW ACCESS_TYPE'(0,NULL);
          FOR POINTER_OBJ1 USE AT VARIABLE_ADDRESS;
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN
          IF EQUAL(3,3) THEN
               POINTER_OBJ1 := NEW ACCESS_TYPE'(10,NULL);
          END IF;

          IF POINTER_OBJ1.ALL /= (10,NULL) THEN
               FAILED ("INCORRECT VALUE FOR ACCESS VARIABLE");
          END IF;

          IF POINTER_OBJ1'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR ACCESS VARIABLE");
          END IF;
     END PKG;

     BEGIN
          NULL;
     END;

     RESULT;
END CD5014M;
