-- CD5012M.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF A
--     LIMITED PRIVATE TYPE IN THE DECLARATIVE PART OF A GENERIC
--     SUBPROGRAM.

-- HISTORY:
--     DHH 09/15/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;
PROCEDURE CD5012M IS

BEGIN

     TEST ("CD5012M", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF A LIMITED " &
                      "PRIVATE TYPE IN THE DECLARATIVE " &
                      "PART OF A GENERIC SUBPROGRAM");

     DECLARE

          PACKAGE P IS
               TYPE FIXED IS LIMITED PRIVATE;

          PRIVATE
               TYPE FIXED IS DELTA 2.0**(-4) RANGE -10.0..10.0;
          END P;

          USE P;

          GENERIC
          PROCEDURE GENPROC;

          PROCEDURE GENPROC IS

               TESTFIX : FIXED;

               FOR TESTFIX USE AT
                 SPPRT13.VARIABLE_ADDRESS;
          BEGIN
               IF TESTFIX'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
                    FAILED ("WRONG ADDRESS FOR LIMITED PRIVATE " &
                            "TYPE VARIABLE IN GENERIC PROCEDURE");
               END IF;
          END GENPROC;

     PROCEDURE PROC IS NEW GENPROC;
     BEGIN
          PROC;
     END;
     RESULT;
END CD5012M;
