-- CD5012A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF AN
--     ENUMERATION TYPE IN THE DECLARATIVE PART OF A GENERIC SUBPROGRAM.

-- HISTORY:
--     DHH 09/15/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;
PROCEDURE CD5012A IS

BEGIN

     TEST ("CD5012A", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF AN ENUMERATION " &
                      "TYPE IN THE DECLARATIVE PART OF A " &
                      "GENERIC SUBPROGRAM");

     DECLARE
          TYPE NON_CHAR IS (RED, BLUE, GREEN);

          COLOR : NON_CHAR;
          TEST_VAR : ADDRESS := COLOR'ADDRESS;

          GENERIC
          PROCEDURE GENPROC;

          PROCEDURE GENPROC IS

               HUE : NON_CHAR := GREEN;
               FOR HUE USE AT
                        SPPRT13.VARIABLE_ADDRESS;
          BEGIN
               IF EQUAL (3, 3) THEN
                    HUE := RED;
               END IF;
               IF HUE /= RED THEN
                    FAILED ("WRONG VALUE FOR VARIABLE IN " &
                            "GENERIC PROCEDURE");
               END IF;
               IF HUE'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
                    FAILED ("WRONG ADDRESS FOR VARIABLE " &
                            "IN GENERIC PROCEDURE");
               END IF;
          END GENPROC;

          PROCEDURE PROC IS NEW GENPROC;
     BEGIN
          PROC;
     END;
     RESULT;
END CD5012A;
