-- CD5013E.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE VISIBLE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF A FLOATING POINT TYPE,
--     WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013E IS

     TYPE FLT_TYPE IS DIGITS 5 RANGE -1.0 .. 1.0;

     PACKAGE PACK IS
          CHECK_VAR : FLT_TYPE;
          FOR CHECK_VAR USE AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

BEGIN

     TEST ("CD5013E", "AN ADDRESS CLAUSE CAN BE GIVEN IN " &
                      "THE VISIBLE PART OF A PACKAGE SPECIFICATION " &
                      "FOR A VARIABLE OF A FLOATING POINT TYPE, " &
                      "WHERE THE VARIABLE IS DECLARED IN THE VISIBLE " &
                      "PART OF THE SPECIFICATION");

     CHECK_VAR := 0.5;
     IF EQUAL(3,3) THEN
          CHECK_VAR := 0.0;
     END IF;

     IF CHECK_VAR /= 0.0 THEN
          FAILED ("INCORRECT VALUE FOR FLOATING POINT VARIABLE");
     END IF;

     IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR FLOATING POINT VARIABLE");
     END IF;

     RESULT;
END CD5013E;
