-- CD5013A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE VISIBLE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF AN ENUMERATION TYPE,
--     WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013A IS

     TYPE ENUM_TYPE IS (ONE,TWO,THREE,FOUR,FIVE,SIX);

     PACKAGE PACK IS
          CHECK_TYPE : ENUM_TYPE;
          FOR CHECK_TYPE USE AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

BEGIN

     TEST ("CD5013A", "AN ADDRESS CLAUSE CAN BE GIVEN IN " &
                      "THE VISIBLE PART OF A PACKAGE SPECIFICATION " &
                      "FOR A VARIABLE OF AN ENUMERATION TYPE, WHERE " &
                      "THE VARIABLE IS DECLARED IN THE VISIBLE PART " &
                      "OF THE SPECIFICATION");

     CHECK_TYPE := ONE;
     IF EQUAL(3,3) THEN
          CHECK_TYPE := THREE;
     END IF;

     IF CHECK_TYPE /= THREE THEN
          FAILED ("INCORRECT VALUE FOR ENUMERATION VARIABLE");
     END IF;

     IF CHECK_TYPE'ADDRESS /= VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR ENUMERATION VARIABLE");
     END IF;

     RESULT;
END CD5013A;
