-- CD5011K.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF A
--     RECORD TYPE IN THE DECLARATIVE PART OF A BLOCK STATEMENT.

-- HISTORY:
--     JET 09/15/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;

PROCEDURE CD5011K IS

BEGIN

     TEST ("CD5011K", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF A RECORD " &
                      "TYPE IN THE DECLARATIVE PART OF A " &
                      "BLOCK STATEMENT");

     DECLARE

          TYPE REC_TYPE IS RECORD
               I : INTEGER := 12;
               B : BOOLEAN := TRUE;
          END RECORD;

          REC : REC_TYPE;
          FOR REC USE
               AT SPPRT13.VARIABLE_ADDRESS;

     BEGIN
          IF EQUAL (3, 3) THEN
               REC.I := 17;
               REC.B := FALSE;
          END IF;

          IF REC.I /= 17 OR REC.B THEN
               FAILED ("WRONG VALUE FOR VARIABLE IN BLOCK");
          END IF;

          IF REC'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("WRONG ADDRESS FOR VARIABLE IN BLOCK");
          END IF;

     END;

     RESULT;

END CD5011K;
