-- CD5011A.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF AN
--     ENUMERATION TYPE IN THE DECLARATIVE PART OF A SUBPROGRAM.

-- HISTORY:
--     PWB 08/06/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;
PROCEDURE CD5011A IS

     TYPE ENUM IS (RED, BLUE, 'R', 'B');

     PROCEDURE MIX IS
          HUE : ENUM := RED;
          FOR HUE USE
               AT SPPRT13.VARIABLE_ADDRESS;
     BEGIN
          IF EQUAL (3, 3) THEN
               HUE := BLUE;
          END IF;
          IF HUE /= BLUE THEN
               FAILED ("WRONG VALUE FOR VARIABLE IN PROCEDURE");
          END IF;
          IF HUE'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("WRONG ADDRESS FOR VARIABLE IN PROCEDURE");
          END IF;
     END MIX;

     FUNCTION FIX RETURN BOOLEAN IS
          LETTER : ENUM := 'R';
          FOR LETTER USE AT
                    SPPRT13.VARIABLE_ADDRESS;
     BEGIN
          IF EQUAL (3, 3) THEN
               LETTER := 'B';
          END IF;
          IF LETTER /= ENUM'LAST THEN
               FAILED ("WRONG VALUE FOR VARIABLE IN FUNCTION");
          END IF;
          IF LETTER'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("WRONG ADDRESS FOR VARIABLE IN FUNCTION");
          END IF;
          RETURN EQUAL(3,3);
     END FIX;

BEGIN

     TEST ("CD5011A", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF AN ENUMERATION " &
                      "TYPE IN THE DECLARATIVE PART OF A " &
                      "SUBPROGRAM.");

     IF NOT FIX THEN
          FAILED ("FUNCTION FIX YIELDS WRONG VALUE");
     END IF;

     MIX;
     RESULT;

END CD5011A;
