-- CD5011G.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF A
--     FIXED POINT TYPE IN THE DECLARATIVE PART OF A SUBPROGRAM.

-- HISTORY:
--     JET 09/11/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;

PROCEDURE CD5011G IS

     TYPE FIX_TYPE IS DELTA 0.125 RANGE 0.0 .. 10.0;

     PROCEDURE CD5011G_PROC IS

          FP : FIX_TYPE := 2.0;
          FOR FP USE
               AT SPPRT13.VARIABLE_ADDRESS;

     BEGIN
          IF EQUAL (3, 3) THEN
               FP := 3.0;
          END IF;

          IF FP /= 3.0 THEN
               FAILED ("INCORRECT VALUE FOR VARIABLE IN PROCEDURE");
          END IF;

          IF FP'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR VARIABLE IN PROCEDURE");
          END IF;

     END CD5011G_PROC;

BEGIN
     TEST ("CD5011G", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF A FIXED POINT " &
                      "TYPE IN THE DECLARATIVE PART OF A " &
                      "SUBPROGRAM");

     CD5011G_PROC;

     RESULT;

END CD5011G;
