-- CD5013O.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF A PRIVATE TYPE, WHERE
--     THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013O IS

     PACKAGE P1 IS
     END P1;

     PACKAGE PACK IS
          TYPE F IS PRIVATE;
     PRIVATE
          TYPE F IS NEW INTEGER;
          CHECK_VAR : F;
          FOR CHECK_VAR USE AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

     PACKAGE BODY P1 IS
     BEGIN
          TEST ("CD5013O", "AN ADDRESS CLAUSE CAN BE GIVEN" &
                           " IN THE PRIVATE PART OF A PACKAGE " &
                           "SPECIFICATION FOR A VARIABLE OF A " &
                           "PRIVATE TYPE, WHERE THE VARIABLE IS " &
                           "DECLARED IN THE VISIBLE PART OF THE " &
                           "SPECIFICATION");
     END P1;

     PACKAGE BODY PACK IS
     BEGIN
          CHECK_VAR := 100;
          IF EQUAL(3,3) THEN
               CHECK_VAR := 25;
          END IF;

          IF CHECK_VAR /= 25 THEN
               FAILED ("INCORRECT VALUE FOR PRIVATE VARIABLE");
          END IF;

          IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR PRIVATE VARIABLE");
          END IF;
     END PACK;

BEGIN

     RESULT;
END CD5013O;
