-- CD5011E.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF A
--     FLOATING POINT TYPE IN THE DECLARATIVE PART OF A BLOCK
--     STATEMENT.

-- HISTORY:
--     JET 09/11/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;

PROCEDURE CD5011E IS

BEGIN

     TEST ("CD5011E", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF A FLOATING POINT " &
                      "TYPE IN THE DECLARATIVE PART OF A " &
                      "BLOCK STATEMENT");

     DECLARE

          FP : FLOAT := 3.0;
          FOR FP USE
               AT SPPRT13.VARIABLE_ADDRESS;

     BEGIN
          IF EQUAL (3, 3) THEN
               FP := 2.0;
          END IF;

          IF FP /= 2.0 THEN
               FAILED ("WRONG VALUE FOR VARIABLE IN BLOCK");
          END IF;

          IF FP'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("WRONG ADDRESS FOR VARIABLE IN BLOCK");
          END IF;

     END;

     RESULT;

END CD5011E;
