-- CD5011C.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF
--     AN INTEGER TYPE IN THE DECLARATIVE PART OF A PACKAGE BODY.

-- HISTORY:
--     JET 09/11/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;

PROCEDURE CD5011C IS

     PACKAGE CD5011C_PACKAGE IS
     END CD5011C_PACKAGE;

     PACKAGE BODY CD5011C_PACKAGE IS

          INT : INTEGER := 0;
          FOR INT USE
               AT SPPRT13.VARIABLE_ADDRESS;

     BEGIN
          TEST ("CD5011C", "AN ADDRESS CLAUSE CAN BE " &
                           "GIVEN FOR A VARIABLE OF AN INTEGER " &
                           "TYPE IN THE DECLARATIVE PART OF A " &
                           "PACKAGE BODY");

          IF EQUAL (3, 3) THEN
               INT := 5;
          END IF;
          IF INT /= IDENT_INT (5) THEN
               FAILED ("WRONG VALUE FOR VARIABLE IN PACKAGE");
          END IF;
          IF INT'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("WRONG ADDRESS FOR VARIABLE IN PACKAGE");
          END IF;
     END;

BEGIN

     RESULT;

END CD5011C;
