-- CD5013G.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF A FIXED POINT TYPE,
--     WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013G IS

     TYPE FIX_TYPE IS DELTA 0.5 RANGE -7.5 .. 7.5;

     PACKAGE PACK IS
          CHECK_VAR : FIX_TYPE;
     PRIVATE
          FOR CHECK_VAR USE
               AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

BEGIN

     TEST ("CD5013G", "AN ADDRESS CLAUSE CAN BE GIVEN IN " &
                      "THE PRIVATE PART OF A PACKAGE SPECIFICATION " &
                      "FOR A VARIABLE OF A FIXED POINT TYPE, " &
                      "WHERE THE VARIABLE IS DECLARED IN THE VISIBLE " &
                      "PART OF THE SPECIFICATION");

     CHECK_VAR := 1.5;
     IF EQUAL(3,3) THEN
          CHECK_VAR := 5.0;
     END IF;

     IF CHECK_VAR /= 5.0 THEN
          FAILED ("INCORRECT VALUE FOR FIXED POINT VARIABLE");
     END IF;

     IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR FIXED POINT VARIABLE");
     END IF;

     RESULT;
END CD5013G;
