-- CD5011I.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF
--     AN ARRAY TYPE IN THE DECLARATIVE PART OF A PACKAGE BODY.

-- HISTORY:
--     JET 09/11/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;

PROCEDURE CD5011I IS

     PACKAGE CD5011I_PACKAGE IS
     END CD5011I_PACKAGE;

     PACKAGE BODY CD5011I_PACKAGE IS

          INT : ARRAY (1 .. 10) OF INTEGER;
          FOR INT USE
               AT SPPRT13.VARIABLE_ADDRESS;

     BEGIN
          TEST ("CD5011I", "AN ADDRESS CLAUSE CAN BE " &
                           "GIVEN FOR A VARIABLE OF AN ARRAY " &
                           "TYPE IN THE DECLARATIVE PART OF A " &
                           "PACKAGE BODY");

          FOR I IN INT'RANGE LOOP
               INT (I) := IDENT_INT (I);
          END LOOP;

          FOR I IN INT'RANGE LOOP
               IF INT (I) /= I THEN
                    FAILED ("WRONG VALUE FOR ELEMENT" &
                            INTEGER'IMAGE (I));
               END IF;
          END LOOP;

          IF INT'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("WRONG ADDRESS FOR VARIABLE IN PACKAGE");
          END IF;
     END;

BEGIN

     RESULT;

END CD5011I;
