-- CD5013C.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF AN INTEGER TYPE, WHERE
--     THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013C IS

     TYPE INT_TYPE IS RANGE INTEGER'FIRST .. INTEGER'LAST;

     PACKAGE PACK IS
          CHECK_VAR : INT_TYPE;
     PRIVATE
          FOR CHECK_VAR USE AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

BEGIN

     TEST ("CD5013C", "AN ADDRESS CLAUSE CAN BE GIVEN IN " &
                      "THE PRIVATE PART OF A PACKAGE SPECIFICATION " &
                      "FOR A VARIABLE OF AN INTEGER TYPE, WHERE THE " &
                      "VARIABLE IS DECLARED IN THE VISIBLE PART OF " &
                      "THE SPECIFICATION");

     CHECK_VAR := 100;
     IF EQUAL(3,3) THEN
          CHECK_VAR := 10;
     END IF;

     IF CHECK_VAR /= 10 THEN
          FAILED ("INCORRECT VALUE FOR INTEGER VARIABLE");
     END IF;

     IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR INTEGER VARIABLE");
     END IF;

     RESULT;
END CD5013C;
