-- CD5013K.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF A RECORD TYPE, WHERE
--     THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013K IS

     TYPE REC_TYPE IS RECORD
          BOOL : BOOLEAN;
          INT  : INTEGER;
     END RECORD;

     PACKAGE PACK IS
          CHECK_VAR : REC_TYPE;
     PRIVATE
          FOR CHECK_VAR USE
               AT VARIABLE_ADDRESS;
     END PACK;

     PACKAGE BODY PACK IS
     BEGIN
          TEST ("CD5013K", "AN ADDRESS CLAUSE CAN BE GIVEN " &
                           "IN THE PRIVATE PART OF A PACKAGE " &
                           "SPECIFICATION FOR A VARIABLE OF A RECORD " &
                           "TYPE, WHERE THE VARIABLE IS DECLARED IN " &
                           "THE VISIBLE PART OF THE SPECIFICATION");

          CHECK_VAR := (TRUE, IDENT_INT(5));
          IF EQUAL(3,3) THEN
               CHECK_VAR := (FALSE, IDENT_INT(10));
          END IF;

          IF CHECK_VAR /= (FALSE, IDENT_INT (10)) THEN
               FAILED ("INCORRECT VALUE FOR RECORD VARIABLE");
          END IF;

          IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR RECORD VARIABLE");
          END IF;
     END PACK;

BEGIN

     RESULT;
END CD5013K;
