-- CD5014T.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART
--     OF A GENERIC PACKAGE SPECIFICATION FOR A VARIABLE OF A FORMAL
--     DISCRETE TYPE, WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART
--     OF THE SPECIFICATION.


-- HISTORY:
--     BCB 10/08/87  CREATED ORIGINAL TEST.

--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.
WITH SYSTEM; USE SYSTEM;
WITH SPPRT13; USE SPPRT13;
WITH REPORT; USE REPORT;

PROCEDURE CD5014T IS

BEGIN

     TEST ("CD5014T", " AN ADDRESS CLAUSE CAN BE GIVEN " &
                      "IN THE PRIVATE PART OF A GENERIC PACKAGE " &
                      "SPECIFICATION FOR A VARIABLE OF A FORMAL " &
                      "DISCRETE TYPE, WHERE THE VARIABLE IS DECLARED " &
                      "IN THE VISIBLE PART OF THE SPECIFICATION");

     DECLARE

     GENERIC
          TYPE FORM_DISCRETE_TYPE IS (<>);
     PACKAGE PKG IS
          FORM_DISCRETE_OBJ1 : FORM_DISCRETE_TYPE :=
               FORM_DISCRETE_TYPE'FIRST;
     PRIVATE
          FOR FORM_DISCRETE_OBJ1 USE
               AT VARIABLE_ADDRESS;
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN

          IF EQUAL(3,3) THEN
               FORM_DISCRETE_OBJ1 := FORM_DISCRETE_TYPE'LAST;
          END IF;

          IF FORM_DISCRETE_OBJ1 /= FORM_DISCRETE_TYPE'LAST THEN
               FAILED ("INCORRECT VALUE FOR FORMAL DISCRETE VARIABLE");
          END IF;

          IF FORM_DISCRETE_OBJ1'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR FORMAL DISCRETE " &
                       "VARIABLE");
          END IF;
     END PKG;

     PACKAGE PACK IS NEW PKG(FORM_DISCRETE_TYPE => INTEGER);

     BEGIN
          NULL;
     END;

     RESULT;
END CD5014T;
