-- CD5011M.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF
--     AN ACCESS TYPE IN THE DECLARATIVE PART OF A SUBPROGRAM.

-- HISTORY:
--     JET 09/15/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;

PROCEDURE CD5011M IS

     TYPE ACC_TYPE IS ACCESS STRING;

     PROCEDURE CD5011M_PROC IS

          ACC : ACC_TYPE := NEW STRING'("THE QUICK BROWN FOX");
          FOR ACC USE
               AT SPPRT13.VARIABLE_ADDRESS;

     BEGIN
          IF EQUAL (3, 3) THEN
               ACC := NEW STRING'("THE LAZY DOG");
          END IF;

          IF ACC.ALL /= IDENT_STR ("THE LAZY DOG") THEN
               FAILED ("INCORRECT VALUE FOR VARIABLE IN PROCEDURE");
          END IF;

          IF ACC'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR VARIABLE IN PROCEDURE");
          END IF;

     END CD5011M_PROC;

BEGIN
     TEST ("CD5011M", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF AN ACCESS " &
                      "TYPE IN THE DECLARATIVE PART OF A " &
                      "SUBPROGRAM");

     CD5011M_PROC;

     RESULT;

END CD5011M;
