-- CD5014E.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE VISIBLE PART
--     OF A GENERIC PACKAGE SPECIFICATION FOR A VARIABLE OF A FLOATING
--     POINT TYPE, WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART
--     OF THE SPECIFICATION.


-- HISTORY:
--     CDJ 08/19/87  CREATED ORIGINAL TEST.
--     BCB 09/30/87  CHANGED TEST TO STANDARD FORMAT.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH SPPRT13; USE SPPRT13;
WITH REPORT; USE REPORT;

PROCEDURE CD5014E IS

BEGIN

     TEST ("CD5014E", " AN ADDRESS CLAUSE CAN BE GIVEN " &
                      "IN THE VISIBLE PART OF A GENERIC PACKAGE " &
                      "SPECIFICATION FOR A VARIABLE OF A FLOATING " &
                      "POINT TYPE, WHERE THE VARIABLE IS DECLARED " &
                      "IN THE VISIBLE PART OF THE SPECIFICATION");

     DECLARE

     GENERIC
     PACKAGE PKG IS
          TYPE FLOAT_TYPE IS DIGITS SYSTEM.MAX_DIGITS
               RANGE 0.0 .. 100.0;
          FLOAT_OBJ1 : FLOAT_TYPE := 50.0;
          FOR FLOAT_OBJ1 USE AT VARIABLE_ADDRESS;
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN
          IF EQUAL(3,3) THEN
               FLOAT_OBJ1 := 5.0;
          END IF;

          IF FLOAT_OBJ1 /= 5.0 THEN
               FAILED ("INCORRECT VALUE FOR FLOATING POINT VARIABLE");
          END IF;

          IF FLOAT_OBJ1'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR FLOATING POINT VARIABLE");
          END IF;
     END PKG;

     BEGIN
          NULL;
     END;

     RESULT;
END CD5014E;
