-- CD5013M.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE VISIBLE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF AN ACCESS TYPE, WHERE
--     THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013M IS

     TYPE ACC_TYPE IS ACCESS INTEGER;

     PACKAGE PACK IS
          CHECK_VAR : ACC_TYPE;
          FOR CHECK_VAR USE
               AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

BEGIN

     TEST ("CD5013M", "AN ADDRESS CLAUSE CAN BE GIVEN IN " &
                      "THE VISIBLE PART OF A PACKAGE SPECIFICATION " &
                      "FOR A VARIABLE OF AN ACCESS TYPE, WHERE THE " &
                      "VARIABLE IS DECLARED IN THE VISIBLE PART OF " &
                      "THE SPECIFICATION");

     CHECK_VAR := NEW INTEGER'(100);
     IF EQUAL(3,3) THEN
          CHECK_VAR := NEW INTEGER'(25);
     END IF;

     IF CHECK_VAR.ALL /= 25 THEN
          FAILED ("INCORRECT VALUE FOR ACCESS VARIABLE");
     END IF;

     IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR ACCESS VARIABLE");
     END IF;

     RESULT;
END CD5013M;
