-- CD5013I.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE VISIBLE PART OF
--     A PACKAGE SPECIFICATION FOR A VARIABLE OF AN ARRAY TYPE, WHERE
--     THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.

-- HISTORY:
--     BCB 09/16/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SPPRT13; USE SPPRT13;
WITH SYSTEM;  USE SYSTEM;

PROCEDURE CD5013I IS

     TYPE ARR_TYPE IS ARRAY(1..5) OF INTEGER;

     PACKAGE PACK IS
          CHECK_VAR : ARR_TYPE;
          FOR CHECK_VAR USE
               AT VARIABLE_ADDRESS;
     END PACK;

     USE PACK;

BEGIN

     TEST ("CD5013I", "AN ADDRESS CLAUSE CAN BE GIVEN IN " &
                      "THE VISIBLE PART OF A PACKAGE SPECIFICATION " &
                      "FOR A VARIABLE OF AN ARRAY TYPE, WHERE THE " &
                      "VARIABLE IS DECLARED IN THE VISIBLE PART OF " &
                      "THE SPECIFICATION");

     CHECK_VAR := (1,2,3,4,5);
     IF EQUAL(3,3) THEN
          CHECK_VAR := (5,4,3,2,1);
     END IF;

     IF CHECK_VAR /= (5,4,3,2,1) THEN
          FAILED ("INCORRECT VALUE FOR ARRAY VARIABLE");
     END IF;

     IF CHECK_VAR'ADDRESS /= VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR ARRAY VARIABLE");
     END IF;

     RESULT;
END CD5013I;
