-- CD5003A.ADA

-- OBJECTIVE:
--     CHECK THAT A 'WITH' CLAUSE NAMING 'SYSTEM' NEED NOT BE GIVEN FOR
--     A PACKAGE BODY CONTAINING AN ADDRESS CLAUSE AS LONG AS A 'WITH'
--     CLAUSE IS GIVEN FOR THE SPECIFICATION.

-- HISTORY:
--     RJW 10/13/88  CREATED ORIGINAL TEST.
--     BCB 04/18/89  CHANGED EXTENSION TO '.ADA'.  REMOVED APPLICABILITY
--                   CRITERIA AND N/A ERROR MESSAGES.

WITH SYSTEM;
PACKAGE CD5003A_PKG2 IS END CD5003A_PKG2;

WITH SPPRT13;
WITH REPORT; USE REPORT;
PRAGMA ELABORATE (SPPRT13);
PRAGMA ELABORATE (REPORT);
PACKAGE BODY CD5003A_PKG2 IS
     TEST_VAR : INTEGER;
     FOR TEST_VAR USE AT SPPRT13.VARIABLE_ADDRESS;
     USE SYSTEM;
BEGIN
     TEST ("CD5003A", "CHECK THAT A 'WITH' CLAUSE NAMING 'SYSTEM' " &
                      "NEED NOT BE GIVEN FOR A PACKAGE BODY " &
                      "CONTAINING AN ADDRESS CLAUSE AS LONG AS A " &
                      "'WITH' CLAUSE IS GIVEN FOR THE SPECIFICATION");

     TEST_VAR := IDENT_INT (3);

     IF TEST_VAR /= 3 THEN
          FAILED ("INCORRECT VALUE FOR TEST_VAR");
     END IF;

     IF TEST_VAR'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR TEST_VAR");
     END IF;

END CD5003A_PKG2;

WITH REPORT; USE REPORT;
WITH CD5003A_PKG2; USE CD5003A_PKG2;
WITH SPPRT13;
PROCEDURE CD5003A IS
BEGIN

    RESULT;
END CD5003A;
