-- CD5014Z.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART
--     OF A GENERIC PACKAGE SPECIFICATION FOR A VARIABLE OF A FORMAL
--     LIMITED PRIVATE TYPE, WHERE THE VARIABLE IS DECLARED IN THE
--     VISIBLE PART OF THE SPECIFICATION.

-- HISTORY:
--     BCB 10/08/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH SPPRT13; USE SPPRT13;
WITH REPORT; USE REPORT;

PROCEDURE CD5014Z IS

BEGIN

     TEST ("CD5014Z", " AN ADDRESS CLAUSE CAN BE GIVEN " &
                      "IN THE PRIVATE PART OF A GENERIC PACKAGE " &
                      "SPECIFICATION FOR A VARIABLE OF A FORMAL " &
                      "LIMITED PRIVATE TYPE, WHERE THE VARIABLE IS " &
                      "DECLARED IN THE VISIBLE PART OF THE " &
                      "SPECIFICATION");

     DECLARE

     GENERIC
          TYPE FORM_LIM_PRIVATE_TYPE IS LIMITED PRIVATE;
     PACKAGE PKG IS
          FORM_LIM_PRIVATE_OBJ1 : FORM_LIM_PRIVATE_TYPE;
     PRIVATE
          FOR FORM_LIM_PRIVATE_OBJ1 USE
               AT VARIABLE_ADDRESS;
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN
          IF FORM_LIM_PRIVATE_OBJ1'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR FORMAL LIMITED PRIVATE " &
                       "VARIABLE");
          END IF;
     END PKG;

     PACKAGE PACK IS NEW PKG(FORM_LIM_PRIVATE_TYPE => INTEGER);

     BEGIN
          NULL;
     END;

     RESULT;
END CD5014Z;
