-- CD5012F.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN FOR A VARIABLE OF AN
--     ARRAY TYPE IN THE DECLARATIVE PART OF A GENERIC
--     PACKAGE BODY.

-- HISTORY:
--     DHH 09/17/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH SPPRT13;
PROCEDURE CD5012F IS

BEGIN

     TEST ("CD5012F", "AN ADDRESS CLAUSE CAN BE " &
                      "GIVEN FOR A VARIABLE OF AN ARRAY " &
                      "TYPE IN THE DECLARATIVE " &
                      "PART OF A GENERIC PACKAGE BODY");

     DECLARE

          GENERIC
          PACKAGE GENPACK IS

          END GENPACK;

          PACKAGE BODY GENPACK IS
               ARRAY_VAR : ARRAY (0..4) OF INTEGER := (0,1,2,3,4);

               FOR ARRAY_VAR USE AT SPPRT13.VARIABLE_ADDRESS;


          BEGIN
               IF EQUAL (3, 3) THEN
                    ARRAY_VAR := (4,3,2,1,0);
               END IF;
               IF ARRAY_VAR /= (4,3,2,1,0) THEN
                    FAILED ("WRONG VALUE FOR VARIABLE IN " &
                            "A GENERIC PACKAGE BODY");
               END IF;
               IF ARRAY_VAR'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
                    FAILED ("WRONG ADDRESS FOR VARIABLE " &
                            "IN A GENERIC PACKAGE BODY");
               END IF;
          END GENPACK;

          PACKAGE PACK IS NEW GENPACK;
     BEGIN
          NULL;
     END;
     RESULT;
END CD5012F;
