-- CD5014X.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART
--     OF A GENERIC PACKAGE SPECIFICATION FOR A VARIABLE OF A FORMAL
--     ARRAY TYPE, WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART
--     OF THE SPECIFICATION.

-- HISTORY:
--     BCB 10/08/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH SPPRT13; USE SPPRT13;
WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;

PROCEDURE CD5014X IS

BEGIN

     TEST ("CD5014X", " AN ADDRESS CLAUSE CAN BE GIVEN " &
                      "IN THE PRIVATE PART OF A GENERIC PACKAGE " &
                      "SPECIFICATION FOR A VARIABLE OF A FORMAL " &
                      "ARRAY TYPE, WHERE THE VARIABLE IS DECLARED " &
                      "IN THE VISIBLE PART OF THE SPECIFICATION");

     DECLARE

          TYPE COLOR IS (RED,BLUE,GREEN);
          TYPE COLOR_TABLE IS ARRAY (COLOR) OF INTEGER;

     GENERIC
          TYPE INDEX IS (<>);
          TYPE FORM_ARRAY_TYPE IS ARRAY (INDEX) OF INTEGER;
     PACKAGE PKG IS
          FORM_ARRAY_OBJ1 : FORM_ARRAY_TYPE := (1,2,3);
     PRIVATE
          FOR FORM_ARRAY_OBJ1 USE AT VARIABLE_ADDRESS;
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN

          IF EQUAL(3,3) THEN
               FORM_ARRAY_OBJ1 := (10,20,30);
          END IF;

          IF FORM_ARRAY_OBJ1 /= (10,20,30) THEN
               FAILED ("INCORRECT VALUE FOR FORMAL ARRAY VARIABLE");
          END IF;

          IF FORM_ARRAY_OBJ1'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR FORMAL ARRAY " &
                       "VARIABLE");
          END IF;
     END PKG;

     PACKAGE PACK IS NEW PKG(INDEX => COLOR,
                             FORM_ARRAY_TYPE => COLOR_TABLE);

     BEGIN
          NULL;
     END;

     RESULT;
END CD5014X;
