-- CD5014K.ADA

-- OBJECTIVE:
--     CHECK THAT AN ADDRESS CLAUSE CAN BE GIVEN IN THE PRIVATE PART
--     OF A GENERIC PACKAGE SPECIFICATION FOR A VARIABLE OF A RECORD
--     TYPE, WHERE THE VARIABLE IS DECLARED IN THE VISIBLE PART OF THE
--     SPECIFICATION.


-- HISTORY:
--     CDJ 07/24/87  CREATED ORIGINAL TEST.
--     BCB 10/01/87  CHANGED TEST TO STANDARD FORMAT.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH SYSTEM; USE SYSTEM;
WITH SPPRT13; USE SPPRT13;
WITH REPORT; USE REPORT;

PROCEDURE CD5014K IS

BEGIN

     TEST ("CD5014K", " AN ADDRESS CLAUSE CAN BE GIVEN " &
                      "IN THE PRIVATE PART OF A GENERIC PACKAGE " &
                      "SPECIFICATION FOR A VARIABLE OF A RECORD " &
                      "TYPE, WHERE THE VARIABLE IS DECLARED IN THE " &
                      "VISIBLE PART OF THE SPECIFICATION");


     DECLARE

     GENERIC
     PACKAGE PKG IS
          TYPE REC_TYPE IS RECORD
               VAL : INTEGER;
          END RECORD;
          REC_OBJ1 : REC_TYPE := (VAL => 10);
     PRIVATE
          FOR REC_OBJ1 USE AT VARIABLE_ADDRESS;
     END PKG;

     PACKAGE BODY PKG IS
     BEGIN
          IF EQUAL(3,3) THEN
               REC_OBJ1.VAL := 100;
          END IF;

          IF REC_OBJ1.VAL /= 100 THEN
               FAILED ("INCORRECT VALUE FOR RECORD VARIABLE COMPONENT");
          END IF;

          IF REC_OBJ1'ADDRESS /= VARIABLE_ADDRESS THEN
               FAILED ("INCORRECT ADDRESS FOR RECORD VARIABLE");
          END IF;
     END PKG;

     BEGIN
          NULL;
     END;

     RESULT;
END CD5014K;
