-- CD7007B.ADA

-- OBJECTIVE:
--     CHECK THAT THE SUBTYPE 'PRIORITY' IS DECLARED WITHIN THE PACKAGE
--     SYSTEM AND IT IS A SUBTYPE OF 'INTEGER'.

-- HISTORY:
--     VCL  09/16/87  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE CD7007B IS
BEGIN
     TEST ("CD7007B", "THE SUBTYPE 'PRIORITY' IS DECLARED WITHIN " &
                      "THE PACKAGE SYSTEM AND IT IS A SUBTYPE OF " &
                      "'INTEGER'");

     DECLARE
          CHECK_VAR : SYSTEM.PRIORITY;
     BEGIN
          IF SYSTEM.PRIORITY'FIRST NOT IN
                              INTEGER'FIRST .. INTEGER'LAST AND
                    SYSTEM.PRIORITY'LAST NOT IN
                              INTEGER'FIRST .. INTEGER'LAST THEN
               FAILED ("'SYSTEM.PRIORITY' IS NOT AN INTEGER SUBTYPE");
          END IF;
     END;

     RESULT;
END CD7007B;
