-- CD7002A.ADA

-- OBJECTIVE:
--     CHECK THAT A VARIABLE OF TYPE ADDRESS CAN BE DECLARED IN A UNIT
--     WHICH HAS A WITH CLAUSE NAMING SYSTEM.

-- HISTORY:
--     DHH 08/31/88  CREATED ORIGINAL TEST.

WITH SYSTEM;
WITH REPORT; USE REPORT;
PROCEDURE CD7002A IS

     I : INTEGER;

     OBJECT : SYSTEM.ADDRESS := I'ADDRESS;

     SUBTYPE MY_ADDRESS IS SYSTEM.ADDRESS;

BEGIN
     TEST ("CD7002A", "CHECK THAT A VARIABLE OF TYPE ADDRESS CAN BE " &
                      "DECLARED IN A UNIT WHICH HAS A WITH CLAUSE " &
                      "NAMING SYSTEM");

     IF NOT IDENT_BOOL(OBJECT IN MY_ADDRESS) THEN
          FAILED("INCORRECT RESULT");
     END IF;

     RESULT;
END CD7002A;
