-- CD7205C.ADA

-- OBJECTIVE:
--     CHECK THAT IF A COLLECTION SIZE REPRESENTATION CLAUSE IS GIVEN
--     FOR AN ACCESS TYPE, THEN THE 'STORAGE_SIZE ATTRIBUTE RETURNS A
--     CORRECT VALUE.  CHECK THAT THE STORAGE_ERROR EXCEPTION IS
--     RAISED WHEN THE ALLOCATED SPACE EXCEEDS THE SPECIFIED COLLECTION
--     SIZE.

-- HISTORY:
--     BCB 09/11/87  CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT;  USE REPORT;
WITH SYSTEM;

PROCEDURE CD7205C IS

     SPECIFIED_SIZE : CONSTANT := 1000;

     TYPE CHECK_TYPE IS ACCESS INTEGER;
     FOR CHECK_TYPE'STORAGE_SIZE USE SPECIFIED_SIZE;

     UNITS_PER_INTEGER : CONSTANT :=
                    (INTEGER'SIZE + SYSTEM.STORAGE_UNIT - 1) /
                    SYSTEM.STORAGE_UNIT;

     TYPE ACC_ARRAY_TYPE IS ARRAY
          (INTEGER RANGE 1 .. (CHECK_TYPE'STORAGE_SIZE /
          UNITS_PER_INTEGER)) OF CHECK_TYPE;
     ACC_ARRAY : ACC_ARRAY_TYPE;

     ACC : CHECK_TYPE;
     PLACE : INTEGER;

BEGIN
     TEST ("CD7205C", "IF COLLECTION SIZE REPRESENTATION " &
                      "CLAUSES ARE ALLOWED FOR ACCESS TYPES, THEN " &
                      "THE 'STORAGE_SIZE ATTRIBUTE RETURNS A CORRECT " &
                      "VALUE.  CHECK THAT THE STORAGE_ERROR " &
                      "EXCEPTION IS RAISED WHEN THE ALLOCATED SPACE " &
                      "EXCEEDS THE SPECIFIED COLLECTION SIZE");

     IF CHECK_TYPE'STORAGE_SIZE < IDENT_INT (SPECIFIED_SIZE) THEN
          FAILED ("VALUE TOO SMALL FOR CHECK_TYPE'STORAGE_SIZE");
     END IF;

     IF CHECK_TYPE'STORAGE_SIZE > 2 * IDENT_INT (SPECIFIED_SIZE) THEN
          FAILED ("EXTREME VALUE FOR CHECK_TYPE'STORAGE_SIZE");
     END IF;

     BEGIN

          FOR I IN ACC_ARRAY'RANGE LOOP
               ACC_ARRAY (I) := NEW INTEGER'(I);
               IF ACC_ARRAY (I).ALL /= IDENT_INT (I) THEN
                    FAILED ("INCORRECT VALUE FOR ACC_ARRAY (" &
                                 INTEGER'IMAGE (I) & ")");
               END IF;
          END LOOP;

          ACC := NEW INTEGER'(IDENT_INT(0));

          IF EQUAL (ACC.ALL, 0) THEN
               FAILED ("NO EXCEPTION RAISED WHEN RESERVED SPACE " &
                        "EXCEEDED");
          END IF;

     EXCEPTION
          WHEN STORAGE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED WHEN RESERVED SPACE " &
                       "EXCEEDED");
     END;

     RESULT;

END CD7205C;
