-- CD7204B.ADA

-- OBJECTIVE:
--     CHECK THAT THE PREFIX OF THE 'POSITION, 'LAST_BIT, AND 'FIRST_BIT
--     ATTRIBUTES CAN DENOTE A RECORD COMPONENT, AND THE ATTRIBUTES
--     RETURN APPROPRIATE VALUES WHEN A RECORD REPRESENTATION CLAUSE IS
--     NOT PRESENT.

-- HISTORY:
--     BCB 09/14/87  CREATED ORIGINAL TEST.
--     RJW 02/08/88  REVISED SO THAT TEST PASSES IF BOOLEAN'SIZE = 1.

WITH REPORT;  USE REPORT;

PROCEDURE CD7204B IS

     TYPE BASIC_REC IS RECORD
          CHECK_INT : INTEGER := 5;
          CHECK_BOOL : BOOLEAN := TRUE;
     END RECORD;

     CHECK_REC : BASIC_REC;

BEGIN

     TEST ("CD7204B", "CHECK THAT THE PREFIX OF THE 'POSITION, " &
                      "'LAST_BIT, AND 'FIRST_BIT ATTRIBUTES CAN " &
                      "DENOTE A RECORD COMPONENT, AND THE ATTRIBUTES " &
                      "RETURN APPROPRIATE VALUES WHEN A RECORD " &
                      "REPRESENTATION CLAUSE IS NOT PRESENT");

     IF CHECK_REC.CHECK_INT'FIRST_BIT >= CHECK_REC.CHECK_INT'LAST_BIT
          THEN FAILED ("INCORRECT VALUES FOR FIRST_BIT OR LAST_BIT " &
                       "OF CHECK_INT");
     END IF;

     IF (CHECK_REC.CHECK_INT'LAST_BIT - CHECK_REC.CHECK_INT'FIRST_BIT
          + 1) > INTEGER'SIZE THEN
          FAILED ("INCORRECT SIZE FOR CHECK_INT");
     END IF;

     IF CHECK_REC.CHECK_BOOL'FIRST_BIT > CHECK_REC.CHECK_BOOL'LAST_BIT
          THEN FAILED ("INCORRECT VALUE FOR FIRST_BIT OR LAST_BIT " &
                       "OF CHECK_BOOL");
     END IF;

     IF (CHECK_REC.CHECK_BOOL'LAST_BIT - CHECK_REC.CHECK_BOOL'FIRST_BIT
          + 1) > BOOLEAN'SIZE THEN
          FAILED ("INCORRECT SIZE FOR CHECK_BOOL");
     END IF;

     RESULT;

END CD7204B;
