-- CD7305A.ADA

-- OBJECTIVE:
--     CHECK, FOR DIGITS 5, THAT MACHINE_RADIX, MACHINE_MANTISSA,
--     MACHINE_EMAX, AND MACHINE_EMIN HAVE THE CORRECT VALUES.

-- HISTORY:
--     DHH 09/15/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE CD7305A IS

     TYPE T IS DIGITS 5;

     B : BOOLEAN := FALSE;

BEGIN
     TEST ("CD7305A", "CHECK, FOR DIGITS 5, THAT MACHINE_RADIX, " &
                      "MACHINE_MANTISSA, MACHINE_EMAX, AND " &
                      "MACHINE_EMIN HAVE THE CORRECT VALUES");


     IF T'MACHINE_EMAX < 1 OR T'BASE'MACHINE_EMAX /= T'MACHINE_EMAX OR
        (1.0 * T'MACHINE_RADIX) ** (T'MACHINE_EMAX - 1) / 2 <
        2.0 ** (T'SAFE_EMAX - 1) / T'MACHINE_RADIX THEN
          FAILED ("INCORRECT 'MACHINE_EMAX");
     END IF;

     IF T'MACHINE_EMIN > -1 OR T'BASE'MACHINE_EMIN /= T'MACHINE_EMIN OR
        (1.0 * T'MACHINE_RADIX) ** (T'MACHINE_EMIN + 2) *
        (1.0 * T'MACHINE_RADIX) ** (-3) > T'SAFE_SMALL THEN
          FAILED ("INCORRECT 'MACHINE_EMIN");
     END IF;

     -- CHECK THAT T'MACHINE_MANTISSA >=
     --            T'MANTISSA * LOG (2) / LOG (T'MACHINE_RADIX).
     CASE T'MACHINE_RADIX IS
          WHEN 2 =>
               B := T'MACHINE_MANTISSA >= T'MANTISSA;
          WHEN 4 =>
               B := T'MACHINE_MANTISSA * 2 >= T'MANTISSA;
          WHEN 8 =>
               B := T'MACHINE_MANTISSA * 3 >= T'MANTISSA;
          WHEN 10 =>
               B := T'MACHINE_MANTISSA * 3.322 >= T'MANTISSA * 1.0;
          WHEN 16 =>
               B := T'MACHINE_MANTISSA * 4 >= T'MANTISSA;
          WHEN OTHERS =>
               B := TRUE;
     END CASE;

     IF T'MACHINE_MANTISSA < 1 OR NOT B OR
        T'BASE'MACHINE_MANTISSA /= T'MACHINE_MANTISSA THEN
          FAILED ("INCORRECT 'MACHINE_MANTISSA");
     END IF;

     IF T'MACHINE_RADIX < 2 OR
        T'BASE'MACHINE_RADIX /= T'MACHINE_RADIX THEN
          FAILED ("INCORRECT 'MACHINE_RADIX");
     END IF;

     RESULT;
END CD7305A;
