-- CDA101B.ADA

-- OBJECTIVE:
--     CHECK THAT IF AN INSTANTIATION OF UNCHECKED_DEALLOCATION IS
--     CALLED FOR A VARIABLE WHICH DESIGNATES A TASK, THE TASK
--     CONTINUES TO EXECUTE CORRECTLY.

-- HISTORY:
--     JET 09/23/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH UNCHECKED_DEALLOCATION;
PROCEDURE CDA101B IS

     TASK TYPE T_TYPE IS
          ENTRY STOP (I : IN OUT INTEGER);
     END T_TYPE;

     TYPE ACC IS ACCESS T_TYPE;

     INT : INTEGER := 10;

     TASK BODY T_TYPE IS
     BEGIN
          ACCEPT STOP (I : IN OUT INTEGER) DO
               I := IDENT_INT(I) + 1;
          END STOP;
     END T_TYPE;

     PROCEDURE RELEASE IS NEW UNCHECKED_DEALLOCATION(T_TYPE, ACC);

BEGIN
     TEST ("CDA101B", "CHECK THAT IF AN INSTANTIATION OF UNCHECKED_" &
                      "DEALLOCATION IS CALLED FOR A VARIABLE WHICH " &
                      "DESIGNATES A TASK, THE TASK CONTINUES TO " &
                      "EXECUTE CORRECTLY");

     DECLARE
          A : ACC := NEW T_TYPE;

          PROCEDURE P(I : IN OUT INTEGER) RENAMES A.STOP;
     BEGIN
          RELEASE(A);

          P(INT);

          IF INT /= 11 THEN
               FAILED("INCORRECT RETURN VALUE FROM DEALLOCATED TASK");
          END IF;
     END;

     RESULT;
END CDA101B;
