-- CDA201C.ADA

-- OBJECTIVE:
--     CHECK THAT UNCHECKED_CONVERSION CAN BE INSTANTIATED FOR
--     CONVERSION BETWEEN CONSTRAINED ARRAY AND RECORD TYPES.

-- HISTORY:
--     JET 09/12/88  CREATED ORIGINAL TEST.
--     DHH 05/17/89  CHANGED FROM '.DEP' TEST TO '.ADA' TEST.

WITH REPORT; USE REPORT;
WITH UNCHECKED_CONVERSION;
PROCEDURE CDA201C IS

     TYPE INT IS NEW INTEGER;

     TYPE ARR IS ARRAY (1..2) OF INTEGER;
     TYPE ARR2 IS ARRAY (ARR'RANGE) OF INT;

     TYPE REC IS RECORD
          D : INTEGER;
          I : INTEGER;
     END RECORD;

     TYPE REC2 IS RECORD
          D : INT;
          I : INT;
     END RECORD;

     A : ARR2;
     R : REC2;

     FUNCTION ARR_CONV IS NEW UNCHECKED_CONVERSION(ARR, ARR2);
     FUNCTION REC_CONV IS NEW UNCHECKED_CONVERSION(REC, REC2);

BEGIN
     TEST ("CDA201C", "CHECK THAT UNCHECKED_CONVERSION CAN BE " &
                      "INSTANTIATED FOR CONVERSION BETWEEN " &
                      "CONSTRAINED ARRAY AND RECORD TYPES");

     A := ARR_CONV(ARR'(ARR'RANGE => IDENT_INT(-1)));

     IF A /= ARR2'(ARR'RANGE => -1) THEN
          FAILED("INCORRECT RESULT FROM ARRAY CONVERSION");
     END IF;

     R := REC_CONV(REC'(D | I => IDENT_INT(1)));

     IF R /= REC2'(D => 1, I => 1) THEN
          FAILED("INCORRECT RESULT FROM RECORD CONVERSION");
     END IF;

     RESULT;
END CDA201C;
