-- CDA201E.ADA

-- OBJECTIVE:
--     CHECK THAT UNCHECKED_CONVERSION CAN BE INSTANTIATED FOR THE
--     CONVERSION OF AN ENUMERATION TYPE WITH A REPRESENTATION CLAUSE TO
--     INTEGER.

-- HISTORY:
--     JET 09/23/88  CREATED ORIGINAL TEST.
--     DHH 05/17/89  CHANGED FROM '.DEP' TEST TO '.ADA' TEST.

WITH REPORT; USE REPORT;
WITH UNCHECKED_CONVERSION;
PROCEDURE CDA201E IS

     TYPE STOOGE IS (CURLY, MOE, LARRY);
     FOR STOOGE USE (CURLY => -5, MOE => 13, LARRY => 127);

     TYPE INT IS RANGE -128 .. 127;
     FOR INT'SIZE USE 8;

     I : INT;

     FUNCTION E_TO_I IS NEW UNCHECKED_CONVERSION(STOOGE, INT);

     FUNCTION ID(E : STOOGE) RETURN STOOGE IS
     BEGIN
          RETURN STOOGE'VAL(STOOGE'POS(E) + IDENT_INT(0));
     END ID;

BEGIN
     TEST ("CDA201E", "CHECK THAT UNCHECKED_CONVERSION CAN BE " &
                      "INSTANTIATED FOR THE CONVERSION OF AN " &
                      "ENUMERATION TYPE WITH A REPRESENTATION " &
                      "CLAUSE TO INTEGER");

     BEGIN
          I := E_TO_I(ID(CURLY));
          IF I /= -5 THEN
               FAILED ("INCORRECT VALUE OF CURLY: " & INT'IMAGE(I));
          END IF;

          I := E_TO_I(ID(MOE));
          IF I /= 13 THEN
               FAILED ("INCORRECT VALUE OF MOE: " & INT'IMAGE(I));
          END IF;

          I := E_TO_I(ID(LARRY));
          IF I /= 127 THEN
               FAILED ("INCORRECT VALUE OF LARRY: " & INT'IMAGE(I));
          END IF;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED BY CONVERSION");
     END;

     RESULT;
END CDA201E;
