-- CDA201A.ADA

-- OBJECTIVE:
--     CHECK THAT UNCHECKED_CONVERSION CAN BE INSTANTIATED FOR
--     CONVERSION BETWEEN INTEGER AND BOOLEAN ARRAY TYPES.

-- HISTORY:
--     JET 09/12/88  CREATED ORIGINAL TEST.
--     DHH 05/17/89  CHANGED FROM '.DEP' TEST TO '.ADA' TEST.

WITH REPORT; USE REPORT;
WITH UNCHECKED_CONVERSION;
PROCEDURE CDA201A IS

     TYPE BOOL_ARR IS ARRAY (1..INTEGER'SIZE) OF BOOLEAN;
     PRAGMA PACK (BOOL_ARR);

     I : INTEGER;
     B : BOOL_ARR;

     FUNCTION INT_TO_BOOL IS NEW
                               UNCHECKED_CONVERSION (INTEGER, BOOL_ARR);

     FUNCTION BOOL_TO_INT IS NEW UNCHECKED_CONVERSION(BOOL_ARR,INTEGER);

BEGIN
     TEST ("CDA201A", "CHECK THAT UNCHECKED_CONVERSION CAN BE " &
                      "INSTANTIATED FOR CONVERSION BETWEEN " &
                      "INTEGER AND BOOLEAN ARRAY TYPES");

     I := BOOL_TO_INT((1..INTEGER'SIZE => IDENT_BOOL(TRUE)));

     IF INT_TO_BOOL(IDENT_INT(I)) /= (1..INTEGER'SIZE => TRUE) THEN
          FAILED("INCORRECT RESULT FROM ARRAY-INTEGER-ARRAY");
     END IF;

     B := INT_TO_BOOL(IDENT_INT(-1));

     FOR J IN B'RANGE LOOP
          B(J) := IDENT_BOOL(B(J));
     END LOOP;

     IF BOOL_TO_INT(B) /= -1 THEN
          FAILED("INCORRECT RESULT FROM INTEGER-ARRAY-INTEGER");
     END IF;

     RESULT;
END CDA201A;
