-- CDA201B.ADA

-- OBJECTIVE:
--     CHECK THAT UNCHECKED_CONVERSION CAN BE INSTANTIATED FOR
--     CONVERSION BETWEEN FLOAT AND BOOLEAN ARRAY TYPES.

-- HISTORY:
--     JET 09/12/88  CREATED ORIGINAL TEST.
--     DHH 05/17/89  CHANGED FROM '.DEP' TEST TO '.ADA' TEST.

WITH REPORT; USE REPORT;
WITH UNCHECKED_CONVERSION;
PROCEDURE CDA201B IS

     TYPE BOOL_ARR IS ARRAY (1..FLOAT'SIZE) OF BOOLEAN;
     PRAGMA PACK (BOOL_ARR);

     B : BOOL_ARR;

     FUNCTION FLT_TO_BOOL IS NEW UNCHECKED_CONVERSION(FLOAT, BOOL_ARR);

     FUNCTION BOOL_TO_FLT IS NEW UNCHECKED_CONVERSION(BOOL_ARR, FLOAT);

BEGIN
     TEST ("CDA201B", "CHECK THAT UNCHECKED_CONVERSION CAN BE " &
                      "INSTANTIATED FOR CONVERSION BETWEEN " &
                      "FLOAT AND BOOLEAN ARRAY TYPES");

     B := FLT_TO_BOOL(FLOAT'LARGE + FLOAT(IDENT_INT(0)));

     FOR J IN B'RANGE LOOP
          B(J) := B(J+IDENT_INT(0));
     END LOOP;

     IF BOOL_TO_FLT(B) /= FLOAT'LARGE THEN
          FAILED("INCORRECT RESULT FROM FLOAT-ARRAY-FLOAT");
     END IF;

     RESULT;
END CDA201B;
