-- CE2115B.ADA

-- OBJECTIVE:
--     CHECK WHETHER USE_ERROR IS RAISED BY SEQUENTIAL_IO CREATE
--     WHEN A NAMED EXTERNAL FILE ALREADY EXISTS AND OUT_FILE IS
--     THE SPECIFIED MODE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     SEQUENTIAL FILES.

-- HISTORY:
--     TBN 09/30/86
--     JLH 07/29/87 ADDED CHECK FOR USE_ERROR WHEN DELETING FILES.

WITH SEQUENTIAL_IO;
WITH REPORT; USE REPORT;

PROCEDURE CE2115B IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO (INTEGER);
     USE SEQ_IO;

     FILE1 : FILE_TYPE;
     INCOMPLETE : EXCEPTION;

BEGIN
     TEST ("CE2115B", "CHECK WHETHER USE_ERROR IS RAISED BY " &
                      "SEQUENTIAL_IO CREATE WHEN A NAMED EXTERNAL " &
                      "FILE ALREADY EXISTS AND OUT_FILE IS THE " &
                      "SPECIFIED MODE");

     -- INITIALIZE TEST FILE

     BEGIN
          CREATE (FILE1, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED DURING CREATE WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED DURING CREATE WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
     END;

     WRITE (FILE1, 24);
     CLOSE (FILE1);

     BEGIN
          CREATE (FILE1, OUT_FILE, LEGAL_FILE_NAME);
          COMMENT ("THIS IMPLEMENTATION DOES NOT RAISE USE_ERROR " &
                   "AND ALLOWS SECOND CREATE");
     EXCEPTION
          WHEN USE_ERROR =>
               COMMENT ("USE_ERROR RAISED DURING SECOND CREATE");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED DURING SECOND " &
                       "CREATE");
     END;

     BEGIN
          IF IS_OPEN (FILE1) THEN
               DELETE (FILE1);
          END IF;
     EXCEPTION
          WHEN USE_ERROR =>
               NULL;
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2115B;
