-- CE2108B.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXTERNAL SEQUENTIAL FILE SPECIFIED BY A NULL STRING
--     NAME IS NOT ACCESSIBLE AFTER THE COMPLETION OF THE MAIN PROGRAM.

--     THIS TEST CHECKS THE SEQUENTIAL FILE AND TEXT FILE CREATED IN
--     CE2108A.ADA

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     TEXT FILES AND SEQUENTIAL FILES IN WHICH TEMPORARY FILES HAVE
--     NAMES THAT ARE NOT MORE THAN 255 CHARACTERS LONG.

-- HISTORY:
--     ABW 08/16/82
--     SPS 09/24/82
--     SPS 11/09/82
--     SPS 12/08/82
--     JBG 02/22/84  CHANGE TO .ADA TEST.
--     JBG 12/03/84
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     TBN 07/16/87  COMPLETELY REVISED TEST.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;
WITH TEXT_IO;

PROCEDURE CE2108B IS

     PACKAGE SEQ IS NEW SEQUENTIAL_IO (INTEGER);
     SEQ_NAME, FILE_NULL_NAME : SEQ.FILE_TYPE;
     TEXT_NAME, NAMES_FILE : TEXT_IO.FILE_TYPE;
     INCOMPLETE : EXCEPTION;

BEGIN

     TEST ("CE2108B", "CHECK THAT SEQUENTIAL FILES WITH NULL STRING " &
                      "NAMES ARE NOT ACCESSIBLE AFTER COMPLETION OF " &
                      "THE PROGRAM WHICH CREATES THEM");

     -- CHECK FOR SUPPORT OF SEQUENTIAL FILES.

     BEGIN
          SEQ.CREATE (SEQ_NAME);
          SEQ.CLOSE (SEQ_NAME);
     EXCEPTION
          WHEN SEQ.USE_ERROR | SEQ.NAME_ERROR =>
               NOT_APPLICABLE ("TEMPORARY SEQUENTIAL FILES NOT " &
                               "SUPPORTED");
               RAISE INCOMPLETE;
     END;

     -- CHECK FOR SUPPORT OF TEXT FILES.

     BEGIN
          TEXT_IO.CREATE (TEXT_NAME);
          TEXT_IO.CLOSE (TEXT_NAME);
     EXCEPTION
          WHEN TEXT_IO.USE_ERROR | TEXT_IO.NAME_ERROR =>
               NOT_APPLICABLE ("TEMPORARY TEXT FILES NOT SUPPORTED");
               RAISE INCOMPLETE;
     END;

     -- BEGIN ACTUAL TEST OBJECTIVE.

     BEGIN
          TEXT_IO.OPEN (NAMES_FILE, TEXT_IO.IN_FILE,
                        LEGAL_FILE_NAME(1, "CE2108A"));
     EXCEPTION
          WHEN TEXT_IO.USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON OPEN OF TEXT " &
                               "FILE WITH IN_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON OPENING " &
                       "OF TEXT FILE, WHICH SHOULD HAVE BEEN " &
                       "CREATED BY TEST CE2108A.ADA");
               RAISE INCOMPLETE;
     END;

     DECLARE
          TEMP_LEN : NATURAL;
          TEMP_NAME : STRING (1 .. 255);
     BEGIN
          TEXT_IO.GET_LINE (NAMES_FILE, TEMP_NAME, TEMP_LEN);
          IF TEMP_NAME(1..3) = "HAS" THEN
               TEXT_IO.GET_LINE (NAMES_FILE, TEMP_NAME, TEMP_LEN);
               BEGIN
                    SEQ.OPEN (FILE_NULL_NAME, SEQ.IN_FILE,
                              TEMP_NAME (1 .. TEMP_LEN));
                    FAILED ("SEQ TEMP FILE ACCESSIBLE AFTER " &
                            "MAIN PROGRAM COMPLETED");
                    BEGIN
                         SEQ.DELETE (FILE_NULL_NAME);
                    EXCEPTION
                         WHEN SEQ.USE_ERROR =>
                              NULL;
                         WHEN OTHERS =>
                              FAILED ("UNEXPECTED EXCEPTION RAISED " &
                                      "ON DELETE OF TEMP SEQ FILE");
                    END;
               EXCEPTION
                    WHEN SEQ.NAME_ERROR =>
                         NULL;
                    WHEN OTHERS =>
                         FAILED ("UNEXPECTED EXCEPTION RAISED ON " &
                                 "ATTEMPT TO OPEN SEQ TEMP FILE");
               END;
          ELSIF TEMP_NAME(1..3) = "TOO" THEN
               NOT_APPLICABLE ("A TEMPORARY SEQUENTIAL FILE HAS A " &
                               "NAME LONGER THAN 255 CHARACTERS");
          ELSE
               NOT_APPLICABLE ("A TEMPORARY SEQUENTIAL FILE HAS NO " &
                               "NAME");
          END IF;
     EXCEPTION
          WHEN OTHERS =>
               FAILED ("EXCEPTION RAISED - UNABLE TO READ TEMP " &
                       "FILE NAME");
     END;

     BEGIN
          TEXT_IO.DELETE (NAMES_FILE);
     EXCEPTION
          WHEN TEXT_IO.USE_ERROR =>
               NULL;
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;
END CE2108B;
