-- CE2111A.ADA

-- OBJECTIVE:
--     CHECK THAT THE FILE REMAINS OPEN AFTER A RESET.

--     THIS OBJECTIVE IS BEING INTERPRETED AS : CHECK THAT A FILE
--     REMAINS OPEN AFTER AN ATTEMPT TO RESET.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     SEQUENTIAL FILES.

-- HISTORY:
--     DLD 08/13/82
--     SPS 11/09/82
--     JBG 03/24/83
--     EG  05/28/85
--     JLH 07/22/87  REWROTE TEST ALGORITHM.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2111A IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO(INTEGER);
          USE SEQ_IO;

     SEQ_FILE : SEQ_IO.FILE_TYPE;
     VAR1 : INTEGER := 5;
     INCOMPLETE : EXCEPTION;

BEGIN

     TEST ("CE2111A", "CHECK THAT THE FILE REMAINS OPEN AFTER A RESET");

-- CREATE SEQUENTIAL TEST FILE

     BEGIN
          CREATE (SEQ_FILE, OUT_FILE, LEGAL_FILE_NAME);
          WRITE (SEQ_FILE, VAR1);
          CLOSE (SEQ_FILE);
     EXCEPTION
          WHEN USE_ERROR | NAME_ERROR =>
               NOT_APPLICABLE ("SEQUENTIAL FILES NOT SUPPORTED");
               RAISE INCOMPLETE;
     END;

-- OPEN FILE

     BEGIN
          OPEN (SEQ_FILE, IN_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("OPEN WITH IN_FILE MODE NOT SUPPORTED " &
                               "FOR SEQ_IO");
               RAISE INCOMPLETE;
     END;

-- RESET FILE

     BEGIN
          RESET(SEQ_FILE);
     EXCEPTION
          WHEN USE_ERROR  =>
               NULL;
     END;

     IF IS_OPEN (SEQ_FILE) THEN
          CLOSE (SEQ_FILE);
     ELSE
          FAILED ("RESET FOR IN_FILE, CLOSED FILE");
     END IF;

-- RE-OPEN AS OUT_FILE AND REPEAT TEST

     BEGIN
          OPEN (SEQ_FILE, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("OPEN WITH OUT_FILE MODE NOT " &
                               "SUPPORTED FOR SEQ_IO");
               RAISE INCOMPLETE;
     END;

     BEGIN
          RESET (SEQ_FILE);
     EXCEPTION
          WHEN USE_ERROR  =>
               NULL;
     END;

     IF IS_OPEN (SEQ_FILE) THEN
          BEGIN
               DELETE (SEQ_FILE);
          EXCEPTION
               WHEN USE_ERROR =>
                    NULL;
          END;
     ELSE
          FAILED ("RESET FOR OUT_FILE, CLOSED FILE");
     END IF;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2111A;
