-- CE2107F.ADA

-- OBJECTIVE:
--     CHECK WHETHER OR NOT MORE THAN ONE INTERNAL FILE MAY BE
--     ASSOCIATED WITH THE SAME EXTERNAL FILE FOR DIRECT IO WHEN
--     BOTH FILES ARE READING.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     MULTIPLE ACCESS OF EXTERNAL FILES WHEN BOTH FILES ARE READING.

-- HISTORY:
--     ABW 08/13/82
--     SPS 11/09/82
--     JBG 03/24/83
--     JBG 06/04/84
--     EG  05/08/85
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 09/24/87  CORRECTED EXCEPTION HANDLING AND READ THE VALUE
--                   FROM THE FILE THAT WAS WRITTEN.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2107F IS

     PACKAGE DIR IS NEW DIRECT_IO (INTEGER);
     USE DIR;
     FILE_DIR1,FILE_DIR2 : DIR.FILE_TYPE;
     ITEM : INTEGER;
     INCOMPLETE : EXCEPTION;

BEGIN

     TEST( "CE2107F", "CHECK WHETHER SEVERAL INTERNAL " &
                      "FILES MAY ACCESS THE SAME " &
                      "EXTERNAL FILE FOR READING WITH DIRECT IO" );

     BEGIN
          CREATE(FILE_DIR1, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; DIRECT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED; DIRECT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; DIRECT CREATE");
               RAISE INCOMPLETE;
     END;

     WRITE (FILE_DIR1, 4);
     CLOSE (FILE_DIR1);

     BEGIN
          OPEN  (FILE_DIR1, IN_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; DIRECT OPEN WITH " &
                               "IN_FILE MODE");
               RAISE INCOMPLETE;
     END;

     BEGIN  -- ATTEMPT TO OPEN SECOND FILE
          OPEN (FILE_DIR2, IN_FILE, LEGAL_FILE_NAME);
          READ (FILE_DIR2, ITEM);
          IF ITEM /= 4 THEN
               FAILED ("INCORRECT VALUE READ");
          END IF;
          BEGIN
               CLOSE (FILE_DIR2);
          EXCEPTION
               WHEN OTHERS =>
                    FAILED ("UNABLE TO CLOSE SECOND DIR FILE");
          END;
     EXCEPTION
          WHEN DIR.USE_ERROR =>
               NOT_APPLICABLE ("THIS IMPLEMENTATION DOES NOT " &
                               "ALLOW TWO INTERNAL DIRECT " &
                               "FILES TO BE ASSOCIATED WITH THE " &
                               "SAME EXTERNAL FILE FOR READING");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON SECOND OPEN");
     END;

     BEGIN
          IF IS_OPEN(FILE_DIR1) THEN
               DELETE (FILE_DIR1);
          END IF;
     EXCEPTION
          WHEN DIR.USE_ERROR =>
               COMMENT ("IMPLEMENTATION WOULD NOT ALLOW DELETION OF " &
                        "EXTERNAL FILE");
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2107F;
