-- CE2108E.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXTERNAL SEQUENTIAL FILE SPECIFIED BY A NON-NULL
--     STRING NAME IS ACCESSIBLE AFTER THE COMPLETION OF THE MAIN
--     PROGRAM.

--     THIS TEST CREATES A SEQUENTIAL FILE;  CE2108F.ADA READS IT.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF AN EXTERNAL SEQUENTIAL FILE WITH OUT_FILE MODE.

-- HISTORY:
--     TBN 07/16/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2108E IS

     PACKAGE SEQ IS NEW SEQUENTIAL_IO (INTEGER);
     INCOMPLETE : EXCEPTION;
     FILE_NAME : SEQ.FILE_TYPE;
     PREVENT_EMPTY_FILE : NATURAL := 5;

BEGIN

     TEST ("CE2108E" , "CHECK THAT AN EXTERNAL SEQUENTIAL FILE " &
                       "SPECIFIED BY A NON-NULL STRING NAME IS " &
                       "ACCESSIBLE AFTER THE COMPLETION OF THE MAIN " &
                       "PROGRAM");
     BEGIN
          BEGIN
               SEQ.CREATE (FILE_NAME, SEQ.OUT_FILE, LEGAL_FILE_NAME);
          EXCEPTION
               WHEN SEQ.USE_ERROR =>
                    NOT_APPLICABLE ("USE_ERROR RAISED ON SEQUENTIAL " &
                                    "CREATE WITH OUT_FILE MODE");
                    RAISE INCOMPLETE;
               WHEN SEQ.NAME_ERROR =>
                    NOT_APPLICABLE ("NAME_ERROR RAISED ON SEQUENTIAL " &
                                    "CREATE WITH OUT_FILE MODE");
                    RAISE INCOMPLETE;
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED ON " &
                            "SEQUENTIAL CREATE");
                    RAISE INCOMPLETE;
          END;

          SEQ.WRITE (FILE_NAME, PREVENT_EMPTY_FILE);
          SEQ.CLOSE (FILE_NAME);

     EXCEPTION
          WHEN INCOMPLETE =>
               NULL;
     END;

     RESULT;

END CE2108E;
