-- CE2108F.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXTERNAL SEQUENTIAL FILE SPECIFIED BY A NON-NULL
--     STRING NAME IS ACCESSIBLE AFTER THE COMPLETION OF THE MAIN
--     PROGRAM.

--     THIS TEST CHECKS THE CREATION OF A SEQUENTIAL FILE WHICH WAS
--     CREATED BY CE2108E.ADA.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     SEQUENTIAL FILES.

-- HISTORY:
--     TBN 07/16/87  CREATED ORIGINAL TESTED.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2108F IS

     PACKAGE SEQ IS NEW SEQUENTIAL_IO (INTEGER);
     USE SEQ;
     INCOMPLETE : EXCEPTION;
     CHECK_SUPPORT, FILE_NAME : FILE_TYPE;
     PREVENT_EMPTY_FILE : NATURAL := 0;

BEGIN
     TEST ("CE2108F", "CHECK THAT AN EXTERNAL SEQUENTIAL FILE " &
                      "SPECIFIED BY A NON-NULL STRING NAME IS " &
                      "ACCESSIBLE AFTER THE COMPLETION OF THE MAIN " &
                      "PROGRAM");

     -- TEST FOR SEQUENTIAL FILE SUPPORT.

     BEGIN
          CREATE (CHECK_SUPPORT, OUT_FILE, LEGAL_FILE_NAME);
          BEGIN
               DELETE (CHECK_SUPPORT);
          EXCEPTION
               WHEN USE_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED ON DELETE");
          END;
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON SEQUENTIAL " &
                               "CREATE WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED ON SEQUENTIAL " &
                               "CREATE WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON " &
                       "SEQUENTIAL CREATE");
               RAISE INCOMPLETE;
     END;

     -- BEGIN TEST OBJECTIVE.

     BEGIN
          OPEN (FILE_NAME, IN_FILE, LEGAL_FILE_NAME(1, "CE2108E"));
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON OPEN FOR " &
                               "SEQUENTIAL FILE WITH IN_FILE " &
                               "MODE");
               RAISE INCOMPLETE;
     END;
     READ (FILE_NAME, PREVENT_EMPTY_FILE);
     IF PREVENT_EMPTY_FILE /= 5 THEN
          FAILED ("OPENED WRONG FILE OR DATA ERROR");
     END IF;
     BEGIN
          DELETE (FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               COMMENT ("IMPLEMENTATION WOULD NOT ALLOW DELETION OF " &
                        "EXTERNAL FILE");
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;
END CE2108F;
