-- CE2102F.ADA

-- OBJECTIVE:
--     CHECK THAT USE_ERROR IS RAISED WHEN CREATING A FILE OF MODE
--     INOUT_FILE, WHEN INOUT_FILE MODE IS NOT SUPPORTED FOR CREATE BY
--     THE IMPLEMENTATION FOR DIRECT_IO.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS ONLY APPLICABLE TO IMPLEMENTATIONS WHICH DO NOT
--     SUPPORT INOUT_FILE FOR CREATE FOR DIRECT FILES.

-- HISTORY:
--     SPS 08/26/82
--     JBG 06/04/84
--     TBN 07/23/87  COMPLETELY REVISED TEST.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2102F IS
BEGIN

     TEST ("CE2102F", "CHECK THAT USE_ERROR IS RAISED WHEN MODE " &
                      "INOUT_FILE IS NOT SUPPORTED FOR THE OPERATION " &
                      "OF CREATE FOR DIRECT_IO");
     DECLARE
          PACKAGE DIR IS NEW DIRECT_IO (BOOLEAN);
          USE DIR;
          FILE1 : FILE_TYPE;
     BEGIN
          CREATE (FILE1, INOUT_FILE);
          CLOSE (FILE1);
          NOT_APPLICABLE ("CREATE WITH MODE INOUT_FILE ALLOWED");
     EXCEPTION
          WHEN USE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON CREATE");
     END;

     RESULT;

END CE2102F;
