-- CE2105B.ADA

-- OBJECTIVE:
--     CHECK THAT CREATE IS PERMITTED FOR AN IN_FILE.

--          B) DIRECT FILES

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATE WITH IN_FILE MODE FOR DIRECT FILES.

-- HISTORY:
--     TBN 02/12/86
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     SPW 07/24/87  INSERTED ALLOWABLE EXCEPTION USE_ERROR ON
--                   DELETE.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2105B IS

BEGIN

     TEST( "CE2105B", "CHECK THAT CREATE IS PERMITTED FOR " &
                      "AN IN_FILE FOR DIRECT_IO");

     DECLARE
          PACKAGE DIR IS NEW DIRECT_IO (INTEGER);
          USE DIR;
          FILE2 : FILE_TYPE;
     BEGIN
          CREATE (FILE2, IN_FILE, LEGAL_FILE_NAME);
          BEGIN
               DELETE (FILE2);
          EXCEPTION
               WHEN USE_ERROR =>
                    COMMENT ("DELETION OF EXTERNAL FILE NOT SUPPORTED");
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED - DIR DELETE");
          END;
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; DIRECT CREATE " &
                               "WITH IN_FILE MODE");
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED; DIRECT CREATE " &
                               "WITH IN_FILE MODE");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; DIRECT CREATE");
     END;

     RESULT;

END CE2105B;
