-- CE2108G.ADA

-- OBJECTIVE:
--     CHECK THAT AN EXTERNAL DIRECT FILE SPECIFIED BY A NON-NULL
--     STRING NAME IS ACCESSIBLE AFTER THE COMPLETION OF THE MAIN
--     PROGRAM.

--     THIS TEST CREATES A DIRECT FILE;  CE2108H.ADA READS IT.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF AN EXTERNAL DIRECT FILE.

-- HISTORY:
--     TBN 07/16/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2108G IS

     PACKAGE DIR IS NEW DIRECT_IO (INTEGER);
     INCOMPLETE : EXCEPTION;
     FILE_NAME : DIR.FILE_TYPE;
     PREVENT_EMPTY_FILE : NATURAL := 5;

BEGIN

     TEST ("CE2108G", "CHECK THAT AN EXTERNAL DIRECT FILE SPECIFIED " &
                      "BY A NON-NULL STRING NAME IS ACCESSIBLE AFTER " &
                      "THE COMPLETION OF THE MAIN PROGRAM");
     BEGIN
          BEGIN
               DIR.CREATE (FILE_NAME, DIR.OUT_FILE, LEGAL_FILE_NAME);
          EXCEPTION
               WHEN DIR.USE_ERROR =>
                    NOT_APPLICABLE ("USE_ERROR RAISED ON DIRECT " &
                                    "CREATE WITH OUT_FILE MODE");
                    RAISE INCOMPLETE;
               WHEN DIR.NAME_ERROR =>
                    NOT_APPLICABLE ("NAME_ERROR RAISED ON DIRECT " &
                                    "CREATE WITH OUT_FILE MODE");
                    RAISE INCOMPLETE;
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED ON " &
                            "DIRECT CREATE");
                    RAISE INCOMPLETE;
          END;

          DIR.WRITE (FILE_NAME, PREVENT_EMPTY_FILE);
          DIR.CLOSE (FILE_NAME);

     EXCEPTION
          WHEN INCOMPLETE =>
               NULL;
     END;

     RESULT;

END CE2108G;
