-- CE2103C.ADA

-- OBJECTIVE:
--     CHECK THAT IS_OPEN RETURNS THE PROPER VALUES FOR FILES OF
--     TYPE SEQUENTIAL_IO.

--          B) OPENED FILES

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     SEQUENTIAL FILES.

-- HISTORY:
--     SPW 08/10/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2103C IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO(CHARACTER);
     USE SEQ_IO;
     INCOMPLETE : EXCEPTION;
     TEST_FILE_ONE : SEQ_IO.FILE_TYPE;
     VAL : BOOLEAN;

BEGIN

     TEST ("CE2103C", "CHECK THAT IS_OPEN RETURNS THE PROPER " &
                      "VALUES FOR FILES OF TYPE SEQUENTIAL_IO");

-- FOLLOWING A CREATE

     VAL := FALSE;

     BEGIN
          CREATE (TEST_FILE_ONE, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON CREATE WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED ON CREATE WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
     END;

     VAL := IS_OPEN (TEST_FILE_ONE);

     IF VAL = FALSE THEN
          FAILED ("IS_OPEN RETURNS FALSE AFTER CREATE");
     END IF;

-- FOLLOWING CLOSE

     VAL := TRUE;
     CLOSE (TEST_FILE_ONE);
     VAL := IS_OPEN (TEST_FILE_ONE);
     IF VAL = TRUE THEN
          FAILED ("IS_OPEN RETURNS TRUE AFTER CLOSE");
     END IF;

-- FOLLOWING OPEN

     VAL := FALSE;

     BEGIN
          OPEN (TEST_FILE_ONE, IN_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               IF IS_OPEN (TEST_FILE_ONE) /= FALSE THEN
                    FAILED ("IS_OPEN GIVES TRUE ON " &
                            "UNSUCESSFUL OPEN");
               END IF;
               RAISE INCOMPLETE;
     END;

     VAL := IS_OPEN (TEST_FILE_ONE);
     IF VAL = FALSE THEN
          FAILED ("IS_OPEN RETURNS FALSE AFTER OPEN");
     END IF;

-- AFTER RESET

     VAL := FALSE;

     BEGIN
          RESET (TEST_FILE_ONE);
     EXCEPTION
          WHEN USE_ERROR =>
               NULL;
     END;

     VAL := IS_OPEN (TEST_FILE_ONE);
     IF VAL = FALSE THEN
          FAILED ("IS_OPEN RETURNS FALSE AFTER RESET");
     END IF;

-- AFTER DELETE

     VAL := TRUE;

     BEGIN
          DELETE (TEST_FILE_ONE);
     EXCEPTION
          WHEN USE_ERROR =>
               IF IS_OPEN (TEST_FILE_ONE) /= FALSE THEN
                    FAILED ("IS_OPEN GIVES TRUE ON UNSUCCESSFUL " &
                            "DELETE");
               END IF;
               RAISE INCOMPLETE;
     END;

     VAL := IS_OPEN (TEST_FILE_ONE);
     IF VAL = TRUE THEN
          FAILED ("IS_OPEN RETURNS TRUE AFTER DELETE");
     END IF;

     RESULT;

EXCEPTION

     WHEN INCOMPLETE =>
          RESULT;

END CE2103C;
