-- CE2102L.ADA

-- OBJECTIVE:
--     CHECK TO SEE THAT STATUS_ERROR IS RAISED WHEN PERFORMING ILLEGAL
--     OPERATIONS ON OPENED OR UNOPENED FILES OF TYPE SEQUENTIAL_IO.

--          B) UNOPENED FILES

-- HISTORY:
--     SPW 07/29/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2102L IS

     PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO(INTEGER);
     USE SEQ_IO;

     TEST_FILE_ONE : SEQ_IO.FILE_TYPE;
     STR : STRING (1 .. 10);
     FL_MODE : SEQ_IO.FILE_MODE ;

BEGIN

     TEST ("CE2102L", "CHECK THAT STATUS_ERROR IS RAISED WHEN " &
                      "PERFORMING ILLEGAL OPERATIONS ON UNOPENED " &
                      "FILES OF TYPE SEQUENTIAL_IO");

-- CHECK TO SEE THAT PROPER EXCEPTIONS ARE RAISED WHEN
-- PERFORMING OPERATIONS ON AN UNOPENED FILE

-- CLOSE AN UNOPENED FILE

     BEGIN
          CLOSE (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED " &
                  "FILE IS USED IN A CLOSE");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON CLOSE");
     END;

-- DELETE AN UNOPENED FILE

     BEGIN
          DELETE (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED " &
                  "FILE IS USED IN A DELETE");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON DELETE");
     END;

-- RESET UNOPENED FILE

     BEGIN
          RESET (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED " &
                  "FILE IS USED IN A RESET");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON RESET");
     END;

     BEGIN
          RESET (TEST_FILE_ONE, IN_FILE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN A UNOPENED FILE " &
                  "IS USED IN A RESET WITH MODE PARAMETER");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON RESET " &
                       "WITH MODE");
     END;

-- ATTEMPT TO DETERMINE MODE OF UNOPENED FILE

     BEGIN
          FL_MODE := MODE (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN A UNOPENED " &
                  "FILE IS USED IN A MODE OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON MODE");
     END;

-- ATTEMPT TO DETERMINE NAME OF UNOPENED FILE

     BEGIN
          STR := NAME (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN A UNOPENED " &
                  "FILE IS USED IN A NAME OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON NAME");
     END;

--ATTEMPT TO DETERMINE FORM OF UNOPENED FILE

     BEGIN
          STR := FORM (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED " &
                  "FILE IS USED IN A FORM OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON FORM");
     END;

     RESULT;

END CE2102L;
