-- CE2105A.ADA

-- OBJECTIVE:
--     CHECK THAT CREATE IS PERMITTED FOR AN IN_FILE FOR SEQUENTIAL_IO.

--          A) SEQUENTIAL FILES

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATE WITH IN_FILE MODE FOR SEQUENTIAL FILES.

-- HISTORY:
--     ABW 08/10/82
--     SPS 11/09/82
--     JBG 03/24/83
--     TBN 02/12/86  SPLIT TEST.  PUT DIRECT_IO INTO CE2105B.ADA.
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     SPW 07/24/87  INSERTED ALLOWABLE EXCEPTION USE_ERROR ON DELETE.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2105A IS

BEGIN

     TEST( "CE2105A", "CHECK THAT CREATE IS PERMITTED FOR " &
                      "AN IN_FILE FOR SEQUENTIAL_IO");

     DECLARE
          PACKAGE SEQ IS NEW SEQUENTIAL_IO (INTEGER);
          USE SEQ;
          FILE  : FILE_TYPE;
     BEGIN
          CREATE (FILE, IN_FILE, LEGAL_FILE_NAME);
          BEGIN
               DELETE (FILE);
          EXCEPTION
               WHEN USE_ERROR =>
                    COMMENT ("DELETION OF EXTERNAL FILE NOT SUPPORTED");
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED - SEQ DELETE");
          END;
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; SEQUENTIAL CREATE " &
                               "WITH IN_FILE MODE");
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED; SEQUENTIAL CREATE " &
                               "WITH IN_FILE MODE");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; SEQUENTIAL " &
                       "CREATE");
     END;

     RESULT;

END CE2105A;
