-- CE2102M.ADA

-- OBJECTIVE:
--     CHECK TO SEE THAT STATUS_ERROR IS RAISED WHEN PERFORMING ILLEGAL
--     OPERATIONS ON OPENED OR UNOPENED FILES OF TYPE DIRECT_IO.

--          B) UNOPENED FILES

-- HISTORY:
--     SPW 02/24/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2102M IS

     PACKAGE DIR_IO IS NEW DIRECT_IO(INTEGER);
     USE DIR_IO;

     TEST_FILE_ONE : DIR_IO.FILE_TYPE;
     STR : STRING (1 .. 10);
     FL_MODE : DIR_IO.FILE_MODE ;

BEGIN

     TEST ("CE2102M", "CHECK THAT STATUS_ERROR IS RAISED WHEN " &
                      "PERFORMING ILLEGAL OPERATIONS ON UNOPENED " &
                      "FILES OF TYPE DIRECT_IO");

-- CHECK TO SEE THAT PROPER EXCEPTIONS ARE RAISED WHEN
-- PERFORMING OPERATIONS ON AN UNOPENED FILE

-- CLOSE AN UNOPENED FILE

     BEGIN
          CLOSE (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A CLOSE OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON CLOSE");
     END;

-- DELETE AN UNOPENED FILE

     BEGIN
          DELETE (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A DELETE OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON DELETE");
     END;

-- RESET UNOPENED FILE

     BEGIN
          RESET (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A RESET");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON RESET");
     END;

     BEGIN
          RESET (TEST_FILE_ONE, IN_FILE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A RESET WITH MODE PARAMETER");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON RESET WITH " &
                       "MODE PARAMETER");
     END;

-- ATTEMPT TO DETERMINE MODE OF UNOPENED FILE

     BEGIN
          FL_MODE := MODE (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A MODE OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON MODE");
     END;

-- ATTEMPT TO DETERMINE NAME OF UNOPENED FILE

     BEGIN
          STR := NAME (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A NAME OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON NAME");
     END;

--ATTEMPT TO DETERMINE FORM OF UNOPENED FILE

     BEGIN
          STR := FORM (TEST_FILE_ONE);
          FAILED ("STATUS_ERROR NOT RAISED WHEN AN UNOPENED FILE " &
                  "IS USED IN A FORM OPERATION");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON FORM");
     END;

     RESULT;
END CE2102M;
