-- CE2201C.ADA

-- OBJECTIVE:
--     CHECK THAT READ, WRITE, AND END_OF_FILE ARE SUPPORTED FOR
--     SEQUENTIAL FILES WITH ELEMENT_TYPE FLOAT.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     SEQUENTIAL FILES.

-- HISTORY:
--     ABW 08/17/82
--     SPS 11/10/82
--     JBG 20/22/84  CHANGED TO .ADA TEST.
--     EG  05/16/85
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 08/03/87  REMOVED DEPENDENCE OF RESET AND CREATED AN EXTERNAL
--                   FILE RATHER THAN A TEMPORARY FILE.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2201C IS
BEGIN

     TEST ("CE2201C", "CHECK THAT READ, WRITE, AND " &
                      "END_OF_FILE ARE SUPPORTED FOR " &
                      "SEQUENTIAL FILES - FLOAT");

     DECLARE
          PACKAGE SEQ_FLT IS NEW SEQUENTIAL_IO (FLOAT);
          USE SEQ_FLT;
          FILE_FLT : FILE_TYPE;
          INCOMPLETE : EXCEPTION;
          FLT : FLOAT := 65.0;
          ITEM_FLT : FLOAT;
     BEGIN
          BEGIN
               CREATE (FILE_FLT, OUT_FILE, LEGAL_FILE_NAME);
          EXCEPTION
               WHEN USE_ERROR | NAME_ERROR =>
                    NOT_APPLICABLE ("CREATE OF SEQUENTIAL FILE WITH " &
                                    "MODE OUT_FILE NOT SUPPORTED");
                    RAISE INCOMPLETE;
          END;

          WRITE (FILE_FLT, FLT);
          CLOSE (FILE_FLT);

          BEGIN
               OPEN (FILE_FLT, IN_FILE, LEGAL_FILE_NAME);
          EXCEPTION
               WHEN USE_ERROR =>
                    NOT_APPLICABLE ("OPEN OF SEQUENTIAL FILE WITH " &
                                    "MODE IN_FILE NOT SUPPORTED");
                    RAISE INCOMPLETE;
          END;

          IF END_OF_FILE (FILE_FLT) THEN
               FAILED ("WRONG END_OF_FILE VALUE FOR FLOATING POINT");
          END IF;

          READ (FILE_FLT, ITEM_FLT);

          IF ITEM_FLT /= 65.0 THEN
               FAILED ("READ WRONG VALUE - FLOAT");
          END IF;

          IF NOT END_OF_FILE (FILE_FLT) THEN
               FAILED ("END OF FILE NOT TRUE - FLOAT");
          END IF;

          BEGIN
               DELETE (FILE_FLT);
          EXCEPTION
               WHEN USE_ERROR =>
                    NULL;
          END;

     EXCEPTION
          WHEN INCOMPLETE =>
               NULL;

     END;

     RESULT;

END CE2201C;
