-- CE2204C.ADA

-- OBJECTIVE:
--     CHECK THAT WRITE IS FORBIDDEN FOR SEQUENTIAL FILES OF
--     MODE IN_FILE.

--          B)  CHECK TEMPORARY FILES.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     TEMPORARY SEQUENTIAL FILES AND THE RESETTING FROM OUT_FILE
--     TO IN_FILE.

-- HISTORY:
--     GMT 07/27/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SEQUENTIAL_IO;

PROCEDURE CE2204C IS
     INCOMPLETE : EXCEPTION;
BEGIN
     TEST ("CE2204C", "CHECK THAT MODE_ERROR IS RAISED BY WRITE " &
                      "WHEN THE MODE IS INFILE AND THE FILE IS " &
                      "A TEMPORARY FILE");
     DECLARE
          PACKAGE SEQ_IO IS NEW SEQUENTIAL_IO (INTEGER);
          USE SEQ_IO;
          FT   : FILE_TYPE;
          VAR1 : INTEGER  := 5;
     BEGIN
          BEGIN
               CREATE (FT, OUT_FILE);
          EXCEPTION
               WHEN USE_ERROR =>
                    NOT_APPLICABLE ("USE_ERROR RAISED ON CREATE - 1");
                    RAISE INCOMPLETE;
          END;

          WRITE (FT, VAR1);

          BEGIN
               RESET (FT, IN_FILE);
          EXCEPTION
               WHEN USE_ERROR =>
                    NOT_APPLICABLE ("USE_ERROR RAISED ON RESET - 2");
                    RAISE INCOMPLETE;
          END;

          BEGIN
               WRITE(FT, 3);
               FAILED ("MODE_ERROR NOT RAISED ON WRITE - 3");
          EXCEPTION
               WHEN MODE_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED ("WRONG EXCEPTION RAISED ON WRITE - 4");
          END;

          CLOSE (FT);
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2204C;
