-- CE2404B.ADA

-- OBJECTIVE:
--     CHECK THAT READ RAISES MODE_ERROR WHEN THE CURRENT MODE IS
--     OUT_FILE.

--          B)  CHECK TEMPORARY FILES.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF DIRECT FILES WITH MODE OUT_FILE.

-- HISTORY:
--     GMT 08/03/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2404B IS

     PACKAGE DIR_IO IS NEW DIRECT_IO(INTEGER);
     USE DIR_IO;
     DIR_FILE_2 : FILE_TYPE;
     I          : INTEGER;
     INCOMPLETE : EXCEPTION;

BEGIN
     TEST ("CE2404B", "CHECK THAT READ RAISES MODE_ERROR WHEN THE " &
                      "CURRENT MODE IS OUT_FILE AND THE FILE IS " &
                      "A TEMPORARY FILE");
     BEGIN
          CREATE (DIR_FILE_2, OUT_FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON CREATE - 1");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON CREATE - 2");
               RAISE INCOMPLETE;
     END;

     BEGIN
          READ(DIR_FILE_2, I);
          FAILED("MODE_ERROR NOT RAISED ON READ - 3");
     EXCEPTION
          WHEN MODE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED("WRONG EXCEPTION RAISED ON READ - 4");
     END;

     CLOSE (DIR_FILE_2);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2404B;
