-- CE2410A.ADA

-- OBJECTIVE:
--     CHECK THAT END_OF_FILE RAISES MODE_ERROR WHEN THE CURRENT
--     MODE IS OUT_FILE.

--          1) CHECK NON-TEMPORARY FILES.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATE WITH OUT_FILE MODE FOR DIRECT FILES.

-- HISTORY:
--     ABW 08/20/82
--     SPS 09/16/82
--     SPS 11/09/82
--     JBG 02/22/84  CHANGED TO .ADA TEST
--     EG  11/02/84
--     EG  05/16/85
--     GMT 08/05/87  REVISED EXCEPTION HANDLING AND MOVED THE CASE FOR
--                   TEMPORARY FILES INTO CE2410B.ADA.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2410A IS

     PACKAGE DIR IS NEW DIRECT_IO (INTEGER);
     USE DIR;
     FILE1       : FILE_TYPE;
     INT         : INTEGER := IDENT_INT (18);
     BOOL        : BOOLEAN;
     INCOMPLETE  : EXCEPTION;

BEGIN

     TEST ("CE2410A", "CHECK THAT END_OF_FILE RAISES MODE_ERROR WHEN " &
                      "THE CURRENT MODE IS OUT_FILE AND THE FILE IS " &
                      "A NON-TEMPORARY FILE.");

     BEGIN
          CREATE (FILE1, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR | NAME_ERROR =>
               NOT_APPLICABLE ("CREATE WITH MODE OUT_FILE NOT " &
                               "SUPPORTED FOR DIRECT FILES - 1");
               RAISE INCOMPLETE;
     END;

     BEGIN
          BOOL := END_OF_FILE (FILE1);
          FAILED ("MODE_ERROR NOT RAISED ON END_OF_FILE - 2");
     EXCEPTION
          WHEN MODE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON " &
                       "END_OF_FILE - 3");
     END;

     BEGIN
          DELETE (FILE1);
     EXCEPTION
          WHEN USE_ERROR =>
               NULL;
     END;

     RESULT ;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2410A ;
