-- CE2409B.ADA

-- OBJECTIVE:
--     FOR DIRECT ACCESS FILES, CHECK THAT A WRITE TO A POSITION
--     GREATER THAN THE CURRENT END POSITION CAUSES THE WRITE
--     POSITION AND THE FILE SIZE TO BE INCREMENTED.

--          2) CHECK FILES OF MODE OUT_FILE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATE WITH MODE OUT_FILE FOR DIRECT FILES.

-- HISTORY:
--     GMT 08/05/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2409B IS

     PACKAGE DIR IS NEW DIRECT_IO (INTEGER);
     USE DIR;
     FILE1      : FILE_TYPE;
     INCOMPLETE : EXCEPTION;

BEGIN

     TEST ("CE2409B", "CHECK THAT WRITE POSITION AND " &
                      "SIZE ARE INCREMENTED APPROPRIATELY");
     BEGIN
          CREATE (FILE1, OUT_FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("CREATE WITH MODE OUT_FILE NOT " &
                               "SUPPORTED FOR DIR FILES - 1");
               RAISE INCOMPLETE;
     END;

     DECLARE
          INT      : INTEGER := IDENT_INT (18);
          TWO_C    : COUNT := COUNT (IDENT_INT(2));
          THREE_C  : COUNT := COUNT (IDENT_INT(3));
          THREE_PC : POSITIVE_COUNT
                           := POSITIVE_COUNT (IDENT_INT(3));
          FOUR_PC  : POSITIVE_COUNT
                           := POSITIVE_COUNT (IDENT_INT(4));
     BEGIN
          WRITE (FILE1, INT);
          WRITE (FILE1, INT);
          IF INDEX (FILE1) /= THREE_PC THEN
               FAILED ("INCORRECT VALUE FOR INDEX - 2");
          END IF;
          IF SIZE (FILE1) /= TWO_C THEN
               FAILED ("INCORRECT VALUE FOR SIZE - 3");
          END IF;

          WRITE (FILE1, INT);
          IF INDEX (FILE1) /= FOUR_PC THEN
               FAILED ("INCORRECT VALUE FOR INDEX - 4");
          END IF;
          IF SIZE (FILE1) /= THREE_C THEN
               FAILED ("INCORRECT VALUE FOR SIZE - 5");
          END IF;

     END;

     CLOSE (FILE1);

     RESULT ;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2409B ;
