-- CE2410B.ADA

-- OBJECTIVE:
--     CHECK THAT END_OF_FILE RAISES MODE_ERROR WHEN THE CURRENT
--     MODE IS OUT_FILE.

--          2) CHECK TEMPORARY FILES.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATE WITH OUT_FILE MODE FOR DIRECT FILES.

-- HISTORY:
--     GMT 08/05/87  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH DIRECT_IO;

PROCEDURE CE2410B IS

     PACKAGE DIR IS NEW DIRECT_IO (INTEGER);
     USE DIR;
     FILE1       : FILE_TYPE;
     INT         : INTEGER := IDENT_INT (18);
     BOOL        : BOOLEAN;
     INCOMPLETE  : EXCEPTION;

BEGIN

     TEST ("CE2410B", "CHECK THAT END_OF_FILE RAISES MODE_ERROR WHEN " &
                      "THE CURRENT MODE IS OUT_FILE AND THE FILE IS " &
                      "A TEMPORARY FILE.");

     BEGIN
          CREATE (FILE1, OUT_FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("CREATE WITH OUT_FILE MODE NOT " &
                               "SUPPORTED FOR DIRECT FILES - 1");
               RAISE INCOMPLETE;
     END;

     BEGIN
          BOOL := END_OF_FILE (FILE1);
          FAILED ("MODE_ERROR NOT RAISED ON END_OF_FILE - 2");
     EXCEPTION
          WHEN MODE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("WRONG EXCEPTION RAISED ON " &
                       "END_OF_FILE - 3");
     END;

     CLOSE (FILE1);

     RESULT ;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE2410B ;
