-- CE3002D.ADA

-- CHECK THAT NUMBER_BASE IS A SUBTYPE OF INTEGER, WITH
-- NUMBER_BASE'FIRST EQUAL 2 AND NUMBER_BASE'LAST EQUAL 16.

-- SPS 10/1/82

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3002D IS
BEGIN

     TEST ("CE3002D", "CHECK THAT NUMBER_BASE IS A SUBTYPE " &
                      "OF INTEGER WITH NUMBER_BASE'FIRST = 2 " &
                      "AND NUMBER_BASE'LAST = 16");

     DECLARE
          X : INTEGER;
          Y : NUMBER_BASE;
     BEGIN
          IF NUMBER_BASE'FIRST /= IDENT_INT (2) THEN
               FAILED ("NUMBER_BASE'FIRST NOT 2");
          END IF;

          IF NUMBER_BASE'LAST /= IDENT_INT (16) THEN
               FAILED ("NUMBER_BASE'LAST NOT 16");
          END IF;

          X := IDENT_INT (3);
          Y := X;
          Y := IDENT_INT (8);
          X := Y;
     END;

RESULT;
END CE3002D;
