-- CE3109A.ADA

-- OBJECTIVE:
--     CHECK THAT CREATE IS PERMITTED FOR AN IN_FILE.

-- HISTORY:
--     ABW  08/10/82
--     SPS  11/09/82
--     JBG  03/24/83
--     TBN  11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                    RESULT WHEN FILES ARE NOT SUPPORTED.
--     GMT  08/14/87  REMOVED UNNECESSARY CODE AND ADDED A CHECK FOR
--                    USE_ERROR ON DELETE.

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;

PROCEDURE CE3109A IS

BEGIN

     TEST ("CE3109A", "CHECK THAT CREATE IS PERMITTED FOR " &
                      "AN IN_FILE");

     DECLARE
          FILE1 : FILE_TYPE;
     BEGIN
          CREATE (FILE1, IN_FILE, LEGAL_FILE_NAME);
          BEGIN
               DELETE (FILE1);
          EXCEPTION
               WHEN USE_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED FOR DELETE");
          END;
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("CREATE WITH IN_FILE MODE FOR TEXT " &
                               "FILES RAISES USE_ERROR");
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("CREATE WITH IN_FILE MODE FOR TEXT " &
                               "FILES RAISES NAME_ERROR");
          WHEN OTHERS =>
               FAILED ("CREATE WITH IN_FILE MODE FOR TEXT FILES " &
                       "RAISES THE WRONG EXCEPTION");
     END;

     RESULT;

END CE3109A;
