-- CE3102G.ADA

-- OBJECTIVE:
--     CHECK THAT USE_ERROR IS RAISED WHEN AN EXTERNAL FILE
--     CANNOT BE DELETED.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     TEXT FILES, BUT DO NOT SUPPORT DELETION OF EXTERNAL FILES.

-- HISTORY:
--     JLH 08/12/87  CREATED ORIGINAL TEST.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3102G IS

     INCOMPLETE : EXCEPTION;
     FILE : FILE_TYPE;
     VAR1 : CHARACTER := 'A';

BEGIN

     TEST ("CE3102G" , "CHECK THAT USE_ERROR IS RAISED WHEN AN " &
                       "EXTERNAL FILE CANNOT BE DELETED");

     BEGIN
          CREATE (FILE, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON CREATE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED ON CREATE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               NOT_APPLICABLE ("UNEXPECTED EXCEPTION RAISED ON CREATE");
               RAISE INCOMPLETE;
     END;

     PUT (FILE, VAR1);

     BEGIN
          DELETE (FILE);
          NOT_APPLICABLE ("DELETION OF EXTERNAL FILES ALLOWED");
     EXCEPTION
          WHEN USE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED FOR DELETE");
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3102G;
