-- CE3202A.ADA

-- CHECK THAT CURRENT_INPUT AND CURRENT_OUTPUT INITIALLY
-- CORRESPOND TO STANDARD FILES.

-- ABW  8/25/82
-- SPS  11/9/82
-- JBG  3/17/83
-- JBG 5/8/84

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3202A IS


BEGIN

     TEST ("CE3202A", "CHECK THAT CURRENT_INPUT AND " &
                      "CURRENT_OUTPUT INITIALLY " &
                      "CORRESPOND TO STANDARD FILES");

     IF NAME (CURRENT_INPUT) /= NAME (STANDARD_INPUT) THEN
          FAILED ("CURRENT_INPUT INCORRECT - NAME");
     END IF;

     IF NAME (CURRENT_OUTPUT) /= NAME (STANDARD_OUTPUT) THEN
          FAILED ("CURRENT_OUTPUT INCORRECT - NAME");
     END IF;

     RESULT;

END CE3202A;
