-- CE3306A.ADA

-- OBJECTIVE:
--     CHECK THAT CONSTRAINT_ERROR IS RAISED IF THE VALUE OF 'TO' IS
--     NEGATIVE OR GREATER THAN COUNT'LAST WHEN COUNT'LAST IS LESS THAN
--     COUNT'BASE'LAST.

-- HISTORY:
--     JET 08/17/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;
PROCEDURE CE3306A IS

BEGIN
     TEST ("CE3306A", "CHECK THAT CONSTRAINT_ERROR IS RAISED IF THE " &
                      "VALUE OF 'TO' IS NEGATIVE OR GREATER THAN " &
                      "COUNT'LAST WHEN COUNT'LAST IS LESS THAN " &
                      "COUNT'BASE'LAST");

     BEGIN
          SET_LINE_LENGTH(-1);
          FAILED("NO EXCEPTION FOR SET_LINE_LENGTH(-1)");
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED("UNEXPECTED EXCEPTION FOR SET_LINE_LENGTH(-1)");
     END;

     BEGIN
          SET_PAGE_LENGTH(COUNT(IDENT_INT(-1)));
          FAILED("NO EXCEPTION FOR SET_PAGE_LENGTH(-1)");
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED("UNEXPECTED EXCEPTION FOR SET_PAGE_LENGTH(-1)");
     END;

     IF COUNT'LAST < COUNT'BASE'LAST THEN
          BEGIN
               SET_LINE_LENGTH(COUNT'LAST + COUNT(IDENT_INT(1)));
               FAILED("NO EXCEPTION FOR SET_LINE_LENGTH(COUNT'LAST+1)");
          EXCEPTION
               WHEN CONSTRAINT_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED("UNEXPECTED EXCEPTION FOR SET_LINE_LENGTH" &
                           "(COUNT'LAST+1)");
          END;

          BEGIN
               SET_PAGE_LENGTH(COUNT'LAST + 1);
               FAILED("NO EXCEPTION FOR SET_PAGE_LENGTH(COUNT'LAST+1)");
          EXCEPTION
               WHEN CONSTRAINT_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED("UNEXPECTED EXCEPTION FOR SET_PAGE_LENGTH" &
                           "(COUNT'LAST+1)");
          END;
     ELSE
          COMMENT("COUNT'LAST IS EQUAL TO COUNT'BASE'LAST");
     END IF;

     RESULT;
END CE3306A;
