-- CE3406D.ADA

-- OBJECTIVE:
--     CHECK THAT SKIP_PAGE OPERATES ON THE CURRENT DEFAULT INPUT
--     FILE WHEN NO FILE IS SPECIFIED.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     TEXT FILES.

-- HISTORY:
--     ABW 08/26/82
--     JBG 01/26/83
--     TBN 11/10/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 09/24/87  CREATED NON-TEMPORARY FILE, REMOVED DEPENDENCE
--                   ON RESET, AND CHECKED CHARACTER READ IN.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3406D IS

     INCOMPLETE : EXCEPTION;
     FILE : FILE_TYPE;
     ITEM_CHAR : CHARACTER;
     TWO : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(2));
     THREE : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(3));

BEGIN

     TEST ("CE3406D", "CHECK THAT SKIP_PAGE OPERATES ON THE CURRENT " &
                      "DEFAULT INPUT FILE WHEN NO FILE IS SPECIFIED");

     BEGIN
          CREATE (FILE, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED ON TEXT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     PUT (FILE, "ABC");
     NEW_PAGE (FILE);
     PUT (FILE, "DEF");

     CLOSE (FILE);

     BEGIN
          OPEN (FILE, IN_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT OPEN WITH " &
                               "IN_FILE MODE");
               RAISE INCOMPLETE;
     END;

     SET_INPUT (FILE);

     SKIP_PAGE;

     GET (FILE, ITEM_CHAR);
     IF ITEM_CHAR /= 'D' THEN
          FAILED ("INCORRECT VALUE READ FROM FILE");
     END IF;

     IF PAGE (CURRENT_INPUT) /= TWO THEN
          FAILED ("SKIP_PAGE NOT APPLIED TO CURRENT_INPUT");
     END IF;

     SKIP_PAGE (FILE);

     IF PAGE (CURRENT_INPUT) /= THREE THEN
          FAILED ("SKIP_PAGE NOT APPLIED TO CURRENT_INPUT");
     END IF;

     BEGIN
          DELETE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NULL;
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3406D;
