-- CE3403C.ADA

-- OBJECTIVE:
--     CHECK THAT SKIP_LINE SETS THE CURRENT COLUMN NUMBER TO ONE,
--     AND THAT IT IS PERFORMED SPACING TIMES.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH
--     SUPPORT TEXT FILES.

-- HISTORY:
--     ABW 08/26/82
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     DWC 09/08/87  REVISED EXCEPTION HANDLING, REMOVED
--                   DEPENDENCE ON RESET, AND ADDED NEW CASES.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3403C IS

     INCOMPLETE : EXCEPTION;
     FILE : FILE_TYPE;
     ONE : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(1));
     SPAC3 : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(3));
     FOUR : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(4));
     CH: CHARACTER;

BEGIN

     TEST ("CE3403C" , "CHECK THAT SKIP_LINE SETS THE CURRENT " &
                       "COLUMN NUMBER TO ONE, AND THAT IT IS " &
                       "PERFORMED SPACING TIMES");

     BEGIN
          CREATE (FILE, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; TEXT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED; TEXT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     FOR I IN 'A' .. 'E' LOOP
          FOR J IN 1 .. 3 LOOP
               PUT (FILE, I);
          END LOOP;
          NEW_LINE (FILE);
     END LOOP;

     CLOSE (FILE);

     BEGIN
           OPEN (FILE, IN_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; TEXT OPEN " &
                               "FOR IN_FILE MODE");
               RAISE INCOMPLETE;
     END;

     IF COL (FILE) /= ONE THEN
          FAILED ("COLUMN NOT SET TO ONE");
     END IF;

     GET (FILE, CH);

     IF CH /= 'A' THEN
          FAILED ("INCORRECT VALUE READ - 1");
     END IF;

     SKIP_LINE (FILE,SPAC3);
     GET (FILE, CH);

     IF CH /= 'D' THEN
          FAILED ("INCORRECT VALUE READ - 2");
     END IF;

     IF LINE (FILE) /= FOUR THEN
          FAILED ("NOT PERFORMED SPACING TIMES");
     END IF;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3403C;
