-- CE3410B.ADA

-- OBJECTIVE:
--     CHECK THAT SET_LINE RAISES CONSTRAINT_ERROR IF THE GIVEN
--     LINE NUMBER IS ZERO, NEGATIVE, OR GREATER THAN COUNT'LAST
--     WHEN COUNT'LAST < COUNT'BASE'LAST.

-- HISTORY:
--     ABW 08/26/82
--     SPS 09/22/82
--     JBG 01/27/83
--     JLH 08/31/87  ADDED CASE FOR COUNT'LAST.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3410B IS

     FILE : FILE_TYPE;

BEGIN

     TEST ("CE3410B", "CHECK THAT SET_LINE RAISES CONSTRAINT_ERROR " &
                      "IF THE GIVEN LINE NUMBER IS ZERO, NEGATIVE, " &
                      "OR GREATER THAN COUNT'LAST WHEN COUNT'LAST < " &
                      "COUNT'BASE'LAST");

     BEGIN
          SET_LINE (FILE, POSITIVE_COUNT(IDENT_INT(0)));
          FAILED ("CONSTRAINT_ERROR NOT RAISED FOR ZERO");
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN STATUS_ERROR =>
               FAILED ("STATUS_ERROR INSTEAD OF CONSTRAINT_ERROR - 1");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED FOR ZERO");
     END;

     BEGIN
          SET_LINE (FILE, POSITIVE_COUNT(IDENT_INT(-2)));
          FAILED ("CONSTRAINT_ERROR NOT RAISED FOR NEGATIVE NUMBER");
     EXCEPTION
          WHEN CONSTRAINT_ERROR =>
               NULL;
          WHEN STATUS_ERROR =>
               FAILED ("STATUS_ERROR INSTEAD OF CONSTRAINT_ERROR - 2");
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED FOR NEGATIVE " &
                       "NUMBER");
     END;

     IF COUNT'LAST < COUNT'BASE'LAST THEN
          BEGIN
               SET_LINE (FILE, COUNT'LAST + 1);
               FAILED ("CONSTRAINT_ERROR NOT RAISED FOR COUNT'LAST " &
                       "+ 1");
          EXCEPTION
               WHEN CONSTRAINT_ERROR =>
                    NULL;
               WHEN STATUS_ERROR =>
                    FAILED ("STATUS_ERROR INSTEAD OF " &
                            "CONSTRAINT_ERROR - 3");
               WHEN OTHERS =>
                    FAILED ("UNEXPECTED EXCEPTION RAISED FOR " &
                            "COUNT'LAST + 1");
          END;
     END IF;

     RESULT;

END CE3410B;
