-- CE3402D.ADA

-- OBJECTIVE:
--     CHECK THAT NEW_LINE SETS THE CURRENT COLUMN NUMBER TO ONE,
--     AND NEW_LINE OUTPUTS LINE TERMINATORS WHEN THE SPACING IS
--     GREATER THAN ONE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS ONLY APPLICABLE TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATE WITH OUT_FILE MODE FOR TEXT FILES.

-- HISTORY:
--     ABW 08/26/82
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     DWC 08/19/87  CHANGED FAILED MESSAGE.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3402D IS

     INCOMPLETE : EXCEPTION;
     FILE : FILE_TYPE;
     ONE : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(1));
     SPAC3 : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(3));
     FOUR : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(4));

BEGIN

     TEST ("CE3402D",  "CHECK THAT NEW_LINE SETS THE CURRENT " &
                       "COLUMN NUMBER TO ONE, AND NEW_LINE OUTPUTS " &
                       "TERMINATORS WHEN THE SPACING IS " &
                       "GREATER THAN ONE");

     BEGIN
          CREATE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; TEXT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     FOR I IN 1..5 LOOP
          PUT (FILE, 'X');
     END LOOP;

     NEW_LINE (FILE, SPAC3);
     IF LINE (FILE) /= FOUR THEN
          FAILED ("NEW_LINE DID NOT OUTPUT LINE TERMINATORS");
     END IF;

     IF COL (FILE) /= ONE THEN
          FAILED ("COLUMN NOT SET TO ONE");
     END IF;
     CLOSE (FILE);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3402D;
