-- CE3410A.ADA

-- OBJECTIVE:
--     CHECK THAT SET_LINE RAISES LAYOUT_ERROR IF THE PAGE LENGTH IS
--     BOUNDED AND THE GIVEN LINE POSITION EXCEEDS THE PAGE LENGTH
--     FOR FILES OF MODE OUT_FILE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF TEMPORARY TEXT FILES WITH OUT_FILE MODE.

-- HISTORY:
--     ABW 08/26/82
--     TBN 11/10/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 08/31/87  CORRECTED EXCEPTION HANDLING.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3410A IS

     INCOMPLETE : EXCEPTION;
     FILE  : FILE_TYPE;
     THREE : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(3));
     FOUR  : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(4));

BEGIN

     TEST ("CE3410A", "CHECK THAT SET_LINE RAISES " &
                      "LAYOUT_ERROR APPROPRIATELY");

     BEGIN
          CREATE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE FOR " &
                               "TEMPORARY FILE WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     SET_PAGE_LENGTH (FILE, THREE);

     BEGIN
          SET_LINE (FILE, FOUR);
          FAILED ("LAYOUT ERROR NOT RAISED FOR SET_LINE");
     EXCEPTION
          WHEN LAYOUT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED FOR SET_LINE");
     END;

     CLOSE (FILE);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3410A;
