-- CE3407B.ADA

-- OBJECTIVE:
--     CHECK THAT END_OF_PAGE CAN ONLY BE APPLIED TO FILES OF MODE
--     IN_FILE, THAT MODE_ERROR IS RAISED FOR FILES OF MODE OUT_FILE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF TEMPORARY TEXT FILES WITH OUT_FILE MODE.

-- HISTORY:
--     ABW 08/26/82
--     SPS 09/22/82
--     TBN 11/10/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 08/28/87  CORRECTED EXCEPTION HANDLING AND ADDED CASE
--                   FOR CURRENT_OUTPUT.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3407B IS

     INCOMPLETE : EXCEPTION;
     FILE : FILE_TYPE;
     BOOL : BOOLEAN;

BEGIN

     TEST ("CE3407B", "CHECK THAT END_OF_PAGE RAISES MODE_ERROR " &
                      "FOR FILES OF MODE OUT_FILE");

     BEGIN
          CREATE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE FOR " &
                               "TEMPORARY FILE WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     BEGIN
          BOOL := END_OF_PAGE (FILE);
          FAILED ("MODE_ERROR NOT RAISED FOR OUT_FILE");
     EXCEPTION
          WHEN MODE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED FOR OUT_FILE");
     END;

     BEGIN
          BOOL := END_OF_PAGE (STANDARD_OUTPUT);
          FAILED ("MODE_ERROR NOT RAISED FOR STANDARD_OUTPUT");
     EXCEPTION
          WHEN MODE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED FOR STANDARD_OUTPUT");
     END;

     BEGIN
          BOOL := END_OF_PAGE (CURRENT_OUTPUT);
          FAILED ("MODE_ERROR NOT RAISED FOR CURRENT_OUTPUT");
     EXCEPTION
          WHEN MODE_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("OTHER EXCEPTION RAISED FOR CURRENT_OUTPUT");
     END;

     CLOSE (FILE);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3407B;
