-- CE3410D.ADA

-- OBJECTIVE:
--     CHECK THAT, FOR FILES OF MODE IN_FILE, SET_LINE READS UNTIL A
--     PAGE IS FOUND HAVING A LINE AT THE SPECIFIED POSITION, SKIPPING
--     LINE AND PAGE TERMINATORS AS NECESSARY.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     TEXT FILES.

-- HISTORY:
--     JBG 01/27/83
--     TBN 11/10/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 09/01/87  REMOVED DEPENDENCE ON RESET AND CHECKED FOR
--                   USE_ERROR ON DELETE.

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;

PROCEDURE CE3410D IS

     INCOMPLETE : EXCEPTION;
     FILE : FILE_TYPE;
     FOUR : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(4));
     ITEM_CHAR : CHARACTER;

BEGIN

     TEST ("CE3410D", "CHECK THAT SET_LINE SKIPS PAGE " &
                      "TERMINATORS WHEN NECESSARY");

     BEGIN
          CREATE (FILE, OUT_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE WITH " &
                               "MODE OUT_FILE");
               RAISE INCOMPLETE;
          WHEN NAME_ERROR =>
               NOT_APPLICABLE ("NAME_ERROR RAISED ON TEXT CREATE " &
                               "WITH MODE OUT_FILE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     FOR I IN 'A'..'C' LOOP
          PUT (FILE, I);
          NEW_LINE (FILE);
     END LOOP;

     NEW_PAGE (FILE);

     FOR I IN 'D'..'H'   -- 5 LINES
     LOOP
          PUT (FILE, I);
          NEW_LINE (FILE);
     END LOOP;

     CLOSE (FILE);

     BEGIN
          OPEN (FILE, IN_FILE, LEGAL_FILE_NAME);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT OPEN WITH " &
                               "IN_FILE MODE");
               RAISE INCOMPLETE;
     END;

     SET_LINE (FILE, FOUR);
     GET (FILE, ITEM_CHAR);

     IF ITEM_CHAR /= 'G' THEN
          FAILED ("SET_LINE DOESN'T SKIP PAGE MARKS; " &
                  "ACTUALLY READ '" & ITEM_CHAR & "'");
     END IF;

     BEGIN
          DELETE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
                    NULL;
     END;

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3410D;
