-- CE3409A.ADA

-- OBJECTIVE:
--     CHECK THAT SET_COL RAISES LAYOUT_ERROR IF THE LINE LENGTH IS
--     BOUNDED AND THE GIVEN COLUMN POSITION EXCEEDS THE LINE LENGTH
--     FOR FILES OF MODE OUT_FILE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF TEMPORARY TEXT FILES WITH OUT_FILE MODE.

-- HISTORY:
--     ABW 08/26/82
--     TBN 11/10/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 08/31/87  CORRECTD EXCEPTION HANDLING AND ADDED NEW CASES
--                   FOR OBJECTIVE.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3409A IS

     INCOMPLETE : EXCEPTION;
     FILE  : FILE_TYPE;
     THREE : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(3));
     FOUR  : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(4));
     FIVE  : POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(5));

BEGIN

     TEST ("CE3409A", "CHECK THAT SET_COL RAISES " &
                      "LAYOUT_ERROR APPROPRIATELY");

     BEGIN
          CREATE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE FOR " &
                               "TEMPORARY FILE WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     SET_LINE_LENGTH (FILE, THREE);

     BEGIN
          SET_COL (FILE, FOUR);
          FAILED ("LAYOUT_ERROR NOT RAISED ON SET_COL - 1");
     EXCEPTION
          WHEN LAYOUT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON SET_COL - 1");
     END;

     IF COL (FILE) /= 1 THEN
          FAILED ("COLUMN LENGTH NOT INITIALLY ONE");
     END IF;

     PUT (FILE, 'A');
     PUT (FILE, 'B');
     PUT (FILE, 'C');

     SET_LINE_LENGTH (FILE, FOUR);

     BEGIN
          SET_COL (FILE, FIVE);
          FAILED ("LAYOUT_ERROR NOT RAISED ON SET_COL - 2");
     EXCEPTION
          WHEN LAYOUT_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON SET_COL - 2");
     END;

     CLOSE (FILE);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END CE3409A;
