-- CE3605A.ADA

-- OBJECTIVE:
--     CHECK THAT PUT FOR CHARACTER AND STRING PARAMETERS DOES NOT
--     UPDATE THE LINE NUMBER WHEN THE LINE LENGTH IS UNBOUNDED,
--     ONLY THE COLUMN NUMBER.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF TEMPORARY TEXT FILES WITH OUT_FILE MODE.

-- HISTORY:
--     SPS 09/02/82
--     JBG 02/22/84  CHANGED TO .ADA TEST
--     RJW 11/04/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 09/08/87  CORRECTED EXCEPTION HANDLING AND ADDED CHECKS
--                   FOR COLUMN NUMBER.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3605A IS
     INCOMPLETE : EXCEPTION;

BEGIN

     TEST ("CE3605A", "CHECK THAT PUT FOR CHARACTER AND STRING " &
                      "PARAMETERS DOES NOT UPDATE THE LINE NUMBER " &
                      "WHEN THE LINE LENGTH IS UNBOUNDED, ONLY THE " &
                      "COLUMN NUMBER");

     DECLARE
          FILE1 : FILE_TYPE;
          LN : POSITIVE_COUNT := 1;
     BEGIN

          BEGIN
               CREATE (FILE1);
          EXCEPTION
               WHEN USE_ERROR =>
                    NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE " &
                                    "FOR TEMPORARY FILES WITH " &
                                    "OUT_FILE MODE");
                    RAISE INCOMPLETE;
          END;

          LN := LINE (FILE1);

          IF LN /= 1 THEN
               FAILED ("CURRENT LINE NUMBER NOT INITIALLY ONE");
          END IF;

          IF COL (FILE1) /= 1 THEN
               FAILED ("CURRENT COLUMN NUMBER NOT INITIALLY ONE");
          END IF;

          FOR I IN 1 .. IDENT_INT(360) LOOP
               PUT(FILE1, 'A');
          END LOOP;
          IF LINE (FILE1) /= LN THEN
               FAILED ("PUT ALTERED LINE NUMBER - CHARACTER");
          END IF;

          IF COL(FILE1) /= 361 THEN
               FAILED ("COLUMN NUMBER NOT UPDATED CORRECTLY - 1");
          END IF;

          NEW_LINE(FILE1);
          LN := LINE (FILE1);

          FOR I IN 1 .. IDENT_INT(86) LOOP
               PUT (FILE1, "STRING");
          END LOOP;
          IF LN /= LINE (FILE1) THEN
               FAILED ("PUT ALTERED LINE NUMBER - STRING");
          END IF;

          IF COL(FILE1) /= 517 THEN
               FAILED ("COLUMN NUMBER NOT UPDATED CORRECTLY - 2");
          END IF;

          CLOSE (FILE1);

     EXCEPTION
          WHEN INCOMPLETE =>
               NULL;

     END;

     RESULT;

END CE3605A;
