-- CE3701A.ADA

-- OBJECTIVE:
--     CHECK THAT GET AND PUT OF INTEGER_IO RAISE STATUS_ERROR IF
--     THE FILE IS NOT OPEN.

-- HISTORY:
--     ABW 08/27/82
--     JBG 08/30/83
--     DWC 09/09/87  REMOVED UNNECESSARY CODE, CORRECTED EXCEPTION
--                   HANDLING, AND ATTEMPTED TO CREATE A FILE.

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;

PROCEDURE CE3701A IS

     PACKAGE INT_IO IS NEW INTEGER_IO (INTEGER);
     USE INT_IO;
     FILE : FILE_TYPE;
     INT_ITEM : INTEGER := 7;

BEGIN

     TEST ("CE3701A", "CHECK THAT GET AND PUT RAISE " &
                       "STATUS_ERROR IF THE FILE " &
                       "IS NOT OPEN");

     BEGIN
          PUT (FILE, IDENT_INT(8));
          FAILED ("STATUS_ERROR NOT RAISED WHEN PUT APPLIED " &
                  "TO A NON-EXISTENT FILE");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED WHEN PUT " &
                       "APPLIED TO A NON-EXISTENT FILE");
     END;

     BEGIN
          GET (FILE, INT_ITEM);
          FAILED ("STATUS_ERROR NOT RAISED WHEN GET APPLIED " &
                  "TO A NON-EXISTENT FILE");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED WHEN GET " &
                       "APPLIED TO A NON-EXISTENT FILE");
     END;

     BEGIN
          CREATE (FILE);     -- THIS IS JUST AN ATTEMPT TO CREATE
          CLOSE (FILE);      -- A FILE.  WHETHER THIS IS SUCCESSFUL
     EXCEPTION               -- OR NOT HAS NO EFFECT ON TEST
          WHEN USE_ERROR =>  -- OBJECTIVE.
               NULL;
     END;

     BEGIN
          PUT (FILE, IDENT_INT(8));
          FAILED ("STATUS_ERROR NOT RAISED WHEN PUT APPLIED " &
                  "TO AN UNOPENED FILE");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED WHEN PUT " &
                       "APPLIED TO AN UNOPENED FILE");
     END;

     BEGIN
          GET (FILE, INT_ITEM);
          FAILED ("STATUS_ERROR NOT RAISED WHEN GET APPLIED " &
                  "TO AN UNOPENED FILE");
     EXCEPTION
          WHEN STATUS_ERROR =>
               NULL;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED WHEN GET " &
                       "APPLIED TO AN UNOPENED FILE");
     END;

     RESULT;

END CE3701A;
