-- CE3814A.ADA

-- OBJECTIVE:
--     CHECK THAT FIXED POINT SAFE NUMBERS ARE OUTPUT EXACTLY IF AFT
--     IS SUFFICIENTLY LARGE AND THAT NUMBERS LYING BETWEEN MODEL
--     NUMBERS ARE CORRECTLY ROUNDED ON OUTPUT.

-- HISTORY:
--     JET 10/28/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH TEXT_IO; USE TEXT_IO;
PROCEDURE CE3814A IS

     TYPE FIX IS DELTA 2#0.0001# RANGE -16#100.0# .. 16#100.0#;

     PACKAGE FIO IS NEW FIXED_IO(FIX);
     USE FIO;

     FX, X, Y, Z : FIX;
     STRX, STRY, STRZ : STRING(1..20) := (OTHERS => ' ');
     LAST : POSITIVE;

     F : FILE_TYPE;
     OK : BOOLEAN := FALSE;

BEGIN
     TEST ("CE3814A", "CHECK THAT FIXED POINT SAFE NUMBERS ARE " &
                      "OUTPUT EXACTLY IF AFT IS SUFFICIENTLY LARGE " &
                      "AND THAT NUMBERS LYING BETWEEN MODEL NUMBERS " &
                      "ARE CORRECTLY ROUNDED ON OUTPUT");

     X := 16#0.1#;
     Y := 16#FF.F#;
     Z := -16#55.51# + FIX(IDENT_INT(0));

     PUT(STRX, X, AFT => 4);
     IF STRX(14..20) /= IDENT_STR(" 0.0625") THEN
          FAILED("RESULT FROM STRING PUT IS NOT EXACT (X)");
     END IF;

     PUT(STRY, Y, AFT => 6);
     IF STRY(11..20) /= IDENT_STR("255.937500") THEN
          FAILED("RESULT FROM STRING PUT IS NOT EXACT (Y)");
     END IF;

     PUT(STRZ, Z, AFT => 10);
     IF STRZ /= IDENT_STR("      -85.3750000000") AND
        STRZ /= IDENT_STR("      -85.3125000000") THEN
          FAILED("RESULT FROM STRING PUT IS NOT CORRECT (Z)");
     END IF;

     BEGIN
          CREATE(F, OUT_FILE, LEGAL_FILE_NAME);
          OK := TRUE;
     EXCEPTION
          WHEN USE_ERROR | NAME_ERROR =>
               COMMENT("UNABLE TO CREATE DATA FILE FOR FILE CHECKS");
     END;

     IF OK THEN
          PUT(F, X, AFT => 59); NEW_LINE(F);
          PUT(F, Y, AFT => 30); NEW_LINE(F);
          PUT(F, Z, AFT => 21); NEW_LINE(F);
          CLOSE(F);
          OPEN(F, IN_FILE, LEGAL_FILE_NAME);

          GET(F, FX);
          IF FX /= X THEN
               FAILED("RESULT FROM FILE PUT IS NOT EXACT (X)");
          END IF;

          GET(F, FX);
          IF FX /= Y THEN
               FAILED("RESULT FROM FILE PUT IS NOT EXACT (Y)");
          END IF;

          GET(F, FX);
          IF FX < -16#55.6# OR FX > -16#55.5# THEN
               FAILED("RESULT FROM FILE PUT IS NOT CORRECT (Z)");
          END IF;

          BEGIN
               DELETE(F);
          EXCEPTION
               WHEN USE_ERROR =>
                    COMMENT ("DATA FILE COULD NOT BE DELETED");
          END;
     END IF;

     RESULT;
END CE3814A;
