-- CE3907A.ADA

-- CHECK THAT PUT FOR ENUMERATION TYPES CAN BE APPLIED TO A STRING.
-- CHECK THAT IT RAISES LAYOUT_ERROR WHEN THE ENUMERATION LITERAL TO BE
-- PLACED IN THE STRING IS LONGER THAN THE STRING.

-- SPS 10/11/82
-- JBG 2/22/84  CHANGED TO .ADA TEST 

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE CE3907A IS
BEGIN

     TEST ("CE3907A", "CHECK THAT ENUMERATION_IO PUT OPERATES ON " &
                      "STRINGS CORRECTLY");

     DECLARE
          TYPE COLOR IS (RED, BLUE, GREEN);
          ST : STRING (1..4);
          PACKAGE COLOR_IO IS NEW ENUMERATION_IO (COLOR);
          USE COLOR_IO;
          CRAYON : COLOR := GREEN;
     BEGIN
          PUT (ST, RED);
          IF ST /= "RED " THEN
               FAILED ("PUT TO STRING, LENGTH LESS THAN STRING " &
                       "INCORRECT");
          END IF;

          PUT (ST, BLUE);
          IF ST /= "BLUE" THEN
               FAILED ("PUT TO STRING, LENGTH EQUAL TO STRING " &
                       "INCORRECT");
          END IF;

          BEGIN
               PUT (ST, CRAYON);
               FAILED ("LAYOUT_ERROR NOT RAISED");
          EXCEPTION
               WHEN LAYOUT_ERROR =>
                    NULL;
               WHEN OTHERS =>
                    FAILED ("WRONG EXCEPTION RAISED");
          END;

     END;

     RESULT;
END CE3907A;
