-- D55A03E.ADA

 
-- CHECK THAT AN ARBITRARY LEVEL OF LOOP NESTING IS PERMITTED.

-- CHECK 31 LEVELS OF LOOP NESTING.
 
-- ASL 8/06/81
--  RM 6/28/82
--  RM 7/06/82
-- SPS 3/2/83

WITH REPORT;
PROCEDURE D55A03E IS
 
     USE REPORT;
 
     X : INTEGER := 1;
 
     COUNT : INTEGER := 0;
 
     DESCENDING  :  BOOLEAN  :=  IDENT_BOOL( TRUE );
 
BEGIN

     TEST ("D55A03E","31 LEVELS OF LOOP NESTING");
 
     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP
     WHILE  DESCENDING  LOOP
     LOOP
     EXIT WHEN  NOT DESCENDING ;

     FOR I IN X..IDENT_INT(1) LOOP

          COUNT := COUNT + 1;
          DESCENDING  :=  IDENT_BOOL( FALSE );

     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
     END LOOP;
 
     IF COUNT /= 1 THEN
          FAILED ("LOOPS NOT EXECUTED PROPER NUMBER OF TIMES");
     END IF;
 
     RESULT;

END D55A03E;
