PRAGMA MEMORY_SIZE (0, 1);
PRAGMA MEMORY_SIZE;
PRAGMA STORAGE_UNIT (8, 1);
PRAGMA STORAGE_UNIT;
PRAGMA SYSTEM_NAME (WHO, WHAT);
PRAGMA SYSTEM_NAME;

-- E28002D.ADA

-- OBJECTIVE:
--     CHECK THAT A PREDEFINED PRAGMA MAY HAVE AN ARBITRARY NUMBER OF
--     ARGUMENTS.

--     THESE PRAGMAS ARE IMPROPER, BUT LEGAL STATEMENTS THAT MUST BE
--     IGNORED BY THE COMPILER.

-- PASS/FAIL CRITERIA:
--     1) THE TEST MUST EXECUTE AND REPORT "TENTATIVELY PASSED";
--     2) THE TW0 COMMENTS CONTAINING "*** MUST APPEAR ***" MUST APPEAR
--        IN THE LISTING;
--     3) THE TWO COMMENTS CONTAINING "*** SAME PAGE ***" MUST APPEAR ON
--        THE SAME PAGE.

-- HISTORY:
--     TBN 02/24/86  CREATED ORIGINAL TEST.
--     JET 01/13/88  ADDED CALLS TO SPECIAL_ACTION AND UPDATED HEADER.

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
PRAGMA ELABORATE;

PROCEDURE E28002D IS

     PRAGMA OPTIMIZE (TIME, SPACE);
     PRAGMA OPTIMIZE;
     PRAGMA PRIORITY (PRIORITY'LAST, PRIORITY'FIRST);
     PRAGMA PRIORITY;

     TYPE REC1 IS
          RECORD
               NULL;
          END RECORD;
     TYPE ACCESS_REC1 IS ACCESS REC1;
     TYPE ACCESS_REC2 IS ACCESS REC1;

     PRAGMA CONTROLLED (ACCESS_REC1, ACCESS_REC2);
     PRAGMA CONTROLLED;

     ONE, TWO : INTEGER := 1;

     PRAGMA SHARED (ONE, TWO);
     PRAGMA SHARED;

     PROCEDURE FUN IS
     BEGIN
          NULL;
     END;

     PRAGMA INTERFACE (FORTRAN, FUN, FUN);
     PRAGMA INTERFACE (FORTRAN);
     PRAGMA INTERFACE;
     PRAGMA INLINE;
     PRAGMA PACK (REC1, REC1);
     PRAGMA PACK;
     PRAGMA SUPPRESS (RANGE_CHECK, ONE, TWO);
     PRAGMA SUPPRESS;

BEGIN
     TEST ("E28002D", "CHECK THAT A PREDEFINED PRAGMA MAY HAVE AN " &
                      "ARBITRARY NUMBER OF ARGUMENTS");

     PRAGMA LIST (OFF, ON);
-- THIS COMMENT *** MUST APPEAR ***.
     PRAGMA LIST;
-- THIS COMMENT *** MUST APPEAR ***.
     PRAGMA LIST (ON);
     PRAGMA PAGE;
-- THIS COMMENT MUST BE ON THE *** SAME PAGE *** AS THE NEXT COMMENT.
     PRAGMA PAGE (1);
-- THIS COMMENT MUST BE ON THE *** SAME PAGE *** AS THE PRECEDING
-- COMMENT.

     SPECIAL_ACTION ("CHECK THAT THE TWO ""*** MUST APPEAR ***"" " &
                     "COMMENTS APPEAR IN THE COMPILATION LISTING");

     SPECIAL_ACTION ("CHECK THAT THE TWO ""*** SAME PAGE ***"" " &
                     "COMMENTS APPEAR ON THE SAME PAGE OF THE " &
                     "COMPILATION LISTING");

     RESULT;

END E28002D;
