PRAGMA PAGE;
-- E28005D.ADA

-- OBJECTIVE:
--     CHECK THAT WHEN PRAGMA PAGE IS USED AT THE BEGINNING OR END OF A
--     COMPILATION, THERE IS NO PROBLEM.

-- PASS/FAIL CRITERIA:
--     THE TEST MUST COMPILE TO EXECUTE WITH A 'TENTATIVELY PASSED'
--     RESULT.  THERE IS A PAGE BREAK BEFORE THE TEST NAME AND A
--     PAGE BREAK AFTER THE END OF THE TEST.

-- HISTORY:
--     RJW 04/16/86  CREATED ORIGINAL TEST.
--     JET 01/13/88  ADDED CALLS TO SPECIAL_ACTION AND UPDATED HEADER.

WITH REPORT; USE REPORT;

PROCEDURE E28005D IS
BEGIN
     TEST ( "E28005D", "CHECK THAT WHEN PRAGMA PAGE IS USED AT THE " &
                       "BEGINNING OR END OF A COMPILATION, THERE " &
                       "IS NO PROBLEM");

     SPECIAL_ACTION ("CHECK THAT THE PAGE PRAGMAS AT THE BEGINNING " &
                     "AND END OF THE PROGRAM CAUSE THE TEXT " &
                     "FOLLOWING THE PRAGMAS TO APPEAR AT THE START " &
                     "OF A NEW PAGE OF THE COMPILATION LISTING");
     RESULT;

END E28005D;

PRAGMA PAGE;
