PRAGMA SYSTEM_NAME (NOBODY);
PRAGMA MEMORY_SIZE (ONE);
PRAGMA STORAGE_UNIT (TWO);

-- E28002A.ADA

-- OBJECTIVE:
--     CHECK THAT A PREDEFINED OR AN UNRECOGNIZED PRAGMA MAY HAVE
--     ARGUMENTS INVOLVING IDENTIFIERS THAT ARE NOT VISIBLE.

--     THESE PRAGMAS ARE IMPROPER, BUT THEY ARE LEGAL STATEMENTS
--     THAT MUST BE IGNORED BY THE COMPILER.

-- PASS/FAIL CRITERIA:
--     1) THE TEST MUST EXECUTE AND REPORT "TENTATIVELY PASSED";
--     2) THE COMMENT CONTAINING "*** MUST APPEAR ***" MUST APPEAR IN
--        THE COMPILATION LISTING;
--     3) THE TWO COMMENTS CONTAINING "*** SAME PAGE ***" MUST APPEAR ON
--        THE SAME PAGE.

-- HISTORY:
--     TBN 02/21/86  CREATED ORIGINAL TEST.
--     JET 01/13/88  ADDED CALLS TO SPEC_ACT AND UPDATED HEADER FORMAT.
--     DHH 03/02/89  ADDED PRAGMA PAGE BEFORE PRAGMA PAGE(ONE).

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (ZZZZZZZ_ZZZ);

PROCEDURE E28002A IS

     PRAGMA OPTIMIZE (WHAT);
     PRAGMA PRIORITY (ONE);
     PRAGMA CONTROLLED (OPTIMIZE);
     PRAGMA SHARED (GLOBAL_MONEY);
     PRAGMA INTERFACE (FORTRAN, FUN);
     PRAGMA INLINE (XYZ);
     PRAGMA PACK (CHAR_TYPE);
     PRAGMA SUPPRESS (MONEY, INTEGER);
     PRAGMA PHIL_BRASHEAR (ONE);
     MY_INT : INTEGER;

BEGIN
     TEST ("E28002A", "CHECK THAT A PREDEFINED OR AN UNRECOGNIZED " &
                      "PRAGMA MAY HAVE ARGUMENTS INVOLVING " &
                      "IDENTIFIERS THAT ARE NOT VISIBLE");

     PRAGMA LIST (NEXT);
-- THIS COMMENT *** MUST APPEAR ***.
     SPECIAL_ACTION ("CHECK LISTING FOR COMMENT ""*** MUST APPEAR " &
                     "***""");
     PRAGMA ROSA_WILLIAMS (TW0);
     PRAGMA THOMAS_NORRIS (THREE);
     PRAGMA PAGE;
     PRAGMA PAGE (ONE);
-- THIS COMMENT MUST BE ON THE *** SAME PAGE *** AS THE NEXT COMMENT.
     PRAGMA PAGE (FOUR);
-- THIS COMMENT MUST BE ON THE *** SAME PAGE *** AS THE PRECEDING
-- COMMENT.
     SPECIAL_ACTION ("CHECK THAT COMMENTS ""*** SAME PAGE ***"" " &
                     "ARE ON THE SAME PAGE OF THE LISTING");
     RESULT;

END E28002A;
