-- E28002B.ADA

-- OBJECTIVE:
--     CHECK THAT A PREDEFINED OR AN UNRECOGNIZED PRAGMA MAY HAVE
--     ARGUMENTS INVOLVING OVERLOADED IDENTIFIERS WITHOUT ENOUGH
--     CONTEXTUAL INFORMATION TO RESOLVE THE OVERLOADING.

-- PASS/FAIL CRITERIA:
--     THIS TEST IS PASSED IF IT REPORTS "TENTATIVELY PASSED" AND
--     THE STARRED COMMENT DOES NOT APPEAR IN THE LISTING.

--     AN IMPLEMENTATION FAILS THIS TEST IF THE STARRED COMMENT
--     LINE APPEARS IN THE COMPILATION LISTING.

-- HISTORY:
--     TBN 02/24/86  CREATED ORIGINAL TEST.
--     JET 01/13/88  ADDED CALLS TO SPECIAL_ACTION AND UPDATED HEADER.

WITH REPORT, SYSTEM; USE REPORT, SYSTEM;
PROCEDURE E28002B IS

     FUNCTION OFF RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END OFF;

     FUNCTION OFF RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END OFF;

     PRAGMA LIST (OFF);
--***** THIS LINE MUST NOT APPEAR IN COMPILATION LISTING.
     PRAGMA LIST (ON);

     FUNCTION ELABORATION_CHECK RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END ELABORATION_CHECK;

     FUNCTION ELABORATION_CHECK RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END ELABORATION_CHECK;

     PRAGMA SUPPRESS (ELABORATION_CHECK, ELABORATION_CHECK);

     FUNCTION TIME RETURN INTEGER IS
     BEGIN
          RETURN 1;
     END TIME;

     FUNCTION TIME RETURN BOOLEAN IS
     BEGIN
          RETURN TRUE;
     END TIME;

     PRAGMA OPTIMIZE (TIME);

     PROCEDURE XYZ IS
     BEGIN
          NULL;
     END XYZ;

     PROCEDURE XYZ (COUNT : INTEGER) IS
     BEGIN
          NULL;
     END XYZ;

     PRAGMA INLINE (XYZ);
     PRAGMA PHIL_BRASHEAR (XYZ);

BEGIN
     TEST ("E28002B", "CHECK THAT A PREDEFINED OR AN UNRECOGNIZED " &
                      "PRAGMA MAY HAVE ARGUMENTS INVOLVING " &
                      "OVERLOADED IDENTIFIERS WITHOUT ENOUGH " &
                      "CONTEXTUAL INFORMATION TO RESOLVE THE " &
                      "OVERLOADING");

     SPECIAL_ACTION ("CHECK THAT THE COMPILATION LISTING DOES NOT " &
                     "SHOW THE STARRED COMMENT LINE");

     RESULT;

END E28002B;
