-- EA1003B.ADA

-- CHECK WHETHER MORE THAN ONE COMPLETELY INDEPENDENT COMPILATION
-- UNIT CAN BE SUBMITTED IN A SINGLE FILE AND WHETHER ERRORS IN
-- ONE INDEPENDENT UNIT AFFECT LATER INDEPENDENT UNITS IN THE FILE.

-- AN IMPLEMENTATION IS ALLOWED BY AI-00255 TO REJECT LEGAL COMPILATION
-- UNITS IN THIS COMPILATION FILE IN ADDITION TO THE ILLEGAL ONE,
-- EA1003B_PKG, IN WHICH CASE THE TEST SHOULD NOT BE LINKABLE.

-- JRK 5/12/81
-- JRK 11/21/85  RENAMED FROM CA1003B-AB.ADA; REVISED ACCORDING TO
--               AI-00255.


PROCEDURE EA1003B_P (I : IN OUT INTEGER) IS
BEGIN
     I := I + 1;
END EA1003B_P;


PACKAGE EA1003B_PKG IS
     I : T;     -- ERROR: UNDEFINED TYPE NAME.
END EA1003B_PKG;


FUNCTION EA1003B_F (I : INTEGER) RETURN INTEGER IS
BEGIN
     RETURN -I;
END EA1003B_F;


WITH REPORT, EA1003B_P, EA1003B_F;
USE REPORT;

PROCEDURE EA1003B IS

     I : INTEGER := IDENT_INT (0);

BEGIN
     TEST ("EA1003B", "INDEPENDENT UNITS IN A SINGLE FILE " &
           "ARE NOT AFFECTED BY ERRORS IN OTHER UNITS");

     EA1003B_P (I);
     IF I /= 1 THEN
          FAILED ("INDEPENDENT PROCEDURE NOT INVOKED");
     END IF;

     IF EA1003B_F (IDENT_INT(5)) /= -5 THEN
          FAILED ("INDEPENDENT FUNCTION NOT INVOKED");
     END IF;

     RESULT;
END EA1003B;
