-- EA3003C1.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILATION OF A PACKAGE SPECIFICATION WHICH
--     HAS BEEN CHANGED ONLY WITH RESPECT TO ITS COMMENTS OR FORMATTING
--     REQUIRES RECOMPILATION OF ALL SUBORDINATE UNITS.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH EA3003C_PACK; USE EA3003C_PACK;
PRAGMA ELABORATE (REPORT);
PROCEDURE EA3003C_PROC IS
BEGIN
     I := IDENT_INT(I) + 1;
END EA3003C_PROC;
