-- EA3003A2.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILATION OF A SUBUNIT PARENT WHICH HAS BEEN
--     CHANGED ONLY WITH RESPECT TO ITS COMMENTS OR FORMATTING
--     REQUIRES RECOMPILATION OF ALL SUBORDINATE UNITS.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

-- THE FOLLOWING UNIT IS SPACED DIFFERENTLY
-- FROM THE ONE IN EA3003A0.ADA.

WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PROCEDURE EA3003A_PROC(I : IN OUT INTEGER) IS

     PROCEDURE EA3003A_SUBPROC IS SEPARATE;

BEGIN

     EA3003A_SUBPROC;

END EA3003A_PROC;
