-- EA3003B2.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILING A PACKAGE SPECIFICATION TO WHICH
--     DECLARATIONS HAVE BEEN ADDED AT THE END CAUSES THE RECOMPILATION
--     OF SUBORDINATE UNITS TO BE REQUIRED.

-- HISTORY:
--     JET 08/17/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE EA3003B_PACK IS
     SUBTYPE T IS INTEGER RANGE -100..100;
     I : INTEGER := IDENT_INT(1);
     J : T := 1;
END EA3003B_PACK;
