-- EA3003B1.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILING A PACKAGE SPECIFICATION TO WHICH
--     DECLARATIONS HAVE BEEN ADDED AT THE END CAUSES THE RECOMPILATION
--     OF SUBORDINATE UNITS TO BE REQUIRED.

-- HISTORY:
--     JET 08/17/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH EA3003B_PACK;
PRAGMA ELABORATE (REPORT);
PACKAGE EA3003B_PACK2 IS
     K : INTEGER := IDENT_INT(-1000);
END EA3003B_PACK2;

PACKAGE BODY EA3003B_PACK2 IS
BEGIN
     IF IDENT_INT(EA3003B_PACK.I) /= 1 THEN
          FAILED("INCORRECT VALUE OF PACKAGE VARIABLE I");
     END IF;
END EA3003B_PACK2;
