-- EA3003A3M.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILATION OF A SUBUNIT PARENT WHICH HAS BEEN
--     CHANGED ONLY WITH RESPECT TO ITS COMMENTS OR FORMATTING
--     REQUIRES RECOMPILATION OF ALL SUBORDINATE UNITS.

-- PASS/FAIL CRITERIA:
--     THIS TEST PASSES IF IT COMPILES, LINKS, AND REPORTS "PASSED." IN
--     THIS CASE, RECOMPILATION OF SUBORDINATE UNITS IS NOT REQUIRED
--     AFTER FORMATTING CHANGES.  ALTERNATIVELY, THIS TEST PASSES IF IT
--     COMPILES SUCCESSFULLY BUT LINKING IS UNSUCCESSFUL DUE TO
--     AN OBSOLETE SUBORDINATE UNIT.  IN THIS CASE RECOMPILATION IS
--     REQUIRED BY THE IMPLEMENTATION.

-- SEPARATE FILES ARE:
--     EA3003A0.ADA  - ORIGINAL PARENT PROCEDURE.
--     EA3003A1.ADA  - SUBORDINATE UNIT FOR THE ABOVE PARENT.
--     EA3003A2.ADA  - REPLACEMENT PARENT PROCEDURE.
--     EA3003A3M.ADA - MAIN PROCEDURE.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH EA3003A_PROC;
PROCEDURE EA3003A3M IS

     I : INTEGER := 0;

BEGIN
     TEST ("EA3003A", "CHECK WHETHER RECOMPILATION OF A SUBUNIT " &
                      "PARENT WHICH HAS BEEN CHANGED ONLY WITH R" &
                      "ESPECT TO ITS COMMENTS OR FORMATTING REQU" &
                      "IRES RECOMPILATION OF ALL SUBORDINATE UNITS");

     EA3003A_PROC(I);

     IF I /= 1 THEN
          FAILED("INCORRECT RETURN VALUE FROM PROCEDURE");
     END IF;

     RESULT;

END EA3003A3M;
