-- EA3003A1.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILATION OF A SUBUNIT PARENT WHICH HAS BEEN
--     CHANGED ONLY WITH RESPECT TO ITS COMMENTS OR FORMATTING
--     REQUIRES RECOMPILATION OF ALL SUBORDINATE UNITS.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

SEPARATE(EA3003A_PROC)
PROCEDURE EA3003A_SUBPROC IS
BEGIN
     I := IDENT_INT(I) + 1;
END EA3003A_SUBPROC;
