-- EA3003C0.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILATION OF A PACKAGE SPECIFICATION WHICH
--     HAS BEEN CHANGED ONLY WITH RESPECT TO ITS COMMENTS OR FORMATTING
--     REQUIRES RECOMPILATION OF ALL SUBORDINATE UNITS.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

PACKAGE EA3003C_PACK IS
     SUBTYPE T IS INTEGER RANGE -100..100;
     I : T := 0;
END EA3003C_PACK;
