-- EA3003C3M.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILATION OF A PACKAGE SPECIFICATION WHICH
--     HAS BEEN CHANGED ONLY WITH RESPECT TO ITS COMMENTS OR FORMATTING
--     REQUIRES RECOMPILATION OF ALL SUBORDINATE UNITS.

-- PASS/FAIL CRITERIA:
--     THIS TEST PASSES IF IT COMPILES, LINKS, AND REPORTS "PASSED." IN
--     THIS CASE, RECOMPILATION OF SUBORDINATE UNITS IS NOT REQUIRED
--     AFTER FORMATTING CHANGES.  ALTERNATIVELY, THIS TEST PASSES IF
--     IT CAUSES A COMPILE TIME ERROR WHEN THE PROCEDURE EA3003C_PROC
--     IS MENTIONED IN THE WITH CLAUSE BELOW.  IN THIS CASE
--     RECOMPILATION IS REQUIRED BY THE IMPLEMENTATION.

-- SEPARATE FILES ARE:
--     EA3003C0.ADA  - ORIGINAL PACKAGE SPECIFICATION.
--     EA3003C1.ADA  - SUBORDINATE UNIT FOR THE ABOVE.
--     EA3003C2.ADA  - REPLACEMENT PACKAGE SPECIFICATION.
--     EA3003C3M.ADA - MAIN PROCEDURE.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH EA3003C_PACK;
WITH EA3003C_PROC;                    -- PASSED => ERROR.
PROCEDURE EA3003C3M IS

     I : EA3003C_PACK.T := 0;

BEGIN
     TEST ("EA3003C", "CHECK WHETHER RECOMPILATION OF A PACKAGE SP" &
                      "ECIFICATION WHICH HAS BEEN CHANGED ONLY WIT" &
                      "H RESPECT TO ITS COMMENTS OR FORMATTING REQ" &
                      "UIRES RECOMPILATION OF ALL SUBORDINATE UNITS");

     EA3003C_PROC;

     IF EA3003C_PACK.I /= 1 THEN
          FAILED("INCORRECT VALUE OF PACKAGE VARIABLE");
     END IF;

     RESULT;

END EA3003C3M;
