-- EA3003B3M.ADA

-- OBJECTIVE:
--     CHECK WHETHER RECOMPILING A PACKAGE SPECIFICATION TO WHICH
--     DECLARATIONS HAVE BEEN ADDED AT THE END CAUSES THE RECOMPILATION
--     OF SUBORDINATE UNITS TO BE REQUIRED.

-- PASS/FAIL CRITERIA:
--     THIS TEST PASSES IF IT COMPILES, LINKS, AND REPORTS "PASSED." IN
--     THIS CASE, RECOMPILATION OF SUBORDINATE UNITS IS NOT REQUIRED
--     AFTER FORMATTING CHANGES.  ALTERNATIVELY, THIS TEST PASSES IF THE
--     WITH CLAUSE FOR EA3003B_PACK2 IS NOT ACCEPTED DUE TO THE UNIT
--     BEING OBSOLETE.  IN THIS CASE RECOMPILATION IS REQUIRED BY THE
--     IMPLEMENTATION.

-- SEPARATE FILES ARE:
--     EA3003B0.ADA  - ORIGINAL PACKAGE SPECIFICATION.
--     EA3003B1.ADA  - ANOTHER PACKAGE SPECIFICATION AND BODY.
--     EA3003B2.ADA  - REPLACEMENT FOR FIRST PACKAGE SPECIFICATION.
--     EA3003B3M.ADA - MAIN PROCEDURE.

-- HISTORY:
--     JET 08/17/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH EA3003B_PACK;
WITH EA3003B_PACK2;                    -- PASSED => ERROR.
PROCEDURE EA3003B3M IS
BEGIN
     TEST ("EA3003B", "CHECK WHETHER RECOMPILING A PACKAGE SPECIFI" &
                      "CATION TO WHICH DECLARATIONS HAVE BEEN ADDED " &
                      "AT THE END CAUSES THE RECOMPILATION OF " &
                      "SUBORDINATE UNITS TO BE REQUIRED");

     IF EA3003B_PACK.J /= 1 THEN
          FAILED("INCORRECT VALUE OF PACKAGE VARIABLE J");
     END IF;

     IF IDENT_INT(EA3003B_PACK2.K) /= -1000 THEN
          FAILED("INCORRECT VALUE OF PACKAGE VARIABLE K");
     END IF;

     RESULT;

END EA3003B3M;
