-- EA3004D6M.ADA

-- CHECK THAT, IF THE BODY OF AN INLINE FUNCTION IS MODIFIED,
-- ALL UNITS CALLING THAT FUNCTION AS AN INLINE FUNCTION
-- MUST BE RECOMPILED.

-- SEPARATE FILES ARE:
--   EA3004D0  A LIBRARY FUNCTION DECLARATION (EA3004D0).
--   EA3004D1  A LIBRARY FUNCTION BODY (EA3004D0).
--   EA3004D2  A LIBRARY PROCEDURE.
--   EA3004D3  A LIBRARY FUNCTION.
--   EA3004D4  A LIBRARY PACKAGE DECLARATION.
--   EA3004D5  A LIBRARY FUNCTION BODY (EA3004D0).
--   EA3004D6M THE MAIN PROCEDURE.

-- IF THE INLINE PRAGMA IS SUPPORTED FOR FUNCTIONS, THEN EXPECT TO GET
--   COMPILE-TIME ERROR MESSAGES WHERE INDICATED IN THIS FILE.
-- OTHERWISE, THIS TEST SHOULD EXECUTE AND GIVE A NOT-APPLICABLE RESULT.

-- WKB 07/13/81
-- EG  06/05/84
-- JRK 5/21/85

WITH REPORT; USE REPORT;
WITH EA3004D2;           -- ERROR: OBSOLETE OR MISSING.
WITH EA3004D3;           -- ERROR: OBSOLETE OR MISSING.
WITH EA3004D4;           -- ERROR: OBSOLETE OR MISSING.

PROCEDURE EA3004D6M IS

     TEMP_I : INTEGER;

BEGIN
     TEST ("EA3004D", "MODIFYING THE BODY OF AN INLINE FUNCTION " &
                      "REQUIRES RECOMPILATION OF CALLING UNITS");

     EA3004D2 (TEMP_I);
     CASE TEMP_I IS
          WHEN 3 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PROCEDURE " &
                       "NOT RECOMPILED");
          WHEN 7 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PROCEDURE");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PROCEDURE");
     END CASE;

     CASE EA3004D3 IS
          WHEN 4 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING FUNCTION " &
                       "NOT RECOMPILED");
          WHEN 8 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM FUNCTION");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY FUNCTION");
     END CASE;

     CASE EA3004D4.I IS
          WHEN 5 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PACKAGE " &
                       "DECLARATION NOT RECOMPILED");
          WHEN 9 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PACKAGE DECLARATION");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PACKAGE");
     END CASE;

     RESULT;
END EA3004D6M;
