-- EA3004C5M.ADA

-- CHECK THAT, IF THE BODY OF AN INLINE PROCEDURE IS MODIFIED,
-- ALL UNITS CALLING THAT PROCEDURE AS AN INLINE PROCEDURE
-- MUST BE RECOMPILED.

-- SEPARATE FILES ARE:
--   EA3004C0  A LIBRARY PACKAGE DECLARATION (EA3004C0).
--   EA3004C1  A LIBRARY PACKAGE BODY (EA3004C0).
--   EA3004C2  A LIBRARY PROCEDURE.
--   EA3004C3  A LIBRARY FUNCTION.
--   EA3004C4  A LIBRARY PACKAGE BODY (EA3004C0).
--   EA3004C5M THE MAIN PROCEDURE.

-- IF THE INLINE PRAGMA IS SUPPORTED FOR PROCEDURES, THEN EXPECT TO GET
--   COMPILE-TIME ERROR MESSAGES WHERE INDICATED IN THIS FILE.
-- OTHERWISE, THIS TEST SHOULD EXECUTE AND GIVE A NOT-APPLICABLE RESULT.

-- WKB 07/13/81
-- EG  06/05/84
-- JRK 5/21/85

WITH REPORT; USE REPORT;
WITH EA3004C2;           -- ERROR: OBSOLETE OR MISSING.
WITH EA3004C3;           -- ERROR: OBSOLETE OR MISSING.

PROCEDURE EA3004C5M IS

     TEMP_I : INTEGER;

BEGIN
     TEST ("EA3004C", "MODIFYING THE BODY OF AN INLINE " &
                      "PROCEDURE REQUIRES RECOMPILATION OF " &
                      "CALLING UNITS");

     EA3004C2 (TEMP_I);
     CASE TEMP_I IS
          WHEN 3 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PROCEDURE " &
                       "NOT RECOMPILED");
          WHEN 7 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PROCEDURE");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PROCEDURE");
     END CASE;

     CASE EA3004C3 IS
          WHEN 4 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING FUNCTION " &
                       "NOT RECOMPILED");
          WHEN 8 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM FUNCTION");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY FUNCTION");
     END CASE;

     RESULT;
END EA3004C5M;
