-- EB4012A.ADA

-- OBJECTIVE:
--     CHECK THAT WHEN AN UNHANDLED EXCEPTION IS RAISED IN THE MAIN
--     PROGRAM, THE MAIN PROGRAM IS ABANDONED.

-- PASS/FAIL CRITERIA:
--     THIS TEST MUST EXECUTE AND PRINT "TENTATIVELY PASSED". IN
--     ADDITION, THE OUTPUT/LOG FILE MUST SHOW THAT THE PROGRAM
--     WAS ABANDONED DUE TO AN UNHANDLED EXCEPTION.

-- HISTORY:
--     DHH 03/29/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE EB4012A IS

BEGIN
     TEST("EB4012A", "CHECK THAT WHEN AN UNHANDLED EXCEPTION IS " &
                     "RAISED IN THE MAIN PROGRAM, THE MAIN PROGRAM " &
                     "IS ABANDONED");
     SPECIAL_ACTION("CHECK THE OUTPUT/LOG FILE TO SEE THAT THIS " &
                    "PROGRAM WAS ABANDONED BECAUSE OF AN UNHANDLED " &
                    "EXCEPTION");

     RESULT;

     IF EQUAL(3,3) THEN
          RAISE CONSTRAINT_ERROR;
     END IF;

     TEST("EB4012A", "SHOULD NOT PRINT OUT");
     FAILED("CONSTRAINT_ERROR NOT RAISED");

     RESULT;

END EB4012A;
