-- EB4014A.ADA

-- OBJECTIVE:
--     CHECK THAT WHEN EXCEPTIONS ARE RAISED DURING THE ELABORATION OF
--     A LIBRARY UNIT, EXECUTION OF THE MAIN PROGRAM IS ABANDONED.

-- PASS/FAIL CRITERIA:
--     THIS TEST MUST EXECUTE AND REPORT "TENTATIVELY PASSED". IN
--     ADDITION, THE OUTPUT/LOG FILE MUST INDICATE THAT THE PROGRAM
--     TERMINATED WITH AN UNHANDLED EXCEPTION.

-- HISTORY:
--     DHH 03/29/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
FUNCTION EB4014A1 RETURN INTEGER IS
BEGIN

     TEST("EB4014A", "THIS LINE SHOULD NOT BE PRINTED");

     FAILED("THE MAIN PROGRAM BODY WAS ENTERED");
     RESULT;

     RETURN IDENT_INT(1);

END EB4014A1;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE EB4014A_OUTSIDE IS
END EB4014A_OUTSIDE;

PACKAGE BODY EB4014A_OUTSIDE IS
BEGIN
     TEST("EB4014A", "CHECK THAT WHEN EXCEPTIONS ARE RAISED DURING " &
                     "THE ELABORATION OF A LIBRARY UNIT, EXECUTION " &
                     "OF THE MAIN PROGRAM IS ABANDONED");

     SPECIAL_ACTION("CHECK THE OUTPUT/LOG FILE TO SEE IF THIS " &
                    "PROGRAM TERMINATED WITH AN UNHANDLED " &
                    "EXCEPTION");

     RESULT;

     RAISE CONSTRAINT_ERROR;
END EB4014A_OUTSIDE;

WITH EB4014A1; WITH EB4014A_OUTSIDE;
WITH REPORT; USE REPORT;
PROCEDURE EB4014A IS
     X : INTEGER := EB4014A1;
BEGIN

     TEST("EB4014A", "THIS LINE SHOULD NOT PRINT OUT");

     FAILED("EXCEPTION DID NOT CAUSE MAIN PROGRAM TERMINATION");
     RESULT;
     X := IDENT_INT(X);
END EB4014A;
