-- EB4011A.ADA

-- OBJECTIVE:
--     CHECK THAT UNHANDLED EXCEPTIONS RAISED IN PACKAGE SUBUNITS ARE
--     PROPAGATED TO THE ENVIRONMENT STATICALLY ENCLOSING THE
--     CORRESPONDING BODY STUB (DECLARER OF THE PARENT UNIT).

-- PASS/FAIL CRITERIA:
--     THIS TEST MUST EXECUTE AND REPORT "TENTATIVELY PASSED". IN
--     ADDITION, THE OUTPUT/LOG FILE MUST INDICATE THAT THE PROGRAM
--     TERMINATED WITH AN UNHANDLED EXCEPTION.

-- HISTORY:
--     DHH 03/29/88 CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
PROCEDURE EB4011A IS

     PACKAGE EB4011A_OUTSIDE IS
     END EB4011A_OUTSIDE;

     PACKAGE EB4011A1 IS
     END EB4011A1;

     PACKAGE BODY EB4011A1 IS
     BEGIN

          TEST("EB4011A", "CHECK THAT UNHANDLED EXCEPTIONS RAISED IN " &
                          "PACKAGE SUBUNITS ARE PROPAGATED TO THE " &
                          "ENVIRONMENT STATICALLY ENCLOSING THE" &
                          "CORRESPONDING BODY STUB (DECLARER OF THE " &
                          "PARENT UNIT)");

          SPECIAL_ACTION("CHECK THE OUTPUT FILE TO SEE IF THIS " &
                         "PROGRAM TERMINATED WITH AN UNHANDLED " &
                         "EXCEPTION");

          RESULT;

     END EB4011A1;

     PACKAGE BODY EB4011A_OUTSIDE IS SEPARATE;

BEGIN

     TEST("EB4011A", "THIS LINE SHOULD NOT PRINT OUT");

     FAILED("EXCEPTION DID NOT CAUSE MAIN PROGRAM TERMINATION");
     RESULT;

END EB4011A;

SEPARATE (EB4011A)
PACKAGE BODY EB4011A_OUTSIDE IS
BEGIN
     RAISE CONSTRAINT_ERROR;
END EB4011A_OUTSIDE;
