-- ED1D04A.ADA

-- OBJECTIVE:
--     CHECK WHETHER THE OCCURRENCE OF A PRAGMA PACK PRIOR TO A
--     RECORD REPRESENTATION CLAUSE MAKES THE CLAUSE ILLEGAL.

-- HISTORY:
--     JET 09/17/87  CREATED ORIGINAL TEST.
--     DHH 03/27/89  ADDED STATEMENT OF PREFERRED BEHAVIOR TO PASS/FAIL
--                   CRITERIA.

-- PASS/FAIL CRITERIA:
--     THIS TEST IS PASSED IF IT EXECUTES AND REPORTS "PASSED" OR
--     IF THE REPRESENTATION CLAUSE FOR "REC_TYPE" IS REJECTED.
--     HOWEVER, THE PREFERRED BEHAVIOR IS ACCEPTANCE AND EXECUTION OF
--     THE PROGRAM.

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;

PROCEDURE ED1D04A IS

     UNITS_PER_INTEGER : CONSTANT :=
          (INTEGER'SIZE + SYSTEM.STORAGE_UNIT - 1) /
          SYSTEM.STORAGE_UNIT;

     TYPE E_TYPE IS (RED, BLUE, GREEN);

     TYPE TEST_REP IS
          RECORD
               I : INTEGER RANGE 0 .. 127 := 127;
               C : CHARACTER := 'S';
               B : BOOLEAN := FALSE;
               E : E_TYPE := BLUE;
          END RECORD;

     FOR TEST_REP USE
          RECORD
               C AT 0 * UNITS_PER_INTEGER RANGE 0 .. CHARACTER'SIZE - 1;
               B AT 1 * UNITS_PER_INTEGER RANGE 0 .. BOOLEAN'SIZE - 1;
               I AT 2 * UNITS_PER_INTEGER RANGE 0 .. INTEGER'SIZE/2 - 1;
               E AT 3 * UNITS_PER_INTEGER RANGE 0 .. CHARACTER'SIZE - 1;
          END RECORD;

     TYPE REC_TYPE IS
          RECORD
               I : INTEGER RANGE 0 .. 127 := 127;
               C : CHARACTER := 'S';
               B : BOOLEAN := FALSE;
               E : E_TYPE := BLUE;
          END RECORD;

     PRAGMA PACK (REC_TYPE);

     FOR REC_TYPE USE                       -- PASSED => ERROR.
          RECORD                            -- NOTE: THIS IS *NOT*
                                            --  THE PREFERRED BEHAVIOR!!
                                            --  SEE PASS/FAIL CRITERIA.

               C AT 0 * UNITS_PER_INTEGER RANGE 0 .. CHARACTER'SIZE - 1;
               B AT 1 * UNITS_PER_INTEGER RANGE 0 .. BOOLEAN'SIZE - 1;
               I AT 2 * UNITS_PER_INTEGER RANGE 0 .. INTEGER'SIZE/2 - 1;
               E AT 3 * UNITS_PER_INTEGER RANGE 0 .. CHARACTER'SIZE - 1;
          END RECORD;

     REC : REC_TYPE;

BEGIN

     TEST("ED1D04A", "CHECK WHETHER THE OCCURRENCE OF A PRAGMA " &
                     "PACK PRIOR TO A RECORD REPRESENTATION " &
                     "CLAUSE MAKES THE CLAUSE ILLEGAL");

     IF REC.C'POSITION /= IDENT_INT (0) OR
        REC.B'POSITION /= IDENT_INT (UNITS_PER_INTEGER) OR
        REC.I'POSITION /= IDENT_INT (2 * UNITS_PER_INTEGER) OR
        REC.E'POSITION /= IDENT_INT (3 * UNITS_PER_INTEGER) THEN
          FAILED ("INCORRECT POSITIONS OF REC COMPONENTS");
     END IF;

     IF REC.C'FIRST_BIT /= IDENT_INT (0) OR
        REC.B'FIRST_BIT /= IDENT_INT (0) OR
        REC.I'FIRST_BIT /= IDENT_INT (0) OR
        REC.E'FIRST_BIT /= IDENT_INT (0) THEN
          FAILED ("INCORRECT FIRST_BITS OF REC COMPONENTS");
     END IF;

     IF REC.C'LAST_BIT /= IDENT_INT (CHARACTER'SIZE - 1) OR
        REC.B'LAST_BIT /= IDENT_INT (BOOLEAN'SIZE - 1) OR
        REC.I'LAST_BIT /= IDENT_INT (INTEGER'SIZE/2 - 1) OR
        REC.E'LAST_BIT /= IDENT_INT (CHARACTER'SIZE - 1) THEN
          FAILED ("INCORRECT LAST_BITS OF REC COMPONENTS");
     END IF;

     RESULT;

END ED1D04A;
