-- ED2A26A.ADA

-- OBJECTIVE:
--     IF A SIZE SPECIFICATION FOR AN ENUMERATION TYPE CAN
--     BE GIVEN AFTER AN ENUMERATION REPRESENTATION CLAUSE FOR
--     THE TYPE, CHECK WHETHER IT CAN ALSO BE GIVEN BEFORE THE
--     ENUMERATION CLAUSE.

-- PASS/FAIL CRITERIA
--     THIS TEST PASSES IF IT EXECUTES AND REPORTS "PASSED", OR
--     IF THE ENUMERATION REPRESENTATION CLAUSE FOR "STAT" IS
--     REJECTED.

-- HISTORY:
--     DHH 09/18/87 CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'

WITH REPORT; USE REPORT;
PROCEDURE ED2A26A IS

     SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE/2;

     TYPE STATUS IS (OFF, ON, READY);
     FOR STATUS USE (OFF => 6, ON => 7, READY => 8);

     FOR STATUS'SIZE USE SPECIFIED_SIZE;

     TYPE STAT IS (OFF, ON, READY);
     FOR STAT'SIZE USE SPECIFIED_SIZE;

     FOR STAT USE (OFF => 6, ON => 7, READY => 8); -- PASSED => ERROR.

BEGIN
     TEST ("ED2A26A", "IF A SIZE SPECIFICATION FOR AN " &
                      "ENUMERATION TYPE CAN BE GIVEN AFTER AN " &
                      "ENUMERATION RERESENTATION CLAUSE FOR THE " &
                      "TYPE, CHECK WHETHER IT CAN ALSO BE GIVEN " &
                      "BEFORE THE ENUMERATION CLAUSE");

     IF STAT'SIZE /= IDENT_INT(SPECIFIED_SIZE) THEN
          FAILED("INCORRECT VALUE FOR STAT'SIZE");
     END IF;

     RESULT;
END ED2A26A;
