-- ED2A56A.ADA

-- OBJECTIVE:
--     IF A SIZE SPECIFICATION FOR A FIXED TYPE CAN BE GIVEN
--     AFTER A 'SMALL SPECIFICATION FOR THE TYPE, CHECK
--     WHETHER IT CAN ALSO BE GIVEN BEFORE THE 'SMALL CLAUSE.

-- PASS FAIL CRITERIA
--     THIS TEST PASSES IF IT EXECUTES AND REPORTS "PASSED", OR
--     IF THE 'SMALL CLAUSE FOR "STAT" IS REJECTED.

-- HISTORY:
--     DHH 09/22/87 CREATED ORIGINAL TEST.
--     PWB 05/11/89  CHANGED EXTENSION FROM '.DEP' TO '.ADA'.

WITH REPORT; USE REPORT;
PROCEDURE ED2A56A IS

     SPECIFIED_SIZE : CONSTANT := INTEGER'SIZE/2;

     TYPE FIXED IS DELTA 1.0 RANGE 0.0..4.0;
     FOR FIXED'SMALL USE 2.0**(-4);
     FOR FIXED'SIZE USE SPECIFIED_SIZE;

     TYPE STAT IS DELTA 1.0 RANGE 0.0..4.0;
     FOR STAT'SIZE USE SPECIFIED_SIZE;
     FOR STAT'SMALL USE 2.0**(-4);             --PASSED => ERROR.

BEGIN
     TEST ("ED2A56A", "IF A SIZE SPECIFICATION FOR A FIXED " &
                      "TYPE CAN BE GIVEN AFTER A 'SMALL " &
                      "SPECIFICATION FOR THE TYPE, " &
                      "CHECK WHETHER IT CAN ALSO BE GIVEN " &
                      "BEFORE THE 'SMALL CLAUSE");

     IF FIXED'SIZE /= IDENT_INT(SPECIFIED_SIZE) OR
                     STAT'SIZE /= IDENT_INT(SPECIFIED_SIZE) THEN
          FAILED ("'SIZE ATTRIBUTE GIVES WRONG RESULT");
     END IF;

     IF FIXED'SMALL /= STAT'SMALL THEN
          FAILED ("'SMALL ATTRIBUTE GIVES WRONG RESULT");
     END IF;

     RESULT;
END ED2A56A;
