-- ED4021A.ADA

-- OBJECTIVE:
--     CHECK THAT A COMPONENT CLAUSE CAN BE GIVEN FOR A COMPONENT
--     WITH AN ENUMERATION SUBTYPE.  CHECK WHETHER IT CAN SPECIFY
--     LESS THAN THE USUAL AMOUNT OF SPACE ALLOCATED TO A VARIABLE OF
--     THAT SUBTYPE.

-- PASS/FAIL CRITERIA:
--     THIS TEST PASSES IF IT EXECUTES AND REPORTS 'PASSED'.
--     ALTERNATELY, THIS TEST PASSES IF THE REPRESENTATION CLAUSE FOR
--     REC IS REJECTED.

-- HISTORY:
--     BCB 09/14/88  CREATED ORIGINAL TEST.
--     BCB 03/20/89  CHANGED EXTENSION FROM '.ADA' TO '.DEP'.

WITH REPORT; USE REPORT;

PROCEDURE ED4021A IS

     TYPE ENUM IS (ONE, TWO, THREE, FOUR, FIVE);

     SUBTYPE SUBENUM IS ENUM RANGE ONE .. TWO;

     CHECK_SIZE : CONSTANT INTEGER := ENUM'SIZE/2;

     TYPE CHECK_RECORD IS RECORD
          X : ENUM;
     END RECORD;

     FOR CHECK_RECORD USE RECORD
          X AT 0 RANGE 0 .. ENUM'SIZE-1;
     END RECORD;

     TYPE REC IS RECORD
          RECVAR : SUBENUM;
     END RECORD;

     FOR REC USE RECORD
          RECVAR AT 0 RANGE 0 .. CHECK_SIZE-1;       -- PASSED => ERROR.
     END RECORD;

BEGIN
     TEST ("ED4021A", "CHECK THAT A COMPONENT CLAUSE CAN BE GIVEN " &
                      "FOR A COMPONENT WITH AN ENUMERATION SUBTYPE.  " &
                      "CHECK WHETHER IT CAN SPECIFY LESS THAN " &
                      "THE USUAL AMOUNT OF SPACE ALLOCATED TO A " &
                      "VARIABLE OF THAT SUBTYPE");

     RESULT;
END ED4021A;
