-- ED7002B.ADA

-- OBJECTIVE:
--     CHECK WHETHER A VALUE OF TYPE ADDRESS CAN BE ASSIGNED TO A
--     VARIABLE OF THE TYPE.

-- PASS/FAIL CRITERIA:
--     THIS TEST PASSES IF IT COMPILES, LINKS, AND REPORTS "PASSED." IN
--     THIS CASE, A VALUE OF TYPE SYSTEM.ADDRESS CAN BE ASSIGNED TO A
--     VARIABLE OF THAT TYPE.  ALTERNATIVELY, THIS TEST PASSES IF THE
--     ASSIGNMENT TO VARIABLE 'A' IS REJECTED.  IN THIS CASE, SUCH
--     ASSIGNMENTS ARE NOT ALLOWED.

-- HISTORY:
--     JET 08/25/88  CREATED ORIGINAL TEST.

WITH REPORT; USE REPORT;
WITH SYSTEM; USE SYSTEM;
PROCEDURE ED7002B IS

     I : INTEGER;
     A : ADDRESS;

BEGIN
     TEST ("ED7002B", "CHECK WHETHER A VALUE OF TYPE ADDRESS CAN BE " &
                      "ASSIGNED TO A VARIABLE OF THE TYPE");

     A := I'ADDRESS;                         -- PASSED => ERROR.

     COMMENT("A VALUE OF TYPE SYSTEM.ADDRESS CAN BE ASSIGNED TO A " &
             "VARIABLE");

     RESULT;
END ED7002B;
