-- EE3409F.ADA

-- OBJECTIVE:
--     CHECK THAT THE FILE PARAMETER FOR SET_COL IS OPTIONAL, AND
--     THAT THE FUNCTION IS THEN APPLIED TO THE CURRENT DEFAULT
--     OUTPUT FILE.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     CREATION OF TEMPORARY TEXT FILES WITH OUT_FILE MODE.

-- PASS/FAIL CRITERIA:
--     THIS TEST IS PASSED IF IT EXECUTES, PRINTS TENTATIVELY PASSED,
--     AND THE CONTENTS OF THE STANDARD OUTPUT FILE ARE CORRECT.

-- HISTORY:
--     ABW 08/26/82
--     SPS 09/20/82
--     TBN 11/10/86  REVISED TEST TO OUTPUT A NOT_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     JLH 08/31/87  CORRECTED EXCEPTION HANDLING, CHECKED FOR
--                   USE_ERROR ON DELETE, AND RENAMED FROM
--                   CE3409F.ADA.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE EE3409F IS

     INCOMPLETE : EXCEPTION;
     FILE_OUT : FILE_TYPE;
     TWO   : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(2));
     THREE : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(3));

BEGIN

     TEST ("EE3409F", "CHECK DEFAULT FILE FOR SET_COL");

     BEGIN
          CREATE (FILE_OUT);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED ON TEXT CREATE " &
                               "FOR TEMPORARY FILES WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED ON TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     SPECIAL_ACTION ("THE NEXT LINE SHOULD BEGIN IN COLUMN TWO");

     SET_COL (TWO);
     PUT ("SHOULD BEGIN IN COLUMN TWO");

     IF COL (STANDARD_OUTPUT) /= 28 THEN
          FAILED ("SET_COL DOES NOT OPERATE ON THE DEFAULT " &
                  "STANDARD_OUTPUT");
     END IF;

     NEW_LINE;

     SET_OUTPUT (FILE_OUT);
     SET_COL (THREE);
     IF COL (CURRENT_OUTPUT) /= THREE THEN
          FAILED ("SET_COL DOES NOT OPERATE ON THE DEFAULT " &
                  "CURRENT_OUTPUT");
     END IF;

     CLOSE (FILE_OUT);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END EE3409F;
