-- EE3405B.ADA

-- OBJECTIVE:
--     CHECK THAT NEW_PAGE OPERATES ON THE CURRENT DEFAULT OUTPUT
--     FILE IF NO FILE IS SPECIFIED.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH
--     SUPPORT TEMPORARY TEXT FILES WITH OUT_FILE MODE.

-- PASS/FAIL CRITERIA:
--     THIS TEST IS PASSED IF IT EXECUTES, PRINTS TENTATIVELY PASSED,
--     AND THE CONTENTS OF THE STANDARD OUTPUT FILE ARE CORRECT.

-- HISTORY:
--     ABW 08/26/82
--     SPS 09/17/82
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     DWC 09/23/87  RENAMED TEST TO EE3405B.ADA.  CORRECTED EXCEPTION
--                   HANDLING AND CALLED SPECIAL_ACTION PROCEDURE.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;

PROCEDURE EE3405B IS

     INCOMPLETE : EXCEPTION;
     FILE_OUT   : FILE_TYPE;
     ONE        : POSITIVE_COUNT := POSITIVE_COUNT(IDENT_INT(1));
     CUR_PAGE   : COUNT;

BEGIN

     TEST ("EE3405B", "CHECK THAT NEW_PAGE OPERATES ON THE CURRENT " &
                      "DEFAULT OUTPUT FILE IF NO FILE IS SPECIFIED");

     BEGIN
          CREATE (FILE_OUT);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; TEXT CREATE " &
                               "FOR TEMPORARY FILE WITH " &
                               "OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; TEXT CREATE");
               RAISE INCOMPLETE;
     END;

     SPECIAL_ACTION ("PAGE TERMINATOR OUTPUT AFTER THIS COMMENT");
     CUR_PAGE := PAGE(STANDARD_OUTPUT);
     NEW_PAGE;
     IF PAGE (STANDARD_OUTPUT) /= CUR_PAGE + ONE THEN
          FAILED ("NEW_PAGE WITHOUT PARAMETER DOES NOT OPERATE " &
                  "ON STANDARD_OUTPUT");
     END IF;

     SET_OUTPUT (FILE_OUT);
     NEW_PAGE;
     NEW_PAGE;
     IF PAGE (CURRENT_OUTPUT) /=  3 THEN
          FAILED ("FILE DEFAULT NOT CURRENT_OUTPUT");
     END IF;

     CLOSE (FILE_OUT);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END EE3405B;
