-- EE3402B.ADA

-- OBJECTIVE:
--     CHECK THAT NEW_LINE HAS AN OPTIONAL SPACING PARAMETER WITH
--     DEFAULT VALUE ONE, AND CHECK THAT NEW_LINE OPERATES ON THE
--     CURRENT DEFAULT OUTPUT FILE IF NO FILE IS SPECIFIED.

-- APPLICABILITY CRITERIA:
--     THIS TEST IS APPLICABLE ONLY TO IMPLEMENTATIONS WHICH SUPPORT
--     TEXT FILES.

-- PASS/FAIL CRITERIA:
--     THIS TEST IS PASSED IF IT EXECUTES, PRINTS TENTATIVELY PASSED,
--     AND THE CONTENTS OF THE STANDARD OUTPUT FILE ARE CORRECT.

-- HISTORY:
--     ABW 08/26/82
--     SPS 09/16/82
--     TBN 11/04/86  REVISED TEST TO OUTPUT A NON_APPLICABLE
--                   RESULT WHEN FILES ARE NOT SUPPORTED.
--     DWC 08/19/87  ADDED SPECIAL ACTION FUNCTION AND REMOVED
--                   EXCEPTION HANDLERS.  CHANGED TO AN E TEST.

WITH REPORT;
USE REPORT;
WITH TEXT_IO;
USE TEXT_IO;
WITH CHECK_FILE;

PROCEDURE EE3402B IS

     INCOMPLETE : EXCEPTION;
     FILE, FILE_OUT : FILE_TYPE;
     SPAC : CONSTANT POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(4));
     TWO : CONSTANT POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(2));
     FOUR : CONSTANT POSITIVE_COUNT := POSITIVE_COUNT (IDENT_INT(4));
     CUR_LINE : COUNT;

BEGIN

     TEST ("EE3402B", "CHECK THAT NEW_LINE HAS AN OPTIONAL " &
                      "SPACING PARAMETER WITH DEFAULT VALUE ONE, " &
                      "AND CHECK THAT NEW_LINE OPERATES ON THE " &
                      "CURRENT DEFAULT OUTPUT FILE IF NO FILE IS " &
                      "SPECIFIED.");

     BEGIN
          CREATE (FILE);
     EXCEPTION
          WHEN USE_ERROR =>
               NOT_APPLICABLE ("USE_ERROR RAISED; TEXT CREATE " &
                               "WITH OUT_FILE MODE");
               RAISE INCOMPLETE;
          WHEN OTHERS =>
               FAILED ("UNEXPECTED EXCEPTION RAISED; TEXT CREATE - 1");
               RAISE INCOMPLETE;
     END;

     CREATE (FILE_OUT);

     SPECIAL_ACTION ("CHECK OUTPUT FOR FOUR BLANK LINES");

     NEW_LINE (FILE);
     IF LINE (FILE) /= TWO THEN
          FAILED ("SPACING DEFAULT NOT ONE");
     END IF;

     SPECIAL_ACTION ("FOUR BLANK LINES SHOULD FOLLOW THIS COMMENT");
     CUR_LINE := LINE (STANDARD_OUTPUT);
     NEW_LINE (SPAC);
     IF LINE (STANDARD_OUTPUT) /= CUR_LINE + 4 THEN
          FAILED ("FILE DEFAULT NOT CORRECT FOR STANDARD_OUTPUT");
     END IF;

     SET_OUTPUT (FILE_OUT);
     NEW_LINE (SPAC);
     IF LINE (CURRENT_OUTPUT) /= FOUR + 1 THEN
          FAILED ("FILE DEFAULT NOT CORRECT FOR CURRENT_OUTPUT");
     END IF;

     SET_OUTPUT (STANDARD_OUTPUT);      -- RESET STANDARD OUTPUT
     COMMENT ("CHECKING FILE");
     CHECK_FILE (FILE, "#@%");
     COMMENT ("CHECKING FILE_OUT");
     CHECK_FILE (FILE_OUT, "####@%");

     CLOSE (FILE);
     CLOSE (FILE_OUT);

     RESULT;

EXCEPTION
     WHEN INCOMPLETE =>
          RESULT;

END EE3402B;
