-- LA1001F.ADA

-- OBJECTIVE:
--     CHECK THAT A PACKAGE CANNOT BE NAMED AS A MAIN PROGRAM.

-- HISTORY:
--     JET 08/12/88  CREATED ORIGINAL TEST.

PACKAGE LA1001F IS
END LA1001F;

WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE BODY LA1001F IS
BEGIN
     TEST("LA1001F", "CHECK THAT A PACKAGE CANNOT BE NAMED AS A " &
                      "MAIN PROGRAM");

     FAILED("PACKAGE WAS IMPROPERLY LINKED AND EXECUTED");

     RESULT;
END LA1001F;
