-- LA3004A6M.ADA

-- CHECK THAT, IF THE BODY OF AN INLINE PROCEDURE IS MODIFIED,
-- ALL UNITS CALLING THAT PROCEDURE AS AN INLINE PROCEDURE
-- MUST BE RECOMPILED.

-- SEPARATE FILES ARE:
--   LA3004A0  A LIBRARY PACKAGE DECLARATION (LA3004A0).
--   LA3004A1  A LIBRARY PACKAGE BODY (LA3004A0).
--   LA3004A2  A LIBRARY PROCEDURE DECL AND BODY.
--   LA3004A3  A LIBRARY FUNCTION DECL AND BODY.
--   LA3004A4  A LIBRARY PACKAGE DECL AND BODY.
--   LA3004A5  A LIBRARY PACKAGE BODY (LA3004A0).
--   LA3004A6M THE MAIN PROCEDURE.

-- IF THE INLINE PRAGMA IS SUPPORTED FOR PROCEDURES, THEN EXPECT TO GET
--   LINK-TIME ERROR MESSAGES THAT THE BODIES OF LA3004A(2,3,4) ARE
--   OBSOLETE OR MISSING.
-- OTHERWISE, THIS TEST SHOULD EXECUTE AND GIVE A NOT-APPLICABLE RESULT.

-- WKB 07/13/81
-- EG  06/05/84
-- JRK 5/21/85

WITH REPORT; USE REPORT;
WITH LA3004A2, LA3004A3, LA3004A4;

PROCEDURE LA3004A6M IS

     TEMP_I : INTEGER;

BEGIN
     TEST ("LA3004A", "MODIFYING THE BODY OF AN INLINE " &
                      "PROCEDURE REQUIRES RECOMPILATION OF " &
                      "CALLING UNITS");

     LA3004A2 (TEMP_I);
     CASE TEMP_I IS
          WHEN 3 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PROCEDURE " &
                       "BODY NOT RECOMPILED");
          WHEN 7 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PROCEDURE BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PROCEDURE");
     END CASE;

     CASE LA3004A3 IS
          WHEN 4 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING FUNCTION " &
                       "BODY NOT RECOMPILED");
          WHEN 8 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM FUNCTION BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY FUNCTION");
     END CASE;

     CASE LA3004A4.I IS
          WHEN 5 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING PACKAGE " &
                       "BODY NOT RECOMPILED");
          WHEN 9 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM PACKAGE BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PACKAGE");
     END CASE;

     RESULT;
END LA3004A6M;
