-- LA3004B7M.ADA

-- CHECK THAT, IF THE BODY OF AN INLINE FUNCTION IS MODIFIED,
-- ALL SUBUNITS CALLING THAT FUNCTION AS AN INLINE FUNCTION
-- MUST BE RECOMPILED.

-- SEPARATE FILES ARE:
--   LA3004B0  A LIBRARY FUNCTION DECLARATION (LA3004B0).
--   LA3004B1  A LIBRARY FUNCTION BODY (LA3004B0).
--   LA3004B2  A LIBRARY PROCEDURE (LA3004B2) AND ITS SUBUNIT PROCEDURE
--                  BODY (LA3004B2P).
--   LA3004B3  A LIBRARY FUNCTION (LA3004B3) AND ITS SUBUNIT FUNCTION
--                  BODY (LA3004B3F).
--   LA3004B4  A LIBRARY PACKAGE DECL AND BODY (LA3004B4) AND ITS
--                  SUBUNIT PACKAGE BODY (LA3004B4Q).
--   LA3004B5  A LIBRARY PACKAGE DECL AND BODY (LA3004B5) AND ITS
--                  SUBUNIT TASK BODY (LA3004B5T).
--   LA3004B6  A LIBRARY FUNCTION BODY (LA3004B0).
--   LA3004B7M THE MAIN PROCEDURE.

-- IF THE INLINE PRAGMA IS SUPPORTED FOR FUNCTIONS, THEN EXPECT TO GET
--   LINK-TIME ERROR MESSAGES THAT THE BODIES OF LA3004B(2P,3F,4Q,5T)
--   ARE OBSOLETE OR MISSING.
-- OTHERWISE, THIS TEST SHOULD EXECUTE AND GIVE A NOT-APPLICABLE RESULT.

-- WKB 07/13/81
-- EG  06/05/84
-- JRK 5/21/85

WITH REPORT; USE REPORT;
WITH LA3004B2, LA3004B3, LA3004B4, LA3004B5;

PROCEDURE LA3004B7M IS

     TEMP_I : INTEGER;

BEGIN
     TEST ("LA3004B", "MODIFYING THE BODY OF AN INLINE FUNCTION " &
                      "REQUIRES RECOMPILATION OF CALLING SUBUNITS");

     LA3004B2 (TEMP_I);
     CASE TEMP_I IS
          WHEN 3 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING SUBUNIT " &
                       "PROCEDURE BODY NOT RECOMPILED");
          WHEN 7 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM SUBUNIT PROCEDURE BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PROCEDURE");
     END CASE;

     CASE LA3004B3 IS
          WHEN 4 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING SUBUNIT " &
                       "FUNCTION BODY NOT RECOMPILED");
          WHEN 8 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM SUBUNIT FUNCTION BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY FUNCTION");
     END CASE;

     CASE LA3004B4.I IS
          WHEN 4 =>
               FAILED ("INLINE PRAGMA OBEYED BUT PARENT UNIT OF " &
                       "CALLING SUBUNIT PACKAGE BODY ALSO MADE " &
                       "OBSOLETE");
          WHEN 7 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING SUBUNIT " &
                       "PACKAGE BODY NOT RECOMPILED");
          WHEN 11 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM SUBUNIT PACKAGE BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PACKAGE");
     END CASE;

     CASE LA3004B5.I IS
          WHEN 6 =>
               FAILED ("INLINE PRAGMA OBEYED BUT CALLING SUBUNIT " &
                       "TASK BODY NOT RECOMPILED");
          WHEN 10 =>
               NOT_APPLICABLE ("INLINE PRAGMA NOT OBEYED IN CALL " &
                               "FROM SUBUNIT TASK BODY");
          WHEN OTHERS =>
               FAILED ("WRONG VALUE RETURNED BY PACKAGE/TASK");
     END CASE;

     RESULT;
END LA3004B7M;
