-- LA5008F1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE F:  MISSING SUBUNIT GENERIC PACKAGE BODY (NON-GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008F0  A LIBRARY PACKAGE DECL AND BODY.
--   LA5008F1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PACKAGE
--   LA5008F0.LA5008F0P IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008F0
--   THAT THE BODY OF GENERIC PACKAGE LA5008F0.LA5008F0P IS NOT IN THE
--   SAME COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008F0;

PROCEDURE LA5008F1M IS
BEGIN
     TEST ("LA5008F", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT GENERIC PACKAGE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008F1M;
