-- LA5007H2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE H:  OBSOLETE (BY RECOMP. OF DECL.) LIBRARY PROCEDURE BODY
--          (SEPARATE DECL.).

-- SEPARATE FILES ARE:
--   LA5007H0  A LIBRARY PROCEDURE DECL AND BODY.
--   LA5007H1  A LIBRARY PROCEDURE DECLARATION (LA5007H0).
--   LA5007H2M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PROCEDURE LA5007H0
--   IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007H0;

PROCEDURE LA5007H2M IS
BEGIN
     TEST ("LA5007H", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PROCEDURE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007H2M;
