-- LA5008K3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE K:  OBSOLETE (BY RECOMP. OF WITHED GENERIC UNIT) LIBRARY GENERIC
--          PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5008K0  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008K1  A LIBRARY GENERIC PACKAGE DECL AND BODY.
--   LA5008K2  A LIBRARY GENERIC PACKAGE DECLARATION (LA5008K0).
--   LA5008K3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PACKAGE
--   LA5008K1 IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008K1;

PROCEDURE LA5008K3M IS
BEGIN
     TEST ("LA5008K", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PACKAGE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008K3M;
