-- LA5007A1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE A:  MISSING LIBRARY PROCEDURE BODY (SEPARATE DECL.).

-- SEPARATE FILES ARE:
--   LA5007A0  A LIBRARY PROCEDURE DECLARATION.
--   LA5007A1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PROCEDURE LA5007A0
--   IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007A0;

PROCEDURE LA5007A1M IS
BEGIN
     TEST ("LA5007A", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PROCEDURE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007A1M;
