-- LA5007F1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE F:  MISSING SUBUNIT PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5007F0  A LIBRARY PACKAGE DECL AND BODY.
--   LA5007F1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PACKAGE
--   LA5007F0.LA5007F0P IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007F0;

PROCEDURE LA5007F1M IS
BEGIN
     TEST ("LA5007F", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT PACKAGE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007F1M;
