-- LA5008I3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE I:  OBSOLETE (BY RECOMP. OF WITHED NON-GENERIC UNIT) LIBRARY
--          GENERIC FUNCTION BODY.

-- SEPARATE FILES ARE:
--   LA5008I0  A LIBRARY PACKAGE DECLARATION.
--   LA5008I1  A LIBRARY GENERIC FUNCTION DECL AND BODY.
--   LA5008I2  A LIBRARY PACKAGE DECLARATION (LA5008I0).
--   LA5008I3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC FUNCTION
--   LA5008I1 IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008I1;

PROCEDURE LA5008I3M IS
BEGIN
     TEST ("LA5008I", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC FUNCTION BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008I3M;
