-- LA5007Q2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE Q:  OBSOLETE (BY RECOMP. OF WITHED UNIT) LIBRARY FUNCTION
--          (SEPARATE) DECLARATION.

-- SEPARATE FILES ARE:
--   LA5007Q0  A LIBRARY FUNCTION DECL AND BODY.
--   LA5007Q1  A LIBRARY FUNCTION DECL AND BODY.
--   LA5007Q2M THE MAIN PROCEDURE.
--   LA5007Q3  A LIBRARY FUNCTION DECL AND BODY (LA5007Q0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5007Q2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT THE DECLARATION OF
--   FUNCTION LA5007Q1 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007Q1;

PROCEDURE LA5007Q2M IS
BEGIN
     TEST ("LA5007Q", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY FUNCTION DECLARATION IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007Q2M;
