-- LA5007G1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE G:  MISSING SUBUNIT TASK BODY.

-- SEPARATE FILES ARE:
--   LA5007G0  A LIBRARY PACKAGE DECL AND BODY.
--   LA5007G1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF TASK
--   LA5007G0.LA5007G0T IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007G0;

PROCEDURE LA5007G1M IS
BEGIN
     TEST ("LA5007G", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT TASK BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007G1M;
