-- LA5008R2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE R:  OBSOLETE (BY RECOMP. OF WITHED GENERIC UNIT) LIBRARY GENERIC
--          PACKAGE DECLARATION.

-- SEPARATE FILES ARE:
--   LA5008R0  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008R1  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008R2M THE MAIN PROCEDURE.
--   LA5008R3  A LIBRARY GENERIC PACKAGE DECLARATION (LA5008R0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008R2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT THE DECLARATION OF
--   GENERIC PACKAGE LA5008R1 IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008R1;

PROCEDURE LA5008R2M IS
BEGIN
     TEST ("LA5008R", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PACKAGE DECLARATION IS " &
                      "OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008R2M;
