-- LA5007E1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE E:  MISSING SUBUNIT FUNCTION BODY.

-- SEPARATE FILES ARE:
--   LA5007E0  A LIBRARY FUNCTION.
--   LA5007E1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF FUNCTION
--   LA5007E0.LA5007E0F IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007E0;

PROCEDURE LA5007E1M IS
BEGIN
     TEST ("LA5007E", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT FUNCTION BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007E1M;
