-- LA5008V3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE V:  OBSOLETE (BY RECOMP. OF WITHED NON-GENERIC UNIT) LIBRARY
--          GENERIC PACKAGE INSTANTIATION.

-- SEPARATE FILES ARE:
--   LA5008V0  A LIBRARY PACKAGE DECLARATION.
--   LA5008V1  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008V2  A LIBRARY GENERIC PACKAGE INSTANTIATION.
--   LA5008V3M THE MAIN PROCEDURE.
--   LA5008V4  A LIBRARY PACKAGE DECLARATION (LA5008V0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008V3M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT PACKAGE LA5008V2 IS
--   MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008V2;

PROCEDURE LA5008V3M IS
BEGIN
     TEST ("LA5008V", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PACKAGE INSTANTIATION IS " &
                      "OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008V3M;
