-- LA5008C0.ADA

-- JRK 11/1/85

GENERIC
PACKAGE LA5008C0 IS

     PROCEDURE P;

END LA5008C0;       -- OPTIONAL ERROR: CORRESPONDING BODY NOT IN SAME
                    -- COMPILATION FILE AS ITS DECLARATION.
