-- LA5007O4M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE O:  OBSOLETE (BY RECOMP. OF WITHED UNIT) SUBUNIT TASK BODY.

-- SEPARATE FILES ARE:
--   LA5007O0  A LIBRARY PACKAGE DECLARATION.
--   LA5007O1  A LIBRARY PACKAGE DECL AND BODY.
--   LA5007O2  A SUBUNIT TASK BODY (LA5007O1.LA5007O2).
--   LA5007O3  A LIBRARY PACKAGE DECLARATION (LA5007O0).
--   LA5007O4M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF TASK
--    LA5007O1.LA5007O2 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007O1;

PROCEDURE LA5007O4M IS
BEGIN
     TEST ("LA5007O", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT TASK BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007O4M;
