-- LA5008M2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE M:  OBSOLETE (BY RECOMP. OF PARENT) SUBUNIT GENERIC FUNCTION
--          BODY (GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008M0  A LIBRARY GENERIC FUNCTION DECL AND BODY,
--             A SUBUNIT GENERIC FUNCTION BODY (LA5008M0.LA5008M0F).
--   LA5008M1  A LIBRARY GENERIC FUNCTION BODY (LA5008M0).
--   LA5008M2M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC FUNCTION
--   LA5008M0.LA5008M0F IS MISSING OR OBSOLETE.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008M1
--   THAT THE DECLARATION OF GENERIC FUNCTION LA5008M0 IS NOT IN THE
--   SAME COMPILATION FILE AS ITS BODY.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008M1
--   THAT THE BODY OF GENERIC FUNCTION LA5008M0.LA5008M0F IS NOT IN THE
--   SAME COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85
-- LDC 08/22/88     CHANGED CALL TO FAILED TO A CALL TO SPECIAL_ACTION
--                  TO HANDLE THE CASE IN WHICH SEPARATE COMPILATION OF
--                  GENERIC SUBUNITS IS NOT SUPPORTED.

WITH REPORT; USE REPORT;
WITH LA5008M0;

PROCEDURE LA5008M2M IS
BEGIN
     TEST ("LA5008M", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT GENERIC FUNCTION BODY IS OBSOLETE");

     SPECIAL_ACTION("IF SEPARATE COMPILATION OF GENERIC SUBUNITS IS " &
                    "NOT SUPPORTED, THEN THE TEST IS NOT " &
                    "APPLICABLE, OTHERWISE, THE TEST FAILS.");

     RESULT;
END LA5008M2M;
