-- LA5008O3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE O:  OBSOLETE (BY RECOMP. OF WITHED NON-GENERIC UNIT) SUBUNIT
--          TASK BODY (GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008O0  A LIBRARY PACKAGE DECLARATION.
--   LA5008O1  A LIBRARY GENERIC PACKAGE DECL AND BODY,
--             A SUBUNIT TASK BODY (LA5008O1.LA5008O1T).
--   LA5008O2  A LIBRARY PACKAGE DECLARATION (LA5008O0).
--   LA5008O3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF TASK
--    LA5008O1.LA5008O1T IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008O1;

PROCEDURE LA5008O3M IS
BEGIN
     TEST ("LA5008O", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT TASK BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008O3M;
