-- LA5007C1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE C:  MISSING LIBRARY PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5007C0  A LIBRARY PACKAGE DECLARATION.
--   LA5007C1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PACKAGE LA5007C0
--   IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007C0;

PROCEDURE LA5007C1M IS
BEGIN
     TEST ("LA5007C", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PACKAGE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007C1M;
