-- LA5008U2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE U:  OBSOLETE (BY RECOMP. OF GENERIC DECL) LIBRARY GENERIC
--          PACKAGE INSTANTIATION.

-- SEPARATE FILES ARE:
--   LA5008U0  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008U1  A LIBRARY GENERIC PACKAGE INSTANTIATION.
--   LA5008U2M THE MAIN PROCEDURE.
--   LA5008U3  A LIBRARY GENERIC PACKAGE DECLARATION (LA5008U0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008U2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT PACKAGE LA5008U1 IS
--   MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008U1;

PROCEDURE LA5008U2M IS
BEGIN
     TEST ("LA5008U", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PACKAGE INSTANTIATION IS " &
                      "OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008U2M;
