-- LA5008C1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE C:  MISSING LIBRARY GENERIC PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5008C0  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008C1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PACKAGE
--   LA5008C0 IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008C0
--   THAT THE BODY OF GENERIC PACKAGE LA5008C0 IS NOT IN THE SAME
--   COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008C0;

PROCEDURE LA5008C1M IS
BEGIN
     TEST ("LA5008C", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PACKAGE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008C1M;
