-- LA5007N3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE N:  OBSOLETE (BY RECOMP. OF PARENT) SUBUNIT PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5007N0  A LIBRARY PACKAGE DECL AND BODY.
--   LA5007N1  A SUBUNIT PACKAGE BODY (LA5007N0.LA5007N1).
--   LA5007N2  A LIBRARY PACKAGE BODY (LA5007N0).
--   LA5007N3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PACKAGE
--    LA5007N0.LA5007N1 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007N0;

PROCEDURE LA5007N3M IS
BEGIN
     TEST ("LA5007N", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT PACKAGE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007N3M;
