-- LA5007B1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE B:  MISSING LIBRARY FUNCTION BODY (SEPARATE DECL.).

-- SEPARATE FILES ARE:
--   LA5007B0  A LIBRARY FUNCTION DECLARATION.
--   LA5007B1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF FUNCTION LA5007B0
--   IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007B0;

PROCEDURE LA5007B1M IS
BEGIN
     TEST ("LA5007B", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY FUNCTION BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007B1M;
