-- LA5008P2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE P:  OBSOLETE (BY RECOMP. OF WITHED NON-GENERIC UNIT) LIBRARY
--          GENERIC PROCEDURE DECLARATION.

-- SEPARATE FILES ARE:
--   LA5008P0  A LIBRARY PROCEDURE DECL AND BODY.
--   LA5008P1  A LIBRARY GENERIC PROCEDURE DECL AND BODY.
--   LA5008P2M THE MAIN PROCEDURE.
--   LA5008P3  A LIBRARY PROCEDURE DECL AND BODY (LA5008P0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008P2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT THE DECLARATION OF
--   GENERIC PROCEDURE LA5008P1 IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008P1;

PROCEDURE LA5008P2M IS
BEGIN
     TEST ("LA5008P", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PROCEDURE DECLARATION IS " &
                      "OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008P2M;
