-- LA5007J2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE J:  OBSOLETE (BY RECOMP. OF DECL.) LIBRARY PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5007J0  A LIBRARY PACKAGE DECL AND BODY.
--   LA5007J1  A LIBRARY PACKAGE DECLARATION (LA5007J0).
--   LA5007J2M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PACKAGE LA5007J0
--   IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007J0;

PROCEDURE LA5007J2M IS
BEGIN
     TEST ("LA5007J", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PACKAGE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007J2M;
