-- LA5008H2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE H:  OBSOLETE (BY RECOMP. OF DECL.) LIBRARY GENERIC PROCEDURE
--          BODY.

-- SEPARATE FILES ARE:
--   LA5008H0  A LIBRARY GENERIC PROCEDURE DECL AND BODY.
--   LA5008H1  A LIBRARY GENERIC PROCEDURE DECLARATION (LA5008H0).
--   LA5008H2M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PROCEDURE
--   LA5008H0 IS MISSING OR OBSOLETE.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008H1
--   THAT THE BODY OF GENERIC PROCEDURE LA5008H0 IS NOT IN THE SAME
--   COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008H0;

PROCEDURE LA5008H2M IS
BEGIN
     TEST ("LA5008H", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PROCEDURE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008H2M;
