-- LA5007T2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE T:  OBSOLETE (BY RECOMP. OF WITHED UNIT) LIBRARY FUNCTION.

-- SEPARATE FILES ARE:
--   LA5007T0  A LIBRARY FUNCTION.
--   LA5007T1  A LIBRARY FUNCTION.
--   LA5007T2M THE MAIN PROCEDURE.
--   LA5007T3  A LIBRARY FUNCTION (LA5007T0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5007T2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT FUNCTION LA5007T1
--   IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007T1;

PROCEDURE LA5007T2M IS
BEGIN
     TEST ("LA5007T", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY FUNCTION IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007T2M;
