-- LA5008G1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE G:  MISSING SUBUNIT TASK BODY (GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008G0  A LIBRARY GENERIC PACKAGE DECL AND BODY.
--   LA5008G1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF TASK
--   LA5008G0.LA5008G0T IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008G0
--   THAT THE BODY OF SUBUNIT TASK LA5008G0.LA5008G0T IS NOT IN THE SAME
--   COMPILATION FILE AS ITS GENERIC PARENT.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008G0;

PROCEDURE LA5008G1M IS
BEGIN
     TEST ("LA5008G", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT TASK BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008G1M;
