-- LA5007K3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE K:  OBSOLETE (BY RECOMP. OF WITHED UNIT) LIBRARY PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5007K0  A LIBRARY PACKAGE DECLARATION.
--   LA5007K1  A LIBRARY PACKAGE DECL AND BODY.
--   LA5007K2  A LIBRARY PACKAGE DECLARATION (LA5007K0).
--   LA5007K3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PACKAGE LA5007K1
--   IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007K1;

PROCEDURE LA5007K3M IS
BEGIN
     TEST ("LA5007K", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PACKAGE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007K3M;
