-- LA5007R2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE R:  OBSOLETE (BY RECOMP. OF WITHED UNIT) LIBRARY PACKAGE
--          DECLARATION.

-- SEPARATE FILES ARE:
--   LA5007R0  A LIBRARY PACKAGE DECLARATION.
--   LA5007R1  A LIBRARY PACKAGE DECLARATION.
--   LA5007R2M THE MAIN PROCEDURE.
--   LA5007R3  A LIBRARY PACKAGE DECLARATION (LA5007R0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5007R2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT THE DECLARATION OF
--   PACKAGE LA5007R1 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007R1;

PROCEDURE LA5007R2M IS
BEGIN
     TEST ("LA5007R", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PACKAGE DECLARATION IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007R2M;
