-- LA5007P2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE P:  OBSOLETE (BY RECOMP. OF WITHED UNIT) LIBRARY PROCEDURE
--          (SEPARATE) DECLARATION.

-- SEPARATE FILES ARE:
--   LA5007P0  A LIBRARY PROCEDURE DECL AND BODY.
--   LA5007P1  A LIBRARY PROCEDURE DECL AND BODY.
--   LA5007P2M THE MAIN PROCEDURE.
--   LA5007P3  A LIBRARY PROCEDURE DECL AND BODY (LA5007P0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5007P2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT THE DECLARATION OF
--   PROCEDURE LA5007P1 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007P1;

PROCEDURE LA5007P2M IS
BEGIN
     TEST ("LA5007P", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY PROCEDURE DECLARATION IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007P2M;
