-- LA5008N2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE N:  OBSOLETE (BY RECOMP. OF PARENT) SUBUNIT GENERIC PACKAGE
--          BODY (GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008N0  A LIBRARY GENERIC PACKAGE DECL AND BODY,
--             A SUBUNIT GENERIC PACKAGE BODY (LA5008N0.LA5008N0P).
--   LA5008N1  A LIBRARY GENERIC PACKAGE BODY (LA5008N0).
--   LA5008N2M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PACKAGE
--    LA5008N0.LA5008N0P IS MISSING OR OBSOLETE.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008N1
--   THAT THE DECLARATION OF GENERIC PACKAGE LA5008N0 IS NOT IN THE SAME
--   COMPILATION FILE AS ITS BODY.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008N1
--   THAT THE BODY OF GENERIC PACKAGE LA5008N0.LA5008N0P IS NOT IN THE
--   SAME COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008N0;

PROCEDURE LA5008N2M IS
BEGIN
     TEST ("LA5008N", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT GENERIC PACKAGE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008N2M;
