-- LA5008D1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE D:  MISSING SUBUNIT GENERIC PROCEDURE BODY (GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008D0  A LIBRARY GENERIC PROCEDURE DECL AND BODY.
--   LA5008D1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PROCEDURE
--   LA5008D0.LA5008D0P IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008D0
--   THAT THE BODY OF GENERIC PROCEDURE LA5008D0.LA5008D0P IS NOT IN THE
--   SAME COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008D0;

PROCEDURE LA5008D1M IS
BEGIN
     TEST ("LA5008D", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT GENERIC PROCEDURE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008D1M;
