-- LA5001A0.ADA

-- IN THE CASE THAT ELABORATION OF ANY UNITS OCCURS, THIS PACKAGE'S
-- BODY ENSURES THAT THE PROPER FAILURE MESSAGES ARE PRINTED.

-- JBG 6/4/84
-- JRK 9/24/84


PACKAGE LA5001A0 IS

     FUNCTION RF (X : STRING) RETURN INTEGER;

END LA5001A0;


WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY LA5001A0 IS

     FUNCTION RF (X : STRING) RETURN INTEGER IS
     BEGIN
          FAILED (X & " DECLARATION ELABORATED");
          RETURN 0;
     END RF;

BEGIN

     TEST ("LA5001A","INCONSISTENT ELABORATION ORDER OF LIBRARY UNITS");
     FAILED ("LA5001A0 BODY ELABORATED");

END LA5001A0;
