-- LA5008S3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE S:  OBSOLETE (BY RECOMP. OF WITHED GENERIC UNIT) LIBRARY GENERIC
--          PROCEDURE INSTANTIATION.

-- SEPARATE FILES ARE:
--   LA5008S0  A LIBRARY GENERIC PROCEDURE DECL AND BODY.
--   LA5008S1  A LIBRARY GENERIC PROCEDURE DECL AND BODY.
--   LA5008S2  A LIBRARY GENERIC PROCEDURE INSTANTIATION.
--   LA5008S3M THE MAIN PROCEDURE.
--   LA5008S4  A LIBRARY GENERIC PROCEDURE DECL AND BODY (LA5008S0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008S3M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008S2
--   IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008S2;

PROCEDURE LA5008S3M IS
BEGIN
     TEST ("LA5008S", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PROCEDURE INSTANTIATION IS " &
                      "OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008S3M;
