-- LA5007I3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE I:  OBSOLETE (BY RECOMP. OF WITHED UNIT) LIBRARY FUNCTION BODY
--          (SEPARATE DECL.).

-- SEPARATE FILES ARE:
--   LA5007I0  A LIBRARY PACKAGE DECLARATION.
--   LA5007I1  A LIBRARY FUNCTION DECL AND BODY.
--   LA5007I2  A LIBRARY PACKAGE DECLARATION (LA5007I0).
--   LA5007I3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF FUNCTION LA5007I1
--   IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007I1;

PROCEDURE LA5007I3M IS
BEGIN
     TEST ("LA5007I", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY FUNCTION BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007I3M;
