-- LA5007L4M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE L:  OBSOLETE (BY RECOMP. OF WITHED UNIT) SUBUNIT PROCEDURE BODY.

-- SEPARATE FILES ARE:
--   LA5007L0  A LIBRARY PACKAGE DECLARATION.
--   LA5007L1  A LIBRARY PROCEDURE.
--   LA5007L2  A SUBUNIT PROCEDURE BODY (LA5007L1.LA5007L2).
--   LA5007L3  A LIBRARY PACKAGE DECLARATION (LA5007L0).
--   LA5007L4M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PROCEDURE
--   LA5007L1.LA5007L2 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007L1;

PROCEDURE LA5007L4M IS
BEGIN
     TEST ("LA5007L", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT PROCEDURE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007L4M;
