-- LA5007D1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE D:  MISSING SUBUNIT PROCEDURE BODY.

-- SEPARATE FILES ARE:
--   LA5007D0  A LIBRARY PROCEDURE DECL AND BODY.
--   LA5007D1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF PROCEDURE
--   LA5007D0.LA5007D0P IS MISSING.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007D0;

PROCEDURE LA5007D1M IS
BEGIN
     TEST ("LA5007D", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT PROCEDURE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007D1M;
