-- LA5008Q2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE Q:  OBSOLETE (BY RECOMP. OF WITHED GENERIC UNIT) LIBRARY GENERIC
--          FUNCTION DECLARATION.

-- SEPARATE FILES ARE:
--   LA5008Q0  A LIBRARY GENERIC FUNCTION DECL AND BODY.
--   LA5008Q1  A LIBRARY GENERIC FUNCTION DECL AND BODY.
--   LA5008Q2M THE MAIN PROCEDURE.
--   LA5008Q3  A LIBRARY GENERIC FUNCTION DECL AND BODY (LA5008Q0).

-- EXPECT A LINK-TIME ERROR MESSAGE THAT PROCEDURE LA5008Q2M IS
--   MISSING OR OBSOLETE.
-- OPTIONALLY EXPECT A LINK-TIME ERROR MESSAGE THAT THE DECLARATION OF
--   GENERIC FUNCTION LA5008Q1 IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008Q1;

PROCEDURE LA5008Q2M IS
BEGIN
     TEST ("LA5008Q", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC FUNCTION DECLARATION IS " &
                      "OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008Q2M;
