-- LA5008J2M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE J:  OBSOLETE (BY RECOMP. OF DECL.) LIBRARY GENERIC PACKAGE BODY.

-- SEPARATE FILES ARE:
--   LA5008J0  A LIBRARY GENERIC PACKAGE DECL AND BODY.
--   LA5008J1  A LIBRARY GENERIC PACKAGE DECLARATION (LA5008J0).
--   LA5008J2M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PACKAGE
--   LA5008J0 IS MISSING OR OBSOLETE.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008J1
--   THAT THE BODY OF GENERIC PACKAGE LA5008J0 IS NOT IN THE SAME
--   COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008J0;

PROCEDURE LA5008J2M IS
BEGIN
     TEST ("LA5008J", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PACKAGE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008J2M;
