-- LA5007M3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   NON-GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE M:  OBSOLETE (BY RECOMP. OF PARENT) SUBUNIT FUNCTION BODY.

-- SEPARATE FILES ARE:
--   LA5007M0  A LIBRARY FUNCTION DECL AND BODY.
--   LA5007M1  A SUBUNIT FUNCTION BODY (LA5007M0.LA5007M1).
--   LA5007M2  A LIBRARY FUNCTION BODY (LA5007M0).
--   LA5007M3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF FUNCTION
--   LA5007M0.LA5007M1 IS MISSING OR OBSOLETE.

-- JRK 6/3/85

WITH REPORT; USE REPORT;
WITH LA5007M0;

PROCEDURE LA5007M3M IS
BEGIN
     TEST ("LA5007M", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT FUNCTION BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5007M3M;
