-- LA5008B1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE B:  MISSING LIBRARY GENERIC FUNCTION BODY.

-- SEPARATE FILES ARE:
--   LA5008B0  A LIBRARY GENERIC FUNCTION DECLARATION.
--   LA5008B1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC FUNCTION
--   LA5008B0 IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008B0
--   THAT THE BODY OF GENERIC FUNCTION LA5008B0 IS NOT IN THE SAME
--   COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008B0;

PROCEDURE LA5008B1M IS
BEGIN
     TEST ("LA5008B", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC FUNCTION BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008B1M;
