-- LA5008L3M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE L:  OBSOLETE (BY RECOMP. OF WITHED GENERIC UNIT) SUBUNIT GENERIC
--          PROCEDURE BODY (NON-GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008L0  A LIBRARY GENERIC PACKAGE DECLARATION.
--   LA5008L1  A LIBRARY PROCEDURE,
--             A SUBUNIT GENERIC PROCEDURE BODY (LA5008L1.LA5008L1P).
--   LA5008L2  A LIBRARY GENERIC PACKAGE DECLARATION (LA5008L0).
--   LA5008L3M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PROCEDURE
--   LA5008L1.LA5008L1P IS MISSING OR OBSOLETE.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008L1;

PROCEDURE LA5008L3M IS
BEGIN
     TEST ("LA5008L", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT GENERIC PROCEDURE BODY IS OBSOLETE");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008L3M;
