-- LA5008A1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE A:  MISSING LIBRARY GENERIC PROCEDURE BODY.

-- SEPARATE FILES ARE:
--   LA5008A0  A LIBRARY GENERIC PROCEDURE DECLARATION.
--   LA5008A1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC PROCEDURE
--   LA5008A0 IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008A0
--   THAT THE BODY OF GENERIC PROCEDURE LA5008A0 IS NOT IN THE SAME
--   COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008A0;

PROCEDURE LA5008A1M IS
BEGIN
     TEST ("LA5008A", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "LIBRARY GENERIC PROCEDURE BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008A1M;
