-- LA5008E1M.ADA

-- CHECK THAT EXECUTION OF A MAIN PROGRAM IS NOT ALLOWED IF A NEEDED
--   GENERIC UNIT IS MISSING OR OBSOLETE.

-- CASE E:  MISSING SUBUNIT GENERIC FUNCTION BODY (NON-GENERIC PARENT).

-- SEPARATE FILES ARE:
--   LA5008E0  A LIBRARY FUNCTION.
--   LA5008E1M THE MAIN PROCEDURE.

-- EXPECT A LINK-TIME ERROR MESSAGE THAT THE BODY OF GENERIC FUNCTION
--   LA5008E0.LA5008E0F IS MISSING.
-- ALTERNATIVELY, EXPECT A COMPILE-TIME ERROR MESSAGE FOR FILE LA5008E0
--   THAT THE BODY OF GENERIC FUNCTION LA5008E0.LA5008E0F IS NOT IN THE
--   SAME COMPILATION FILE AS ITS DECLARATION.

-- JRK 11/1/85

WITH REPORT; USE REPORT;
WITH LA5008E0;

PROCEDURE LA5008E1M IS
BEGIN
     TEST ("LA5008E", "CHECK THAT MAIN PROGRAM NOT EXECUTED IF A " &
                      "SUBUNIT GENERIC FUNCTION BODY IS MISSING");

     FAILED ("SHOULD NOT EXECUTE");

     RESULT;
END LA5008E1M;
