PACKAGE REPORT IS
PROCEDURE TEST(NAME:STRING;DESC:STRING);
PROCEDURE FAILED(MSG:STRING);
PROCEDURE RESULT;
FUNCTION IDENT_INT(X:INTEGER)RETURN INTEGER;
FUNCTION IDENT_BOOL(X:BOOLEAN)RETURN BOOLEAN;
FUNCTION IDENT_CHAR(X:CHARACTER)RETURN CHARACTER;
FUNCTION IDENT_STR(X:STRING)RETURN STRING;
END REPORT;
